### ISSUE TITLE
Index intersection

### ISSUE THREAD

**Issue by vadimkantorov** [facebookresearch/faiss#10]
I have a few thousand sets of vectors for which I need to answer `ClosestPairOfPoints(A, B)` queries, that is find element `a` from `A` and `b` from `B` that minimize `d(a, b)`. Is there a way I could support such queries with Faiss?

Thanks!

**Comment by jegou** [comment]
Faiss is not specifically designed for this, but you can easily use it to compute
min d(a,b)  for all a,
and then task the min over a

**Comment by vadimkantorov** [comment]
Thanks for the lightning-fast answer :) Sure, I was wondering if one can do it in sub-linear time.

**Comment by jegou** [comment]
Right. Yet, for this size of the problem (very small considering that Faiss is typically designed for dozen millions to billions of vectors), brute-force will certainly be the fastest way to compute the `ClosestPairOfPoints`, especially if you use the GPU implementation.
