### ISSUE TITLE
How to get the PQ binary code of feature directly?

### ISSUE THREAD

**Issue by welfred** [facebookresearch/faiss#100]
When I use "add_with_ids" function of GpuIndexIVFPQ class to add features into index, but it didn't return any PQ binary codes of these features. It disables me to save binary codes to my database. I need to use "write_index" to a file to get the codes. It doesn't make sense. Any suggestion?

**Comment by mdouze** [comment]
Hi 

What are you trying to do? If you just want to compute codes see 

https://github.com/facebookresearch/faiss/wiki/Faiss-building-blocks#pq-encoding--decoding

**Comment by welfred** [comment]
ok, thank you!
