### ISSUE TITLE
IndexPreTransform.cpp:163: Error: 'is_trained' failed

### ISSUE THREAD

**Issue by xiaohujecky** [facebookresearch/faiss#1005]
# Summary

Error when building the index.  
# Platform
Linux Server

OS: 
Linux version 4.15.0-66-generic (buildd@lgw01-amd64-050) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #75~16.04.1-Ubuntu SMP Tue Oct 1 14:01:08 UTC 2019
Faiss version: 

Faiss compilation options: 
Faiss was installed by 
`conda install faiss-gpu cudatoolkit=9.0 -c pytorch`

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

 

when I build the index with:
`
        self.index = faiss.index_factory(self.fea_dims, 'PCA128,IVF2048,PQ16')
        self.index.add(np.ascontiguousarray(feas))
`
it complained like :
File "/home/alth/anaconda3/lib/python3.7/site-packages/faiss/__init__.py", line 123, in replacement_add
    self.add_c(n, swig_ptr(x))
  File "/home/alth/anaconda3/lib/python3.7/site-packages/faiss/swigfaiss_avx2.py", line 1956, in add
    return _swigfaiss_avx2.IndexPreTransform_add(self, n, x)
RuntimeError: Error in virtual void faiss::IndexPreTransform::add(faiss::Index::idx_t, const float*) at IndexPreTransform.cpp:163: Error: 'is_trained' failed

**Comment by beauby** [comment]
You need to train the index first (using the `train()` method).
