### ISSUE TITLE
index.setNumProbes not working in benchmark scripts

### ISSUE THREAD

**Issue by lujq96** [facebookresearch/faiss#1007]
# Summary

In benchs/bench_gpu_1bn.py and benchs/bench_gpu_sift1m.py (I only tried these two) I got same recalls under different nprobes.  I add print index.getNumProbes() after index.setNumProbes(nprobe) and the return is always 1, showing the set command doesn't work.

# Platform

OS: Ubuntu

Faiss version: I use conda install faiss-gpu cudatoolkit=10.0 -c pytorch to install it today.

Interface: 
- [2.7] Python

# Reproduction instructions

just run 
```
python bench_gpu_1bn.py  Deep1B OPQ20_80,IVF262144,PQ20 -nnn 10 -R 2 -ngpu 4 -altadd -noptables -tempmem $[1024*1024*1024]
```
or
```
python bench_gpu_sift1m.py
```

**Comment by mdouze** [comment]
right, I can repro the error.

**Comment by mdouze** [comment]
The bug is here: 
https://github.com/facebookresearch/faiss/blob/master/gpu/GpuIndexIVF.cu#L197
it should be `this->nprobe = nprobe`.

**Comment by mdouze** [comment]
Fixed in FB internal. We will roll out an update to github version with a fix.
Thanks for flagging.

**Comment by lujq96** [comment]
Thanks!
