### ISSUE TITLE
I met an error in testing the BLAS/Lapack？

### ISSUE THREAD

**Issue by yyy007** [facebookresearch/faiss#101]
At the beginning of using Faiss, when I run './tests/test_blas', I got an error below:
![testblas](https://cloud.githubusercontent.com/assets/17923170/25578276/9621ae74-2e9f-11e7-8fe5-4da271f6febf.jpg)
What is it mean, and how can I fix it? Thank you!

**Comment by mdouze** [comment]
Hi 

This is not an error. It just means Lapack uses 32-bit integers.

**Comment by vtgist** [comment]
so what's the significance of this message. Should we try to make lapack use 64-bit integer.

**Comment by mdouze** [comment]
Hi
No it matters only if you have to use 64-bit ints for an external reason.

**Comment by oldtree** [comment]
thanks !

**Comment by whutcstczw** [comment]
makes confued!
