### ISSUE TITLE
Internal Library crash when searching with small numbers of vectors.

### ISSUE THREAD

**Issue by triclops200** [facebookresearch/faiss#1010]
# Summary

# Platform

OS: Ubuntu Linux 19.04

Faiss version: 8bc09261f4f4cf66371e14f8f9cef0b4a904e84a
Faiss compilation options: no-cuda
Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

I'm creating a IndexIVFFlat at 512 dimensions with 2048 probe points. I'm inserting 2k vectors then doing a search and the code crashes. This is the resulting error

```IndexPQ.cpp:861: void faiss::{anonymous}::MinSumK<T, SSA, use_seen>::run(const T*, int64_t, T*, int64_t*) [with T = float; SSA = faiss::{anonymous}::SemiSortedArray<float>; bool use_seen = false; int64_t = long int]: Assertion `heap_size > 0' failed.```

**Comment by mdouze** [comment]
So that's an `IndexIVFFlat` with `MultiIndexQuantizer` quantizer. 
That's an interesting bug, which is probably due to the data distribution. 
Would it be possible for you to share the code + actual vectors this bug shows up?

**Comment by triclops200** [comment]
Sure, take your demo_imi_flat.cpp and change nb to 1000 and you'll encounter the same error.

**Comment by triclops200** [comment]
Any updates?

**Comment by mdouze** [comment]
Yes I could repro the issue. Marking this as an enhancement.

**Comment by mdouze** [comment]
Should be fixed by #1673
