### ISSUE TITLE
Faiss clustering does not use all cpu cores. 

### ISSUE THREAD

**Issue by midhunharikumar** [facebookresearch/faiss#1012]
# Summary

Faiss CPU clustering does not use all cores. Monitoring CPU usage it seems to be using only one core at 100%. Is there additional dependencies that i have to install ? MKL is install in my ec2 instance.

# Platform

Ubuntu 16.04 EC2 instance.

OS: ubuntu 16.04
Faiss version: 1.6.0
Faiss compilation options: conda install

Running on:
CPU

Interface: 
Python

# Reproduction instructions

Install with conda

conda install faiss-cpu -c pytorch

**Comment by mdouze** [comment]
What is the value of `faiss.omp_get_max_threads()` before running the clustering?

**Comment by midhunharikumar** [comment]
This issue was resolved. Turns out my installation was bad. Reinstall made it work.
