### ISSUE TITLE
Faiss assertion 'mallocCurrent_ >= size' failed in void faiss::gpu::StackDeviceMemory::Stack::returnAlloc(char*, size_t, cudaStream_t) at gpu/utils/StackDeviceMemory.cpp:141

### ISSUE THREAD

**Issue by hws912** [facebookresearch/faiss#1014]
Error:
Faiss assertion 'mallocCurrent_ >= size' failed in void faiss::gpu::StackDeviceMemory::Stack::returnAlloc(char*, size_t, cudaStream_t) at gpu/utils/StackDeviceMemory.cpp:141

This error happened occasionally.

Running on:
- [x] GPU

Interface: 
- [x] C++

# Reproduction instructions
index type: GpuIndexIVFPQ
dims: 64
nlist: 8192
nprobe: 1024
subQuantizers: 64
bitsPerCode: 8
metric: METRIC_L2

index size: 85 million
training size: 2097152

code:
```
    std::vector<dist_t> distances(k);
    std::vector<faiss::Index::idx_t> labels(k);
    gpu_index_->search(1, item->data(), k, distances.data(), labels.data());
```

**Comment by wickedfoo** [comment]
Are you calling the index from multiple CPU threads concurrently?

**Comment by hws912** [comment]
> Are you calling the index from multiple CPU threads concurrently?

Yes, I have seen this issue: #321 
**a single index (CPU or GPU) can only be used by a single CPU thread at any given time.**

But I have called the index(CPU) from multiple threads concurrently and core-dump never happened. Is it okay for CPU index?

**Comment by mdouze** [comment]
About threading of GPU and CPU indexes: 

https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls

**Comment by hws912** [comment]
> About threading of GPU and CPU indexes:
> 
> https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls

Got it, thanks!
