### ISSUE TITLE
why faiss->search() return -1 for I?

### ISSUE THREAD

**Issue by jiangxiaohe** [facebookresearch/faiss#1016]
# Summary

when I use index>search(), I found the returned I is "-1", is there anythings wrong? 

I am sure that no feature id is -1.

The platform is Jetson TX2 while system is Ubuntu 16.04.

the main code are as follows:

```
faiss::IndexFlatIP quantizer(feature_dim); 
faiss::IndexIVFFlat index(&quantizer, feature_dim, num_centroids, faiss::METRIC_INNER_PRODUCT);
index->search();
```

thanks for your attention!

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

**Comment by Enet4** [comment]
That appears to be already covered by the [FAQ](https://github.com/facebookresearch/faiss/wiki/FAQ#what-does-it-mean-when-a-search-returns--1-ids):

> To perform searches in an IndexIVF, the algorithm scans a finite set of elements. If there are not enough elements to fill the result list, the missing results are set to -1. You can increase the number of elements that are visited with `ParameterSpace().set_index_parameter(index, 'nprobe', 100)`. The parameter `nprobe` adjusts the speed/accuracy tradeoff of the search.

**Comment by jiangxiaohe** [comment]
But I am confused that I set the k=1 in the search function, why not return one ?

**Comment by beauby** [comment]
@jiangxiaohe You're using an index that performs non-exhaustive search. In certain circumstances, it may find less than `k` candidates. You can increase the `nprobe` parameter or decrease the `num_centroids` parameters to avoid this, depending on your data.

**Comment by jiangxiaohe** [comment]
thanks, I have got it !

**Comment by lianuo** [comment]
@jiangxiaohe Hi, I notice that you have compile and run faiss on tx2 successfully. could you give us a manual on how to complile faiss on tx2? thank you !
