### ISSUE TITLE
Very low metrics for Quantized models

### ISSUE THREAD

**Issue by Arjunsankarlal** [facebookresearch/faiss#1018]
I have 100k vectors of 768 dimensions, I am using IndexIVFFlat to find the nearest neighbours
> quantizer = faiss.IndexFlatL2(d)
> index = faiss.IndexIVFFlat(quantizer, d, nlist)

with this the model size became 31 MB. So I tried quantizing the model with,

> d = 768
> nlist = 10
> quantizer = faiss.IndexFlatL2(d)
> index = faiss.IndexIVFPQ(quantizer, d, nlist, 3, 8)

Now the model size is 12.1 MB and the results are ok compared to the uncompressed one, but there is a significance drop in the distance calculated between the points. 

For the same input the output before quantizing,
Indices : [2, 1657, 2873, 1839, 3882, 2166, 8531, 7543, 4508, 9374]
Distances : [0.0, 185.27962, 186.81586, 202.15588, 203.5038, 218.45499, 219.3068, 222.31326, 224.09625, 228.50064]

the output after quantizing,
Indices : [2, 3882, 2873, 1637, 1370, 3621, 3638, 3293, 3683, 4241]
Distances : [-3.8146973e-06, 19.403374, 48.64019, 52.57158, 54.341316, 56.17192, 56.45891, 56.45891, 57.326767, 57.92022]

Why is this happening ? Also I would like to clarify few things on quantization,

1. faiss.IndexIVFPQ(quantizer, d, nlist, 3, 8) with this now the dimensions of the vector stored in the index would be 768/3 = 256. And instead of 32 bit float the numbers would be quantized to 8 bit numbers right ? 
2. Also while inference, I reconstruct the vectors from the index and pass it as the input for search, is it influencing the less distance output?
3. How to get the quantized vectors (with reduced dimension) from the index ?
4. Can we search with the quantized (with reduced dimension) vectors ?
5. Also why the index output vectors of dimension 768 during reconstruction when it is quantized ?

Kindly correct me if I am wrong. Any or quantization or methods I can try for better accuracy ?

OS: macOS 10.13.3 
Faiss version: Latest
Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

Sorry for the long post. And thanks for the great work ❤️

**Comment by mdouze** [comment]
Distance computations are not very accurate with the PQ variants, see https://hal.inria.fr/inria-00514462/document section |||.C 
The order of the results is more relevant. 
If you need more accurate distance estimates, you can use the ScalarQuantizer, but it will require more memory.
1. yes, you go from 768 * sizeof(float) to 3 bytes.

For the rest of the questions: there is no dimensionality reduction.

**Comment by Arjunsankarlal** [comment]
Thanks for the quick response @mdouze!
