### ISSUE TITLE
`index_factory` normalization step?

### ISSUE THREAD

**Issue by bkj** [facebookresearch/faiss#102]
I see I can define an index that applies PCA and then exhaustive L2 search via

```
index = faiss.index_factory(128, "PCA80,Flat")
```

Is it possible to add a normalization step as well?  I'd like to L2 normalize the output of the PCA before adding to the flat index -- would maybe look something like:

```
index = faiss.index_factory(128, "PCA80,l2_normalize,Flat")
```

**Comment by mdouze** [comment]
Hi 

There is no `VectorTransform` that does L2 normalization. Feel free to add it, build it in the `index_factory` and submit a pull request.

**Comment by mdouze** [comment]
Implemented in latest version, see `index_factory` `L2norm` option
