### ISSUE TITLE
g++ -std=c++11 -DFINTEGER=int  -fopenmp  -fPIC -m64 -Wno-sign-compare -g -O3 -Wall -Wextra -std=c++0x -mpopcnt -msse4 -o demo_sift1M demo_sift1M.cpp -fopenmp   -lopenblas    -lfaiss

### ISSUE THREAD

**Issue by 2012fang** [facebookresearch/faiss#1027]
demo_sift1M.cpp: In function ‘int main()’:
demo_sift1M.cpp:114:17: error: ‘index_factory’ is not a member of ‘faiss’
         index = faiss::index_factory(d, index_key);
                 ^
In file included from /usr/include/c++/4.8.2/cassert:43:0,
                 from demo_sift1M.cpp:13:
demo_sift1M.cpp:205:38: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
         assert (selected_params.size() >= 0 ||

**Comment by 2012fang** [comment]
add a new line in demo_sift1M.cpp
#include <faiss/index_factory.h>

**Comment by mdouze** [comment]
Thanks for flagging. Fixed.
