### ISSUE TITLE
Could I use nbits_per_idx > 8 in IVFPQ?

### ISSUE THREAD

**Issue by chasingegg** [facebookresearch/faiss#1028]
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

Here I wanna train a codebook with 1024 centroids per subvector(which needs 10 bytes), but it seems that `nbits_per_idx` could not be bigger than 8 when I use the python api, `faiss.IndexIVFPQ(quantizer, d, nlist, m, 10)` . So how can I use a larger `nbits_per_idx`? Is that enough to simply disable the check ` FAISS_THROW_IF_NOT (nbits_per_idx <= 8);` in `IndexIVFPQ.cpp`.

**Comment by mdouze** [comment]
No it is not, the check is there for a reason :-)
`IndexIVFPQ` has not been upgraded to support numbers of bits per vector different from 8. It should not be very hard though.
Marking this as an enhancement.

**Comment by chasingegg** [comment]
Actually it is a little bit weird to hardcode the number of bits per vector, hope you guys would release a new version soon.

**Comment by dugu9sword** [comment]
Hello, if nbits is always set to 8, will the number of centroids have to be smaller than 256? thanks~ @mdouze

**Comment by mdouze** [comment]
I don't understand the question.

**Comment by dugu9sword** [comment]
> I don't understand the question.

Since `nbits_per_idx` could not be bigger than 8,  how can I train a codebook with 512 centroids per subvector(which needs 9 bits)? Thanks

**Comment by mdouze** [comment]
You can't. See here what is supported:
https://github.com/facebookresearch/faiss/wiki/FAQ#is-pq-encoding-with-more-or-less-than-8-bits-per-components-supported

**Comment by mdouze** [comment]
Supported in 1.6.3.

**Comment by AutumnZ-94** [comment]
I notice that `FAISS_THROW_IF_NOT (nbits_per_idx <= 8);`  in `IndexIVFPQ.cpp` still exists after 1.6.1 tags. should I manually comment this line?

**Comment by AutumnZ-94** [comment]
> Supported in 1.6.3.

I notice that `FAISS_THROW_IF_NOT (nbits_per_idx <= 8);`  in `IndexIVFPQ.cpp` still exists after 1.6.3 tags. 

Should I manually comment this line?

**Comment by physicsrob** [comment]
I'm getting `IndexIVFPQ.cpp:44: Error: 'nbits_per_idx <= 8' failed` while using version 1.7.0.  It seems that the FAQ is inconsistent with the code?

**Comment by AutumnZ-94** [comment]
> > Supported in 1.6.3.
> 
> I notice that `FAISS_THROW_IF_NOT (nbits_per_idx <= 8);` in `IndexIVFPQ.cpp` still exists after 1.6.3 tags.
> 
> Should I manually comment this line?

Remove this line and train with c++ API works, 

BTW nbits > 8 is only supported on cpu training, and training time significantly increase,( 50M, 256D trainset，[nbits=8 10min], [nbits=12 120min] on my test)

**Comment by rajharshiitb** [comment]
@AutumnZ-94 How do you remove that line? I can't find IndexIVFPQ.cpp in my conda environment. 
Thanks

**Comment by gmberton** [comment]
@mdouze me and others above are still getting that error with versions >=1.6.3 (I'm using 1.7.2). Is there a way to solve this?
Specifically, I am getting `IndexIVFPQ 64 11 Error in faiss::IndexIVFPQ::IndexIVFPQ(faiss::Index*, size_t, size_t, size_t, size_t, faiss::MetricType) at /project/faiss/faiss/IndexIVFPQ.cpp:47: Error: 'nbits_per_idx <= 8' failed`

**Comment by mdouze** [comment]
Please use a more recent version of Faiss.

**Comment by gmberton** [comment]
@mdouze I tried with versions 1.6.3, 1.7.0, 1.7.2, 1.7.3 and it doesn't work. Did you fix it only for C++, and not for Python?
This is my script
```
import faiss
import numpy as np
DIM = 512
db_feates = np.random.randn(1000, DIM)
q_features = np.random.randn(100, DIM)
coarse_quantizer = faiss.IndexFlatL2(DIM)
faiss_index = faiss.IndexIVFPQ(coarse_quantizer, DIM, 1000, 64, 9)
```

**Comment by ga1i13o** [comment]
I am experiencing the same issue as @gmberton, @physicsrob and @rajharshiitb
