### ISSUE TITLE
I can't run the gpu demo "demo_ivfpq_indexing_gpu"

### ISSUE THREAD

**Issue by yyy007** [facebookresearch/faiss#103]
After 'make' the gpu subdirectory, I run the "demo_ivfpq_indexing_gpu", but I got an error below:
![gpudemo_error](https://cloud.githubusercontent.com/assets/17923170/25621846/26670656-2f85-11e7-9ea2-b3e9a42f4fc3.png)
The system is Ubuntn 14.04, I have installed the 'cuda-8.0' and nvidia driver, the gpu is two Tesla K40c.
Why I got this error, and how can I fix it? Thank you!

**Comment by wickedfoo** [comment]
The CUDA libs don't seem to be in your LD_LIBRARY_PATH? Add the directory with the CUDA libs to LD_LIBRARY_PATH.

**Comment by yyy007** [comment]
Thank you for replying me, it start working! Thank you!
