### ISSUE TITLE
Number of probes for multi-GPU index

### ISSUE THREAD

**Issue by bittremieux** [facebookresearch/faiss#1030]
How can you set the number of probes to use during querying for a multi-GPU index using the Python API?

For a CPU-based index you have to use `index.nprobe = x`, whereas for a GPU-based `index.setNumProbes(x)` should be used, which is already a bit confusing.
But `setNumProbes` doesn't work on a multi-GPU index (created using `index_cpu_to_all_gpus`). Similarly, `setNumProbes` doesn't seem to work on each of the sub-indexes of the multi-GPU index either.

**Comment by mdouze** [comment]
Right, there is currently a bug in the `setNumProbes` function, see #1007 

In the meantime and from now on you can set the `nprobe` directly for `GpuIndexIVF` sub-classes.

**Comment by bittremieux** [comment]
Apologies for the duplicate issue.

To clarify, for a multi-GPU index I should set `nprobe` on each of the sub-indexes? Example:

```
for i in range(multi_index.count()):
    multi_index.at(i).nprobe = nprobe
```

**Comment by mdouze** [comment]
Yes, but the code above should be changed to 
```
index = faiss.read_index(filename)
co = faiss.GpuMultipleClonerOptions()
multi_index = faiss.index_cpu_to_all_gpus(index, co)
for i in range(multi_index.count()):
    faiss.downcast_index(multi_index.at(i)).nprobe = nprobe
```
see the WARNING here: https://github.com/facebookresearch/faiss/wiki/FAQ#how-can-i-set-nprobe-on-an-opaque-index

**Comment by bittremieux** [comment]
Thank you for the detailed help, setting the number of probes that way indeed works as expected.
