### ISSUE TITLE
To compare with get_nns_by_vector of Annoy Similarly Search

### ISSUE THREAD

**Issue by SGA-cai-sanru** [facebookresearch/faiss#1036]
# Summary

The result of using euclidean distance to do similarity search that come from Annoy and Faiss.
In few data the result in index is most the same however distance is different .  In a little more data the result whatever index or distance are very different.

# Platform

OS: ubuntu 18.4

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by wickedfoo** [comment]
The distances reported for L2 are distances squared. e.g.,

0.7826493382453918^2 = 0.6125...

**Comment by wickedfoo** [comment]
Also you are comparing two different approximate k-NN implementations (I don't know what algorithm AnnoyIndex is using), so there is no guarantee that they would return the same thing as they are both approximate. 

In fact, the approximate Faiss index becomes an inefficient implementation of IndexFlat (an exact, brute force search) when nprobe == nlist, which is what you seem to be using.

**Comment by SGA-cai-sanru** [comment]
Our team review feasibility of changing similarly search from annoy to faiss for our project.
My boss ask me 「why the result is so different」.
Although I also agree your argument , why would they must return the same thing, but i must explain the result.
I do not know where is different in the algorithm between faiss and annoy . So i add issue for my question. I wish can get some clue .

**Comment by SGA-cai-sanru** [comment]
Sorry, I research Faiss wiki ,「faiss.METRIC_L2」is using Mahalanobis distance .  Does 「faiss.METRIC_L2」also support Euclidean distance? If 「faiss.METRIC_L2」does not support Euclidean distance, what kind of metric type in Faiss support  Euclidean distance?

Using the same sample source code. I create the feature vector that dimension=512, and do similarly search again. I think「 faiss.METRIC_INNER_PRODUCT」is using cosine similarity  and Annoy is using 
cosine similarity, too. But the result whatever index or distance are very different.
512-dot: sample data = 100 pieces 
     from annoy : 
           index : [50, 55, 99, 5, 60, 85, 96, 88, 47, 33]
           distance: [1.0, 0.09054122120141983, 0.0820605605840683, 0.06430304050445557, 0.0625334307551384, 0.058647520840168, 0.05805570259690285, 0.055907901376485825, 0.054843321442604065, 0.05467139557003975]
     from faiss : 
           index :  [[50 55  5 85 96 47 34 87 28 41]]
           distance:[[1.         0.09054123 0.06430303 0.05864753 0.05805567 0.05484333  0.05434781 0.05389509 0.05305935 0.04639321]]

512-dot: sample data = 300 pieces 
     from annoy : 
           index : [150, 69, 189, 177, 176, 161, 96, 87, 199, 50]
           distance: [1.0, 0.10086497664451599, 0.10029798746109009, 0.09646575897932053, 0.09121981263160706, 0.09091666340827942, 0.08724302053451538, 0.08587765693664551, 0.08555935323238373, 0.0850575715303421]
     from faiss : 
           index :  [[150 189 177 176 161  87 199  50 291 184]]
           distance:[[1.         0.10029798 0.09646577 0.09121983 0.09091666 0.08587764  0.08555934 0.08505756 0.08174883 0.08058398]]

[Faiss]
dimension = 512
metric type = faiss.METRIC_INNER_PRODUCT
# create index
quantizer = faiss.IndexFlatL2(xb.shape[1])
index = faiss.IndexIVFFlat(quantizer, xb.shape[1], nlist, faiss.METRIC_INNER_PRODUCT)

[Annoy]
dimension = 512
# create index
annoy_data = AnnoyIndex(dimension, metric='dot')

**Comment by SGA-cai-sanru** [comment]
I have a solution for this issue. Thanks!!
