### ISSUE TITLE
Really strange inconsistent problem

### ISSUE THREAD

**Issue by hxsnow10** [facebookresearch/faiss#104]
i use faiss to do fast word2vec similar search
following is code.
vec.txt is standard google w2v txt。
two similar code, when index/data should unchanged, but work differently.
 
**INIT LAST1 work
INIT LAST2 core dumped
when LAST2 work just after LAST1**
![qq 20170502222913](https://cloud.githubusercontent.com/assets/5416620/25622409/e6d40410-2f86-11e7-8179-1cdc2577e9ef.png)

```python
#encoding=utf-8
import numpy
import numpy as np
import faiss

s=None
def normalized(a, axis=-1, order=2):
    # np.sum(np.abs(a)**2,axis=-1)**(1./2)
    #print 'a=',a
    #print 'norm=',np.linalg.norm(a, order, axis)
    l2 = np.atleast_1d(np.linalg.norm(a, order, axis))
    l2[l2==0] = 1 
    #print l2
    return a / np.expand_dims(l2, axis)
from copy import deepcopy
class W2vFast():
    '''for quick simikar search'''

    def __init__(self, w2v_path, index_type='fast'):
        self.xb=None
        self.index_strange=None
        self.word_vecs, _, self.d=self.load(w2v_path)
        self.build_index(self.word_vecs, self.d, index_type)
        self.build_index(self.word_vecs, self.d, index_type)
        print 'INIT LAST2' , self.index_strange.search(self.xb[-5:],4)

    def load(self,w2v_path):
        rval={}
        ii=open(w2v_path,'r')
        N,d=ii.readline().strip().split()
        N,d=int(N), int(d)
        for line in ii:
            s=line.strip().split()
            w=s[0]
            v=numpy.array(s[1:],dtype=numpy.float32)
            #v=normalized(v)[0]
            rval[w]=v*100
        ii.close()
        return rval,N,d

    def build_index(self, wv, d, index_type='fast'):
        '''
        wv是一个字典,d是向量长度
        '''

        self.int2word={k:key for k,key in enumerate(wv.keys())}
        self.word2int={key:k for k,key in enumerate(wv.keys())}
        
        xb=numpy.array(wv.values())#不支持float16
        
        
        if index_type=='accurate':
            index = faiss.IndexFlatL2(d)
            index.add(xb)
        elif index_type=='fast':
            d=100
            nlist = 100# ?
            quantizer = faiss.IndexFlatL2(d)
            index = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_L2)
            index.train(xb)
            index.add(xb)
        elif index_type=='compress':
            nlist = 100#?
            m = 8                      # number of bytes per vector
            quantizer = faiss.IndexFlatL2(d)  # this remains the same
            index = faiss.IndexIVFPQ(quantizer, d, nlist, m, 8)
            # 8 specifies that each sub-vector is encoded as 8 bits
            index.train(xb)
            index.add(xb)
        self.index_type=index_type
        self.index_strange = index
        self.xb=xb
        print 'INIT LAST1' , self.index_strange.search(self.xb[-5:],4)
        print 'INIT LAST1.1' , self.index_strange.search(self.xb[-5:],4)


    def index_search(self, v, k, nprobe=1):
        v=np.array([v,v,v],dtype=numpy.float32)
        if not nprobe:# ?
            self.index.nprobe=nprobe
        print self.index
        print self.index.ntotal
        D,I=self.index.search(v,k)
        return list(I[0])

    def search(self, w, k, nprobe=10):
        if w not in self.word_vecs:
            return []
        v=self.word_vecs[w]
        s=self.index_search(v,k,nprobe)
        words=[self.int2word[i] for i in s]
        return words

    def add_wv(self, word, vec):#Next Todo
        it=len(self.int2word)
        self.int2word[it]=word
        self.word2it[word]=it
        self.index.add(np.array([vec],dtype=numpy.float16))


if __name__=='__main__':
    #model=W2vFast('vec.txt','accurate')
    model=W2vFast('vec.txt')
    print 'strange damn shit'
    print model.index_strange.search(model.xb[-5:],4)
    #for w in model.search('喜欢',10):
    #    print w
    #model.add_wv
    while true:
        word=raw_input('Input word:')
        k=raw_input('Input K:')
        word=word.strip()
        k=int(k.strip())
        for word in self.search(word,k):
            print word

```

**Sorry for my possible really foolish...**

code & data

**Comment by mdouze** [comment]
Hi 

In build_index, you should keep a reference to quantizer around, for example by setting self.quantizer = quantizer. Otherwise Python will deallocate it when the index still references it. See 

https://github.com/facebookresearch/faiss/wiki/Faiss-code-structure#object-ownership

**Comment by hxsnow10** [comment]
@mdouze Thanks your reply.
In User's View, It is a bug , although i don't get why designed like this.
Or tutorial should add thsi point better~

**Comment by jaytimbadia** [comment]
> i use faiss to do fast word2vec similar search
> following is code.
> vec.txt is standard google w2v txt。
> two similar code, when index/data should unchanged, but work differently.
> 
> **INIT LAST1 work INIT LAST2 core dumped when LAST2 work just after LAST1**
> ![qq 20170502222913](https://cloud.githubusercontent.com/assets/5416620/25622409/e6d40410-2f86-11e7-8179-1cdc2577e9ef.png)
> 
> ```python
> #encoding=utf-8
> import numpy
> import numpy as np
> import faiss
> 
> s=None
> def normalized(a, axis=-1, order=2):
>     # np.sum(np.abs(a)**2,axis=-1)**(1./2)
>     #print 'a=',a
>     #print 'norm=',np.linalg.norm(a, order, axis)
>     l2 = np.atleast_1d(np.linalg.norm(a, order, axis))
>     l2[l2==0] = 1 
>     #print l2
>     return a / np.expand_dims(l2, axis)
> from copy import deepcopy
> class W2vFast():
>     '''for quick simikar search'''
> 
>     def __init__(self, w2v_path, index_type='fast'):
>         self.xb=None
>         self.index_strange=None
>         self.word_vecs, _, self.d=self.load(w2v_path)
>         self.build_index(self.word_vecs, self.d, index_type)
>         self.build_index(self.word_vecs, self.d, index_type)
>         print 'INIT LAST2' , self.index_strange.search(self.xb[-5:],4)
> 
>     def load(self,w2v_path):
>         rval={}
>         ii=open(w2v_path,'r')
>         N,d=ii.readline().strip().split()
>         N,d=int(N), int(d)
>         for line in ii:
>             s=line.strip().split()
>             w=s[0]
>             v=numpy.array(s[1:],dtype=numpy.float32)
>             #v=normalized(v)[0]
>             rval[w]=v*100
>         ii.close()
>         return rval,N,d
> 
>     def build_index(self, wv, d, index_type='fast'):
>         '''
>         wv是一个字典,d是向量长度
>         '''
> 
>         self.int2word={k:key for k,key in enumerate(wv.keys())}
>         self.word2int={key:k for k,key in enumerate(wv.keys())}
>         
>         xb=numpy.array(wv.values())#不支持float16
>         
>         
>         if index_type=='accurate':
>             index = faiss.IndexFlatL2(d)
>             index.add(xb)
>         elif index_type=='fast':
>             d=100
>             nlist = 100# ?
>             quantizer = faiss.IndexFlatL2(d)
>             index = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_L2)
>             index.train(xb)
>             index.add(xb)
>         elif index_type=='compress':
>             nlist = 100#?
>             m = 8                      # number of bytes per vector
>             quantizer = faiss.IndexFlatL2(d)  # this remains the same
>             index = faiss.IndexIVFPQ(quantizer, d, nlist, m, 8)
>             # 8 specifies that each sub-vector is encoded as 8 bits
>             index.train(xb)
>             index.add(xb)
>         self.index_type=index_type
>         self.index_strange = index
>         self.xb=xb
>         print 'INIT LAST1' , self.index_strange.search(self.xb[-5:],4)
>         print 'INIT LAST1.1' , self.index_strange.search(self.xb[-5:],4)
> 
> 
>     def index_search(self, v, k, nprobe=1):
>         v=np.array([v,v,v],dtype=numpy.float32)
>         if not nprobe:# ?
>             self.index.nprobe=nprobe
>         print self.index
>         print self.index.ntotal
>         D,I=self.index.search(v,k)
>         return list(I[0])
> 
>     def search(self, w, k, nprobe=10):
>         if w not in self.word_vecs:
>             return []
>         v=self.word_vecs[w]
>         s=self.index_search(v,k,nprobe)
>         words=[self.int2word[i] for i in s]
>         return words
> 
>     def add_wv(self, word, vec):#Next Todo
>         it=len(self.int2word)
>         self.int2word[it]=word
>         self.word2it[word]=it
>         self.index.add(np.array([vec],dtype=numpy.float16))
> 
> 
> if __name__=='__main__':
>     #model=W2vFast('vec.txt','accurate')
>     model=W2vFast('vec.txt')
>     print 'strange damn shit'
>     print model.index_strange.search(model.xb[-5:],4)
>     #for w in model.search('喜欢',10):
>     #    print w
>     #model.add_wv
>     while true:
>         word=raw_input('Input word:')
>         k=raw_input('Input K:')
>         word=word.strip()
>         k=int(k.strip())
>         for word in self.search(word,k):
>             print word
> ```
> 
> **Sorry for my possible really foolish...**
> 
> code & data

Hey Good Work, 
Will this work on Google word2vec .bin file?

Also, How much increase in speed and decrease in fetching most similar words has it achieved?

Also, Can you share your latest script, if possible?
