### ISSUE TITLE
Why IVFSQ8 is faster than IVFFlat in CPU mode?

### ISSUE THREAD

**Issue by cydrain** [facebookresearch/faiss#1040]
Hi,
I'm from Milvus team.
When I do FAISS performance testing, it confused me that IVFSQ8 is 2~3 times faster than IVFFLAT in CPU mode.
From the source code, we can see that there is no difference between IVFFlat and IVFSQ8 distance computation except "reconstruct_8_components()" is called in IVFSQ8. It will be well-understood if IVFSQ8 is slower, since IVFSQ8 do more computation work.
But why we see IVFSQ8 is much faster ? 

Dataset: sift-1b (1 billion, dimension 128)
Search mode: CPU
nlist: 16384
nprobe: 32
nq: 1000
topk: 100

**Comment by wickedfoo** [comment]
I would imagine this is due to 1/4x the required memory bandwidth for SQ8, most likely. IVFFlat has to load 4 bytes per vector dimension, while SQ8 loads 1 byte. The added computation is a non-issue because the original computation is likely memory bandwidth bound.
