### ISSUE TITLE
Is there any method to retrieve feature via id?

### ISSUE THREAD

**Issue by aaron900813** [facebookresearch/faiss#1043]
Interface: 
- [ ] C++
- [x] Python

Maybe like:
features = fails.get_feature(ids)

**Comment by mdouze** [comment]
see https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes#reconstructing-vectors-from-an-index

**Comment by aaron900813** [comment]
> see https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes#reconstructing-vectors-from-an-index

Thanks for help

**Comment by mustfkeskin** [comment]
How can I get a vector by id? 
index_flat = faiss.IndexFlatIP(DIM)
index_flat = faiss.IndexIDMap(index_flat)

Flat index got error when `index.reconstruct(vector_id)`

**Comment by lxw0109** [comment]
> How can I get a vector by id?
> index_flat = faiss.IndexFlatIP(DIM)
> index_flat = faiss.IndexIDMap(index_flat)
> index_flat.add_with_ids(vectors, np.array(ids))
> 
> I want to get vector given id
> Flat index got error when `index.reconstruct(vector_id)`

I have the same problem

**Comment by bigtiger90** [comment]
> How can I get a vector by id?
> index_flat = faiss.IndexFlatIP(DIM)
> index_flat = faiss.IndexIDMap(index_flat)
> index_flat.add_with_ids(vectors, np.array(ids))
> 
> I want to get vector given id
> Flat index got error when `index.reconstruct(vector_id)`

need add make_direct_map

**Comment by crystal3239** [comment]
IndexIDMap may not be able to do so. Try IndexIDMap2

Reference: https://github.com/facebookresearch/faiss/issues/1529
