### ISSUE TITLE
python test failed because of print in python 2 style

### ISSUE THREAD

**Issue by mylyu** [facebookresearch/faiss#1049]
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

I complied FAISS python interface for python 3.6 from the git master branch yesterday, and found that the python test failed on tests/test_build_blocks.py where print is called in python 2 style. After using 2to3 to convert it to python3 style, all tests passed. I checked the commit history, this seems introduced a few months ago.

**Comment by mdouze** [comment]
Making all tests py3 compatible is on our todo list.

**Comment by mdouze** [comment]
Fixed in 1.6.3
