### ISSUE TITLE
faiss.write_index(ann.index, 'xx')

### ISSUE THREAD

**Issue by Jie-Yuan** [facebookresearch/faiss#1054]
RuntimeError: Error in void faiss::write_index(const faiss::Index*, faiss::IOWriter*) at impl/index_write.cpp:464: don't know how to serialize this type of index

**Comment by only-yao** [comment]
I had the same problem

**Comment by dimitrisnikolaou10** [comment]
+1 on this issue

**Comment by mdouze** [comment]
Insufficient info to repro issue. 
Please submit a proper (new) issue.
