### ISSUE TITLE
Question about invlists？

### ISSUE THREAD

**Issue by dongzhen123** [facebookresearch/faiss#1055]
my code:
#############################
nlist=1024
m=8
k=5
d=64
coarse_quantizer=faiss.IndexFlatL2(d)
index=faiss.IndexIVFPQ(coarse_quantizer,d,nlist,m,8)

index.train(xb)
index.add(xb)

il=index.invlists

l=il.get_single_code(0,10)

#############################

list entry=id+code
Then how to show the code in invlists like this,for example:16,48,21,165,172,254,201,77
each value represent indice in pq.centroids.

**Comment by mdouze** [comment]
Yes see here: 
[get_invlists.ipynb](https://gist.github.com/mdouze/b0a65aba70a64b00d6425b0e268a4c80)

**Comment by dongzhen123** [comment]
> Yes see here:
> [get_invlists.ipynb](https://gist.github.com/mdouze/b0a65aba70a64b00d6425b0e268a4c80)

Thanks!
