### ISSUE TITLE
search_centroin  

### ISSUE THREAD

**Issue by lockeliu** [facebookresearch/faiss#1058]
IVFlib.h  can support search_centroin  assign nprobe， now default nprobe is 1
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
I don't understand the question.

**Comment by lockeliu** [comment]
function search_centroin  of file IVFlib.h specifying parameters nprobe
like this
```
void search_centroid(faiss::Index *index,
                     const float* x, int n,
                     idx_t* centroid_ids, int nprobe )
{
    std::unique_ptr<float[]> del;
    if (auto index_pre = dynamic_cast<faiss::IndexPreTransform*>(index)) {
        x = index_pre->apply_chain(n, x);
        del.reset((float*)x);
        index = index_pre->index;
    }
    faiss::IndexIVF* index_ivf = dynamic_cast<faiss::IndexIVF*>(index);
    assert(index_ivf);
    index_ivf->quantizer->assign(n, x, centroid_ids, nprobe );
}
```


sorry，my English not well
