### ISSUE TITLE
different accuracy between IndexIVFFlat and GpuIndexIVFFlat

### ISSUE THREAD

**Issue by hws912** [facebookresearch/faiss#1061]
# Summary

I test IndexIVFFlat and GpuIndexIVFFlat on the same data, but the accuracy of GpuIndexIVFFlat is far less than IndexIVFFlat.

The accuracy is what the fraction of overlap between the result of GpuIndexIVFFlat/GpuIndexIVFFlat and brute force.

In my test, the accuracy of IndexIVFFlat is 95%, but the accuracy of GpuIndexIVFFlat is only 30%.

The parameters are as follows:
data size: 8 million
dim: 100
topK: 20
MetricType: METRIC_L2
train size: 500000
nlist: 10000
nprobe: 100

I tried to adjust parameters for GpuIndexIVFFlat and found that the accuracy can be 90% if I set nlist a small number, such as 16, but the search time cost will be very high which is not accepted.

Could you please give me some suggestions? Thanks.

**Comment by wickedfoo** [comment]
How exactly are you testing accuracy? i.e., are you using GpuIndexFlat or IndexFlat, what is the size of your test set, and are you evaluating the true nearest neighbor, or all top 20 neighbors?

**Comment by hws912** [comment]
> How exactly are you testing accuracy? i.e., are you using GpuIndexFlat or IndexFlat, what is the size of your test set, and are you evaluating the true nearest neighbor, or all top 20 neighbors?

I'm not using GpuIndexFlat nor IndexFlat, I wrote a cpu program to calculate L2 distance betweeen test vector and each candidate vector, and select top 20 with minimum L2 distance as the true result, then calculate the fraction of overlap between the result of GpuIndexIVFFlat/GpuIndexIVFFlat and the true result with all top 20 neighbors.

My test set is 1000 and I think the test result is credible.

**Comment by mdouze** [comment]
Normally, the results should be very close. 
A few questions: 
- are there identical distances, such that the ordering of results is undefined? 
- could you train on CPU and transfer to GPU and vice-versa to see if the training has an impact?

**Comment by wickedfoo** [comment]
How close are all the top-20 neighbors to each other? i.e., how many floating point units in the last place (ulp) do they differ from each other? Identical distances could also affect things a lot.

Are all the top-20 reported by the GPU in, say, the top 100 reported by your version?

The order of floating point evaluation differs between the CPU and GPU IVFFlat versions so are not guaranteed to be equivalent, especially if the nearest neighbors are quite close to each other.

**Comment by wickedfoo** [comment]
Also how are you setting nprobe on the GPU? Do you have this fix that broke setNumProbes for a bit?

https://github.com/facebookresearch/faiss/commit/e325c50e971039d42404539e7a5b91584549b204

**Comment by hws912** [comment]
> e325c50

Oh，the bug still in my code. Let me test with the newest version. Thanks.

**Comment by hws912** [comment]
The problem is solved after the bug fixed. GpuIndexFlat is even more accurate than  IndexIVFFlat. Thanks.
