### ISSUE TITLE
How to get the value of  IndexHNSWFlat in python?

### ISSUE THREAD

**Issue by dongzhen123** [facebookresearch/faiss#1064]
For example,I want to achieve the search in python in my own code.So first I need to get the  related value in index=faiss.IndexHNSWFlat(d,32).And then implement the entire process of search in python.Is there any demo?

**Comment by mdouze** [comment]
Not sure I understand the question. Take a look at this: 
https://github.com/facebookresearch/faiss/blob/master/benchs/bench_hnsw.py#L43

**Comment by dongzhen123** [comment]
> Not sure I understand the question. Take a look at this:
> https://github.com/facebookresearch/faiss/blob/master/benchs/bench_hnsw.py#L43

for example,how to get the connet id ?

**Comment by mdouze** [comment]
So if you refer to the HNSW graph structure, this function should work: 
https://github.com/facebookresearch/faiss/blob/a8118acbc516b0263dde610862c806400cc48bf5/benchs/link_and_code/bench_link_and_code.py#L263

**Comment by dongzhen123** [comment]
> So if you refer to the HNSW graph structure, this function should work:
> https://github.com/facebookresearch/faiss/blob/a8118acbc516b0263dde610862c806400cc48bf5/benchs/link_and_code/bench_link_and_code.py#L263

after use this function,error happen:
![IMG_6704](https://user-images.githubusercontent.com/29719811/71616121-9bd7a300-2bef-11ea-9639-89e7a73a698e.JPG)

**Comment by mdouze** [comment]
Please do not paste screenshots.

I could repro the bug, see

https://gist.github.com/mdouze/a25eae93db9afb17a041e1e54f0e675e

There is probably something wrong in the SWIG file. Will investigate.

**Comment by dongzhen123** [comment]
> Please do not paste screenshots.
> 
> I could repro the bug, see
> 
> https://gist.github.com/mdouze/a25eae93db9afb17a041e1e54f0e675e
> 
> There is probably something wrong in the SWIG file. Will investigate.

Ok,thanks!

**Comment by mdouze** [comment]
This is due to an invalid typedef here:
https://github.com/facebookresearch/faiss/blob/master/python/swigfaiss.swig#L28
Fixing now, but you will have to recompile to get the fix.

**Comment by dongzhen123** [comment]
> This is due to an invalid typedef here:
> https://github.com/facebookresearch/faiss/blob/master/python/swigfaiss.swig#L28
> Fixing now, but you will have to recompile to get the fix.

Ok,many thanks！
