### ISSUE TITLE
Faiss Consume Too Many Threads 

### ISSUE THREAD

**Issue by aaron900813** [facebookresearch/faiss#1066]
# Summary

# Platform

OS: 
`Linux 4.15 Ubuntu 18.04 and 72 cores`
Faiss version: 
`1.5.3`
Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

```
import sys
print('import sys')
sys.stdin.read(1)
import faiss
print('import faiss')
sys.stdin.read(1)
```
Run `ps huH p $PROCESSID | wc -l `
I get 64 threads, I don't do anything add or search, so why allocate so many thread?  
And is there any method to limit max thread count?

**Comment by mdouze** [comment]
Maybe the OpenMP implementation allocates idle threads upfront. 
See here on how to set the number of OpenMP threads: https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls#internal-threading

**Comment by aaron900813** [comment]
> Maybe the OpenMP implementation allocates idle threads upfront.
> See here on how to set the number of OpenMP threads: https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls#internal-threading

Yes, OpenMP allocates idle threads, this can limit max thread count.
```os.environ['OMP_NUM_THREADS'] = str(2)
import faiss
