### ISSUE TITLE
How can I get a vector by id?

### ISSUE THREAD

**Issue by sky94520** [facebookresearch/faiss#1068]
I browsed some pages and codes about faiss, but I did not find the function which I can get  by offering its id.

**Comment by yzrluo** [comment]
same question here

**Comment by aaron900813** [comment]
Check this https://github.com/facebookresearch/faiss/issues/1043

**Comment by sky94520** [comment]
> Check this #1043

Thank you！！！

**Comment by sky94520** [comment]
> same question here

Thank You！！！

**Comment by j-ai-deloitte** [comment]
**Extracting vector values using id:**
 
    index = faiss.read_index(index_file)
    
    # Assuming index is your trained Faiss index and d is the dimension of the vectors
    d = 1536

    # Id of the vector to retrieve
    vec_id = 190

    # Create an empty numpy array to hold the vector
    vec = np.empty((1, d), dtype='float32')

    # Call the reconstruct method
    index.index.reconstruct(vec_id, vec[0])

    # Now vec contains the vector associated to the id
    print(vec[0])
