### ISSUE TITLE
Remove id from a Gpu index

### ISSUE THREAD

**Issue by welfred** [facebookresearch/faiss#107]
In class GpuIndexIVFFlat, there is not an interface to remove ids. So we need to transfer  the GPU index to CPU index，then turn back like this:
`  faiss::Index::idx_t deleteIDs[1];

   deleteIDs[0] = 1000;

   faiss::IDSelectorBatch idBatch = faiss::IDSelectorBatch(1, deleteIDs);

   cpu_index = faiss::gpu::index_gpu_to_cpu (oldGpuIndex);  
  
   cpu_index->remove_ids(idBatch);
  
   newGpuIndex = (faiss::gpu::GpuIndexIVFFlat*)faiss::gpu::index_cpu_to_gpu(&res, device, cpu_index, NULL);`

Is it right?

**Comment by mdouze** [comment]
Hi, 

This is right. I think supporting id removal on GPU is not high-priority, @wickedfoo can you confirm?

Note that the above code is very inefficient because of the removal of a single index and the round-trip to/from GPU.

**Comment by mdouze** [comment]
Closing issue.
