### ISSUE TITLE
Some confusion?

### ISSUE THREAD

**Issue by dongzhen123** [facebookresearch/faiss#1070]
1.As the paper show:

M-number of established connections
Mmax-maximun number of connections for each element per layer(except l0)
Mmax0-maximun number of connections for each element in l0

so the quantitaive relationship between them is what?
what I know is Mmax0=2*Mmax. but then the relationship between Mmax and M is what?

2.How to export the id of neighbors of one vertex in the graph in python?

**Comment by mdouze** [comment]
1. It is unclear what paper is referred to. In the HNSW interface, M is Mmax.

2. see https://github.com/facebookresearch/faiss/blob/a8118acbc516b0263dde610862c806400cc48bf5/benchs/link_and_code/bench_link_and_code.py#L263

**Comment by dongzhen123** [comment]
> 1. It is unclear what paper is referred to. In the HNSW interface, M is Mmax.
> 2. see https://github.com/facebookresearch/faiss/blob/a8118acbc516b0263dde610862c806400cc48bf5/benchs/link_and_code/bench_link_and_code.py#L263

thanks and happy new year！
