### ISSUE TITLE
Where does the randomness of hnsw come from?

### ISSUE THREAD

**Issue by quoniammm** [facebookresearch/faiss#1073]
I used the same data, trained three times with hnsw, the test set is the same, but the three recalls are different. Where does the randomness of hnsw come from? Hnsw has a fixed random seed operation, so the same data, the same order, add to the index It ’s weird why the recall is different.

the recall is:
first time: 0.973862 
second time: 0.972478
third time: 0.972676

Can someone help me explain why?

**Comment by mdouze** [comment]
see #983. 
Added a section in the doc: 
https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls#reproducibility-with-multiple-threads

**Comment by quoniammm** [comment]
thanks, it does help me.
