### ISSUE TITLE
In the constructor of `IndexIVFPQ` class, what does `nlist` stand for?

### ISSUE THREAD

**Issue by thelinuxmaniac** [facebookresearch/faiss#1080]
Thank you faiss authors and contributors for creating this extremely valuable software. I have a question regarding the description of method arguments for the constructor of `IndexIVFPQ` class.

The method definition of `IndexIVFPQ` in C++ API documentation (generated by dOxygen) is given as follows:
```
IndexIVFPQ (Index *quantizer, size_t d, size_t nlist, size_t M, size_t nbits_per_idx)
```
I understand the meaning of all the method arguments **except** the 3rd argument `size_t nlist`. What does `nlist` signify in `IndexIVFPQ`. In the faiss tutorials and example code, I see that `int nlist = 100;`. What does a value of `100` mean here?

**Comment by mdouze** [comment]
see https://github.com/facebookresearch/faiss/wiki/Faiss-indexes#cell-probe-methods-indexivf-indexes

**Comment by thelinuxmaniac** [comment]
Thank you very much indeed for quick reply.
