### ISSUE TITLE
How to read an index from S3?

### ISSUE THREAD

**Issue by PabloPardoGarcia** [facebookresearch/faiss#1082]
I built an index (`IVF262144_HNSW32,Flat`) with ~50M 1024d vectors ondisk following this [example](https://github.com/facebookresearch/faiss/blob/master/demos/demo_ondisk_ivf.py). 

Is it possible to store the index on s3 and read it with [S3FS](https://s3fs.readthedocs.io/en/latest/) or [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/index.html) ? If so how can I do it?

Also, is it possible to specify the path where the merged inverted lists are stored?

**Comment by mdouze** [comment]
I don't think S3 supports memory maps, which is what ondisk is built upon, so searching from S3 is not supported.
 
It should be possible to add support for reading or writing indexes (but not inverted lists that require mmap), but the API is not available from python currently, only C++.

Serialization to a buffer works but duplicates the index in RAM:
https://github.com/facebookresearch/faiss/issues/227#issuecomment-404789816

Path for merged data is set here: https://github.com/facebookresearch/faiss/blob/master/demos/demo_ondisk_ivf.py#L81

**Comment by PabloPardoGarcia** [comment]
Thank you for your fast response, that was very helpful.

**Comment by happinessbaby** [comment]
https://medium.com/swlh/add-similarity-search-to-dynamodb-with-faiss-c68eb6a48b08
This article might help anyone who's still interested. You could update and save the embeddings to S3 and load the embeddings...
