### ISSUE TITLE
bench_gpu_1bn.py has same recall for different nprobe and k 

### ISSUE THREAD

**Issue by wjtan99** [facebookresearch/faiss#1085]
I tested bench_gpu_1bn.py, but the recall results for all different nprob and k are all the same 

python benchs/bench_gpu_1bn.py SIFT10M IVF262144,Flat 
Loading faiss with AVX2 support.
Preparing dataset SIFT10M
sizes: B (10000000, 128) Q (10000, 128) T (100000000, 128) gt (10000, 1000)
cachefiles:
None
/tmp/bench_gpu_1bn/cent_SIFT10M_IVF262144.npy
/tmp/bench_gpu_1bn/SIFT10M_IVF262144,Flat.index
preparing resources for 4 GPUs
load /tmp/bench_gpu_1bn/SIFT10M_IVF262144,Flat.index
CPU index contains 10000000 vectors, move to GPU
copying loaded index to GPUs
IndexShards shard 0 select modulo 4 = 0
IndexShards shard 1 select modulo 4 = 1
IndexShards shard 2 select modulo 4 = 2
IndexShards shard 3 select modulo 4 = 3
move to GPU done in 29.953 s
search...
9900/10000 (1.496 s)      probe=1  : 1.508 s 1-R@1: 0.1800 1-R@10: 0.1800 
9900/10000 (1.494 s)      probe=2  : 1.509 s 1-R@1: 0.1800 1-R@10: 0.1800 
9900/10000 (1.833 s)      probe=4  : 1.847 s 1-R@1: 0.1800 1-R@10: 0.1800 
9900/10000 (1.572 s)      probe=8  : 1.583 s 1-R@1: 0.1800 1-R@10: 0.1800 
9900/10000 (1.783 s)      probe=16 : 1.794 s 1-R@1: 0.1800 1-R@10: 0.1800 
9900/10000 (1.207 s)      probe=32 : 1.218 s 1-R@1: 0.1800 1-R@10: 0.1800 
9900/10000 (1.400 s)      probe=64 : 1.412 s 1-R@1: 0.1800 1-R@10: 0.1800 
9900/10000 (3.172 s)      probe=128: 3.359 s 1-R@1: 0.1800 1-R@10: 0.1800 
9900/10000 (1.416 s)      probe=256: 1.428 s 1-R@1: 0.1800 1-R@10: 0.1800 

# Platform

OS: Ubuntu 16.04 LTS

Faiss version: latest 

Faiss compilation options: 

Running on:
- [ ] CPU
- [x ] GPU

Interface: 
- [ ] C++
- [x ] Python

# Reproduction instructions

python benchs/bench_gpu_1bn.py SIFT10M IVF262144,Flat

**Comment by wjtan99** [comment]
I installed FAISS with conda: 

conda install faiss-gpu cudatoolkit=10.0 -c pytorch # For CUDA10

**Comment by mdouze** [comment]
There was a bug with Faiss 1.6.0 where the nprobe was not set correctly. Are you using 1.6.1 ?

**Comment by wjtan99** [comment]
Thanks for your answer. I tried installing faiss 1.6.1 from compiling the source code. but I met another problem.  After that problem is resolved, I will test if the problem in this issue is gone.

**Comment by wjtan99** [comment]
I uninstalled faiss-gpu and reinstalled. The Anaconda repository https://anaconda.org/pytorch/faiss-gpu says version 1.6.1.  I believe this is the faiss version.  So I do not know why the results for all different nprobes are the same.   
I still have problem compiling faiss from source.

**Comment by wjtan99** [comment]
By locating faiss, I confirmed this is faiss 1.6.0.  Information is like this  

locate faiss 
/home/ubuntu/anaconda2/envs/FAISS_PY2/conda-meta/faiss-gpu-1.6.0-py27h32c130d_0.json
/home/ubuntu/anaconda2/envs/FAISS_PY2/lib/python2.7/site-packages/faiss
/home/ubuntu/anaconda2/envs/FAISS_PY2/lib/python2.7/site-packages/faiss-1.6.0-py2.7.egg-info

I run into a lot problems in compiling 1.6.1 from source code.  So far it still has not resolved yet.

**Comment by wjtan99** [comment]
After I compiled version 1.6.1, this problem seems gone. 
Actually, when I uninstalled the faiss-gpu in Anaconda and reinstalled it, the problem was also gone. I do not know for sure if the version 1.6.0 caused the problem.  Anyway, it is great the problem is finally gone.
