### ISSUE TITLE
Load index from stream in Python

### ISSUE THREAD

**Issue by zelcookie** [facebookresearch/faiss#1089]
Hi
Is it possible to load index from stream in Python(such as io.BytesIO or io.BufferedReader)?

**Comment by mdouze** [comment]
This would require some C/python + SWIG magic but would be valuable. 
I'll mark this as enhancement. No guarantee that it will be supporte soon. 
If you can live with 3 simultaneous copies of the index in RAM, you can use `serialize_index` / `deserialize_index` to copy it to a byte array.
https://github.com/facebookresearch/faiss/blob/master/python/faiss.py#L711

**Comment by mdouze** [comment]
Supported in 1.6.3. See 
https://github.com/facebookresearch/faiss/wiki/Index-IO,-cloning-and-hyper-parameter-tuning#generic-io-support
