### ISSUE TITLE
[Question] Can range_search results maintain the distribution in the range

### ISSUE THREAD

**Issue by AaronHeee** [facebookresearch/faiss#1090]
###  Can range_search return results maintaining the distribution in the range?

For example, supposing there are 2000 vectors, where 1000 vectors of them are within the required range. Can we use `range_search` to approximately return 100 vectors, which are maintaining a similar distribution like the 1000 vectors' ?

Thanks for your help.

**Comment by mdouze** [comment]
At first sight this seems statistically equivalent to building an index on a sample of 1/10th of the data, which is cheaper...

**Comment by AaronHeee** [comment]
Thanks, that's a nice alternative approach. 
Yet is it possible to use `range_search` on the whole vectors directly?

**Comment by mdouze** [comment]
No. See https://github.com/facebookresearch/faiss/wiki/FAQ#is-it-possible-to-dynamically-exclude-vectors-based-on-some-criterion

**Comment by AaronHeee** [comment]
Got it, thanks for your reply!
