### ISSUE TITLE
Question about IVFFlat invlist ids and centroids

### ISSUE THREAD

**Issue by guskovd** [facebookresearch/faiss#1093]
Let's say we have an index object

I learned how to get a 0..index.nlist-1 of centroids:

```python
index.quantizer.reconstruct_n(0, index.nlist)
```

I also figured out how to get 0..index.nlist-1 nlists of this index and the identifiers of the vectors in each invlist by:

https://gist.github.com/mdouze/b0a65aba70a64b00d6425b0e268a4c80

My task is to get the vectors themselves, not their codes.

1. Do I understand correctly that the IDs of the centroids and invlist are the same IDs?
2. Do I understand correctly that in order to get a vector by its ID, you need to find it in the index?
By:

```python
index.reconstruct_n(0, index.ntotal)[id]
```

**Comment by mdouze** [comment]
1. yes
2. you can also use `index.reconstruct` see https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes#reconstructing-vectors-from-an-index

**Comment by guskovd** [comment]
Thanks!
