### ISSUE TITLE
brew install faiss

### ISSUE THREAD

**Issue by ankane** [facebookresearch/faiss#1099]
Hi, thanks for creating Faiss! Just wanted to let you know that the C++ library can now be installed with Homebrew to make installation easier and quicker for Mac users.

```sh
brew install faiss
```

https://github.com/Homebrew/homebrew-core/pull/49235

**Comment by mdouze** [comment]
Thanks! Added it to https://github.com/facebookresearch/faiss/wiki/Related-projects#bindings-to-other-languages-and-porting-to-other-platforms

**Comment by ankane** [comment]
Great, thanks @mdouze!

**Comment by arjansiddhpura** [comment]
Hi, I just installed it using brew install faiss, how can I now actually use it though? 😅

**Comment by rswethashankar92** [comment]
> Hi, I just installed it using brew install faiss, how can I now actually use it though? 😅

Same question

**Comment by arjansiddhpura** [comment]
> > Hi, I just installed it using brew install faiss, how can I now actually use it though? 😅
> 
> Same question

Hi, I just used the faiss library from python instead. I believe it was this one: https://pypi.org/project/faiss-cpu/
