### ISSUE TITLE
Error when compiling the Python interface with GPU support

### ISSUE THREAD

**Issue by willard-yuan** [facebookresearch/faiss#11]
Hi,

I face a problem when I compile the Python interface with GPU support (step 1 and step 2 are ok). The error is reported as following:

```sh
cd ../python; swig -Doverride= -python -c++ -DGPU_WRAPPER -o ../python/swigfaiss_gpu_wrap.cxx ../swigfaiss.swig
../gpu/StandardGpuResources.h:67: Error: Syntax error in input(3).
make: *** [../python/swigfaiss_gpu_wrap.cxx] error 1
```

Anyone help me?

**Comment by mdouze** [comment]
Hi, 
This is probably because the swig version is too old, and you have probably erased the swig-generated files by doing make clean. You can restore them by

cd ../python 
git checkout swigfaiss_gpu_wrap.cxx swigfaiss_gpu.py
