### ISSUE TITLE
What exactly is faiss-gpu on Pypi?

### ISSUE THREAD

**Issue by bricksdont** [facebookresearch/faiss#1101]
I succesfully installed the `faiss-cpu` package from Pypi:

    pip install faiss-cpu

Then I noticed that there is also `faiss-gpu`:

https://pypi.org/project/faiss-gpu/

But what exactly is in this package? Building from source (https://github.com/facebookresearch/faiss/blob/master/INSTALL.md) requires specifying a particular version of CUDA. Which version of CUDA does this package expect?

In case this package is not built with CUDA, follow-up question: what is the purpose of the package?

**Comment by bricksdont** [comment]
@kyamagu

**Comment by kyamagu** [comment]
@bricksdont  faiss-cpu and faiss-gpu on pypi are unofficially built wheels. You can check how they are built in [this repo](https://github.com/kyamagu/faiss-wheels).

c.f. #170

**Comment by bricksdont** [comment]
Thanks! Closing.
