### ISSUE TITLE
Explanation of IVF65536_HNSW32,PQ64 index structure

### ISSUE THREAD

**Issue by sgjurano** [facebookresearch/faiss#1107]
# Summary

Do I correctly understand, that with this index we firstly find $nprobe nearest InvertedFile clusters using HNSW to speed up the search process and then we compute distances to all vectors in found clusters using ProductQuantization code books, ordering results by distances and return it to user?

If I want to use HNSW at the second level (inside IVF clusters), which index structure should I use?

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
The explanation is correct. 
Using HNSW inside the IVF clusters is not implemented. It is likely that it would be less efficient than using a single HNSW on all the vectors to index.

**Comment by sgjurano** [comment]
Thank you for the answer.
