### ISSUE TITLE
Faiss assertion 'err == cudaSuccess || err == cudaErrorInvalidValue' failed in int faiss::gpu::getDeviceForAddress(const void*) at gpu/utils/DeviceUtils.cu:105 [1]    28704 abort (core dumped)

### ISSUE THREAD

**Issue by luan1412167** [facebookresearch/faiss#1112]
# Summary

# Platform

OS: ubuntu 18.04 

Faiss version: latest

Faiss compilation options: gcc.

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

I'm trying below script and get the following bug
"Faiss assertion 'err == cudaSuccess || err == cudaErrorInvalidValue' failed in int faiss::gpu::getDeviceForAddress(const void*) at gpu/utils/DeviceUtils.cu:105
[1]    29836 abort (core dumped)  ./test_faiss"
Any recommend for me? thanks
`   int d = 512;
    faiss::gpu::StandardGpuResources res;
    // index_ivf = new faiss::gpu::GpuIndexIVFFlat(&res, d, nlist, faiss::METRIC_L2);
    // faiss::gpu::GpuIndexFlatL2 index_flat(&res, d);
    int nlist = 2;
    faiss::gpu::GpuIndexIVFFlat index_ivf(&res, d, nlist, faiss::METRIC_L2);

    
    // printf("is_trained = %s\n", index_flat.is_trained ? "true" : "false");
    // const float* data = &xbs[0];
    int nb_ = 100000;                       // database size
    int nq = 10000;                        // nb_ of queries

    float *xb = new float[d * nb_];
    float *xq = new float[d * nq];

    for(int i = 0; i < nb_; i++) {
        for(int j = 0; j < d; j++)
            xb[d * i + j] = drand48();
        xb[d * i] += i / 1000.;
    }

    assert(!index_ivf.is_trained);
    index_ivf.train(nb_, xb);
    printf("is_trained = %s\n", index_ivf.is_trained ? "true" : "false");
    assert(index_ivf.is_trained);
    index_ivf.add(nb_, xb);  // add vectors to the index

    printf("ntotal = %ld\n", index_ivf.ntotal);
    `

**Comment by mdouze** [comment]
At what stage does the code crash? at the index instantiation, train or add?

**Comment by luan1412167** [comment]
@mdouze thanks for your reply. 
It is crashed at index_ivf.train(nb_, xb);

**Comment by wickedfoo** [comment]
Can you add the following:

`CUDA_TEST_ERROR();`

at the end of `StandardGpuResources::initializeForDevice` in StandardGpuResources.cpp and see if you see an error there when running it?

Perhaps something is set up wrong with your drivers, or there is something wrong with cuBLAS?

Also, you can change `getDeviceForAddress` in `gpu/utils/DeviceUtils.cu` to this and run again, which should give you the actual error code it is returning:

```

int getDeviceForAddress(const void* p) {
  if (!p) {
    return -1;
  }

  cudaPointerAttributes att;
  cudaError_t err = cudaPointerGetAttributes(&att, p);
  FAISS_ASSERT_FMT(err == cudaSuccess ||
                   err == cudaErrorInvalidValue,
                   "unknown error %d", (int) err);

  if (err == cudaErrorInvalidValue) {
    // Make sure the current thread error status has been reset
    err = cudaGetLastError();
    FAISS_ASSERT_FMT(err == cudaErrorInvalidValue,
                     "unknown error %d", (int) err);
    return -1;
  } else if (att.memoryType == cudaMemoryTypeHost) {
    return -1;
  } else {
    return att.device;
  }
}
```

**Comment by luan1412167** [comment]
@wickedfoo thanks for your support. I have fixed it by how modify CMakeLists.txt link_library to libfaiss.so. I think that before I linked to wrong library.
