### ISSUE TITLE
Does GpuIndexIVFPQ support adding while searching?

### ISSUE THREAD

**Issue by wxingda** [facebookresearch/faiss#1116]
I know GPU index is not thread safety, but I tested adding while searching, surprisingly,  it didn't crash, so GPU index  support  adding while searching?

**Comment by wxingda** [comment]
@wickedfoo

**Comment by mdouze** [comment]
It is not supported on GPU, and neither does the CPU. 
Keep in mind that tests cannot prove there is no bug. They can only prove there *is* a bug.

**Comment by wxingda** [comment]
Thank you！
