### ISSUE TITLE
Cosine similarity of sentence representations

### ISSUE THREAD

**Issue by ajesujoba** [facebookresearch/faiss#1117]
So I am trying to compute the cosine similarity of sentence representations between two languages. I have `a_list ` and `b_list `  which are lists of tuples where each tuple contains the (sentence, embedding_representation), that is `[(tens1, tens2), ...]` where `tens1` represents the sentence, and `tens2` is the vector representation of the sentence needed to compute the similarities. Is it possible to get this done faiss?

**Comment by mdouze** [comment]
You can use eg. https://docs.scipy.org/doc/scipy/reference/spatial.distance.html to compute distances. Faiss is useful if there is indexing involved.
