### ISSUE TITLE
How to select a suitable ‘nlist’?

### ISSUE THREAD

**Issue by yyy007** [facebookresearch/faiss#112]
In the Wiki-tutorial, the 'nlist' is 100 for database with 100000 vectors. How can I choose a suitable 'nlist' value for database with a different quantity of vectors? Thank you!

**Comment by wickedfoo** [comment]
4 * sqrt(n) is usually reasonable, or some other O(sqrt(n)).
It's a tradeoff between speed (high nlist) against accuracy (low nlist). Various nprobe must be considered as well (which likewise trades off speed versus accuracy).

You'd have to experiment and look at the search quality and speed.

**Comment by yyy007** [comment]
Thank you for replying me!

**Comment by Crispae** [comment]
> 4 * sqrt(n) is usually reasonable, or some other O(sqrt(n)). It's a tradeoff between speed (high nlist) against accuracy (low nlist). Various nprobe must be considered as well (which likewise trades off speed versus accuracy).
> 
> You'd have to experiment and look at the search quality and speed.

Here ```n``` is number of data, just to confirm?

**Comment by jacksonchen1998** [comment]
> > 4 * sqrt(n) is usually reasonable, or some other O(sqrt(n)). It's a tradeoff between speed (high nlist) against accuracy (low nlist). Various nprobe must be considered as well (which likewise trades off speed versus accuracy).
> > You'd have to experiment and look at the search quality and speed.
> 
> Here `n` is number of data, just to confirm?

I think so.
