### ISSUE TITLE
Possible wrong formula used in the documentation regarding conversion from L2 to cosine similarity

### ISSUE THREAD

**Issue by EvilPort2** [facebookresearch/faiss#1128]
In the documentation https://github.com/facebookresearch/faiss/wiki/FAQ#how-can-i-index-vectors-for-cosine-distance it is mentioned that d_L2 = 2 - 2*d_IP.

Isn't that the wrong formula? Shouldn't the formula be d_L2^2 = 2 - 2*d_IP?

**Comment by mdouze** [comment]
Right, thanks for flagging!
