### ISSUE TITLE
About install faiss on TX2

### ISSUE THREAD

**Issue by xiaoxiaotao** [facebookresearch/faiss#1129]
# Platform
TX2,Ubuntu
Running on:
- [*] CPU
- [*] GPU

Interface: 
- [* ] C++
- [ ] Python
 when I make compile ,it show:

`g++ -std=c++11 -DFINTEGER=int  -fopenmp -I/usr/local/cuda-9.0/include  -I. -fPIC  -Wno-sign-compare -g -O3 -Wall -Wextra -march=armv8.2-a -c IndexFlat.cpp -o IndexFlat.o
IndexFlat.cpp:1:0: error: unknown value ‘armv8.2-a’ for -march
 /**
 ^
Makefile:42: recipe for target 'IndexFlat.o' failed
make: *** [IndexFlat.o] Error 1
`

**Comment by mdouze** [comment]
Please check the compiler flags to enable SIMD instructions on your platform. Then edit the `makefile.inc` file. See also 
https://github.com/facebookresearch/faiss/wiki/Related-projects#bindings-to-other-languages-and-porting-to-other-platforms

**Comment by xiaoxiaotao** [comment]
ok,thank you!
