### ISSUE TITLE
How do I get the settings of a loaded/read index?

### ISSUE THREAD

**Issue by geniki** [facebookresearch/faiss#1130]
# Summary

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

In python, how do I obtain the parameters (the `index_factory` settings) of an index that has been previously created and I now have loaded using `read_index()`?

**Comment by mdouze** [comment]
As soon as the index leaves the index_factory, the string is lost. This is because it is just a shorthand to create the index structure.

**Comment by geniki** [comment]
I see. So there's no another way to retrieve info on what the index structure is? That would be a useful feature if you have a saved index but you don't have the script that created it.

**Comment by mdouze** [comment]
See this FAQ entry: 
https://github.com/facebookresearch/faiss/wiki/FAQ#how-to-explore-the-contents-of-an-opaque-index

**Comment by geniki** [comment]
Thank you, this helps.
