### ISSUE TITLE
Ruby Library

### ISSUE THREAD

**Issue by ankane** [facebookresearch/faiss#1132]
Hi, thanks for this library! Just wanted to let you know there are now [Ruby bindings](https://github.com/ankane/faiss) for it.

If you have any feedback, let me know or feel free to create an issue in the project for it. Thanks!

**Comment by mdouze** [comment]
Thanks a lot! 
Out of curiosity, how is the wrapping done? From the C API ? Or directly C++?
Added the link to the wiki 
https://github.com/facebookresearch/faiss/wiki/Related-projects#bindings-to-other-languages-and-porting-to-other-platforms

**Comment by ankane** [comment]
Awesome, thanks @mdouze! It currently uses the C++ library wrapped by [Rice](https://github.com/jasonroelofs/rice) (the Ruby version of pybind11).
