### ISSUE TITLE
the accuracy is abnormal

### ISSUE THREAD

**Issue by cloudren2017** [facebookresearch/faiss#1137]
# Summary
I load the index from the file saved before, If I search all the pictures in the database, the accuracy is about 93%. However, if I search a little pictures of the database,the accuracy is always 0%.

# Platform

OS: Centos 7.7.1908

Faiss version: 1.5.3

Faiss compilation options: default

Running on:
- [ ] CPU
- [*] GPU

Interface: 
- [*] C++
- [ ] Python

# Reproduction instructions

I use at most 500 orb features(32 dims) to generate a vlad vector(8192 dims) for a picture.And then I use 60000 pictures to make the database, so the "xb" is 60000. After I train and add the database, the index is in memory and I search 3000 samples, in which the accuracy is about 100%.
The index_factory string is "PCAR128, IVF1024, IDMap, Flat". I save the index to a file.
Then I load the index from the file, in this case, if I search all the pictures in the database, the accuracy is about 93%. However, if I search a little pictures of the database,the accuracy is always 0%.
I don't know why, wish for your help

**Comment by cloudren2017** [comment]
I test that if i save some data as query vectors from the dababase before saving the index file . And then I load the index from my faiss_index file, I search the query vectors which are stored in a file and the result is good and not changed. The accuracy is about 100%. I think that my problem  may be caused by the feature descriptors which are changed. I'm not sure.

**Comment by cloudren2017** [comment]
I found that maybe it's wrong for my ids that given in function add_with_ids

**Comment by luochenxi** [comment]
@cloudren2017  I have the same problem。At the beginning, I thought it is caused by adding and searching without adding a mutex in the case of multithreading。After adding the mutex, it will still reappear。

May I ask? How did you solve it? 

No longer use `add_with_ids` function ?

**Comment by honghande** [comment]
Open CV feature vectors such as surf and sift have been extracted. How to use faiss for vector index? Do you have any reference cases? Thank you!
