### ISSUE TITLE
Image to Vector conversion

### ISSUE THREAD

**Issue by zoe-cheung** [facebookresearch/faiss#114]
What are the steps to convert 1000 of images into vectors for FAISS?

**Comment by jegou** [comment]
This is task-dependent, i.e. it really depends on what you want to do with you images. It is somehow how of scope for Faiss, but out of curiosity, what is the problem you want to address?

On 12 May 2017, at 01:36, zoe-cheung <notifications@github.com<mailto:notifications@github.com>> wrote:


What are the steps to convert 1000 of images into vectors for FAISS?

**Comment by zoe-cheung** [comment]
FAISS needs vector dataset. I have image files. I just want to convert the images into vectors for FAISS. I would like to match similar images.

**Comment by welfred** [comment]
Converting an image into a vector is irrelevant to Faiss.  You need to study CNN or SIFT to extract features(vector) from images. Then you can use Faiss to index these vectors to search or match.
