### ISSUE TITLE
FAISS memory error

### ISSUE THREAD

**Issue by naveenkumarmarri** [facebookresearch/faiss#1144]
# Summary

I have 140M database with 2048 dim vector each. since the data is large, I trained on 15M vectors which went through successfully, however, after adding 10M vectors to the index, I get MemoryError

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

```
import numpy as np
import faiss
faiss.get_num_gpus()
xt = faiss.rand((25000000, 2048))
index = faiss.index_factory(2048, "PCA64,IVF16384_HNSW32,Flat")
index_ivf = faiss.extract_index_ivf(index)
clustering_index = faiss.index_cpu_to_all_gpus(faiss.IndexFlatL2(64))
index_ivf.clustering_index = clustering_index
index.train(xt)
```

```
index.add(faiss.rand((10000000, 2048)))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/pyt1.4/lib/python3.7/site-packages/faiss/__init__.py", line 595, in rand
    res = np.empty(n, dtype='float32')
MemoryError: Unable to allocate 38.1 GiB for an array with shape (5000000, 2048) and data type float32
```

Is there a way to overcome this.

**Comment by mdouze** [comment]
The error does not correspond to the code. 
There does not seem to be enough RAM left to allocate a 5M*2048 dim vector in numpy.
