### ISSUE TITLE
faiss v1.6.2 on anaconda

### ISSUE THREAD

**Issue by derekehyatt** [facebookresearch/faiss#1146]
I'm interested in using both reconstruct and remove_ids for a IndexBinaryIVF, which is unsupported before v1.6.2, but with DirectMap (type=hashtable) in v1.6.2 it looks achievable.

Is there a timeline for when faiss v1.6.2 will be available on anaconda? Is there anything I can do to help? Currently only [v1.6.1 is available on pytorch](https://anaconda.org/search?q=faiss-cpu). I know I could build the source for v1.6.2 myself, but my current project uses anaconda and docker for installations and I want to stick with these if possible.

Thanks for your time!

**Comment by mdouze** [comment]
We are working on preparing the packages for anaconda. 
In the meantime, you can also compile Faiss yourself.

**Comment by derekehyatt** [comment]
Awesome, thanks so much!

**Comment by derekehyatt** [comment]
Hey @mdouze I see that 1.6.3 was uploaded for osx, but not for linux. Was it forgotten? https://anaconda.org/pytorch/faiss-cpu/files
Thanks!
