### ISSUE TITLE
Does faiss provide operation to find target vectors which are within L hamming distance to a query vector?

### ISSUE THREAD

**Issue by xwk** [facebookresearch/faiss#1147]
I was wondering whether faiss provides any class or function which can find all vectors among a set of candidate vectors which are within L hamming distance to a query vector?

I understand IndexBinaryFlat can be used to get the K nearest vectors for a query vector in terms of Hamming distance, but it does not seem to support the kind of query descrived above.

**Comment by mdouze** [comment]
Epsilon-search will be supported in 1.6.3.

**Comment by mdouze** [comment]
supported in 1.6.3. Closing.
