### ISSUE TITLE
What is the meaning of "x12" in "OPQ64_256,PQ64x12"?

### ISSUE THREAD

**Issue by fengsky401** [facebookresearch/faiss#1148]
I read the Vector codec benchmarks(https://github.com/facebookresearch/faiss/wiki/Vector-codec-benchmarks), in the benchmark it appears a lot of "x12" or "x10" after PQ.
I tried "OPQ64_256,PQ64x12"  in my experiment, it reports error:
RuntimeError: Error in faiss::IndexIVFPQ::IndexIVFPQ(faiss::Index*, size_t, size_t, size_t, size_t) at IndexIVFPQ.cpp:43: Error: 'nbits_per_idx <= 8' failed.

I don't know what is the "x12" or "x10" meaning after "PQ".

**Comment by mdouze** [comment]
It is supported in Faiss 1.6.2
Explanations: 
https://github.com/facebookresearch/faiss/wiki/The-index-factory#encodings
https://github.com/facebookresearch/faiss/wiki/FAQ#is-pq-encoding-with-more-or-less-than-8-bits-per-components-supported

**Comment by fengsky401** [comment]
got it, thank you!
