### ISSUE TITLE
Is there any way to make centroid of centroids?

### ISSUE THREAD

**Issue by batrlatom** [facebookresearch/faiss#1149]
Hi, 
I would like to know if it is possible to improve this example even more by
adding second stage quantizer? Something like to make centroid of centroids ?

first stage:
quantizer = faiss.IndexFlatL2(d)  # the other index
index = faiss.IndexIVFFlat(quantizer, d, nlist)

second stage like this? ( just as an example, really not working )
quantizer = faiss.IndexFlatL2(d)  # the other index
quantizer2 = faiss.IndexFlatL2(quantizer)  # the other index
index = faiss.IndexIVFFlat(quantizer2, d, nlist)

**Comment by mdouze** [comment]
Because the question came up several times, I added a FAQ entry about this: 
https://github.com/facebookresearch/faiss/wiki/FAQ#why-is-multi-level-ivf-search-not-supported-in-faiss

**Comment by batrlatom** [comment]
thanks
