### ISSUE TITLE
The searching efficiency of faiss on GPU puzzles me

### ISSUE THREAD

**Issue by yyy007** [facebookresearch/faiss#115]
I am running a 'gpuIndexIVFPQ' test. The result shows that searching with 'nprobe=1' is slower than with 'nprobe=5 or 10'. Why I did not get the increasing time-consuming with increasing searching centres?
Here is the main code:
`faiss::gpu::GpuIndexIVFPQ index (
         &resources, dev_no, d,
         ncentroids, 32, 8, true,
         faiss::gpu::INDICES_64_BIT,
         false,
         faiss::METRIC_L2);

    {//training
        index.verbose = true;
        index.train (nb, xb);
    }
	index.add(nb, xb);

	int k = 1;
	struct timeval start;
	struct timeval end;
	unsigned long diff;

	//nprobe = 1
	index.setNumProbes(1);
	std::vector<faiss::Index::idx_t> nns(k * nq);
	std::vector<float>               dis(k * nq);
	gettimeofday(&start, NULL);
	index.search(nq, xq, k, dis.data(), nns.data());
	gettimeofday(&end, NULL);
	diff = 1000000 * (end.tv_sec - start.tv_sec) + end.tv_usec - start.tv_usec;
	printf("Searching time is(nprobe=1) %ld us!\n", diff);`
Here is the result:
`Searching time is(nprobe = 1) 15016 us!
	Searching time is(nprobe = 5) 7311 us!
	Searching time is(nprobe = 10) 9814 us!`
My basedata contains 18000 vectors with 800-dimension, the querydata contains 1000 vectors. The system is Ubuntn 14.04, the gpu is two Tesla K40c.

**Comment by wickedfoo** [comment]
You only appear to be timing a single run. For performance analysis, I'd time multiple runs and look at the distribution.

**Comment by yyy007** [comment]
@wickedfoo Thank you for replying me!
Here is my complete test code:
`#include < cmath>
#include < cstdio>
#include < cstdlib>

#include "../StandardGpuResources.h"
#include "../GpuIndexIVFPQ.h"

#include "../GpuAutoTune.h"
#include "../../index_io.h"

#include < iostream>
#include < fstream>
#include < sys/time.h>
#include < unistd.h>
using namespace std;


int main ()
{
    // dimension of the vectors to index
    int d = 800;

    // size of the database we plan to index
    size_t nb = 18000;
    size_t nq = 1000;

    float *xb = new float[d * nb];
    float *xq = new float[d * nq];

    ifstream datafile1("/home/user/faiss/gpu/test/TestData/NormDataG.txt", ios::in);
	if (!datafile1)
	{
		cout << "BaseData is not exist!" << endl;
		return -1;
	}
	int i = 0;
	while (!datafile1.eof())
	{
		datafile1 >> xb[i];
		i++;
	}
	datafile1.close();
    cout << "Get BaseData Finished!" << endl;
	ifstream datafile2("/home/user/faiss/gpu/test/TestData/NormDataP.txt", ios::in);
	if (!datafile2)
	{
		cout << "QueryData is not exist!" << endl;
		return -1;
	}
	int j = 0;
	while (!datafile2.eof())
	{
		datafile2 >> xq[j];
		j++;
	}
	datafile2.close();
    cout << "Get QueryData Finished!" << endl;

    int dev_no = 1;

    // a reasonable number of centroids to index nb vectors
    int ncentroids = int (4 * sqrt (nb));

    faiss::gpu::StandardGpuResources resources;

    // the coarse quantizer should not be dealloced before the index
    // 4 = nb of bytes per code (d must be a multiple of this)
    // 8 = nb of bits per sub-code (almost always 8)
    faiss::gpu::GpuIndexIVFPQ index (
         &resources, dev_no, d,
         ncentroids, 32, 8, false,
         faiss::gpu::INDICES_64_BIT,
         false,
         faiss::METRIC_L2);

    { // training

        index.verbose = true;

        index.train (nb, xb);
    }

    {
        printf ("Adding the vectors to the index!\n");

        index.add (nb, xb);
    }

    { // searching the database
        int k = 1;

        struct timeval start1;
        struct timeval end1;
        unsigned long diff1;
        // nprobe = 1
        index.setNumProbes(1);
        printf ("Searching with nprobe=1!\n");
        std::vector<faiss::Index::idx_t> nns1 (k * nq);
        std::vector<float>               dis1 (k * nq);
        gettimeofday(&start1,NULL);
        index.search (nq, xq, k, dis1.data(), nns1.data());
        gettimeofday(&end1,NULL);
        diff1=1000000*(end1.tv_sec-start1.tv_sec)+ end1.tv_usec-start1.tv_usec;
        printf ("Searching time is(nprobe=1) %ld us!\n",diff1);
        ofstream outfile1;
	    outfile1.open("/home/user/faiss/gpu/test/TestResult/IVFPQ1.txt");
	    for (int i = 0; i < nq; i++)
	    {
	    	for (int j = 0; j < k; j++)
	    	{
		    	outfile1 << nns1[k * i + j];
			    if (i < (nq-1))
			    {
			    	outfile1 << endl;
			    }
		    }
	    }
	    outfile1.close();

        struct timeval start2;
        struct timeval end2;
        unsigned long diff2;
        // nprobe = 5
        index.setNumProbes(5);
        printf ("Searching with nprobe=5!\n");
        std::vector<faiss::Index::idx_t> nns2 (k * nq);
        std::vector<float>               dis2 (k * nq);
        gettimeofday(&start2,NULL);
        index.search (nq, xq, k, dis2.data(), nns2.data());
        gettimeofday(&end2,NULL);
        diff2=1000000*(end2.tv_sec-start2.tv_sec)+ end2.tv_usec-start2.tv_usec;
        printf ("Searching time is(nprobe=5) %ld us!\n",diff2);
        printf ("Searching done!\n");
        ofstream outfile2;
	    outfile2.open("/home/user/faiss/gpu/test/TestResult/IVFPQ5.txt");
	    for (int i = 0; i < nq; i++)
	    {
	    	for (int j = 0; j < k; j++)
	    	{
		    	outfile2 << nns2[k * i + j];
			    if (i < (nq-1))
			    {
			    	outfile2 << endl;
			    }
		    }
	    }
	    outfile2.close();

        struct timeval start3;
        struct timeval end3;
        unsigned long diff3;
		// nprobe = 10
        index.setNumProbes(10);
        printf ("Searching with nprobe=10!\n");
        std::vector<faiss::Index::idx_t> nns3 (k * nq);
        std::vector<float>               dis3 (k * nq);
        gettimeofday(&start3,NULL);
        index.search (nq, xq, k, dis3.data(), nns3.data());
        gettimeofday(&end3,NULL);
        diff3=1000000*(end3.tv_sec-start3.tv_sec)+ end3.tv_usec-start3.tv_usec;
        printf ("Searching time is(nprobe=10) %ld us!\n",diff3);
        printf ("Searching done!\n");
        ofstream outfile3;
	    outfile3.open("/home/user/faiss/gpu/test/TestResult/IVFPQ10.txt");
	    for (int i = 0; i < nq; i++)
	    {
	    	for (int j = 0; j < k; j++)
	    	{
		    	outfile3 << nns3[k * i + j];
			    if (i < (nq-1))
			    {
			    	outfile3 << endl;
			    }
		    }
	    }
	    outfile3.close();
    }
    delete [] xb;
    delete [] xq;

    return 0;
}`

**Comment by mdouze** [comment]
Hi

Closing this issue. Please make a new issue with a short reproduction if the problem reappears.
