### ISSUE TITLE
Index for images

### ISSUE THREAD

**Issue by KantareddySaiSandeep** [facebookresearch/faiss#1150]
Hi, what is the best index for using faiss on images. Using indexflatIP the similarity of images aren't good. Is there any specific indexes such that I can use it for images.
Thank you.

**Comment by wickedfoo** [comment]
Constructing a vector representation appropriate for an image (e.g., from SIFT vectors, CNN features or something else) is outside the scope of the Faiss library. These vector representations can be passed to a Faiss index, but how these are generated is up to you.

**Comment by KantareddySaiSandeep** [comment]
I have already constructed the image vector from VGG16 architecture that is (224,224,3). As I mentioned I am also getting similar images for the given images but my question is which index can be used for better similarity of images as you know the faiss has lot of different indexes.

**Comment by mdouze** [comment]
The answer is the same as for generic vectors see: https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index

**Comment by KantareddySaiSandeep** [comment]
Okay thank you.
