### ISSUE TITLE
Fatal error: Faiss/IndexIndexIVFPQ.h file not found

### ISSUE THREAD

**Issue by xuanvinh1997** [facebookresearch/faiss#1154]
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [x] Python

# Reproduction instructions

I built Faiss from source. When I used python interface, libfaiss run normally. But I used it in C++:
#include <faiss/IndexIVFPQ.h>
#include <faiss/gpu/GpuIndexFlat.h>
then error's thrown:
Fatal error: Faiss/IndexIndexIVFPQ.h file not found
(sorry for my English not good! I'm new C++ developer)

**Comment by mdouze** [comment]
IndexIndexIVFPQ.h does not exist. Please check where it is mentioned.
