### ISSUE TITLE
Python 3 Kmeans error in train

### ISSUE THREAD

**Issue by oguitart** [facebookresearch/faiss#1156]
# Summary

When I try to use faiss Kmeans in python3 I get this error:

kmeans.train(self.data)
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/faiss/__init__.py", line 678, in train
    clus = Clustering(d, self.k, self.cp)
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/faiss/swigfaiss.py", line 1199, in __init__
    this = _swigfaiss.new_Clustering(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_Clustering'.
  Possible C/C++ prototypes are:
    faiss::Clustering::Clustering(int,int)
    faiss::Clustering::Clustering(int,int,faiss::ClusteringParameters const &)

OS: Ubuntu 16.04

Faiss version: 1.6.1

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

I use the typical code that you provide in your tutorial

**Comment by oguitart** [comment]
Sorry the problem was k was not a integer.

**Comment by SharangKaul123** [comment]
@oguitart Hey! I am also getting an error similar to this. What did you change in the code? Also, I am running the cluster mode for now at the beginning before the training mode.

===> Loading dataset(s)
===> Building model
===> Calculating descriptors and clusters
====> Extracting Descriptors
====> Clustering..
Traceback (most recent call last):
  File "main.py", line 496, in <module>
    get_clusters(whole_train_set)
  File "main.py", line 279, in get_clusters
    kmeans.train(dbFeat[...])
  File "/home/kau4hi/gpu_anaconda3/lib/python3.6/site-packages/faiss/__init__.py", line 734, in train
    clus.train(x, self.index, weights)
  File "/home/kau4hi/gpu_anaconda3/lib/python3.6/site-packages/faiss/__init__.py", line 85, in replacement_train
    self.train_c(n, swig_ptr(x), index)
  File "/home/kau4hi/gpu_anaconda3/lib/python3.6/site-packages/faiss/swigfaiss_avx2.py", line 1477, in train
    return _swigfaiss_avx2.Clustering_train(self, n, x, index, x_weights)
NotImplementedError: Wrong number or type of arguments for overloaded function 'Clustering_train'.
  Possible C/C++ prototypes are:
    faiss::Clustering::train(faiss::Clustering::idx_t,float const *,faiss::Index &,float const *)
    faiss::Clustering::train(faiss::Clustering::idx_t,float const *,faiss::Index &)

**Comment by oriolcmp** [comment]
As I said in the closing comment the problem was that the passed parameter was not in the right format. In my case, it was not an integer, probably it was a float

**Comment by SharangKaul123** [comment]
Yeah! I got it. But in my case, I am not able to resolve the issue. The format in my case is already as float32. I also went through this (https://github.com/facebookresearch/faiss/issues/1417). But don't know what is the error?
