### ISSUE TITLE
Fix merge_into usage mistake

### ISSUE THREAD

**Issue by danielmoreira** [facebookresearch/faiss#1158]
# Summary
Dear all,

I've given "False" to the third parameter of "faiss.merge_into" by mistake (I've just figured out I should have used "True", to properly shift feature IDs of the second index).
As a consequence, I have features mapping to the same ID by mistake.

Besides rebuilding the original indices and merging them again, this time using the correct parameter values, is there any other way to fix/update the IDs within the merged index, with no index rebuilding? Let's say, shifting the IDs of all features that previously belonged to the second original index, within the new merged one? Is this possible? Is there a data structure within your data model that stores the order/time of the added indices due to merging?

Please let me know if you need any clarification.

Thanks in advance for your attention and for sharing FAISS with the community,
Daniel.

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
That is hard.... because you need to be able to differentiate the ids from several adds. 
There is no metadata that can be used.
What about re-running the whole process?

**Comment by danielmoreira** [comment]
Interesting, thanks for your answer.
That's what I had to do, in the end (re-running the whole process).
Best, Daniel.
