### ISSUE TITLE
IVF index with Hashtable direct map and add (without ids) doesn't work

### ISSUE THREAD

**Issue by derekehyatt** [facebookresearch/faiss#1165]
# Summary

IVF indices with Hashtable direct map type and add (without ids) does not work.
The issue is [this line](https://github.com/facebookresearch/faiss/blob/v1.6.3/IndexBinaryIVF.cpp#L85) where (if no ids are provided) we default to the ntotal + 1. This works for Array direct maps, but (after a removal) it will start overwriting previously inserted values for Hashtable direct maps. For Hashtable direct maps we would have to track nadded and have the default be nadded + 1

You can fix this issue by simply switching to add_with_ids and keep a counter yourself, but I wanted to post to make sure no one else runs into this issue.

# Platform

Faiss version: 1.6.3

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

```
import numpy as np
import faiss

dimension = 256
rs = np.random.RandomState(1234)
index = faiss.IndexBinaryIVF(faiss.IndexBinaryFlat(dimension), dimension, 1)
index.set_direct_map_type(faiss.DirectMap.Hashtable)
db = rs.randint(256, size=(1, 32), dtype=np.uint8)
index.train(db)
index.add(db)
index.add(rs.randint(256, size=(1, 32), dtype=np.uint8))
recon0 = index.reconstruct(0)
recon1 = index.reconstruct(1)
to_remove = np.array([0])
to_remove = faiss.IDSelectorArray(len(to_remove), faiss.swig_ptr(to_remove))
index.remove_ids(to_remove)
assert np.array_equal(recon1, index.reconstruct(1))
index.add(rs.randint(256, size=(1, 32), dtype=np.uint8))
# this assertion fails, id 1 has been overwritten with the above new value
assert np.array_equal(recon1, index.reconstruct(1))
```

**Comment by mdouze** [comment]
There is a semantic difference between removing ids between flat and IVF indexes, that is explained here: 
https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes#removing-elements-from-an-index
And indeed it is hard to make it work consistently. In any case, we don't plan to add a state variable (nadded) to the index that handles this case, it's the user's responsibility.

**Comment by derekehyatt** [comment]
@mdouze It totally makes sense not to add an additional state variable, I think a better solution is just to not support add (without ids) into a Hashtable direct map:
```
void DirectMap::check_can_add (const idx_t *ids) {
    if (type == Array && ids) {
        FAISS_THROW_MSG ("cannot have array direct map and add with ids");
    } else if (type == Hashtable && !ids) {
        FAISS_THROW_MSG ("cannot have hashtable direct map and add (without ids)")      
    }
}
```
This will make sure that users don't accidentally overwrite their previously indexed values and it will make it clear that they need to track the ids themselves.

**Comment by mdouze** [comment]
Not sure I want to enforce this. There may be use cases where people want to mix `add` and `add_with_ids`. They are also used to reconstruct vectors.

**Comment by derekehyatt** [comment]
Yeah that's understandable. My thoughts for enforcing this are:
- If users are not interested in using reconstruction (NoMap, which is the default behavior) or they are using an Array direct map, this will not effect them. 
- If users use Hashtable with add then once they remove anything from the index, they will start overwriting previously inserted values.
- If users don't remove anything from the index, then the proposed change will require them to change their code. But all that they will have to do is add an incrementing counter to their additions, which is not difficult. Similarly if they mix add and add_with_ids they could track with a counter.

To me the overwriting indexed values is much more difficult to track down and understand than being required to track id insertions yourself (for Hashtable type only). Like I said, if you decide not to change this functionality, I totally understand, just wanted to provide more of my reasoning. What do you think?
Thanks!

**Comment by mdouze** [comment]
Thanks for the comments, but this does not seem enough to change the behaviour.
Closing.

**Comment by yuyifan1991** [comment]
I cannot reconstruct vectors by _index.set_direct_map_type(faiss.DirectMap.Hashtable)_. I use the IndexIVFFlat and already created the index. The error is : _AttributeError: 'IndexIVFFlat' object has no attribute 'set_direct_map_type'_
