### ISSUE TITLE
Acceleration issues on aarch64/arm64

### ISSUE THREAD

**Issue by Jowekk** [facebookresearch/faiss#1166]
# Summary

In distances_simd.cpp, there is no significant difference in speed between the implementation on aarch64 and the scalar implementation?
# Platform
aarch64

Running on:
- [✓] CPU
- [ ] GPU

Interface: 
- [✓] C++
- [ ] Python

aarch64 implementation
`
float fvec_L2sqr (const float * x,
                  const float * y,
                  size_t d)
{
    if (d & 3) return fvec_L2sqr_ref (x, y, d);
    float32x4_t accu = vdupq_n_f32 (0);
    for (size_t i = 0; i < d; i += 4) {
        float32x4_t xi = vld1q_f32 (x + i);
        float32x4_t yi = vld1q_f32 (y + i);
        float32x4_t sq = vsubq_f32 (xi, yi);
        accu = vfmaq_f32 (accu, sq, sq);
    }
    float32x4_t a2 = vpaddq_f32 (accu, accu);
    return vdups_laneq_f32 (a2, 0) + vdups_laneq_f32 (a2, 1);
}

float fvec_inner_product (const float * x,
                          const float * y,
                          size_t d)
{
    if (d & 3) return fvec_inner_product_ref (x, y, d);
    float32x4_t accu = vdupq_n_f32 (0);
    for (size_t i = 0; i < d; i += 4) {
        float32x4_t xi = vld1q_f32 (x + i);
        float32x4_t yi = vld1q_f32 (y + i);
        accu = vfmaq_f32 (accu, xi, yi);
    }
    float32x4_t a2 = vpaddq_f32 (accu, accu);
    return vdups_laneq_f32 (a2, 0) + vdups_laneq_f32 (a2, 1);
}

float fvec_norm_L2sqr (const float *x, size_t d)
{
    if (d & 3) return fvec_norm_L2sqr_ref (x, d);
    float32x4_t accu = vdupq_n_f32 (0);
    for (size_t i = 0; i < d; i += 4) {
        float32x4_t xi = vld1q_f32 (x + i);
        accu = vfmaq_f32 (accu, xi, xi);
    }
    float32x4_t a2 = vpaddq_f32 (accu, accu);
    return vdups_laneq_f32 (a2, 0) + vdups_laneq_f32 (a2, 1);
}

// not optimized for ARM
void fvec_L2sqr_ny (float * dis, const float * x,
                        const float * y, size_t d, size_t ny) {
    fvec_L2sqr_ny_ref (dis, x, y, d, ny);
}

float fvec_L1 (const float * x, const float * y, size_t d)
{
    return fvec_L1_ref (x, y, d);
}

float fvec_Linf (const float * x, const float * y, size_t d)
{
    return fvec_Linf_ref (x, y, d);
}`

scalar implementation
`

float fvec_L2sqr (const float * x,
                  const float * y,
                  size_t d)
{
    return fvec_L2sqr_ref (x, y, d);
}

float fvec_L1 (const float * x, const float * y, size_t d)
{
    return fvec_L1_ref (x, y, d);
}

float fvec_Linf (const float * x, const float * y, size_t d)
{
    return fvec_Linf_ref (x, y, d);
}

float fvec_inner_product (const float * x,
                             const float * y,
                             size_t d)
{
    return fvec_inner_product_ref (x, y, d);
}

float fvec_norm_L2sqr (const float *x, size_t d)
{
    return fvec_norm_L2sqr_ref (x, d);
}

void fvec_L2sqr_ny (float * dis, const float * x,
                        const float * y, size_t d, size_t ny) {
    fvec_L2sqr_ny_ref (dis, x, y, d, ny);
}`

**Comment by mdouze** [comment]
We don't have access anymore to aarch64 hardware. 
Could you post benchmark results and make sure by decompiling the code that the SIMD codepath is used indeed?

**Comment by Jowekk** [comment]
Sorry, I made a mistake during the test. Now I retest and found that when the vector dimension is small, the performance is significantly different.

**Comment by Jowekk** [comment]
This is a simple test result, the time unit is second.

n = 64 | fvec_L2_sqr | fvec_inner_product
-- | -- | --
scalar implementation | 1.10E-04 | 1.00E-04
aarch64 implementation | 1.30E-05 | 9.00E-06

**Comment by mdouze** [comment]
Perf is as expected. 
Closing issue.
