### ISSUE TITLE
[Question] Should search by range return -1 in case there is not enough results?

### ISSUE THREAD

**Issue by yana2301** [facebookresearch/faiss#1167]
According to documentation, search by count returns -1s in labels array if there are not enough vectors in response. 
Should search by range method return -1s instead of labels in case there are enough vectors?
I'm using C API for both search by range and search by count.

**Comment by Enet4** [comment]
While I cannot answer the answer directly (I am not familiar with all of the index implementations), the presence of `-1` vector identifiers aligns with the of the output slices being provided by the caller of `search`; they are allocated in advance for the expected `n` vectors per query. In `range_search`, the results are allocated by the callee to accommodate the matching vectors. The implementation of `RangeSearchResult` even admits a variable length of results for query.

As such, it is intuitive to believe that there won't be any `-1` IDs, but I'm not sure if this can be relied on by the API.
For what it's worth, the C API (as well as my Rust bindings) make no type distinction between an ID that might not point to a particular vector and an ID which is sure to point to one.

**Comment by yana2301** [comment]
@Enet4  thanks for the response! However, I still wonder if there is any way to understand that labels in RangeSearchResult do not correspond to actual vector labels. 
I'm running the 2 queries on the same index. Query vectors are the same. Search by count returns -1's. Search by range returns some non-existing ids, maybe that's because labels array in RangeSearchResult struct hasn't been initialized at all.

**Comment by Enet4** [comment]
Can you provide a minimal example where that effect can be reproduced?

**Comment by mdouze** [comment]
@yana2301  "Search by range returns some non-existing ids": this is a bug. Indeed please post minimal code that reproduces this.

**Comment by yana2301** [comment]
@Enet4 @mdouze  please find the example below: 
I'm using C API via Java native runtime(jnr library). Below isn't the exact code, rather list of commands that I run: 
1. Code for index creation: 

`FaissIndex* quantizer = NULL;
 FaissIndexIVFFlat* index = NULL;
  FAISS_TRY(faiss_IndexFlat_new_with(&quantizer, dimension, METRIC_INNER_PRODUCT));
 FAISS_TRY(faiss_IndexIVFFlat_new_with_metric(&index, quantizer, dimension, nlist,  
 METRIC_INNER_PRODUCT));
 FAISS_TRY(faiss_Index_train(index, vector_count, vectors));
 FAISS_TRY(faiss_Index_add_with_ids(index, vector_count, vectors, ids));`

2. Code for querying index:

`FaissRangeSearchResult* result = NULL;
//labels and distances are not created - the array is initialized in java. Both are arrays of [limit*query_size]
 FAISS_TRY(faiss_RangeSearchResult_new_with(&result, query_size, limit));

 FAISS_TRY(faiss_Index_range_search(index, query_size, query, radius, result));
 faiss_RangeSearchResult_labels_getter(result, labels, distances);`

faiss_RangeSearchResult_labels_getter - I added a method that accepts direct pointers to AuxIndexStructures.h/cpp - since it was easier for me to work with direct pointers. However, I've got same results when pass pointers to pointers. Please note that it's not result of wrong array conversion between Java and C - I tried printing array in C++ code and got same incorrect results. 
Note that If I run search by count with same vectors in query - I get -1's in response.
I tried different values for radius - no matter what I pass, I wouldn't get correct results.


Input vectors, query and changed AuxIndexStructures files are attached. 

[input_vectors.csv.zip](https://github.com/facebookresearch/faiss/files/4416351/input_vectors.csv.zip)

[AuxIndexStructures.zip](https://github.com/facebookresearch/faiss/files/4416355/AuxIndexStructures.zip)

[query.txt](https://github.com/facebookresearch/faiss/files/4416379/query.txt)

**Comment by mdouze** [comment]
Sorry but this is not self-contained code in C++ or Python so I can't repro.
Closing for now. Feel free to re-open if you can provide a repro.
