### ISSUE TITLE
ScalarQuantizer doesn't support remove_ids

### ISSUE THREAD

**Issue by fengsky401** [facebookresearch/faiss#1168]
```
import faiss
import numpy as np

quantizer = faiss.index_factory(512,"PCAR256,IDMap,SQ8")
print(quantizer)
quant1 = faiss.downcast_index(quantizer.index)
print(quant1)
quant2 = faiss.downcast_index(quant1.index)
print(quant2)

xb = np.load("xb.npy")
quantizer.train(xb)
quantizer.add_with_ids(xb,np.arange(1000))
print(quantizer.ntotal)
query_array = np.zeros([1,512],dtype=np.float32)

quantizer.remove_ids(np.arange(709,710))
```

I tried index_factory with "PCAR256,IDMap,Flat","PCAR256,IDMap,PQ8" , the codes all work.
When I try with "PCAR256,IDMap,SQ8", it reports :
RuntimeError: Error in virtual size_t faiss::Index::remove_ids(const faiss::IDSelector&) at Index.cpp:52: remove_ids not implemented for this type of index

So if I use scalarquantization,  how do I remove ids from the index?

**Comment by mdouze** [comment]
Right, remove_ids is not implemented for IndexScalarQuantizer. 
I'll mark it as an enhancement, no guarantee on when it will be added.

**Comment by fengsky401** [comment]
> Right, remove_ids is not implemented for IndexScalarQuantizer.
> I'll mark it as an enhancement, no guarantee on when it will be added.

If I add remove_ids function in IndexScalarQuantizer.h and  IndexScalarQuantizer.cpp like IndexPQ::remove_ids by myself, what's consideration should I take?

**Comment by mdouze** [comment]
See the implementation for the Flat index: 
https://github.com/facebookresearch/faiss/blob/master/IndexFlat.cpp#L105

**Comment by fengsky401** [comment]
> See the implementation for the Flat index:
> https://github.com/facebookresearch/faiss/blob/master/IndexFlat.cpp#L105

I noticed that in IndexFlat or IndexPQ, the removal operation shifts the ids of vectors above the removed vector id.
If I don't want the ids of other vectors changed, which implementation can I take as a reference?

**Comment by ramilbakhshyiev** [comment]
Confirmed that `remove_ids()` works with scaled quantizers (implemented in [IndexFlatCodes](https://github.com/facebookresearch/faiss/blob/252ae16ea371ca861663db3fcae02cbe40deef05/faiss/IndexFlatCodes.cpp#L42)]). Modified test case used:
```
d, n = 512, 2500
quantizer = faiss.index_factory(d, "PCAR256,IDMap,SQ8")
db_vectors = np.random.random((n, d)).astype('float32')

quantizer.train(db_vectors)
quantizer.add_with_ids(db_vectors, np.arange(n))

quantizer.remove_ids(np.arange(709, 710))
```
