### ISSUE TITLE
Segmentation fault on write index L1

### ISSUE THREAD

**Issue by biarne-a** [facebookresearch/faiss#1169]
# Summary

A call to the method faiss.write_index for a flat index build with a METRIC_L1 results in a segmentation fault (for any number of indexed vectors of any dimension). A small example has been attached with the issue.

# Platform

OS: 

Faiss version:  1.6.1

Faiss compilation options: 

Running on:
- [X ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X ] Python

# Reproduction instructions

Very easy to reproduce see below:
```
import faiss
import numpy as np


xb = np.random.randn(10, 10).astype(np.float32)
index = faiss.IndexFlat(10, faiss.METRIC_L1)
index.add(xb)

faiss.write_index(index, 'index.index')
```

This results in a segmentation fault

**Comment by mdouze** [comment]
Can't repro in 1.6.3, please upgrade.
There was a bug in 1.6.1 on serialization of "alternative distance" flat indexes. It may be related to that, although it seems surprising that it produces a segfault.

**Comment by biarne-a** [comment]
Thank you for the quick reply.
I upgrade to 1.6.3 and it works like a charm.
