### ISSUE TITLE
FAISS installation in ubuntu server 16

### ISSUE THREAD

**Issue by cartal** [facebookresearch/faiss#117]
So, I have been browsing almost all the internet and haven't found the reason of this error. And although it may be a rookie mistake and I may be risking a huge facepalm from the developers, here it is:

I can't compile FAISS. I have modified the make.in.Linux file accordingly, but when I type make, I got the following error:

makefile.inc:66: *** missing separator. Stop.

It doesn't matter what I do, I always get the same error. 

I have checked for wrongly placed tabs, or other potential mistakes of mine. But I can't see it. 

Any help will be greatly appreciated.

**Comment by cartal** [comment]
Issue has been solved!

**Comment by sk-ubuntu** [comment]
I am also having the same issue. Could you please tell me what you did to remove that error.

Thanks.
