### ISSUE TITLE
Slow CUDA initialization with FAISS

### ISSUE THREAD

**Issue by bmccann** [facebookresearch/faiss#1177]
# Summary
```
Python 3.7.7 
[GCC 7.3.0] :: Anaconda, Inc. on linux
torch.__version__
'1.4.0'
faiss.__version__
'1.6.3'
```

Running on:
- [ ] GPU

Interface: 
- [ ] Python

# Reproduction instructions

Dockerfile
```
FROM nvidia/cuda:10.1-runtime-ubuntu16.04

RUN apt-get update \
        && apt-get install -y --no-install-recommends \
            git \
            ssh \
            build-essential \
            locales \
            ca-certificates \
            curl \
            unzip \
            vim \
            wget

RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh && \
     /opt/conda/bin/conda install conda-build python=3.7 && \
     /opt/conda/bin/conda clean -ya
ENV PATH /opt/conda/bin:$PATH

# Default to utf-8 encodings in python
# Can verify in container with:
# python -c 'import locale; print(locale.getpreferredencoding(False))'
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN conda install pytorch cudatoolkit=10.0 -c pytorch
RUN conda install faiss-gpu cudatoolkit=10.0 -c pytorch
RUN conda install tensorboard nltk numpy tqdm
RUN pip install sacrebleu transformers

CMD bash
```

minimum_example.py
```
import torch
import timeit
import faiss


t0 = timeit.default_timer()
if torch.cuda.is_available():
    torch.cuda.manual_seed(2809)
    torch.backends.cudnn.deterministic = True
    device = torch.device('cuda:0')
    ngpus = torch.cuda.device_count()
    print("Using {} GPU(s)...".format(ngpus))
    torch.randn(1, device="cuda")
print("Setup takes {:.2f}".format(timeit.default_timer()-t0))
```

If I run `minimum_example.py` with  `import faiss` it takes 170+ seconds.
When run with `#import faiss` (faiss commented out), it takes 5 seconds.

Why does the cuda initialization take so much longer when faiss is imported?
Perhaps related to https://github.com/facebookresearch/faiss/issues/908, but didn't see any resolution there. 
Painful to have the script take 3 minutes to startup every time I run it while debugging.

**Comment by wickedfoo** [comment]
What GPU (specifically, the CUDA compute capability) are you running with?

I wonder if it could be the case that it is having to JIT at runtime the CUDA kernels for your particular architecture.

**Comment by bmccann** [comment]
Quadro GV100 
Driver Version: 430.26
CUDA Version: 10.2

**Comment by wickedfoo** [comment]
@beauby What compute capability does `conda install faiss-gpu cudatoolkit=10.0 -c pytorch` use, or where does it get its compute capability from?

**Comment by beauby** [comment]
@wickedfoo https://github.com/facebookresearch/faiss/blob/master/conda/Dockerfile#L25 – let me know if you want to change it, I can rebuild the packages.

**Comment by mdouze** [comment]
Do you observe the same for other CUDA programs? 
We often see that when the cuda cache in ~/.nv is either not readable/writable or on a slow disk.

**Comment by bmccann** [comment]
That seems likely now. I haven't entirely confirmed this since there is nothing reporting a failed write to cache, but the evidence below suggests something like that:

I was running this inside a docker container, and having passed my user and group id, I was not root inside the container. Perhaps the permissions inside the container then prevented writing to the cuda cache, and so every single run had a very slow cuda initialization.

If I do not pass the user and group id (so that I am root inside the docker container), it looks like the first run takes about 3 minutes to initialize cuda, and then repeated initializations take a more typical 3 seconds.

Feel free to close this out, since it seems like something I'll have to figure out on the Docker side if I want to preserve user permissions inside the container while avoiding this cache issue.

**Comment by vblagoje** [comment]
@bmccann @mdouze @wickedfoo I had the slow CUDA initialization with a 15Gb index loaded in GPU. It would take half an hour to boot the Docker container. The solution is to boot it once and then [commit](https://www.thegeekdiary.com/how-to-update-add-a-file-in-the-docker-image/) the ComputeCache from ~/.nv to container disk. My container would boot in less than 3 minutes after this fix.
