### ISSUE TITLE
AttributeError: 'Clustering' object has no attribute 'obj'

### ISSUE THREAD

**Issue by neouyghur** [facebookresearch/faiss#1179]
# Summary

Hi, I am running the MNIST GPU Kmeans example. However, I got this error: "AttributeError: 'Clustering' object has no attribute 'obj'".   How can I solve this problem? thanks.

# Platform

OS: Ubuntu 18.04 

Faiss version: 1.6.3 

Faiss compilation options: I don't know. I installed it through PIP. 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
Right, this option was replaced. The fix is:

```
obj = np.array([clus.stats.at(i).obj for i in range(clus.stats.size())])
```
This example should be fixed to be py3 compatible btw.
Marking this as an enhancement.

**Comment by kunalmessi10** [comment]
If I'm right, we're supposed to replace clus.obj by this obj as mentioned. After doing so, I'm getting another error,
AttributeError: 'Clustering' object has no attribute 'stats'. It is while running deepcluster.

**Comment by neouyghur** [comment]
@mdouze That is what I did after checking the kmeans code.

**Comment by MaryamHaghighat** [comment]
Is this issue solved?

**Comment by MaryamHaghighat** [comment]
> If I'm right, we're supposed to replace clus.obj by this obj as mentioned. After doing so, I'm getting another error,
> AttributeError: 'Clustering' object has no attribute 'stats'. It is while running deepcluster.

I have the same problem. Is this issue solved?

**Comment by kunalmessi10** [comment]
I don't know exactly, but this error can removed by downgrading to faiss version 1.6.1.
pip install faiss-gpu==1.6.1
or pip install faiss==1.6.1

**Comment by mdouze** [comment]
Sorry the code above should be 
```
stats = clus.iteration_stats
obj = np.array([stats.at(i).obj for i in range(stats.size())])
```

stats = clus.iteration_stats

**Comment by neouyghur** [comment]
I pased my full code here. It might be useful:
```
def run_kmeans(x, nmb_clusters, verbose=False):
    """Runs kmeans on 1 GPU.
    Args:
        x: data
        nmb_clusters (int): number of clusters
    Returns:
        (list: ids of data in each cluster, float: loss value)
    """
    n_data, d = x.shape

    # faiss implementation of k-means
    clus = faiss.Clustering(d, nmb_clusters)

    # Change faiss seed at each k-means so that the randomly picked
    # initialization centroids do not correspond to the same feature ids
    # from an epoch to another.
    clus.seed = np.random.randint(1234)

    clus.niter = 20
    clus.max_points_per_centroid = 10000000
    res = faiss.StandardGpuResources()
    flat_config = faiss.GpuIndexFlatConfig()
    flat_config.useFloat16 = False
    flat_config.device = 0
    index = faiss.GpuIndexFlatL2(res, d, flat_config)

    # perform the training
    clus.train(x, index)
    _, I = index.search(x, 1)

    # losses = faiss.vector_to_array(clus.obj)

    stats = clus.iteration_stats
    losses = np.array([
        stats.at(i).obj for i in range(stats.size())
    ])


    if verbose:
        print('k-means loss evolution: {0}'.format(losses))

    return [int(n[0]) for n in I], losses[-1]
```

**Comment by neouyghur** [comment]
@kunalmessi10 This problem is only valid for newer version. The code has been changed in the newer version. Downgrading will be work, but I don't recommend it.
