### ISSUE TITLE
how to compile FAISS files(eg: faiss.framework) for iOS system? 

### ISSUE THREAD

**Issue by lqhart** [facebookresearch/faiss#1181]
how to compile FAISS files(eg: faiss.framework) for iOS system?  

Can anyone give me any idea?

Thank you,

**Comment by mdouze** [comment]
See
https://github.com/facebookresearch/faiss/projects/3
The main blocker is that calling BLAS with Fortran conventions is not supported on iOS.

**Comment by lqhart** [comment]
@mdouze After clicking the link, it displayed the following message :"This project doesn’t have any columns or cards."

I have searched the following Demo :

 https://github.com/opedge/FaissExample

Unfortunately ,it can't run  as there are a lot of compile errors in the faiss.framework,I have noticed the Opedge , who is the author of this demo, compiled the v 1.2.1 of faiss successfully. I am struggling to compile this version now.  Do you have any good idea to continue this work?

**Comment by mdouze** [comment]
Please ask the creator of opedge. We don't support iOS currently.

**Comment by lqhart** [comment]
Thank you for your message. I am not sure what the "Fortran conventions" is , I found it on google :https://alm.engr.colostate.edu/cb/wiki/16983, i think this is incorrect.

Could you please let me know the detail of "Fortran conventions"? 
 I will try to find the new  alternative solution.

Thank you,

**Comment by mdouze** [comment]
See eg here the fortran version of the BLAS functions: 
https://github.com/facebookresearch/faiss/blob/master/VectorTransform.cpp#L34
the C version is defined in cblas.

**Comment by lqhart** [comment]
@mdouze  On iOS, Accelerate.framework  provides the BLAS API with the fortran wrapping conventions in which we can also find the  sgemm, ssyrk etc. function used in VectorTransform.cpp.
Here is the BLAS's link of apple documents :

https://developer.apple.com/documentation/accelerate/blas.

There are several BLAS implementations, why don't we use the BLAS Supported  iOS ?
Here is another alternative solution where we can also find described things regarding  information supported iOS.

https://github.com/xianyi/OpenBLAS

it would be great if you can let me know if it is possible to use them  as the new alternative solution.

Thanks you,

**Comment by mdouze** [comment]
What needs to be done to use the cblas interface is clear. 
However, it is not currently in our priorities.
Feel free to submit a PR if you implement it yourself.

**Comment by lqhart** [comment]
it means that it should work well if all the BLAS function  are replaced with Api of Accelerate.framework.

I would love to work on it. I  am going to compile and debug it from source code.

Could you please let me know what my first step is?

For now, I am using Mac, which IDE I should to use to debug your code?

how to debug  the source code ?

Thank you,

**Comment by mdouze** [comment]
Closing issue, feel free to re-open if there is news.

**Comment by jkrukowski** [comment]
I'm working on Swift bindings for Faiss, you can see the current progress here https://github.com/jkrukowski/SwiftFaiss any feedback is appreciated!
