### ISSUE TITLE
make py gives multiple errors

### ISSUE THREAD

**Issue by manishagate** [facebookresearch/faiss#1184]
# Summary

# Platform

OS:  Ubuntu 16.04 LTS

Faiss version:  

Faiss compilation options:  ./configure --without-cuda --with-python=python3.6m

###SWIG version = 3.0.12

Running on:
- [ .] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [. ] Python

# Reproduction instructions

 
 ### There are many lines of it. I have posted some of them  

swigfaiss.cpp:107213:56: error: expected ‘)’ before ‘;’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp3);
                                                        ^
swigfaiss.cpp:107214:7: error: ‘arg3’ was not declared in this scope
       arg3 = *temp;
       ^
swigfaiss.cpp:107215:39: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
       if (SWIG_IsNewObj(res3)) delete temp;
                                       ^
swigfaiss.cpp:107218:20: error: ‘arg3’ was not declared in this scope
   (arg1)->add(arg2,arg3);
                    ^
swigfaiss.cpp: In function ‘PyObject* _wrap_DistanceComputer___call__(PyObject*, PyObject*)’:
swigfaiss.cpp:107735:3: error: ‘idx_t’ was not declared in this scope
   idx_t arg2 ;
   ^
swigfaiss.cpp:107735:3: note: suggested alternative:
In file included from swigfaiss.cpp:3440:0:
/usr/local/include/faiss/IVFlib.h:49:22: note:   ‘faiss::ivflib::idx_t’
 typedef Index::idx_t idx_t;
                      ^
swigfaiss.cpp:107758:15: error: ‘temp’ was not declared in this scope
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
               ^
swigfaiss.cpp:107758:40: error: ‘idx_t’ does not name a type
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
                                        ^
swigfaiss.cpp:107758:46: error: expected ‘>’ before ‘*’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
                                              ^
swigfaiss.cpp:107758:46: error: expected ‘(’ before ‘*’ token
swigfaiss.cpp:107758:48: error: expected primary-expression before ‘>’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
                                                ^
swigfaiss.cpp:107758:56: error: expected ‘)’ before ‘;’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
                                                        ^
swigfaiss.cpp:107759:7: error: ‘arg2’ was not declared in this scope
       arg2 = *temp;
       ^
swigfaiss.cpp:107760:39: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
       if (SWIG_IsNewObj(res2)) delete temp;
                                       ^
swigfaiss.cpp:107763:39: error: ‘arg2’ was not declared in this scope
   result = (float)(arg1)->operator ()(arg2);
                                       ^
swigfaiss.cpp: In function ‘PyObject* _wrap_DistanceComputer_symmetric_dis(PyObject*, PyObject*)’:
swigfaiss.cpp:107774:3: error: ‘idx_t’ was not declared in this scope
   idx_t arg2 ;
   ^
swigfaiss.cpp:107774:3: note: suggested alternative:
In file included from swigfaiss.cpp:3440:0:
/usr/local/include/faiss/IVFlib.h:49:22: note:   ‘faiss::ivflib::idx_t’
 typedef Index::idx_t idx_t;
                      ^
swigfaiss.cpp:107775:9: error: expected ‘;’ before ‘arg3’
   idx_t arg3 ;
         ^
swigfaiss.cpp:107801:15: error: ‘temp’ was not declared in this scope
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
               ^
swigfaiss.cpp:107801:40: error: ‘idx_t’ does not name a type
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
                                        ^
swigfaiss.cpp:107801:46: error: expected ‘>’ before ‘*’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
                                              ^
swigfaiss.cpp:107801:46: error: expected ‘(’ before ‘*’ token
swigfaiss.cpp:107801:48: error: expected primary-expression before ‘>’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
                                                ^
swigfaiss.cpp:107801:56: error: expected ‘)’ before ‘;’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
                                                        ^
swigfaiss.cpp:107802:7: error: ‘arg2’ was not declared in this scope
       arg2 = *temp;
       ^
swigfaiss.cpp:107803:39: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
       if (SWIG_IsNewObj(res2)) delete temp;
                                       ^
swigfaiss.cpp:107814:15: error: ‘temp’ was not declared in this scope
       idx_t * temp = reinterpret_cast< idx_t * >(argp3);
               ^
swigfaiss.cpp:107814:40: error: ‘idx_t’ does not name a type
       idx_t * temp = reinterpret_cast< idx_t * >(argp3);
                                        ^
swigfaiss.cpp:107814:46: error: expected ‘>’ before ‘*’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp3);
                                              ^
swigfaiss.cpp:107814:46: error: expected ‘(’ before ‘*’ token
swigfaiss.cpp:107814:48: error: expected primary-expression before ‘>’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp3);
                                                ^
swigfaiss.cpp:107814:56: error: expected ‘)’ before ‘;’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp3);
                                                        ^
swigfaiss.cpp:107815:7: error: ‘arg3’ was not declared in this scope
       arg3 = *temp;
       ^
swigfaiss.cpp:107816:39: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
       if (SWIG_IsNewObj(res3)) delete temp;
                                       ^
swigfaiss.cpp:107819:41: error: ‘arg2’ was not declared in this scope
   result = (float)(arg1)->symmetric_dis(arg2,arg3);
                                         ^
swigfaiss.cpp:107819:46: error: ‘arg3’ was not declared in this scope
   result = (float)(arg1)->symmetric_dis(arg2,arg3);
                                              ^
Makefile:22: recipe for target 'swigfaiss.o' failed
make[1]: *** [swigfaiss.o] Error 1
make[1]: Leaving directory '/extend_homes/manish/rta/third_party/faiss/python'
Makefile:83: recipe for target 'py' failed

### makefile.inc :

CXX          = g++ -std=c++11
CXXCPP       = g++ -std=c++11 -E
CPPFLAGS     = -DFINTEGER=int  -fopenmp
CXXFLAGS     = -fPIC -m64 -Wno-sign-compare -g -O3 -Wall -Wextra
CPUFLAGS     = -mpopcnt -msse4
LDFLAGS      = -fopenmp
LIBS         = -lopenblas
PYTHONCFLAGS =  -I/usr/include/python3.6m -I/usr/include/python3.6m -I
SWIGFLAGS    = -DSWIGWORDSIZE64

NVCC         =
CUDA_ROOT    =
CUDA_ARCH    = default
NVCCFLAGS    = -I $(CUDA_ROOT)/targets/x86_64-linux/include/ \
-Xcompiler -fPIC \
-Xcudafe --diag_suppress=unrecognized_attribute \
$(CUDA_ARCH) \
-lineinfo \
-ccbin $(CXX) -DFAISS_USE_FLOAT16

OS = $(shell uname -s)

SHAREDEXT   = so
SHAREDFLAGS = -shared

ifeq ($(OS),Darwin)
        SHAREDEXT   = dylib
        SHAREDFLAGS = -dynamiclib -undefined dynamic_lookup
        SWIGFLAGS   =
endif

MKDIR_P      = /bin/mkdir -p
PYTHON       = python3.6m
SWIG         = swig
AR          ?= ar

prefix      ?= /usr/local
exec_prefix ?= ${prefix}
libdir       = ${exec_prefix}/lib
includedir   = ${prefix}/include

**Comment by steplee** [comment]
I am having the same issue. Reverting to v1.5.0 seems to work. Any help with the newer versions would be appreciated.

**Comment by manishagate** [comment]
> I am having the same issue. Reverting to v1.5.0 seems to work. Any help with the newer versions would be appreciated.

Thanks for reply.

You mean SWIG version 1.5.0?

**Comment by steplee** [comment]
No, iirc I'm using SWIG 3.0.
I checked out the version v1.5.0 of faiss and it was able to build the python bindings and GPU code.
Wish they went with CMake and pybind11!

**Comment by manishagate** [comment]
It got resolved after I did following

> git checkout 

> git pull to latest master code

> ./configure --without-cuda --with-python=python3.6m

>make py

Thanks..!
