### ISSUE TITLE
Is it possible to set efSearch with IndexIDMap

### ISSUE THREAD

**Issue by JayYip** [facebookresearch/faiss#1188]
I have an index constructed by following code: 
```python
faiss.IndexIDMap(faiss.index_factory(
            100, 'HNSW32'))
```
Is it possible to set the hnsw parameter efSearch to this index? Thanks.

**Comment by JayYip** [comment]
Turns out I can use `faiss.downcast_index` to achieve that. 

Close.

**Comment by guigarfr** [comment]
@JayYip Could you give an example? I am trying to do the same thing... but for efConstruction
