### ISSUE TITLE
install issue: raise AttributeError: module 'faiss' has no attribute 'IndexFlatL2'

### ISSUE THREAD

**Issue by yydai** [facebookresearch/faiss#1195]
# Summary

# Platform

OS: ubuntu 16.04

Faiss version: faiss-cpu-1.6.3

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

 
1. install with the cmd:
 `conda create -n faiss python=3.6`
 `conda install faiss-cpu -c pytorch`
    
2.  When I run the code of  tutorial/python/1-Flat.py, raise the Error:
`Traceback (most recent call last):
  File "faiss.py", line 12, in <module>
    import faiss
  File "1-Flat.py", line 16, in <module>
    quantizer = faiss.IndexFlatL2(d)  # the other index
AttributeError: module 'faiss' has no attribute 'IndexFlatL2'`

 I have tried  **Compile from source** , it doesn't work too. 

Anyone can help me? Thanks!!!

**Comment by bixiaopeng0** [comment]
I have same question,how did you solve it?

**Comment by yydai** [comment]
Yes. I have this issue because I create a **faiss.py** file same as the package name.   Hope it helps you.

**Comment by bixiaopeng0** [comment]
thanks




| |
毕晓鹏
|
|
邮箱：bixiaopeng1996@163.com
|

签名由 网易邮箱大师 定制

On 06/06/2020 13:00, Godiva wrote:

Yes. I have this issue because I create a faiss.py file same as the package name. Hope it helps you.

**Comment by taoszhang** [comment]
牛逼，就是因为有一个faiss.py文件，给我坑惨了

**Comment by athraaalbehadili** [comment]
im having this error message "ImportError                               Traceback (most recent call last)
Cell In[2], line 2
      1 import faiss
----> 2 from faiss import IndexHNSWFlatL2

ImportError: cannot import name 'IndexHNSWFlatL2' from 'faiss' (C:\anaconda3\envs\hnsw_project3\Lib\site-packages\faiss\__init__.py)" and i tried many ways to make it work but in vain , what should i do

**Comment by saiveeranki9996** [comment]
I have the same issue, I do not have faiss.py file. I am loading faiss from langchain.vectorstores and using FAISS.from_documents. I have no clue where exactly this error rises. Any help is appreciated.
