### ISSUE TITLE
Question Regarding How Faiss Search Neighbors

### ISSUE THREAD

**Issue by IhaveAquestionHere** [facebookresearch/faiss#1199]
Hi, I have some questions about how Faiss search for neighbors:

1. For HNSW, why faiss allowed searching k > ef ?
2. For IndexLSH, what is the searching algorithm? Return top k data in the bucket that the query data belong to? What if k > size(bucket that query data belongs to)?

Thanks!

**Comment by mdouze** [comment]
1. Why not? When there are not enough search results, the missing entries are set to -1.
2. no. The IndexLSH just binarizes the input vector and does exhaustive search on the binary vectors (there are no buckets).

**Comment by IhaveAquestionHere** [comment]
Thank you very much for your reply! For HNSW, what will happen when the query number k is larger than ef (the dynamic list of neighbors)?

**Comment by mdouze** [comment]
hen there are not enough search results, the missing entries are set to -1

**Comment by IhaveAquestionHere** [comment]
Thank you very much!
