### ISSUE TITLE
Undefined reference to faiss::Index

### ISSUE THREAD

**Issue by zoe-cheung** [facebookresearch/faiss#120]
I created my cpp script but it failed due to many errors (eg underfined reference to).  Then I compile 1-Flat.cpp (g++ -std=gnu++11 -I.. 1-Flat.cpp -o 1-Flat) and got the following errors 

/tmp/cc8jS9iT.o: In function `main':
1-Flat.cpp:(.text+0x2e2): undefined reference to `faiss::IndexFlat::add(long, float const*)'
1-Flat.cpp:(.text+0x3a7): undefined reference to `faiss::IndexFlat::search(long, float const*, long, float*, long*) const'
1-Flat.cpp:(.text+0x59a): undefined reference to `faiss::IndexFlat::search(long, float const*, long, float*, long*) const'
/tmp/cc8jS9iT.o: In function `faiss::Index::~Index()':
1-Flat.cpp:(.text._ZN5faiss5IndexD2Ev[_ZN5faiss5IndexD5Ev]+0xd): undefined reference to `vtable for faiss::Index'
/tmp/cc8jS9iT.o: In function `faiss::IndexFlat::~IndexFlat()':
1-Flat.cpp:(.text._ZN5faiss9IndexFlatD2Ev[_ZN5faiss9IndexFlatD5Ev]+0xd): undefined reference to `vtable for faiss::IndexFlat'
/tmp/cc8jS9iT.o: In function `faiss::IndexFlatL2::IndexFlatL2(long)':
1-Flat.cpp:(.text._ZN5faiss11IndexFlatL2C2El[_ZN5faiss11IndexFlatL2C5El]+0x24): undefined reference to `faiss::IndexFlat::IndexFlat(long, faiss::MetricType)'
/tmp/cc8jS9iT.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x28): undefined reference to `faiss::IndexFlat::add(long, float const*)'
/tmp/cc8jS9iT.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x30): undefined reference to `faiss::Index::add_with_ids(long, float const*, long const*)'
/tmp/cc8jS9iT.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x38): undefined reference to `faiss::IndexFlat::search(long, float const*, long, float*, long*) const'
/tmp/cc8jS9iT.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x40): undefined reference to `faiss::IndexFlat::range_search(long, float const*, float, faiss::RangeSearchResult*) const'
/tmp/cc8jS9iT.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x48): undefined reference to `faiss::IndexFlat::reset()'
/tmp/cc8jS9iT.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x50): undefined reference to `faiss::Index::remove_ids(faiss::IDSelector const&)'
/tmp/cc8jS9iT.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x58): undefined reference to `faiss::IndexFlat::reconstruct(long, float*) const'
/tmp/cc8jS9iT.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x60): undefined reference to `faiss::Index::reconstruct_n(long, long, float*) const'
/tmp/cc8jS9iT.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x70): undefined reference to `faiss::IndexFlat::set_typename()'
/tmp/cc8jS9iT.o:(.rodata._ZTIN5faiss11IndexFlatL2E[_ZTIN5faiss11IndexFlatL2E]+0x10): undefined reference to `typeinfo for faiss::IndexFlat'
collect2: error: ld returned 1 exit status

What did I do wrong with 1-Flat.cpp?

**Comment by mdouze** [comment]
Hi

You need to link with the Faiss library. Please refer to a C++ compiler command line documentation.

**Comment by zoe-cheung** [comment]
I did tried to link the library with -l and the directory with -L

 g++ -std=gnu++11 -I.. -L/home/zcheung -lfaiss demo_v3.cpp -o demo__v3

Then I tried to copy the libfaiss.a to /usr/lib

I still get the following errors: 

/tmp/ccMql5vq.o: In function `main':
demo_fedex_v3.cpp:(.text+0x56e): undefined reference to `faiss::IndexFlat::add(long, float const*)'
demo_fedex_v3.cpp:(.text+0x6cc): undefined reference to `faiss::IndexFlat::search(long, float const*, long, float*, long*) const'
/tmp/ccMql5vq.o: In function `faiss::Index::~Index()':
demo_fedex_v3.cpp:(.text._ZN5faiss5IndexD2Ev[_ZN5faiss5IndexD5Ev]+0xd): undefined reference to `vtable for faiss::Index'
/tmp/ccMql5vq.o: In function `faiss::IndexFlat::~IndexFlat()':
demo_fedex_v3.cpp:(.text._ZN5faiss9IndexFlatD2Ev[_ZN5faiss9IndexFlatD5Ev]+0xd): undefined reference to `vtable for faiss::IndexFlat'
/tmp/ccMql5vq.o: In function `faiss::IndexFlatL2::IndexFlatL2(long)':
demo_fedex_v3.cpp:(.text._ZN5faiss11IndexFlatL2C2El[_ZN5faiss11IndexFlatL2C5El]+0x24): undefined reference to `faiss::IndexFlat::IndexFlat(long, faiss::MetricType)'
/tmp/ccMql5vq.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x28): undefined reference to `faiss::IndexFlat::add(long, float const*)'
/tmp/ccMql5vq.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x30): undefined reference to `faiss::Index::add_with_ids(long, float const*, long const*)'
/tmp/ccMql5vq.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x38): undefined reference to `faiss::IndexFlat::search(long, float const*, long, float*, long*) const'
/tmp/ccMql5vq.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x40): undefined reference to `faiss::IndexFlat::range_search(long, float const*, float, faiss::RangeSearchResult*) const'
/tmp/ccMql5vq.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x48): undefined reference to `faiss::IndexFlat::reset()'
/tmp/ccMql5vq.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x50): undefined reference to `faiss::Index::remove_ids(faiss::IDSelector const&)'
/tmp/ccMql5vq.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x58): undefined reference to `faiss::IndexFlat::reconstruct(long, float*) const'
/tmp/ccMql5vq.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x60): undefined reference to `faiss::Index::reconstruct_n(long, long, float*) const'
/tmp/ccMql5vq.o:(.rodata._ZTVN5faiss11IndexFlatL2E[_ZTVN5faiss11IndexFlatL2E]+0x70): undefined reference to `faiss::IndexFlat::set_typename()'
/tmp/ccMql5vq.o:(.rodata._ZTIN5faiss11IndexFlatL2E[_ZTIN5faiss11IndexFlatL2E]+0x10): undefined reference to `typeinfo for faiss::IndexFlat'
collect2: error: ld returned 1 exit status

**Comment by kobemajian** [comment]
@zoe-cheung , you can try the following command:
g++ -o demo_v3 demo_v3.cpp libfaiss.a -fopenmp /usr/lib64/libopenblas.so.0 -I.. -L/home/zcheung

**Comment by kobemajian** [comment]
@zoe-cheung 
g++ -o test_faiss -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= test_faiss.cpp libfaiss.a -g -fPIC  -fopenmp /usr/lib64/libopenblas.so.0
