### ISSUE TITLE
"IndexFlatL2" search return -1 

### ISSUE THREAD

**Issue by Na-Z** [facebookresearch/faiss#1206]
Running on:
* CPU

Interface: 
* Python

# Reproduction instructions
When I running the following code, sometimes the output **I** contain `-1` values, and the corresponding value in **D**  is `3.4028235e+38`
```
index = faiss.IndexFlatL2(self.feat_dim)
index.add(X)
D, I = index.search(X, k + 1)
```
Do you have any idea how it happens?

**Comment by ShaileshSridhar2403** [comment]
See if this helps [https://github.com/facebookresearch/faiss/issues/1016](url)
