### ISSUE TITLE
how to compute the cosine similarity ?

### ISSUE THREAD

**Issue by ucasiggcas** [facebookresearch/faiss#1208]
hi,dear
I have tried the [codes](https://github.com/facebookresearch/faiss/blob/master/tutorial/python) of python,but no cosine similarity?
could you please show me the tutorials ?
thx

# Platform
OS: 

Running on:
- [ ] GPU

Interface: 
- [ ] Python

**Comment by mdouze** [comment]
see https://github.com/facebookresearch/faiss/wiki/MetricType-and-distances#how-can-i-index-vectors-for-cosine-similarity
