### ISSUE TITLE
add_with_ids not implemented for this type of index

### ISSUE THREAD

**Issue by foocker** [facebookresearch/faiss#1212]
# Problem:
RuntimeError: Error in virtual void faiss::IndexBinary::add_with_ids(faiss::IndexBinary::idx_t, const uint8_t*, const idx_t*) at IndexBinary.cpp:35: add_with_ids not implemented for this type of index

Running on:
- [x] CPU using yes.
- [ ] GPU version yes, but not use. 

Interface: 
- [ ] C++
- [x] Python yes

# Reproduction instructions
simple code as follows:
index = faiss.IndexBinaryFlat(dimensions*8)   #dimensions=32
features = []
ids = []
ids_count =0
for loop:
  ret, feature = way_feature(way, file_name)   # eg, cv2.ORB_create()...
  ids_list = np.linspace(ids_count, ids_count, num=feature.shape[0], dtype="int64")
  features.append(feature)
  ids.append(ids_list)

features = np.vstack(features)
ids = np.hstack(ids)
if features.any():
    if not index.is_trained:
        index.train(features)
    index.add_with_ids(features, ids)    # change

**Comment by mdouze** [comment]
add_with_ids is not supported for Flat indexes. 
See https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index#then-flat

**Comment by foocker** [comment]
> 
> 
> add_with_ids is not supported for Flat indexes.
> See https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index#then-flat

thx for your replay.
some point:
 surf's feature is float, so i can use "IDMap,Flat", it's work. but orb's feature vector is uint8, i should use binary index, and hamming distance, not cosine or L2, all sence will be add_with_ids.
so i have two question:
1.binary index, with add_with_ids, using hamming, what index should i choose?
2.when i change orb's feature from surf'feature, which work well, i get :
  TypeError: in method 'Index_add_with_ids', argument 3 of type 'float const *'

**Comment by foocker** [comment]
> 
> 
> > add_with_ids is not supported for Flat indexes.
> > See https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index#then-flat
> 
> thx for your replay.
> some points:
> surf's feature is float, so i can use "IDMap,Flat", it's work. but orb's feature vector is uint8, i should use binary index, and hamming distance, not cosine or L2, all sence will be add_with_ids.
> so i have two questions:
> 1.binary index, with add_with_ids, using hamming, what index should i choose?
> 2.when i change orb's feature from surf'feature, surf work well, i got :
> TypeError: in method 'Index_add_with_ids', argument 3 of type 'float const *'

i have test some other binary index, in binary wiki, add_with_ids is not implemented。

**Comment by honghande** [comment]
@foocker Open CV feature vectors such as surf and sift have been extracted. How to use faiss for vector index? Do you have any reference cases? Thank you!
