### ISSUE TITLE
index_factory does not parse the IVFx string

### ISSUE THREAD

**Issue by DarthJuri** [facebookresearch/faiss#1213]
# Summary

I have tried to generate the IVF65536_HNSW32 index using this code:

```python
import faiss

index = faiss.index_factory(100, "IVF65536_HNSW32")
```
and it throws the following error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-34-52e6f0e7fd0c> in <module>
----> 1 faiss.index_factory(100, "IVF65536_HNSW32")

RuntimeError: Error in faiss::Index* faiss::index_factory(int, const char*, faiss::MetricType) at index_factory.cpp:322: Error: 'index' failed: description IVF65536_HNSW32 did not generate an index
```

I have tried it for "IVF4096" as well and the same error occurs.

# Platform

OS: Ubuntu 18.04.4 LTS

Faiss version: faiss-cpu, 1.6.3, py37h6bb024c_0, pytorch (conda installation)

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by mdouze** [comment]
use "IVF65536_HNSW32,Flat" (the encoding of the vectors needs to be specified as well).

**Comment by DarthJuri** [comment]
Thanks, it works! Would it be possible to mention it in the [docs](https://github.com/facebookresearch/faiss/wiki/The-index-factory)? And I think there is an opposite issue on the [Faiss indexes page](https://github.com/facebookresearch/faiss/wiki/Faiss-indexes), where the index factory string for HNSW is written as `HNSWx,Flat`, which does not work (for HNSW works only the `HNSWx` string).

**Comment by mdouze** [comment]
Right, there is both a bug and an error in the doc. 
The bug is that 
```
faiss.index_factory(10, 'HNSW32_SQ8')
```
does not work.

**Comment by mdouze** [comment]
Patched the source to accept the correct HNSW syntax.
