### ISSUE TITLE
How can i get index type when readIndex

### ISSUE THREAD

**Issue by ftyuuu** [facebookresearch/faiss#1214]
`faiss::Index *index = faiss::read_index(indexNameBuf);`
I forgot the type of the index, how can I get the type of any index file ?

**Comment by mdouze** [comment]
See here how to do it in Python: 
https://github.com/facebookresearch/faiss/wiki/FAQ#how-to-explore-the-contents-of-an-opaque-index
In C++ use dynamic_cast.

**Comment by ftyuuu** [comment]
> See here how to do it in Python:
> https://github.com/facebookresearch/faiss/wiki/FAQ#how-to-explore-the-contents-of-an-opaque-index
> In C++ use dynamic_cast.

thank you for your reply. Is it possible to directly obtain the input string like index_factory through the Index interface?

**Comment by mdouze** [comment]
no.
