### ISSUE TITLE
Error while adding custom index using IndexIDMap

### ISSUE THREAD

**Issue by ravitashaw** [facebookresearch/faiss#1215]
Hi, I'm facing difficulty in adding custom index (filename) to the IndexMap. The objective of the task is to add feature vectors for indexing and while searching the output should be filename rather than an ordinal index. The test code is:

```
def test_faiss():
    d = 20
    nb = 1
    file_name = 'test.png'
    xb = np.random.random((nb, d)).astype('float32')
    ids = np.array(file_name).reshape(nb, 1)
    index = faiss.IndexFlatL2(d)
    index = faiss.IndexIDMap(index)
    index.add_with_ids(xb, ids)
    return
```

and, the error is:

```
assert ids.shape == (n, ), 'not same nb of vectors as ids'
AssertionError: not same nb of vectors as ids
```

I'm using only 1 vector for indexing, so my `ids` also has shape of (1, 1). Is there something missing or misunderstood?

**Comment by ravitashaw** [comment]
I figured out from [#641](https://github.com/facebookresearch/faiss/issues/641)

The above code works fine when the `ids` is replaced as an integer array. The custom index mapping need to be manually managed. 

But the error seems misleading, the shape of `ids` is ok but the datatype.

**Comment by SlytherinWyne** [comment]
I'm encountering the same issue, the dimension of xb and ids seem can not be 1, quite weird, annoying error...
