### ISSUE TITLE
Range search around query point squared

### ISSUE THREAD

**Issue by wollschl** [facebookresearch/faiss#1219]
# Summary
Should the radius which has to be provided for the range search be given as squared distance?
If I just generate random points and search for 10 neighbors, I get 10 squared L2 distances. If I take the square root of the largest one and do a range search around the query point I do not get the same result. I get significantly less neighbors. If I plug in the squared largest distance I get the (so the largest distance I get from the neighbor search) then I retrieve my 10 neighbors again.

I am just wondering because I don't find it in the documentation:

"The method range_search returns all vectors within a radius around the query point (as opposed to the k nearest ones)."

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by mdouze** [comment]
The range search also takes a squared distance. 

If you search by the max of distances found by range search (+ epsilon because comparison is strict) and not find back the same results, then it is a bug (please post a reproduction script).
