### ISSUE TITLE
Where is the ideal directory to install FAISS in Ubuntu 16.04?

### ISSUE THREAD

**Issue by zoe-cheung** [facebookresearch/faiss#122]
1. Where is the ideal directory to install FAISS in Ubuntu 16.04?
2. Where should the libfaiss.a be located for g++ compiler?

**Comment by zoe-cheung** [comment]
Need to improve because for a cpp script in faiss directory with 

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstring>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <sys/time.h>
#include <faiss/AutoTune.h>
#include <faiss/IndexFlat.h>

need to be compile with a lengthy g++ command: 

z@z-VirtualBox:~/faiss$ **g++ -o demo_fedex_v3 -I.. -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp demo_fedex_v3.cpp libfaiss.a -g -fPIC  -fopenmp -Wl,--no-as-needed -L/opt/intel/compilers_and_libraries/linux/mkl//lib/intel64   -lmkl_intel_ilp64  -lmkl_core -lmkl_gnu_thread -ldl -lpthread**

**Comment by mdouze** [comment]
Hi 

I don't understand the question.
