### ISSUE TITLE
[Question] IndexBinaryIVF Clustering

### ISSUE THREAD

**Issue by sahuang** [facebookresearch/faiss#1221]
- I am currently trying to use Faiss to store & search Binary vectors. I noticed that Faiss uses K-Means to cluster binary vectors. From [Binary Indexes wiki](https://github.com/facebookresearch/faiss/wiki/Binary-indexes):
> The "IVF" (Inverse Vector File) flavor speeds up the search by clustering the vectors. This clustering is done using a second (binary) index for quantization (usually a flat index). This is equivalent to the IndexIVFFlat of the floating-point indexes.
- My question is whether applying K-Means for floating-point data to binary vector clustering is a decent approach, because according to some articles (e.g. [this](https://www.ibm.com/support/pages/clustering-binary-data-k-means-should-be-avoided)), centres will not be binary after the first iteration and thus clusters are hard to be interpreted properly. Search accuracy might not be guaranteed like float vectors.
- What's Faiss' rationale for this? Will other K-means extensions like K-modes be used in the future? Any explanations will be highly appreciated!

**Comment by mdouze** [comment]
The floating-point centroids are rounded to closest binary coordinate after the k-means run.
We did not evaluate other clustering options extensively, and there may indeed be better ones. 
Some experiments here: 
https://github.com/facebookresearch/faiss/wiki/Binary-hashing-index-benchmark

**Comment by sahuang** [comment]
Thanks for the information! Much appreciated.
