### ISSUE TITLE
Will IVFPQR and hnsw support inner product?

### ISSUE THREAD

**Issue by uestc-lfs** [facebookresearch/faiss#1233]
Thank you for your greate work. I find that both IVFPQR and hnsw not supporting ip and I am considering implementing them myself, is there some difficulty that make it hard to implement
ip on IVFPQR?

**Comment by mdouze** [comment]
HNSW does support METRIC_INNER_PRODUCT.
It is not particularly hard for IVFPQR it's just that we don't use IVFPQR too often.

**Comment by JayYip** [comment]
> HNSW does support METRIC_INNER_PRODUCT.
> It is not particularly hard for IVFPQR it's just that we don't use IVFPQR too often.

Could you inform how to use METRIC_INNER_PRODUCT with HNSW? I tried `faiss.index_factory(
                vector_size, 'HNSW32', METRIC_INNER_PRODUCT)` but no luck.

**Comment by uestc-lfs** [comment]
@JayYip I met the same problem, maybe `index_factory` shuld be updated

**Comment by mdouze** [comment]
index_factory has a bug that is fixed in the FB internal version (see #1213)
In the meantime it is ok to just set metric_type on the index manually.

**Comment by uestc-lfs** [comment]
Hello, @mdouze , since IVFPQ support inner product, should this line alse be removed?
https://github.com/facebookresearch/faiss/blob/e8c8db85aeb72d80f4c83e8003ca778fab575092/IndexIVF.cpp#L93

**Comment by lhoestq** [comment]
@uestc-lfs @mdouze any news about this line ?
https://github.com/facebookresearch/faiss/blob/e8c8db85aeb72d80f4c83e8003ca778fab575092/IndexIVF.cpp#L93

Thanks for your amazing work btw :)

**Comment by uestc-lfs** [comment]
@lhoestq https://github.com/facebookresearch/faiss/issues/1261

**Comment by Kun-Ming** [comment]
@uestc-lfs Hi, I just wondering how to make a HNSW index with inner product metric. The code `index = faiss.index_factory( vector_size, 'HNSW32', METRIC_INNER_PRODUCT)`doesn't work. When I check the `index.metric_type`, it returns 1, which means L2 metric. but this work for IVF or IVF PQ.

**Comment by uestc-lfs** [comment]
> @uestc-lfs Hi, I just wondering how to make a HNSW index with inner product metric. The code `index = faiss.index_factory( vector_size, 'HNSW32', METRIC_INNER_PRODUCT)`doesn't work. When I check the `index.metric_type`, it returns 1, which means L2 metric. but this work for IVF or IVF PQ.

@Kun-Ming Use this:
![image](https://user-images.githubusercontent.com/18738958/119213411-5d4acd00-baf1-11eb-80b6-4aed458689e4.png)

**Comment by kwang2049** [comment]
Hi @uestc-lfs @mdouze,

I am wondering, by indicating `faiss.METRIC_INNER_PRODUCT` in `faiss.IndexHNSWFlat`, does it mean the transformation from dot-product to L2 space will be done automatically?

I have this question since I saw in the DPR repo, the author implemented the transformation process themselves: https://github.com/facebookresearch/DPR/blob/1ee31c6c5335f05c45138161eb5ce2c03023115d/dpr/indexer/faiss_indexers.py#L157. So maybe they did something unnecessary?

Thanks and looking forward to your reply!

**Comment by uestc-lfs** [comment]
@kwang2049 Since HNSW supports the inner product, I think it is unnecessary to do the transform.

**Comment by mdouze** [comment]
> > @uestc-lfs Hi, I just wondering how to make a HNSW index with inner product metric. The code `index = faiss.index_factory( vector_size, 'HNSW32', METRIC_INNER_PRODUCT)`doesn't work. When I check the `index.metric_type`, it returns 1, which means L2 metric. but this work for IVF or IVF PQ.
> 
> @Kun-Ming Use this:
> ![image](https://user-images.githubusercontent.com/18738958/119213411-5d4acd00-baf1-11eb-80b6-4aed458689e4.png)

Works in latest version
