### ISSUE TITLE
Is it a bug here?

### ISSUE THREAD

**Issue by uestc-lfs** [facebookresearch/faiss#1237]
https://github.com/facebookresearch/faiss/blob/833d417db1b6b6fd4b19e092f735373f07eab33f/index_factory.cpp#L275-L281
In this way, you can not generate index of type HNSW+SQ

**Comment by mdouze** [comment]
Well spotted! 
Yes it's a bug, see #1213. It is fixed in the Facebook internal version and will be corrected in the next version.
