### ISSUE TITLE
<class 'faiss.swigfaiss_avx2.FloatVector'> how to get the value of this class

### ISSUE THREAD

**Issue by NuistZF** [facebookresearch/faiss#1240]
# Summary
I use faiss.Clustering to cluster my data x. The code is:

clus=faiss.Clustering(feature_dim, n_cls)
res = faiss.StandardGpuResources()
flat_config = faiss.GpuIndexFlatConfig()
flat_config.useFloat16 = False
flat_config.device = 0
index = faiss.GpuIndexFlatL2(res, feature_dim, flat_config)
clus.train(x, index)

After clustering, I want to obtain the centroids of my data. Thus, I ues cc=clus.centroids. However, it shows that this variable cc is <class 'faiss.swigfaiss_avx2.FloatVector'>. I don't know how to get the value of this class. Or, can this class be converted into numpy class?

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
Please use `faiss.vector_to_array` as in 
https://github.com/facebookresearch/faiss/blob/master/python/faiss.py#L735
See 
https://github.com/facebookresearch/faiss/wiki/Faiss-code-structure#c-code-wrapping

**Comment by NuistZF** [comment]
Thanks for your reply!
