### ISSUE TITLE
Why SQ index is not supported in GPU? 

### ISSUE THREAD

**Issue by wjtan99** [facebookresearch/faiss#1242]
From the wiki page https://github.com/facebookresearch/faiss/wiki/Faiss-on-the-GPU, it seems SQ is not supported? If that is true? If yes, why?

**Comment by mdouze** [comment]
It is supported now, with `GpuIndexIVFScalarQuantizer` or via index_cpu_to_gpu`. 
I corrected this in the doc.

**Comment by wjtan99** [comment]
Thanks. I also noticed the type GpuIndexIVFScalarQuantizer in the source code directory.
