### ISSUE TITLE
The recall will be low when efSearch is smaller than k

### ISSUE THREAD

**Issue by uestc-lfs** [facebookresearch/faiss#1244]
When `efSearch` is smaller thant `k`, `ef` will set to `k`
https://github.com/facebookresearch/faiss/blob/e8c8db85aeb72d80f4c83e8003ca778fab575092/impl/HNSW.cpp#L692

But here you still use `efSearch`, my experiments find that this will make the recall lower than when `efSearch` is set to `k`
https://github.com/facebookresearch/faiss/blob/e8c8db85aeb72d80f4c83e8003ca778fab575092/impl/HNSW.cpp#L587

**Comment by mdouze** [comment]
Yes the behavior of efSearch < k is not very consistent. However, we don't plan to fix it if it does not crash, the user can just set efSearch to a more suitable value.
