### ISSUE TITLE
D % 4 is no more checked for L2 computations?

### ISSUE THREAD

**Issue by matsui528** [facebookresearch/faiss#1248]
# Summary

The wiki is saying that `D % 4` is checked to switch the implementation of L2 computations:
`We use implementation 1 when nq < 20 and d is a multiple of 4, and implementation 2 otherwise. `
https://github.com/facebookresearch/faiss/wiki/Implementation-notes#matrix-multiplication-to-do-many-l2-distance-computations

However, if I understand correctly, it seems `D % 4` is no more checked.
https://github.com/facebookresearch/faiss/blob/master/utils/distances.cpp#L382

Should the wiki be updated?

Best,

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
Right, this check is not done anymore. Fixed the doc.
