### ISSUE TITLE
running kmeans_mnist.py cored dumped

### ISSUE THREAD

**Issue by xasw1** [facebookresearch/faiss#125]
Hi , I have tried to run benchs/kmeans_mnist.py script, but core dumped. I've change the size of dataset to 1M.
python kmeans_mnist.py 5 5
load /home/sensetime/faiss/benchs/mnist8m/mnist1m-patterns-idx3-ubyte
[[   2051]
 [1100000]
 [     28]
 [     28]]
(862400000,) 1100000 28 28
reshape
run
Faiss assertion device_ < getNumDevices() failed in faiss::gpu::GpuIndex::GpuIndex(faiss::gpu::GpuResources*, int, int, faiss::MetricType) at GpuIndex.cu:30Aborted (core dumped)

**Comment by mdouze** [comment]
Hi 

Do you have 5 GPUs in your machine?

**Comment by xasw1** [comment]
well...I've tried to run python kmeans_mnist.py 5 1 , but there's a link error:


modprobe: ERROR: could not insert 'nvidia_340_uvm': Invalid argument
Faiss assertion numDev != -1 failed in int faiss::gpu::getNumDevices() at utils/DeviceUtils.cpp:34Aborted (core dumped)

**Comment by xasw1** [comment]
Oh, I've solved this problem by "sudo apt-get remove nvidia-340" referenceing "https://github.com/tensorflow/tensorflow/issues/4770"
:)
