### ISSUE TITLE
Is metric_type necessary in IndexBinary?

### ISSUE THREAD

**Issue by wxingda** [facebookresearch/faiss#1255]
Hi guys,

Metric_type is only used in `search_knn_hamming_heap` for sorting
https://github.com/facebookresearch/faiss/blob/e8c8db85aeb72d80f4c83e8003ca778fab575092/IndexBinaryIVF.cpp#L394

But hamming's results usually takes the smallest ones, so I think metric_type can be removed from IndexBinary.

It's also to be consistent with `IndexBinaryFlat`, which only supports select the k smallest values
https://github.com/facebookresearch/faiss/blob/e8c8db85aeb72d80f4c83e8003ca778fab575092/IndexBinaryFlat.h#L25
What do you think?

**Comment by mdouze** [comment]
You're right. But we'll keep it for future expansion ;-)
