### ISSUE TITLE
Index factory dimension not the same or returns -1

### ISSUE THREAD

**Issue by war-and-peace** [facebookresearch/faiss#1256]
# Summary

# Platform

OS:  Ubuntu 18.04

Faiss version:  faiss-gpu 1.6.3 (checked using both pip and conda)

Faiss compilation options: 

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

I have a dataset with 1.3 million items, each has a dimension of 768. I have tried to build the following index:
```
index = faiss.index_factory(768,"L2norm,IVF262144_HNSW32,SQ4")
index_ivf = faiss.extract_index_ivf(index)
clustering_index = faiss.index_cpu_to_all_gpus(faiss.IndexFlatL2(384))
index_ivf.clustering_index = clustering_index
```

But when I run `index.train(data)` it prints an error: _Clustering.cpp:281: Error: 'index.d == d' failed: Index dimension 384 not the same as data dimension 768._ Surprisingly, the same code worked on another machine. How is it possible?

After that, I changed 384 in `faiss.IndexFlatL2(384)` to 768 and it worked, but when I search on the index it returns -1 after several results (I added the data to index: `index.add(data)`). For example, if I query for top 100 results, it returns ids for the first 50 and the rest is -1. I checked several configurations: with IVF65536_HNSW32, IVFx_HNSW32 (x - smaller number), etc. But the results are the same. How can I make it return ids instead of -1?

**Comment by wickedfoo** [comment]
https://github.com/facebookresearch/faiss/wiki/FAQ

see "What does it mean when a search returns -1 ids?"

**Comment by war-and-peace** [comment]
Thank you for your answer. Could you please explain why the above code works in one machine and doesn't work on another? The dimension in `faiss.IndexFlatL2(384)` should be 384 or 768? I have checked with different versions of *faiss* on both CPU and GPU.

**Comment by mdouze** [comment]
The issue with different machines is probably a bug on your side.
To know which dimension the `clustering_index` should have, it is safest to compute it with 
```
dim = extract_index_ivf(index).d
```

**Comment by wickedfoo** [comment]
Also you have too many IVF lists for your data set size. Typically the IVF list size should be something around 4 * sqrt(N), so 4 * sqrt(1.3 million) = 4,560 or so. You have 262,144. Many of these are likely to be empty.

**Comment by war-and-peace** [comment]
Thank you for your answers and suggestions. I have solved fixed the issue with -1 by changing `nprobe` value as you suggested. However, I still could not figure out the problem of having different results in different machines. I agree that it is likely a bug on my side.
