### ISSUE TITLE
Search neighbors of mulitiple query vectors based on the average distance?

### ISSUE THREAD

**Issue by zoujx96** [facebookresearch/faiss#1257]
Hi,

The current KNN search in faiss only supports searching neighbors of each query separately. What if I want to search neighbors of a group of vectors based on the average distance of each database vector to all query vectors? Thanks!

**Comment by mdouze** [comment]
For maximum inner product (or cosine distance) you can just use the average query vector as query.

For L2 distance, it is a bit more tricky. You can use the identity:

argmin_j sum_i || x_i - y_j ||^2 = argmax_j < avg | y_j >  - 1/2 ||y_j||^2

where avg = the averarge query vector. The argmax can be solved by making a maximum inner product index of dimension d+1, where you index the y_j's and append one dimension containing -1/2 ||y_j||^2 

This is similar to the approach mentioned here: https://github.com/facebookresearch/faiss/wiki/MetricType-and-distances#how-can-i-do-max-inner-product-search-on-indexes-that-support-only-l2

**Comment by zoujx96** [comment]
Thank you so much!
