### ISSUE TITLE
Question about metric type in IVFx_HNSWy

### ISSUE THREAD

**Issue by uestc-lfs** [facebookresearch/faiss#1261]
It seems that IVFx_HNSWy does not support inner product, as indicated by the code:
https://github.com/facebookresearch/faiss/blob/e8c8db85aeb72d80f4c83e8003ca778fab575092/index_factory.cpp#L141-L144
and here:
https://github.com/facebookresearch/faiss/blob/e8c8db85aeb72d80f4c83e8003ca778fab575092/IndexIVF.cpp#L87-L104

**Comment by mdouze** [comment]
Right, the index_factory does not support it. You can build it by hand with 
```python 
d = 32
quantizer = faiss.IndexHNSWFlat(d, 32, faiss.METRIC_INNER_PRODUCT)
index = faiss.IndexIVFFlat(quantizer, d, 1024, faiss.METRIC_INNER_PRODUCT)

# transfer ownership of quantizer
index.own_fields = True
quantizer.this.disown()
```

**Comment by uestc-lfs** [comment]
Thank you @mdouze , when I use inner product for IVFx_HNSWy, I use metric l2 for level-1 quantizer and still get good result. Why is this?
