### ISSUE TITLE
Do the normalize functions run faster on GPU?

### ISSUE THREAD

**Issue by BramVanroy** [facebookresearch/faiss#1265]
Faiss version: current master (https://github.com/facebookresearch/faiss/commit/e8c8db85aeb72d80f4c83e8003ca778fab575092)

Running on:
- [x] GPU
- [ ] CPU

Interface: 
- [x] Python
- [ ] C++

I am building an index to store some sentence representation, so my main function looks something like this:

```python
index = faiss.index_factory(64, "Flat", faiss.METRIC_INNER_PRODUCT)
# will be a list of numpy arrays, each being a sentence representation vector
sent_vecs = []
with open(corpus, encoding="utf-8") as fhin:
    for line in fhin:
        sent_vecs.append(convert_line_to_vector(line))

# convert list to array
sent_vecs = np.array(sent_vecs)
# normalise vectors in-place
faiss.normalize_L2(sent_vecs)

# add vectors to FAISS index
index.add(sent_vecs)
# save index to disk
faiss.write_index(index, output_f)
```

This would allow me to later find similar sentences in the index with cosine similarity.

A few questions come to mind regarding the GPU:

- The normalisation process is relatively slow, though, so I am wondering whether it automatically uses the GPU (when compiled with CUDA)
- in my use-case, is there any advantage of putting the index on the GPU? I would think that it would speed up searching, but not so much creating the index itself
- is there any way to automatically select the correct device? Or alternatively, something like: `if compiled_with_cuda:`

Thanks!

**Comment by mdouze** [comment]
The GPU is not used automatically. 
Since you use brute-force search with a flat index, you don't strictly need to build an index, you can search directly in a matrix. See 

https://github.com/facebookresearch/faiss/wiki/Brute-force-search-without-an-index

**Comment by BramVanroy** [comment]
@mdouze Thanks for your reply. In my case, we need to build the index first and use it later in other scripts/machines. A portable index is useful for us.

Could you shed some light on the two last questions I had? 
- is there an advantage of creating an index on the GPU, or is a GPU only beneficial when querying or training?
- does faiss come with a built-in function to check whether or not CUDA is enabled in faiss?

**Comment by mdouze** [comment]
GPU also speeds up index creation. But for the flat index, it's just a copy so it is not faster. 
You can check `faiss.get_num_gpus() > 0`

**Comment by BramVanroy** [comment]
Thanks!
