### ISSUE TITLE
negative distance returned in IndexFlatL2 range_search query

### ISSUE THREAD

**Issue by joshim5** [facebookresearch/faiss#1266]
# Summary

This issue was raised in #297 for `search`. Here I report the same issue still occurs in `range_search`.

# Platform

OS: Ubuntu 18.04

Faiss version: e8c8db85aeb72d8

Faiss compilation options: CUDA 10.1

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

Perhaps this was fixed for index.search(Data, 10), but I get negative distances for index.range_search. Here's an example:
```
lims, D, I = index.range_search(data, 555)
>>> min(D)
-3145728.0
>>> max(D)
512.0
```
Is this numerical overflow?

**Comment by mdouze** [comment]
Could you post some code to reproduce?

**Comment by mdouze** [comment]
Seems to be an issue related to badly conditioned data, see 
https://github.com/facebookresearch/faiss/wiki/FAQ#why-do-i-get-weird-results-with-brute-force-search-on-vectors-with-large-components
