### ISSUE TITLE
Getting the number of rows in the index

### ISSUE THREAD

**Issue by BramVanroy** [facebookresearch/faiss#1267]
# Summary

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

I would like to find out how many rows (items, vectors) are part of the index in the Python part. I think I looked everywhere and can't find this documented (perhaps I have been using the wrong search kleywords). I tried a simple `len()` as well as `.numVectors` but those do not work.

**Comment by BramVanroy** [comment]
Found it in the docs HTML files. It would be useful if these docs were also online somewhere.

```python
index.nbtotal
```

**Comment by GuanghuaShu** [comment]
> Found it in the [docs HTML files](https://rawgit.com/facebookresearch/faiss/master/docs/html/annotated.html).
> 
> ```python
> index.nbtotal
> ```

The info may have been updated. It is `index.ntotal` now and here is the [doc HTML](https://faiss.ai/cpp_api/struct/structfaiss_1_1AdditiveCoarseQuantizer.html?highlight=ntotal#_CPPv4N5faiss23AdditiveCoarseQuantizer6ntotalE).
