### ISSUE TITLE
Chunk access to search results

### ISSUE THREAD

**Issue by BramVanroy** [facebookresearch/faiss#1268]
# Summary

I am looking to find X matches (e.g. 100) that have to adhere to a given criteria (something outside of FAISS). My main goal is to make this efficient (exact search, though). This is troublesome because for this reason I cannot simpy use `.search(vec, 100)` since not all of those 100 results will match my criteria. I am looking for alternatives.

# Platform

Faiss version: latest master, running Python on CPU

# Reproduction instructions

My current implementation is the following (which works). However, technically it is a mess: I iteratively keep searching for matches until `n_matches` is the number of matches that we want (`find_n_matches`) or until we reach the end of the index. To be lenient in terms of look up speed, I only do small lookups (starting with `k=2*find_n_matches`). If `n_matches` are not found yet, we do a new query with `k += find_n_matches`, effectively finding the same results as before `+find_n_matches` extra. To be lenient on memory and speed, we index these results to only include the results that we did not have previously.

This approach works, and works very well if the matching results are found early. However, if they are more near the end, this is getting very slow. To counter this, intuitively, something like chunk access might come in handy. This would mean, rather than resulting topk, return the results between `topk-topj`. I guess that is basically the same thing as I am now doing manually, although the Cpp implementation would be faster. Other suggestions to make this "better" (speed and memory-wise) are very welcome.

I tried to be as descriptive as possible in my comments but if anything is not clear, please let me know:

```python
def search(vec, faiss_index, find_n_matches=50):
    """We are iteratively querying larger topk values (`k_search`), e.g.: first we query for 100 results,
       but if these are not the ones we need (duplicates) we have to look again, so we increase
       topk to e.g. 150, filter out the first 100 (by indexing from `prev_k_search` onwards)
       and look for more results. For a small `find_n_matches` value that should be okay,
       but for larger values (hundreds or thousands) this may be an issue."""
    faiss_index_size = faiss_index.ntotal
    faiss.normalize_L2(vec)

    # we can abort when n_matches == find_n_matches so track n_matches
    n_matches = 0

    # prev_k_search to keep track where our previous query ended
    # this way, we can only select the larger indices in the next query
    prev_k_search = 0
    # k_search to iteratively increase the size of the topk query in the index
    k_search = find_n_matches*2

    def find():
        """Recursive function to iteratively query for larger topk values (`k_search`)."""
        nonlocal n_matches, prev_k_search, k_search

        done = False

        # We have reached the end of the index, so we can stop looking
        # This is unlikely to happen (except if there are a lot of dupicates in a very small index
        # or if `find_n_matches` is very large compared to the size of the index)
        if k_search > faiss_index_size - 1:
            done = True
            return [], k_search, n_matches, done

        dists, idxs = faiss_index.search(vec, k_search)

        # only process matches that we hadn't found before
        dists = dists.squeeze()[prev_k_search:]
        idxs = idxs.squeeze()[prev_k_search:]
        # exclude the matches that are an exact match
        # due to rounding errors dists can also be 0.999998 or 1.000004
        same = np.where(dists >= 1.)
        real_dists = np.delete(dists, same)
        real_idxs = np.delete(idxs, same)

        prev_k_search = k_search
        k_search += find_n_matches

        # Now that have all results from our query - excluding results from the
        # previous query because we start index from the previous query size -
        # we can filter these matches so that do not match our criteria
        temp_results = []
        for i in range(real_dists.shape[0]):
            match_idx = real_idxs[i]
            
            # `matches_condition` can be any function
            if not matches_condition(match_idx):
                continue
            
            temp_results.append(match_idx)
            n_matches += 1
            if n_matches == find_n_matches:
                done = True
                break

        return temp_results, done

    res = []
    while True:
        temp_res, is_done = find()
        res.append(temp_res)

        if is_done:
            break

    # flatten appended results
    res = [r for temp_res in res for r in temp_res]
    n_res = len(res)

    if n_res < find_n_matches:
        logging.warning(f"Only found {n_res:,} results (find_n_matches={find_n_matches:,}) for vec {src_vec}")

    return res

```

**Comment by mdouze** [comment]
Have you checked what is the runtime impact of searching with a very large number of results (k)? Normally search speed is only weakly dependent on k.

**Comment by BramVanroy** [comment]
> Have you checked what is the runtime impact of searching with a very large number of results (k)? Normally search speed is only weakly dependent on k.

I am not so much worried about runtime in this part but about memory usage. Surely fetching and storing all results must take up quite some memory. 

Let's assume that we have all the memory in the world, though. Would you suggest to retrieve all matches? I.e. `faiss_index.search(vec, faiss_index.ntotal)`?

**Comment by diegovalenzuelaiturra** [comment]
Does it makes sense to remove all duplicates first ?

I think it could be done using `range_search` method (with a `threshold` value near to `1.`) instead of `search` 

https://github.com/facebookresearch/faiss/issues/1273#issuecomment-652837078

**Comment by BramVanroy** [comment]
@diegovalenzuelaiturra Apologies for the very late reply.

In our case removing duplicates first is not an option as other metadata might differ depending on the index of the match.
