### ISSUE TITLE
Non-zero distance yet closest neighbour is itself

### ISSUE THREAD

**Issue by JustCunn** [facebookresearch/faiss#1272]
```
xb = X
xq = X


res = faiss.StandardGpuResources()

index = faiss.IndexFlatL2(dim)
gpu_idx = faiss.index_cpu_to_gpu(res, 0, index)
print(gpu_idx.is_trained)
gpu_idx.add(xb)
print(gpu_idx.ntotal)

k = 4
D, I = gpu_idx.search(xq, k)
```
As you can see `D` is the distance matrix. My query and database matrices `xq` and `xb` are the same because I need to find every sentence's closest neighbours in relation to each other (if that makes sense). You'd expect every entries closest neighbours to be itself because of this and so the first distance should always be 0. This is true for most but some have very, very small distances such as 1.283929...e-07, which is very close to zero, yet not quite there.

Apologies if my question is simple, but is this just a 'trait' of faiss/methods used (like L2)? I suspect it is but I came to check in case.

**Comment by wickedfoo** [comment]
This is likely an artifact of using a matrix multiplication kernel to compute L2 for larger problem sizes (a larger number of query vectors). Do you get different results if the number of vectors in `xq` is 1? How many vectors are in `xq`?

(x - y)^2 is computed in two steps: 
-2xy via matrix multiplication (GEMM)
+ x^2 + y^2 by adding the vector norms

which will not cancel in the same way in floating point arithmetic as the original (x - y) ^ 2 expression when x == y.

**Comment by mdouze** [comment]
See also 
https://github.com/facebookresearch/faiss/wiki/Implementation-notes#matrix-multiplication-to-do-many-l2-distance-computations

**Comment by JustCunn** [comment]
Yes, I think it is just an artefact of matrix multiplication. It's only for a rough estimate anyways so I can take it as being zero pretty much. Thanks for that!
