### ISSUE TITLE
How to use bfKnn in Python?

### ISSUE THREAD

**Issue by moskomule** [facebookresearch/faiss#1276]
Hi! Thank you for developing this great project.

I recently notice that `bruteForceKnn` is deprecated and now `bfKnn` is the main.

https://github.com/facebookresearch/faiss/blob/9258a9535eed8e09760f82ac1e2889e5cd1979f6/gpu/GpuDistance.cu#L97

I'm using faiss via Python and not familiar with how to specify the arguments of this function. How can I specify them in Python, especially `GpuDistanceParams`?

P.S. The test for PyTorch uses the old `bruteForceKnn`.

https://github.com/facebookresearch/faiss/blob/9258a9535eed8e09760f82ac1e2889e5cd1979f6/gpu/test/test_pytorch_faiss.py#L94

**Comment by mdouze** [comment]
`bruteForceKnn` still works AFAIK. Why would you switch to `bfKnn`?

**Comment by moskomule** [comment]
Yes, it works. But it's not possible to suppress this deprecated warning message (if I understand correctly), so I want to use the new `bfKnn` if possible.

https://github.com/facebookresearch/faiss/blob/9258a9535eed8e09760f82ac1e2889e5cd1979f6/gpu/GpuDistance.cu#L135

**Comment by mdouze** [comment]
Ah right. That's why it was not showing up in the tests. I will fix the test with the new function.

**Comment by mdouze** [comment]
See this diff: https://gist.github.com/mdouze/94d1d18f4fa84ef58350d54509a7bb3f
We may move the enclosing function to a library within Faiss to make it easier to use from outside.

**Comment by moskomule** [comment]
Thank you for your prompt fix!
