### ISSUE TITLE
FAISS for Windows: Conda Install not working?

### ISSUE THREAD

**Issue by afogarty85** [facebookresearch/faiss#1277]
Following instructions here https://github.com/bitsun/faiss-windows/blob/master/INSTALL.md to run:

conda install faiss-cpu -c pytorch

This yields: PackagesNotFoundError: The following packages are not available from current channels:

CPU only version returns the same:

conda install faiss-cpu -c pytorch

# Platform

OS: Windows 10

# Torch

I am using a nightly torch:

torch                            1.7.0.dev20200705

**Comment by bitsun** [comment]
they do not officially support windows yet. But  I do have a windows port in my  branch https://github.com/bitsun/faiss, and i included very detailed instructions of building python wrapper on windows, check the file INSTALL_cmake.md there

**Comment by afogarty85** [comment]
> they do not officially support windows yet. But I do have a windows port in my branch https://github.com/bitsun/faiss, and i included very detailed instructions of building python wrapper on windows, check the file INSTALL_cmake.md there

I appreciate your time and help!
