### ISSUE TITLE
`IndexRefineFlat` does not support `downcast_index`

### ISSUE THREAD

**Issue by QwertyJack** [facebookresearch/faiss#1278]
# Summary

`IndexFactory` or `read_index` will lose type info of a `IndexRefineFlat` object. Thus, one
can not change the parameter `k_factor` in some situation (such as write the index and read back).

# Platform

OS:  not platform-specific

Faiss version:  1.6.3

Faiss compilation options:  all

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

 

```python
index_inner = faiss.index_factory(...)
index = faiss.IndexRefineFlat(index_inner)
index.k_factor = 4     # this is ok

faiss.write_index(index, 'refined.index')
index = faiss.read_index('refined.index')
index.k_factor = 5     # 'Index' object has no attribute 'k_factor'
faiss.ParameterSpace().set_index_parameter(index, 'k_factor', 5)    # try another method, still error

# using `index_factory`
index = index_factory(d, 'RFlat,IVF...')
index.k_factor = 4     # error
```

**Comment by QwertyJack** [comment]
From the source code `impl/index_write.cpp` I find that the last 4 bytes of a `IndexRefineFlat` index is actually the parameter `k_factor`. Here is a dirty way to change the parameter after writing the index to the disk:

```python
# write the IndexRefineFlat object to the disk
faiss.write_index(index, 'refined.index')

# open it using mmap
buffer = np.memmap('refined.index', dtype='uint8', mode='r+')

# change the parameter `k_factor`, i.e. to `5`
buffer[-4:] = np.array([5], dtype='float32').view('uint8')

# save and clean up
del buffer
```

BTW,
maybe changing `struct IndexRefineFlat: Index` to `struct IndexRefineFlat: IndexFlat` helps.

**Comment by QwertyJack** [comment]
Actually casting on `index.base_index` will work.

**Comment by QwertyJack** [comment]
I find the root cause: `IndexRefineFlat` is missing in the swig file.

**Comment by mdouze** [comment]
Confirmed: https://github.com/facebookresearch/faiss/blob/master/python/swigfaiss.swig#L565
Mark as enhancement, we will work on this.

**Comment by QwertyJack** [comment]
Thanks to your work! I'm closing this issue since it's been merged.
