### ISSUE TITLE
The question about "nredo" in Clustering::train_encoded 

### ISSUE THREAD

**Issue by hws912** [facebookresearch/faiss#1281]
# Summary

I have a question about the code below in  Clustering.cpp. 
According the code below, the clustering result is better with "err" being smaller.
But I think this is only right when we use METRIC_L2,  and the clustering result is better with "err" being bigger for METRIC_INNER_PRODUCT.
I'm not sure if my idea is correct，looking forward to your answer, thanks.

`if (nredo > 1) {
            if (err < best_err) {
                if (verbose) {
                    printf ("Objective improved: keep new clusters\n");
                }
                best_centroids = centroids;
                best_obj = iteration_stats;
                best_err = err;
            }
            index.reset ();
        }`

**Comment by mdouze** [comment]
Yes indeed, this is the case only for L2 distance. 
The problem with inner product search is that there is no objective that is optimized. For IP indexes we often just fall back to clustering with L2 normalization of the centroids (the `spehrical` option in https://github.com/facebookresearch/faiss/blob/master/Clustering.h#L27). 
Marking this as an enhancement.

**Comment by hws912** [comment]
> Yes indeed, this is the case only for L2 distance.
> The problem with inner product search is that there is no objective that is optimized. For IP indexes we often just fall back to clustering with L2 normalization of the centroids (the `spehrical` option in https://github.com/facebookresearch/faiss/blob/master/Clustering.h#L27).
> Marking this as an enhancement.

Got it, thanks a lot!
