### ISSUE TITLE
  FAISS_ASSERT (list_no < nlist) failured!

### ISSUE THREAD

**Issue by Markliang1994** [facebookresearch/faiss#129]
I must tell u that I modify the index_io.h and index_io.cpp to make the Index can seralize to db.(In my case I use a vector<char> then use memcpy). Everything seem to very well. but today the program crashed. 
I try to import data to faiss. use faiss::IndexIVFFlat. First of all, I build a empty Index by blow code.
`   int nlist = 1; // we only have 1 nlist. when you see this code read https://github.com/facebookresearch/faiss first
        faiss::IndexFlatL2 quantizer(DIMEN);
        faiss::IndexIVFFlat index(&quantizer, DIMEN, nlist, faiss::METRIC_L2);` 
then use my serialize tool write to redis. 

if the user click to import, the blow code will run
` 
  
    readindex(libidstr, findex);   // findex std::shared_ptr<faiss::IndexIVFFLat>
    if(!detail::isTrained(libidstr)) {
        findex->train(1, vec);
    }
   findex->add_with_ids(1, vec, &qid);    // core dumped!!!
`
Ignore my usage QAQ.

the core information 

> in faiss::IndexIVFFlat::add_core (this=0x1667c90, n=1, x=0x1f75850, xids=<optimized out>, precomputed_idx=0x0) at IndexIVF.cpp:249

 IndexIVF.cpp:249 is:`FAISS_ASSERT (list_no < nlist);`
 When I use gdb to debug. I find the nlist valus is: 1 because the list_no value is optimize out, I add some code to see the list_no value.

 if(!detail::isTrained(libidstr)) {
        findex->train(1, vec);
    }

    {
        int n = 1;
        long * idx0 = new long [n];
        findex->quantizer->assign (n, vec, idx0);
        const long * idx;
        idx = idx0;
        for (size_t i = 0; i < n; i++) {
            long list_no = idx[i];
            LOG2(forStat, ERROR, "list_no is: " << list_no << " nlist is: " << findex->nlist);
            if (list_no < 0)
                continue;
            FAISS_ASSERT (list_no < findex->nlist);
        }
    }

    findex->add_with_ids(1, vec, &qid);`

and the log content

> 2017-06-07 01:00:19,509 ERROR 0x7fbeb5fcfa80 list_no is: 0 nlist is: 1
2017-06-07 01:00:19,637 ERROR 0x7fbeb5fcfa80 list_no is: 0 nlist is: 1
2017-06-07 01:00:19,664 ERROR 0x7fbeb5fcfa80 list_no is: 0 nlist is: 1
2017-06-07 01:00:20,039 ERROR 0x7fbeb5fcfa80 list_no is: -1 nlist is: 1

this very strange. list_no is -1 but  FAISS_ASSERT(list_no < nlist) crashed!
may be because of my serialize tool?

**Comment by mdouze** [comment]
Hi 

This is most likely due to your changes in the Faiss code, we cannot debug that.
