### ISSUE TITLE
Difference between faiss.Clustering and faiss.Kmeans

### ISSUE THREAD

**Issue by haohang96** [facebookresearch/faiss#1291]
# Platform

OS:  Ubuntu 16.04

Faiss version:  1.6.3

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

1:  When I use faiss do kmeans clustering, I found two similar interface: faiss.Clustering() and faiss.Kmeans()

```
# standard usage of faiss.Clustering #
# x: features need to be clustered
n_data, d = x.shape
ncentroids = 3000

clus = faiss.Clustering(d, ncentroids)
clus.niter = 20

res = faiss.StandardGpuResources()
flat_config = faiss.GpuIndexFlatConfig()
flat_config.device = 0 # gpu_id 

index = faiss.GpuIndexFlatL2(res, d, flat_config)
clus.train(x, index)


# standard usage of faiss.Kmeans  #
# refer (https://github.com/facebookresearch/faiss/wiki/Faiss-building-blocks:-clustering,-PCA,-quantization) #
# x: features need to be clustered
n_data, d = x.shape
ncentroids = 3000
niter = 20

kmeans = faiss.Kmeans(d, ncentroids, niter, gpu=True)

kmeans.train(x)
```

It seems that the usage of faiss.Clustering and faiss.Kmeans is almost the same, except that clus.train() need index as param but kmeans.train() do not. **So what are the relation and difference between faiss.Kmeans and faiss.Clustering?  Which one is recommended?**

2: Another question is that when I need do spherical k-means, I found **For spherical k-means, use GpuIndexFlatIP and set cp.spherical = true** in [GPU k means example(c++)](https://github.com/facebookresearch/faiss/wiki/GPU-k-means-example).

So in python, Is it right like below?
```
# spherical k-means #
# x: features need to be clustered
n_data, d = x.shape
ncentroids = 3000

clus = faiss.Clustering(d, ncentroids)
clus.niter = 20
clus.spherical = True # add this for spherical k-means

res = faiss.StandardGpuResources()
flat_config = faiss.GpuIndexFlatConfig()
flat_config.device = 0 # gpu_id 

index = faiss.GpuIndexFlatIP(res, d, flat_config) # use inner-product for spherical k-means
clus.train(x, index)
```

3: The final question is how can I use faiss.Kmeans() do spherical k-means?  I have test that it's OK to specify **spherical=True** constructor option in the KMeans object: `kmeans = faiss.Kmeans(spherical=True)`
But how can I assign a special index(index = faiss.GpuIndexFlatIP) to faiss.Kmeans()?

**Comment by wickedfoo** [comment]
`Kmeans` is just a wrapper around the `Clustering` object.

https://github.com/facebookresearch/faiss/blob/a17a631dc326b3b394f4e9fb63d0a7af475534dc/python/faiss.py#L698

setting `.cp.spherical = True` on the `Kmeans` object will enable spherical clustering (the vectors will be constrained to lie on the surface of a unit hypersphere).
