### ISSUE TITLE
For Kmeans clustering in Python, how can I initialize centroids with computed array instead of random initialization ?

### ISSUE THREAD

**Issue by weixuansun** [facebookresearch/faiss#1294]
# Summary

When doing kmeans in python, I am trying to set pre-computed centroids before training instead of random initialization, I wonder how can I do that?

# Platform

OS: ubuntu18.04

Running on: GPU

Interface: Python

**Comment by QwertyJack** [comment]
+1

**Comment by wickedfoo** [comment]
I believe setting `centroids` with your desired starting centroids on the `Clustering` object before performing k-means clustering will start with that centroid set.

https://github.com/facebookresearch/faiss/blob/master/Clustering.h#L73

**Comment by QwertyJack** [comment]
How can I do so for `IndexIVF.train()`?

**Comment by QwertyJack** [comment]
> How can I do so for `IndexIVF.train()`?

Might be difficult for now; add a `Clustering` object to `IndexIVF::Level1Quantizer` would help.

**Comment by wickedfoo** [comment]
All IndexIVF classes have a `cp` member which is the `ClusteringParameters` used for the IVF clustering.

https://github.com/facebookresearch/faiss/blob/master/IndexIVF.h#L45

**Comment by mdouze** [comment]
Right. This should be documented better.

**Comment by mdouze** [comment]
See here: 
https://github.com/facebookresearch/faiss/wiki/Python-C---code-snippets#how-can-i-force-the-k-means-initialization

**Comment by sthalles** [comment]
What version of faiss is the 'init_centroids' parameter available? I am using faiss-gpu 1.6.3 and when I run the notebook, I get.

```got an unexpected keyword argument 'init_centroids'```

**Comment by mdouze** [comment]
Ah right, it may be available only in the latest version of Faiss. 
As a quick workaround, you can just patch your faiss.py with the code here: 
https://github.com/facebookresearch/faiss/blob/750d43f/faiss/python/__init__.py#L693

**Comment by sthalles** [comment]
Thanks.

**Comment by Solacex** [comment]
> Ah right, it may be available only in the latest version of Faiss.
> As a quick workaround, you can just patch your faiss.py with the code here:
> https://github.com/facebookresearch/faiss/blob/750d43f/faiss/python/__init__.py#L693

Hello, I tried to replace the code in the file you mentioned, but it does not work. 
I am currently using faiss-1.6.1, are there any possible solutions for this?

**Comment by xushilin1** [comment]
> Ah right, it may be available only in the latest version of Faiss. As a quick workaround, you can just patch your faiss.py with the code here: https://github.com/facebookresearch/faiss/blob/750d43f/faiss/python/__init__.py#L693

This method has failed if faiss-gpu==1.6.1
Are there any other methods to initialize centroids now?

**Comment by xushilin1** [comment]
> > Ah right, it may be available only in the latest version of Faiss. As a quick workaround, you can just patch your faiss.py with the code here: https://github.com/facebookresearch/faiss/blob/750d43f/faiss/python/__init__.py#L693
> 
> This method has failed if faiss-gpu==1.6.1 Are there any other methods to initialize centroids now?

I found a way to solve this problem.
It is better to use `faiss.Clustering` instead of `faiss.Kmenas` and use `faiss.copy_array_to_vector(faiss.vector_to_array(km.centroids).ravel(), clus.centroids)` to initialize the centroids.
