### ISSUE TITLE
Confusion about Asymptotic Complexity

### ISSUE THREAD

**Issue by ashfaq92** [facebookresearch/faiss#1297]
Consider two methods:
 
Method 1.
```
import faiss      
index = faiss.IndexFlatL2(d) 
index.add(xb)   
index.search(xq)
```

Method 2. 
```
nlist = 100
k = 4
quantizer = faiss.IndexFlatL2(d)  # the other index
index = faiss.IndexIVFFlat(quantizer, d, nlist)
index.train(xb)
index.add(xb)   
```

From the study of related research papers, as far as i knew, the Asymptotic growth of method 1 would be linear O(n), that of method 2 should be sublinear O(n/k). When I run experiments for searching nearest neighbor for `n` times, method 1 followed quadratic growth (which makes sense i.e. O(n * n) = O(n^2). However, method 2 seem to follow linear or log-linear growth, which is beyond my understanding. Isn't it should also follow quadratic growth i.e. O(n * n / k) = O(n^2 / k) = O(n^2). I could not see theoretical complexity analysis in papers (i am talking about `faiss-cpu`). The results are follows:

![image](https://user-images.githubusercontent.com/28701122/87873548-18e43180-c9f5-11ea-8ff2-9f3de5f8e79e.png)

**Comment by mdouze** [comment]
If you fix nlist, it should indeed be quadratic indeed (although it is weird to measure this with a growing query set). Maybe this would be visible if you plot in log-scale on the y axis.
