### ISSUE TITLE
Jaccard similarity 

### ISSUE THREAD

**Issue by SidharthChandra** [facebookresearch/faiss#1299]
Running on:
- CPU

Interface: 
- Python
 
How can I find Jaccard similarity

**Comment by mdouze** [comment]
I assume this is 

jac(a, b) = sum_i min(a_i, b_i) / sum_i max(a_i, b_i)

It is not supported. I'll mark it as an enhancement. We already support other weird similarity measures.

**Comment by mdouze** [comment]
TODO check if this is a similarity or dis-similarity 
(most of the code assumes all distances except INNER_PRODUCT are dis-similarities)

**Comment by NinaCalvi** [comment]
has this been added?

**Comment by edgBR** [comment]
Ey, this would be a good feature to have.

Even gower distance would nice to have:

https://ruivieira.dev/gower-distance.html

**Comment by lvoursl** [comment]
Implemented and committed to the main branch, closing this issue :)

**Comment by mansourshams** [comment]
I use langchain with jaccard similarity, it returns large numbers (200 range)
