### ISSUE TITLE
Retrieve Parameters from Index

### ISSUE THREAD

**Issue by keekiat** [facebookresearch/faiss#1302]
API Question:

I train/built an IndexPQ sometime ago but forgot what code_size and n_bits I used initially. Is there a way to retrieve code_size and n_bits from the python API?

I looked around the API and found that i can retrieve ntotal (index total size) and d (dimension size)
Thanks!

**Comment by mdouze** [comment]
These fields are available in the `index.pq` field, see https://github.com/facebookresearch/faiss/blob/master/impl/ProductQuantizer.h#L23

**Comment by keekiat** [comment]
ok thanks i deep dive into it further
