### ISSUE TITLE
Ability to use 32-bit indices

### ISSUE THREAD

**Issue by cjnolet** [facebookresearch/faiss#1304]
I can't remember if I've asked this before and I couldn't find a related issue about it. 

Currently the `faiss::Index::idx_t` seems limited to a 64-bit integer. Is there any way we can use 32-bit indices today? 

If not, could this feature be added without too much trouble?

**Comment by wickedfoo** [comment]
Yes, most CUDA kernels in Faiss perform indexing arithmetic only in int32/uint32 (save for dealing with user-provided int64 indices), this should be easy to add. In fact, for the brute-force code, extra work is done anyways to translate to idx_t:

https://github.com/facebookresearch/faiss/blob/master/gpu/GpuDistance.cu#L87

**Comment by mdouze** [comment]
no acitivity, closing.

**Comment by zbjornson** [comment]
@mdouze this hasn't been implemented though. Do you have a separate place to track feature requests?

**Comment by wickedfoo** [comment]
This could be done for the bfKnn function, but we will not do this for the indices themselves.

**Comment by zbjornson** [comment]
@wickedfoo can you clarify what you mean please? As in, you're able to add a conversion layer, but the implementation internally would still use int64?

**Comment by wickedfoo** [comment]
The brute-force function `bfKnn` that cuML is using will be able to use int32 natively, but indices (e.g., GpuIndexIVFFlat, GpuIndexIVFPQ, even those which are brute-force having the index interface like GpuIndexFlat) will continue to operate only in int64, as they try to keep some parity with the CPU interface on this.

Perhaps a future version of the API could allow for different data types of the inputs (e.g., float16 data, int32 indices, etc), but not happening anytime soon.

**Comment by wickedfoo** [comment]
(I'm speaking for the GPU side of Faiss here which is what @cjnolet was effectively inquiring about)

**Comment by zbjornson** [comment]
Aha thanks, I got confused between "index" (GpuIndexIVFFlat) and "indices" (KNN indices).

**Comment by wickedfoo** [comment]
This is now implemented in https://github.com/facebookresearch/faiss/pull/1445, will likely push tomorrow.

**Comment by wickedfoo** [comment]
committed
