### ISSUE TITLE
Non exhaustive search returns -1 as index

### ISSUE THREAD

**Issue by b4r0** [facebookresearch/faiss#1309]
# Summary

Searching for the Knn on a 100K vectors dataset with IVFFlat index return -1 as index id after a certain point (e.g when k is 1000 searching with IVFFlat returns -1 after index 102)

# Platform

OS: Ubuntu 18.04.4 LTS

Faiss version: 1.6.3

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

This is how I implemented the index

res = faiss.StandardGpuResources()
d = 2048
C = 4
n_centroid = int(C * math.sqrt(dataset_size))
gpu_index = faiss.GpuIndexIVFFlat(res, d, n_centroid, faiss.METRIC_L2)

**Comment by wickedfoo** [comment]
https://github.com/facebookresearch/faiss/wiki/FAQ#what-does-it-mean-when-a-search-returns--1-ids

**Comment by b4r0** [comment]
Thank you very much.
