### ISSUE TITLE
BLAS Requirement

### ISSUE THREAD

**Issue by arnaudmiribel** [facebookresearch/faiss#131]
Good morning,

__CONFIG__ : EC2 g2 instance - Ubuntu 64
I installed BLAS using the following (as stated [here](https://askubuntu.com/questions/623578/installing-blas-and-lapack-packages))

```
sudo apt-get install libblas-dev liblapack-dev
```

Now, testing BLAS using `make tests/test_blas`. Output:

```
cc  tests/test_blas.cpp -o tests/test_blas  
/tmp/cctKib5n.o: In function `new_random_vec(int)':
test_blas.cpp:(.text+0x31): undefined reference to `operator new[](unsigned long)'
/tmp/cctKib5n.o: In function `main':
test_blas.cpp:(.text+0x106): undefined reference to `operator new[](unsigned long)'
test_blas.cpp:(.text+0x176): undefined reference to `sgemm_'
test_blas.cpp:(.text+0x2f0): undefined reference to `operator new[](unsigned long)'
test_blas.cpp:(.text+0x330): undefined reference to `sgeqrf_'
collect2: error: ld returned 1 exit status
Makefile:58: recipe for target 'tests/test_blas' failed
make: *** [tests/test_blas] Error 1
```

Any hint on this ? Thanks!

**Comment by mdouze** [comment]
Hi 

For some reason you are compiling with a C compiler not C++.

**Comment by arnaudmiribel** [comment]
Sorry, I'm not quite sure how to solve this. Any hint on how to check these `make` default rules, change them ?

**Comment by mbstrange** [comment]
@arnaudmiribel make sure you install g++, but the first line of your makefile.inc should be CC=g++.  Like @mdouze said, if you use the makefile this shouldn't be a problem.

**Comment by mdouze** [comment]
Thanks @mbstrange! 
Closing issue.
