### ISSUE TITLE
when will METRIC_INNER_PRODUCT be fully implemented on GpuIndexIVFPQ?

### ISSUE THREAD

**Issue by SupermeReturns** [facebookresearch/faiss#132]
Hello!
Our projects requires to store more than 100Millions vectors (256D) on GPU, so we plan to use GpuIndexIVFPQ in order to compress the data, but METRIC_INNER_PRODUCT is not implented in GpuIndexIVFPQ which is a must for our projects.
So could you please tell us when will METRIC_INNER_PRODUCT be fully implemented on GpuIndexIVFPQ?

thank you very much

**Comment by mdouze** [comment]
Hi 

Implementing this is not currently high on our priority list. 

You may be interested in http://ulrichpaquet.com/Papers/SpeedUp.pdf section 3 that transforms inner product computations into L2 distance computations.

**Comment by kittenkaka** [comment]
METRIC_INNER_PRODUCT is not implented in IndexIVFFlat？ I set nlist = 100, nprobe = 10 in IndexIVFFlat, but not get the correct result..

**Comment by mdouze** [comment]
Hi 
Please open a new issue with a complete bug report.

**Comment by billkle1n** [comment]
@mdouze assuming vectors are normalized before indexing/training/search,  wouldn't `(2-distances**2)/2` convert the `METRIC_L2` distances (returned by the search function) to cosine similarities?

**Comment by mdouze** [comment]
Yes for normalized vectors.

**Comment by billkle1n** [comment]
@mdouze thanks. I just noticed that the distances returned by IVFPQ are already squared so it would be `(2-distance) / 2`
