### ISSUE TITLE
Write/Read index fails with GPU+IVF+SQ

### ISSUE THREAD

**Issue by steplee** [facebookresearch/faiss#1324]
# Summary

Using SQ + IVF, moving to GPU, training/adding, then saving, then loading leads to a segfault.
Perhaps I am missing a step, but doing the same thing with PQ or Flat instead of SQ works as expected.

# Platform

OS: Ubuntu 18.04

Faiss version: v1.6.0

Faiss compilation options: Python (3.6), CUDA 10.2

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

Only SQ with IVF crashes, PQ works.
Training + adding without copying to gpu also works.
However, using SQ+IVF+Gpu segfaults:
```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007fffd9bba71f in faiss::(anonymous namespace)::Codec8bit::decode_component (i=<optimized out>,
    code=<optimized out>) at impl/ScalarQuantizer.cpp:69
69              return (code[i] + 0.5f) / 255.0f;
(gdb) 
```

```
import faiss, numpy as np

x = np.random.randn(5000,32).astype(np.float32)

i = faiss.index_factory(32,'IVF32,SQ8') # PQ8 works, SQ8 without IVF works.

i = faiss.index_cpu_to_gpu(faiss.StandardGpuResources(), 0, i)
i.train(x)
i.add(x)
i = faiss.index_gpu_to_cpu(i)
faiss.write_index(i, 'b')
i2 = faiss.read_index('b')
i2.search(x[:5], 5) # Crashes.
```

The index takes up disk space, but when loaded has `ntotal` zero.

**Comment by mdouze** [comment]
I can't repro the crash -- it works for me on the latest Faiss.

**Comment by steplee** [comment]
Okay. Hopefully it was related to the old version, or something with my build. I am just using the GPU for now. Thanks.
