### ISSUE TITLE
Faiss memory allocation

### ISSUE THREAD

**Issue by manmitya** [facebookresearch/faiss#1326]
# Summary

Hi! Is there information somewhere in the faiss documentation about how memory allocation is managed in faiss and how this process can be affected? How do I find out how much memory is currently allocated for the faiss index?
In issue #758, I read that when adding new indexes, when new memory is needed, fiass doubles the memory allocated to it.
How much memory is allocated to the faiss index during initial initialization and when does the index double?

# Platform

OS: CentOS 7.6 x86-64

Faiss version: faiss-cpu-1.6.1 from https://anaconda.org/conda-forge/faiss/files

Faiss compilation options: Anaconda3-5.2.0-Linux-x86_64 with Intel MKL

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

I use a FlatL2 type index with IDs. d = 128 * float32. I add vectors to faiss in chunks of 50,000 vectors at a time. When I try to add at least one new vector to the index with the number of vectors = 102,400,000, I get the error 'std::bad_alloc'.

**Comment by mdouze** [comment]
On CPU, Faiss mainly uses the C++ std::vector allocation, so there is nothing special there. It does geometric reallocation so OOM can happen even if the vectors would fit in RAM.

**Comment by manmitya** [comment]
Can I manage this process or optimize memory usage in some way?

**Comment by mdouze** [comment]
Take a look at 
https://github.com/facebookresearch/faiss/wiki/Indexes-that-do-not-fit-in-RAM
