### ISSUE TITLE
Does faiss have a function to delete and modify？

### ISSUE THREAD

**Issue by honghande** [facebookresearch/faiss#1329]
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
Please reformulate the question.

**Comment by honghande** [comment]
@mdouze I use the python version of faiss to add indexes. Suppose you want to delete one of the indexes, or delete some indexes in batches, and query the indexes, what function should I use faiss? At present, I have not found this function，thank you！

**Comment by mdouze** [comment]
I assume you mean add vectors to indexes. See 
https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes#removing-elements-from-an-index
