### ISSUE TITLE
FAISS installation in ubuntu16

### ISSUE THREAD

**Issue by sk-ubuntu** [facebookresearch/faiss#134]
The issue below was reported earlier but it was marked solve. Now I am facing the same issue. Any help is appreciated. Thanks

So, I have been browsing almost all the internet and haven't found the reason of this error. And although it may be a rookie mistake and I may be risking a huge facepalm from the developers, here it is:

I can't compile FAISS. I have modified the make.in.Linux file accordingly, but when I type make, I got the following error:

makefile.inc:66: *** missing separator. Stop.

It doesn't matter what I do, I always get the same error.

I have checked for wrongly placed tabs, or other potential mistakes of mine. But I can't see it.

Any help will be greatly appreciated.

**Comment by mdouze** [comment]
Hi 

The missing separator error usually is due to tab->space conversion. Could you post a gist with the makefile.inc you are using?

**Comment by sk-ubuntu** [comment]
Hi,
Please find the gist link : https://gist.github.com/sk-ubuntu/dac74b717e5ff4d9db48cda72eb81b79

I have copied makefile.inc.Linux from example_makefiles/ subdirectory to the directory where I have Makefile and changed the name of makefile.inc.Linux to makefile.inc.

Rest all the files are same. I have not made any changes to them. 

I have only made changes to makefile.inc since I am using Ubuntu 16.

Thanks.

**Comment by mbstrange** [comment]
@sk-ubuntu --- check your line 66 in makefile.inc --- just comment this line out.

`sudo apt-get install libopenblas-dev python-numpy python-dev`

This isn't supposed to be in the makefile, it's just the terminal command you would run to install a bunch of the prerequisites.  Copy and paste that into terminal and run it, then comment that line out in the makefile and this issue will go away.

**Comment by sk-ubuntu** [comment]
Thanks. That worked.
