### ISSUE TITLE
CPU faster than GPU?

### ISSUE THREAD

**Issue by mbstrange** [facebookresearch/faiss#135]
# Info

First off, I'm using Ubuntu 14, an i7-5930k,  a Pascal Titan X, 32GB of RAM, and I'm getting better results with the CPU, which seems counterintuitive. Is there a reason for this? I'm using the mkl libs for CPU.

I ran the demo_ivfpq_indexing / gpu versions that come with the faiss distribution.

# Results

These are the results for **CPU** (i7-5930k) **4.519 seconds**

![image](https://user-images.githubusercontent.com/10414055/27090490-f10e441a-5022-11e7-805d-54f1109efaeb.png)

and these are for the **GPU** (Titan X) **7.852 seconds**

![image](https://user-images.githubusercontent.com/10414055/27090561-24ef20b0-5023-11e7-91ef-e34e2910fba6.png)

**Comment by wickedfoo** [comment]
That time is from the start of the program, is it not? It's only querying the index once, and it takes time to upload kernel code to the GPU, allocate memory on the GPU, potentially load the driver if you are not using the persistent GPU driver, etc.

You'd need to compare the time for the actual query.

**Comment by mbstrange** [comment]
Queries on CPU looks like ~ (0.33s, search 0.30 s) on average
and for GPU it looks like ~ (1.53 s, search 1.24 s) on average,

**Comment by mbstrange** [comment]
It seems as if the CPU version subsamples 65k of the input size, but the GPU version handles all the inputs.

**Comment by mbstrange** [comment]
I was being stupid.  Once I made the problem size bigger the GPU made a fool of the CPU.
