### ISSUE TITLE
index_cpu_to_gpu gives aCERT EXP-60

### ISSUE THREAD

**Issue by paryang** [facebookresearch/faiss#1355]
# Summary

The coverity check gives CERT EXP-60 issue for index_gpu_to_cpu (), whcih means has a non-standard layout, across an execution boundary. Also, same issue for index_gpu_to_cpu， wirte_index, removed_ids and etc. Any suggestion for this issue? 

# Platform

OS: <Ubuntu server 16.04>

Faiss version: <faiss version 1.6.4>

Faiss compilation options: <cmakelist provied by faiss>

Running on:
- [* ] CPU
- [* ] GPU

Interface: 
- [* ] C++
- [ ] Python

# Reproduction instructions
code:
        cpu_index = faiss::read_index(index_file.c_str(), 0);

        options_single->indicesOptions=faiss::gpu::INDICES_64_BIT;
        options_single->useFloat16CoarseQuantizer = false;
        options_single->useFloat16 = false;
        options_single->usePrecomputed = false;
        options_single->reserveVecs = 0;
        options_single->storeTransposed = false;
        options_single->verbose = true;

        gpu_index = faiss::gpu::index_cpu_to_gpu(res_single, device_id, cpu_index, options_single);

erros message:
 CERT-CPP Expressions (CERT EXP60-CPP)
1. cert_exp60_cpp_violation: Passing res_single, which has a non-standard layout, across an execution boundary

 CERT-CPP Expressions (CERT EXP60-CPP)
1. cert_exp60_cpp_violation: Passing cpu_index, which has a non-standard layout, across an execution boundary.

**Comment by mdouze** [comment]
Would you mind explaining or providing some pointers on what "CERT EXP60-CPP" means?

**Comment by paryang** [comment]
CERT EXP60-CPP is a part of the C++ Coding Standards, which means not pass a nonstandard-layout type object across execution boundaries. for details, referenced to https://wiki.sei.cmu.edu/confluence/display/cplusplus/EXP60-CPP.+Do+not+pass+a+nonstandard-layout+type+object+across+execution+boundaries.

**Comment by wickedfoo** [comment]
What host compiler is nvcc using in this case?

Seems like the issue is when Faiss is being compiled with two different compilers (e.g., nvcc's host compiler is not the same as what is being used for the CPU code).

**Comment by paryang** [comment]
@wickedfoo the host compile of nvcc is gcc, same as cpu node. BTW, the write_index() also has the same issue which should be totally compiled by CPU node.

**Comment by mdouze** [comment]
Thanks for flagging. It seems low priority to fix this unless it actually causes a bug.
