### ISSUE TITLE
demo_ivfpq_indexing core dumped error

### ISSUE THREAD

**Issue by sk-ubuntu** [facebookresearch/faiss#136]
Hi,
When I am trying to test FAISS by running this command tests/demo_ivfpq_indexing, it throws me this error
![screenshot from 2017-06-14 13-26-41](https://user-images.githubusercontent.com/29388068/27145861-36b0b7e0-5105-11e7-94fe-200b4f0ede74.png)

Any help is appreciated.

Thanks

**Comment by mbstrange** [comment]
Did you edit the makefile any further? Could you post it again and/or the commands you used to build faiss.

**Comment by sk-ubuntu** [comment]
No I just commented line #66. 

https://gist.github.com/sk-ubuntu/19145ea64320e8aa3aad3d6ba4067b7a

I tested BLAS/Lapack and this is the output I got.

![image](https://user-images.githubusercontent.com/29388068/27153662-596e9822-5120-11e7-8b70-7ee3eeb7855b.png)

But when I tried make and then tests/demo_ivfpq_indexing I go the above error.

**Comment by mbstrange** [comment]
that output from ./test/test_blas is not an error as far as I'm aware.  I get a verbatim identical screen to you.  I'm on Ubuntu 14, however.

Can you post the specs of your system? I think this error can be thrown by a lack of memory resources.  I just ran it on my end and profiled it with top. It only ever consumed like 100MB though, so I'm remiss to pin it on that.

See if you can get a memory usage statistic

**Comment by sk-ubuntu** [comment]
I am running it on Oracle VM VirtualBox with 1GB RAM and 10GB HDD space.
But when I try to run the cmd : free -m, this is the stats I get

![image](https://user-images.githubusercontent.com/29388068/27155403-db945d2c-5126-11e7-9d47-118f71af5218.png)

I think so this might be a problem. How could I solve this?

Thanks

**Comment by mbstrange** [comment]
You need to give the VM more memory or they need to rewrite it so that everything needn't be in memory at the same time as far as I know. I think you should either allocate more memory to the VM or see if you can increase the virtual memory space.  You can't carry a gallon of water with a half gallon bottle, ya know?

**Comment by sk-ubuntu** [comment]
Thank you. It works.
