### ISSUE TITLE
self-defined id appeared shifting when remove_ids by using approximate algorithms!!!

### ISSUE THREAD

**Issue by victory-hsu** [facebookresearch/faiss#1379]
# Summary
when using brute-force, ind1=ind2; But using IVF100(this will train the index),ind1 !=ind2.

`
import numpy as np
import faiss

d = 768  
data = [[i] * d for i in range(500)]
data = np.array(data).astype('float32')
ids = np.arange(2000, 2500)
index = faiss.index_factory(d, "IDMap,IVF100,Flat", faiss.METRIC_L2)  
index.train(data)
index.add_with_ids(data, ids)

query_vector = np.array([[1] * 768]).astype('float32')
dis, ind1 = index.search(query_vector, 1)
print(ind1)
print(dis)

index.remove_ids(np.array([2000]))

query_vector = np.array([[1] * 768]).astype('float32')
dis, ind2 = index.search(query_vector, 1)
print(ind2)
print(dis)

assert ind1==ind2

`

# Platform

OS: 

Faiss version: <0.58.0>

Running on:
- CPU

Interface: 
- Python

# Reproduction instructions

the id should be equal when remove_other vectors

**Comment by mdouze** [comment]
This is expected, see https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes#removing-elements-from-an-index
