### ISSUE TITLE
image feature is 2-Dimensional, what is ids for one picture ?

### ISSUE THREAD

**Issue by linzuk** [facebookresearch/faiss#138]
i extract feature from image. every picture have 2-Dimensional feature, like [[0.32, 0.52 ...], [0.32, 0.52 ...], [0.32, 0.52 ...]].
when i index for one picture. it like this

xb = # xb extract from one image
index = faiss.IndexFlatL2(xb.shape[1])
index_with_ids = faiss.IndexIDMap(index)
index_with_ids.add_with_ids(xb, ids)

then, what is ids for one picture ?

and, what is xb and ids for many images ? (image feature is 2-Dimensional)

**Comment by linzuk** [comment]
does all the id for one picture xb is the same?
xb = # xb extract from one image
ids = [image_id] * xb.shape[0] # all the id for this image is same
index = faiss.IndexFlatL2(xb.shape[1])
index_with_ids = faiss.IndexIDMap(index)
index_with_ids.add_with_ids(xb, ids)

**Comment by mdouze** [comment]
Hi 

The code above will not work because ids must by a numpy array of type int64 not a Python list. And indeed, if you give the same id to all vectors, you will get a single id as output.

**Comment by linzuk** [comment]
64bit?

demo is
index = faiss.IndexFlatL2(xb.shape[1]) 
ids = np.arange(xb.shape[0])
index.add_with_ids(xb, ids)  # this will crash, because IndexFlatL2 does not support add_with_ids
index2 = faiss.IndexIDMap(index)
index2.add_with_ids(xb, ids) # works, the vectors are stored in the underlying index

so, xb.shape[0] value must be 64?

**Comment by linzuk** [comment]
So, when i index an image, the feature ID is really the same?
