### ISSUE TITLE
GPU_MAX_SELECTION_K

### ISSUE THREAD

**Issue by WaterElapse** [facebookresearch/faiss#1384]
# Summary

i have a demand: recall num > GPU_MAX_SELECTION_K(2048), recall num of result is between 5000 and 50000, simply modify GPU_MAX_SELECTION_K to 50000, will this work?
if not, what i need to do to make this possible ?
Will faiss support calculate in float16? not only for quantizer but for invert list.

# Platform
centos 7

OS: 

Faiss version: 1.6.3

Faiss compilation options:

Running on:
- [ ] CPU
- [ X] GPU

Interface: 
- [ X] C++
- [ ] Python

# Reproduction instructions

**Comment by wickedfoo** [comment]
No, it is limited to 2048 due to GPU register memory limitations.
