### ISSUE TITLE
CMake 3.17 is too high!

### ISSUE THREAD

**Issue by QwertyJack** [facebookresearch/faiss#1387]
I'm curious whether 3.17 is really necessary.

**Comment by mdouze** [comment]
Agreed. But note that installing cmake is very easy.

**Comment by QwertyJack** [comment]
It would be nice if we can downgrade cmake to 3.14, because then we can install it via anaconda.

**Comment by QwertyJack** [comment]
Today I find that CMake 3.18 is available in the anaconda main channel. So everything is fine now.

BTW, may I submit a PR about conda build?
