### ISSUE TITLE
why Spherical by default if the metric is inner_product

### ISSUE THREAD

**Issue by kittenkaka** [facebookresearch/faiss#139]
in file IndexIVF.cpp line 46, why Spherical by default if the metric is inner_product?

**Comment by mdouze** [comment]
Hi 

We observed that spherical assignment gives better results. This makes sense because otherwise the centroids with a higher norm inherently are assigned to more often, and unbalanced assignments are typically less efficient.

**Comment by kittenkaka** [comment]
Hi,
But it does't get correct result when I set spherical =true. 
In 2-IVFFlat.py  I set quantizer = faiss.IndexFlatIP(d) and index = faiss.IndexIVFFlat(quantizer, d, nlist) , but the result is quite different with 1-Flat.py

**Comment by mdouze** [comment]
Since the metric is different, there is no reason that the results are the same.
