### ISSUE TITLE
how to get nlist using indexfactory?

### ISSUE THREAD

**Issue by yusufazishty** [facebookresearch/faiss#1396]
here it is the snippet I used to build the faiss index 
```
index = faiss.index_factory(
        params['n_dim'], params['index_factory'], faiss.METRIC_L2)
index.train(vectors)
index.add_with_ids(vectors, ids)
```
with `n_dim=128` and `index_factory='OPQ16,IVF2048_HNSW32,PQ16'`

I wonder how do I get the n_list here since I'm using `index.nlist` is throwing error like [here](https://github.com/facebookresearch/faiss/issues/884)

is it taking `2048` as `nlist` is right  from the `index_factory` name?

or I could use something like [this](https://github.com/facebookresearch/faiss/issues/112)

if the second choice is right, then I should use 4*sqrt(index.ntotal)  CMIIW

**Comment by mdouze** [comment]
The number of inverted lists is 2048, see https://github.com/facebookresearch/faiss/wiki/The-index-factory#non-exhaustive-search-components

**Comment by yusufazishty** [comment]
Thank you!
