### ISSUE TITLE
Should we wait for ScaNN inside faiss?

### ISSUE THREAD

**Issue by sgjurano** [facebookresearch/faiss#1399]
Hi guys!

Do you have plans about supporting ScaNN algorithm inside faiss? 
https://github.com/google-research/google-research/tree/master/scann

**Comment by mdouze** [comment]
We are working on better support for PQ 4 bits in Faiss (which is the main advantage of SCANN over Faiss currently). 

NB that this is already supported in a fork of Faiss, see 
https://github.com/technicolor-research/faiss-quickeradc

**Comment by sgjurano** [comment]
Thanks for the link, I will check it :)
BTW, do you have some roadmap for faiss development?

**Comment by mdouze** [comment]
That is a recurrent question. 
There are some elements in a presentation we gave a recently: https://www.facebook.com/groups/faissusers/permalink/1017557432001876

**Comment by mdouze** [comment]
The 4-bit PQ implementation of SCANN is in Faiss. See benchmarks in 

https://github.com/facebookresearch/faiss/wiki/Indexing-1M-vectors
https://github.com/facebookresearch/faiss/wiki/Indexing-1G-vectors

**Comment by parsa-ra** [comment]
> The 4-bit PQ implementation of SCANN is in Faiss. See benchmarks in
> 
> https://github.com/facebookresearch/faiss/wiki/Indexing-1M-vectors https://github.com/facebookresearch/faiss/wiki/Indexing-1G-vectors

There is no mention of 4-bit PQ vs SCANN in billion-scale, is this a typo? Or I'm missing something.

**Comment by lqhl** [comment]
> We are working on better support for PQ 4 bits in Faiss (which is the main advantage of SCANN over Faiss currently).
> 
> NB that this is already supported in a fork of Faiss, see https://github.com/technicolor-research/faiss-quickeradc

hi @mdouze , has Quicker ADC been merged back to faiss?

**Comment by saraswat** [comment]
any update on this?

**Comment by mdouze** [comment]
see https://github.com/facebookresearch/faiss/wiki/Fast-accumulation-of-PQ-and-AQ-codes-(FastScan)
