### ISSUE TITLE
Using GPU via python interface

### ISSUE THREAD

**Issue by crcrpar** [facebookresearch/faiss#14]
Hi,

To try this fantastic library in python & GPU, I read the wiki and found that the link in [wiki](https://github.com/facebookresearch/faiss/wiki/Faiss-on-the-GPU#in-python) did not exist.

**Comment by mdouze** [comment]
Hi

Thanks for the comment. I replaced it with an existing script.

**Comment by crcrpar** [comment]
Thank you
