### ISSUE TITLE
How can I get the data in a Tensor type?

### ISSUE THREAD

**Issue by yyy007** [facebookresearch/faiss#140]
I got an incorrect result using the GPU implement, so I want to check the intermediate variate. In the file "gpu/impl/Distance.cu", I added some codes in function "void runIPDistance (GpuResources* resources, Tensor<T, 2, true>& centroids, ... )": ( I used the float input )
`float* data1=centroids.data();`
`for(int i=0;i<5;i++){`
     `printf("BaseData %d is 0x%08x\n",i,*(uint32_t*)(data1+i));`
`}`
But I got an error "Segmentation Fault". 
What's wrong with my codes, and how can I view a Tensor type data? Thank you!

**Comment by wickedfoo** [comment]
`centroids` is in the memory address space of the GPU, not CPU. You can't inspect the value from the GPU without copying it to the CPU.

**Comment by wickedfoo** [comment]
and you would have to properly synchronize with the stream where the computation that is producing results that you are inspecting before you copy

**Comment by yyy007** [comment]
I understand, thank you very much!
