### ISSUE TITLE
OPQ accuracy / Reproducing BigANN 10M results

### ISSUE THREAD

**Issue by ellchow** [facebookresearch/faiss#1400]
Hi,

I have been trying  to reproduce the BigANN 10M results (https://github.com/facebookresearch/faiss/wiki/Indexing-1G-vectors#10m-datasets) but have not been able to achieve the same a 1-recall@1. I am focusing on the OPQ + IVF HNSW + PQ variants.  For example let's take `OPQ64_128,IVF65536_HNSW32,PQ64`.   Instead of the 0.8 `1-recall@1` at 10^-1 seconds/query, I am only getting about 0.27.  What makes me confused/suspicious is that it stays at 0.27 regardless of what nprobe I use (I tried nprobe of 10, 1000, 10000, and 30000). To verify my setup, I tried `IVF65536_HNSW32,Flat` and that behaves as expected - higher nprobe leads to better 1-recall@1, getting close to 1 with nprobe=1000.

I then tried this on a smaller dataset (Sift 1M) and a simplified script to confirm the same behavior.  Indeed, I am seeing the same pattern.  I included the PQ variant _without_ the OPQ transform as well and it also behaves more like what I would expect.  Across different OPQ settings, the relative behavior also seems fine.

[This](https://gist.github.com/ellchow/fc26737db859f42bc92fbca272d47ffb) is the script I ran for Sift 1M and here is the output.

```
==========================
IVF2048,Flat memory nprobe 1 0.3942
IVF2048,Flat saved nprobe 1 0.3942
IVF2048,Flat memory nprobe 10 0.8674
IVF2048,Flat saved nprobe 10 0.8674
IVF2048,Flat memory nprobe 100 0.9898
IVF2048,Flat saved nprobe 100 0.9898
==========================
IVF2048,PQ64 memory nprobe 1 0.3622
IVF2048,PQ64 saved nprobe 1 0.3622
IVF2048,PQ64 memory nprobe 10 0.7489
IVF2048,PQ64 saved nprobe 10 0.7489
IVF2048,PQ64 memory nprobe 100 0.833
IVF2048,PQ64 saved nprobe 100 0.833
==========================
IVF2048,PQ8 memory nprobe 1 0.1948
IVF2048,PQ8 saved nprobe 1 0.1948
IVF2048,PQ8 memory nprobe 10 0.2954
IVF2048,PQ8 saved nprobe 10 0.2954
IVF2048,PQ8 memory nprobe 100 0.3039
IVF2048,PQ8 saved nprobe 100 0.3039
==========================
OPQ64,IVF2048,PQ64 memory nprobe 1 0.3727
OPQ64,IVF2048,PQ64 saved nprobe 1 0.3727
OPQ64,IVF2048,PQ64 memory nprobe 10 0.3727
OPQ64,IVF2048,PQ64 saved nprobe 10 0.3727
OPQ64,IVF2048,PQ64 memory nprobe 100 0.3727
OPQ64,IVF2048,PQ64 saved nprobe 100 0.3727
==========================
OPQ8,IVF2048,PQ8 memory nprobe 1 0.1978
OPQ8,IVF2048,PQ8 saved nprobe 1 0.1978
OPQ8,IVF2048,PQ8 memory nprobe 10 0.1978
OPQ8,IVF2048,PQ8 saved nprobe 10 0.1978
OPQ8,IVF2048,PQ8 memory nprobe 100 0.1978
```

The reason I compared the index in memory with one that was saved and loaded was to rule out any issues with serialization - in all my experiments, I have always saved the index before evaluating.  From this, saving/loading doesn't seem to be an issue.

Any insight would be much appreciated.

**Comment by mdouze** [comment]
This is because there is a pretransform. 
See https://github.com/facebookresearch/faiss/wiki/FAQ#how-can-i-set-nprobe-on-an-opaque-index

**Comment by ellchow** [comment]
Thanks - that fixes things!
