### ISSUE TITLE
Reconstructed vectors completely different from original vectors

### ISSUE THREAD

**Issue by howardwang15** [facebookresearch/faiss#1401]
# Summary

I've created and trained an index using the the factory string `PCAR100,IVF8192_HNSW32,SQ8`. My vectors are 768 dimensional (coming from BERT). I train on 1 million vectors and then add all the vectors to the index. 

After the index is built and saved, I read it back from disk and try to run some queries using the 768D vectors from the original dataset that the index was trained on, but the search always returns ids of -1. I try to call `reconstruct` using id's from the `IDMap2` wrapped around my index and comparing the original vectors to the reconstructed ones, they are completely different.

Is there something that I'm missing?

# Platform
Debian 9.12 (stretch)

OS: 

Faiss version: 
v1.6.3 (installed u=using pip)

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
Usually when there are -1 entries it is due to nprobe being too low. However, it is unlikely that the results are *all* -1. 

What do you mean by "completely different" ? PCA to 100D followed by scalar compression is quite violent, so expect the reconstruction to be approximate. BTW you don't need an IDMap2, you can use a hashmap, see https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes#direct-map-for-an-indexivf

**Comment by howardwang15** [comment]
Hi @mdouze , here's an example of the original vector in my dataset (part of the 768 dimensions). This is after I switched from the above factory string (I wanted to use a quantizer to reduce the size of the index, perhaps that's why the results were not what I expected?) to `PCA100,L2norm,IVF65536_HNSW32,Flat`. The results that I get from using the new index don't seem to be very different from what I got before when I compare my original vector to the reconstructed one.
 
```
array([ 2.76310652e-01, -1.22745909e-01, -7.65509546e-01, -6.89711347e-02,
       -9.90689814e-01,  6.82754964e-02,  8.85269165e-01, -3.37829232e-01,
        2.46092051e-01, -6.65157259e-01, -4.18106824e-01,  2.06796855e-01,
       -1.56525657e-01,  2.28337049e-01, -1.14603331e-02, -1.00692436e-01,
        7.71973312e-01,  1.84803560e-01,  5.09534776e-02, -5.42563200e-01,
       -2.93840080e-01, -2.05612153e-01, -9.19360947e-03, -3.85858677e-02,
        2.84246087e-01,  1.79520071e-01```
```
and here's the corresponding reconstructed vector

```
array([-1.62908122e-01, -8.74676108e-02, -5.75435497e-02, -1.30452007e-01,
       -1.66372061e-01, -5.71530648e-02,  1.08739130e-01,  8.59814286e-02,
        1.17583357e-01, -4.92691882e-02,  7.41730630e-02,  8.25016201e-02,
        3.14130969e-02, -3.75517160e-02,  1.29766449e-01,  8.88118818e-02,
        1.88591689e-01,  3.70975509e-02,  1.13011315e-01, -2.08391119e-02,
        1.91952810e-02, -9.06952620e-02,  4.28372845e-02, -1.31537721e-01,
       -2.76961923e-01,  1.49700776e-01,  1.07845418e-01,  4.26135212e-02,
       -1.18568428e-01, -6.85937610e-03
```
I'm probably misunderstanding what reconstruction does, I thought that the reconstructed vectors should be very close (ie difference = 0) to the original ones but it doesn't seem to be the case.

However, when I try to instead searching using the original vector, these are the results that I get (even after increasing nprobe to 1000)
```python
knn.nprobe = 1000
knn.search(x[np.newaxis], 10)  # x is now the original vector
```
```
(array([[3.4028235e+38, 3.4028235e+38, 3.4028235e+38, 3.4028235e+38,
         3.4028235e+38, 3.4028235e+38, 3.4028235e+38, 3.4028235e+38,
         3.4028235e+38, 3.4028235e+38]], dtype=float32),
 array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]]))
```

But, what I found through experimentation is that if I manually l2 normalize the original vector beforehand, then the search appears to work - however, I'm not sure why this is the case - I thought that the vector would've been l2 normed after doing the PCA.
```
(array([[0.        , 0.00153657, 0.00169334, 0.00196096, 0.00201936,
         0.00209208, 0.00217888, 0.00218532, 0.0022524 , 0.00226521]],
       dtype=float32),
 array([[1924038, 3340193, 5459200, 4404122, 5056092, 4571932, 5079087,
         6335297, 5053487, 3975833]]))
```

**Comment by howardwang15** [comment]
Actually, I just realized that I had to l2 normalize the vectors because I normalized them when I was indexing them - my mistake, closing this issue!
