### ISSUE TITLE
Using faiss IndexFlatIP  indexes from disk

### ISSUE THREAD

**Issue by MaheshChandrra** [facebookresearch/faiss#1403]
# Summary
Hi Team Faiss

Is it possible to read indexes directly from disk,instead of loading to RAM. I've used IndexFlatIP for my indexes and IndexIDMap2 for mapping those indexes to specific id's.

Thanks in advance!!
# Platform

OS: Ubuntu

Faiss version: '1.6.3'

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by QwertyJack** [comment]
Maybe adding mmap to io flag will help.

**Comment by mdouze** [comment]
Searching indexes from disk is supported only for IVF indexes. 
https://github.com/facebookresearch/faiss/wiki/Indexes-that-do-not-fit-in-RAM
