### ISSUE TITLE
Correction for tutorial/cpp/ 4-GPU.cpp and 5-Multiple-GPUs.cpp

### ISSUE THREAD

**Issue by yangyueren** [facebookresearch/faiss#1408]
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

 

https://github.com/facebookresearch/faiss/blob/d2d32af6c58c7f4227a3575365425a32b753ce0a/tutorial/cpp/4-GPU.cpp#L82
This line should be changed to  `faiss::gpu::GpuIndexIVFFlat index_ivf(&res, d, nlist, faiss::METRIC_L2);`

https://github.com/facebookresearch/faiss/blob/d2d32af6c58c7f4227a3575365425a32b753ce0a/tutorial/cpp/5-Multiple-GPUs.cpp#L47
This line should be changed to  `std::vector<faiss::gpu::GpuResourcesProvider*> res;`

**Comment by mdouze** [comment]
Thanks for the corrections! 
Makes me think that we should add building the tutorial to CI as well.

**Comment by HossamAmer12** [comment]
How do you compile this file using g++?
