### ISSUE TITLE
Wiki:  Example: increase the number of dimensions - Bug in code

### ISSUE THREAD

**Issue by hadjilucasL** [facebookresearch/faiss#141]
Hi,

I am wondering if the example code in the [Pre--and-post-processing wiki](https://github.com/facebookresearch/faiss/wiki/Pre--and-post-processing#example-increase-the-number-of-dimensions) page, section "Example: increase the number of dimensions"

Should be changed from:

```
  # input is in dimension d, but we want a multiple of M
  d2 = (d + M - 1) / M * M
  remapper = faiss.RemapDimensionsTransform (d, d2, true)
```

To:
```
  # input is in dimension d, but we want a multiple of M
  d2 = int((d + M) - (d % M))
  remapper = faiss.RemapDimensionsTransform (d, d2, true)
```

**Comment by wickedfoo** [comment]
The version at top results in `d2` being rounded up to the next highest multiple of `M` if it is not already a multiple of `M`; i.e., `(d + M - 1) / M` calculates ceil(d / M) using integer math, so the full expression is effectively `ceil(d / M) * M`.

Your version will result in `d2` being `d + M` if `d` is already a multiple of `M`.

**Comment by hadjilucasL** [comment]
Ah, ok got it, but then for your expression to work should it not be:

(d + M - 1) // M * M

per [PEP-238](http://www.python.org/dev/peps/pep-0238/) ?

otherwise

```
d=int(10)
M=int(8)
d2 = (d + M - 1) / M * M
print(d2)
17.0
```

**Comment by wickedfoo** [comment]
Yes, looks like it, didn't pay attention that it was Python. Thanks!

**Comment by mdouze** [comment]
Let's make it `int((d + M - 1) / M) * M` so that it works in py2 and py3.
