### ISSUE TITLE
Compile for real CUDA architecture, not virtual

### ISSUE THREAD

**Issue by jglaser** [facebookresearch/faiss#1416]
# Summary

the library calls `nvcc` with these options (in `./configure`)

```-gencode=arch=compute_52,code=compute_52 \\
-gencode=arch=compute_60,code=compute_60 \\
-gencode=arch=compute_61,code=compute_61 \\
-gencode=arch=compute_70,code=compute_70 \\
-gencode=arch=compute_75,code=compute_75"
```

This leads the compiler to generate PTX for those architectures, but does not actually produce binaries for them. Instead, the CUDA driver compiles the PTX into binary code **using JIT** whenever the context is created after dynamic library load, which incurs considerable latency in the application launch. Here, I am  using RAPIDS `cuml` which has FAISS as a dependency. Normally, the latency is masked by the JIT caching feature of CUDA (controlled, e.g. by the  `CUDA_CACHE_PATH` environment variable https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars), however, in my case, the default cache location wasn't writable leading the application to recompile the PTX with every context creation....

The above lines should be fixed like this:

```-gencode=arch=compute_52,code=sm_51 \\
-gencode=arch=compute_60,code=sm_60 \\
-gencode=arch=compute_61,code=sm_61 \\
-gencode=arch=compute_70,code=sm_70 \\
-gencode=arch=compute_75,code=sm_75"
```

# Platform

OS: 

Faiss version: a93a4b39571db0ab6ad0b4ef42a6b8734ca05135

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

Configure/compile with default options for `-with-cuda-arch`.

Current workaround (for V100):

```
./configure --with-cuda=<CUDA_TOOLKIT_DIR> --with-cuda-arch=-gencode="arch=compute_70,code=sm_70 <other_options>"
```

**Comment by wickedfoo** [comment]
@beauby The internal FB build uses compute_NN / sm_NN as well

**Comment by mdouze** [comment]
@beauby  @wickedfoo  what is the right approach here?

**Comment by beauby** [comment]
The packages for 1.6.4 (out soon) are compiled with `compute_NN/sm_NN`.

**Comment by ahmadudin** [comment]
> The packages for 1.6.4 (out soon) are compiled with `compute_NN/sm_NN`.

@beauby using 1.7.0 with `CMAKE_CUDA_ARCHITECTURE` specified, my build still executing JIT. Is that expected?

**Comment by beauby** [comment]
@ahmadudin What GPU do you have and what value are you passing to `CMAKE_CUDA_ARCHITECTURE`?
