### ISSUE TITLE
Python callbacks missing

### ISSUE THREAD

**Issue by daniel-acuna** [facebookresearch/faiss#1419]
# Summary

I used to be able to access the `PyCallbackIOReader` and `PyCallbackIOWriter` functions to read and write indices to exotic filesystems. However, I am getting an import error now in Python when I try something like `python -c "import faiss; print(faiss.PyCallbackIOWriter)"`

# Platform

OS: MacOS 10.15.6 

Faiss version: 1.6.3

Faiss compilation options: 

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

```bash
conda create -n test_environment python=3.7 -y
conda activate test_environment
conda install faiss-cpu -c pytorch -y
python -c "import faiss; print(faiss.PyCallbackIOWriter)"
```

**Comment by mdouze** [comment]
Hmm it should work, since this is tested in https://github.com/facebookresearch/faiss/blob/master/tests/test_io.py#L53

**Comment by daniel-acuna** [comment]
That's what surprised me too. The API works on Ubuntu. I'll just avoid using this API on Mac OS, for now. Thanks
