### ISSUE TITLE
New conda package for recent updates

### ISSUE THREAD

**Issue by cjnolet** [facebookresearch/faiss#1420]
It looks like the packages on conda-forge are about 3.5 months old but there have been several more recent updates in the Github repository that we are hoping to start using in cuML (such as the 32-bit brute force indices and pluggable memory management). It would be great to have a new conda package on conda-forge with these updates.

**Comment by beauby** [comment]
@cjnolet We are not in charge of the `conda-forge` packages for Faiss, but we will release new packages on the `pytorch` channel .
