### ISSUE TITLE
Installation problem:Policy CMP0104 is not set

### ISSUE THREAD

**Issue by john4d20** [facebookresearch/faiss#1424]
# Summary
cmake -B build .
After I enter this command , the error message shows in the following:

-- Could NOT find MKL (missing: MKL_LIBRARIES) 
-- A library with LAPACK API found.
-- Configuring done
CMake Warning (dev) in faiss/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "faiss".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/ubuntu/faiss

I have no idea to deal with it , besides I am using jetson NX

**Comment by QwertyJack** [comment]
Just turn off CUDA if you want to build cpu-only version:

```bash
mkdir build && cd build
cmake .. -DFAISS_ENABLE_GPU=OFF
```

**Comment by john4d20** [comment]
sorry, I need the gpu version

**Comment by beauby** [comment]
@john4d20 With CMake 3.18 you need to provide the CUDA architectures you want to build Faiss for. Example for a Turing GPU: `cmake -DCMAKE_CUDA_ARCHITECTURES=75 -B build .`.
