### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by lukedeo** [facebookresearch/faiss#143]
Are there any updates on conversion to *anything* but CC-by-NC? The CC folks even [say](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) that this shouldn't be used for software. I'd love to use this library in more cases, but my legal counsel has suggested I stay away until this gets resolved at some point in the future, even for more research oriented purposes.

**Comment by mdouze** [comment]
Hi @lukedeo 

I understand your concern. There are discussions ongoing internally on this topic. Unfortunately there is no evolution on the license front on this for the time being.

**Comment by billkle1n** [comment]
I'm in the same boat. It's not even clear if I can run the software on my work laptop with the current license.

**Comment by mdouze** [comment]
We relaxed the FAISS license.
