### ISSUE TITLE
Advises for avoiding peaking time in search using FAISS

### ISSUE THREAD

**Issue by vmthanh** [facebookresearch/faiss#1430]
# Summary
Hi, our team are building a 1-N searching using FAISS as the core for searching. The requirement for our system is that:
- The size of dataset started at 5M and will keep gradually increasing (which we expect to reach 10M at the end of this year). 
- Embedding vector is in 512 length
- Update pipeline will run every 15mins for adding more embedding vectors to the whole db (1000 vectors / update)
- Search using cosine similarity 
- TopK = 30

Given with those requirements, I built the index for the FAISS with index_string `IVF16384_HNSW32,Flat`, nprobe = 300 and use GPU for training the clustering with given this code. 
```python
dim = 512
index_string = 'IVF16384_HNSW32,Flat'
self.faiss_emb_vec = faiss.index_factory(dim, index_string)
res = None 
res = faiss.StandardGpuResources()
if res is not None:
      index_ivf = faiss.extract_index_ivf(self.faiss_emb_vec)
      clustering_index = faiss.index_cpu_to_all_gpus(faiss.IndexFlatIP(dim))
      index_ivf.clustering_index = clustering_index
self.faiss_emb_vec.train(norm_emb_db_list_np_arr)
self.faiss_emb_vec.add(norm_emb_db_list_np_arr)
self.faiss_emb_vec.nprobe = 300 # Search in 300 closest cluster
``` 
When the system is launched, everything runs fine for almost 6 months till now with the searching time in FAISS about 15-20ms. But in last recent 30 days, we monitored and saw the some time peaking time in searching which the time went up to 800ms or more which makes the total response time for request > 1000ms. The interesting is that when we tried to collect those requests which have response time > 1s and called again, all requests ran very fast again within 200ms in total. The QPS of us is low, about 3-5 only. 

![Screenshot 2020-09-29 at 10 50 35](https://user-images.githubusercontent.com/8940457/94507156-b2c02a00-0241-11eb-969c-7d64f3b12848.png)

At the initial thought, I suspected that the update pipeline is affecting the query call. So that, I decided to slow it down to calling update every 30mins. But it seems not help. Then also, I tried to lower the **nprobe** to 200 and also the **topK** to 15. But still got peaking time frequently.

Im very appreciated if can hear from you guys some advises about this issue and also the way how to solve this. Few of questions I would like to mention here:
- Any advises for help reducing the peaking time in search. 
- As I understand, the FAISS will build (train) the clusters only one at the beginning. Then after that, when adding more vectors, it won't rebuild the index. Is it true? Does it mean that the new adding vectors will be added to the trained clusters only?
- If in some circumstances, is there anyway to rebuild the index on the fly? 

# Platform

OS: Ubuntu 16.04

Faiss version: **faiss-gpu==1.5.2** 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
Indeed the training is done once and for all. So if many vectors are added that correspond to a different data distribution, then the inverted lists will become unbalanced. You can monitor this by following index_ivf.invlists.imbalance_factor(), which should remain in the 1-10 range.

I would expect there is a drift in the data distribution that unbalances de dataset. However, since when you "replay" the search the peak does not show up, which suggests there is an external factor that slows down the search.

**Comment by vmthanh** [comment]
> Indeed the training is done once and for all. So if many vectors are added that correspond to a different data distribution, then the inverted lists will become unbalanced. You can monitor this by following index_ivf.invlists.imbalance_factor(), which should remain in the 1-10 range.
> 
> I would expect there is a drift in the data distribution that unbalances de dataset. However, since when you "replay" the search the peak does not show up, which suggests there is an external factor that slows down the search.

Hi @mdouze 
Thanks for quick reply. Regarding to ` monitor this by following index_ivf.invlists.imbalance_factor()`, how could I invoke to this parameter for monitoring? Because the code is already compiled and running right now. 

For some other similarity system like **Milvus** or **OpenDistro**, as I understand that the framework is built like "client-server" mechanism, the way I communicate is using "client" to connect to a "server" (Milvus server or ES server), and can get the information relating about the index name, number total of vectors, etc... But for FAISS, I dont know how to access this if the code is already complied and running.

**Comment by mdouze** [comment]
Faiss is a C++ library, not a client-server system. So if you can't change the code, you cannot do anything at the Faiss level.

**Comment by vmthanh** [comment]
Thanks for your answer. I will keep looking further on this.
