### ISSUE TITLE
Broken link in "Brute force search without an index" wiki

### ISSUE THREAD

**Issue by eyaltrabelsi** [facebookresearch/faiss#1436]
# Summary

At the ["Brute force search without an index wiki" ](https://github.com/facebookresearch/faiss/wiki/Brute-force-search-without-an-index) the link for the test_pytorch_faiss.py is broken and should be changed from [this](https://github.com/facebookresearch/faiss/blob/master/gpu/test/test_pytorch_faiss.py) to [this](https://github.com/facebookresearch/faiss/blob/master/faiss/gpu/test/test_pytorch_faiss.py)

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [x] C++
- [x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
Fixed! thanks for flagging.
