### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by junha-l** [facebookresearch/faiss#1437]
I see the number of PRs are merged to support Faiss on Windows

Is Faiss supported on Windows officially?

**Comment by mdouze** [comment]
Yes it is. 
We don't have precompiled packages yet, so you'll have to compile it yourself.

**Comment by h-vetinari** [comment]
Ooooh, @mdouze, that's interesting re: https://github.com/conda-forge/faiss-split-feedstock/pull/2. Is this something that applies to 1.6.3 already, or only to HEAD?

**Comment by mdouze** [comment]
We support conda packages for the pytorch channel. The conda-forge channel's packages do not work on windows yet AFAIK

**Comment by h-vetinari** [comment]
@mdouze 
I was simply not aware that things had moved since you opened conda-forge/faiss-split-feedstock#2. There should be no fundamental problem to build for windows on conda-forge as well.

**Comment by hcji** [comment]
@mdouze I find there has not been a precompiled package on conda-forge for windows. Is there a guide for how to compile the source code for win?

**Comment by beauby** [comment]
@hcji There are pre-compiled nightly packages available on the pytorch channel (`conda install -c pytorch/label/nightly faiss-cpu`).

**Comment by hcji** [comment]
@beauby Thank you. But the GPU version is not ready?

**Comment by h-vetinari** [comment]
Restarted the conda-forge effort for windows under https://github.com/conda-forge/faiss-split-feedstock/pull/17. With the build system changes from 1.6.3->1.6.4, it might still take a while, but should get there eventually.

**Comment by mdouze** [comment]
Windows is supported through anaconda now. closing.

**Comment by boluochuile** [comment]
@beauby That is great!

**Comment by h-vetinari** [comment]
Starting from today, there are now windows packages in conda-forge. Cuda support for windows is hopefully not far away either: conda-forge/faiss-split-feedstock#19.

**Comment by alextaymx** [comment]
May I know the steps to install faiss-gpu using anaconda on windows?

**Comment by h-vetinari** [comment]
Faiss is not yet available with GPU on windows. It will be available once [this PR](https://github.com/conda-forge/faiss-split-feedstock/pull/19) is merged, but realistically, that will only happen when faiss itself officially supports it - there's ongoing work for this in #1610.

Once that feedstock PR is merged, you will be able to do:
```
conda config --add channels conda-forge 
conda install faiss=*=*cuda
```
