### ISSUE TITLE
Advises for avoiding heap-allocated arrays and use VLA ?

### ISSUE THREAD

**Issue by bonezhang** [facebookresearch/faiss#1439]
hi,  can I submit a pr that looks like the following :

```
void IndexIVF::search (idx_t n, const float *x, idx_t k,
                           float *distances, idx_t *labels) const
    {
        idx_t idx[n * nprobe];
        float coarse_dis[n * nprobe];
        // std::unique_ptr<idx_t[]> idx(new idx_t[n * nprobe]);
        //std::unique_ptr<float[]> coarse_dis(new float[n * nprobe]);

        double t0 = getmillisecs();
        quantizer->search (n, x, nprobe, coarse_dis, idx);
        indexIVF_stats.quantization_time += getmillisecs() - t0;

        t0 = getmillisecs();
        invlists->prefetch_lists (idx, n * nprobe);

        search_preassigned (n, x, k, idx, coarse_dis,
                            distances, labels, false);
        indexIVF_stats.search_time += getmillisecs() - t0;
    }
 ```

Look forward to your reply！

**Comment by wickedfoo** [comment]
n * nprobe can essentially be without bound. I think it is indeterminate whether any given compiler will allocate VLAs on the stack or perhaps add code to overflow to the heap. The stack size per thread is something that can be configured and is not necessarily visible to the compiler, however, so in my opinion using VLA is potentially dangerous and could trigger guard pages or overflow the stack. An efficient heap allocator will maintain small block allocators for smaller allocation sizes, and the time of heap allocation relative to the general search method is small in any case.

**Comment by bonezhang** [comment]
thank you, i agree with you!
