### ISSUE TITLE
how to use function search and train of lsh?

### ISSUE THREAD

**Issue by vega110** [facebookresearch/faiss#144]
Direct code for my bug.
k = 2
hist = getSciImageHogHist("/data/project/pyspace/dog.jpg")
d = hist.shape[0]
xb_tmp = []
xb_tmp.append(hist1)
xb_tmp.append(hist2)
xb_tmp.append(hist3)
hist1, hist2, hist3 are the same format like hist1

xb_tmp = np.array(xb_tmp, dtype=np.float32)
n_bits = 2 * d
lsh = faiss.IndexLSH(d, n_bits)
lsh.add(xb_tmp)
#query param
xq_tmp = []
xq_tmp.append(hist)
q_tmp = np.array(xq_tmp)
D, I = lsh.search(q_tmp.astype('float32'), k)

when I ran above code, I got RuntimeError,
RuntimeError: Error in void faiss::hammings_knn(faiss::int_maxheap_array_t*, const uint8_t*, const uint8_t*, size_t, size_t, int) at hamming.cpp:501: Error: 'ncodes % 8 == 0' failed

can help me figure out what's wrong ?
boz online information search are not many, perhaps the users want more  a detailed description of demo codes.
can give me some right codes about lsh demo. 
ths.

**Comment by mdouze** [comment]
Hi, 

n_bits must be a multiple of 8 and only n_bits/8 = 4, 8, 16, 32 are supported currently.

**Comment by mdouze** [comment]
Sizes that are not a multiple of 8 bytes are supported now (thanks @alexandresablayrolles)
