### ISSUE TITLE
AttributeError: module 'faiss' has no attribute 'StandardGpuResources' on adding FAISS index to Hugging face Dataset

### ISSUE THREAD

**Issue by AndreGodinho7** [facebookresearch/faiss#1440]
Hello everyone,

I am having the following exception: ``AttributeError: module 'faiss' has no attribute 'StandardGpuResources'.`` when [adding a FAISS index to a Hugging Face Dataset. ](https://huggingface.co/docs/datasets/faiss_and_ea.html)

# Platform

OS: Ubuntu 18.04.5
Faiss version: 1.6.3

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

I am adding a [FAISS index to a Hugging Face Dataset](https://huggingface.co/docs/datasets/faiss_and_ea.html). When I am loading the FAISS index to the GPU it throws `AttributeError: module 'faiss' has no attribute 'StandardGpuResources'.`

`docs.load_faiss_index('embeddings', DATAPATH_INDEXED_ENCODED_PASSAGES, device=torch.cuda.current_device())`

**Notes:**
 `DATAPATH_INDEXED_ENCODED_PASSAGES` is a directory where I have .faiss file saved in disk.  

`print(docs.features)` 
>> `{'embeddings': Sequence(feature=Value(dtype='float64', id=None), length=-1, id=None),
 'passage': Value(dtype='string', id=None),
 'pid': Value(dtype='int32', id=None)}`

Any ideas?

The full trace is the following:
````
<ipython-input-6-389874b8ea37> in <module>
      1 docs = dpr_doc_sys.get_documents()['train']
----> 2 docs.load_faiss_index('embeddings', DATAPATH_INDEXED_ENCODED_PASSAGES, device=torch.cuda.current_device())
```

```
~/.conda/envs/andregodinho/lib/python3.6/site-packages/datasets/search.py in load_faiss_index(self, index_name, file, device)
    464             device (Optional `int`): If not None, this is the index of the GPU to use. By default it uses the CPU.
    465         """
--> 466         index = FaissIndex.load(file, device=device)
    467         assert index.faiss_index.ntotal == len(
    468             self
```

```
~/.conda/envs/andregodinho/lib/python3.6/site-packages/datasets/search.py in load(cls, file, device)
    332         index = faiss.read_index(file)
    333         if faiss_index.device is not None and faiss_index.device > -1:
--> 334             faiss_index.faiss_res = faiss.StandardGpuResources()
    335             index = faiss.index_cpu_to_gpu(faiss_index.faiss_res, faiss_index.device, index)
    336         faiss_index.faiss_index = index
```

AttributeError: module 'faiss' has no attribute 'StandardGpuResources'`

**Comment by mdouze** [comment]
Are you sure you installed gpu faiss and not cpu faiss?

**Comment by AndreGodinho7** [comment]
Thank you, Matthijs. I have some updates.

[FAISS installation](https://github.com/facebookresearch/faiss/blob/master/INSTALL.md) (1)

1) Not having faiss-cpu, just having faiss-gpu. Installed it by:
`        conda install faiss-gpu cudatoolkit=10.2 -c pytorch`

According to (1), it should be cudatoolkit=10.0, but that leads to downgrades that can lead to future problems. 

 throws 
`AssertionError: You must install Faiss to use FaissIndex. To do so you can run pip install faiss-cpu or pip install faiss-gpu`

2) Not having faiss-cpu, just having faiss-gpu. Installed it by

`pip install faiss-gpu`

Works. 

Cheers

**Comment by kqwang** [comment]
I find that there is not faiss-gpu for Window10, is it?

**Comment by romanvelichkin** [comment]
> I find that there is not faiss-gpu for Window10, is it?

https://anaconda.org/conda-forge/faiss-gpu - has win-64 version of faiss-gpu
