### ISSUE TITLE
Incorrect semantic expression in C++ examples on Binary Indexes Wiki page

### ISSUE THREAD

**Issue by MichaelMai2000** [facebookresearch/faiss#1441]
# Summary

On https://github.com/facebookresearch/faiss/wiki/Binary-indexes, all
```
// Querying the index
index.search(queries.size(), queries.data(), k, distances.data(), labels.data());
```
should be replaced by
```
// Querying the index
index.search(n, queries.data(), k, distances.data(), labels.data());
```

Where n is the number of queries (which also hasn't been clarified on the wiki page), rather than queries.size(), which actually equals to n*d/8.

https://github.com/facebookresearch/faiss/blob/6918f4ee48b0f2f72635a04e20661cc0b87e1b10/faiss/IndexBinaryFlat.cpp#L34-L38

**Comment by mdouze** [comment]
yes absolutely, thanks for flagging.

**Comment by MichaelMai2000** [comment]
Issue solved, cheers!
