### ISSUE TITLE
The size of each vector in IndexIVFFlat

### ISSUE THREAD

**Issue by naaktslaktauge** [facebookresearch/faiss#1446]
According to [this wiki page](https://github.com/facebookresearch/faiss/wiki/Faiss-indexes), the size of a vector in IndexIVFFlat is **4d** (bytes/vector, and d indicates the dimensionality).
However, I think it would be **4d+4** because each vector should have additional information about which cluster (cell) it belongs to.
In fact, the wiki says that IndexIVFPQ has M+4 (or M+8) bytes/vector, and this 4 (or 8) probably means the additional information about cells.
Is this explanation right?
Thank you.

**Comment by mdouze** [comment]
It is the other way round: the additional 8 bytes (64 bits id) corresponds to the vector id. The cluster contents are stored in contiguous arrays so the cluster id does not need to be stored.

**Comment by naaktslaktauge** [comment]
Thank you for the answer.
As far as I understand, 8 of M+8 in IVFPQ indicates the vector ID.
Then, Why are the additional 8 bytes unnecessary in IndexIVFFlat? 
If the cluster contents are stored in contiguous arrays as well as IndexIVFPQ, the IVFFlat case also needs vector id, doesn't it?

**Comment by mdouze** [comment]
Right, the sizes from that table are not accurate. Will do a pass to fix them.

**Comment by mdouze** [comment]
fixed.
