### ISSUE TITLE
FAISS Index I/O bound

### ISSUE THREAD

**Issue by AndreGodinho7** [facebookresearch/faiss#1447]
# Summary

Hello everyone, 
I am using [Hugging face datasets](https://huggingface.co/docs/datasets/add_dataset.html?highlight=pop) and [adding a FAISS index](https://huggingface.co/docs/datasets/faiss_and_ea.html) for indexing ~8.8M documents of MSMARCO dataset.

I am trying to retrieve the top-1000 passages for several queries of MSMARCO by using `get_nearest_examples()` (line 610 of [datasets/search.py](https://github.com/huggingface/datasets/blob/master/src/datasets/search.py)) from Hugging face datasets, which uses faiss python API (`faiss.index_factory()`, and other methods). 

# Platform

OS: Ubuntu 18.04.5
Faiss version: 1.6.3

Running on:
[x] CPU
[ ] GPU

Interface: 
[ ] C++
[x] Python

# Reproduction instructions

I came to realize that something was not making much sense. FAISS is a library for efficient similarity search and clustering of dense vectors. Thus, I would expect that getting the top-k nearest examples would not be a *"very long task"*. Therefore, I have done some tests on running `get_nearest_examples()` with a FAISS index over two different queries (4000 and 4001) several times **on the CPU**.

**1) 1st attempt query 4000 - Retrieve top-1000 passages for query 4000 (wall time = 9min 17s ; CPU time = 10.8s)**

```
%%time
scores, retrieved_documents = docs.get_nearest_examples('embeddings',
                                                        np.array(questions_dataset[4000]['embeddings'], dtype=np.float32), 
                                                        k=1000)
```

**CPU times**: user 10.8 s, sys: 469 ms, **total: 11.2 s**
**Wall time: 9min 17s**

**2) 2nd attempt query 4000 - Retrieve top-1000 passages for query 4000 (wall time = 8.97s ; CPU time = 8.97s)**

```
%%time
scores, retrieved_documents = docs.get_nearest_examples('embeddings',
                                                        np.array(questions_dataset[4000]['embeddings'], dtype=np.float32), 
                                                        k=1000)
```

**CPU times**: user 8.97 s, sys: 0 ns, **total: 8.97 s**
**Wall time: 8.97 s**

**3) 1st attempt query 4001 - Retrieve top-1000 passages for query 4001 (wall time = 10min 10s ; CPU time = 11.3s)**

```
%%time
scores, retrieved_documents = docs.get_nearest_examples('embeddings',
                                                        np.array(questions_dataset[4001]['embeddings'], dtype=np.float32), 
                                                        k=1000)
```

**CPU times**: user 11.3 s, sys: 148 ms, **total: 11.4 s**
**Wall time: 10min 10s**

**4) 3rd attempt query 4000 - Retrieve top-1000 passages for query 4000 (wall time = 9.03s ; CPU time = 9.03s)**

```
%%time
scores, retrieved_documents = docs.get_nearest_examples('embeddings',
                                                        np.array(questions_dataset[4000]['embeddings'], dtype=np.float32), 
                                                        k=1000)
```

**CPU times:** user 9.03 s, sys: 0 ns, **total: 9.03 s**
**Wall time: 9.03 s**

**5) 2nd attempt query 4001 - Retrieve top-1000 passages for query 4001 (wall time = 8.95s ; CPU time = 8.95s)**

```
%%time
scores, retrieved_documents = docs.get_nearest_examples('embeddings',
                                                        np.array(questions_dataset[4001]['embeddings'], dtype=np.float32), 
                                                        k=1000)
```

**CPU times:** user 8.95 s, sys: 0 ns, **total: 8.95 s**
**Wall time: 8.95 s**

As you can observe, the first time I try to retrieve the top-1000 passages for both queries 4000 and 4001 the wall time is ~9-10min. After that, the wall time matches the CPU time, which seems to indicate that `get_nearest_examples()` is I/O bounded and uses efficient caching.

**Should I be expecting faster retrievals on the first attempt?** All the CPU times *"were short"*, which makes sense since FAISS is a library for efficient similarity search and clustering of dense vectors. **Is there any workaround to achieve faster retrievals on such a collection with ~8.8M documents?**

**Comment by wickedfoo** [comment]
We did not write the huggingface library so I don't know what they are doing for I/O, or if you happen to be downloading this data off the internet in the background. This question is probably best asked of them in their repo.

If they are using `IndexFlat`, which is brute-force search for k-nearest neighbor (e.g., for each query, for each vector in the dataset, compute distance and find top-k), then this could be slow. 

https://github.com/huggingface/datasets/blob/master/src/datasets/search.py#L243

There are many tradeoff choices for a Faiss index, depending upon whether you need exact or approximate answers, your sensitivity to accuracy, memory usage, time, etc.

https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index
