### ISSUE TITLE
when compiling the newest version may occur some problems?

### ISSUE THREAD

**Issue by flxshujie** [facebookresearch/faiss#145]
FaissException.h:30:22: error: expected ‘;’ at end of member declaration
   const char* what() const noexcept override
                      ^
FaissException.h:30:28: error: ‘noexcept’ does not name a type
   const char* what() const noexcept override
                            ^
FaissException.h:32:20: error: expected ‘;’ at end of member declaration
   ~FaissException () noexcept override {}
                    ^
FaissException.h:32:22: error: ‘noexcept’ does not name a type
   ~FaissException () noexcept override {}
                      ^
FaissException.h:30:15: error: looser throw specifier for ‘virtual const char* faiss::FaissException::what() const’
   const char* what() const noexcept override
               ^
In file included from FaissException.h:14:0,
                 from FaissAssert.h:14,
                 from hamming.cpp:36:
/usr/include/c++/4.8/exception:68:25: error:   overriding ‘virtual const char* std::exception::what() const throw ()’
     virtual const char* what() const _GLIBCXX_USE_NOEXCEPT;
                         ^
In file included from FaissAssert.h:14:0,
                 from hamming.cpp:36:
FaissException.h:32:3: error: looser throw specifier for ‘virtual faiss::FaissException::~FaissException()’
   ~FaissException () noexcept override {}
   ^
In file included from FaissException.h:14:0,
                 from FaissAssert.h:14,
                 from hamming.cpp:36:
/usr/include/c++/4.8/exception:64:13: error:   overriding ‘virtual std::exception::~exception() throw ()’
     virtual ~exception() _GLIBCXX_USE_NOEXCEPT;
             ^
make: *** [hamming.o] Error 1

**Comment by mdouze** [comment]
Hi 

Faiss now requires a C++11 compiler. Please make sure you have the -std=c++11 flag on your g++ command line.

**Comment by mdouze** [comment]
Closing. Re-open if not fixed.
