### ISSUE TITLE
Can not compile on Mac

### ISSUE THREAD

**Issue by Hap-Hugh** [facebookresearch/faiss#1450]
# Summary

I git clone the latest Faiss version. But I try to follow the install.md to compile this source code. I can not run "./configure --with-python=/path/to/python3.7" in my terminal. Having no idea about that. And shall I use some old version of Faiss?

PS: My purpose is to do some experiments based on Faiss. Could I use Faiss in Python and modify the code in Py? Because modify the python code will be much easier.

# Platform

OS: macOS 10.15.6

Faiss version: latest version

Faiss compilation options: 

Running on:
- CPU

Interface: 
- C++

**Comment by mdouze** [comment]
Where did you find the ./configure command?
Please refer to the current INSTALL.md, which recommends to install via conda.
