### ISSUE TITLE
same datasize and index parameter,python demo has better performance than c++ demo?

### ISSUE THREAD

**Issue by chenqingguo** [facebookresearch/faiss#1454]
# Summary
I just change the datasize and dimension of 2-IVFFlat.cpp and 2-IVFFlat.py provided in tutorial. I found that the performance of python is much better than c++ in train and add processes, because demo(python) can use all cpus while c++ only use one cpu. 
I want c++ demo to use all cpus during train and add.

# Platform

OS:  centos 7.6 using docker

Faiss version:  release 1.6.3

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [x] Python

# Reproduction instructions
Here is the details. database size is 1000000 ,nlist=2048,d=512, and I have 32 processors. Python cost just one minute but C++ cost more than one hour during train and add. It looks like c++ doesn't use openMP.
I build c++ from resource and install python interface by anaconda. I don't limit docker‘s resource.

**Comment by mdouze** [comment]
There are two things to check: 
1. does your C++ compile support openmp?
2. did you compile with the MKL blas implementation (as opposed to the slow system BLAS)? 

I just realized MKL is not documented in INSTALL.md. You have to add the flags 

```
-DBLA_VENDOR=Intel10_64_dyn -DMKL_LIBRARIES=/path/to/mkl/libs
```

To the compiler flags.

**Comment by chenqingguo** [comment]
well, my compile is gcc 4.8.5. I add a test under tutorial/cpp using the same Makefile
here is test:
```
void main()
{
#pragma omp parallel
    std::cout<<"parallel run "<<std::endl;
}
```
I got 32 prints,so openmp works.

I don't compile with MKL, here is a part of dependence of my libfaiss.so
```
libblas.so.3
liblapack.so.6
libm.so.6
libgomp.so.1
libgcc_s.so.1
libpthread.so.0
libc.so.6
```
If python use MKL，It looks like using MKL is 90+ times faster than BLAS under my data and index parameter conditions.
Is the performance gap between BLAS and MKL so big?

**Comment by chenqingguo** [comment]
Hi, @mdouze
The reason is MKL. The time-consuming is similar to python after compile with the MKL.
MKL should be mentioned in INSTALL.md.That is very important.
Thanks.

**Comment by mdouze** [comment]
ongoing work in https://github.com/facebookresearch/faiss/pull/1456

**Comment by mdouze** [comment]
The install doc is updated
