### ISSUE TITLE
V1.6.3 compilation failed on macOS.

### ISSUE THREAD

**Issue by gyd2019** [facebookresearch/faiss#1457]
os:  macOS 10.14
llvm: llvm@10
`./configure --without-cuda`   and    `make`

The compiler error message is as follows:

```
g++ -std=c++11 -DFINTEGER=int    -I. -fPIC -m64 -Wno-sign-compare -g -O3 -Wall -Wextra -mpopcnt -msse4 -c Clustering.cpp -o Clustering.o
Clustering.cpp:38:5: error: member initializer 'decode_block_size' does
      not name a non-static data member or base class
    decode_block_size(32768)
    ^~~~~~~~~~~~~~~~~~~~~~~~
Clustering.cpp:81:18: error: out-of-line definition of 'train' does not
      match any declaration in 'faiss::Clustering'
void Clustering::train (idx_t nx, const float *x_in, Index & index,
                 ^~~~~
Clustering.cpp:83:5: error: use of undeclared identifier
      'train_encoded'
    train_encoded (nx, reinterpret_cast<const uint8_t *>(x_in)...
    ^
```

Hello, thank you very much faiss team.

**Comment by beauby** [comment]
Please see [INSTALL.md](https://github.com/facebookresearch/faiss/blob/master/INSTALL.md) for up to date instructions.

**Comment by gyd2019** [comment]
Hello, thank you very much for your reply.&nbsp;&nbsp;My project is currently compatible with FaISS V1.6.3.&nbsp; &nbsp;I want to use V1.6.3 on the MAC.&nbsp; But compile error.&nbsp; &nbsp;Faiss V1.6.4 compilation is available on MAC.&nbsp; &nbsp;Is there a solution to v1.6.3 compilation error?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/faiss"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月19日(星期一) 中午1:07
收件人:&nbsp;"facebookresearch/faiss"<faiss@noreply.github.com&gt;;
抄送:&nbsp;"1666066431"<1666066431@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [facebookresearch/faiss] V1.6.3 compilation failed on macOS. (#1457)





 
Please see INSTALL.md for up to date instructions.
