### ISSUE TITLE
How to get the datasets used in Link-and-Code

### ISSUE THREAD

**Issue by Hap-Hugh** [facebookresearch/faiss#1464]
I try to run the code of the bench named 'Link and Code'.

But I need the datasets used in this py code, like Deep1M, sift1M, bigann1B, deep1B.

Where can I get it? And do I need to do pre-processing work?

**Comment by crmuhsin** [comment]
for anyone like me
https://www.tensorflow.org/datasets/catalog/overview#nearest_neighbors
