### ISSUE TITLE
Documentation missing "full list of metrics"

### ISSUE THREAD

**Issue by mgavish** [facebookresearch/faiss#1470]
# Summary
[MetricType and distances](https://github.com/facebookresearch/faiss/wiki/MetricType-and-distances) page in documentation has outdated link to [full list of metrics](https://github.com/facebookresearch/faiss/blob/master/MetricType.h#L44)

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions
navigate to MetricType and distances page: https://github.com/facebookresearch/faiss/wiki/MetricType-and-distances and click on hyperlink "see here."

**Comment by mdouze** [comment]
Thanks for flagging. We moved the main source to a subdirectory and this caused a series of dangling links.
