### ISSUE TITLE
Question: Using `bf_knn` on multiple gpus 

### ISSUE THREAD

**Issue by joelsimonoff** [facebookresearch/faiss#1471]
# Summary

I'm having difficulties figuring out the best way to run `bf_knn` using multiple GPUs. I've been following the code example here: https://github.com/facebookresearch/faiss/blob/master/faiss/gpu/test/test_contrib.py on how to call `bf_knn`. However, the example doesn't cover multi GPU brute force KNN.

# Platform

Ubuntu 18.04
Installed via: `conda install faiss-gpu cudatoolkit=10.0 -c pytorch`

Running on:
- [ ] CPU
- [ X] GPU

Interface: 
- [ ] C++
- [C ] Python

# Reproduction instructions

This is how I've been running brute force KNN on a single GPU.

```
from faiss.contrib.exhaustive_search import knn_gpu

res = faiss.StandardGpuResources()
D, I = knn_gpu(res, xb, xq, k)
```

How can I modify this to run on multiple gpus? Is there something analogous to `faiss.index_cpu_to_all_gpus()` for `bf_knn`?

**Comment by mdouze** [comment]
Where does the data reside?

**Comment by joelsimonoff** [comment]
@mdouze The data is all stored in RAM.

**Comment by mdouze** [comment]
you could split by queries and run in several threads.

**Comment by wickedfoo** [comment]
The only thing the API offers at the moment is the ability to assign computation to a device.
I will add multi-GPU support to my list for future implementation.

An easier solution the time being might be just using a normal GpuIndexFlatL2 / GpuIndexFlatIP per GPU with an IndexShards (if the data you are querying against is huge) or IndexReplicas (if the data you are querying against can fit on a single GPU). Something like this (I did not test this out, just typing something along the lines of what I think should work):

```
index = faiss.IndexShards()
sub_indices = []
for device in range(num_gpus):
  config = faiss.GpuIndexFlatConfig()
  config.device = device
  sub_index = faiss.GpuIndexFlatL2(faiss.StandardGpuResources(), dims, config)
  sub_indices.append(sub_index)
  index.add_shard(sub_index)

index.add(xb)
res_d, res_i = index.search(xq, k)
```

(sub_indices I think is needed as it looks like the SWIG code doesn't add a reference to IndexShards, I'll look into that)

**Comment by joelsimonoff** [comment]
Thanks! I'll give that a try, and I'll also try splitting queries and running in separate processes on each GPU.

**Comment by wickedfoo** [comment]
@joelsimonoff the above code snippet will run the queries in different native C++ threads across multiple GPUs, but if that doesn't work, splitting queries across multiple processes/GPUs would work too, which is what IndexReplicas does in different threads. One can also split data, but that requires a join on the partial results, which IndexShards above handles automatically. I don't think the convenient merge functions for that are available in Python though.
