### ISSUE TITLE
What sort algorithm does GpuIndexIVFFlat search use to get the topk result?

### ISSUE THREAD

**Issue by lighteningzhang** [facebookresearch/faiss#1473]
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions
I found that In the L2Select.cu, in the function l2SelectMinK, the variable name of the sorted result of GPU is called heap, but use the data structure of heap may be costly in GPU. So I'd like to ask what the algorithm does faiss GPUIndexIVFFlat search uses to get the topk result?

the definition of the variable is as follows:
```c++
BlockSelect<T, int, false, Comparator<T>,
              NumWarpQ, NumThreadQ, ThreadsPerBlock>
    heap(initK, -1, smemK, smemV, k);
```

**Comment by wickedfoo** [comment]
the algorithm is described in section 4 of https://arxiv.org/pdf/1702.08734.pdf

It maintains a reservoir of values within the top-k which could be called a "heap", though it is not maintained using a classical heap algorithm.
