### ISSUE TITLE
Release 1.6.3 cost  much more time and more CPU than release 1.5.3 using IVFx,SQ8

### ISSUE THREAD

**Issue by zhangqiang4002** [facebookresearch/faiss#1487]
I test release 1.5.3 and release 1.6.3 with the same dataset and Index:
- Dataset: 1024 dimension, total 300000 vectors
- Index: IVF1000,SQ8
- Search 10000 times in 10 concurrent threads, nprobe=10, k=10

Release 1.6.3 version cost  much more time(70ms vs 40ms) and more CPU(almost double) than release 1.5.3 version, Why?

 **release 1.5.3 test result**  
2020/10/22 17:16:10 Load total 100000 search conditions
2020/10/22 17:16:52 Total:10000 search executed with success:10000, error:0, avg latency:40
2020/10/22 17:17:34 Total:20000 search executed with success:20000, error:0, avg latency:40
2020/10/22 17:18:16 Total:30000 search executed with success:30000, error:0, avg latency:40
2020/10/22 17:18:57 Total:40000 search executed with success:40000, error:0, avg latency:40
2020/10/22 17:19:39 Total:50000 search executed with success:50000, error:0, avg latency:40
2020/10/22 17:20:21 Total:60000 search executed with success:60000, error:0, avg latency:40
2020/10/22 17:21:03 Total:70000 search executed with success:70000, error:0, avg latency:40
2020/10/22 17:21:44 Total:80000 search executed with success:80000, error:0, avg latency:40
2020/10/22 17:22:26 Total:90000 search executed with success:90000, error:0, avg latency:40
2020/10/22 17:23:07 Total:100000 search executed with success:100000, error:0, avg latency:40
2020/10/22 17:23:07 Cost 6m56.990517025s to do total:100000 search executed with success:100000, error:0, avg latency:40
2020/10/22 17:23:07 [11-50] count:97036, latency:40, percent:0.9704
2020/10/22 17:23:07 [51-100] count:2964, latency:52, percent:0.0296
2020/10/22 17:23:07 latency status:map[average:40 max:95 min:32 p90:45 p99:53 p999:58]

**release 1.6.3 test result**
2020/10/22 17:32:56 Load total 100000 search conditions
2020/10/22 17:34:07 Total:10000 search executed with success:10000, error:0, avg latency:69
2020/10/22 17:35:18 Total:20000 search executed with success:20000, error:0, avg latency:70
2020/10/22 17:36:30 Total:30000 search executed with success:30000, error:0, avg latency:70
2020/10/22 17:37:41 Total:40000 search executed with success:40000, error:0, avg latency:70
2020/10/22 17:38:51 Total:50000 search executed with success:50000, error:0, avg latency:70
2020/10/22 17:40:02 Total:60000 search executed with success:60000, error:0, avg latency:69
2020/10/22 17:41:14 Total:70000 search executed with success:70000, error:0, avg latency:70
2020/10/22 17:42:25 Total:80000 search executed with success:80000, error:0, avg latency:70
2020/10/22 17:43:36 Total:90000 search executed with success:90000, error:0, avg latency:70
2020/10/22 17:44:47 Total:100000 search executed with success:100000, error:0, avg latency:70
2020/10/22 17:44:47 Cost 11m51.441050917s to do total:100000 search executed with success:100000, error:0, avg latency:70
2020/10/22 17:44:47 [11-50] count:34, latency:49, percent:0.0003
2020/10/22 17:44:47 [51-100] count:99430, latency:69, percent:0.9943
2020/10/22 17:44:47 [101-200] count:535, latency:107, percent:0.0054
2020/10/22 17:44:47 [201-500] count:1, latency:220, percent:0.0000
2020/10/22 17:44:47 latency status:map[average:70 max:220 min:45 p90:80 p99:97 p999:111]

OS:  Linux

Faiss version: release 1.5.3 Vs release 1.6.3

Installed from:  compiled by myself 

Faiss compilation options:  using MKL 

Running on: CPU

Interface:  C++

**Comment by mdouze** [comment]
It is likely because you did not enable AVX2 at compile time.

**Comment by zhangqiang4002** [comment]
> It is likely because you did not enable AVX2 at compile time.

compile 1.6.3 with CPUFLAGS  = -mavx2 -mf16c -msse4 -mpopcnt and the two versions work the same.
It’s strange that the two versions behave differently when exec ./configure --without-cuda

**Comment by mdouze** [comment]
AFAIK CPUFLAGS is not used.
