### ISSUE TITLE
benchmark for sift1m giving segmentation error

### ISSUE THREAD

**Issue by bluejay9676** [facebookresearch/faiss#149]
load data
load GT
============ Exact search
add vectors to index
warmup
benchmark
k=1 0.523 s, R@1 0.9914
k=2 0.510 s, R@1 0.9935
k=4 0.514 s, R@1 0.9935
k=8 0.514 s, R@1 0.9935
k=16 0.509 s, R@1 0.9935
k=32 0.510 s, R@1 0.9935
k=64 0.520 s, R@1 0.9935
k=128 0.526 s, R@1 0.9935
k=256 0.546 s, R@1 0.9935
k=512 0.594 s, R@1 0.9935
k=1024 0.840 s, R@1 0.9935
============ Approximate search
train
WARNING clustering 100000 points to 4096 centroids: please provide at least 159744 training points
add vectors to index
Segmentation fault (core dumped)

I am using Titan X just like the paper

**Comment by mdouze** [comment]
Closing. Submit a new issue if the crash occurs again.
