### ISSUE TITLE
Broken link in Wiki

### ISSUE THREAD

**Issue by jeongukjae** [facebookresearch/faiss#1490]
# Summary

In https://github.com/facebookresearch/faiss/wiki/Faiss-on-the-GPU#conversions section, a link( `gpu/GpuClonerOptions.h`) is not working.

It is a link to `https://github.com/facebookresearch/faiss/blob/master/gpu/GpuClonerOptions.h`, but it should be `https://github.com/facebookresearch/faiss/blob/master/faiss/gpu/GpuClonerOptions.h`.

**Comment by mdouze** [comment]
Thanks for flagging. We should do a full pass on the wiki to fix those links.
