### ISSUE TITLE
Interpret numpy index

### ISSUE THREAD

**Issue by WenqiJiang** [facebookresearch/faiss#1493]
# Summary

Dear Faiss Team, 

I am working on a research project in which I need to extract the PQ code, PQ codebook, and the cell centroid vectors from the Faiss index to numpy array. In the wiki directory as below, I learned that I can save the index as numpy array by "serialize_index". 

> https://github.com/facebookresearch/faiss/wiki/Index-IO,-cloning-and-hyper-parameter-tuning  

> https://github.com/matsui528/faiss_tips

After that, I loaded the saved numpy array and found it mixes everything together. How can I identify which part of the array stores which index (PQ code, codebook, etc.)? Any source code files I should read to understand the mechanism?

For example, I use IVF with 8192 cells and PQ 16. The PQ code size should be 16 byte * 1e9 = 16 GB, yet the index file (regardless numpy of Faiss original) are 24 GB, so I think it mixed many stuffs together. 

> python bench_polysemous_1bn.py SIFT1000M IVF8192,PQ16 nprobe=1 

![image](https://user-images.githubusercontent.com/42897680/97292788-fcedf880-184b-11eb-86a8-d28a6425b90a.png)

Running on:
- [ ] CPU

Interface: 
- [ ] Python

**Comment by wickedfoo** [comment]
You're not accounting for 8 bytes for the vector ID (a 64-bit integer), so you have 16 bytes for the PQ code + 8 bytes for the vector ID = 24 bytes per vector.
