### ISSUE TITLE
How to save kmeans index

### ISSUE THREAD

**Issue by QuentinSpalla** [facebookresearch/faiss#1494]
# Summary

I cannot save my kmeans index with the function write_index(). I got this error:
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-59-1625bd4bbdcc> in <module>
----> 1 faiss.write_index(kmeans, 'content/index/20201027_kmeans.obj')

/opt/conda/lib/python3.7/site-packages/faiss/swigfaiss.py in write_index(*args)
   5079 
   5080 def write_index(*args):
-> 5081     return _swigfaiss.write_index(*args)
   5082 
   5083 def write_index_binary(*args):

TypeError: Wrong number or type of arguments for overloaded function 'write_index'.
  Possible C/C++ prototypes are:
    faiss::write_index(faiss::Index const *,char const *)
    faiss::write_index(faiss::Index const *,FILE *)
    faiss::write_index(faiss::Index const *,faiss::IOWriter *)`

Can you tell me how can i save the kmeans index in order to reuse it later ? 

# Platform

OS: Debian9

Faiss version: faiss-gpu==1.6.4

Installed from: pip

Running on:
- CPU
- GPU

Interface: 
- [ ] C++
-  Python

# Reproduction instructions

**Comment by mdouze** [comment]
Kmeans is not an index. You can store the centroids instead.

**Comment by EdwardChan5000** [comment]
refer this can solve problem
https://github.com/facebookresearch/faiss/issues/2087
