### ISSUE TITLE
A quick question about IVF index with inner product metric

### ISSUE THREAD

**Issue by wenyun** [facebookresearch/faiss#1496]
# Summary

Looks like the IndexIVF.cpp implementation treat inner product metric slightly differently from L2 metric as follows
1. use max heap instead of min heap
2. use spherical centroid (normalized to length 1) in coarse quantization

My question is whether this is enough to let the n_probe clusters retrieve items with largest inner product values to the query vector? My understanding is that if all items have similar L2 norm, it is probably fine. But if, for example, some item embeddings are extremely large, they are more likely to have large inner product with query embeddings. Does FAISS consider this case?

**Comment by wickedfoo** [comment]
You are asking about the case of maximum inner product search (MIPS) I take it? 

MIPS is generally a task that is not yet well handled by the approximate k-NN algorithms available in Faiss and is still an active area of research, though we are working on possible extensions (e.g., https://papers.nips.cc/paper/7722-non-metric-similarity-graphs-for-maximum-inner-product-search.pdf or other related works). The METRIC_INNER_PRODUCT indices beyond IndexFlat (which can solve MIPS via brute-force if you don't normalize your vectors) are more geared towards cosine similarity (which is what gets produced with the normalization).

IVFFlat or similar implementations may or may not handle your task well, you could compare the quality of the approximate results against the ground truth. The partitioning of the database may also have nothing to do with the distribution of the query vectors (especially regarding their norms).

**Comment by wenyun** [comment]
@wickedfoo Thank you a lot for your good answers! It makes sense now. I have been wondering how the METRIC_INNER_PRODUCT works with IVF for a while. Now I know it actually does not.

**Comment by mdouze** [comment]
IVF with METRIC_INNER_PRODUCT **does** work. However, we recommend check the accuracy of the results because some data distributions are difficult to index (but this sometimes happens with L2 distance as well). 

*some item embeddings are extremely large, they are more likely to have large inner product with query embeddings*: if this is not intended then the input vectors should be modified.

**Comment by wenyun** [comment]
Thanks you for the great answers!
