### ISSUE TITLE
Indexing only bright pixels in an image?

### ISSUE THREAD

**Issue by zubair-ahmed-ai** [facebookresearch/faiss#1497]
# Platform

OS: Ubuntu 18

Faiss version: faiss-cpu-noavx2==1.6.3

Installed from: https://medium.com/@rom1504/image-embeddings-ed1b194d113e

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

I have images like these which Black pixels for introducing padding to keep the same dimensions

![Cam2_MD_1601525257150](https://user-images.githubusercontent.com/66907171/97531307-be844500-19d5-11eb-82fc-71c0acdad804.jpg)
![Cam2_MD_1601527304495](https://user-images.githubusercontent.com/66907171/97531314-c04e0880-19d5-11eb-81cd-411d257ae957.jpg)

My question is, can I somehow exclude the dark pixels and feed only the bright pixels for indexing and search?

**Comment by wickedfoo** [comment]
Image manipulation is outside the scope of the faiss library, sorry.
