### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by Firenze11** [facebookresearch/faiss#1498]
# Summary

https://github.com/facebookresearch/faiss#full-documentation-of-faiss
the link to  doxygen documentation is broken.

**Comment by mdouze** [comment]
We are working on moving the doxygen doc elsewhere. In the meantime you can generate it yourself and browse locally.

**Comment by mdouze** [comment]
Doxygen doc is now at https://facebookresearch.github.io/faiss/
