### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by TopGun666** [facebookresearch/faiss#1499]
# Summary

# Platform

OS:  Ubuntu 18.04.1

Faiss version:  faiss-gpu 1.6.4

Installed from:   pip

Faiss compilation options:  none

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

 

modified `demo_ondisk_ivf.py` dataset from `sift1M` to my own. My dataset array shape is (813208, 62). The other parameters are default.  The error is below

```python
    if stage == 0:
        # train the index
        xt = np.load('raw_data/feature.npy')
        print(xt.shape[1])
        index = faiss.index_factory(xt[:, :, 0].shape[1], "IMI2x9,Flat")
        # index = faiss.index_factory(xt[:, :, 0].shape[1], "IVF4096,Flat")
        print("training index")
        print(xt[:, :, 0].shape)
        index.train(xt[:, :, 0])
        print("write " + tmpdir + "trained.index")
        faiss.write_index(index, tmpdir + "trained.index")
```

![Screenshot from 2020-10-30 17-16-05](https://user-images.githubusercontent.com/23215825/97689691-edceab00-1ad6-11eb-8176-afa31a1ffb0d.png)

Run
```bash
python demo_ondisk_ivf.py 0
```

**Comment by mdouze** [comment]
As the message indicates, the array should be contiguous. You can make it contiguous by using

`np.ascontiguousarray(xt[:, :, 0])`

**Comment by TopGun666** [comment]
Got it. Thank you.
