### ISSUE TITLE
Clearing Cache

### ISSUE THREAD

**Issue by stefanjuang** [facebookresearch/faiss#1505]
Gooday all,

Is there a way to clear cache after a query? (Using on-disk faiss)
I noticed the ram usage started to buildup as repeated random queries are performed.

I would like it to clear cache whenever the program used up more than 90% of total ram.

Thank you.

- Stefan

**Comment by mdouze** [comment]
Cache control is a system-level functionality. Cache can be disabled with 
```
sync && sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches'
```

**Comment by stefanjuang** [comment]
Thank you!
