### ISSUE TITLE
Repeated result

### ISSUE THREAD

**Issue by stefanjuang** [facebookresearch/faiss#1507]
# Summary

Hello all,

I running the on-disk faiss.
The **result index list and distance list** are **correct**, but the list seems to contain **many repeated entries**.
i.e. The **ground truth** index in the example below is **"268871"**, with a **distance of 0**, but the **same index** is **repeated 18 times**.

The number of repeat does not seem to be constant. 
Usually in the range of 2 to 20

**Parameters:**
dimension of data = 1088
"IVF20536,Flat"
on disk merge bno = 20
nprobe = 64
top k = 64

### Result:
**Distance:**
<img width="515" alt="Screenshot 2020-11-05 at 2 58 48 PM" src="https://user-images.githubusercontent.com/33438238/98208133-bf8a1900-1f77-11eb-8fae-97c230372c13.png">

**Index:**
<img width="507" alt="Screenshot 2020-11-05 at 2 59 00 PM" src="https://user-images.githubusercontent.com/33438238/98208137-c31da000-1f77-11eb-9bb1-ac9021193ffb.png">

Can I change some parameters to get 64 unique indexes?

Appreciated,

-Stefan

# Platform

OS: 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7" 

Faiss version: 

Installed from:  
Installed with anaconda and compiled with cmake

Faiss compilation options: 

Running on:
- [y] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [y] Python

**Comment by mdouze** [comment]
Can you confirm you did not add a vector with the same id several times?

**Comment by stefanjuang** [comment]
Now you mentioned it, I suspect that might be the case.
The tmp directory is surprising large.

What is troubling to me is I still have the following lines from the on-disk demo:
print(xb[i0:i1].shape,np.arange(i0, i1).shape)
index.add_with_ids(xb[i0:i1], np.arange(i0, i1)) 

At the output, I only see each index range to be added once.

Will try to do more testing this week on my end.
