### ISSUE TITLE
how to use query server after add  feature vector index ?

### ISSUE THREAD

**Issue by vega110** [facebookresearch/faiss#151]
lsh = faiss.IndexLSH(d, n_bits)
lsh.add(xb_tmp)
I have finish to add feature vector index .
If I have added all my vectors, and then how to use only run lsh.search(q_tmp.astype('float32'), k) exclude lsh.add.

separate index server and search server.

**Comment by vega110** [comment]
@mdouze can u tell me?

**Comment by wickedfoo** [comment]
Sorry, what is your question? I don't understand.
What do you mean by "query server"?

**Comment by vega110** [comment]
After add index of image vectors in my function code by faiss  (lsh=faiss.IndexLSH(d, n_bits); lsh.add(xb_tmp)), how can I find the index of vectors.And how do I operate the specified store path. If I want to code search function in other codes(lsh = faiss.IndexLSH(d, n_bits); lsh.search(q_tmp.astype('float32'), k);) ,how query the  vector in memory?

**Comment by mdouze** [comment]
Please rephrase.
