### ISSUE TITLE
Install on Raspberry Pi

### ISSUE THREAD

**Issue by rose-jinyang** [facebookresearch/faiss#1512]
Hello
How are you?
Thanks for contributing this project.
I am going to use the Faiss on Raspberry Pi 32 bit & 64bit OS.
If the Faiss supports Raspbian OS, could u provide the commands to install on Raspberry Pi 32 bit & 64 bit OS?
Thanks

**Comment by Riut521** [comment]
do you have any idea how to install on raspberry Pi now? I searched in many ways but found little files in association, and i wants to install it on a orange pi (rk3399)

**Comment by mdouze** [comment]
We and others  verified that older versions of Faiss does work on ARM platforms, there are also a few NEON-optimized primitives. However, it is not supported by the build system.
The best way to install it is probably to compile it one C++ file at a time. Let us know how it goes!

**Comment by mdouze** [comment]
ARM is supported now. Checked on an AWS instance.
