### ISSUE TITLE
Decomposition for ADC distance

### ISSUE THREAD

**Issue by zhou0913meng** [facebookresearch/faiss#1514]
When computing the distance of ADC for IVFPQ, I can't verify the the term3 in the decomposition of distance expression. So, could anyone tell me where it is minused?

**Comment by mdouze** [comment]
I don't understand the question.

**Comment by zhou0913meng** [comment]
d = || x - y_C ||^2 + || y_R ||^2 + 2 * (y_C|y_R) - 2 * (x|y_R)
 *        ---------------   ---------------------------       -------
 *             term 1                 term 2                   term 3
term2 is precomputed, term1 is computed using coarse centroid in the first stage search. But I can't find where term3 is computed.

**Comment by mdouze** [comment]
See equation (11) of https://arxiv.org/pdf/1702.08734.pdf

**Comment by zhou0913meng** [comment]
Yes, I have seen the equation (11), but I can't find the computation of term 3 in the source code of C++. So could you tell me the part related to it's compution in the source file?

**Comment by mdouze** [comment]
Here: 

https://github.com/facebookresearch/faiss/blob/master/faiss/IndexIVFPQ.cpp#L617
