### ISSUE TITLE
How to convert one by one search to batch search

### ISSUE THREAD

**Issue by trantuantu** [facebookresearch/faiss#1515]
https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls
According to wiki, Faiss indexes will work in the best performance if we submit queries by batches. But in case of query come from client one by one, How to gather them into 1 batch and search to boost performance? Or we only can search one by one with multithreading in this case?

**Comment by wickedfoo** [comment]
You can hold up incoming serial requests by some short time and then process whatever batch you have at once.

This would likely require a multi-producer, single consumer queue (so the incoming request threads can post their queries) and a condition variable timer mechanism which will run the query batch if you have either accumulated enough queries or if your timeout time (say, 50 milliseconds or whatever) has been passed.

However, general multithreaded/multiprocess/asynchronous programming is beyond the scope of the Faiss library and we unfortunately can't help you with this implementation beyond telling you that we ourselves and others have used such tricks before in the past.

**Comment by trantuantu** [comment]
I see. Thank you for your comment.
