### ISSUE TITLE
Reduce memory allocated on GPU

### ISSUE THREAD

**Issue by zelcookie** [facebookresearch/faiss#1517]
# Summary

The code below allocated 464MiB of GPU memory. Is it possible reduce this value?

# Platform

OS: Ubuntu 18.04.3 LTS

Faiss version: 1.6.3

Installed from: pip

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

```
resources = faiss.StandardGpuResources()
resources.noTempMemory()
config = faiss.GpuIndexIVFFlatConfig()
index = faiss.GpuIndexIVFFlat(resources, 768, 16, faiss.METRIC_L2, config)
```

**Comment by wickedfoo** [comment]
Try `index.reclaimMemory()` after adding to it.

Otherwise, see your other issue about float16.

**Comment by zelcookie** [comment]
@wickedfoo Are there any negative consequences of using `index.reclaimMemory()`?
If not, why isn't this done by default?

**Comment by wickedfoo** [comment]
@zelcookie it makes incremental additions to the index slower, as the allocations are tailored exactly to the number of vectors that you have exactly in the index. By default the IVF lists function much the way as C++ `std::vector<T>` does, with amortized growth and a distinction between size and capacity.

If you only add to the index once via a single call to add(), then it makes sense to me to have the reclaimMemory behavior by default.
