### ISSUE TITLE
useFloat16 doesn't affect the size of the allocated GPU memory

### ISSUE THREAD

**Issue by zelcookie** [facebookresearch/faiss#1518]
# Summary

Why size of allocated GPU memory is the same with FP32 and FP16?

# Platform

OS: Ubuntu 18.04.3 LTS

Faiss version:  1.6.3

Installed from:  pip

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

```
import faiss
import numpy as np

def create_index(use_fp_16):
    np.random.seed(0)
    vectors = np.random.rand(1_000_000, 768).astype('float32')

    resources = faiss.StandardGpuResources()
    resources.setTempMemory(200*1024*1024)
    config = faiss.GpuIndexIVFFlatConfig()
    config.flatConfig.useFloat16 = use_fp_16
    index = faiss.GpuIndexIVFFlat(resources, 768, 16, faiss.METRIC_L2, config)
    index.nprobe = 4
    index.train(vectors)
    index.add(vectors)
    return index
```

```
index = create_index(False)
```
GPU: 4850MiB

```
index = create_index(True)
```
GPU: 4848MiB

**Comment by wickedfoo** [comment]
GpuIndexIVFFlatConfig.flatConfig are the configuration parameters for the coarse quantizer, which in this case is a matrix of size nlist * dim = 16 * 768. This in your configuration would save only an expected 16 * 768 * (sizeof(float) - sizeof(half)) = 24 KiB.

For float16 encoding, use GpuIndexIVFScalarQuantizer.
