### ISSUE TITLE
cuda error 77 in runBlockSelectPair_float_false_32_ when large data for brute search

### ISSUE THREAD

**Issue by monchin** [facebookresearch/faiss#1523]
# Summary

For a long time I have used faiss for brute search well. But recently I need to search large data, say, over 800k * 30. I got the error 
```
Faiss assertion 'err__ == cudaSuccess' failed in void faiss::gpu::runBlockSelectPair_float_false_32_(f
aiss::gpu::Tensor<float, 2, true>&, faiss::gpu::Tensor<int, 2, true>&, faiss::gpu::Tensor<float, 2, tr
ue>&, faiss::gpu::Tensor<int, 2, true>&, bool, int, cudaStream_t) at gpu/utils/blockselect/BlockSelect
Float32.cu:13; details: CUDA error 77 an illegal memory access was encountered
```
600k * 30 is ok, but 800k * 30 the error would occur. I tried to reduce the batch size for each turn to search to 50000, but it seems it didn't work, and the GPU memory was used only about 20%. 

So I'm wondering why this error occurs.

# Platform

OS: Ubuntu 16.04

Faiss version: 1.6.0

Installed from: anaconda

Running on:
-  GPU, 1080ti, cuda 10.0

Interface: 
-  Python 3.7.3

# Reproduction instructions
My code:
```python
def search(data, k):
    num, dimension = data.shape

    res = faiss.StandardGpuResources()
    cpu_index = faiss.IndexFlatL2(dimension)
    gpu_index = faiss.index_cpu_to_gpu(res, 0, cpu_index)

    batch_size = 50000
    batch_starts = np.arange(0, num, batch_size)

    gpu_index.add(data)
    
    d_list, i_list = [], []
    for i, each in enumerate(batch_starts):
        print("round", i)
        if i!=batch_starts.shape[0]-1:
            D, I = gpu_index.search(data[each:each+batch_size], k)
        else:
            D, I = gpu_index.search(data[each:num], k)
        d_list.append(D)
        i_list.append(I)
    
    d = np.vstack(d_list)
    d = np.sqrt(d)
    idx = np.vstack(i_list)
    return d, idx
```
In fact, I print "round i" for each round, and found that if the data is 5M * 30, the error would occur on round 1(the second round). If the data is 800k * 30, the error would occur  on round 13. If 600k * 30, no error occurs.

**Comment by wickedfoo** [comment]
I will investigate this, I have an idea what the error could be.

**Comment by monchin** [comment]
> I will investigate this, I have an idea what the error could be.

@wickedfoo  Thank you and hope for your good news!  Here's some new information I got.
I tried to use batch search, as code below:
```python
def search(data, k):
    num, dimension = data.shape

    res = faiss.StandardGpuResources()
    cpu_index = faiss.IndexFlatL2(dimension)
    gpu_index = faiss.index_cpu_to_gpu(res, 0, cpu_index)

    batch_size = 50000
    batch_starts = np.arange(0, num, batch_size)
    batch_starts_cp = batch_starts.copy()

    starts_num = batch_starts.shape[0]
    d_list, i_list = [], []
    for i, each_idx in enumerate(batch_starts):
        print('round', i)
        d_batch_list, i_batch_list = [], []
        if i != starts_num - 1:
            data_i = data[each_idx:each_idx+batch_size]
            num_batch = batch_size
        else:
            data_i = data[each_idx:num]
            num_batch = num - each_idx

        for j, each_search in enumerate(batch_starts_cp):
            print("round",i,'subround',j)
            if j != starts_num - 1:
                data_j = data[each_search:each_search+batch_size]
            else:
                data_j = data[each_search:num]

            gpu_index.add(data_j)
            D, I = gpu_index.search(data_i, k)
            d_batch_list.append(D)
            i_batch_list.append(I + each_search)
            gpu_index.reset()

        
        d_sub = np.hstack(d_batch_list)
        i_sub = np.hstack(i_batch_list)
        row_i = np.arange(num_batch).repeat(k).reshape(num_batch, k)

        idx_sub = np.argsort(d_sub, axis=1)[:, :k]
        d_sub = d_sub[row_i, idx_sub]
        i_sub = i_sub[row_i, idx_sub]
        
        d_list.append(d_sub)
        i_list.append(i_sub)
    
    d = np.vstack(d_list)
    d = np.sqrt(d)
    idx = np.vstack(i_list)
    return d, idx
```
But the same error still occurred when data is large and no error when data is small

**Comment by wickedfoo** [comment]
So I tried your code on a 5M x 30 tensor with k=10, and it seems to work for me (though I am using CUDA 10.1, and V100 GPUs with 16 GiB of memory). What k value are you using?

I presume your 1080Ti is being used as a video card as well? How much free memory does it have on it before running your script?

If you want all-to-all k-nearest neighbor on the 5M x 30, you can also use the `knn_gpu` function, like:

```
data = ... # your 5M x 30 array or whatever
res = faiss.StandardGpuResources()
d, i = faiss.knn_gpu(res, data, data, k)
```

This will take a while before producing the full results (of size 5M x k) and unfortunately won't print out anything while doing so (I should add a verbose mode), but will be a lot faster.

**Comment by monchin** [comment]
> So I tried your code on a 5M x 30 tensor with k=10, and it seems to work for me (though I am using CUDA 10.1, and V100 GPUs with 16 GiB of memory). What k value are you using?
> 
> I presume your 1080Ti is being used as a video card as well? How much free memory does it have on it before running your script?
> 
> If you want all-to-all k-nearest neighbor on the 5M x 30, you can also use the `knn_gpu` function, like:
> 
> ```
> data = ... # your 5M x 30 array or whatever
> res = faiss.StandardGpuResources()
> d, i = faiss.knn_gpu(res, data, data, k)
> ```
> 
> This will take a while before producing the full results (of size 5M x k) and unfortunately won't print out anything while doing so (I should add a verbose mode), but will be a lot faster.

It may because of the cards, or the version of cuda. My card is not a video card, it's on server and empty, and as batch size was small, 800k*30 the highest GPU mem usage was 20%, but error still occurred. I tried the code on a 2080ti card on another server, and everything worked well. 
I used k=30 before, but tried k=10, and nothing changed.
Although it's still strange, I can report how to solve it (changing a better card). Anyway thank you for your kind help!
