### ISSUE TITLE
Cuda architecture 8.6 support

### ISSUE THREAD

**Issue by pololanik** [facebookresearch/faiss#1524]
# Summary
Hi, I tried to build Faiss for Cuda architecture 8.6, but it failed.

`#error Unknown __CUDA_ARCH__; please define parameters for compute capability`

Version 8.0 works. 

Am I doing something wrong?

**nvcc --version**
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0

# Platform

OS: Ubuntu 18.04 (docker nvcr.io/nvidia/tensorrt:20.10-py3)

Faiss version: 1.6.4

Installed from:  

Faiss compilation options: -DCMAKE_CUDA_ARCHITECTURES="86"

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python 

# Reproduction instructions

git clone https://github.com/facebookresearch/faiss && \
	cd faiss && \
	cmake -B build . -DCMAKE_CUDA_ARCHITECTURES="86"  && \
	make -C build && \
	cd build/faiss/python && python3 setup.py install 

 

`In file included from /opt/faiss/faiss/gpu/impl/GeneralDistance.cuh:14:0,
                 from /opt/faiss/faiss/gpu/impl/Distance.cuh:13,
                 from /opt/faiss/faiss/gpu/GpuDistance.cu:12:
/opt/faiss/faiss/gpu/utils/DeviceDefs.cuh:24:2: error: #error Unknown __CUDA_ARCH__; please define parameters for compute capability
 #error Unknown __CUDA_ARCH__; please define parameters for compute capability
  ^~~~~
make[2]: *** [faiss/CMakeFiles/faiss.dir/gpu/GpuDistance.cu.o] Error 1
faiss/CMakeFiles/faiss.dir/build.make:783: recipe for target 'faiss/CMakeFiles/faiss.dir/gpu/GpuDistance.cu.o' failed
make[2]: Leaving directory '/opt/faiss/build'
CMakeFiles/Makefile2:206: recipe for target 'faiss/CMakeFiles/faiss.dir/all' failed
make[1]: Leaving directory '/opt/faiss/build'
make[1]: *** [faiss/CMakeFiles/faiss.dir/all] Error 2`

**Comment by wickedfoo** [comment]
There is no such compute capability as 8.6, they only go up to 8.0 at
present, see link below (Ampere-class architecture such as the A100). What
are you trying to do?

https://developer.nvidia.com/cuda-gpus

**Comment by beauby** [comment]
@wickedfoo The latest RTX 30xx have compute capability 8.6 according to nvidia

**Comment by sonovice** [comment]
https://github.com/facebookresearch/faiss/issues/1295#issuecomment-744427388 This helped me getting faiss to work on an RTX 3090

**Comment by h-vetinari** [comment]
conda-forge builds packages for `compute_86` (on cuda >=11.1) since https://github.com/conda-forge/faiss-split-feedstock/pull/31.

Since https://github.com/facebookresearch/faiss/commit/f15ce621f32cdc470086bcd46b5983a6b14311e2 (not released yet), the guard that caused the error in the OP is gone as well.

**Comment by phanxuanduc1996** [comment]
I used Anaconda, I installed bellow, it worked. If you use Docker, please install Miniconda.
`conda install faiss-gpu cudatoolkit=11.1 -c pytorch-gpu`
`conda install -c anaconda pytorch-gpu`

**Comment by hongyuanmei** [comment]
> I used Anaconda, I installed bellow, it worked. If you use Docker, please install Miniconda. `conda install faiss-gpu cudatoolkit=11.1 -c pytorch-gpu` `conda install -c anaconda pytorch-gpu`

@phanxuanduc1996 Hi! Thanks for suggestions. I tried it but it said pytorch-gpu is not a valid channel anymore... 
Do you have any other way to get this solved?

**Comment by h-vetinari** [comment]
@hongyuanmei 
Have you tried
```
conda install -c conda-forge faiss-gpu
```
?

PS. the `-c pytorch-gpu` is surely a typo, because no such channel ever existed. Either it might be `-c pytorch` (using pytorch channel) or `pytorch-gpu` (installing pytorch-gpu in addition to faiss etc.)

**Comment by hongyuanmei** [comment]
@h-vetinari Thank you! 
Yeah, I did, and it worked. I am now happily using it. :-) 
Thanks again.
