### ISSUE TITLE
Can I calculate Chebyshev distance in IVFPQ？

### ISSUE THREAD

**Issue by Law0825** [facebookresearch/faiss#1526]
# Summary
I know that  METRIC_Linf(Chebyshev distance) is only supported by IndexFlat.
but I think it's the same as METRIC_L2 ,becouse they are both special case of METRIC_Lp.

so I wanna know it is possible to  modified PQ's code for supporting Chebyshev distance or other METRIC_Lp？

**Comment by mdouze** [comment]
It's METRIC_Linf
Programatically, PQ could compute alternative distances (like Linf) at distance compuation time, bit the training with k-means assumes that the final distance will be L2, so the approximation will not be as good in terms of distance distortion.

**Comment by Law0825** [comment]
> It's METRIC_Linf
> Programatically, PQ could compute alternative distances (like Linf) at distance compuation time, bit the training with k-means assumes that the final distance will be L2, so the approximation will not be as good in terms of distance distortion.

so can I use K-medoids or PAM to replace k-means？

**Comment by mdouze** [comment]
yes but it's not implemented in Faiss.
