### ISSUE TITLE
question about Ondisk IVF

### ISSUE THREAD

**Issue by tangzhy** [facebookresearch/faiss#1528]
As is shown in https://github.com/facebookresearch/faiss/blob/master/demos/demo_ondisk_ivf.py, we divide the data into 4 parts and add them into the index sequentially.

1. Why do we divide the data into different parts? Is that necessary? If so, how many parts are appropriate for various data size? 

2. What would happen if we directly add the data to the index, and use `merge_ondisk` function, which in my view turns the index capable to search on disk. 

3. My data shape is around (80M, 32), and my choice of number of blocks is 128, where the flat IVFIP index gives 1-recall@1024=0.55 on my test data. Then I try to merge ondisk sub-block index in several different ways:
    a. merge only the head 2 files into a populated index and the result is quite good, 1-recall@1024=0.22.
    b. merge the head 10 files into a populated index  and the result is quite good, 1-recall@1024=0.20.
    It seems confusing that the ondisk index performs worse, which causes my concern. Does that meet our expectation?

**Comment by mdouze** [comment]
1. the number of parts is constrained by the available RAM

2. it would be very slow (and we will drop support for merge on disk at some point)

3. This is not normal. The ondisk search should give the exact same results as in-RAM.

**Comment by jeremyephron** [comment]
Hi @mdouze, when you say, "we will drop support for merge on disk at some point", what do you suggest as a better alternative to the on-disk search if the index cannot fit in RAM?

**Comment by mdouze** [comment]
Sorry my mistake, I meant "we will drop support for **add** on disk at some point". 
Merge will become the only way to build an on-disk index.

**Comment by saurabhkumar** [comment]
Hi, I create the initial index (large dataset) and then save it to disk. Afterwards, i load this index to support search. In parallel new data has to be added (in batches, every few minutes). What would be the recommended way to do this?

**Comment by mdouze** [comment]
You may be interested in this incremental index approach: 

https://speakerdeck.com/kumon/cvpr-2020-tutorial-a-large-scale-visual-search-system-in-the-c2c-marketplace-app-mercari?slide=24
