### ISSUE TITLE
About Faiss ID mapping

### ISSUE THREAD

**Issue by mrcsunshine** [facebookresearch/faiss#153]
Hi,
  I want to assign 64-bit vector ids to the vectors I added with add_with_ids. But I got an error when adding it. The codes and error are as follow:

index = faiss.IndexFlatIP(d)
np.array(idlist).astype('int')
index.add_with_ids(features,idlist)  ##the dtype of idlist is int64

RuntimeError: Error in virtual void faiss::Index::add_with_ids(faiss::Index::idx_t, const float*, const long int*) at Index.cpp:33: add_with_ids not implemented for this type of index
    
And the codes on the tutorial page are not work neither:
ids=np.arange(features.shape[0])
index2=faiss.IndexIDMap(index)
index2.add_with_ids(features,ids)

**Comment by mdouze** [comment]
Hi 
The first error is normal. 
Could you report what the error is for the second call?

**Comment by mrcsunshine** [comment]
With the same code above, run it for the second time, I still get the error:

RuntimeError: Error in virtual void faiss::Index::add_with_ids(faiss::Index::idx_t, const float*, const long int*) at Index.cpp:33: add_with_ids not implemented for this type of index

**Comment by mrcsunshine** [comment]
The problem solved.     Thx.

This one works:
index2=faiss.IndexIDMap(index)
 index2.add_with_ids(features,idlist)
