### ISSUE TITLE
write_index_binary for IndexBinaryMultiHash fails (segmentation fault) for more than 570 million hash codes.

### ISSUE THREAD

**Issue by casperhansen** [facebookresearch/faiss#1532]
# Summary

I am having problems using `faiss.write_index_binary` on an `IndexBinaryMultiHash` index. Independent of the hash code length (e.g., 8, 16, or 32 bits) it throws a segmentation fault when the number of hash codes is above 570 million (570 million works, but 580 million does not). I do not experience problems when using `IndexBinaryHash` instead of `IndexBinaryMultiHash`, even for billions of hash codes.

Is there supposed to be this limitation of around 570 million hash codes for `IndexBinaryMultiHash` when writing the index?

# Platform

OS: Ubuntu 18.04.5 LTS (128GB RAM)

Faiss version: 1.6.3

Installed from: anaconda 

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

The following code reproduces the error. If the number of hash codes (if `num_million` is set to 570 it works fine). If the number of hash codes is below 570 million, then increasing both dim (e.g., to 32) and nhash (e.g., to 4) still works as well (i.e., does not throw a segmentation fault).

```
import faiss
import numpy as np

dim = 8
nhash = 1
num_million = 580 # changing to 570 works
index1 = faiss.IndexBinaryMultiHash(dim, nhash, int(dim/nhash))
random_hash_codes = np.random.randint(0, 256, (num_million * int(1e6), int(dim/8))).astype("uint8")
index1.add(random_hash_codes)
faiss.write_index_binary(index1, "tmp.faiss")
```

It produces this error: `Segmentation fault (core dumped)`.

**Comment by mdouze** [comment]
Might be a 64-bit cleanness issue. I will investigate.

**Comment by mdouze** [comment]
I can repro, marking as bug.

**Comment by mdouze** [comment]
Fixed.
