### ISSUE TITLE
Kmeans API broken.

### ISSUE THREAD

**Issue by deepLearnerAnil** [facebookresearch/faiss#1533]
# Summary

# Platform

OS: Ubuntu 20.04.1 LTS (Focal Fossa)

Faiss version: 1.6.4
Python version: 3.6.12
Installed from: pip 

Faiss compilation options: 

Running on:
- [+ ] CPU

Interface: 
- [ +] Python

# Reproduction instructions

`import faiss`  
`ncentroids = 10`
`niter = 50`
`verbose = True`
`d = 128`
`n= 10000`
`km = faiss.Kmeans(d, ncentroids)`
`km.niter = niter`
`km.train(vecs)`_

The same code was working a few days back and I've upgraded my OS from 18.04 to 20.04.
And I'm getting the following error:

`TypeError                                 Traceback (most recent call last)
<ipython-input-18-c194a7a3120f> in <module>
     10 km = faiss.Kmeans(d, ncentroids)
     11 km.niter = niter
---> 12 km.train(vecs)

~/anaconda3/envs/tf-gpu2/lib/python3.6/site-packages/faiss/__init__.py in train(self, x, weights, init_centroids)
    775                 ngpu = self.gpu
    776             self.index = index_cpu_to_all_gpus(self.index, ngpu=ngpu)
--> 777         clus.train(x, self.index, weights)
    778         centroids = vector_float_to_array(clus.centroids)
    779         self.centroids = centroids.reshape(self.k, d)

~/anaconda3/envs/tf-gpu2/lib/python3.6/site-packages/faiss/__init__.py in replacement_train(self, x, index, weights)
     50             self.train_c(n, swig_ptr(x), index, swig_ptr(weights))
     51         else:
---> 52             self.train_c(n, swig_ptr(x), index)
     53     def replacement_train_encoded(self, x, codec, index, weights=None):
     54         n, d = x.shape

~/anaconda3/envs/tf-gpu2/lib/python3.6/site-packages/faiss/swigfaiss.py in train(self, n, x, index, x_weights)
   1155 real_to_binary = _swigfaiss.real_to_binary
   1156 
-> 1157 def hash_bytes(bytes, n):
   1158     return _swigfaiss.hash_bytes(bytes, n)
   1159 hash_bytes = _swigfaiss.hash_bytes

TypeError: Wrong number or type of arguments for overloaded function 'Clustering_train'.
  Possible C/C++ prototypes are:
    faiss::Clustering::train(faiss::Clustering::idx_t,float const *,faiss::Index &,float const *)
    faiss::Clustering::train(faiss::Clustering::idx_t,float const *,faiss::Index  @&)`

@beauby is the API broken or am I doing something wrong?

**Comment by Enet4** [comment]
Can you double check the declaration of the variable `vecs`? It _must_ be a float32 numpy array.

**Comment by deepLearnerAnil** [comment]
> Can you double check the declaration of the variable `vecs`? It _must_ be a float32 numpy array.

@Enet4 Thanks for your time. It really helped.
