### ISSUE TITLE
Is there any way of knowing how many samples were used at training time?

### ISSUE THREAD

**Issue by rinze** [facebookresearch/faiss#1535]
Hi,

I'm trying to find a way to estimate how many training samples were used. My current solution is to obtain the nlist from the index object; then, knowing that `nlist` is a function of the size of the dataset, estimate that; and then with `nlist` and the estimated size of the original dataset, I can estimate how many training points were used.

The entire thing is a bit convoluted, but it works, so no complains here. However, I'm wondering if there is any more direct way, any field in the index object I could be accessing that makes the entire thing easier.

Thanks for your help.

**Comment by wickedfoo** [comment]
No, you'd have to capture this information at the time of the train() call.

Though, all of the vectors passed to train() are not necessarily used. Typically for, say, the IVF coarse quantizer, if a flat index is used, ideally between 39 and 256 vectors are passed to train for each nlist. Passing fewer than this will print an error, and passing more than this will result in a random sub-sample of 256 * nlist vectors used from the trin set.

https://github.com/facebookresearch/faiss/blob/master/faiss/Clustering.cpp#L36

Other possible components of an index like product and scalar quantizers have their own training mechanisms, though I believe that PQ also uses the same clustering code above.

**Comment by rinze** [comment]
Ok, thanks for your response. I'll keep doing what I'm doing now then, for what I want to do is good enough.
