### ISSUE TITLE
Faiss-GPU version with latest Faiss index interoperability 

### ISSUE THREAD

**Issue by shipra25jain** [facebookresearch/faiss#1536]
Hi,
Can I install latest version of faiss-gpu which has improved pytorch-faiss interoperability using index using conda?  with conda install command for cuda 10.0, I am getting faiss-gpu 1.6.3 version. How can I install the latest 1.6.5 version?

Thanks!

**Comment by wickedfoo** [comment]
The updated package is currently building and should hopefully be pushed soon.

**Comment by shipra25jain** [comment]
okay. Any tentative date by when I can expect to be pushed to the conda channel? 
Thanks

**Comment by beauby** [comment]
The 1.6.5 packages are available on conda, for CUDA 10.1 and 10.2.
