### ISSUE TITLE
Is IMI a good index for GPU?

### ISSUE THREAD

**Issue by WenqiJiang** [facebookresearch/faiss#1539]
# Summary

Hi, 

I have noticed that IMI is not implemented in the GPU Faiss. I am trying to guess the reason, is that because IMI's memory access pattern does not favor GPUs? Since IMI partitioned the vector set in a very fine-grained manner, it can lead to many small random memory accesses during the searching process, which is not friendly to GPU because these accesses may lead to bank conflicts on GPU global memory (unbalanced workload on each bank). I am just curious if this guess is correct.

Thanks

**Comment by mdouze** [comment]
Yes it is. Moreover, on the GPU it is more feasible to use expensive exhaustive search for the coarse quantizer.

**Comment by WenqiJiang** [comment]
Thanks, great to hear that!
