### ISSUE TITLE
About train

### ISSUE THREAD

**Issue by vega110** [facebookresearch/faiss#154]
d = 1568
	nlist = 100
	quantizer = faiss.IndexFlatL2(d)   # build the index
	index = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_L2)

	txt_url = "/creative_400.txt"
	f = open(txt_url) 
	line = f.readline() 
	while line:
		line = f.readline()
		hist = getSciImageHogHist(line)
		data = []
		data.append(hist)
		tmp = np.array(data, dtype=np.float32)
		index.train(tmp)
		index.add(tmp)

	f.close()
 RuntimeError: Error in virtual void faiss::Clustering::train(faiss::Clustering::idx_t, const float*, faiss::Index&) at Clustering.cpp:68: Error: 'nx >= k' failed: need at least as many training points as clusters

what's wrong ? thank you for advance

**Comment by logidelic** [comment]
I know you closed this, but can you let me know what the problem was? I'm running into the same error and can't figure it out... Thanks.
