### ISSUE TITLE
Unable to install faiss-cpu on aarch64 with AWS Graviton Processor

### ISSUE THREAD

**Issue by MaheshChandrra** [facebookresearch/faiss#1550]
# Summary

Hi I'm trying to install faiss-cpu on an ubuntu machine with aarch64 configuration, but getting continuous errors which involves cython and swig. May I please know how to set up faiss-cpu on this kind of machines.

Thanks in advance.

# Platform

OS: Ubuntu 18.04

Faiss version: 

Installed from: pip install faiss-cpu 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
We don't publish packages for the aarch platform, so you will have to compile faiss yourself.

**Comment by MaheshChandrra** [comment]
May I know the steps for compilation please.

**Comment by mdouze** [comment]
See here: 

https://github.com/facebookresearch/faiss/blob/master/INSTALL.md#general-compilation-instructions

This will **not** work out-of-the-box, so be prepared to adapt the cmakefiles. If you have feedback on this, we are interested!

**Comment by mdouze** [comment]
ARM on AWS graviton is supported now.
