### ISSUE TITLE
Zarr array with faiss index train

### ISSUE THREAD

**Issue by django-kz** [facebookresearch/faiss#1552]
I want to build faiss index from array of vectors, the problem is number of vectors is rather big and I can't load all of them in memory. As I understand for that purpose I could have used numpy memmap. Is there any possibility to use zarr arrays here?
When I try to do that I am receiving the error like:

```
nlist = 100
m = 8                             # number of subquantizers
k = 4
dim = 128
quantizer = faiss.IndexFlatL2(dim)  # this remains the same
index = faiss.IndexIVFPQ(quantizer, dim, nlist, m, 8)
z1 = zarr.open(
    'data/example.zarr', mode='r', 
    shape=(100000, 128),
    chunks=(1000, 128), dtype=np.float32)
index.train(z1)

    119 
    120     def replacement_train(self, x):
--> 121         assert x.flags.contiguous
    122         n, d = x.shape
    123         assert d == self.d

AttributeError: 'Array' object has no attribute 'flags'
```

**Comment by mdouze** [comment]
What is zarr? Faiss supports numpy and pytorch as array formats.

**Comment by django-kz** [comment]
@mdouze  https://zarr.readthedocs.io/en/stable/ - library for writing/reading from disk

**Comment by wickedfoo** [comment]
You would need to make the zarr look like a numpy array, or you can look at how we interface numpy arrays with the C/C++ API via swig here and do something similar yourself, where raw pointers to underlying data is passed to the interface.

https://github.com/facebookresearch/faiss/blob/master/faiss/python/__init__.py#L130

If zarr does chunking internally or is not just a simple memory map, then this is likely not possible.

Supporting zarr ourselves is not something we plan on doing. We only officially offer support for numpy and pytorch data interfaces in python.
