### ISSUE TITLE
[Question] Database support & euclidean

### ISSUE THREAD

**Issue by batara666** [facebookresearch/faiss#1556]
# Summary

Hi, i want to make Reverse image search engine, I already have numpy.nd but i have no idea how to do the search on database (the postgresql CUBE max dim are only 100), how do I implement reverse image search engine with FAISS and the database, thankyou

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by wickedfoo** [comment]
Faiss is a library that can be used as a component for an image search engine and can be interfaced with a database, but implementing image search and interfacing with a database such as PostgresSQL is outside the scope of Faiss library itself and is not something we can provide support on, sorry. You could try other members of the community, perhaps in the FB group.
