### ISSUE TITLE
I want to try to run soloV2, but there are some problems that I don’t know how to solve.

### ISSUE THREAD

**Issue by ZhaoChongren** [facebookresearch/faiss#1557]
environment：
RTX 3070
ubuntu18.04 +cuda11.0+cudnn v8.0+torch 1.7 
I am following here :https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md   install Detectron2.I choose  this method <Install Pre-Built Detectron2 (Linux only)> choose cuda11.0 and torch1.7 install the  Detectron2.when I run the setup.py  .
The following error occurred:/usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/zcr/code/AdelaiDet-master/AdelaiDet/adet/layers/csrc -I/home/zcr/anaconda3/envs/solov2/lib/python3.6/site-packages/torch/include -I/home/zcr/anaconda3/envs/solov2/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/zcr/anaconda3/envs/solov2/lib/python3.6/site-packages/torch/include/TH -I/home/zcr/anaconda3/envs/solov2/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/zcr/anaconda3/envs/solov2/include/python3.6m -c /home/zcr/code/AdelaiDet-master/AdelaiDet/adet/layers/csrc/DefROIAlign/DefROIAlign_cuda.cu -o build/temp.linux-x86_64-3.6/home/zcr/code/AdelaiDet-master/AdelaiDet/adet/layers/csrc/DefROIAlign/DefROIAlign_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
nvcc fatal   : Unsupported gpu architecture 'compute_86'
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

Why does this error occur and how can I modify it

**Comment by mdouze** [comment]
Probably the wrong repo.
