### ISSUE TITLE
A possible optimization for L2 distance computing

### ISSUE THREAD

**Issue by DelightRun** [facebookresearch/faiss#1558]
The squared L2 distance between 2 vector *x* and *y* is as follows:

<img src="https://latex.codecogs.com/svg.latex?d(x,%20y)%20=%20||x%20-%20y||^2%20=%20x^Tx%20-%202x^Ty%20+%20y^Tx" />

where <img src="https://latex.codecogs.com/svg.latex?x^Tx" /> and <img src="https://latex.codecogs.com/svg.latex?y^Ty" /> is the squared norm of *x* and *y* respectively.

So I think it is possible to precompute and store these 2 values to archive faster L2 distance computing. Am I right?

**Comment by mdouze** [comment]
Yes, see 
https://github.com/facebookresearch/faiss/wiki/Implementation-notes#matrix-multiplication-to-do-many-l2-distance-computations

**Comment by DelightRun** [comment]
@mdouze Thanks for your quick reply.

However, I think current implementation can be further improved by store data norms as a member variable of index.

Current implementation of `IndexFlat` use `knn_L2sqr` to do KNN search but without passing `y_norm` argument(see `IndexFlat.cpp` line 54), which means the norm of base vector will be computed every time `knn_L2sqr` is called(see `distances.cpp` line 371 and 264). This will lead to many redundant norm computation if we call `search` several times.
So my idea is to compute and store norm as a part of index, i.e. compute and store norms in `index.add()`. The precomputed norms can also be add into `DistanceComputer` to benefit all related Index type.

**Comment by mdouze** [comment]
This makes sense, and it is implemented in this way on GPU. 
However, I tried it on CPU and it did not make a significiant difference in runtime. 
For a low number of queries, the decomposition is not used and for a large  number of queries, the time to pre-compute the norms is negligible w.r.t. the matrix multiplication time.

**Comment by DelightRun** [comment]
Understood, thank you for your answer.
