### ISSUE TITLE
Scalar Quantization in Faiss - Implementation - Question

### ISSUE THREAD

**Issue by unsuthee** [facebookresearch/faiss#1559]
Hi Faiss team,

I am looking at SQ8 - Scalar Quantization code and try to understand what exactly quantization that Faiss performs. https://github.com/facebookresearch/faiss/blob/master/faiss/impl/ScalarQuantizer.cpp

This code is very hard to understand for me. Do you have any paper or document that describes the implementation that you use in ScalarQuantizer.cpp? I want to see if Faiss SQ8 uses a uniform or non-uniform quantization. Also, how SQ8 in faiss determines the bin boundary at each dimension. 

Thank you in advance for any future answer!

**Comment by mdouze** [comment]
Indeed this is not documented very well. 
The quantization is always uniform. The boundaries are determined at training time. By default it just encodes the range [min, max] at training time. Other training options can be set here: 
https://github.com/facebookresearch/faiss/blob/master/faiss/impl/ScalarQuantizer.h#L43

**Comment by unsuthee** [comment]
Thank you for the response.
