### ISSUE TITLE
 can faiss add extra data in the index？

### ISSUE THREAD

**Issue by vega110** [facebookresearch/faiss#156]
I want to save extra data in my index , for example image-name map image-vector, so if  I query one image vector , I can also find this image name.  can u help me this solution to my question? thank for advance.

quantizer = faiss.IndexFlatL2(d)   # build the index
index = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_L2)
index.train(vectors,   extra_data)
index.add(vectors,   extra_data)

**Comment by mdouze** [comment]
Hi 

No you should manage any metadata as an external table. Faiss is not a generic database engine, so it manages only 64-bit ids.
