### ISSUE TITLE
IndexIVFFlat cannot reconstruct

### ISSUE THREAD

**Issue by yuyifan1991** [facebookresearch/faiss#1563]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU

Interface: 
- [ ] Python

# Reproduction instructions

 
I cannot reconstruct that I use the IndexIVFFlat. I have already created the index by IndexIVFFlat which has the hash ids. I cannot reconstruct. When I use the: _index.make_direct_map()_ , it appears error: _RuntimeError: Error in void faiss::IndexIVF::make_direct_map(bool) at IndexIVF.cpp:159: Error: '0 <= idlist [ofs] && idlist[ofs] < ntotal' failed: direct map supported only for seuquential ids_. How can I reconstruct the vector by hash id?

**Comment by mdouze** [comment]
See here: https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes#database-operations-on-indexes

**Comment by yuyifan1991** [comment]
@mdouze I use the method by _index.set_direct_map_type(faiss.DirectMap.Hashtable)_, but the error is:
_AttributeError: 'IndexIVFFlat' object has no attribute 'set_direct_map_type'_

**Comment by mdouze** [comment]
probably an outdated Faiss version.
