### ISSUE TITLE
Does faiss support the compilation of arm mirroring? If it supports the compilation steps, I read the original article that only version 1.4.0 is OK, is that true, but I have to use version 1.6.3, what should I do?

### ISSUE THREAD

**Issue by yuanpengpeng** [facebookresearch/faiss#1564]
Does faiss support the compilation of arm mirroring? If it supports the compilation steps, I read the original article that only version 1.4.0 is OK, is that true, but I have to use version 1.6.3, what should I do?

**Comment by mdouze** [comment]
duplicate of #1550
