### ISSUE TITLE
Get Subvector after run Faiss index.

### ISSUE THREAD

**Issue by Chuvantinh** [facebookresearch/faiss#1565]
**Label: Question**
Hello everyone, I got stuck all day that I have a vector of 50k points and 1024 dimensions. 
Then I would like to compress this big vector to more small subvectors as 8 vector: 50k point and 128 dimensions. It could be like Product quantization.

**is that possible to get those sub-vectors**? because I have to run each vector with dbscann and optics, kmeans, hdbscann ... in order to find the best solution as the requirement of my teacher.

that was a stupid question but I am on the way to become a coder.

thank you very much.

**Comment by mdouze** [comment]
For vector encodings, the entry point would be 

https://github.com/facebookresearch/faiss/wiki/Vector-codecs

**Comment by Chuvantinh** [comment]
I got an error , that is `code = codec.encode(x)
AttributeError: 'IndexScalarQuantizer' object has no attribute 'encode'`

**Comment by mdouze** [comment]
It's `sa_encode`

**Comment by Chuvantinh** [comment]
thank you so much . that was my mistake

**Comment by nikhiljaiswal** [comment]
@Chuvantinh @mdouze what is the faiss version for sa_encode to work?
I am getting error in faiss==1.5.3
![Screen Shot 2023-02-21 at 10 31 35 PM](https://user-images.githubusercontent.com/21051117/220411878-e5552ec0-15b9-4a9e-8d43-fee60510ac04.png)
