### ISSUE TITLE
How to use the diff patch in https://gist.github.com/mdouze/a384a01d0e205bee6d39d52170fb3588 when arm is compiled

### ISSUE THREAD

**Issue by yuanpengpeng** [facebookresearch/faiss#1568]
How do you use the diff patch in https://gist.github.com/mdouze/a384a01d0e205bee6d39d52170fb3588? Isn't diff compare the two files, and then use the patch command to convert between the target file and the source file. This source file is faiss The source file, what is the target file, and what does a/b/ mean in this?

**Comment by mdouze** [comment]
This is a very old patch to remove intel-specific code from Faiss. It should not be necessary anymore.
