### ISSUE TITLE
Is the cosine distance normalized to 0-1 and if so how?

### ISSUE THREAD

**Issue by BramVanroy** [facebookresearch/faiss#1569]
I built an inner_product index with L2 normalized vectors, with the goal to search by cosine distance. The question that I have is whether this distance is in the typical -1 tot 1 range, or whether it has been normalized to 0-1, and if so - how?

Thanks in advance

**Comment by mdouze** [comment]
so it's cosine similarity, which is between -1 and 1 like the normal cosine function.

**Comment by BramVanroy** [comment]
Alright, that is clear. Thank you.
