### ISSUE TITLE
Can I dump the trained index ?

### ISSUE THREAD

**Issue by mrcsunshine** [facebookresearch/faiss#157]
Can I dump the trained index to the file on disk and restore it when searching？

**Comment by mdouze** [comment]
yes

**Comment by mrcsunshine** [comment]
Thx.  And what about the usage of faiss.index_cpu_to_gpu(). I can't find the API on  this page https://rawgit.com/facebookresearch/faiss/master/docs/html/namespacefaiss.html

What is difference between index in cpu and in gpu?

**Comment by luisremis** [comment]
Where can I find the documentation or interface to dump and load an index?

**Comment by luisremis** [comment]
Yes, you can take a look at the interface at https://github.com/facebookresearch/faiss/blob/master/index_io.h

**Comment by mdouze** [comment]
To summarize, you need to convert to cpu before storing the index.
