### ISSUE TITLE
indexivfpq precomputed_table use a lot of memory

### ISSUE THREAD

**Issue by onriv** [facebookresearch/faiss#1570]
# Summary

precomputed_table use a lot of memory, according to the comment in https://github.com/facebookresearch/faiss/blob/v1.6.2/IndexIVFPQ.h#L56,

in my case, nlist = 4096, pq.M = 64, pq.ksub = 256, more detail in [20201214114812.txt](https://github.com/facebookresearch/faiss/files/5686337/20201214114812.txt)

the size of precompute table should be 512MB

but in the prod enviroment with about 50,000,000 ~ 100,000,000 records , it used memory larget than 10GB, the detail of complete jemalloc report [jeprof.out.48690.12999.i12999.heap.pdf](https://github.com/facebookresearch/faiss/files/5686357/jeprof.out.48690.12999.i12999.heap.pdf)

![image](https://user-images.githubusercontent.com/1629055/102039053-c1ab8700-3e03-11eb-9512-0e695315b15c.png)

Is there something I misunderstood or some other reason it use lots of memory? thanks

# Platform

Faiss version: v1.6.2

Installed from: compiled by myself

Faiss compilation options: GNU C++11 9.2.1 20191102 -m64 -mpopcnt -msse4 -mtune=generic -march=x86-64 -g -O3 -std=c++11 -fopenmp -fPIC -fasynchronous-unwind-tables -fstack-protector-strong

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [X] C++
- [ ] Python

**Comment by wickedfoo** [comment]
In your .txt dump, it shows the precomputed table is a vector<float> of size 67108864 floats, which is 4096 * 64 * 256, which is 256 MiB as expected.

I don't quite understand the trace. The thing that is highlighted is where all std::vector allocations will end up, with multiple arrows pointing into it, not just from precompute_table?

**Comment by onriv** [comment]
@wickedfoo thanks for your response. I write my ivfpq index to a file and then read it back to memory  for about every 100000 records. Will it be some leaks in this process? I check it times and it seems to be ok.

![BF1F0099-4A90-4F9C-B10D-07C4347F17BF](https://user-images.githubusercontent.com/1629055/102044306-80ba6f00-3e11-11eb-8c1d-c21239d1ec52.jpeg)
 
anyway since it’s irrelevant to precomputed_table, I closed this issue. Thanks a lot
