### ISSUE TITLE
Default parameter of hnswFlat index

### ISSUE THREAD

**Issue by eshaoliu** [facebookresearch/faiss#1574]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ 1] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [1 ] Python

# Reproduction instructions

 
This documentation describe the parameter of hnsw.https://github.com/facebookresearch/faiss/wiki/Faiss-indexes#indexhnsw-variants. However，I can‘t find the default parameter even I search the source code.https://github.com/facebookresearch/faiss/blob/c5975cda72981329af97df36b4986ae6f65550e2/faiss/AutoTune.cpp

**Comment by mdouze** [comment]
The default parameters are set in 

https://github.com/facebookresearch/faiss/blob/master/faiss/impl/HNSW.cpp#L53

**Comment by eshaoliu** [comment]
Thanks
