### ISSUE TITLE
train and add big data into index

### ISSUE THREAD

**Issue by vega110** [facebookresearch/faiss#158]
I have fifty million pictures, and per image feature vector dimensions is 1152. 
    quantizer = faiss.IndexFlatL2(d)   # build the index
    index = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_L2)
    index.train(xb)
    index.add(xb) 
when I train or add "xb",  Must I put all images feature vectors to "xb", (xb is a big array of all images)
Then, can I  partially train or add array into "xb"?

**Comment by mdouze** [comment]
Hi 

See 

https://github.com/facebookresearch/faiss/tree/master/benchs#experiments-of-the-appendix

to get started.

Note that the index would be 230 GB RAM in your example.

**Comment by vega110** [comment]
many faiss interface methods I can't understand, so I look a bit difficult. Can u give me some operation steps , Just tell me the core information.

**Comment by jegou** [comment]
There are already plenty of examples in Faiss, and some support documentation such as the Wiki. Please consult these before asking "operation steps". This is vague so there is no way we can help you in that matter.
