### ISSUE TITLE
error of remove ids not implemented for this type of index

### ISSUE THREAD

**Issue by Meshiba** [facebookresearch/faiss#1585]
Hi,
I'm using this setup -
* faiss version 1.6.3 running on GPU
* pytorch version 1.7.1
* cudatoolkit-10.1 (tried to update to 9.1 without success, so updated to 10.1)
* cuda release 9.1 

When I try to run remove_ids with IndexFlatL2 I get this error:
RuntimeError: Error in virtual size_t faiss::Index::remove_ids(const faiss::IDSelector&) at Index.cpp:52: remove_ids not implemented for this type of index

I saw that this faiss version is supposed to support remove_ids with this type of index.
Does anyone know what can be the problem?

Some previous occurrences - 
Before I updated the pytorch cudatoolkit to 10.1, remove ids method does work but torch didn't detect my GPU so I updated the pytorch cudatoolkit to 10.1 and since then, torch does detect my GPU but remove ids doesn't work and I get this error.
Thanks

**Comment by Meshiba** [comment]
## update
I just realized that when i use my GPU , i change my index (initially set to faiss.IndexFlatL2) to be - 
faiss_index = faiss.index_cpu_to_gpu(...)
This method returns type of flat GPU index.

Does this type of index support remove_ids in faiss version 1.6.3?
and if not, which type of GPU index does support remove_ids?

**Comment by wickedfoo** [comment]
No GPU index currently supports remove. It is on the list of features to be worked on in H1 2021 though.

**Comment by Meshiba** [comment]
Is it possible to move the index to cpu before calling remove_ids and then move the index back to gpu?

**Comment by wickedfoo** [comment]
Copying GPU -> CPU, remove on CPU and copying back CPU -> GPU will be incredibly slow each time you do it, but yes this will work.

**Comment by Meshiba** [comment]
Thank you for your help!
