### ISSUE TITLE
Slow search when using IVFx,SQ

### ISSUE THREAD

**Issue by ckald** [facebookresearch/faiss#1588]
# Summary

We are experiencing strange performance problems that I cannot reproduce on a small-ish database. Please advise how to investigate this.

We have a dataset of `10^8` unit vectors in `100/200/300` dimensions. Our current production index is 100d `IVF32768,Flat` (with inner product metric), but we would like to move to something like 200/300d `IVF32768,SQ4`.

However, the performance of IVFSQ index is `8` times worse than IVFFlat! We also tried to explore IVFPQ indices and PCA, but the resulting indices did not find correct vectors at all (this might be a question for another day or a problem on our side). So far only SQ indices produced reasonable results.

Things I've investigated:
1. This issue is not reproduced on a `10^6` dataset
2. We have many near and exact duplicates, but the issue does not appear on the `10^6` dataset even if I add `5x10^6` duplicates sampled from 1% of the dataset
3. Other indices like IVFPQ also work well on a 10^6 dataset 
4. We have a wide range of inverted list sizes: the average list size is supposed to be ~2500, but there are a number of them with around 100 000 vectors. I've experimented with removing the largest invlists in-memory, but there was no impact on search time until I have deleted ~30% of the dataset.
5. I've trained an `IVF131072,SQ4` index. The search time is considerably better than `IVF32768,SQ4` (only `1.3` times slower than `Flat`), but the training time is almost unacceptably long.

# Platform

OS: Ubuntu 16.04.7 LTS (GNU/Linux 4.15.0-117-generic x86_64)

Faiss version: 1.6.3

Installed from: faiss-cpu at pypi 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by wickedfoo** [comment]
Does your machine support AVX2, or was this compiled with AVX2 (I don't know about the relation between pypi and where we release our packages, @beauby might know)? 

I highly suspect that It being a lot slower might be due to the fact that it isn't using the AVX2 kernels like this for SQ4:

https://github.com/facebookresearch/faiss/blob/c5975cda72981329af97df36b4986ae6f65550e2/faiss/impl/ScalarQuantizer.cpp#L105

List imbalance is definitely an issue, but presumably you had list imbalance before with IVFFlat as well.

**Comment by ckald** [comment]
Thanks for the reply! The imbalance factor is typically 1.2. And, as I mentioned, removing the largest lists did not improve the performance

**Comment by wickedfoo** [comment]
Can you try installing from/using https://anaconda.org/pytorch/faiss-cpu instead and see if that fixes the issue? This is where we release our packages as far as I know.

**Comment by ckald** [comment]
Looks like our dataset contains ~20% duplicates. Is there an option to nest FlatDedup inside the ScalarQuantizer? 

Ideally, we'd love to compress the vectors such that the index fits on the GPU. IVFFlat takes 28GB now (and it's not becoming any smaller).

I went through the last year of issues here today and started some experiments with FlatDedup. I'll report on this and the Anaconda tomorrow

**Comment by mdouze** [comment]
I second @wickedfoo  here, IVFSQ is very dependent on being compiled with proper AVX flags. Unfortunately the last official packages (including 1.6.3) are compiled without these flags. Please try with a nighly build.

**Comment by ckald** [comment]
@wickedfoo woah... I installed the anaconda nightly version of faiss-cpu and verified that there is `swigfaiss_avx2.so` in the distribution. All vector lookups have become 6-7 times faster immediately!

Faiss without AVX2:

```python
In [16]: %timeit flatidx.search(normalize(np.random.random((1,100)).astype('float32')), 1000)
1.11 s ± 45 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [17]: %timeit sqidx.search(normalize(np.random.random((1,100)).astype('float32')), 1000)
7.06 s ± 328 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Nightly Faiss with AVX2:

```python
In [25]: %timeit flatidx.search(normalize(np.random.random((1,100)).astype('float32')), 1000)
178 ms ± 2.81 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [26]: %timeit sqidx.search(normalize(np.random.random((1,100)).astype('float32')), 1000)
930 ms ± 32.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

However, the SQ performance compared to the flat index is about the same (even a bit worse). 

Is there something else to check?

**Comment by mdouze** [comment]
It depends the regime the search is running in: 
- if it is CPU-bound then SQ is a bit slower than Flat because it does the same computations and in addition has to decompress the vectors.
- if it is memory bound then SQ is faster because it fetches less data per vector
We generally observe that in a multi-threaded environment, the search is memory bound.

**Comment by ckald** [comment]
I've found the `IndexIVFStats` struct. Does the "decompression time" count towards the `IndexIVFStats.quantization_time`?

I see the following (no AVX2):

```python
In [151]: stats.reset()

In [152]: %time idx.faiss.search(np.random.random((1, 100)).astype(np.float32), 10)
CPU times: user 1.37 s, sys: 157 ms, total: 1.52 s
Wall time: 1.52 s
Out[152]:
...

In [153]: stats.search_time, stats.quantization_time
Out[153]: (1511.805908203125, 10.633056640625)

In [154]: stats.reset()

In [155]: %time sqidx.faiss.search(np.random.random((1, 100)).astype(np.float32), 10)
CPU times: user 9.15 s, sys: 212 ms, total: 9.36 s
Wall time: 9.36 s
Out[155]:
...

In [156]: stats.search_time, stats.quantization_time
Out[156]: (9352.766845703125, 10.68896484375)
```

The quantization time is negligible, while search time is very large — I don't understand where the time is spent.

Regarding the multi-threading — of course, using more threads together with `parallel_mode=1` provide a proportional boost, but the single-thread mode does not look right, I'd like to sort this out.
