### ISSUE TITLE
About index building with IndexFlatIP

### ISSUE THREAD

**Issue by mrcsunshine** [facebookresearch/faiss#160]
Hi, I want to know about the method for index constructing with IndexFlatIP.  Why it is faster than dot product calculation with numpy?

**Comment by mdouze** [comment]
Hi
The dot product calculation is not faster. Finding n largest values is.

**Comment by jegou** [comment]
A big matrix multiplication needs to store many values, eventually causing cache misses, while for the index we are only interested in keeping the largest ones. Faiss avoids this problem by tiling the matrix multiplication and keeping a low temporary memory usage at minimum.

**Comment by mrcsunshine** [comment]
so how to define the largest ones before the query vector comes? and how does the index which set up offline reflect the distance message ?

**Comment by mdouze** [comment]
please rephrase.

**Comment by mdouze** [comment]
Closing.
