### ISSUE TITLE
Python data structure corruption under some circumstances

### ISSUE THREAD

**Issue by mkarppa** [facebookresearch/faiss#1608]
# Summary

FAISS seems to cause Python data structure corruption under some circumstances. The circumstances are somewhat difficult to reproduce, but the attached minimal example seems to cause problems quite often. In practice, when Python unallocates some of its resources, we get errors from malloc checksum failures, free() fails from invalid pointers, or something other rather random (including segfaults and weird exceptions thrown from system libraries). 

# Platform

OS:  macOS 10.15.7, Ubuntu Linux 20.04.1 LTS

Faiss version: git commit d494251b5d134e424721f93eba697f5d4e4d93e2 

Installed from: anaconda 1.6.5 py3.8_h0453e9c_0_cpu, also compiled myself on both macOS and Linux 
On macOS, compiled with CLang 12.0.0, and on Ubuntu, compiled with GCC 9.3.0 and CLang 10.0.0.
On macOS, Python 3.8.5 from Anaconda was used. On Ubuntu, Python 3.8.5 was used as well (from default repository).

Faiss compilation options:  Default (disabled GPU)

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

Run the following script, possibly a few times:
```
import faiss
import numpy as np

index = faiss.IndexIVFFlat(faiss.IndexFlatL2(9), 9, 128, faiss.METRIC_L2)
index.train(np.zeros((2173,9), np.float32))
index.add(np.zeros((2173,9), np.float32))

m = np.zeros(2173) + 0.01
for j in range(2173):
    Z = index.search(np.expand_dims(np.zeros(9,np.float32),axis=0),0)[0]
    e = Z / m[j] 
```

Expected results are error messages originating from standard libraries such as:
```
python3(38083,0x110ed4dc0) malloc: Region cookie corrupted for region 0x7fdc48a00000 (value is 0)[0x7fdc48a0407c]
python3(38083,0x110ed4dc0) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort
```
or
```
free(): invalid pointer
Aborted (core dumped)
```

**Comment by mdouze** [comment]
I can repro

**Comment by mdouze** [comment]
So the problem is that zero results are requested, which is a corner case that is indeed not handled. Low-pri to fix IMO.

**Comment by yinze00** [comment]
@mdouze  coming across this issue, i found version 1.17.1  had fixed this bug  by asserting k > 0
```python
Traceback (most recent call last):
  File "gh.py", line 10, in <module>
    Z = index.search(np.expand_dims(np.zeros(9,np.float32),axis=0),0)[0]
  File "/usr/local/lib/python3.6/site-packages/faiss-1.7.1-py3.6.egg/faiss/__init__.py", line 306, in replacement_search
    assert k > 0
AssertionError
```
