### ISSUE TITLE
Performing sparse updates on a trained IVFFlat index

### ISSUE THREAD

**Issue by daniellevy** [facebookresearch/faiss#161]
Hi,

I have been using the IVFFlat index from FAISS for nearest neighbor search and would be interested to know if there would be an easy way to perform sparse update, i.e. given a trained index, change the value of the i-th without having to retrain the full index.

The signature of the function would look as follows:
`
void update_vector(IVFFlat & ivf, idx_t i, const float *new_val); 
`
Ideally, `idx_t i` could also be a list of indices.

Thanks a lot in advance for your help,

Best,
Daniel

**Comment by mdouze** [comment]
Hi 

The question is whether it is useful to re-train the index at all. Normally when new elements are inserted into the index, they are supposed to follow the data distribution that was viewed during training. If it is not the case, the question is when does re-training need to take place? Every so many updates?

I will submit a PR that supports updates without re-training for IndexIVFFlat.

**Comment by daniellevy** [comment]
Thanks a lot for your help!

In practice, I think the distribution of the data might change slowly with each updates, so re-training might need to take place every so many updates as you suggested.

From my understanding, even after updating the vectors, it is not possible to run index->train() from the previously initialized centroids as the method requires index->is_trained to be set to False. Is there some way around with that API?

Best,

**Comment by mdouze** [comment]
There is no way around with the API, it would change the behavior too much. 
I would indeed suggest to make a new index every once in a while. You can get all the stored vectors with reconstruct_n.

**Comment by mdouze** [comment]
See 

https://github.com/facebookresearch/faiss/blob/master/IndexIVF.h#L198

and associated test

https://github.com/facebookresearch/faiss/blob/master/tests/test_index_composite.py#L48

**Comment by daniellevy** [comment]
Thank you very much for your help and reactivity!

**Comment by Hari-Sheng** [comment]
Hi @mdouze is it possible to update this feature to GpuIndexIVFFlat as well?

**Comment by LiberiFatali** [comment]
Is there anything similar to update vectors for IndexIdMap?
