### ISSUE TITLE
Question about HNSW running on GPUs

### ISSUE THREAD

**Issue by Ji-Hoon-0708** [facebookresearch/faiss#1611]
Hi, currently I try to run the HNSW on GPUs.

However, from the previous issue (https://github.com/facebookresearch/faiss/issues/1348), what I saw is that the HNSW is not implemented on GPU.

So, if what I understand is correct, like the previous issue by adding the (faiss.index_cpu_to_gpu, gpu_index_flat.add, etc), we can run the corresponding index on GPUs but does it work on the same in HNSW? If not, is it possible to run the HNSW on GPUs by using faiss library?

**Comment by mdouze** [comment]
HNSW is not implemented on GPU. If you use index_cpu_to_gpu, it will just copy the index to another CPU index (the default behavior for indexes it does not recognize).

**Comment by Ji-Hoon-0708** [comment]
I see. Thanks!
