### ISSUE TITLE
After faiss saves the index through write_index, is there any way to read the vector id and value stored in it?

### ISSUE THREAD

**Issue by yuanpengpeng** [facebookresearch/faiss#1618]
After faiss saves the index through write_index, is there any way to read the vector id and value stored in it?

**Comment by mdouze** [comment]
What type of index?

**Comment by yuanpengpeng** [comment]
Flat type

**Comment by mdouze** [comment]
https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes#reconstructing-all-vectors-of-a-range-reconstruct_n
