### ISSUE TITLE
If  I want to call faiss through golang, can golang call all the api interfaces of faiss provided by faiss through cgo, is this feasible?

### ISSUE THREAD

**Issue by yuanpengpeng** [facebookresearch/faiss#1619]
If  I want to call faiss through golang, can golang call all the api interfaces of faiss provided by faiss through cgo, is this feasible?

**Comment by mdouze** [comment]
I don't understand the question. 
The official Faiss is not interfaced with Go.

**Comment by yuanpengpeng** [comment]
I saw that faiss provides a C++ interface, can golang call the C++ interface provided by faiss to implement faiss related functions?

**Comment by Enet4** [comment]
This goes a bit beyond the scope of the project. I do not know exactly what capabilities exist for Go to interface with C++ libraries, but that should be answerable with some research. It is known that the unofficial project [go-faiss](https://github.com/41tair/go-faiss) relies on the C API instead.

**Comment by pauloue** [comment]
I also wrote https://github.com/DataIntelligenceCrew/go-faiss/ which is a more direct binding of the C API.
