### ISSUE TITLE
Illegal instruction while running tutorial example

### ISSUE THREAD

**Issue by Mohamed-Okasha** [facebookresearch/faiss#162]
After building FAISS in Ubuntu 16 installed in vps, i faced this error
![screenshot](http://i.imgur.com/7Pexwcc.png)

**Comment by mdouze** [comment]
Hi 
Are you sure the CPU supports AVX? If not, remove the -mavx flag from the compilation flags.

**Comment by Mohamed-Okasha** [comment]
It work fine now, Thank you
