### ISSUE TITLE
hnsw pq correct usage question

### ISSUE THREAD

**Issue by gony0** [facebookresearch/faiss#1621]
Recently, I'm doing a benchmark using faiss hnsw pq.
I couldn't find the exact usage for hnsw-pq, so I want to be checked if I used it correctly.

I am using [ann-benchmarks](https://github.com/erikbern/ann-benchmarks) codes for benchmarking, I just modified `fit` method in  [faiss_hnsw.py](https://github.com/erikbern/ann-benchmarks/blob/8d8df13cd90bfe73ba9105115bb106b0f8f86358/ann_benchmarks/algorithms/faiss_hnsw.py#L15-L26) to build hnsw-pq.
(Assume dim is a multiple of 2)
```python
def fit(self, X):
    dim = len(X[0])
    assert dim % 2 == 0
    pq_m = dim // 2
    
    self.index = faiss.IndexHNSWPQ(dim, pq_m, self.method_param["M"])
    self.index.hnsw.efConstruction = self.method_param["efConstruction"]
    self.index.verbose = True

    if self._metric == 'angular':
        X = X / np.linalg.norm(X, axis=1)[:, np.newaxis]
    if X.dtype != np.float32:
        X = X.astype(np.float32)
        
    self.index.train(X)
    self.index.add(X)
    faiss.omp_set_num_threads(1)
```
I'm wondering if it is the correct way to put all the vectors to be added into the train.
I'm also wondering if I can use the `inner-product` metric in hnsw-pq. In IndexHNSWPQ, I found that the metric cannot be specified and the only l2 is used internally.

**Comment by mdouze** [comment]
If the vectors are normalized it does not matter if you are using L2 or IP metric.
Otherwise the code looks correct.

**Comment by gony0** [comment]
@mdouze Is there any way to use IP metric with pq for non-normalized vectors?

**Comment by mdouze** [comment]
hmm no :-(

**Comment by xsank** [comment]
> Recently, I'm doing a benchmark using faiss hnsw pq. I couldn't find the exact usage for hnsw-pq, so I want to be checked if I used it correctly.
> 
> I am using [ann-benchmarks](https://github.com/erikbern/ann-benchmarks) codes for benchmarking, I just modified `fit` method in [faiss_hnsw.py](https://github.com/erikbern/ann-benchmarks/blob/8d8df13cd90bfe73ba9105115bb106b0f8f86358/ann_benchmarks/algorithms/faiss_hnsw.py#L15-L26) to build hnsw-pq. (Assume dim is a multiple of 2)
> 
> def fit(self, X):
>     dim = len(X[0])
>     assert dim % 2 == 0
>     pq_m = dim // 2
>     
>     self.index = faiss.IndexHNSWPQ(dim, pq_m, self.method_param["M"])
>     self.index.hnsw.efConstruction = self.method_param["efConstruction"]
>     self.index.verbose = True
> 
>     if self._metric == 'angular':
>         X = X / np.linalg.norm(X, axis=1)[:, np.newaxis]
>     if X.dtype != np.float32:
>         X = X.astype(np.float32)
>         
>     self.index.train(X)
>     self.index.add(X)
>     faiss.omp_set_num_threads(1)
> I'm wondering if it is the correct way to put all the vectors to be added into the train. I'm also wondering if I can use the `inner-product` metric in hnsw-pq. In IndexHNSWPQ, I found that the metric cannot be specified and the only l2 is used internally.

Does the code above really works?
