### ISSUE TITLE
Accessing the invlists of a GpuIndexIVFFlat in Python

### ISSUE THREAD

**Issue by MaxVanHoucke** [facebookresearch/faiss#1627]
What would the most efficient way be of accessing the inverted lists of a GpuIndexIVFFlat in Python?
This question arose when trying out a gpu index for the first time, which broke code that was using the invlists attribute of a normal IndexIVFFlat.

**Comment by mdouze** [comment]
There is no API to do that, but you can convert it back to CPU with `index_gpu_to_cpu`.

**Comment by wickedfoo** [comment]
The only API accessible for this at the moment is in C++ in the form equivalent to the CPU form via `GpuIndexIVF::getListVectorData` which returns a `std::vector<uint8_t>`. `gpuFormat` should be `false`, as the GPU data layout is potentially quite different than the CPU format. There is no accessor for the raw data directly on the GPU.

Converting the index to the CPU form and using the accessors there is probably the best way. That will always work.

**Comment by wickedfoo** [comment]
https://github.com/facebookresearch/faiss/blob/master/faiss/gpu/GpuIndexIVF.h#L69

**Comment by MaxVanHoucke** [comment]
Thank you for the quick answers!
