### ISSUE TITLE
Install faiss for nvidia 3090

### ISSUE THREAD

**Issue by RealNewNoob** [facebookresearch/faiss#1629]
Hi, I am currently using a 3090, the earlies driver it supports is 455, which support only cuda 11.1. The faiss-gpu install document only list support for cuda 10.0, is there any method to use faiss-gpu on my device?

**Comment by e-tony** [comment]
Try [#1525 (commen)](https://github.com/facebookresearch/faiss/issues/1524#issuecomment-758688833)?

**Comment by RealNewNoob** [comment]
> Try [#1525 (comment)](https://github.com/facebookresearch/faiss/issues/1524#issuecomment-758688833)?

The kernel stops at solving enviroments.

**Comment by h-vetinari** [comment]
You can follow https://github.com/conda-forge/cudatoolkit-feedstock/issues/47 for the conda-forge effort regarding CUDA 11.1 / 11.2. Things are getting pretty close, and once the infrastructure is out of the way, it won't take long for the migrator comes by the faiss [feedstock](https://github.com/conda-forge/faiss-split-feedstock).

**Comment by h-vetinari** [comment]
Now that https://github.com/conda-forge/faiss-split-feedstock/pull/29 was merged, you should be able to do `conda install -c conda-forge faiss-gpu` for both CUDA 11.1 & CUDA 11.2 setups.

**Comment by phanxuanduc1996** [comment]
I used Anaconda, I installed bellow, it worked. If you use Docker, please install Miniconda.
`conda install faiss-gpu cudatoolkit=11.1 -c pytorch-gpu`
`conda install -c anaconda pytorch-gpu`
