### ISSUE TITLE
ProductQuantizer does not Initialize

### ISSUE THREAD

**Issue by eladmw** [facebookresearch/faiss#1632]
# Summary
# Platform

OS: Linux (Virtual Machine)

Faiss version: 

Installed from: pip

Running on:
- [ ] CPU

Interface: 
- [ ] Python

# Reproduction instructions

xs,ys = train.shape
cs = 4  # code size (bytes)
pq = faiss.ProductQuantizer(ys, cs, 8)
# pq.train(train.values)

 

/opt/conda/lib/python3.7/site-packages/faiss/swigfaiss.py in __init__(self, *args)
   1561 
   1562     def __init__(self, *args):
-> 1563         this = _swigfaiss.new_ProductQuantizer(*args)
   1564         try:
   1565             self.this.append(this)

RuntimeError: Error in void faiss::ProductQuantizer::set_derived_values() at ProductQuantizer.cpp:164: Error: 'd % M == 0' failed

**Comment by mdouze** [comment]
The number of subquantizers (M) should be a multiple of the dimension of the vector (d).
