### ISSUE TITLE
Multi threads to read the results of the training function.

### ISSUE THREAD

**Issue by cherishtttz** [facebookresearch/faiss#1633]
When we use IndexIVFPQ to search and add data, we found that if multi people read  the  index which were saved from the training function at the same time,  there would be error.  Does faiss just support single thread but not for multi threads to use??

**Comment by mdouze** [comment]
See doc about threading here: 
https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls

**Comment by cherishtttz** [comment]
> See doc about threading here:
> https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls

Got it! thanks so much!
