### ISSUE TITLE
I have a vector file of dimention 768 x 10^9 suggest me a best indexing method

### ISSUE THREAD

**Issue by vigneshmj1997** [facebookresearch/faiss#1638]
My vector is of size 768 * 10^9 my machine had 4*2080 ti gpu and a RAM of 64 g 
suggest me a good indexing method with a good balance of accuracy and time for finding nearest neighbor or any suggestion on how to proceed with this problem 
Thanks in advance

**Comment by mdouze** [comment]
Please refer to https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index
