### ISSUE TITLE
low recall with flat index on gpu

### ISSUE THREAD

**Issue by MDurgaKeerthi** [facebookresearch/faiss#1639]
I took the gpu sample code for python and ran it using glove-100-angular dataset with a dimension of 1183514x100. I am using **faiss.IndexFlatL2** index which is supposed to do an exact search but I am only getting very low values of recall(0.55). I don't even think I missed any parameters. ANN-benchmarks seems to be getting very high values of recall for the same dataset. Can someone please help me identify what is that I'm missing? Attached is the code that I'm using.

```
def compute_recall(neighbors, true_neighbors):
    total = 0
    for gt_row, row in zip(true_neighbors, neighbors):
        total += np.intersect1d(gt_row, row).shape[0]
    return total/true_neighbors.size 

d = 100                           # dimension
nb = 1183514                      # database size
nq = 10000                       # nb of queries
k = 10                          # we want to see 4 nearest neighbors

loc = os.path.join(".", "glove-100-angular.hdf5")
glove_h5py = h5py.File(loc, "r")
xb = np.asarray(glove_h5py['train'], dtype=np.float32)
xq = np.asarray(glove_h5py['test'], dtype=np.float32)

res = faiss.StandardGpuResources()
quantizer = faiss.IndexFlatL2(d) 
gpu_index = faiss.index_cpu_to_gpu(res, 0, quantizer)
gpu_index.add(xb)              # add vectors to the index

D, I = gpu_index.search(xq, k) # actual search
print("Recall:", compute_recall(I, glove_h5py['neighbors'][:, :10]))
```

**Comment by wickedfoo** [comment]
GloVe vectors are meant to be compared with cosine similarity.

Are the vectors normalized? If not, the vectors should be normalized, and use GpuIndexFlatIP for inner product.

**Comment by MDurgaKeerthi** [comment]
Normalizing solves everything. Thanks!
