### ISSUE TITLE
question about writeing and reading GpuIndexIVFPQ. How to set useFloat16LookupTables as reading GpuIndexIVFPQ?

### ISSUE THREAD

**Issue by chenqingguo** [facebookresearch/faiss#1641]
faiss version I using is 1.6.3.
Here is the way I build GpuIndexIVFPQ and save it.

```
//build index
faiss::gpu::GpuIndexIVFPQConfig pqConfig;
pqConfig.useFloat16LookupTables =true;
auto IVFPQIndex=new faiss::gpu::GpuIndexIVFPQ(resource,d,nlist,64,8,faiss::METRIC_INNER_PRODUCT,pqConfig);
...
//save index
faiss::Index *cpuIndex= faiss::gpu::index_gpu_to_cpu(IVFPQIndex);
faiss::write_index(cpuIndex,name.c_str());
delete cpuIndex;
...
//load index
auto cpuIndex=faiss::read_index(name.c_str());
auto gpuIndex=faiss::gpu::index_cpu_to_gpu(resource,0,cpuIndex);
```
Then I got this "Error:'requiredSmemSize<=getMaxSharedMemPerBlock(device_)' failed:Device has 49152 bytes of shared memory,while 8 bits per code and 64 sub-quantizers requires 65536 bytes. Consider useFloat16LookupTables  and/or reduce parameters."
But ```faiss::gpu::GpuClonerOptions``` hasn't this member.
I tried ```options.useFloat16=true```,that works but the top10 results is kind of different with the Index I trained. 

- My device is 2080Ti,there are 5000Mb left when I was running this test. What does ``` Device has 49152 bytes of shared memory,while 8 bits per code and 64 sub-quantizers requires 65536 bytes.``` mean?
- How to set ```useFloat16LookupTables ``` as reading Index?

Thanks!

**Comment by wickedfoo** [comment]
You can copy a CPU index to the GPU by calling `IVFPQIndex->copyFrom(cpuIndex);` in what you have above, which will write over the data present in IVFPQIndex (a GpuIndexIVFPQ) from what is coming from the GPU

**Comment by chenqingguo** [comment]
Got it.
Thanks~
