### ISSUE TITLE
Would you please add  `void write_VectorTransform (const VectorTransform *vt, IOWriter *f)` to the public API?

### ISSUE THREAD

**Issue by vahagnIV** [facebookresearch/faiss#1645]
I noticed that the version of the function that uses IOWriter is defined in `faiss/impl/index_write.cpp` but is absent in the public API, i.e. there's no declaration in the `faiss/index_io.h`

**Comment by mdouze** [comment]
Seems legit. Marking as enhancement.

**Comment by AbdelrahmanElmeniawy** [comment]
This issue was fixed. 
write_VectorTransform(const VectorTransform *vt, IOWriter* f) and read_vectorTransform(IOReader* f) were added to the public API.
