### ISSUE TITLE
Documentation for using other metrics (e.g. L_p)

### ISSUE THREAD

**Issue by dmadras** [facebookresearch/faiss#1646]
Hi - I've been digging through the documentation for a while now and it's not clear to me how I would run knn using a metric other than L2 or cosine distance (or Mahalanobis, through pre/post processing). Specifically I'm interested in METRIC_Lp. Can someone point me to this, or create a page describing this process more clearly? I've seen the list of metrics and the list of indices and I assume somehow I can combine faiss.METRIC_Lp with faiss.IndexFlat, but from reading the docs I have no idea how to do this. 

Let me know if I'm missing something, thanks!

**Comment by wickedfoo** [comment]
Apologies, open-source Faiss documentation is substantially lacking (something we hope to address this half), but instantiate a `faiss.IndexFlat` with the `faiss.METRIC_Lp`, and set `metric_arg` on the `faiss.IndexFlat` to the `p` parameter.

Only `IndexFlat` and `GpuIndexFlat` currently implement the alternative metrics.

**Comment by dmadras** [comment]
No worries, thanks for the response!
