### ISSUE TITLE
avx2 not generated despite flag during installation

### ISSUE THREAD

**Issue by Michiel29** [facebookresearch/faiss#1648]
I am attempting to compile the cpu version of faiss with AVX2. After I cmake, make, and install the python bindings, I just get normal swigfaiss, not swigfaiss_avx2. The loader resolves to swigfaiss after failing to import sigfaiss_avx2, and indeed there is no swigfaiss_avx2 in the build folder. If I try to import manually, I get:

```
ModuleNotFoundError: No module named 'faiss.swigfaiss_avx2'
```

I'm on a modern I7 CPU, and calling instruction_set() in loader.py returns AVX2. 

I am using the build command:

`cmake -B build -DFAISS_ENABLE_GPU=OFF -DPython_EXECUTABLE=<path_to_python> -DFAISS_OPT_LEVEL=avx2  -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON`
```

which results in:

```
-- The CXX compiler identification is GNU 8.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found MKL: /opt/intel/mkl/lib/intel64_lin/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64_lin/libmkl_sequential.so;/opt/intel/mkl/lib/intel64_lin/libmkl_core.so;-lpthread;-lm;-ldl  
-- Found SWIG: /usr/local/bin/swig (found version "4.0.2") found components: python 
-- Found Python: /home/msdejong/anaconda3/envs/testenv/include/python3.8 (found version "3.8.5") found components: Development NumPy Interpreter Development.Module Development.Embed 
-- The C compiler identification is GNU 8.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /home/msdejong/anaconda3/envs/testenv/bin/python (found version "3.8.5") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/msdejong/packages/faiss_test/build
```

**Comment by mdouze** [comment]
This is normal if you compile it yourself. The .so file is called `_swigfaiss.so`. 

You can make sure that it includes AVX by compiling with make VERBOSE=1 and checking that the flag `-mavx2` is on the command line.

**Comment by Michiel29** [comment]
Thanks for the rapid clarification! In that case, the compilation with AVX is slower than conda for other reasons - I will make another issue/join existing issue for that.

**Comment by YJYJLee** [comment]
@Michiel29 Helllo, I am also going through the same issue. Could you briefly explain how you solved this issue?

**Comment by Michiel29** [comment]
> @Michiel29 Helllo, I am also going through the same issue. Could you briefly explain how you solved this issue?

Well, as mdouze mentioned, swigfaiss_avx2 is only relevant to the conda release. The conda release comes with built versions of standard swigfaiss and swigfaiss_avx2, and during import time it checks whether your cpu supports avx2 instructions. If it does, it loads swigfaiss_avx2, otherwise swigfaiss. 

If you're building from source, there's no need to build two versions, it just builds with or without avx depending on whether you put the avx flag, under the name swigfaiss. 

Are you experiencing an error?

**Comment by YJYJLee** [comment]
I'm trying to build it from source and I also checked that my cpu supports avx2 instruction. So I used below command (almost the same as yours) and also checked `-mavx2` flag is in the command line with VERBOSE=1.
`cmake -D CMAKE_CXX_COMPILER=/usr/bin/g++-8 -D CMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc -Wno-dev -B build . -DFAISS_OPT_LEVEL=avx2`

However, after I finish doing cmake, make, and installing the python bindings, when I am trying to import faiss I get following error.. I have no idea why it cannot find the avx module.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/faiss-1.7.0-py3.6.egg/faiss/loader.py", line 52, in <module>
    from .swigfaiss_avx2 import *
ModuleNotFoundError: No module named 'faiss.swigfaiss_avx2'
```

**Comment by Michiel29** [comment]
Is that the whole error? Because that line should be wrapped in a try except. 

What happens is, it tries to import swigfaiss_avx2 (that line is there for conda builds). If it fails, it will import normal swigfaiss in the except. If you built from source with avx flag, that normal swigfaiss will have avx enabled. However, what can happen is that there is some other error happening when importing normal swigfaiss. Then you get the error message: 

ModuleNotFoundError: No module named 'faiss.swigfaiss_avx2'

During handling of the above exception, another exception occurred

real error here

In that case the problem is that real error below, not the swigfaiss_avx2 part

**Comment by YJYJLee** [comment]
Finally, I succeed importing faiss!! Thank you so much.
As you said, swigfaiss_avx2 was not the problem. I turned out that cmake and python bindings used different version of python, so it had trouble importing normal sigfaiss. 
So I specified python version to cmake like below. 
`cmake -D CMAKE_CXX_COMPILER=/usr/bin/g++-8 -D CMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc -Wno-dev -B build . -DFAISS_OPT_LEVEL=avx2 -DPython_EXECUTABLE=/usr/bin/python3.6`

**Comment by Michiel29** [comment]
> Finally, I succeed importing faiss!! Thank you so much.
> As you said, swigfaiss_avx2 was not the problem. I turned out that cmake and python bindings used different version of python, so it had trouble importing normal sigfaiss.
> So I specified python version to cmake like below.
> `cmake -D CMAKE_CXX_COMPILER=/usr/bin/g++-8 -D CMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc -Wno-dev -B build . -DFAISS_OPT_LEVEL=avx2 -DPython_EXECUTABLE=/usr/bin/python3.6`

Glad it worked out!
