### ISSUE TITLE
SWIG out of sync

### ISSUE THREAD

**Issue by Plippe** [facebookresearch/faiss#165]
Hi,

When I generate python code from the master branch, I obtain a very different `swigfaiss.py`. The most noticeable changes are related to method signatures:
```
# Original
def add(self, *args): return _swigfaiss.Index_add(self, *args)

# Generated
def add(self, n, x):
        return _swigfaiss.Index_add(self, n, x)
```

Are there breaking changes coming ?

To reproduce
```
# Download swigfaiss.py from master
mkdir -p /tmp/faiss/github
wget https://raw.githubusercontent.com/facebookresearch/faiss/master/python/swigfaiss.py -O /tmp/faiss/github/swigfaiss.py

# Generate swigfaiss.py from master via docker
mkdir -p /tmp/faiss/docker
docker build -t faiss github.com/facebookresearch/faiss
docker run --rm -itv /tmp/faiss/docker:/opt/faiss/python faiss make clean py

# Compare downloaded VS generated
sdiff /tmp/faiss/github/swigfaiss.py /tmp/faiss/docker/swigfaiss.py
```

**Comment by mdouze** [comment]
Hi 
This is most likely due to a change in SWIG version.  We use version 3.0.1.

**Comment by Plippe** [comment]
Hi,

Just above is a PR that updates the `Dockerfile` to have `swig=3.0.1` over the latest version.

**Comment by mdouze** [comment]
Thanks. 

Did you notice a problem when compiling with the new swig? Otherwise it is fine if the generated code is different.

**Comment by Plippe** [comment]
This seems to fix the generation. 
I do find it funny that a minor version change causes so many issues.
