### ISSUE TITLE
CUDA 10.2 conda builds

### ISSUE THREAD

**Issue by urikz** [facebookresearch/faiss#1650]
Hi! Would you mind providing a conda build for FAISS + CUDA 10.2? That will help a lot since compiling from sources is a bit challenging. 

Thank you in advance!

**Comment by h-vetinari** [comment]
conda-forge has builds for CUDA 9.2, 10.0, 10.1, 10.2 & 11.0 on linux (11.1 & 11.2 coming soon, hopefully windows+CUDA as well).

```
> conda config --add channels conda-forge
> conda install faiss=*=*cuda
> # if you have faiss-gpu installed already, better use:
> conda install faiss-gpu
```

**Comment by beauby** [comment]
Note that we do provide conda builds for CUDA 10.2:
```
$ conda install -c pytorch faiss-gpu cudatoolkit=10.2
```
