### ISSUE TITLE
Why IndexIvfx is slower than IndexFlatL2?

### ISSUE THREAD

**Issue by ppdollhhh** [facebookresearch/faiss#1656]
# Summary
Hello：

When I make performerce test, I found IndexIVFx is slower IndexFlatL2, but when I change xq's shape to (1, 512), IndexIVFFlat is faster IndexFlatL2 about 1 times. 
1、My database shape is (3511, 512)，train data is my full database
2、xq shape is （1000，512)
3、IVFx nlist is 90， nprobe is 9

CPU mode result is:
Flat memory:  7248
Flat add time:  0.0046727657318115234
Flat search time:  0.36131834983825684
----------------
IVF train time:  0.5231897830963135
IVF memory:  6588
IVF add time:  0.04633903503417969
IVF search time:  0.8941836357116699
IVF accuracy with order:  0.9958
IVF accuracy without order:  0.9984
----------------
IVFSQ train time:  0.5908169746398926
IVFSQ memory:  0
IVFSQ add time:  0.0765986442565918
IVFSQ search time:  6.375136137008667
IVFSQ accuracy with order:  0.9912
IVFSQ accuracy without order:  0.9978
----------------

GPU mode：
Flat memory:  0
Flat add time:  0.001638650894165039
Flat search time:  0.0032868385314941406
----------------
IVF train time:  0.15410685539245605
IVF memory:  0
IVF add time:  0.006935834884643555
IVF search time:  0.005383014678955078
IVF accuracy with order:  0.9954
IVF accuracy without order:  0.9964
----------------
IVFSQ train time:  0.17790675163269043
IVFSQ memory:  0
IVFSQ add time:  0.005623817443847656
IVFSQ search time:  0.005033016204833984
IVFSQ accuracy with order:  0.9896
IVFSQ accuracy without order:  0.9958
----------------

# Platform

OS:ubuntu16.04

Faiss version: 1.6.5

Installed from:  compiled

Faiss compilation options:cmake -DCMAKE_CUDA_ARCHITECTURES="61;75" -B build .

Running on:
- [ ] CPU
- [1 ] GPU

Interface: 
- [ ] C++
- [1 ] Python

# Reproduction instructions

my test code:

import os
os.environ['OMP_NUM_THREADS'] = '1'
import faiss
import numpy as np
import time
from memory_profiler import profile

limit = 1000

def indexSearch(xq, index, topk=5):
    D, I = index.search(xq, topk)  # actual search
    S = (3 - D) / 3
    S = np.maximum(S, 0)
    S = np.minimum(S, 1)
    return S, I

def indexFlatL2Bench(xq, dim, topk, device='GPU'):
    indexFlatL2 = faiss.IndexFlatL2(dim)
    if device == 'GPU':
        indexFlatL2 = getGPUIndex(indexFlatL2)
    memory1 = faiss.get_mem_usage_kb()
    time1 = time.time()
    indexFlatL2.add(xq)
    time2 = time.time()
    print('Flat memory:  {0}'.format(faiss.get_mem_usage_kb() - memory1))
    randomRow = np.arange(xq.shape[0])
    np.random.shuffle(randomRow)
    xq = xq[randomRow[:limit]]
    print('Flat add time:  {0}'.format(time2 - time1))
    _, benchIds = indexSearch(xq, indexFlatL2, topk)
    print('Flat search time:  {0}'.format(time.time() - time2))
    print('----------------')
    return randomRow, benchIds

def indexIVFBench(xq, randomRow, trainData, dim, topk, benchIds, nlist=90, nprobe=9, device='GPU'):
    indexIVF = faiss.IndexFlatL2(dim)
    indexIVF = faiss.IndexIVFFlat(indexIVF, dim, nlist)
    if device == 'GPU':
        indexIVF = getGPUIndex(indexIVF)
    time3 = time.time()
    indexIVF.train(trainData)
    memory2 = faiss.get_mem_usage_kb()
    time4 = time.time()
    print('IVF train time:  {0}'.format(time4 - time3))
    indexIVF.add(xq)
    time5 = time.time()
    print('IVF memory:  {0}'.format(faiss.get_mem_usage_kb() - memory2))
    print('IVF add time:  {0}'.format(time5 - time4))
    indexIVF.nprobe = nprobe
    xq = xq[randomRow[:limit]]
    time6 = time.time()
    _, IVFIds = indexSearch(xq, indexIVF, topk)
    print('IVF search time:  {0}'.format(time.time() - time6))
    accuracyWithOrder, accuracyWithoutOrder = getAccuracy(IVFIds, benchIds)
    print('IVF accuracy with order:  {0}'.format(accuracyWithOrder))
    print('IVF accuracy without order:  {0}'.format(accuracyWithoutOrder))
    print('----------------')
    return

def indexIVFSQBench(xq, randomRow, trainData, dim, topk, benchIds, nlist=90, nprobe=9, device='GPU'):
    indexIVFSQ = faiss.IndexFlatL2(dim)
    indexIVFSQ = faiss.IndexIVFScalarQuantizer(indexIVFSQ, dim, nlist, faiss.ScalarQuantizer.QT_8bit)
    if device == 'GPU':
        indexIVFSQ = getGPUIndex(indexIVFSQ)
    time7 = time.time()
    indexIVFSQ.train(trainData)
    memory3 = faiss.get_mem_usage_kb()
    time8 = time.time()
    print('IVFSQ train time:  {0}'.format(time8 - time7))
    indexIVFSQ.add(xq)
    time9 = time.time()
    print('IVFSQ memory:  {0}'.format(faiss.get_mem_usage_kb() - memory3))
    print('IVFSQ add time:  {0}'.format(time9 - time8))
    indexIVFSQ.nprobe = nprobe
    xq = xq[randomRow[:limit]]
    time10 = time.time()
    _, IVFSQIds = indexSearch(xq, indexIVFSQ, topk)
    print('IVFSQ search time:  {0}'.format(time.time() - time10))
    accuracyWithOrder, accuracyWithoutOrder = getAccuracy(IVFSQIds, benchIds)
    print('IVFSQ accuracy with order:  {0}'.format(accuracyWithOrder))
    print('IVFSQ accuracy without order:  {0}'.format(accuracyWithoutOrder))
    print('----------------')
    return

def getAccuracy(ids, benchIds):
    numberBench = np.sum(benchIds == benchIds)
    numberIdsWithOrder = np.sum(ids == benchIds)
    accuracyWithOrder = numberIdsWithOrder / numberBench
    numberIdsWithoutOrder = 0
    for id, benchId in zip(ids, benchIds):
        for i in id:
            if i in benchId:
                numberIdsWithoutOrder += 1
    accuracyWithoutOrder = numberIdsWithoutOrder / numberBench
    return accuracyWithOrder, accuracyWithoutOrder

def getGPUIndex(index):
    res = faiss.StandardGpuResources()
    index = faiss.index_cpu_to_gpu(res, 1, index)  # we want to see 4 nearest neighbors
    return index

if __name__ == '__main__':
    dim = 512
    topk = 5
    device = 'CPU'
    xq = np.load('trainFeatures.npy')
    trainData = xq
    randomRow, benchIds = indexFlatL2Bench(xq=xq, dim=dim, topk=topk, device=device)
    indexIVFBench(xq=xq, randomRow=randomRow, trainData=trainData, dim=dim, topk=topk, benchIds=benchIds, device=device)
    indexIVFSQBench(xq=xq, randomRow=randomRow, trainData=trainData, dim=dim, topk=topk, benchIds=benchIds, device=device)

**Comment by ppdollhhh** [comment]
Anyone can help me?Thx

**Comment by mdouze** [comment]
The database is too small for IVF to be useful.

**Comment by ppdollhhh** [comment]
I have try database （100000， 512）， then the result is same
