### ISSUE TITLE
Documentation suggestion: replace 'x' as variable for code size, given x already used as 'times'

### ISSUE THREAD

**Issue by Michiel29** [facebookresearch/faiss#1657]
Given the drive to improve documentation for 2021 I figured I'd give this suggestion.

If I understand correctly, a number of places in the wiki (e.g. https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index, https://github.com/facebookresearch/faiss/wiki/Faiss-indexes) use x both as a variable and as a times symbol. For example, I think "PQ"x"x"nbits means PQ$num_codes times $bits_per_code. This was pretty confusing to me for a while. I think replacing variable x with z or u,v,w would be a low-cost significant improvement to documentation clarity.

**Comment by mdouze** [comment]
that makes sense...

**Comment by mdouze** [comment]
Done.
