### ISSUE TITLE
Does faiss support online spherical clustering with GPU?

### ISSUE THREAD

**Issue by RealNewNoob** [facebookresearch/faiss#1658]
We are going to perform a spherical clustering on a large dataset which is over our gpu memory, can and how I do it with faiis?

**Comment by mdouze** [comment]
NB that only the centroids need to fit in GPU memory, not the dataset.

**Comment by RealNewNoob** [comment]
> NB that only the centroids need to fit in GPU memory, not the dataset.

I read the wiki and learned how to set up the index on disk. However, I still don't know how to load huge data properly in faiss.Clustering() or faiss.Kmeans(). Is there any tutorial for this?

**Comment by gasparyanartur** [comment]
Seeing as this was completed, could you mind pointing to where you found the answer to the question?
