### ISSUE TITLE
Parameters used for comparison with HNSW

### ISSUE THREAD

**Issue by Chetter2** [facebookresearch/faiss#166]
It looks like the memory overhead for the HNSW method in the comparison table is incorrect https://github.com/facebookresearch/faiss/wiki/Indexing-1M-vectors

nmslib (hnsw) | 0.081 s | 0.8195 | 512 + 796 MB | 173 s

For example M=32 -> 32 * 2 * 4 * 1000000 / 1024 / 1024 = 244 MB

So I wonder what parameters did you use?

**Comment by mdouze** [comment]
Hi,

I used M=16. The exact source code is here: 

https://gist.github.com/mdouze/1fbbfa779091ce221b589ab9f944b5f7

The memory overhead is the size of the dataset + the file size.

**Comment by jegou** [comment]
Question answered, and no reply in more than 3 months -> closing.
