### ISSUE TITLE
NVIDIA 3080 failed to run demo in faiss 1.6.3

### ISSUE THREAD

**Issue by Aurevoir-68** [facebookresearch/faiss#1664]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

 

We use the source code to compile faiss 1.6.3, which is no problem; however, when we run 4- GPU.cpp and 5-multiple- GPUs.cpp in faiss/tutorial/cpp，There is a problem:

running 4- GPU.cpp, the questions are as follows:

**Faiss asseration ' err == CUBLAS_STATUS_SUCCESS ' failed in void faiss::gpu::runMatrixMult(faiss::gpu::Tensor<float,2,true>&,bool,faiss::gpu::Tensor<T,2,true>&)
...
details:cublas failed(13):(512,64) x (10000,64)' = (512,100000)
Aborated（core dumped）**

Is this because the computing capability of 3080 is 8.6 and faiss 1.6.3 does not support such a high computing capability?
Hope to see your reply, thank you!!!

**Comment by wickedfoo** [comment]
I've been engaging with Nvidia on this, might be an issue in CUDA 11. I've checked in a workaround, but would require getting latest and building Faiss from scratch to see if it fixes your problem.

**Comment by Aurevoir-68** [comment]
@wickedfoo  When the above problems occur, I use CUDA version 8.0 instead of 11.0. Are the reason and solution the same as what you said above?

**Comment by Aurevoir-68** [comment]
@wickedfoo  When the above problems occur, I use CUDA version 8.0 instead of 11.0. Are the reason and solution the same as what you said above?

**Comment by wickedfoo** [comment]
Can you try CUDA 11 instead with what is latest in the github repository?

**Comment by phanxuanduc1996** [comment]
I used Anaconda, I installed bellow, it worked. If you use Docker, please install Miniconda.
`conda install faiss-gpu cudatoolkit=11.1 -c pytorch-gpu`
`conda install -c anaconda pytorch-gpu`
