### ISSUE TITLE
how could I validate searching with cpu or gpu?

### ISSUE THREAD

**Issue by juncaofish** [facebookresearch/faiss#1665]
# Summary

The code for building index offline

```import faiss
faiss.get_num_gpus() # 8

index = faiss.index_factory(1024, "PCA256,IVF65536,PQ64")

- copy from https://gist.github.com/mdouze/46d6bbbaabca0b9778fca37ed2bcccf6
index_ivf = faiss.extract_index_ivf(index)
clustering_index = faiss.index_cpu_to_all_gpus(faiss.IndexFlatL2(256))
index_ivf.clustering_index = clustering_index
index.train(random_sampled_embeddings)

- add to index
for batch_embedding in some_generator:
    index.add(batch_embedding)

- dump the index to disk
faiss.write_index(index, "/tmp/trained.index")
```

when online,
```
index = faiss.read_index("/tmp/trained.index")
distances, indices = index.search(query_embeddings, top_k)
```
The question is how could I use gpu to accelerate searching , and how could I validate whether I'm searching on GPU.

Thanks a lot.

**Comment by mdouze** [comment]
You can move the index to GPU with 
https://github.com/facebookresearch/faiss/wiki/Running-on-GPUs#in-python-3a

**Comment by juncaofish** [comment]
> You can move the index to GPU with
> https://github.com/facebookresearch/faiss/wiki/Running-on-GPUs#in-python-3a

I'm not sure what you mean by moving the index to GPU. Since the index is trained on GPU and adds vectors before dumping to disk. When I read the index from disk file and tried to use index cpu_to_gpu, an AssertError appeared

**Comment by juncaofish** [comment]
> > You can move the index to GPU with
> > https://github.com/facebookresearch/faiss/wiki/Running-on-GPUs#in-python-3a
> 
> I'm not sure what you mean by moving the index to GPU. Since the index is trained on GPU and adds vectors before dumping to disk. When I read the index from disk file and tried to use index cpu_to_gpu, an AssertError appeared

> RuntimeError: Error in void faiss::gpu::GpuIndexIVFPQ::verifySettings_() const at /__w/faiss-wheels/faiss-wheels/faiss/faiss/gpu/GpuIndexIVFPQ.cu:433: Error: 'requiredSmemSize <= getMaxSharedMemPerBlock(config_.device)' failed: Device 0 has 49152 bytes of shared memory, while 8 bits per code and 64 sub-quantizers requires 65536 bytes. Consider useFloat16LookupTables and/or reduce parameters

when running the code
```
index = faiss.read_index("/tmp/trained.index")
gpu_index = faiss.index_cpu_to_all_gpus(  # build the index
    index
)
```

**Comment by juncaofish** [comment]
Solved.

**Comment by flexobrain** [comment]
Could you maybe provide information on how you solved the issue because i am facing the same one.
