### ISSUE TITLE
k-NN search in IndexBinaryHash returns elements unodrered.

### ISSUE THREAD

**Issue by mdouze** [facebookresearch/faiss#1670]
missing maxheap_reorder 

https://github.com/facebookresearch/faiss/blob/master/faiss/IndexBinaryHash.cpp#L142

**Comment by Soonhwan-Kwon** [comment]
Thank you for reporting this issue, I solved my problem with your insight. I updated faiss then I can get correct result.

**Comment by asadoughi** [comment]
Appears to be addressed in https://github.com/facebookresearch/faiss/commit/10c8583b2d41433925d72adc1ad9c44885c4976b
