### ISSUE TITLE
The different results when shuffle the samples.

### ISSUE THREAD

**Issue by httpswlt** [facebookresearch/faiss#1676]
# Summary

# Platform

Centos: 7

Faiss version: laste version

Installed from: anaconda

Faiss compilation options:  conda install faiss-cpu -c pytorch

Running on:
- [x] CPU

- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
1. Ori-Code:

import faiss
import numpy as np
import os
from video_reader import VideoReader
import copy
import numpy as np

d = 64  # dimension
nb = 100000  # database size
nq = 10000  # nb of queries
np.random.seed(1234)  # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
tmp = int(len(xb) / 2)
before = copy.deepcopy(xb[:tmp, :])
after = copy.deepcopy(xb[tmp:, :])
xb[:tmp, :] = before
xb[tmp:, :] = after
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

import faiss  # make faiss available

index = faiss.IndexFlatL2(d)  # build the index
print(index.is_trained)
index.add(xb)  # add vectors to the index
print(index.ntotal)

k = 4  # we want to see 4 nearest neighbors
D, I = index.search(xb[:5], k)  # sanity check
print(I)
print(D)
D, I = index.search(xq, k)  # actual search
print(I[:5])  # neighbors of the 5 first queries
print(I[-5:])

Result:
True
100000
[[  0 393 363  78]
 [  1 555 277 364]
 [  2 304 101  13]
 [  3 173  18 182]
 [  4 288 370 531]]
[[0.        7.1751733 7.207629  7.2511625]
 [0.        6.3235645 6.684581  6.7999454]
 [0.        5.7964087 6.391736  7.2815123]
 [0.        7.2779055 7.5279865 7.6628466]
 [0.        6.7638035 7.2951202 7.3688145]]
[[ 381  207  210  477]
 [ 526  911  142   72]
 [ 838  527 1290  425]
 [ 196  184  164  359]
 [ 526  377  120  425]]
[[ 9900 10500  9309  9831]
 [11055 10895 10812 11321]
 [11353 11103 10164  9787]
 [10571 10664 10632  9638]
 [ 9628  9554 10036  9582]]

2. Adjust the order for the samples:

import faiss
import numpy as np
import os
from video_reader import VideoReader
import copy
import numpy as np

d = 64  # dimension
nb = 100000  # database size
nq = 10000  # nb of queries
np.random.seed(1234)  # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
tmp = int(len(xb) / 2)
before = copy.deepcopy(xb[:tmp, :])
after = copy.deepcopy(xb[tmp:, :])
xb[:tmp, :] = after
xb[tmp:, :] = before
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

import faiss  # make faiss available

index = faiss.IndexFlatL2(d)  # build the index
print(index.is_trained)
index.add(xb)  # add vectors to the index
print(index.ntotal)

k = 4  # we want to see 4 nearest neighbors
D, I = index.search(xb[:5], k)  # sanity check
print(I)
print(D)
D, I = index.search(xq, k)  # actual search
print(I[:5])  # neighbors of the 5 first queries
print(I[-5:])

Result:
True
100000
[[    0    74 99167 99497]
 [    1 99727 99374 99628]
 [    2 98512 99959 99700]
 [    3   113 99561 99928]
 [    4   232 99252 99500]]
[[0.        5.5615516 6.179271  6.463312 ]
 [0.        5.7446327 5.7933464 5.974424 ]
 [0.        6.897052  6.927189  7.02889  ]
 [0.        5.673896  6.399749  6.4457197]
 [0.        6.430212  6.650798  6.700003 ]]
[[50381 50207 50210 50477]
 [50526 50911 50142 50072]
 [50838 50527 51290 50425]
 [50196 50184 50164 50359]
 [50526 50377 50120 50425]]
[[59900 60500 59309 59831]
 [61055 60895 60812 61321]
 [61353 61103 60164 59787]
 [60571 60664 60632 59638]
 [59628 59554 60036 59582]]

I just adjusted the order of the samples. Why are the results different?

**Comment by httpswlt** [comment]
I have knowed.

**Comment by jarandaf** [comment]
@httpswlt care to elaborate? I am experiencing a similar issue.
