### ISSUE TITLE
Issues with max_points_per_centroid parameters

### ISSUE THREAD

**Issue by jonsaadfalcon** [facebookresearch/faiss#1679]
# Summary

Hello, I am having some trouble with faiss.KMeans. When I try to set the parameter max_points_per_centroid, the KMeans model doesn't seem to take it into account. It will still create clusters with more datapoints than the max parameter. Here is my code:

```
ncentroids = 1024
niter = 20
verbose = True
kmeans = faiss.Kmeans(dimension, ncentroids, niter=niter, verbose=verbose, 
                      min_points_per_centroid= 100, max_points_per_centroid= 4000)
kmeans.train(testingResultsEmbeddings)

cluster_centers_ = kmeans.centroids
labels_ = kmeans.index.search(x=testingResultsEmbeddings, k=1)[1].reshape(-1)
```

When I test to see the largest cluster in the labels_ variable, it seems to have clusters with larger than 4000 points.

OS:  macOS 10.13.3

Faiss version: Latest

Installed from: Pip

Running on:
- [x] CPU

Interface: 
- [x] Python

**Comment by wickedfoo** [comment]
Those parameters control the min/max number of training points used per centroid (e.g., you are saying that you want a dataset between 1024 * 100 and 1024 * 4000 vectors in `testingResultsEmbeddings`; if you don't provide at least 102400 vectors it will complain, and if you provide more than 4096000 vectors it will subsample and use only 4096000 of them), not the min/max number of points actually clustered per each centroid.
