### ISSUE TITLE
There has a code line seems will never work.

### ISSUE THREAD

**Issue by yyy007** [facebookresearch/faiss#168]
In file "IndexIVFPQ.cpp" line 1162 to 1172. When "prev + 1 ==i" or not, "dup_ids [lims [ngroup]++]" will be "list_ids [ord [i]]", the line "dup_ids [lims [ngroup]++] = list_ids [ord [prev]]" will never play a part. Is there any wrong with the codes? Thank you!
```
            if (prev >= 0 && cs.cmp (ord [prev], ord [i]) == 0) {
                // same as previous => remember
                if (prev + 1 == i) { // start new group
                    ngroup++;
                    lims[ngroup] = lims[ngroup - 1];
                    dup_ids [lims [ngroup]++] = list_ids [ord [prev]];
                }
                dup_ids [lims [ngroup]++] = list_ids [ord [i]];
            } else { // not same as previous.
                prev = i;
            }
```

**Comment by mdouze** [comment]
Hi 

You realize there is a new group when the current code and the previous code are the same, ie. `cs.cmp (ord [prev], ord [i]) == 0` and prev=i-1. In that case, you need to put both prev and i in the group, hence the two operations. So I think the code is correct.

What could be changed is to loop from i=1 and initialize prev to 0. This would spare a test.

**Comment by yyy007** [comment]
I understand, I missed the `lims [ngroup]++`.
Thank you very much for helping me!
