### ISSUE TITLE
Batch wise index creation and search for data won't find memory  ?  

### ISSUE THREAD

**Issue by naveen-panwar** [facebookresearch/faiss#1692]
# Summary

How to create index of very big data while loading data in batches ? My goal is to get K-NN for all the data points in dataset. 

# Platform

OS: Linux amd64

Faiss version: 1.6.5

Installed from: anaconda 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

This is the snippet. How should I create index here ?  
**Can't  share the data :(** 

```python
import faiss
improt pandas

quantizer = faiss.IndexFlatL2(64) 
index = faiss.IndexIVFPQ(quantizer, 64, 1024, 8, 8)

df = pd.read_csv("Very big file won't fit into the memory", chunksize=10000)

for df_batch in df:
    
    batch_data = df.values ## just getting numpy  array of df 

    # is this step right ? will it update the index ? 
    index.train(batch_data)
    index.add(batch_data)

# will I have index on all the data once for-loop is complete ? 

all_knn = []
for df_batch in df:

     batch_data = df.values ## just getting numpy  array of df 
     all_knn += index.search(batch_data, k=15)

```

**Task:**
I have 100M data points with 100+  features. I want to find K-NN value for each of these 10M points.

**Questions:**
* How should I efficiently **create index** for 100M points.. preferable batch wise (I have memory constraint whole data won't fit into the memory) ? 

* How should I efficiently **search** for K-NN in  index for all 100M points ?

**Comment by mdouze** [comment]
You should train once and call add on each of the batches.

From the second loop I assume you want to search the set of vectors among themselves.

**Comment by naveen-panwar** [comment]
Thanks @mdouze for information.. 
> You should train once and call add on each of the batches.

I am assuming it won't harm the indexing.. As I am **only training on 1 batch(10K data points) and adding rest (9M 90K data points)** 




> From the second loop I assume you want to search the set of vectors among themselve

I want to search for k nearest neighbours of data in one batches but neighbours can be from entire data.. 

Just wanted to confirm again.. `index.search(batch_data, k=15)` **will give me neighbours from all dataset not only from this batch.**

```python
all_knn = []
for df_batch in df:

     batch_data = df.values ## just getting numpy  array of df 
     batch_knn = index.search(batch_data, k=15)
     all_knn += batch_knn
````
