### ISSUE TITLE
Do you have a plan to add a clang-format file to format the code?

### ISSUE THREAD

**Issue by KinglittleQ** [facebookresearch/faiss#1693]
# Summary

There are multiple coding styles in faiss, e.g. 2/4 spaces indentation. It may confuse the contributors and make the code a little hard to read. Providing a code format tool or guide would keep the code in a unified style. `clang-format` is a powerful and configurable tool to format the code and the coding style could be controlled by `.clang-format` file. 

It is a little risky to force the coding style to be unified because most of the files will be overwritten. But
I think it is still valuable to do this since this could solve one for all in the future.

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
That is a long lasting discussion....

**Comment by beauby** [comment]
Done.
