### ISSUE TITLE
How to infer index returned by IndexFlatL2.search()

### ISSUE THREAD

**Issue by tomar840** [facebookresearch/faiss#1698]
When using the index.search(), 2 parameters are returned as shown below - 
distance, neighbours = index.search(query_vector,k)

what does neighbours hold in it ? Is it the actual index of the embeddings ? 
E.g. I have added embeddings of size 10000x1024 to the index and the neighbour(return parameter of index.search()) holds [25,247] as the index for top-2 searches.  Does 25 & 247 are the position of vectors in embeddings ? like can I access these similar vectors by embeddings[25] & embeddings[247] ?

**Comment by FoilHao** [comment]
Have you understand the meaning of neighbors. I'm also confused since it seems I can only obtain idx of centroids from index.search().

**Comment by tomar840** [comment]
Yeah, elements in neighbours list contains the index of the neighbour elements. You don't get index of centroid, these are the index of neighbour elements. 
Hope it's helpful.
