### ISSUE TITLE
ModuleNotFoundError: No module named 'faiss' on windows

### ISSUE THREAD

**Issue by abdulwajid725** [facebookresearch/faiss#1699]
# Summary

I installed Faiss using the following command in my conda environment --> "conda install -c pytorch faiss-cpu"

Windows 10
Running on CPU
Interface - python

List of packages installed :
+conda-forge/win-64::faiss-1.7.0-py37h59bcff0_2_cpu
+conda-forge/win-64::faiss-cpu-1.7.0-hf9c7e24_2
+conda-forge/win-64::libfaiss-1.7.0-he82878b_2_cpu

Importing Faiss gives "ModuleNotFoundError: No module named 'faiss'"
Looked into previous solutions for this issue but no success.

**Comment by beauby** [comment]
It seems you have packages installed from `conda-forge`, yet you mention installing from the `pytorch` channel. Please try installing in a fresh conda environment:

```
conda create -n faiss_env -c pytorch python=3.8 faiss-cpu
conda activate faiss_env
```

**Comment by NeverInAsh** [comment]
Hi I am installing in a new environment. But i still face this issue.
I am attaching the image of my packages in the new environment.

![image](https://user-images.githubusercontent.com/7336367/110137035-67183a80-7df6-11eb-83da-fff0749df797.png)

**Comment by beauby** [comment]
@NeverInAsh You have both `faiss` (from pypi) and `faiss-cpu`(from conda) installed. This is almost a guarantee for conflicts.

**Comment by NeverInAsh** [comment]
@beauby  Sorry I didn't see this comment. But this is something that is getting installed automatically. Why is this happening ?

**Comment by beauby** [comment]
@NeverInAsh Not sure about your setup, but try `pip uninstall faiss`.

**Comment by NeverInAsh** [comment]
It is not finding faiss package

![image](https://user-images.githubusercontent.com/7336367/110141317-08a18b00-7dfb-11eb-95df-5937a69dff6e.png)

**Comment by DeepTecher** [comment]
i guess you need uninstall faiss-cpu

you can grep to find faiss package:
> pip list | grep faiss

**Comment by tginart** [comment]
Hi all,

Having a similar issue:

```
(env) tginart@machine:~$ conda list | grep 'faiss'
faiss-gpu                 1.7.1           py3.7_h080d439_1_cuda10.2    pytorch
libfaiss                  1.7.1           h4fe19ad_1_cuda10.2    pytorch
```
 
But I still cannot import:

```
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import faiss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'faiss'
```

Any suggestions? Thanks!

**Comment by jpm1989** [comment]
Try to install "jupyter notebook" or "jupyter lab" in that environment. After that try to "import faiss".
e.g. (my_env) c:\Users\xyz "here install jupyter notebook"
then open that notebook,
then "import faiss"

**Comment by hemangjoshi37a** [comment]
`pip install faiss-cpu`
