### ISSUE TITLE
the difference between code and doc about indexing 1T vectors

### ISSUE THREAD

**Issue by wanghainan89** [facebookresearch/faiss#1703]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- CPU
- [ ] GPU

Interface: 
- [ ] C++
- Python

# Reproduction instructions

From the wiki(https://github.com/facebookresearch/faiss/wiki/Indexing-1T-vectors) we can see "we chose the codec that offers precision > 90% and recall> 99.9% for the lowest memory usage: this is the 6-bit scalar quantizer with PCA to 72 dim: 54 bytes, 2.7x more compact than exhaustive storage."

However, In the code of this experiment (https://github.com/facebookresearch/faiss/blob/master/benchs/distributed_ondisk/make_trained_index.py), there is nothing about PCA, only have RandomRotation and ScalarQuantizer operations.

I want to know is there any difference between code and doc when choosing the encoding? If not, how the PCA operation is implemented?

thanks!

**Comment by mdouze** [comment]
That's correct. The documentation is about internal data that we cannot share. 
The code  runs on a publicly available dataset, with is 96-dimensional, therefore it is not necessary to use a PCA to reduce the dimensionality to 72 * 6 / 8 = 72 bytes, hence the RandomRotation. However, it is easy to replace the RandomRotation with a PCAMatrix in make_trained_index.py.

**Comment by wanghainan89** [comment]
OK, I see, thanks very much!
