### ISSUE TITLE
Indexing the feature vector list of unequal shapes

### ISSUE THREAD

**Issue by Zumbalamambo** [facebookresearch/faiss#1705]
I have extracted embeddings from images and each vectors are of different shapes. so I have added all the individual vector to a list `descriptors`.

Finally I use the following code to index the descriptors,

```
def create_index(features, index_file_name):
    d = features.shape[1]
    index_model = faiss.IndexFlatIP(d)
    index_model.train(features)
    index_model.add(features)
    faiss.write_index(index_model, index_file_name)

```
whereas `features` is a list of features with embeddings of varied shape. Unfortunately the list element has no shape which then throws an error message as follow,

`
    d = features.shape[1]
AttributeError: 'list' object has no attribute 'shape'
`
How can I index list of unequal feature vectors?

**Comment by mdouze** [comment]
You can't because it is not possible to compute a distance between vectors of different sizes.

**Comment by Zumbalamambo** [comment]
thank you
