### ISSUE TITLE
Questions about saving and loading

### ISSUE THREAD

**Issue by Jerrylu5683** [facebookresearch/faiss#171]
I auto-tune the parameters using the code "tests/demo_sift1M.cpp".  And after runing "params.set_index_parameters()",  I save the index to a file. Should I set the parameters again when using this index by loading with "read_index()". Or how can I print the index's parameters?

**Comment by mdouze** [comment]
Hi 
No the parameters are saved along with the file. There is no generic way of printing an index's parameters.
