### ISSUE TITLE
why is K-means of faiss-gpu version slower than sklearn cpu version

### ISSUE THREAD

**Issue by erwangccc** [facebookresearch/faiss#1719]
# Summary

# Platform

OS:  Ubantu 16.04

Faiss version:  1.7.0

Installed from:  pip install faiss-gpu

Faiss compilation options: 

cuda: 10.2
GPU TITAN

Running on:
- [ ] CPU
- [+] GPU

Interface: 
- [ ] C++
- [+] Python

# Reproduction instructions

 

I installed faiss-gpu version to do image segmentation via k-means and i found faiss-gpu version(1s) slower than sklearn(300ms).
They have same parameters. the code is as follows:
` 
# faiss implementation of k-means
    clus = faiss.Clustering(d, nmb_clusters)
    # Change faiss seed at each k-means so that the randomly picked
    # initialization centroids do not correspond to the same feature ids
    # from an epoch to another.
    clus.seed = np.random.randint(1234)
    clus.niter = 50
    clus.max_points_per_centroid = 100000
    res = faiss.StandardGpuResources()
    flat_config = faiss.GpuIndexFlatConfig()
    flat_config.useFloat16 = False
    flat_config.device = 0
    index = faiss.GpuIndexFlatL2(res, d, flat_config)
    # perform the training
    clus.train(image, index)
    _, I = index.search(image, 1)`

please let me know if you need other information.
Thanks in advance.

**Comment by mdouze** [comment]
I suspect that the problem is too small to make a difference here. What is the number of training vectors and their dimensionality, and the number of centroids?

**Comment by wickedfoo** [comment]
also how many iterations is sklearn performing?

**Comment by erwangccc** [comment]
> I suspect that the problem is too small to make a difference here. What is the number of training vectors and their dimensionality, and the number of centroids?

Thanks. 
vectors is [16000, 1], centroids.shape=7.

**Comment by erwangccc** [comment]
> also how many iterations is sklearn performing?

Thanks. It's also 50.

**Comment by wickedfoo** [comment]
You are performing k-means on scalars (1-dimensional vectors). Faiss is meant for high-dimensional data (dims > 32 usually).
