### ISSUE TITLE
Question about instantiating DistanceCompyter 

### ISSUE THREAD

**Issue by Kun-Ming** [facebookresearch/faiss#1721]
# Summary

I am working on find out how many points are calculated during a `IndexHNSWFlat` search, the dataset using `inner_product` metric. So I want to navigate the code which responsible to  compute distance. Then I found a class named `DistanceComputer`, which will be instantiated in `IndexHNSWFlat::search()`, see https://github.com/facebookresearch/faiss/blob/master/faiss/IndexHNSW.cpp#L305, and then turn to https://github.com/facebookresearch/faiss/blob/master/faiss/IndexHNSW.cpp#L103, then through `storage->get_distance_computer()` to https://github.com/facebookresearch/faiss/blob/master/faiss/Index.cpp#L142, which should raise an error rather than a object, when the `metric_type` is not `METRIC_L2`. It makes me confusing.

**Comment by mdouze** [comment]
The number of distance computations performed is available via the search stats, see 

https://github.com/facebookresearch/faiss/wiki/Implementation-notes#statistics-for-non-exhaustive-search

**Comment by Kun-Ming** [comment]
> The number of distance computations performed is available via the search stats, see
> 
> https://github.com/facebookresearch/faiss/wiki/Implementation-notes#statistics-for-non-exhaustive-search

Thx! Does it also available in python version?

**Comment by Kun-Ming** [comment]
> > The number of distance computations performed is available via the search stats, see
> > https://github.com/facebookresearch/faiss/wiki/Implementation-notes#statistics-for-non-exhaustive-search
> 
> Thx! Does it also available in python version?

Oh i see the the python version. Thx again.

**Comment by Kun-Ming** [comment]
> The number of distance computations performed is available via the search stats, see
> 
> https://github.com/facebookresearch/faiss/wiki/Implementation-notes#statistics-for-non-exhaustive-search

What does n1, n2, n3, nreorder mean in HNSWStats?
