### ISSUE TITLE
[help] Distance calculation needs improvement for my faiss index

### ISSUE THREAD

**Issue by juncaofish** [facebookresearch/faiss#1729]
I tried building faiss index with template "OPQ64_256,IVF262144,PQ32" on 10M vector(1024 dimension), and the result distances are used to calculate some kind of probability, which seems to have bad accuracy. 

The question is how could we improve the distance accuracy and keep the index size compact at the same time.

Thanks.

**Comment by juncaofish** [comment]
I change the index factory template to "IVF262144,PQ32" (remove the dimension reduction step), the distance accuracy improves obviously... As a tradeoff, the index size increase from 993.9 M to 1.8 G .  Any further optimization suggestion ?

**Comment by mdouze** [comment]
Actually the PQ size is the same in both cases. The dominant factor is the size of the IVF codebook (262144*1024*4 bytes). 
To reduce the codebook size, you can 
1. compress the codebook, eg with IVF262144(SQ8) 
2. use IMI, eg. with IMI2x9,PQ32
