### ISSUE TITLE
undefined symbol GPU python

### ISSUE THREAD

**Issue by bzwqq** [facebookresearch/faiss#173]
when i compile the gpu python part. i do it success.  but when i try to test it with" import _swigfaiss_gpu", it output the error info :"/opt/intel****/intel64/libmkl_gnu_thread.so: undefined symbol: mkl_sparse_z_block_mv_a_rowmajor_i8".

then,  i find the libmkl_gnu_thread.so, and do:  nm -s libmkl_gnu_thread.so | grep "mkl_sparse_z_block_mv_a_*".  it do have the symbol "mkl_sparse_z_block_mv_a_rowmajor_i8".

I don't known  why ,  can anybody help me ?  thanks anyway!

**Comment by mdouze** [comment]
Hi 

This is yet another MKL link problem...

**Comment by bzwqq** [comment]
now, i have solve this problem.
 i delete all mkl-versions in my machine, and completely reinstall the lastest mkl version.  and then  binggo now. 
i think the reason is  there's some old mkl-versions before, and that cause  the  link error.

**Comment by mdouze** [comment]
closing.
