### ISSUE TITLE
Warnings in Python; e.g., Parameter 'x' unfilled

### ISSUE THREAD

**Issue by jmugan** [facebookresearch/faiss#1730]
# Summary

In PyCharm I get a warning for
```
index = faiss.IndexFlatL2(512)
index.add(my_vecs)
```
It says "Parameter 'x' unfilled on the second line.

I get similar warnings on other calls, but it seems to work. I can't tell what the Python API should be. Is this documented anywhere?

OS: 
Ubuntu

Installed from: pip 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ x] Python

# Reproduction instructions
Load tutorial in PyCharm

**Comment by mdouze** [comment]
Sorry, I don't know what PyCharm is. 
We have a PR in flight to add documentation to the most common index methods.

**Comment by moyangjiayou** [comment]
I met the same problem when I use python interface of faiss。the parameter of All interface is same to c++。It's too odd！
![image](https://user-images.githubusercontent.com/10397230/129439384-cc46c549-9d35-42c9-a9fa-ad7918a72d6e.png)

**Comment by smallLian** [comment]
I met the same problem, will it cause problems?

**Comment by moyangjiayou** [comment]
您好！我是莫洋，我已经收到您的来信了！
