### ISSUE TITLE
Unable to add indexes

### ISSUE THREAD

**Issue by NeverInAsh** [facebookresearch/faiss#1732]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- **[ ] CPU**
- [ ] GPU

Interface: 
- [ ] C++
- **[ ] Python**

# Reproduction instructions

HI, I am unable to add custom indexes

# Building FAISS Index
embeddings = np.array([embedding for embedding in embeddings]).astype("float32")

# Instantiate the index
index = faiss.IndexFlatIP(embeddings.shape[1])

# Pass the passage index to IndexIDMap
index = faiss.IndexIDMap(index)

#numerical map
passage_num_map = {i:x for i,x in enumerate(passage_data.passage_id.values)}

# Add vectors and their IDs
index.add_with_ids(embeddings, np.array(list(passage_num_map.keys())))

Error:- I am unable to add these indexes
TypeError: in method 'IndexIDMap_add_with_ids', argument 4 of type 'faiss::IndexIDMapTemplate< faiss::Index >::idx_t const *'

**Comment by sinievanderben** [comment]
Hi, I saw you closed your issue. How did you fix it?
