### ISSUE TITLE
[Question] How many vectors are needed to train the SQ8 index?

### ISSUE THREAD

**Issue by ava57r** [facebookresearch/faiss#1735]
# Summary

Hello.

I read https://github.com/facebookresearch/faiss/wiki/Vector-codecs#very-mild-compression.

This type of index need to train.

I can't find information about a train dataset for SQ8 index.

How many vectors are needed to train the SQ8 index?

Thanks.

**Comment by mdouze** [comment]
You don't need many vectors, 256 is too few, around 10000 should be plenty.

**Comment by ava57r** [comment]
Thanks!

**Comment by ava57r** [comment]
Do I need to train again only when the data type changes?

https://github.com/facebookresearch/faiss/wiki/FAQ#can-i-used-an-index-trained-on-some-kind-of-data-to-index-some-other-type-of-data-of-the-same-dimension

**Comment by Enet4** [comment]
The linked FAQ does not necessarily refer to a different data type. It actually refers to any other data domain, which may have a different distribution, and therefore, is likely to invalidate the trained state of the index.

I am not sure whether the same concern applies when creating a new index for the same data set using a different quantizer, but I suspect it would also have to be trained again.

**Comment by ava57r** [comment]
Thanks you.
