### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by NeverInAsh** [facebookresearch/faiss#1736]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [- ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ -] Python

# Reproduction instructions

I am following instructions for installation of faiss on 
https://github.com/facebookresearch/faiss/blob/master/INSTALL.md

to install faiss on windows.

But I am unable to load windows  and I am getting the following error. Something strange is happening i only install faiss-cpu but faiss package is automatically getting installed. Why is that happening ?

```
ImportError                               Traceback (most recent call last)
~\Anaconda3\lib\site-packages\faiss\loader.py in <module>
     33         logger.info("Loading faiss.")
---> 34         from .swigfaiss import *
     35 

~\Anaconda3\lib\site-packages\faiss\swigfaiss.py in <module>
     12 if __package__ or "." in __name__:
---> 13     from . import _swigfaiss
     14 else:

ImportError: DLL load failed: The specified module could not be found.
```

**Comment by h-vetinari** [comment]
> Something strange is happening i only install faiss-cpu but faiss package is automatically getting installed.

Could you share the outputs of `conda list` and `conda info`? It sounds like you're actually pulling in a package from the conda-forge, where `faiss-cpu` is just a compatibility wrapper around `faiss` (and the cpu-information is encoded in the build-string).

If this is failing in an existing environment, it may also make sense to try again by testing it with the creation of a new environment, e.g. `conda create -n my_new_environment -c pytorch faiss-cpu python=3.8`. I just tested that, and `import faiss` succeeds.

**Comment by NeverInAsh** [comment]
I realize where the error was , it came when i was planning to use pyserini. It has overwritten the python package installed from conda.
https://github.com/castorini/pyserini/issues/403

Thanks @h-vetinari
