### ISSUE TITLE
How can I set ClusteringParameters for GpuIndexIVFFlat  in python ?

### ISSUE THREAD

**Issue by djy4713** [facebookresearch/faiss#174]

**Comment by mdouze** [comment]
Hi 

with eg. `index.cp.niter = 50`

**Comment by djy4713** [comment]
but on gpu edition, it can not work.   eg. GpuIndexIVFFlat object.
I just modify the GpuIndexIVF.h file, change the "cp_" variable from projected to public and recompile, then i can work.  eg. gpu_index.cp_.niter = 50

**Comment by wickedfoo** [comment]
I am changing the GPU code to expose ClusteringParameters in the same way as the CPU code, as a public member. Once the push is made, you should be able to just use `index.cp`.

**Comment by djy4713** [comment]
thank you.

**Comment by mdouze** [comment]
Ok, the push is done in the latest Faiss version.

**Comment by mdouze** [comment]
Seems to solve the problem. Closing.
