### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '_swigfaiss.so'

### ISSUE THREAD

**Issue by KinglittleQ** [facebookresearch/faiss#1743]
# Summary

When compiling from source following the instructions in INSTALL.md, the following error occurred:
``` shell
$ python setup.py install                                                    
Traceback (most recent call last):
  File "setup.py", line 22, in <module>                                      
    shutil.copyfile(f"{prefix}_swigfaiss{ext}", f"faiss/_swigfaiss{ext}")
  File "/opt/conda/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '_swigfaiss.so'
```
The CMake/make part passed but the Python setup failed.

# Platform

OS: 

Faiss version: 

Installed from: compiled from source

Faiss compilation options: 

cmake -B build -DCMAKE_BUILD_TYPE=Release -DFAISS_OPT_LEVEL=avx2 -DFAISS_ENABLE_GPU=OFF -DMKL_LIBRARIES=/opt/conda/lib -DPython_EXECUTABLE=$(which python)

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

 

``` shell
cmake -B build -DCMAKE_BUILD_TYPE=Release -DFAISS_OPT_LEVEL=avx2 -DFAISS_ENABLE_GPU=OFF -DMKL_LIBRARIES=/opt/conda/lib -DPython_EXECUTABLE=$(which python)
make -C build -j faiss
make -C build -j swigfaiss
cd build/faiss/python
python setup.py install
```

**Comment by KinglittleQ** [comment]
https://github.com/facebookresearch/faiss/blob/f2464141a7e15e9e201de84eeb360955aa229364/faiss/python/CMakeLists.txt#L65

This line of code makes the installation failed. Removing it could fix the problem.

**Comment by mdouze** [comment]
Ah right, that's an artifact of the previous AVX2 fix... @beauby how could we handle this?

**Comment by KinglittleQ** [comment]
Solved by https://github.com/facebookresearch/faiss/pull/1746.
