### ISSUE TITLE
Accelerate searching in HNSW with _mm_prefetch

### ISSUE THREAD

**Issue by KinglittleQ** [facebookresearch/faiss#1747]
# Summary

According to [ann-benchmarks](https://github.com/erikbern/ann-benchmarks), there is a gap between the HNSW implementation of faiss and hnswlib. It may due to the lack of optimization on graph traversal using `_mm_prefetch` instruction. The performance of searching could be improved by prefetching the vectors which will be visited in the next step into the cache.

Faiss is designed as a layer-by-layer structure which makes it possible to combine different indexes in a flexible way. However, the higher layer of the index cannot access the underlying data directly. I think it is the main reason why `_mm_prefetch` is not used in the implementation of HNSW.

To access the underlying data in `IndexFlat`, I think the most convenient way is to add a member function such as `float *data_hint(idx_t i)` to `DistanceComputer` and implement it in `FlatL2Dis` and `FlatIPDis` which will be passed into `IndexHNSW` in searching. To make `IndexHNSW` compatible with other underlying indexes such as `IndexPQ` and `IndexSQ`, the original `search()` method could be renamed to a template internal function: `template <bool prefetch> search_internal()`. And then we could call it in `search()` and decide to use or not use the prefetch instruction by the template argument without any overhead according to the type of the underlying index.

I am here to consult your opinions. Do you think it is a workable solution?

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
Thanks for the analysis.
To be honest, I wanted to avoid adding these mm_prefetch because it is quite ugly in the original code. 
At the very least I think a first step would be to crudely add mm_prefetch instructions in a non-generic manner and time the improvement in runtime.
