### ISSUE TITLE
GpuIndex initialization takes a long time on Jetson nano

### ISSUE THREAD

**Issue by microyybar** [facebookresearch/faiss#1748]
idx = faiss.GpuIndexIVFPQ(res, d, nlist, M, nbits,faiss.METRIC_L2, config) takes 18minutes.
How to shorten the time?

runing on 
jetson nano 
JetPack 4.4.1
CUDA 10.2

**Comment by mdouze** [comment]
May be related to cuda cache in ~/.nv
see https://github.com/facebookresearch/faiss/issues/1177

**Comment by dantegd** [comment]
Funnily just opened an issue in the feedstock repo that I think is the same,and we're seeing in cuML. The issue incldues a repro for Turing using the CUDA 11 conda-forge package: https://github.com/conda-forge/faiss-split-feedstock/issues/36, 

But in general it looks like the conda-forge packages are doing JIT compilation for every architecture except the latest one of that CUDA version.
