### ISSUE TITLE
[Question] add_with_ids error

### ISSUE THREAD

**Issue by SJP8530** [facebookresearch/faiss#1750]
# Summary

index.add_with_ids works fine at first (before saving index on hard drive)

After i save the index on hard drive, and when trying to load the index on gpu and use add_with_ids again. It doesn't work.

# Platform

OS: Ubuntu 18.04.3 LTS

Faiss version: Faiss-gpu 1.7.0

Installed from: pip install faiss_gpu

Running on:
- [ ] CPU
- [*] GPU

Interface: 
- [ ] C++
- [*] Python

# Reproduction instructions

**initial Faiss save code**

res = faiss.StandardGpuResources()
cpu_index = faiss.index_factory(96, "OPQ48,IVF262144_HNSW32,PQ48x8", faiss.METRIC_INNER_PRODUCT)

vectors_np = np.asarray(vectors, dtype = np.float32)
faiss.normalize_L2(vectors_np)
ids = np.asarray(indexes, dtype = np.int64)

cpu_index = faiss.IndexIDMap2(cpu_index)
index = faiss.index_cpu_to_gpu(res, 0, cpu_index)
index.train(vectors_np)
index.add_with_ids(vectors_np, ids)   #works fine

cpu_index = faiss.index_gpu_to_cpu(index)
faiss.write_index(cpu_index, "FAISS.index")

**loading index and using add_with_ids again code**

cpu_index = faiss.read_index("FAISS.index", faiss.METRIC_INNER_PRODUCT)
index = faiss.index_cpu_to_gpu(res, 0, cpu_index)

faiss_input_ids = np.asarray(faiss_input_ids, dtype = np.int64)
faiss_input_vectors_np = np.asarray(faiss_input_vectors_np, dtype = np.float32)
faiss.normalize_L2(faiss_input_vectors_np)
       
index.add_with_ids(faiss_input_vectors_np, faiss_input_ids)

**ERROR message**
Faiss assertion 'indices->numVecs == oldNumVecs' failed in int faiss::gpu::IVFBase::addVectors(faiss::gpu::Tensor<float, 2, true>&, faiss::gpu::Tensor<long int, 1, true>&) at /__w/faiss-wheels/faiss-wheels/faiss/faiss/gpu/impl/IVFBase.cu:569
2021-03-09 07:11:55,178 WARNING worker.py:1107 -- A worker died or was killed while executing task cc0320e00aa0584cffffffffffffffffffffffff01000000.

**Comment by SJP8530** [comment]
faiss_input_ids.shape                   (n, )
faiss_input_vectors_np.shape      (n, 96)

**Comment by mdouze** [comment]
Before looking further, why use an IndexIDMap2 on top of an IVF index? 
add_with_ids works directly on the cpu_index from index_factory.

**Comment by SJP8530** [comment]
Before looking further, why use an IndexIDMap2 on top of an IVF index?
add_with_ids works directly on the cpu_index from index_factory.
>>>> 
I didn't know add_with_ids works directly on index_factory without using IndexIDMap2. I revised my code. thank you.

But even with revised code, when (1) read saved index, (2) load it on gpu, and (3) add any vectors on loaded index it shows same errors again. (with cpu version, it works fine. but after loading the index on gpu and add vectors, it shows errors)

Below are my codes.


**CODE**
import numpy as np
import faiss
import os

## SAVING FAISS INDEX CODE
vectors_np = np.random.rand(1000000, 96).astype(np.float32)
faiss.normalize_L2(vectors_np)

ids = np.arange(1, 1000000000, 35)
ids = ids[:1000000].astype(np.int64)

res = faiss.StandardGpuResources()
cpu_index = faiss.index_factory(96, "OPQ48,IVF262144_HNSW32,PQ48x8", faiss.METRIC_INNER_PRODUCT)
index = faiss.index_cpu_to_gpu(res, 0, cpu_index)
index.train(vectors_np[:300000])
index.add_with_ids(vectors_np, ids)

cpu_index = faiss.index_gpu_to_cpu(index)
faiss.write_index(cpu_index, "saved.index")


## LOADING FAISS INDEX CODE
cpu_index2 = faiss.read_index("saved.index", faiss.METRIC_INNER_PRODUCT)
index2 = faiss.index_cpu_to_gpu(res, 0, cpu_index2)

new_add_vectors = np.random.rand(5, 96).astype(np.float32)
new_add_ids = np.asarray([2, 3, 4, 5, 6], dtype = np.int64)


cpu_index2.add_with_ids(new_add_vectors, new_add_ids) # NO ERROR
index2.add_with_ids(new_add_vectors, new_add_ids)    # ERROR

**ERROR MESSAGE**
WARNING clustering 300000 points to 262144 centroids: please provide at least 10223616 training points

Faiss assertion 'indices->numVecs == oldNumVecs' failed in int faiss::gpu::IVFBase::addVectors(faiss::gpu::Tensor<float, 2, true>&, faiss::gpu::Tensor<long int, 1,true>&) at /__w/faiss-wheels/faiss-wheels/faiss/faiss/gpu/impl/IVFBase.cu:569
Aborted (core dumped)

**Comment by ithanwu** [comment]
is this issue solved ?
I meet the same error , any help ?

**Comment by wickedfoo** [comment]
I believe this particular bug is the same as that fixed in https://github.com/facebookresearch/faiss/pull/2263
