### ISSUE TITLE
Problem with '_swigfaiss' during 'faiss' installation

### ISSUE THREAD

**Issue by OlegIvanytskyi** [facebookresearch/faiss#1755]
# Summary
I encountered troubles while importing `faiss` after its successful installation with conda. 

# Platform

OS: Windows 10 Home

Faiss version: 1.7.0

Installed from:  `conda install -c pytorch faiss-cpu`

Running on:
- CPU

Interface: 
- Python

# Reproduction instructions

I have installed faiss as described in the [official tutorial](https://github.com/facebookresearch/faiss/blob/master/INSTALL.md) using the following command:
`conda install -c pytorch faiss-cpu`. 
The installation completed successfully, but then I get the following problem when I try `import faiss`:
 
> Traceback (most recent call last):
  File "C:\Users\Oleg\anaconda3\lib\site-packages\faiss\loader.py", line 34, in <module>
    from .swigfaiss import *
  File "C:\Users\Oleg\anaconda3\lib\site-packages\faiss\swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: DLL load failed while importing _swigfaiss: The specified module could not be found.

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import faiss
  File "C:\Users\Oleg\anaconda3\lib\site-packages\faiss\__init__.py", line 17, in <module>
    from .loader import *
  File "C:\Users\Oleg\anaconda3\lib\site-packages\faiss\loader.py", line 39, in <module>
    from .swigfaiss import *
  File "C:\Users\Oleg\anaconda3\lib\site-packages\faiss\swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: DLL load failed while importing _swigfaiss: The specified module could not be found.

When I try `import _swigfaiss` separately, it gives me:

> Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import _swigfaiss
ModuleNotFoundError: No module named '_swigfaiss'

What am I doing wrong? Should I install `_swigfaiss` separately? Any help would be appreciated!

**Comment by arikanev** [comment]
Try these: 
https://github.com/facebookresearch/faiss/issues/821#issuecomment-573531694
https://github.com/facebookresearch/faiss/issues/821#issuecomment-490869666
https://github.com/facebookresearch/faiss/issues/821#issuecomment-621020327

Often just googling your problem with a little attention will help you find solutions/potentially make everything work

**Comment by OlegIvanytskyi** [comment]
Okay, well, I did google the problem and found these answers. However, I installed faiss with `conda install -c pytorch faiss-cpu`, and there is nothing written about `libopenblas-dev` or `libomp-dev` in the [installation guide](https://github.com/facebookresearch/faiss/blob/master/INSTALL.md). Do I still have to install these even when using conda for installation? And if yes, are these tools available for Windows?

**Comment by arikanev** [comment]
I would suggest you Conda uninstall and then reinstall with pip including those dependencies that are available to windows of course - they are C or C++ libraries (can't remember which). See if the pure pip install still throws those errors

**Comment by OlegIvanytskyi** [comment]
From what I have read about these tools, to make them work on Windows, I have to install [OpenBlas](https://www.openblas.net/) and [OpenMP](https://stackoverflow.com/questions/11079586/getting-started-with-openmp-install-on-windows). Their installation looks a bit messy and complicated for me, and, unfortunately, I don't have a possibility to try them out now (not without knowing that everything will indeed work). 
I have also tried WSL, and everything works fine there. It looks like the difficulties arise only on Windows. 
It would probably be great to include the information about `libopenblas-dev` and `libomp-dev` in the installation guide, as it can really be confusing.
Anyway, thank you, @arikanev, for your help!

**Comment by arikanev** [comment]
np

**Comment by arikanev** [comment]
found this too: conda install -c menpo openblas https://stackoverflow.com/questions/45722188/tutorial-for-installing-numpy-with-openblas-on-windows

**Comment by pengfei-chen** [comment]
well, I solve the problem by  starting my  jupyter notebook  througt  Anaconda  Prompt,  rather than  use cmd , jupyter notebook.
It did work!   Maybe  because  the base environment... Hope this can help you.

**Comment by kamraz** [comment]
> well, I solve the problem by "conda install faiss-cpu -c pytorch" ,and then starting my jupyter notebook through Anaconda Prompt, rather than use cmd , jupyter notebook.
> It did work! Maybe because the base environment... Hope this can help you.
> 
> update:
> A new conda env also can fix this problem~

This was a life saver. Using the anaconda prompt and a fresh env fixed everything

**Comment by Wang-Yu-Qing** [comment]
I solved the problem by this: `conda install -c conda-forge faiss`

https://stackoverflow.com/questions/65338966/windows-import-faiss-errordll-load-failed
