### ISSUE TITLE
[Question] On-Disk Index

### ISSUE THREAD

**Issue by lynnliu030** [facebookresearch/faiss#1757]
# Summary
I have some questions related to the on-disk index.
1. Is splitting the dataset, adding subset of it to different indices, and using merge_ondisk to merge them the only way to create on-disk index? 
3. If I don't want to mmap the on-disk data but instead want to read the on-disk data into memory when needed, what are the files that I should look at and what are the methods to change? I am currently looking at OnDiskInvertedList.h and OnDiskInvertedList.cpp

**Comment by mdouze** [comment]
1. no it can also be created by add but merging is faster
2. the OS decides
3. The best way to do this is probably to just implement another ReadOnlyInvertedLists class and implement the get_codes / get_ids functions there 
https://github.com/facebookresearch/faiss/blob/master/faiss/invlists/InvertedLists.h#L227
