### ISSUE TITLE
How to assign GPU id to GpuIndexFlatL2?

### ISSUE THREAD

**Issue by shipra25jain** [facebookresearch/faiss#1759]
Hello,
I want to run 4 different GpuIndexFlatL2 in parallel on 4 different GPUs. However, all indexes are being created on the one with gpu_id=0. How can I assign device or gpu id when creating index using GpuIndexFlatL2() or allocating GPU resources StandardGPUResources()?

Thank you

**Comment by wickedfoo** [comment]
Set `device` in the `GpuIndexFlatConfig` that is passed to the constructor of `GpuIndexFlatL2` to your preferred device.
