### ISSUE TITLE
How to use ```IndexIVFFlat``` index on large dataset

### ISSUE THREAD

**Issue by macomzzl** [facebookresearch/faiss#176]
1. I notice that ```IndexIVFFlat``` index has ```train``` and ```add``` stages. But on large dataset, I can not load the dataset all in the memory, so can I split the dataset to pieces, and continually train and add for each piece, just like this:
```
index = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_L2)
for piece in dataset.getNextPiece():
     index.train(piece)
     index.add(piece)
```
Is it right?
2. And another question is whether faiss can search in the way of the range of L2(or cosin). For example,  search all vectors where the value of cosin >= threshold?

**Comment by wickedfoo** [comment]
1. The index can only be trained once on one set of data; the training fixes the partitioning and quantization and other parameters, so the train set should hopefully be representative of the statistics of the entire set. Each call to train after the first does nothing in your example. You can incrementally add to an index, though.

2. `range_search` is supposed to do this, but this feature is not fully supported, and isn't for many indices.
