### ISSUE TITLE
Can someone let me know how is faiss to be installed with MKL in CPU only mode??

### ISSUE THREAD

**Issue by chirupan** [facebookresearch/faiss#1760]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by chirupan** [comment]
Everytime I try compiling faiss with the below flags, I receive undefined reference to ''sgemm_" error.
export MKL_HOME=/opt/intel/compilers_and_libraries/linux/mkl/lib/intel64
cmake -B build . -DFAISS_OPT_LEVEL=avx2 -DBLA_VENDOR=Intel10_64_dyn -DFAISS_ENABLE_GPU=OFF DCMAKE_BUILD_TYPE=Release -DMKL_LIBRARIES=$MKL_HOME/libmkl_core.a $MKL_HOME/libmkl_intel_lp64.a  $MKL_HOME/libmkl_gnu_thread.a

**Comment by user-ZJ** [comment]
I got the same problem. Do you have any solution?

**Comment by chirupan** [comment]
I managed to compile mkl later using the below  :-

Just add MKL libs path (/opt/intel/compilers_and_libraries/linux/mkl/lib/intel64) to LD_LIBRARY_PATH in .bashrc in home directory.

First login as root usind (sudo -s )and then only run below cmake command to compile with cmake

cmake -B build . -DFAISS_ENABLE_GPU=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release 

This will automatically find MKL libs and compile faiss.


make -C build -j faiss

make -C install faiss
