### ISSUE TITLE
[Question] Low Performance of 4-bit PQ

### ISSUE THREAD

**Issue by QwertyJack** [facebookresearch/faiss#1761]
# Summary

I'm trying to reproduce 4-bit PQ benchmark on SIFT1M (mentioned [here](https://github.com/facebookresearch/faiss/wiki/Indexing-1M-vectors#4-bit-pq-comparison-with-scann)). The result on Wiki says QPS is over 10000 with recall > 0.9. However, I only get QPS 8000 with a very low recall on my Intel(R) i7-8700 desktop. I wonder if I missed some sth.

Here is my testing code:

```python
# load dataset
xb = np.load('xb.npy')
xq = np.load('xq.npy')
d = 128

index = faiss.index_factory(d, 'IVF2000,PQ64x4fs')
index.train(xb)
index.add(xb)
index.nprobe = 1 # set nprobe to 1 to achieve max performance

faiss.omp_set_num_threads(1) # single thread

%timeit index.search(xq, 100)

# output
# 
# 1.7 s ± 31.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
# qps = xq.shape[0] / 1.7 = 5882.3529
```

**Comment by mdouze** [comment]
There is an issue with the compilation of the AVX2 conda packages. 
See #1711

**Comment by QwertyJack** [comment]
Thanks.
