### ISSUE TITLE
scikit-learn implementation vs faiss implementation

### ISSUE THREAD

**Issue by abhipn** [facebookresearch/faiss#1763]
I have never used faiss before, I heard the kmeans implementaion of faiss is faster than scikit-learn.

Here's the basic code that I had used. 

```
import faiss

class FaissKMeans:
    def __init__(self, n_clusters=200000, n_init=2, max_iter=500):
        self.n_clusters = n_clusters
        self.n_init = n_init
        self.max_iter = max_iter
        self.kmeans = None
        self.cluster_centers_ = None
        self.inertia_ = None

    def fit(self, X):
        self.kmeans = faiss.Kmeans(d=X.shape[1],
                                   k=self.n_clusters,
                                   niter=self.max_iter,
                                   nredo=self.n_init,
                                   gpu=True,
                                   verbose=True)
        self.kmeans.train(X.astype(np.float32))
        self.cluster_centers_ = self.kmeans.centroids
        self.inertia_ = self.kmeans.obj[-1]

    def predict(self, X):
        return self.kmeans.index.search(X.astype(np.float32), 1)[1]

kmeans = FaissKMeans(n_clusters=200000, max_iter=500, n_init=2)
kmeans.fit(sentence_embeddings)

WARNING clustering 271425 points to 200000 centroids: please provide at least 7800000 training points
Clustering 271425 points in 768D to 200000 clusters, redo 2 times, 500 iterations
  Preprocessing in 0.08 s
Outer iteration 0 / 2

 Iteration 39 (1244.95 s, search 1229.47 s): objective=1.66762e+06 imbalance=1.258 nsplit=0
```

So I never got such warning in scikit-learn implementation, and wanted to know will there be any issue due to this warning? 

I have read that kmeans implementation sub-samples the training set and to overcome this I have to use `max_points_per_centroid=271425`, do I set it as argument in `faiss.Kmeans`. Any example would help. 

Finally, I need some clarification about `imbalance`, what exactly an imbalance mean here?

Any support is appreciated.

**Comment by wickedfoo** [comment]
Yes, the disadvantage is that the number of clusters being produced is about the same as the number of vectors that you are using for clusters, so it isn't really clustering the dataset by much (they will be low quality). The warning is that it wants you to use at least 7800000 / 200000 = 39 vectors per cluster being trained.

Imbalance is the degree to which the 200000 clusters being produced is imbalanced; i.e., the max difference between the cluster that clusters the largest number of vectors and the smallest number of ones. In this case, there is a 1.258x difference between the two. Good clusters should evenly partition the dataset as best as possible (imbalance closer to 1.0 is best).
