### ISSUE TITLE
Is there way to make the  dataset.add_faiss_index faster ? 

### ISSUE THREAD

**Issue by shamanez** [facebookresearch/faiss#1767]
# Summary

Mt dataset contains 30 million vectors and I am using faiss combined with the hugingface datasets library.  I want to iteratively update the dataset index in a training loop, let's save every N number of training steps.  At the moment add_index takes a lot of time to compute. Sometimes 8 hours depending on the other CPU processes. Is there a way I can make the process faster? 

Here's the code I have taken from [here](https://github.com/huggingface/transformers/blob/master/examples/research_projects/rag/use_own_knowledge_dataset.py).

```
    # Let's use the Faiss implementation of HNSW for fast approximate nearest neighbor search
    index = faiss.IndexHNSWFlat(index_hnsw_args.d, index_hnsw_args.m, faiss.METRIC_INNER_PRODUCT)
    dataset.add_faiss_index("embeddings", custom_index=index)
```

# Platform

Anaconda -faiss

OS:  Ubuntu 20.04

Faiss version: v1.7.0

Installed from:  anaconda 

Running on:
- [ X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ X] Python

# Reproduction instructions

 [Huggiface RAG script](https://github.com/huggingface/transformers/blob/master/examples/research_projects/rag/use_own_knowledge_dataset.py).

**Comment by QwertyJack** [comment]
HNSW is quite slow for 30 million vectors. IVF index should work fine.
BTW, you can try other HNSW implementation, i.e. hnswlib, n2.

**Comment by shamanez** [comment]
@QwertyJack 

Hi I am really new to Faiss indexes. So I am really sorry if I ask very basic questions.

I am mainly asking about the add_index part and not about the actual retrieval/search part.  Currently, my add_index process takes around 5-8 hours.  So what you are saving is to change the type of index in the following line right?

`index = faiss.IndexHNSWFlat(index_hnsw_args.d, index_hnsw_args.m, faiss.METRIC_INNER_PRODUCT)
`

Could you please show me how to change this line, atm I am finding it hard to assign a new index.

**Comment by mdouze** [comment]
HNSW is indeed slow at add time. You may want to look into 
https://github.com/facebookresearch/faiss/wiki/Faster-search

**Comment by shamanez** [comment]
@mdouze 

So you are saying to modify the index with the following lines right?

```
quantizer = faiss.IndexFlatL2(d)  # the other index
index = faiss.IndexIVFFlat(quantizer, d, nlist)
```

**Comment by shamanez** [comment]
@mdouze  How to chose the nlist parameter ? I am really struggling.

**Comment by QwertyJack** [comment]
> @mdouze How to chose the nlist parameter ? I am really struggling.

Check this: [Guidelines to choose an index](https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index)

Generally speaking `nlist=262144` should be fine. However, from my experience a lower `nlist` would provide a higher recall.

**Comment by shamanez** [comment]
@QwertyJack  Thanks a lot.

Any idea on what would be a good value for nprobe parameter?

**Comment by QwertyJack** [comment]
`nprobe` is the balance factor between efficiency and recall. The general rule is, 'the higher the recall, the lower QPS', and vice versa. Try different params (e.g. `nprobe = 1,2,4,8,16,32,64,128,256,512,...`) and find **your's** sweet points.

**Comment by shamanez** [comment]
thanks a lot.
