### ISSUE TITLE
Python error: Assertion `ci >= 0 && ci < k' fails when training IndexIVFPQ on the GPU

### ISSUE THREAD

**Issue by SMaharajah** [facebookresearch/faiss#177]
Hi there, 

I'm attempting to train Faiss's IndexIVFPQ on the GPU with a small number (25000) of vectors for visual similarity search.  Unfortunately I receive the following error while attempting to train the Faiss index:

```python: utils.cpp:1391: int faiss::km_update_centroids(const float*, float*, long int*, size_t, size_t, size_t): Assertion `ci >= 0 && ci < k' failed. ```

Here's what our code looks like:

```
GPU = True
centroids, d, m, bits = 256, 128, 16, 8
quantizer = faiss.IndexFlatL2(d)
index_ = faiss.IndexIVFPQ(quantizer, d, centroids, m, bits)

if GPU:
    # convert index to gpu
    res = faiss.StandardGpuResources()
    co = faiss.GpuClonerOptions()
    co.useFloat16 = True
    index_ = faiss.index_cpu_to_gpu(res, 0, index_, co)

assert (not index_.is_trained)
index_.train(vectors)  # only when GPU == True, error happens here
assert (index_.is_trained)

if GPU:
    index_ = faiss.index_gpu_to_cpu(index_)

faiss.write_index(index_, '/tmp/trained.index'))
```

Oddly, when my flag `GPU` is set to `False`, this assertion error doesn't occur; the training works just fine on the CPU.  It seemed odd that an illegal value of ci or k would occur only while training on the gpu.  My machine is CUDA-enabled, and running the test script `./gpu/test/demo_ivfpq_indexing_gpu` succeeds without the mentioned assertion error. Are my parameter choices and my usage okay?

**Comment by wickedfoo** [comment]
Do you have any NaN values in the training data?

I think this usually occurs when the input is partially garbage.

**Comment by SMaharajah** [comment]
Thank you for the response! 

Just checked and, no, `vectors` has no NaNs or infs in it.

But to be extra sure, I randomly generated a data array of the same shape with the following script and the same behavior happened:  when I use **CPU** it works fine, but when I use **GPU** the assertion error crashes the program.

Are you able to reproduce the error?

```
import numpy as np
import faiss

np.random.seed(123)
r = np.random.randn(25000*128)
r = r.reshape(25000, 128)

vectors = r.astype(np.float32)

GPU = True
centroids, d, m, bits = 256, 128, 16, 8
quantizer = faiss.IndexFlatL2(d)
index_ = faiss.IndexIVFPQ(quantizer, d, centroids, m, bits)

if GPU:
    # convert index to gpu
    res = faiss.StandardGpuResources()
    co = faiss.GpuClonerOptions()
    co.useFloat16 = True
    index_ = faiss.index_cpu_to_gpu(res, 0, index_, co)

assert (not index_.is_trained)
index_.train(vectors)  # only when GPU == True, error happens here
assert (index_.is_trained)

if GPU:
    index_ = faiss.index_gpu_to_cpu(index_)

faiss.write_index(index_, '/tmp/trained.index')

```

**Comment by wickedfoo** [comment]
Try removing the `co.useFloat16 = True` line and see if it reproduces.

Did you mean to perform the math in float16?

**Comment by wickedfoo** [comment]
What kind of GPU do you have?

**Comment by SMaharajah** [comment]
It's an NVIDIA gpu.

lspci tells me `NVIDIA Corporation GP106M [GeForce GTX 1060 Mobile]`

removing `co.useFloat16 = True` doesn't change the behavior for me :confused:

**Comment by SMaharajah** [comment]
It's probably just a quirk in my local installation.  Was able to run the code without a problem on an Amazon VM.

Thank you for your help @wickedfoo !
