### ISSUE TITLE
Apple M1 support on conda packages

### ISSUE THREAD

**Issue by fredericokremer** [facebookresearch/faiss#1773]
Any plans to release conda packages compatible with Apple M1 processors?

**Comment by mdouze** [comment]
`conda` does not currently support ARM, so it would be hard.
Compiling on ARM is supported though (tested on Linux).

**Comment by fredericokremer** [comment]
Miniforge already has a support for MacOS ARM, but there's no available installation candidate for `faiss-cpu` using the command:

```
$ conda install -c pytorch faiss-cpu
```

The `pytorch` channel works on MacOS ARM miniforge, and even PyTorch itself can be installed (and works). Therefore i guess the one missing part is the compiled package for `faiss-cpu` to be available on the channel and the platform to be listed as supported.

**Comment by fredericokremer** [comment]
The following error occurred when i was trying to build from source.

Commands:

```
cmake -B build . -DFAISS_ENABLE_GPU=OFF
cd build
make
```

Log: [make_log.txt](https://github.com/facebookresearch/faiss/files/6184765/make_log.txt)

**Comment by h-vetinari** [comment]
> `conda` does not currently support ARM, so it would be hard.

conda-forge builds packages for osx-arm (which corresponds to M1), so it's definitely possible. I haven't investigated why OSX-ARM migrator hasn't made it to the faiss feedstock yet, but since the osx builds run fine, I see no fundamental problem in building those packages.

**Comment by fredericokremer** [comment]
good to know! can you verify it @h-vetinari? i would be awesome to be able to run the project i'm creating on top of FAISS on my new macbook 😄

**Comment by h-vetinari** [comment]
See https://github.com/conda-forge/faiss-split-feedstock/issues/38 - the osx-arm migrator is opt-in apparently. I can get some builds running, and it would be cool if you could test them (conda-forge just cross-compiles, but has no M1's in CI to run tests).

**Comment by fredericokremer** [comment]
Awesome! I will test them as soon as they become available for installation. Thanks @h-vetinari!

**Comment by h-vetinari** [comment]
So, I'm looking at this in https://github.com/conda-forge/faiss-split-feedstock/pull/39, but there's the issue that OSX-ARM is only supported on clang >=11, but that creates a problem with faiss currently, see #1696.

That in itself shouldn't stop us from having a test-build for osx-arm, but there's also some current cmake issues apparently with osx-arm, and cmake 3.20 seems to have come out with a bunch of regressions, so waiting for a newer build on that before I try to debug stuff I don't understand on a machine I don't have 😅

**Comment by h-vetinari** [comment]
OK @fredericokremer, there's now a build for M1 after all, but so far only as a build artefact of a PR on the feedstock repo. Considering that the test suite crashes under vanilla osx when compiled with clang 11 (xref #1696), I'm not comfortable in merging this yet, but would be happy to have you test it as follows:

Go to the [artefact page](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=296786&view=artifacts&pathAsName=false&type=publishedArtifacts) of the CI for https://github.com/conda-forge/faiss-split-feedstock/pull/39, download the one for `osx-arm64` and unpack it somewhere locally.

If you don't have `conda build` installed, you can create an environment like this `conda create -n builder conda-build` & `conda activate builder`. Then run `conda build --test <path/to/unpacked/folder/>/osx-arm64/faiss-1.7.0-py38h<hash>_cpu.tar` (you can adapt the python version obviously) and post the results here. If that doesn't work for reasons unrelated to the test suite, there's one other way to test it, but the above should be the easiest.

**Comment by h-vetinari** [comment]
@fredericokremer, did you have a chance to test the osx-arm64 [artefact](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=302173&view=artifacts&pathAsName=false&type=publishedArtifacts) from https://github.com/conda-forge/faiss-split-feedstock/pull/39?

**Comment by h-vetinari** [comment]
Someone from conda-forge helped me run the test suite for the artefact on an M1, and it also runs into #1696. Therefore, support for M1 is blocked on that issue.

**Comment by debanjum** [comment]
@h-vetinari clang 12 seems to be available for m1 mac (osx-arm64) in [conda-forge](https://anaconda.org/conda-forge/clang). Does that unblock this issue?

**Comment by h-vetinari** [comment]
Hey @debanjum, I know, I was quite [involved](https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/63#issuecomment-877005303) in that. 🙃 

I haven't had the time to play around with this on the faiss feedstock yet, unfortunately.

**Comment by debanjum** [comment]
Yeah, I realized that after I'd already posted! Let me know if and how I can help (though I don't have much experience with creating conda packages)

**Comment by h-vetinari** [comment]
I pushed an update to https://github.com/conda-forge/faiss-split-feedstock/pull/39; once it runs through (assuming no new compilation problems), I'd need someone with an M1 to run the test suite with the produced artefact and see that #1696 is gone.

**Comment by debanjum** [comment]
Hey @h-vetinari, I can help out with the testing but the [build artefacts](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=391245&view=artifacts&pathAsName=false&type=publishedArtifacts) are gone. Could you re-trigger the build?

**Comment by h-vetinari** [comment]
> 
> 
> Hey @h-vetinari, I can help out with the testing but the [build artefacts](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=391245&view=artifacts&pathAsName=false&type=publishedArtifacts) are gone. Could you re-trigger the build?

That's cool, thanks. I'm happy to retrigger a build, but someone from conda-forge tested it already, and there are some code signing [issues](https://github.com/conda-forge/faiss-split-feedstock/pull/39#issuecomment-953565370) (which only affects osx-arm) that I haven't been able to debug.

**Comment by rmwise** [comment]
I've created another terminal with rosetta and intel architecture on it. Even created a conda environment with other architecture but I'm still having errors when running `jupyter lab` with the code inside

**Comment by hiroalchem** [comment]
Is there any update on faiss install via conda? I am currently having problems installing faiss on my M1 mac, and considering the dependency with other libraries, it would be great if it were possible to install via conda.

**Comment by h-vetinari** [comment]
I can reactivate that PR, but last time it kept consistently running into some problem uncovered (or caused by) using newer compilers, and I'll need someone with an M1 to test the artefacts before we release anything

**Comment by mdouze** [comment]
I managed to compile a Faiss compatible with conda on M1, but outside the conda build system: 

https://gist.github.com/mdouze/2b96e804ee2825e72323c0a296061c7e

**Comment by hiroalchem** [comment]
@h-vetinari I'm a beginner and don't know much about this, but could I try this one? If so, I may be able to do it.
https://github.com/facebookresearch/faiss/issues/1773#issuecomment-942805264

**Comment by hiroalchem** [comment]
@mdouze Thank you. If I use this procedure, will cmake or swig installed with conda be used? If so, it may solve the problem I am having.
I am having trouble with the following error while using faiss.
```
OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/

```

**Comment by h-vetinari** [comment]
> @h-vetinari I'm a beginner and don't know much about this, but could I try this one? If so, I may be able to do it. [#1773 (comment)](https://github.com/facebookresearch/faiss/issues/1773#issuecomment-942805264)

Hey @hiroalchem, you can download the osx-arm64 artefact from [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=564678&view=artifacts&pathAsName=false&type=publishedArtifacts) and try to report the result of the instructions you already found. :)

**Comment by h-vetinari** [comment]
> All tests passed

That looks very good! :)

**Comment by hiroalchem** [comment]
@mdouze I solved the problem I was having by installing numpy swig cmake with conda using the code you showed. Thank you very much.

**Comment by bstadlbauer** [comment]
@h-vetinari Is there an option to re-trigger the build for the ARM artifact? I've checked the link but it seems to be gone. 

Also happy to tests things for osx-arm64 if there is a need. 

> > @h-vetinari I'm a beginner and don't know much about this, but could I try this one? If so, I may be able to do it. [#1773 (comment)](https://github.com/facebookresearch/faiss/issues/1773#issuecomment-942805264)
> 
> Hey @hiroalchem, you can download the osx-arm64 artefact from [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=564678&view=artifacts&pathAsName=false&type=publishedArtifacts) and try to report the result of the instructions you already found. :)

**Comment by snauhaus** [comment]
> I managed to compile a Faiss compatible with conda on M1, but outside the conda build system:
> 
> https://gist.github.com/mdouze/2b96e804ee2825e72323c0a296061c7e

I managed to install using your process. However, faiss still runs into a SIGSEV for me on M1 when accessing the index. 

> Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by h-vetinari** [comment]
We have faiss builds for osx-arm in conda-forge now, I guess this might be why @mdouze closed this. 🙃 

Sorry I forgot to report back. :)
