### ISSUE TITLE
Given id, find a vector 

### ISSUE THREAD

**Issue by lynnliu030** [facebookresearch/faiss#1779]
# Summary
I was wondering whether Faiss provides any API that returns the corresponding vector in the index given the vector id?

**Comment by wickedfoo** [comment]
`reconstruct` / `reconstruct_n` if it is supported on the particular index

https://github.com/facebookresearch/faiss/blob/master/faiss/Index.h#L158

**Comment by wickedfoo** [comment]
if the index is quantized, then it will return a reconstruction of the vector from the quantized data, not the original vector added to the index though

**Comment by QwertyJack** [comment]
For IVF index, don't forget do `index.make_direct_map()` before reconstruction.
