### ISSUE TITLE
D,I returned by index.search is confused

### ISSUE THREAD

**Issue by JJplane** [facebookresearch/faiss#1780]
I am confused about the extreamly large distance result in D, and -1 in I. Is it caused by my data or other reason?
```
D, I = kmeans.index.search(kmeans.centroids, 6)
```
```
print(D)
```
[[0.0000000e+00 3.2298622e+00 1.1269009e+01 3.4028235e+38 3.4028235e+38
  3.4028235e+38]
 [0.0000000e+00 1.1269009e+01 2.5175987e+01 3.4028235e+38 3.4028235e+38
  3.4028235e+38]
 [0.0000000e+00 3.2298660e+00 2.5175987e+01 3.4028235e+38 3.4028235e+38
  3.4028235e+38]]
`print(I)`
[[ 0  2  1 -1 -1 -1]
 [ 1  0  2 -1 -1 -1]
 [ 2  0  1 -1 -1 -1]]

**Comment by wickedfoo** [comment]
https://github.com/facebookresearch/faiss/wiki/FAQ#what-does-it-mean-when-a-search-returns--1-ids
