### ISSUE TITLE
faiss search crash

### ISSUE THREAD

**Issue by xiaoyangxu** [facebookresearch/faiss#1781]
# Summary

Using the addWithIds and search methods of indexIdMap, when the same ID is added multiple times, the search will crash.
The specific problem is fevc_inner_ product this method.

# Platform

linux centos

Installed from: compiled by myself

Running on:
- [ ] CPU

Interface: 
- [ ] C++

**Comment by mdouze** [comment]
Could you post a simple reproduction?

**Comment by xiaoyangxu** [comment]
> Could you post a simple reproduction?

For example, I have one thread searching constantly, another thread is constantly adding, using indexidmap and indexflatip, with a data volume of 1 million.

**Comment by wickedfoo** [comment]
>  one thread searching constantly, another thread is constantly adding

Faiss is not natively thread safe. Are you ensuring mutual exclusion between the two threads so you are not searching and adding at the same time?

**Comment by xiaoyangxu** [comment]
> > one thread searching constantly, another thread is constantly adding
> 
> Faiss is not natively thread safe. Are you ensuring mutual exclusion between the two threads so you are not searching and adding at the same time?

Because our application has real-time update logic, it needs to delete and add in real time. If a read-write lock is added, the query will be affected. I want to know why adding and searching are not thread safe
