### ISSUE TITLE
The difference between Tesla T4 and 1080 in GPUIndexIVFPQ search time

### ISSUE THREAD

**Issue by Aurevoir-68** [facebookresearch/faiss#1785]
# Summary

# Platform

OS: Centos 7.6 （NVIDIA 1080  AND  TESLA T4）

Faiss version: 1.6.3

Installed from:  

Faiss compilation options: docker (CUDA 10.0)

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

 

We have tested 100 million data and established a gpuivfpq index with 2 million data. **We found that the search time of 1080 is 17 ms, and that of TESLA T4  is 20 ms. for 50 indexes, the total time difference is 3 * 50 = 150 ms**. 

The search time of Tesla T4 should be higher than NVIDIA 1080, but it is not reflected here?

It should be noted that other environments are the same, but **the driver of the graphics card is different. The NVIDIA 1080 driver version is 418.67, and the Tesla T4 driver version is 455.45.01**. Will this affect the results?

**Comment by zxzxv522** [comment]
> # Summary
> 
> 
> 
> 
> 
> 
> 
> # Platform
> 
> 
> 
> 
> 
> 
> 
> OS: Centos 7.6 （NVIDIA 1080  AND  TESLA T4）
> 
> 
> 
> Faiss version: 1.6.3
> 
> 
> 
> Installed from:  
> 
> 
> 
> Faiss compilation options: docker (CUDA 10.0)
> 
> 
> 
> Running on:
> 
> - [ ] CPU
> 
> - [x] GPU
> 
> 
> 
> Interface: 
> 
> - [x] C++
> 
> - [ ] Python
> 
> 
> 
> # Reproduction instructions
> 
> 
> 
> 
> 
> 
> 
>  
> 
> 
> 
> 
> 
> We have tested 100 million data and established a gpuivfpq index with 2 million data. **We found that the search time of 1080 is 17 ms, and that of TESLA T4  is 20 ms. for 50 indexes, the total time difference is 3 * 50 = 150 ms**. 
> 
> 
> 
> The search time of Tesla T4 should be higher than NVIDIA 1080, but it is not reflected here?
> 
> 
> 
> 
> 
> 
> 
> It should be noted that other environments are the same, but **the driver of the graphics card is different. The NVIDIA 1080 driver version is 418.67, and the Tesla T4 driver version is 455.45.01**. Will this affect the results?
> 
> 
> 
> 
> 
>
