### ISSUE TITLE
How to get code in IVFPQFastScan?

### ISSUE THREAD

**Issue by dongzhen123** [facebookresearch/faiss#1788]
for IVFPQ,we could get each xb code in first list like:

faiss.rev_swig_ptr(il.get_codes(0),il.list_size(0)*il.code_size)

but for IVFPQFastScan,how to get it,and make it corresponds to each xb.

**Comment by mdouze** [comment]
See

https://github.com/facebookresearch/faiss/blob/master/contrib/inspect_tools.py#L9
