### ISSUE TITLE
why   k and nprobe must be <= 1024 for all indices

### ISSUE THREAD

**Issue by bzwqq** [facebookresearch/faiss#179]
i don't know why the warpselect algorithm in GPU with the limit k<=1024?  the register file is always 32K, much more than 1024 in recent GPU ,right?
in the paper,' Since the register file provides much more storage than shared memory, it supports k ≤1024.'. What does this sentence mean?   the shared memory is almost 48k, the register file is always 32k,isn't it right?
I do not have a special understanding of the GPU, so I checked a lot of information, but still did not  understand clearly. can anybody explain it to me simply and intuitively? very thank you!

**Comment by wickedfoo** [comment]
Register file usage is based on the compiler register allocator and ptxas; Nvidia unfortunately does not give people fine-grained control over it. It depends upon the live ranges of variables and how much unrolling the compiler chooses to do internally.

The register file is 256 KB per SM, up to 255 registers / thread. 255 registers * 4 bytes * 32 threads/warp * 4 warps/block  = 130560 bytes. The most smem that can be reserved per block is 48 KiB.

https://devblogs.nvidia.com/parallelforall/inside-pascal/

k = 1024 gets reasonably close to this limit. k = 2048 is actually possible, but the compiler sometimes chooses to spill into local memory, and it takes forever to compile, so I do not enable this option.

**Comment by bzwqq** [comment]
hi, thank you very much.
 there's still two questions. 1, 4 warps/block? why?  2. i still don't see the limit that cause k=1024?
