### ISSUE TITLE
Change the centroid vectors for GpuIndexIVFPQ?

### ISSUE THREAD

**Issue by jingtaozhan** [facebookresearch/faiss#1795]
The wiki provides a method to change the PQ centroids with python and then write back to Faiss Index object. However, it seems not work with Gpu Index. Is there a way to write back to a GPU index object, specifically, GpuIndexIVFPQ?

**Comment by wickedfoo** [comment]
The only way to serialize a GPU index is to convert it to/from the CPU version at present, sorry.

**Comment by wickedfoo** [comment]
The centroid vectors cannot be changed natively on the GPU side, you'd have to convert to the CPU, re-encode, and then convert back.

**Comment by jingtaozhan** [comment]
Thank you!
