### ISSUE TITLE
IndexPQ.cpp:226: Error: 'is_trained' failed

### ISSUE THREAD

**Issue by yanchao-yu** [facebookresearch/faiss#1796]
# Summary

Error when search for docs

# Platform

OS: Linux

Faiss version: 
- faiss-cpu              1.7.0
- faiss-gpu              1.7.0

Installed from: pip3 install faiss-cpu; pip3 install faiss-gpu

Running on:
- [ ] CPU
- [ √] GPU

Interface: 
- [ ] C++
- [√ ] Python

# Reproduction instructions

I've trained the index: 
`index = index_factory(lang_model.config.hidden_size, args.faiss_factory)`
`  if not index.is_trained:`
`     sentence_embeddings = np.concatenate(temp_emb, 0)`
`      ids = np.concatenate(temp_ids, 0)`
`      index.train(sentence_embeddings)`
`      ids = np.ascontiguousarray(ids)`
`      index.add_with_ids(sentence_embeddings, ids)`
`  else:`
`      # normalize the embeddings`
 `     ids = np.ascontiguousarray(ids.cpu().numpy())`
 `     index.add_with_ids(sentence_embeddings, ids)`

When I search for doc using question embedding:
` question_embedding = self.model(**question_tokens)[0].cpu()`
` question_embedding = np.ascontiguousarray(question_embedding[:, 0, :].numpy())`
` scores, ids = self.index.search(question_embedding, k=top_k)`

it complained like :
`File ".../retrieval/classes.py", line 50, in retrieve`
` scores, ids = self.index.search(question_embedding, k=top_k)`
` File ".../ENV/lib/python3.6/site-packages/faiss/__init__.py", line 144, in replacement_search`
`    self.search_c(n, swig_ptr(x), k, swig_ptr(D), swig_ptr(I))`
`  File ".../ENV/lib/python3.6/site-packages/faiss/swigfaiss.py", line 4832, in search`
`   return _swigfaiss.IndexIDMap_search(self, n, x, k, distances, labels)`
`RuntimeError: Error in virtual void faiss::IndexPQ::search(faiss::Index::idx_t, const float*, faiss::Index::idx_t, float*, ``faiss::Index::idx_t*) const at /__w/faiss-wheels/faiss-wheels/faiss/faiss/IndexPQ.cpp:226: Error: 'is_trained' failed`

**Comment by mdouze** [comment]
Probably an error on your side. Is index = self.index ?
