### ISSUE TITLE
 CPU: Calling faiss.knn with metric_L2 raises: Wrong number or type of arguments for overloaded function 'knn_L2sqr'

### ISSUE THREAD

**Issue by jmnum** [facebookresearch/faiss#1797]
# Summary

CPU version: Calling faiss.knn with metric_L2 raises the following error:

TypeError: Wrong number or type of arguments for overloaded function 'knn_L2sqr'.
  Possible C/C++ prototypes are:
    faiss::knn_L2sqr(float const *,float const *,size_t,size_t,size_t,faiss::float_maxheap_array_t *,float const *)
    faiss::knn_L2sqr(float const *,float const *,size_t,size_t,size_t,faiss::float_maxheap_array_t *)

# Platform

OS: Linux

Faiss version: faiss-cpu 1.7.0

Installed from:  pip install faiss-cpu

Running on:
- [X ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X ] Python

# Reproduction instructions

import numpy as np
import faiss
xb=np.random.rand(1024,8)
xq=np.random.rand(16,8)
faiss.knn(xq,xb,4,distance_type=faiss.METRIC_L2)

**Comment by mdouze** [comment]
Please convert to float32.
