### ISSUE TITLE
Question on the objective of KMeans

### ISSUE THREAD

**Issue by heytitle** [facebookresearch/faiss#1799]
# Summary

Hi, I try to understand the objective returned by `.train(..)`. I think it is the same as [`inertia` in `sklearn`](https://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_stability_low_dim_dense.html). Essentially, this is just sum of squared of each point's distance to its closest centroid.

However, this doesn't seem to be the case. Consider the following set up
```
# taken from https://github.com/facebookresearch/faiss/wiki/Getting-started#in-python
d = 32        
nb = 10000

np.random.seed(1234)
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.

def do_clustering(ncentroids):
  niter = 20
  verbose = True
  kmeans = faiss.Kmeans(d, ncentroids, niter=20, verbose=verbose)
  obj = kmeans.train(xb)
  

  D, I = kmeans.index.search(xb, 1)
  man_obj = np.sum(D)
  print("Number of Clusters", ncentroids)
  print("Objective returned from train(..):", obj)
  print("Objective manually calculated    :", man_obj)

  print("> Are they equal: ", np.isclose(man_obj, obj))
```

What returned by `train.(...)` and what I manually calculated is quite different when I used only a few number of clusters.
```
Number of Clusters 10
Objective returned from train(..): 6794.7568359375
Objective manually calculated    : 26811.812
> Are they equal:  False

Number of Clusters 20
Objective returned from train(..): 13153.4169921875
Objective manually calculated    : 25940.469
> Are they equal:  False

Number of Clusters 300
Objective returned from train(..): 20918.275390625
Objective manually calculated    : 20918.246
> Are they equal:  True

Number of Clusters 500
Objective returned from train(..): 19611.4453125
Objective manually calculated    : 19611.479
> Are they equal:  True
```

Is this behaviour something to do with the relationship between input dimensions `d` and the number of clusters?

# Platform

OS: Colab 

Faiss version: `faiss-cpu-1.7.0`

Installed from: `pip install faiss-cpu`

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
Code for reproducing the results can be found at https://colab.research.google.com/drive/1VZEV79B81hun09T11EugWDYwj6Zgk5Cw?usp=sharing

**Comment by mdouze** [comment]
The kmeans algorithm is subsampling the training set when the ratio of number of training vectors / nb centroids is too high.
https://github.com/facebookresearch/faiss/wiki/FAQ#can-i-ignore-warning-clustering-xxx-points-to-yyy-centroids
