### ISSUE TITLE
bad_alloc problem

### ISSUE THREAD

**Issue by deitycitian** [facebookresearch/faiss#180]
Hello, I try to run the demo_ivfpq_indexing, with 10 million-vector-database and 128 dimensions , but get failure.  My RAM is 32G.

terminate called after throwing an instance of 'std::bad_alloc'ance=1.026 nsplit=0 
  what(): std::bad_alloc

**Comment by deitycitian** [comment]
what to do with this ?

**Comment by deitycitian** [comment]
19G

**Comment by deitycitian** [comment]
Is that normal ？Any suggestion？

**Comment by deitycitian** [comment]
Hi, @mdouze 
With a debugger,  I found that Faiss try to alloc a size of 40G memory,  and it cause abort.  Ofcause, there is not enough free memory for the alloc in my machine.

The  code is ProductQuantizer.cpp:396:  "float *dis_tables = new float [n * ksub * M]"; // value of n is 10M,  and  ksub：256， M：4.

It seems like that the alloc  is too large ， isn‘t it ？  I will very appreciate it , if you tell me this is normal or not. Thanks a lot.

**Comment by mdouze** [comment]
To reduce the size of the tables, you can perform searches in batches (of say 10000 elements). 

You can disable the distance tables altogether with 
`index.use_precomputed_table = 0`
it will be a bit slower.

**Comment by deitycitian** [comment]
Thanks very much
