### ISSUE TITLE
IndexIVF does not work in c_api

### ISSUE THREAD

**Issue by ava57r** [facebookresearch/faiss#1803]
# Summary

Hello.
I am creating `constructor` function for `IndexIVF` in c_api 
and my IDE shows this message " `encode_vectors` not implemented for `IndexIVF`"

only declaration 
https://github.com/facebookresearch/faiss/blob/master/faiss/IndexIVF.h#L167

IVF uses
https://github.com/facebookresearch/faiss/blob/master/faiss/IndexIVF.cpp#L228
`IndexIVFFlat::encode_vectors` impl.

Running on:
- CPU

Interface: 
-  C++

**Comment by Enet4** [comment]
`IndexIVF` is an abstract class type. One would not construct a value of this type, but instead of a concrete index type such as `IndexIVFFlat` or `IndexIVFPQ`. As such, it makes sense not to expose a `new` function for `IndexIVF` in the C API.
