### ISSUE TITLE
How could I choice the type for IVFPQ ? And Could I remove ids after I use add_with_ids  to add ids and vectors for IVF*?

### ISSUE THREAD

**Issue by codingcai** [facebookresearch/faiss#1804]
# Summary

Hi，all:

I have  two questions:

1） When I build the index, I use the name "IVF4096,PQ4" to build index through the index_factory . In my understanding, this index will create 4096 center points, and each vector will be compressed in PQ mode. At the same time, the quantizer is flatl2 by default. However, when I use this index to train 10W objects, on the one hand, the log prompts that there are too few vectors(10W vectors to 4096 centroids), on the other hand, it says that training set too big. How could I  choice the index type? Is there anything wrong with that? Or do I have more or less training points?
************************
**log output**
WARNING clustering 100000 points to 4096 centroids: please provide at least 159744 training points
Training level-1 quantizer
Training level-1 quantizer on 100000 vectors in 16D
Training IVF residual
Input training set too big (max size is 65536), sampling 65536 / 100000 vectors
computing residuals
training 4x256 product quantizer on 65536 vectors in 16D
Training PQ slice 0/4
************************
2） After training data with "IVFPQ*" index , and I use the add_with_ids to add vectors and ids , I want to remove some invalids ids and vectors . Could I remove the specific invalid ids so that I won't search these ids and vectors ? I look for the wiki and see the "remove operation" is only supported for Flat* ? 
      And another queshtion is : when I use the add_with_ids , what will happen if I use the same id with different new vectors (how to solve the old vectors)? When I search the result , will the old vector return ?

Thank you.

Running on:
- [x] CPU
- [ ] GPU

Interface: 

- [x] C++

- [ ] Python

**Comment by mdouze** [comment]
Please refer to: 

https://github.com/facebookresearch/faiss/wiki/FAQ#can-i-ignore-warning-clustering-xxx-points-to-yyy-centroids

https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes#removing-elements-from-an-index
