### ISSUE TITLE
[Question] Add a new index that uses customized inverted list 

### ISSUE THREAD

**Issue by lynnliu030** [facebookresearch/faiss#1806]
# Summary
Hi, if I want to implement a new inverted list and add a new index that uses this type of inverted list, what would be the steps of doing so? I.e. which files should I go and modify? For implementing a new inverted list, I'm looking at `faiss/invlists/InvertedLists.h` and `faiss/invlists/InvertedLists.cpp`. For a new index, should I just create `myIndex.h` and `myIndex.cpp` under `/faiss/`? What are the modifications I need to do to add this index to the index factory?

**Comment by mdouze** [comment]
That's correct. You can either build the index explicity or add an option in the index factory: 

https://github.com/facebookresearch/faiss/blob/master/faiss/index_factory.cpp#L120
