### ISSUE TITLE
[Qustion]failed in void faiss::gpu::runMatrixMult

### ISSUE THREAD

**Issue by F0xZz** [facebookresearch/faiss#1807]
my code is based on the :face-cluster-framework
this code is using the faiss to create the cluster
I have try this code in the cuda10.1 gtx1080 env ,is OK :+1: 
But now i try this code in the GTX3060  cuda11
this is error is happened:
--------------------------------------
Faiss assertion 'err == CUBLAS_STATUS_SUCCESS' failed in void faiss::gpu::runMatrixMult(faiss::gpu::Tensor<float, 2, true>&, bool, faiss::gpu::Tensor<T, 2, true>&, bool, faiss::gpu::Tensor<IndexType, 2, true>&, bool, float, float, cublasHandle_t, cudaStream_t) [with AT = float; BT = float; cublasHandle_t = cublasContext*; cudaStream_t = CUstream_st*] at /__w/faiss-wheels/faiss-wheels/faiss/faiss/gpu/utils/MatrixMult-inl.cuh:162; details: cublas failed (13): (140, 256) x (140, 256)' = (140, 140)
Aborted (core dumped)

my working env is list in the below:
i run my code in the docker
Nvidia-Driver: 460.67
Cuda version: 11.0
torch-gpu == 1.7.0+cu110
torchvision = 0.8.1+cu110
faiss-gpu=1.7.0

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

i have also some tips and wanna say:
i also test the faiss 1.6.4 is also have the same question
but when i test on the faiss-gpu 1.5.3 work fun 
thank !
and if can fix the problem plz tell us why the reason occured 
thank you very much again

**Comment by F0xZz** [comment]
when i search the website , i find there were an error when the update the code .
the code when update 1.5.3 to the version 1.6.4 ,has some error maked  
and this is the website that show the error [https://zhuanlan.zhihu.com/p/346728479](websit)

**Comment by mabunday** [comment]
+1 to seeing this issue with Python 1.7.0 and 1.6.5 when searching a CPU index that's been moved to GPU (single and multiple) with Cuda 10.2 on all p2 and p3 SageMaker endpoints. 

```
Faiss assertion 'err == CUBLAS_STATUS_SUCCESS' failed in void faiss::gpu::runBatchMatrixMult(faiss::gpu::Tensor<float, 3, true>&, bool, faiss::gpu::Tensor<U, 3, true, int, faiss::gpu::traits::DefaultPtrTraits>&, bool, faiss::gpu::Tensor<BT, 3, true>&, bool, float, float, cublasHandle_t, cudaStream_t) [with AT = float; BT = float; cublasHandle_t = cublasContext*; cudaStream_t = CUstream_st*] at src/faiss/gpu/utils/MatrixMult-inl.cuh:355; details: cublasGemmStridedBatchedEx failed (8)
```

I've tried upgrading/downgrading Cuda to get past this issue, but for the same environment above Cuda 11.x gives `CUDA error 3 initialization error` when moving the index, and Cuda 9.x and 10.1.x succeed in moving and searching the index for p2 endpoints instances, but fail for p3 endpoints. 

I have not tried FAISS 1.5.3 but I will try that and see if the issue persists.
