### ISSUE TITLE
the similarity of batch search will be different according to the number of query samples

### ISSUE THREAD

**Issue by luohuan02** [facebookresearch/faiss#1808]
# Summary

the similarity of batch search will be different according to the number of query samples

Look at the picture below

The first graph is batch forecasting，batch is 10, 20, all and 50，the most similar distances of the first three samples are different

The second figure is 200 dimensions, the batch prediction results are normal

OS: CentOS Linux release 7.9.2009 (Core)

Faiss version: faiss-gpu                             1.7.0

Installed from: pip

Faiss compilation options: None

Running on:
- [x] CPU
- [] GPU

Interface: 
- [ ] C++
- [x ] Python

# Reproduction instructions

 
![image](https://user-images.githubusercontent.com/13143808/113843719-693f3180-97c6-11eb-8c6c-1279c6018648.png)
![image](https://user-images.githubusercontent.com/13143808/113843796-7c520180-97c6-11eb-83a2-8650f5d8ac34.png)

```
import faiss
import numpy as np
dimension = 5000
train_rand_arr = np.random.randint(0, 2, size = (5000, dimension))
test_rand_arr = np.random.randint(0, 2, size = (2000, dimension))
faiss_index = faiss.IndexFlatL2(dimension)
faiss_index.add(train_rand_arr.astype('float32'))
d1, i1 = faiss_index.search(test_rand_arr[:10].astype('float32'), k = 10)
d2, i2 = faiss_index.search(test_rand_arr[:20].astype('float32'), k = 10)
d4, i4 = faiss_index.search(test_rand_arr[:].astype('float32'), k = 10)
d3, i3 = faiss_index.search(test_rand_arr[:50].astype('float32'), k = 10)
look_num = 4
d1[:look_num], d2[:look_num], d3[:look_num], d4[:look_num]
```

**Comment by mdouze** [comment]
I can't repro, I get
```
(array([[2367., 2380., 2386., 2389., 2391., 2392., 2394., 2395., 2396.,
         2398.],
        [2366., 2369., 2370., 2382., 2383., 2387., 2389., 2391., 2392.,
         2394.],
        [2347., 2355., 2371., 2382., 2384., 2385., 2393., 2393., 2396.,
         2396.],
        [2381., 2383., 2387., 2389., 2391., 2392., 2392., 2400., 2401.,
         2402.]], dtype=float32),
 array([[2367., 2380., 2386., 2389., 2391., 2392., 2394., 2395., 2396.,
         2398.],
        [2366., 2369., 2370., 2382., 2383., 2387., 2389., 2391., 2392.,
         2394.],
        [2347., 2355., 2371., 2382., 2384., 2385., 2393., 2393., 2396.,
         2396.],
        [2381., 2383., 2387., 2389., 2391., 2392., 2392., 2400., 2401.,
         2402.]], dtype=float32),
 array([[2367., 2380., 2386., 2389., 2391., 2392., 2394., 2395., 2396.,
         2398.],
        [2366., 2369., 2370., 2382., 2383., 2387., 2389., 2391., 2392.,
         2394.],
        [2347., 2355., 2371., 2382., 2384., 2385., 2393., 2393., 2396.,
         2396.],
        [2381., 2383., 2387., 2389., 2391., 2392., 2392., 2400., 2401.,
         2402.]], dtype=float32),
 array([[2367., 2380., 2386., 2389., 2391., 2392., 2394., 2395., 2396.,
         2398.],
        [2366., 2369., 2370., 2382., 2383., 2387., 2389., 2391., 2392.,
         2394.],
        [2347., 2355., 2371., 2382., 2384., 2385., 2393., 2393., 2396.,
         2396.],
        [2381., 2383., 2387., 2389., 2391., 2392., 2392., 2400., 2401.,
         2402.]], dtype=float32))
```

**Comment by luohuan02** [comment]
> I can't repro, I get
> 
> ```
> (array([[2367., 2380., 2386., 2389., 2391., 2392., 2394., 2395., 2396.,
>          2398.],
>         [2366., 2369., 2370., 2382., 2383., 2387., 2389., 2391., 2392.,
>          2394.],
>         [2347., 2355., 2371., 2382., 2384., 2385., 2393., 2393., 2396.,
>          2396.],
>         [2381., 2383., 2387., 2389., 2391., 2392., 2392., 2400., 2401.,
>          2402.]], dtype=float32),
>  array([[2367., 2380., 2386., 2389., 2391., 2392., 2394., 2395., 2396.,
>          2398.],
>         [2366., 2369., 2370., 2382., 2383., 2387., 2389., 2391., 2392.,
>          2394.],
>         [2347., 2355., 2371., 2382., 2384., 2385., 2393., 2393., 2396.,
>          2396.],
>         [2381., 2383., 2387., 2389., 2391., 2392., 2392., 2400., 2401.,
>          2402.]], dtype=float32),
>  array([[2367., 2380., 2386., 2389., 2391., 2392., 2394., 2395., 2396.,
>          2398.],
>         [2366., 2369., 2370., 2382., 2383., 2387., 2389., 2391., 2392.,
>          2394.],
>         [2347., 2355., 2371., 2382., 2384., 2385., 2393., 2393., 2396.,
>          2396.],
>         [2381., 2383., 2387., 2389., 2391., 2392., 2392., 2400., 2401.,
>          2402.]], dtype=float32),
>  array([[2367., 2380., 2386., 2389., 2391., 2392., 2394., 2395., 2396.,
>          2398.],
>         [2366., 2369., 2370., 2382., 2383., 2387., 2389., 2391., 2392.,
>          2394.],
>         [2347., 2355., 2371., 2382., 2384., 2385., 2393., 2393., 2396.,
>          2396.],
>         [2381., 2383., 2387., 2389., 2391., 2392., 2392., 2400., 2401.,
>          2402.]], dtype=float32))
> ```

sometimes i can get different result，but not all

Increasing the dimension to 50000 or more makes it easier to repro
