### ISSUE TITLE
fvec_L2sqr‘s AVX implementations is not faster than SSE?

### ISSUE THREAD

**Issue by gongxun0928** [facebookresearch/faiss#181]
The function fvec_L2sqr  comments that AVX implementations  is not faster than SSE on current machines. see P57425519. 
* why?
* what about AVX2 implementations

**Comment by mdouze** [comment]
Hi 
It is quite likely that the performance is limited by memory bandwidth anyways, so it is not useful to speed up the computations.

**Comment by gongxun0928** [comment]
@mdouze  in other words. if momory bandwidth available, AVX/AVX2 implementations is faster? in my testcase, avx implementations is faster.

**Comment by mdouze** [comment]
Here is the benchmark code: https://gist.github.com/mdouze/c660f9bde737a57cb11cb1c715feb412

**Comment by gongxun0928** [comment]
@mdouze thx
