### ISSUE TITLE
IndexIVFFlat search is returning less than specified top-k closest embeddings.

### ISSUE THREAD

**Issue by floschne** [facebookresearch/faiss#1811]
# Summary

Hi,
I'm using an `IndexIVFFlat` Index with `IndexFlatIP` as a quantizer. After training the Index and adding my ~500k  embeddings, I'm running `index.search(query_embedding, 1000)` to receive the top-1000 embeddings according to the dot-product metric. `index.nprobe` is set to 250.

The problem I'm facing is, that I get way less than the top-1000. It depends on the query_embedding but most of the time it returns between 5-50 items only. 

Why is this and how can I solve this to get exactly the top-1000 ?

# Platform

OS: Ubuntu 18.04LTS

Faiss version: 1.7.0 release 

Installed from: conda pytorch

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by mdouze** [comment]
It is unusual to use IndexFlatIP as a quantizer but it should work. You should set the nprobe both for the toplevel index because the default nprobe is 1 (too low). This probably explains why you get fewer results. 
To set the nprobe on the quantizer use 

```
faiss.extract_index_ivf(index.quantizer).nprobe = 123
```

**Comment by floschne** [comment]
Thanks for your answer! I'll give it a try and report what happened :-)

Why is using an IndexFlatIP unusual as quantizer? What quantizer would you recommend and why?

**Comment by QwertyJack** [comment]
@mdouze Does the quantizer `IndexFlatIP` have a `nprobe` ?

**Comment by floschne** [comment]
push :-)

**Comment by wickedfoo** [comment]
> @mdouze Does the quantizer `IndexFlatIP` have a `nprobe` ?

no, nprobe is only on IVF indices. IndexFlatIP is brute-force evaluation (every candidate is considered).

**Comment by wickedfoo** [comment]
nprobe on IndexIVFFlat determines the number of nearest neighbors in the IndexFlatIP (the k) that are being considered though.
