### ISSUE TITLE
How to remove ids in GpuIndexFlat?

### ISSUE THREAD

**Issue by KinglittleQ** [facebookresearch/faiss#1818]
# Summary

There is `remove_ids` method in IndexFlat. Is the same operation supported in GpuIndexFlat?

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [x] C++
- [x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
No, the remove functions are not implemented for GPU.
see also #584
