### ISSUE TITLE
Cosine distance between same keywords is not exactly zero

### ISSUE THREAD

**Issue by Somya555** [facebookresearch/faiss#1820]
# Summary
Hi,
I have trained an IVFPQ faiss index with flatL2 quantizer on a vocabulary. Now, I am trying "search" function of faiss index to find closest match for keywords from the vocabulary.
For example : if my test keyword is "cocaine" and I want to search index for most similar keyword in vocab, having minimum distance with test keyword. My vocabulary already has keyword "cocaine" in it. 
So, when I index search for test keyword, it successfully returns index of keyword "cocaine" as it was the closest match however, the distance returned is 0.0011124562. 

My question is even though my test keyword was part of training vocabulary, why was the distance between same keywords is not zero ?

# Platform

OS: Ubuntu 18.04.4

Faiss version: 1.5.3

Installed from: pip

Running on:
- [ ] CPU

Interface: 
- [ ] Python

**Comment by wickedfoo** [comment]
IVFPQ is an index that uses quantization (product quantization on residuals). The vector as stored in the index if reconstructed will likely not be exactly the same as the vector (full precision floating point data) that you added to the index.

ADC (asymmetric distance comparison) is used for queries; i.e., you are computing the distance between your floating point query vector and the quantized vector as stored in the index. If the quantized vector was originally the same as the query, the reported distance will very likely not be exactly 0 as the quantized vector is slightly different.

**Comment by Somya555** [comment]
Thanks @wickedfoo for quick response and explaining it thoroughly.  
I will further look into this on my part.
