### ISSUE TITLE
Where is the trained OPQ matrix for the CPU Faiss?

### ISSUE THREAD

**Issue by WenqiJiang** [facebookresearch/faiss#1822]
Dear Faiss Team,

I have been using the CPU and GPU version python benchmarking scripts. I found the GPU bench script stores the OPQ matrix as, e.g., preproc_SIFT100M_OPQ16.vectrans. My question is that where does the CPU version script stores the OPQ matrix? It only has cached indexes, i.e., SIFT100M_OPQ16,IVF16384,PQ16_populated.index and SIFT100M_OPQ16,IVF16384,PQ16_trained.index

The scripts I used:

CPU: https://github.com/facebookresearch/faiss/blob/master/benchs/bench_polysemous_1bn.py
GPU: https://github.com/facebookresearch/faiss/blob/master/benchs/bench_gpu_1bn.py

The CPU version should indeed uses OPQ, since the with / without OPQ versions give me different recalls (OPQ is better):

```
python bench_polysemous_1bn.py SIFT100M IVF8192,PQ16 nprobe=32

          	 R@1    R@10   R@100     time    %pass
nprobe=32 	 0.3408 0.8132 0.9628    5.289    0.00


python bench_polysemous_1bn.py SIFT100M OPQ16,IVF8192,PQ16 nprobe=32
          	 R@1    R@10   R@100     time    %pass
nprobe=32 	 0.3509 0.8288 0.9645    5.307    0.00
```

I load the OPQ version of the CPU index to Jupyter, and found that the attributes of the loaded index are a bit different than without OPQ. For example, it does not contain the attribute "pq" that I can dump the quantizer. How can I dump the IVF index, product quantizer, and OPQ matrix in this context?

```
index = faiss.read_index("bench_cpu_SIFT100M_OPQ16,IVF16384,PQ16")

dir(index)

# Results:
['__class__',  '__del__',  '__delattr__', '__dict__', '__dir__', '__doc__', 
'__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', 
'__gt__', '__hash__', '__init__', '__init_subclass__', '__le__',  '__lt__', 
'__module__',  '__ne__', '__new__', '__reduce__',  '__reduce_ex__',  
'__repr__',  '__setattr__', '__sizeof__',  '__str__',  '__subclasshook__', 
 '__swig_destroy__', '__swig_getmethods__', '__swig_setmethods__', '
__weakref__', '_s',  'add',  'add_c',  'add_with_ids', 'add_with_ids_c', 
'apply_chain',  'assign', 'assign_c',  'chain',  'compute_residual',  
'compute_residual_n',  'd',  'get_distance_computer', 'index', 'is_trained',  
'metric_arg', 'metric_type',  'ntotal',  'own_fields',  'prepend_transform',  
'range_search', 'range_search_c', 'reconstruct',  'reconstruct_c', 'reconstruct_n', 
'reconstruct_n_c', remove_ids', 'remove_ids_c', 'reset',  'reverse_chain',  
'sa_code_size', 'sa_decode', 'sa_decode_c', 'sa_encode', 'sa_encode_c', 
'search', 'search_and_reconstruct', 'search_and_reconstruct_c', 
'search_c', 'this', 'train', 'train_c', 'verbose']
```

Thank you,
Wenqi

**Comment by mdouze** [comment]
Please refer to 
https://github.com/facebookresearch/faiss/wiki/Python-C---code-snippets
on how to find the fields of an index.

**Comment by WenqiJiang** [comment]
> Please refer to
> https://github.com/facebookresearch/faiss/wiki/Python-C---code-snippets
> on how to find the fields of an index.

Thank you, I have successfully extracted the OPQ matrix :)
