### ISSUE TITLE
[c_api] IndexIVFFlat inherites from two classes Index and IndexIVF

### ISSUE THREAD

**Issue by ava57r** [facebookresearch/faiss#1824]
# Summary

Hello.
How can I inherite IndexIVFFlat from Index and IndexIVF the same time?

IndexIVF is abstract #1803

IndexIVFFlat inherited from https://github.com/facebookresearch/faiss/blob/master/c_api/IndexIVFFlat_c.h#L26

Is right way this `IndexIVFFlat` <- `IndexIVF` <- `Index`?

Running on:
- CPU

Interface: 
-  c_api

**Comment by Enet4** [comment]
You can keep `FAISS_DECLARE_CLASS_INHERITED(IndexIVFFlat, Index)`, which should still enable users to call IndexIVF functions with a `FaissIndexIVFFlat`.

Note that this is just a _faux_ inheritance and merely a way to make it easier to use the C API without having to cast pointers all the time. The concept of inheritance is not semantically translated into the C API, as C (to the best of my knowledge) does not have a mechanism of covariance with regard to pointers.

**Comment by ava57r** [comment]
Thanks.
