### ISSUE TITLE
A Segmentation fault BUG at branch 1.7.0

### ISSUE THREAD

**Issue by minbaohong** [facebookresearch/faiss#1825]
# Summary

HI,
there is a bug, https://github.com/facebookresearch/faiss/blob/v1.7.0/faiss/gpu/GpuIndexIVFPQ.cu#L146
need add code "index->code_size = index->pq.code_size;". when i use GpuIndexIVFPQ, and set  bitsPerCode = 4, Segmentation fault has occurred
![image](https://user-images.githubusercontent.com/42599813/114852970-e34e6680-9e15-11eb-8926-80af39c32a28.png)

# Platform

OS:CentOS6.3

Faiss version: 1.7.0
Installed from: compiled by myself

Faiss compilation options: -DFAISS_ENABLE_GPU=ON -DCMAKE_BUILD_TYPE=Release -DFAISS_OPT_LEVEL=avx2

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [x] C++
- [ ] Python

**Comment by wickedfoo** [comment]
bitsPerCode != 8 is not currently supported on the GPU, as there is no bit packing code on the GPU. How are you constructing the index such that bitsPerCode is not being checked?

When bitsPerCode == 8, the IndexIVFPQ::code_size is the same as the number of subquantizers (i.e., a byte per PQ code).

**Comment by wickedfoo** [comment]
this is the check:
https://github.com/facebookresearch/faiss/blob/v1.7.0/faiss/gpu/GpuIndexIVFPQ.cu#L396

the interleavedLayout is not currently fully implemented (which will eventually support 4, 5, 6, 7, 8 bits per code).

**Comment by minbaohong** [comment]
Hi,
thanks you for your answer! i use this config
   faiss::gpu::GpuIndexIVFPQConfig config;
    config.device = 0;
    config.interleavedLayout = true;
    config.indicesOptions = faiss::gpu::INDICES_32_BIT;

    faiss::gpu::GpuIndexIVFPQ gpuIndex(
            &res,
            128,
            1024,
            64,
            4,
            faiss::METRIC_INNER_PRODUCT,
            config);
you mean pq4 on gpu is not currently fully implemented? i want to build pq4 on gpu, then convert to IndexIVFPQFastScan，because gpu can not support PQFastScan building, and use cpu building is so slow.
faiss::Index* cpu_index = faiss::gpu::index_gpu_to_cpu(&gpuIndex);
auto ivfpq = dynamic_cast<const faiss::IndexIVFPQ*>(cpu_index);
faiss::IndexIVFPQFastScan index(*ivfpq);

**Comment by mdouze** [comment]
T
