### ISSUE TITLE
Wrong impl demo_imi_flat

### ISSUE THREAD

**Issue by ava57r** [facebookresearch/faiss#1826]
# Summary

Hello

Is it correct impl?

here set `true` quantizer_trains_alone
https://github.com/facebookresearch/faiss/blob/master/demos/demo_imi_flat.cpp#L72
but in declaration different type
https://github.com/facebookresearch/faiss/blob/master/faiss/IndexIVF.h#L40

**Comment by mdouze** [comment]
That's because it was a `bool` in older versions of Faiss.

**Comment by ava57r** [comment]
Could make `quantizer_trains_alone` field as an enum?

**Comment by mdouze** [comment]
That would be the proper way of doing it. But it is low-pri and we don't want to break the file format.

**Comment by ava57r** [comment]
`quantizer_trains_alone` as private field
cast `enum` into `char`
