### ISSUE TITLE
How to get the distance between the specified ID vectors?

### ISSUE THREAD

**Issue by wangzyon** [facebookresearch/faiss#1828]
data = np.random.random((100,2048)).astype(np.float32)
index = faiss.IndexIDMap(faiss.IndexFlat(2048))
index.add_with_ids(data,np.arange(100))

# index.get_distance_between(id1,id2) ?

thanks!

**Comment by mdouze** [comment]
You'll have to reconstruct the 2 vectors with reconstruct.

https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes#reconstruct-some-vectors
