### ISSUE TITLE
how to add new data to old index 

### ISSUE THREAD

**Issue by syukeizen** [facebookresearch/faiss#183]
Hi,
I have to add some new data to my index, but I found that faiss does not support re-train in FAQ...
So if I use L2 method, could I add new data to index for search **but not rebuild** a index?

thx :)

**Comment by mdouze** [comment]
Hi, 
You do not need to re-train the index to add new data to it. This is a problem only if the distribution of the new data differs from the distribution of the training data.

**Comment by syukeizen** [comment]
I appreciate you time ;D

**Comment by chikubee** [comment]
@mdouze hey, I am trying to use faiss for semantic search on documents, for my use-case, editing documents, or adding fresh new data and removing data can be a common practise.,
in that scenario, rebuilding index can be an expensive operation.
But as you mentioned, one needs to train it only if distribution differs?
can you explain how can that be achieved?
and does this hold for all index types?

**Comment by wickedfoo** [comment]
@chikubee "distribution" here refers to the statistical distribution of the vectors in N-dimensional space. k-means clustering is frequently used in approximate Faiss indices to partition that data distribution into relatively equivalent buckets, or to minimize quantization error.

If the data you are adding to an already trained index differs in a meaningful way (significantly out of sample of the data distribution seen when training it), the recall for the newly added out-of-distribution vectors may be low. Whether this is important or not depends upon your own precision/recall metrics desired, and would require you testing these effects.

**Comment by bhargav-11** [comment]
```
    docs = loader.load_and_split(text_splitter)
    for doc in docs:
        doc.metadata["pdf"] = doc.metadata["source"]

    index = FAISS.load_local("embeddings/faiss_index", embeddings, allow_dangerous_deserialization=True)

    # Add the file to the index
    index.add_documents(docs)
```
