### ISSUE TITLE
Different filename for c_api lib when opt level = avx2

### ISSUE THREAD

**Issue by ava57r** [facebookresearch/faiss#1831]
# Summary

Hello.
When opt level == avx2
c_api lib builds in `libfaiss_c.so` with link `libfaiss_avx2.so`

When opt level == general
c_api lib builds in `libfaiss_c.so` with link `libfaiss.so`

Add different target for` c_api lib`
opt level == `avx2`
`libfaiss_avx2_c.so` with link `libfaiss_avx2.so`

# Platform

OS: Linux 

Faiss version: v1.7.0

Running on:
- CPU

Interface: 
-  C++

References:
#1783 
https://github.com/Enet4/faiss-rs/issues/19

**Comment by Enet4** [comment]
As I stated in Enet4/faiss-rs#19, I would prefer the building process of the C API to result in a library always named `faiss_c` (libfaiss_c.so on Linux), regardless of the considered instruction set extensions or features.

**Comment by ava57r** [comment]
> As I stated in [Enet4/faiss-rs#19](https://github.com/Enet4/faiss-rs/issues/19), I would prefer the building process of the C API to result in a library always named `faiss_c` (libfaiss_c.so on Linux), regardless of the considered instruction set extensions or features.

I agree. 
Thanks.
