### ISSUE TITLE
GpuIndexFlatL2 has no attribute shape?

### ISSUE THREAD

**Issue by AfrinaVT** [facebookresearch/faiss#1834]
# Summary

# Platform

OS:  Ubuntu 18.04

Faiss version: 1.70

Installed from: tried with both pip and conda

Faiss compilation options: 

Running on:
- [ ] CPU
- [ X] GPU

Interface: 
- [ ] C++
- [X ] Python

# Reproduction instructions
    
    kmeans = faiss.Kmeans(x.shape[1], k, niter=50, verbose=True, gpu=True)

    res = faiss.StandardGpuResources()
    cfg = faiss.GpuIndexFlatConfig()
    cfg.useFloat16 = False
    cfg.device = 0
    index = faiss.GpuIndexFlatL2(res, x.shape[1], cfg)
    kmeans.train(x, index)

**Comment by mdouze** [comment]
See the doc
https://github.com/facebookresearch/faiss/wiki/Faiss-building-blocks:-clustering,-PCA,-quantization#clustering
If you want to use GPU, please set gpu=True in the Kmeans constructor

**Comment by phanxuanduc1996** [comment]
I used Anaconda, I installed bellow, it worked. If you use Docker, please install Miniconda.
`conda install faiss-gpu cudatoolkit=11.1 -c pytorch-gpu`
`conda install -c anaconda pytorch-gpu`
