### ISSUE TITLE
View Progress During Searching

### ISSUE THREAD

**Issue by JerryLife** [facebookresearch/faiss#1843]
# Summary

Does faiss provide a method to monitor the searching progress on IndexFlat?

# Platform

OS: Linux 

Faiss version: 1.7.0 

Installed from: anaconda  

Faiss compilation options: N/A 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
N/A

**Comment by mdouze** [comment]
If you have several queries, the easiest would be to run them in batches of 0.1 sec each and build a progress bar over batches.

**Comment by JerryLife** [comment]
Should I manually divide the batches and invoke `index.search()` or does faiss provide an interface for batching? I am concerned whether faiss has some optimization on matrix operation, in which cases the manual division could harm the performance of searching.

**Comment by mdouze** [comment]
The performance penalty should not matter if the batches are large enough.
