### ISSUE TITLE
What is the meaning of variables in HNSWStats

### ISSUE THREAD

**Issue by chrysantd** [facebookresearch/faiss#1844]
https://github.com/facebookresearch/faiss/blob/7559cf5c5bf181942ed706fd8914e77a5c4bfb9b/faiss/impl/HNSW.h#L231-L233

Sorry to ask here, but I don't find documents or comments about variables in HNSWStats.
I want to know what n1,n2,n3 and ndis in HNSWStats represent, thanks! My guess is that n3 is the number of visited points in layer 0 and ndis is the total number of visited points, is that right?

**Comment by mdouze** [comment]
Right, it is not documented. Please refer to the code as this is low-level info just used for debugging.
