### ISSUE TITLE
Undefined Rederence to faiss::IndexResiual and  faiss:ResisualCoarseQuantizer functions using cmake

### ISSUE THREAD

**Issue by omp87** [facebookresearch/faiss#1845]
# Summary

# Platform

OS: 

Faiss version: 

Installed from: 
compiled using CMAKE / Make

Faiss compilation options: 
cmake -DFAISS_ENABLE_GPU=OFF -DBUILD_TESTING=ON ..

Running on:
- [x ] CPU
- [ ] GPU

Interface: 
- [x ] C++
- [ ] Python

# Reproduction instructions
I have ben doing this within a docker container that starts with Ubuntu 20.0.4 as a base image. 
I clone the master branch of faiss in this image and use cmake to compile this image. This produces the following errors:
/usr/bin/ld: /usr/local/lib/libfaiss.so: undefined reference to `faiss::Residual                                                                  CoarseQuantizer::ResidualCoarseQuantizer()'
/usr/bin/ld: /usr/local/lib/libfaiss.so: undefined reference to `typeinfo for fa                                                                  iss::IndexResidual'
/usr/bin/ld: /usr/local/lib/libfaiss.so: undefined reference to `faiss::IndexRes                                                                  idual::IndexResidual()'
/usr/bin/ld: /usr/local/lib/libfaiss.so: undefined reference to `faiss::Residual                                                                  CoarseQuantizer::ResidualCoarseQuantizer(int, std::vector<unsigned long, std::al                                                                  locator<unsigned long> > const&, faiss::MetricType)'
/usr/bin/ld: /usr/local/lib/libfaiss.so: undefined reference to `typeinfo for fa                                                                  iss::ResidualCoarseQuantizer'
/usr/bin/ld: /usr/local/lib/libfaiss.so: undefined reference to `faiss::IndexRes                                                                  idual::IndexResidual(int, std::vector<unsigned long, std::allocator<unsigned lon                                                                  g> > const&, faiss::MetricType, faiss::IndexResidual::Search_type_t)'

**Comment by chrysantd** [comment]
Same problem here

**Comment by mdouze** [comment]
see #1846
