### ISSUE TITLE
How to update index? I have to reset index and add  all feature embeddings.

### ISSUE THREAD

**Issue by hitzht** [facebookresearch/faiss#1847]
example:
    index = faiss.IndexFlatL2(dim)
    index.reset()
    feature_embeddings = np.array(updated_df.values).astype('float32')
    index.add(feature_embeddings)
considering that the above way cost lots of time when the index is large ,so i just want to update index[i] instead of all of index.
thanks!

**Comment by mdouze** [comment]
For this case, you should probably use 

https://github.com/facebookresearch/faiss/wiki/Brute-force-search-without-an-index

**Comment by hsfzxjy** [comment]
@mdouze Hi. I am wondering is there any efficient ways to update a GpuIndexFlatL2 ?

**Comment by hitzht** [comment]
来信已收到，我会尽快查看，谢谢!                                  周海涛
