### ISSUE TITLE
Inaccuracy with Textual Data

### ISSUE THREAD

**Issue by NikhilKothari** [facebookresearch/faiss#1848]
# Summary

I might be using it wrong but I've spent a lot of time with it. I can not get accurate results from Faiss when I try it with encodings for textual data. Either the order of results is a bit messed up or some results just get excluded from the result set. I wanted to know if this was an expected behaviour or something is wrong at my end. 

Faiss beats Spotify's Annoy in almost everything except accuracy in my case. Any help would be nice.

## OS 

macOS 10.15.6

## Faiss version

latest

## Installed from

pip

## Running on

CPU

## Interface

Python

**Comment by mdouze** [comment]
What kind of encodings are you using? What index?
Experiments on sentence embeddings suggest that they are hard to encode,
https://github.com/facebookresearch/faiss/wiki/Vector-codec-benchmarks#sentence-embeddings

**Comment by NikhilKothari** [comment]
```
    def create_l2_index(self):
        dimension = len(self.vec[0])
        num_of_clusters = 10

        # quantiser assigns each vector to a cluster with max similarity
        quantiser = faiss.IndexFlatL2(dimension)
        self.index = faiss.IndexIVFFlat(
            quantiser, dimension, num_of_clusters, faiss.METRIC_INNER_PRODUCT
        )

        faiss.normalize_L2(self.vec)
        self.index.train(self.vec)
        self.index.add(self.vec)

        faiss.write_index(self.index, self.index_path)
```

This is how I'm using it. I'm encoding the sentences via Transformers. 

The encodings seem to be fine since I'm getting correct results with Spotify's annoy and a basic cosine similarity as well. Not sure if I'm using Faiss right.

**Comment by mdouze** [comment]
Can't repro
