### ISSUE TITLE
Interest in non-orthogonal codebooks?

### ISSUE THREAD

**Issue by una-dinosauria** [facebookresearch/faiss#185]
I'm wondering if there is interest from the maintainers (and the community) on implementing some non-orthogonal variants of product quantization into faiss?

I have observed that these methods tend to perform very well on features extracted from deep neural networks, and are also pretty well suited for dot product similarity search.

Some baselines that come to my mind are

* Residual Vector Quantization (RVQ) [[paper](http://www.mdpi.com/1424-8220/10/12/11259/htm)]
* Enhanced RVQ (RVQ + a few rounds of ICM) [[paper](https://link.springer.com/article/10.1007/s00530-015-0470-9)]
* Optimized Tree Quantization (OTQ) [paper] -- I'm actually thinking of a variant that does not use Gurobi, similar to [this](https://github.com/una-dinosauria/local-search-quantization/blob/master/src/encodings/encode_chain.jl). [[paper](http://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Babenko_Tree_Quantization_for_2015_CVPR_paper.pdf)]
* Local Search Quantization (LSQ) [paper] -- Iterated local search with ICM. [[paper](https://www.cs.ubc.ca/~julm/papers/eccv16.pdf)]
* Some other improvements to LSQ that are currently under review (will post later)

I have implemented some of these on Julia before, and ported LSQ to the GPU (e.g. [here](https://github.com/una-dinosauria/local-search-quantization)). Please do let me know if there is interest for this; since the licence has been relaxed I'd be happy to contribute some of my own research to the library.

**Comment by mdouze** [comment]
Hi, 
We have no plans of adding non-orthogonal quantization to Faiss, but we would be very grateful if you could implement an option of your choosing. 
If you plan to do this, I would suggest that you look around in the library's structure and propose an index structure (ie a .h file) with the required methods and fields, so that we can comment on it before you spend a lot of time in the implementation.
Thanks!

**Comment by una-dinosauria** [comment]
I think we can close this one since #1862 has landed.
