### ISSUE TITLE
Any good methods to remove records from index permanently

### ISSUE THREAD

**Issue by kinpoon-sn** [facebookresearch/faiss#1851]
# Summary

I have a permanent-running program that inserts records into faiss index frequently and call `remove_ids` hourly, however Faiss doesn't remove the records from memory, which consumes more and more memory. I'm wondering is there any good method to release the memory. What i did to avoid it is :

`faiss.write_index(self.index, self.index_file)`
`self.index = faiss.read_index(self.index_file)` 
or
`faiss.deserialize_index(faiss.serialize_index(index))`

and i don't think it's an elegant way

# Platform

OS: RHL

Faiss version: 1.6.3

Installed from: pip

Running on:
- [+] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [+] Python

# Reproduction instructions

**Comment by mdouze** [comment]
remove_ids /does/ remove the elements from the C++ vector they belong in. What makes you think that the memory is not released?

**Comment by kinpoon-sn** [comment]
@mdouze  thanks for follow up, here is the sample code for reproduction
`import faiss
import gc
import numpy as np
import os
import psutil

def get_memory():
    process = psutil.Process(os.getpid())
    print('memoray usage: ', process.memory_info().rss / 1024**2)

def test_faiss_remove():
    num_vec = 1000000
    d = 256
    nlist = 100
    vectors = np.random.rand(num_vec, d).astype('float32')
    quantizer = faiss.IndexFlatIP(d)
    index = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_INNER_PRODUCT)
    index.train(vectors)
    index.add_with_ids(vectors, np.array(range(num_vec)))

    print('initial ntotal: ', index.ntotal)
    get_memory()

    index.remove_ids(np.array(range(100000)).astype('int64'))
    print('after removing, ntotal: ', index.ntotal)
    gc.collect()
    get_memory()


    index.remove_ids(np.array(range(100000, 200000)).astype('int64'))
    print('after removing, ntotal: ', index.ntotal)
    gc.collect()
    get_memory()

    buff = faiss.serialize_index(index)
    del index
    index = faiss.deserialize_index(buff)
    del buff
    print('after deserialize, ntotal: ', index.ntotal)
    gc.collect()
    get_memory()

test_faiss_remove()`

output is:

> initial ntotal:  1000000
memoray usage:  2386.0390625
after removing, ntotal:  900000
memoray usage:  2386.18359375
after removing, ntotal:  800000
memoray usage:  2386.18359375
after deserialize, ntotal:  800000
memoray usage:  1804.44140625


i think it's similar to [this issue](https://github.com/facebookresearch/faiss/issues/1415#issuecomment-695908674)
ASAK, Milvus provides [compact](https://www.milvus.io/docs/v1.0.0/storage_operation.md#Compact-segments), it seems can fix it

**Comment by KinglittleQ** [comment]
C++ vector class does not release the memory right away after deleting elements unless `vector::shrink_to_fit()` is called.

**Comment by mdouze** [comment]
See also
https://github.com/facebookresearch/faiss/wiki/FAQ#why-does-the-ram-usage-not-go-down-when-i-delete-an-index
