### ISSUE TITLE
Binary index with extremely high dimension

### ISSUE THREAD

**Issue by JerryLife** [facebookresearch/faiss#1854]
# Summary

I am working with extremely high-dimensional binary vectors. Each binary vector has about 100M dimensions. On the other side, the number of vectors and queries is relatively small (about 10-100k). I realize PQ might help reduce dimension but I did not find indices like `IndexBinaryPQ` or `IndexBinaryIVFPQ`. I checked wiki about the 1T dataset but did not find a solution for such large dimensional datasets. Any advice would be appreciated. 

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by wickedfoo** [comment]
What is the sparsity level of the binary vectors? If they are fairly sparse, do you store them dense as packed words (e.g., 100M dims / (sizeof(uint8_t) * 8) = 12.5 MBytes/vec) or in the sparse representation?

The implementations in Faiss are designed for high dimensions, but typically in the 20 - 2000 dim range, say, not extremely high dimensions. The existing brute-force implementations are designed for dense binary vectors. PQ applied to a large number of dimensions will be quite inaccurate.

The best I think you could do would be to implement yourself a brute-force all-to-all comparison on a sparse representation of the vectors, or perhaps consider something like locality sensitive hashing which I think people have used on very high dimensional sparse vectors before.

**Comment by mdouze** [comment]
For brute-force sparse vectors, I recommend `scipy.csr_matrix`, it has very good single-thread performance (can be threaded from python).

**Comment by mdouze** [comment]
A few sparse routines have been added here: https://github.com/facebookresearch/faiss/blob/main/contrib/clustering.py#L193
