### ISSUE TITLE
How to use Fiass with SIFT descriptors ?

### ISSUE THREAD

**Issue by sruthi1014** [facebookresearch/faiss#1861]
# Summary

 

Hi,
After performing SIFT on an image the output I am looking to store is the descriptors information. Each image has different no. of descriptors  and each descriptor has 128 elements.
given 2 images in my dataset. the output i get is (1, no. of descriptors in image1, 128) ,( 1, no. of descriptors in image2, 128) 
converting this set of information to array gives a shape of (2,) and "fiass throws error requires two positional arguments but provided one". in case I take equal no. of descriptors say 10000 and pass the data it throws the error "too many values to unpack" at the index.train(vectors) code line as the array is in shape (2, 10000, 128)  
Please let me know how to handle the data from SIFT to perform feature matching using FIASS.

**Comment by mdouze** [comment]
Vectors to index or to search should be in a 2D array of size (nb vectors, nb dimensions).
