### ISSUE TITLE
Export global vars into c_api

### ISSUE THREAD

**Issue by ava57r** [facebookresearch/faiss#1863]
# Summary

Hello.

Faiss contains various external global variables.
here
https://github.com/facebookresearch/faiss/blob/master/faiss/utils/distances.h#L156-L167

and here
https://github.com/facebookresearch/faiss/blob/master/faiss/IndexIVF.h#L412

Is this API available to library users?

Running on:
- CPU

Interface: 
- C++

**Comment by mdouze** [comment]
yes, they are mainly used to tune block sizes and to collect search stats, see eg. https://github.com/facebookresearch/faiss/wiki/Implementation-notes#statistics-for-non-exhaustive-search

**Comment by ava57r** [comment]
Thanks!
I want to add this into c_api.
