### ISSUE TITLE
Question: Should index_factory use IndexIDMap2 instead?

### ISSUE THREAD

**Issue by michellemay** [facebookresearch/faiss#1864]
# Summary

`index_factory` currently use `IndexIDMap` by default.   Should it use the `IndexIDMap2` that allows reconstruction?

Interface: 
- [x] C++
- [ ] Python

**Comment by michellemay** [comment]
Maybe not the default one, but should be configurable in the factory string ?

**Comment by mdouze** [comment]
you can get an index wrapped in IDMap or IDMap2 with the corresponding index_factory string suffixes. What makes you think that IDMap is used "by default" ?

**Comment by michellemay** [comment]
> you can get an index wrapped in IDMap or IDMap2 with the corresponding index_factory string suffixes. What makes you think that IDMap is used "by default" ?

The code in current master branch explicitely use `IndexIDMap`:  https://github.com/facebookresearch/faiss/blob/bb3c52a057fb5353e043d1f7a41a895879b5c77a/faiss/index_factory.cpp#L463

On the same subject, I saw that IndexIVF have a DirectMap built in.  Again, the index_factory does not allow to specify that setting. (or does it through a different mechanism?)

Maybe I misunderstood something about the factory.. If so, please indulge my ignorance and just point me in the right direction and I'll do my homework properly.

**Comment by mdouze** [comment]
Right, IDMap2 is not supported in the factory (only IDMap is). 
Will mark this as an enhancement.

**Comment by AbdelrahmanElmeniawy** [comment]
Now, Index_factory supports IDMap2 just by adding "IDMap2" to prefix or suffix of the input String!
e.g. "Flat,IDMap2" or "IDMap2,Flat"
