### ISSUE TITLE
Merge d2c04d093576d1d5fe26de28352b857d7236a447 before next release.

### ISSUE THREAD

**Issue by h-vetinari** [facebookresearch/faiss#1876]
Not sure what the timeline is for 1.7.1 or 1.8.0, but it's been a while since 1.7.0, and I'd just like to make sure that https://github.com/facebookresearch/faiss/pull/1610/commits/d2c04d093576d1d5fe26de28352b857d7236a447 gets merged before the next release (doesn't need the whole PR, just as a single commit is fine), otherwise windows GPU support is not possible - or rather, continues to require carrying patches...

I can open a PR with that commit if that's helpful.

**Comment by mdouze** [comment]
We plan to do 1.7.1 ASAP, the current blocker is issues with anaconda.
