### ISSUE TITLE
Enable building libfaiss just for avx2

### ISSUE THREAD

**Issue by h-vetinari** [facebookresearch/faiss#1877]
In the conda-forge packaging, `libfaiss` and `libfaiss_avx2` are separate packages (and `faiss` depends on both to implement the fall-back if AVX2 hardware is not available, cf. https://github.com/conda-forge/faiss-split-feedstock/issues/23), but while trying to adapt to the changes from #1772 in https://github.com/conda-forge/faiss-split-feedstock/pull/35, I'm facing the issue that building just for `--target faiss_avx2` does not work (despite the target-name without "lib", this is from `build-lib.sh` on conda-forge side, which itself takes inspiration from the [`build-lib.sh`](https://github.com/facebookresearch/faiss/blob/b4c320a671e58252b229f12459f2d9c285e8b535/conda/faiss/build-lib.sh#L21) in this repo):

```
[100%] Linking CXX shared library libfaiss_avx2.so
[100%] Built target faiss_avx2
-- Install configuration: "Release"
CMake Error at _build_avx2/faiss/cmake_install.cmake:52 (file):
  file INSTALL cannot find
  "/home/conda/feedstock_root/build_artifacts/faiss-split_1620763716578/work/_build_avx2/faiss/libfaiss.so":
  No such file or directory.
Call Stack (most recent call first):
  _build_avx2/cmake_install.cmake:47 (include)
```

Would be cool if we can make this possible (and `libfaiss_avx2.so` shouldn't have to depend on `libfaiss.so` anyway), because the CI is already pegging hard against the 6h limit on azure that we have on conda-forge (so having to build the lib one more time would push us over the limit for the GPU builds).

I imagine other people would like to have this too, cf. this [comment](https://github.com/facebookresearch/faiss/pull/1838#issuecomment-825536033) about fat binaries.

CC @beauby

**Comment by beauby** [comment]
Right, it is currently possible to build libfaiss for avx2 only, but the `install` step assumes the vanilla version is always built. The reason why we have a separate target for libfaiss_avx2 is mainly due to the way we're building the python package, which ideally would be reworked to invoke Cmake from `setup.py` (though it is not trivial). In the meantime, we can replace the `FACE_OPT_LEVEL` CMake option with two options: `FACE_BUILD_VANILLA` and `FACE_BUILD_AVX2`, and gate the relevant parts behind `FACE_BUILD_VANILLA`. Would you mind issuing a PR if you have time? Otherwise I'll get to it, but probably not this week.

**Comment by h-vetinari** [comment]
Not sure I understand your idea completely; the way I see it, there's 3 different scenarios that we'd ideally like to cover:

| | For conda build | For custom build |
|-|-|-|
| Build `libfaiss` without AVX2 support | ✔️ | ✔️ |
| Build `libfaiss` with AVX2 support | ❌  | ✔️ |
| Build `libfaiss_avx2` with AVX2 support | ✔️ | ❌ | 

This table could of course be extended for arm+neon; etc.

The current CMake infrastructure is geared towards the needs of building the conda package, but If I understand issues like #1836 / #1838 correctly, that's hurting other use cases. 

Why not satisfy all of the above use cases by having something like

| | `FAISS_OPT_LEVEL=Generic` | `FAISS_OPT_LEVEL=AVX2` |
|-|-|-|
| `FAISS_LIB_SUFFIX=` [default] | `libfaiss` without AVX2 support | `libfaiss` with AVX2 support | 
| `FAISS_LIB_SUFFIX=_AVX2` | should error? | `libfaiss_avx2` with AVX2 support | 

This would then also be suitable for extension:

| | `FAISS_OPT_LEVEL=Generic` | `FAISS_OPT_LEVEL=AVX2` | `FAISS_OPT_LEVEL=NEON` | ... |
|-|-|-|-|-|
| `FAISS_LIB_SUFFIX=` [default] | `libfaiss` without AVX2 support | `libfaiss` with AVX2 support | `libfaiss` with NEON support | ... |
| `FAISS_LIB_SUFFIX=<whatever>` | should error? | `libfaiss<whatever>` with AVX2 support | `libfaiss<whatever>` with NEON support | ... |

**Comment by vorj** [comment]
Unlike AVX2, ARM SIMD (usually called _NEON_ ) is part of the ARMv8 ISA, not extension. (The real _NEON_ , in ARMv7, is the extension.)
So (currently) when we use aarch64, ARM SIMD always works.
Actually, current `faiss` uses ARM SIMD with `FAISS_OPT_LEVEL=Generic` .

Does `FAISS_OPT_LEVEL=NEON` mean that `FAISS_OPT_LEVEL=Generic` should use ARMv8 without ARM SIMD?

**Comment by h-vetinari** [comment]
@beauby, any thoughts on the above?

@vorj, I cannot answer the ARM questions, I was just suggesting a build infrastructure that allows building different libraries for different optimizations (e.g. it would then be feasible in principle to do the same fat-binary approach for packaging conda-packages for aarch).

**Comment by vorj** [comment]
@h-vetinari Of course it can to do the fat-binary approach for aarch64, but

- `Generic` one will be NEVER used, because ARM SIMD works on any existing aarch64 CPUs. The fat-binary is unnecessarily fat.
- In order to disable to ARM SIMD for `Generic` , it will need to add `#if USE_NEON == 1` or something like that on the all places of using ARM SIMD.

IMHO the consistency on your suggestion brings just increasing binary size and `faiss` codes complexity for some architectures.
I think that it should take different (and best for each) approach to different architecture.

**Comment by h-vetinari** [comment]
@vorj

"generic" is not so much about "not-NEON", but about the lowest baseline of expected features for a given architecture - if all relevant ARM processors already support NEON, great!

But as architectures mature (or other architectures get added), it might be desirable to support more modern features without leaving the library to be unusable on older processors. So my comment above was really about being able to support `<FEATURE_LEVEL_ON_ARCH>` (and not `AVX2` or `NEON`) in both individual builds & fat-binaries.

**Comment by beauby** [comment]
@h-vetinari The current setup needs two separate targets (one for vanilla, one for avx2) to be declared at the same time (i.e. we want to avoid re-generating the CMake cache). How does your solution account for that?

**Comment by h-vetinari** [comment]
> The current setup needs two separate targets (one for vanilla, one for avx2) to be declared at the same time (i.e. we want to avoid re-generating the CMake cache). How does your solution account for that?

It doesn't yet 😅 
Until recently, there was only one target (with the `FAISS_OPT_LEVEL` switch), so using the cache became a recent nice-to-have, I guess?

> Right, it is currently possible to build libfaiss for avx2 only, but the `install` step assumes the vanilla version is always built.

It would be enough to break this assumption - don't see why it should be necessary? There should never be a cross-dependency between the various optimization levels; even if both are built, the chain of dependence should be:
```
libfaiss      <- swigfaiss      <- loader.py
libfaiss_avx2 <- swigfaiss_avx2 <- loader.py
```

I'd suggest that the cmake files should be geared towards building one lib at a time; building two is only necessary for creating fat binaries (which something that realistically only the maintainers do), and that can be done in the build scripts for that.

Separate targets would IMO still be possible - i.e. building one of the possible targets based on `FAISS_OPT_LEVEL`, and relying on `loader.py` to resolve the imports correctly - the downside being that `loader.py` would need to have fall-backs for all expected optimization levels (since I presume a putative FAISS_LIB_SUFFIX is incompatible - or at least complicated - with having separate targets).

**Comment by h-vetinari** [comment]
@beauby

Is this still on the radar before the release?

**Comment by h-vetinari** [comment]
@beauby
Any thoughts on which approach should be pursued here?

**Comment by beauby** [comment]
The main thing for the release is to avoid breaking the conda packaging, as people making custom builds can always target some commit on master. Ideally, we would have `setup.py` trigger the correct build(s), with separate loaders for fat-package vs single lib.
