### ISSUE TITLE
The count of search result

### ISSUE THREAD

**Issue by welfred** [facebookresearch/faiss#188]
` index.search (nq, queries.data(), k, dis.data(), nns.data());`
I have more than one million features are in the index. I set k = 200 and the index only returned 117 results. 
Shouldn't it return 200 results?

**Comment by mdouze** [comment]
Hi 
Please increase the `nprobe`, the default 1 means that only one data cluster is visited, which may contain too few items.

**Comment by welfred** [comment]
Ok, thanks!
