### ISSUE TITLE
Is there anyway I can use faiss result as a threshold to filter the low confidential ojbect

### ISSUE THREAD

**Issue by youtaya** [facebookresearch/faiss#1885]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

We use Faiss as search engine to index the distance between target object and database object. It aways return the score even there is no correspondence in the database. Is there anyway that can identify the unkown object if the score value is below the set threshold?

**Comment by mdouze** [comment]
I don't understand the quetion.
