### ISSUE TITLE
Does FAISS support Win32?

### ISSUE THREAD

**Issue by liulangdeyeshou** [facebookresearch/faiss#1886]
# Summary

# Platform

OS: win10(x64)

IDE：Visual studio 2019

Faiss version: 1.7.0

Installed from: build from source

Faiss compilation options: using MKL with compile flags

Running on:
- [* ] CPU

Interface: 
- [*] C++

# Reproduction instructions

Cmake command:
cmake -B build . -DMKL_LIBRARIES="C:\Program Files (x86)\Intel\oneAPI\mkl"  -DBLA_VENDOR=Intel10_32 \

After executing cmake, I get a faiss.sln.
Next, I tried to compile the Win32 FAISS project in Visual Studio.However, the following error message is printed:

'''
Generation started...
1&gt;------ Build: Project: FAISS, Configuration: Release Win32
1>AutoTune.cpp
1>D:\Projects\faiss_1.7\faiss\faiss/impl/platform_macros.h(37,5): error C3861: “_BitScanForward64”: The identifier was not found
1>D:\Projects\faiss_1.7\faiss\faiss/impl/platform_macros.h(51,17): error C3861: “__lzcnt64”: The identifier was not found
1>Clustering.cpp
1>D:\Projects\faiss_1.7\faiss\faiss/impl/platform_macros.h(37,5): error C3861: “_BitScanForward64”: The identifier was not found
1>D:\Projects\faiss_1.7\faiss\faiss/impl/platform_macros.h(51,17): error C3861: “__lzcnt64”: The identifier was not found
1>IVFlib.cpp
1>D:\Projects\faiss_1.7\faiss\faiss/impl/platform_macros.h(37,5): error C3861: “_BitScanForward64”: The identifier was not found
......
'''
My question is:
(1) Does FAISS support Win32?
(2) If yes, is the above compilation operation correct?Did I incorrectly configure some options in Visual Studio?would you provide standard steps for compiling FAISS Win32 libraries?
In addition, my operating system is 64-bit, will this affect the library that builds Win32?Thank you very much.

**Comment by beauby** [comment]
No, at the moment Faiss only supports 64 bit.
