### ISSUE TITLE
Does Faiss support distributed system

### ISSUE THREAD

**Issue by deitycitian** [facebookresearch/faiss#189]
Hello, 
I have a  quetion. What if nb is too large ?  Doese Faiss support distribute system ? Or any  solutions about this case ?

**Comment by mdouze** [comment]
Hi 
Faiss can be distributed easily by sharding the database over several machines. 
However, there is no distributed Faiss implementation in the core library.

**Comment by deitycitian** [comment]
OK, thank you very much~

**Comment by MaggieX** [comment]
> Hello,
> I have a quetion. What if nb is too large ? Doese Faiss support distribute system ? Or any solutions about this case ?

Hello, may I know if you were able to run Faiss with Spark?

**Comment by eruzanski** [comment]
> Hi Faiss can be distributed easily by sharding the database over several machines. However, there is no distributed Faiss implementation in the core library.

Hi Matthijs, can you share some code or some reference with more details and example on how to easily distribute FAISS by sharding the database over several machines?

**Comment by wickedfoo** [comment]
> > Hi Faiss can be distributed easily by sharding the database over several machines. However, there is no distributed Faiss implementation in the core library.
> 
> Hi Matthijs, can you share some code or some reference with more details and example on how to easily distribute FAISS by sharding the database over several machines?

There may be some simple distributed wrappers out there, but https://milvus.io/ is also a distributed wrapper around Faiss, and some/most/all? code is on github, which may or may not serve your needs:

https://github.com/milvus-io/milvus/

**Comment by tomlincr** [comment]
Example of distributed faiss on Spark  using `autofaiss` here: https://github.com/criteo/autofaiss/blob/master/docs/distributed/distributed_autofaiss.md

**Comment by seabass011** [comment]
Do you think this would work on ~1 trillion tokens? I'm wondering if faiss or distributed-faiss would be better
