### ISSUE TITLE
Does hnsw or ivf support angular when constructing?

### ISSUE THREAD

**Issue by Kun-Ming** [facebookresearch/faiss#1892]
I am using python interface, but when I add param such as faiss.METRIC_INNER_PRODUCT or faiss.METRIC_L2 in construction function, like faiss.IndexHNSWSQ(), it raises error for too many parameters. But I found in c++ version, there are parameters for metric type. So Why I can't use them in python?

**Comment by mdouze** [comment]
```
index = faiss.IndexHNSWSQ(10, 0, 32, faiss.METRIC_INNER_PRODUCT)
index.metric_type
```
works for me.

**Comment by Kun-Ming** [comment]
Thanks for your help. While when I try these code, it raises error:
![image](https://user-images.githubusercontent.com/45357009/118927813-ebe60f80-b974-11eb-8746-6efb99a43eb3.png)
 I am using faiss 1.5.3.

**Comment by Kun-Ming** [comment]
Sloved after I install faiss through conda, which is faiss 1.7.0. I am using pip before. Hope you can update faiss package on pip, thanks!

**Comment by Kun-Ming** [comment]
Oh the name change to faiss-cpu which version is 1.7.0, not faiss. Thanks again
