### ISSUE TITLE
error when use ivfpq

### ISSUE THREAD

**Issue by boundles** [facebookresearch/faiss#19]
Faiss assertion err == cudaSuccess failed in char* faiss::gpu::StackDeviceMemory::Stack::getAlloc

**Comment by wickedfoo** [comment]
Can you provide context on what you were trying to run, or how to run it?

The above error typically occurs when you run out of GPU memory.

**Comment by boundles** [comment]
Yes, my data is too large.So, what's approach I could employ to solve the problem of limited gpu memory?Please give me some suggestions. Thanks.

**Comment by mdouze** [comment]
Hi, 

Please take a look at 

https://github.com/facebookresearch/faiss/blob/master/benchs/bench_gpu_sift1m.py#L85

and read 

https://github.com/facebookresearch/faiss/wiki/High-level-interface-and-auto-tuning#guidelines
