### ISSUE TITLE
IVF index may contain duplicate ids

### ISSUE THREAD

**Issue by ae86208** [facebookresearch/faiss#190]
As indicated by [remove](https://github.com/facebookresearch/faiss/blob/master/IndexIVF.cpp#L554) and [insert](https://github.com/facebookresearch/faiss/blob/master/IndexIVF.cpp#L240), if one first add data into index, then remove some of them, the add another bunch of data, all add operations do not contain ids, thus using default id = ntotal + i, results ids duplicate.

**Comment by mdouze** [comment]
Hi 
Yes IMO for remove and insert to make sense, `add_with_ids` should be used. Otherwise behavior on the self-assigned indices is not intuitive.
