### ISSUE TITLE
ubuntu 20.04 arm64v8a CUDA 10.2 compilation error

### ISSUE THREAD

**Issue by alborotogarcia** [facebookresearch/faiss#1916]
# Summary

# Platform

OS: 
ubuntu 20.04 arm64v8a-2 with CUDA 10.2
Faiss version: 
release v1.7.0 - 7c2d2388a492d65fdda934c7e74ae87acaeed066
release v1.7.1 - cff072b78ef019998990c6ba02df83dd7d3c8d38
Installed from:  
Compiled by my own with cmake 3.18
Faiss compilation options: 
mkdir build; cd build; cmake .. -DFAISS_ENABLE_GPU=ON -DCMAKE_CUDA_FLAGS="-gencode arch=compute_72,code=sm_72" -DCMAKE_CUDA_ARCHITECTURES=72; make -j8

Running on:
- [ ] CPU
- [ *] GPU

Interface: 
- [ *] C++
- [ *] Python

# Reproduction instructions

logs 

https://gist.github.com/alborotogarcia/3a2ab81e3570b33e10a6284ed0c2ea74

**Comment by alborotogarcia** [comment]
I can confirm it fails also v1.6.5
I've added the full 1.6.5. log 
https://gist.github.com/alborotogarcia/3a2ab81e3570b33e10a6284ed0c2ea74
Surprisingly v1.6.4 compiles.. However cuML needs v1.6.5+

**Comment by vorj** [comment]
@alborotogarcia Would you try to add `-DCMAKE_BUILD_TYPE=Release` on v1.7.1?

**Comment by alborotogarcia** [comment]
@vorj yass, thanks now it works!! though now I get the following error after compiling cuML 0.19 with faiss v1.7.1

`ImportError: /usr/local/lib/libcuml++.so: undefined symbol: _ZN5faiss3gpu5bfKnnEPNS0_20GpuResourcesProviderERKNS0_17GpuDistanceParamsE
`
Should I open a new Issue on rapids repo?

**Comment by alborotogarcia** [comment]
May this be related? #https://github.com/rapidsai/cuml/issues/3772

**Comment by lrtz-v** [comment]
> @alborotogarcia Would you try to add `-DCMAKE_BUILD_TYPE=Release` on v1.7.1?

it helps, on my ubuntu 20.04 aarch64, with faiss:v1.7.1
