### ISSUE TITLE
How to set efSearch when using index_factory like ",IVF65536_HNSW32,"?

### ISSUE THREAD

**Issue by YuxianMeng** [facebookresearch/faiss#1919]

**Comment by mdouze** [comment]
See 
https://github.com/facebookresearch/faiss/wiki/Index-IO,-cloning-and-hyper-parameter-tuning#parameterspace-as-a-way-to-set-parameters-on-an-opaque-index

**Comment by YuxianMeng** [comment]
Thanks for your help!
