### ISSUE TITLE
IVFPQ/PQ search returns **squared** L2 distances

### ISSUE THREAD

**Issue by billkle1n** [facebookresearch/faiss#192]
I noticed that when using the `faiss.METRIC_L2`, the L2 distances returned are squared. It's not necessarily a bug but it should at least be a bit better documented (I only found [one mention](https://github.com/facebookresearch/faiss/wiki/Faiss-building-blocks:-clustering,-PCA,-quantization#assignment) in the wiki of this) as I was intuitively [expecting](https://github.com/facebookresearch/faiss/issues/132#issuecomment-325782137) the function to return L2 distances. I think most people using the library would make that assumption too.

**Comment by mdouze** [comment]
Hi 
Yes that is right, it is to avoid extracting a square root.

**Comment by billkle1n** [comment]
Thanks. I'm not exactly sure but now that it's in the issues it is a bit more searchable.
