### ISSUE TITLE
Question about large indexes

### ISSUE THREAD

**Issue by vamossagar12** [facebookresearch/faiss#1921]
I was going through the documentation and stumbled upon this page:

https://github.com/facebookresearch/faiss/wiki/Indexes-that-do-not-fit-in-RAM

Here, the 3rd point mentions that one of the options is to

`store the index in a distributed key-value store.` 

The question that I have is how can I store the index in a KV store? My guess is that I will have to transform the structures in the KV store into something the in memory index can understand for the search APIs to work? Any pointers/architectural patterns would be helpful. I can use something like rocksdb which can store arbitrary byte arrays but how to stitch them together is something i wanted to understand.

Also, are there any apis available to know the in memory size of the index?

**Comment by vamossagar12** [comment]
hi.. any pointers here would be helpful...

**Comment by mdouze** [comment]
MAybe this 
https://github.com/facebookresearch/faiss/wiki/Inverted-list-objects-and-scanners
