### ISSUE TITLE
FAISS: GPU INDEX Parallel Queries

### ISSUE THREAD

**Issue by astar10239** [facebookresearch/faiss#1925]
Hi,

I am looking for a implementation of FAISS Over GPU

I have a very large index of 100 million embeddings and want real-time search on api, so i loaded in GPU.

But, it seems i cant execute parallel queries as its serving the API backend,

Can anyone help here.

Does Faiss Support Batch GPU Search (given each query is different)

# Platform

OS: Centos 7

Faiss version:  Latest

Installed from: HayStack
 

Running on:
- [ ] CPU
- [ X] GPU

Interface: 
- [ ] C++
- [X ] Python

**Comment by astar10239** [comment]
Hi,

Thank You for the reply,

Is batch query supported then ?

Or is there a way to Parallelize search on gpu, as there are 100million+ embedding to search and < 1sec is the expectation which can only be done on gpu, at the same time maintain concurrency

**Comment by mdouze** [comment]
yes batch is supported.

**Comment by astar10239** [comment]
> yes batch is supported.

Hi,

In batch search, can i search for different type of embeddings/queries

**Comment by mdouze** [comment]
unclear question
