### ISSUE TITLE
about split empty clusters

### ISSUE THREAD

**Issue by yykxx** [facebookresearch/faiss#1928]
Hi, When I read the code of clustering (**[split_clusters in Clustering.cpp](https://github.com/facebookresearch/faiss/blob/master/faiss/Clustering.cpp#L219)**), the method of split empty clusters confused me. 
Is there any theoretical guidance about this method or any advice to help me to understand the method?

Thanks for your great job!

**Comment by mdouze** [comment]
The cluster splitting code is heuristic. 
Its advantages are: 

- it does not need to access the training points (useful in distributed context)

- the splitting of a cluster does not impact neighboring clusters (because it is only an epsilon perturbation of the centroid)

**Comment by yykxx** [comment]
Thanks for your reply!
