### ISSUE TITLE
PCAMatrix segfault

### ISSUE THREAD

**Issue by bkj** [facebookresearch/faiss#193]
I'm getting errors calling `faiss.PCAMatrix` from python when when the matrix has a sufficiently large number of columns. 

This works:

```
>>> z = np.random.uniform(0, 1, (1000, 100000)).astype('float32')
>>> pca_matrix = faiss.PCAMatrix(100000, 512) 
>>> pca_matrix.train(z)
>>>
```

but this throws an error:

```
>>> z = np.random.uniform(0, 1, (1000, 250000)).astype('float32')
>>> pca_matrix = faiss.PCAMatrix(250000, 512) 
>>> pca_matrix.train(z)
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Aborted (core dumped)
```

and this throws a different error:

```
>>> z = np.random.uniform(0, 1, (1000, 262144))
>>> z = z.astype('float32')
>>> pca_matrix = faiss.PCAMatrix(262144, 512) 
>>> pca_matrix.train(z)
Segmentation fault (core dumped)
```

Any ideas?

Thanks

**Comment by mdouze** [comment]
Hi

Even in the Gram matrix case, the full PCA matrix is allocated

https://github.com/facebookresearch/faiss/blob/master/VectorTransform.cpp#L376

This is not useful, since only the n first lines are used.

**Comment by mdouze** [comment]
Today's update should fix this bug.
