### ISSUE TITLE
k-means clustering by Inner Product

### ISSUE THREAD

**Issue by yykxx** [facebookresearch/faiss#1934]
Under Inner Product, the coarse quantizer of IndexIVFFlat is IndexFlatIP (at default). 
After that, the metric for k-means training is Inner Product and the centroids will be normalized, but the train points will not be normalized automatically. 

Q1: Does the train points must be normalized before we invoke Index::train() ?
Q2: Does the approach is the same as [spherical k-means clustering ](https://ieeexplore.ieee.org/document/1556436)? 

Thanks for your great job!

**Comment by mdouze** [comment]
Q1 no
Q2 spherical clustering in the Faiss context just means that the centroids are L2 normalized at each iteration.

**Comment by netw0rkf10w** [comment]
> Q2 spherical clustering in the Faiss context just means that the centroids are L2 normalized at each iteration.

@mdouze Regarding spherical clustering, as I understand, only the centroids are L2-normalized but not the input. Thus, we need to L2-normalize the data before feeding it to `faiss.Kmeans`. Is that correct?
