### ISSUE TITLE
cmake -B build .

### ISSUE THREAD

**Issue by monsters-s** [facebookresearch/faiss#1939]
When I use 'cmake -B build .' then have these questions .
-- Could NOT find MKL (missing: MKL_LIBRARIES) 
CMake Deprecation Warning at _deps/googletest-src/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at _deps/googletest-src/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/lishengwen/faiss

AND when I use 'conda list', I can find mkl as:
mkl                       2021.2.0                 pypi_0    pypi
mkl-service               2.3.0            py37h27cfd23_1  
mkl_fft                   1.3.0            py37h42c9631_2  
mkl_random                1.2.1            py37ha9443f7_2

**Comment by beauby** [comment]
Most probably your MKL installation is not in a directory visible by the linker by default. You should used the `-DMKL_ROOT=/path/to/mkl/directory` CMake parameter.
