### ISSUE TITLE
when use INNER_PRODUCE the distances is very big like 28127331831?

### ISSUE THREAD

**Issue by shaocongliang** [facebookresearch/faiss#194]
I met a situation when I use IndexIVFFlat and INNER_PRODUCT model to do a search, after the searching the distances is very big. this is possible?

**Comment by billkle1n** [comment]
Not sure if that helps but if the corresponding IDs are -1 you should ignore those results.

**Comment by shaocongliang** [comment]
the corresponding ID is not -1 

- 589246 2.9847e+14

I am sure I use INNER_PRODUCT
