### ISSUE TITLE
faiss-swigfaiss ValueError: array is not C-contiguous

### ISSUE THREAD

**Issue by vaneshieh** [facebookresearch/faiss#1941]
# Summary
Hi: When I try to use faiss index search, I got the following error:
"
    distances, indices = self.index.search(embedding, k)
  File "/opt/anaconda3/lib/python3.8/site-packages/faiss/__init__.py", line 301, in replacement_search

    self.search_c(n, swig_ptr(x), k, swig_ptr(D), swig_ptr(I))
  File "/opt/anaconda3/lib/python3.8/site-packages/faiss/swigfaiss.py", line 5700, in swig_ptr

    return _swigfaiss.swig_ptr(a)
ValueError: array is not C-contiguous

"

Appreciate any help!

OS: macOS blur 11.4
Faiss version: faiss-cpu     1.7.1                   
Installed from: anaconda pip
Running on:
- [ ] CPU
Interface: 
- [ ] Python

**Comment by vaneshieh** [comment]
Make input into c-contiguous impulsively

**Comment by albertma-evotec** [comment]
> Make input into c-contiguous impulsively

Sorry, but how exactly? Is it a function that I can apply on an numpy array? 
Thanks

**Comment by scarletteshu** [comment]
> Make input into c-contiguous impulsively

did you solve this problem? I've got the same question.

**Comment by adithya44** [comment]
Specifying order='C' parameter in np.array helped me solve this problem. 
eg : np.array(input_data,order='C').astype('float32')
