### ISSUE TITLE
Access to faiss index from others script python.

### ISSUE THREAD

**Issue by nguyenkhacduyngoc** [facebookresearch/faiss#1944]
# Summary
I'm new to this library so i want to ask about how to use faiss index. 
I'm using faiss-cpu python and i want access faiss database from different script. 
i'm using flask api with blueprint  to handle it and split my code to multiple router files. So if i want to use index i have to init it in to all this files. I want to find a method to access to same index at same time, maybe same way we connect to mysql or other databases as well. (Now when use it in another files, it create new instance of faiss index)

Another question is how to serving faiss efficiency in my application. My project is computer vision and process live stream frame from camera. I use faiss as API and it's a little bit slow. And my faiss include use api for create, update, delete and use for searching continously frame by frame on my App. It's really hard. Can you help me resolve it

# Platform

OS: Ubuntu 18.04

Faiss version: 1.6.3

Installed from: pip

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by mdouze** [comment]
Faiss is a library not a server daemon. 
If you want to access the same index from several processes, you should use a server on top of Faiss. Perhaps Milvus could do that, see https://milvus.io/

**Comment by nguyenkhacduyngoc** [comment]
I got it. Thanks you.
