### ISSUE TITLE
Save direct map for quick loading

### ISSUE THREAD

**Issue by JamesDeAntonis** [facebookresearch/faiss#1948]
# Summary

I have a large IVFPQ index, which takes 18 seconds to read.  For my task, I need to reference ids directly using `DirectMap`.  For this, I run `make_direct_map()`, which takes 75 seconds and I have to do it every time I load the index.  I would like a way to save this mapping so that it can be loaded quickly instead of remade every time.  That doesn't exist, correct?  Is there any way this can be added in the future?

# Reproduction instructions

Load any faiss index, then run `index.make_direct_map()` and notice there is no way to save it for the future; `make_direct_map` must be called every time.

**Comment by dichen-cd** [comment]
Hi @JamesDeAntonis, did you find the solution? Thanks.

**Comment by fferroni** [comment]
Hi @JamesDeAntonis , what was your solution?

**Comment by fabiozappo** [comment]
Hi @JamesDeAntonis , any update on your solution?
