### ISSUE TITLE
Will searching be faster if I merge these small indexes into a bigger one?

### ISSUE THREAD

**Issue by splinter21** [facebookresearch/faiss#1949]
Total ntotal (sum of each indexes) is about 4e9. (Now there are 4 small indexes and ntotal of each one is about 1e9).
Index factory: PCAR96_IVF12288_PQ48
There are about (2e8,512) features to search every day. (512: dim number before PCA, 2e8: number of imgs)
CPU of this machine: 4800%(24 cores)

environment：
Debian 4.9.144-3 (2019-02-02)
faiss-cpu==1.7.0
py3.6

**Comment by mdouze** [comment]
It is usually faster to search a merged index that individual indexes because the coarse quantization overhead is factorized. 
The IVF size seems too small for the 1B vectors, please use at least 100k.
