### ISSUE TITLE
make -C build -j faiss

### ISSUE THREAD

**Issue by monsters-s** [facebookresearch/faiss#1955]
when I use "make -C build -j faiss",there is a problem:
make: Entering directory '/home/lishengwen/faiss/build'
make: *** No rule to make target 'faiss'.  Stop.
make: Leaving directory '/home/lishengwen/faiss/build'
I have use execute “cmake -B build .”  and directory "build" is empty.
Though the step2 is wrong, but I have the same result as showing when I execute:

import numpy as np
d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

import faiss                   # make faiss available
index = faiss.IndexFlatL2(d)   # build the index
print(index.is_trained)
index.add(xb)                  # add vectors to the index
print(index.ntotal)

k = 4                          # we want to see 4 nearest neighbors
D, I = index.search(xb[:5], k) # sanity check
print(I)
print(D)
D, I = index.search(xq, k)     # actual search
print(I[:5])                   # neighbors of the 5 first queries
print(I[-5:])                  # neighbors of the 5 last queries

I don't know if I am successful.

**Comment by r00tk1ts** [comment]
I encountered the same problem after executing "cmake3 build -B . -DFAISS_ENABLE_GPU=OFF -DFAISS_ENABLE_PYTHON=OFF -DBLA_VENDOR=Intel10_64_dyn -DMKL_LIBRARIES=/opt/intel/mkl/lib/intel64_lin/*.so -DCMAKE_BUILD_TYPE=Release -DFAISS_OPT_LEVEL=avx2"
