### ISSUE TITLE
Not getting 100% recall with Flat Index

### ISSUE THREAD

**Issue by aamirbutt** [facebookresearch/faiss#1956]
# Summary

I have 2 vectors which are 512 dimension and differ from each other only after 6th place of decimals for each value. For such vectors, FAISS search doesn't give a perfect recall. I am attaching a sample program and data that demonstrates the problem.

Running on:
- [x] CPU

Interface: 
- [x] Python

# Reproduction instructions

Attaching a sample python program and a small data file that demonstrates the issue.

[faiss-issue.zip](https://github.com/facebookresearch/faiss/files/6685187/faiss-issue.zip)

**Comment by mdouze** [comment]
Computations are done in float32 precision, so if the vectors differ only in the lower bits, the precision gets lost.
