### ISSUE TITLE
Faiss-GPU in windows

### ISSUE THREAD

**Issue by eonseo-choi** [facebookresearch/faiss#1957]
Hi, i'm trying to use Faiss-GPU in windows without conda 
faiss-cpu is work, but gpu didnt 
is there any way to use Faiss-GPU in windows ?? 
i wanna use it without conda if possible.
thanks

OS: windows 10

Running on:
 GPU

Interface: 
 Python

**Comment by GabrielaMichelon** [comment]
I would also be highly interested in a solution to use faiss-gpu on windows.
