### ISSUE TITLE
KMeans objective function

### ISSUE THREAD

**Issue by diaoyingyu** [facebookresearch/faiss#1962]
# Summary

# Platform

OS: Linux Ubuntu

Faiss version: 1.7.0

Installed from: pip install

Faiss compilation options: CUDA

Running on:
GPU

Interface: 
Python

https://github.com/facebookresearch/faiss/blob/7cce100c92e45427f46d912f625bcb9b6cb85ed3/faiss/Clustering.cpp#L441
https://github.com/facebookresearch/faiss/blob/7cce100c92e45427f46d912f625bcb9b6cb85ed3/faiss/Clustering.cpp#L475-L478
Why use float number to calculate total distance here?  When the cumulative result exceeds 2^23 and each distance is small (e.g. 0.3), float and double result differ greatly.

**Comment by mdouze** [comment]
Fair point. If you submit a PR to correct this, I'll accept it.
