### ISSUE TITLE
search based two vector

### ISSUE THREAD

**Issue by hongyuntw** [facebookresearch/faiss#1968]
# Summary

if I have a question vector q, and all documents have each two vectors d1 , d2 , can faiss do calculate score based
```
max(q dot d1 , q dot d2)
````
thank you

# Platform

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by KinglittleQ** [comment]
You could create two indexes for `q dot d1` and `q dot d2` respectively and merge the results at the end.
