### ISSUE TITLE
Remove from sub-index inside IndexIDMap?

### ISSUE THREAD

**Issue by kormalev** [facebookresearch/faiss#1970]
I have an `IndexFlatL2` wrapped by `IndexIDMap` / `IndexIDMap2`. Multiple inner vectors may be mapped to the same ID in the outer index (think class ID).

Is there a way to remove a single vector by its original ID in the sub-index, keeping the wrapper in sync?

The only idea I could come up with so far is to remove all vectors of this class, and then re-add them, except for the one to be deleted.

**Comment by mdouze** [comment]
No, this is not really supported, IndexIDMap assumes the vector ids are distinct.
