### ISSUE TITLE
Reset doesn't free GPU Memory when clustering_index is used

### ISSUE THREAD

**Issue by oubathAI** [facebookresearch/faiss#1971]
# Summary

# Platform

OS:  Ubuntu 18.04

Faiss version:  1.7.1

Installed from:   Anaconda

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

I'm building a lot of faiss indexes through a loop. However, my program always stops because of a Cuda Out of Memory, even when I use reset() after each creation. The GPU memory is not released only when I'm executing this line `
index_ivf.clustering_index = clustering_index` 

Here is a simple code to reproduce the issue:

```
import faiss

def loop_index_creation(with_clustering_index_assignment,nb_indexes=20):
    for i in range(nb_indexes):
        index = faiss.index_factory(128, "OPQ16_64,IVF16384_HNSW32,PQ64")

        index_ivf = faiss.extract_index_ivf(index)

        clustering_index = faiss.index_cpu_to_all_gpus(faiss.IndexFlatL2(index_ivf.d))

        if with_clustering_index_assignment:
            index_ivf.clustering_index = clustering_index

        clustering_index.reset()


print("Loop 1: without assigning index_ivf.clustering_index")
loop_index_creation(with_clustering_index_assignment=False)
print("Loop 1 done")

print("Loop 2: with assigning index_ivf.clustering_index")
loop_index_creation(with_clustering_index_assignment=True)
print("Loop 2 done")
```

As you'll see if you execute this code, the loop 1 has no issue, but the loop 2 never release GPU memory and will eventually throw a Cuda memory error. 

How can I free the GPU memory when using  `index_ivf.clustering_index `  ?

Thanks in advance

**Comment by mdouze** [comment]
Do you plan to do the training inside the loop? 

If no: the clustering_index is used only during training and setting it does not keep track of references, so the program will crash if train is called outside the loop.

If yes: you can just instantiate the clustering_index outside the loop and re-use it for all trainings.

The reason why it is OOMing: the index_cpu_to_all_gpus allocates a good chunk of GPU memory for the GPU resources + the python GC is a bit lazy (don't hesitate to call gc.collect() from time to time).

**Comment by oubathAI** [comment]
Thanks for your reply.
Yes I'm plan to do the training inside the loop; the real code I have is a function creating an index and saving it ; and this function is called inside a loop. The real code looks like:
```
def build_and_save_index(data,save_path):
    index = faiss.index_factory(128, "OPQ16_64,IVF16384_HNSW32,PQ64")
    index_ivf = faiss.extract_index_ivf(index)
    clustering_index = faiss.index_cpu_to_all_gpus(faiss.IndexFlatL2(index_ivf.d))
    index_ivf.clustering_index = clustering_index
    x_train = ohlc_norm_array[sampling_indexes]
    index.train(data)
    index.add(data)
    faiss.write_index(index, save_path)


for data,save_path in zip(data_list,save_path_list):
    build_and_save_index(data,save_path)
```
I tried with `gc.collect()` to free the memory; but it doesn't change anything.

So you're saying that I should rewrite my code like this?
```
clustering_index = faiss.index_cpu_to_all_gpus(faiss.IndexFlatL2(64))
def build_and_save_index(data,save_path,clustering_index=clustering_index):
    index = faiss.index_factory(128, "OPQ16_64,IVF16384_HNSW32,PQ64")
    index_ivf = faiss.extract_index_ivf(index)
    index_ivf.clustering_index = clustering_index
    x_train = ohlc_norm_array[sampling_indexes]
    index.train(data)
    index.add(data)
    faiss.write_index(index, save_path)


for data,save_path in zip(data_list,save_path_list):
    build_and_save_index(data,save_path)

```

When I do it this way, there's no OOM; but my concerns is that if I use the same clustering_index would the previous training results wouldn't affect the next ones  ? since all the indexes I build are differents.
