### ISSUE TITLE
Why does IndexIVFPQFastScan support only 4-bits-per-index cases?

### ISSUE THREAD

**Issue by sunhongmin225** [facebookresearch/faiss#1973]
# Summary

In the beginning of IndexIVFPQFastScan.cpp, it checks for `FAISS_THROW_IF_NOT(nbits_per_idx == 4);`. It seems that FastScan shows better performance than normal IndexIVF search since it sorts QC with coarse list number beforehand. If this is the case, why is FastScan only applied to cases where it requires 4-bits per index? Is it also worth considering to apply this technique, sorting the queries beforehand based on coarse quantization results, to other cases, e.g., 8-bits-per-index cases, as well?

# Platform

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

**Comment by mdouze** [comment]
The difference with the default PQ implementation is that the look-up tables are stored in registers, but registers are too small to host 256-entry LUTs.

**Comment by sunhongmin225** [comment]
I see. Thanks for your reply.
