### ISSUE TITLE
python get_nearest_examples does not work on macos due to libomp

### ISSUE THREAD

**Issue by nicholasprayogo** [facebookresearch/faiss#1977]
Hi. This is pertaining to the huggingface functionality get_nearest_exampes with faiss. I think this is a very important issue since index query does not work on macos due to conflict of the libomp.dylib used by faiss vs libiomp5.dylib used by pytorch. It returns an error similar to this https://github.com/peterwittek/somoclu/issues/135 

The solutions so far simply ignore the warning, but upon ignoring the warning of multiple OpenMP runtimes running, segmentation fault 11 occurs. 

May I know if there can be a quick fix for this? Thanks.

**Comment by mdouze** [comment]
Did you install Faiss and Pytorch with conda?

**Comment by nicholasprayogo** [comment]
> Did you install Faiss and Pytorch with conda?

I installed with pip because I had issues installing with conda. Is installing with pip supported? Thanks

**Comment by mdouze** [comment]
it's not
