### ISSUE TITLE
GPU build fails with MKL

### ISSUE THREAD

**Issue by una-dinosauria** [facebookresearch/faiss#198]
Specifically, this line will fail:

```make
test/demo_ivfpq_indexing_gpu: test/demo_ivfpq_indexing_gpu.cpp \
	$(LIBNAME).a ../libfaiss.a
	$(NVCC) $(NVCCFLAGS) -o $@ $^ -Xcompiler -fopenmp -lcublas \
	$(BLASLDFLAGSNVCC)
```

With the error:

```
ar: creating libgpufaiss.a
/usr/local/cuda-8.0/bin/nvcc  (many flags)
-Xlinker -Wl,--no-as-needed -L/opt/intel/compilers_and_libraries/linux/mkl//lib/intel64   -lmkl_intel_ilp64 -lmkl_core -lmkl_gnu_thread -ldl -lpthread
/usr/bin/ld: unrecognized option '-Wl'
```

This is because

`BLASLDFLAGSNVCC=-Xlinker $(BLASLDFLAGS)`, and

`BLASLDFLAGS=-Wl,--no-as-needed -L$(MKLROOT)/lib/intel64   -lmkl_intel_ilp64 \
 -lmkl_core -lmkl_gnu_thread -ldl -lpthread`

from `makefile.inc` when one is compiling with MKL.

However, `nvcc` does not recognize the `-Wl,--no-as-needed` option ([see the second comment under this SO post](https://stackoverflow.com/a/7221187/1884420)).

I am not sure what the best option here is. Deleting `-Wl,--no-as-needed` works for me, but I guess we could also add an extra variable? I'll submit a PR with the solution that worked for me, but let me know if you know of a better way.

**Comment by ducha-aiki** [comment]
@una-dinosauria  unfortunately, nor deleting, nor as is, doesn`t work for me :(
