### ISSUE TITLE
FAISS Index Not loading on GPU 

### ISSUE THREAD

**Issue by astar10239** [facebookresearch/faiss#1981]
# Summary

So what i did was simply

faiss_index = faiss.IndexFlatL2(256 )
for i in range(20):
    faiss_index.add(np.random.rand(1000000, 256 ).astype('float32'))
 

This should create a index of 20 million random numbers at float 32 and 256 Dim

Which takes around 20GB Space in Ram/Disk

When ever i try to put this index in my GPU (32GB)

res = faiss.StandardGpuResources()
c = faiss.GpuClonerOptions()
c.yseFloat16=True
gpu_index = faiss.index_cpu_to_gpu(res, 0, faiss_index, c)

I get RuntimeError : Error in Virtual Void Alloc Memory Error

I dont know but its very weird.

I have a 32GB GPU 

it works fine with 10 or so far 15 million embedding, with size approx 10-15gb

Strangly as i monitor i see the GPU going till 18 and then coming to 0 with the Memory Failure 

Then whats the problem with 20 ?

Also i noticed even i try a small index let say 5GB, GPU Suddenly Takes 10GB and then comes down to 5GB.

# Platform

Centos 7 |  122GB Ram | Tesla V100 32GB

Faiss version: Latest

Installed from: pip

Running on:
- [ ] CPU
- [ X] GPU

Interface: 
- [ ] C++
- [ X] Python

**Comment by mdouze** [comment]
Have you tried adding the vectors to the index instead of moving the index from CPU to GPU?

**Comment by phanxuanduc1996** [comment]
I used Anaconda, I installed bellow, it worked. If you use Docker, please install Miniconda.
`conda install faiss-gpu cudatoolkit=11.1 -c pytorch-gpu`
`conda install -c anaconda pytorch-gpu`
