### ISSUE TITLE
Question about Faiss quantization

### ISSUE THREAD

**Issue by MrWWheat** [facebookresearch/faiss#1984]
Hi,

Currently I am using IndexPQ and IndexIVFPQ, and looks like when I increase the n_bits, I can get better accuracy. I am just wondering why increase the n_bits will increase the accuracy? Is it because for each sub_vec set, we can generate more centroids?

Appreciate for any help or any docs! Thanks!

**Comment by wickedfoo** [comment]
> Is it because for each sub_vec set, we can generate more centroids?

yes, there are 2^n_bits PQ centroids per each subspace generated, thus higher reproduction fidelity
