### ISSUE TITLE
inconsistent query results

### ISSUE THREAD

**Issue by dongxiao92** [facebookresearch/faiss#1985]
# Summary

I tried two searches with the same query while different Ks. The second search uses K1 which is less than K0 used by the first search. As both use the same query and same library, I assume the result of the second search should be part of the first result(topK1 should be part of topK0). 

The code is shown below. I compare the result indices and count how many pairs are same. I assume it will print 1000000(i.e., 10000 queries * top100) as the result of second query should be the first 100 columns of the result of first query. But actually I got 999892.
I'm not sure if this relates to precision loss as the feature dimension is just 256 and I use the fp32 datatype. Did I use any  APIs wrong?

Faiss version: 1.7.1
Installed from: anaconda

Faiss compilation options: N/A

Running on:
- GPU

Interface: 
-  Python

# Reproduction instructions
```
import numpy as np
import faiss
query = np.random.randn(10000, 256).astype('float32')
reference = np.random.randn(1000000, 256).astype('float32')


index = faiss.IndexFlatL2(query.shape[1])
index.add(reference)
D, I = index.search(query, 10000)

D_100, I_100 = index.search(query, 100)

a = np.sum(I_100 == I[:,:100])
print(a)
```

**Comment by mdouze** [comment]
There are probably a few ties in distances (may or may not be due to floating point roundoff errors)

**Comment by dongxiao92** [comment]
@mdouze thanks for your reply. Do you have any advises on this?
