### ISSUE TITLE
Help to compile FAISS for iOS would be greatly appreciated

### ISSUE THREAD

**Issue by teticio** [facebookresearch/faiss#1986]
# Summary

I'm trying to get FAISS to work on an iPhone / iPhone simulator. I am using Kivy-iOS and have written a "recipe" which seems to be mostly working, but I am hitting an error on importing.

# Platform

OS: iOS 14.4

Faiss version: 1.7.1

Installed from: compiled by me 

Faiss compilation options: no GPU, no AVX2, BLA_VENDOR=Apple

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

If you are familiar with building for iOS using Kivy, you can use my fork of Kivy-iOS (https://github.com/teticio/kivy-ios) with the recipes for openmp and faiss and add the requirement for faiss to your Buildozer.spec file. When I "import faiss" I get the following error:

```
ImportError: dynamic module does not define module export function (PyInit_faiss__swigfaiss)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
ImportError: dynamic module does not define module export function (PyInit__swigfaiss)
```

Nevertheless, if I run the following commands in a shell, I get:
```
$ nm /path/to/_swigfaiss.so | c++filt -p -i | grep PyInit
0000000000003570 T _PyInit__swigfaiss
00000000004bcc80 double PyInit__swigfaiss::SWIG_module

$ lipo -info /path/to/_swigfaqiss.so
Non-fat file: /path/to/_swigfaiss.so is architecture: x86_64

$ otool -l /path/to/_swigfaiss.so | grep IPHONEOS
      cmd LC_VERSION_MIN_IPHONEOS
```
Which, I believe, shows that the library is correctly built for the iPhone Simulator and exports PyInit_faiss__swigfaiss.

Are there any other things I can do to test _swigfaiss.so that might help me home in on the problem? I have managed to build, import and run it for MacOS without any issues. My recipe for building FAISS tries to follow the same steps that conda performs (https://github.com/facebookresearch/faiss/tree/master/conda) - you can see my code here : https://github.com/teticio/kivy-ios/blob/master/kivy_ios/recipes/faiss/__init__.py

Any help would be much appreciated!! Thanks

**Comment by teticio** [comment]
By the way, I found a workaround. I've still no idea why I have to do this - it is probably more to do with iOS and Kivy than it is to do with FAISS and SWIG, but hey. I used ```ctypes``` to import the shared object as a module manually.

```
--- faiss-1.7.1/_build_python/swigfaiss.py      2021-07-19 13:55:09.000000000 +0100
+++ faiss-1.7.1/_build_python/swigfaiss-patched.py      2021-07-19 13:55:33.000000000 +0100
@@ -9,10 +9,12 @@
     raise RuntimeError("Python 2.7 or later required")
 
 # Import the low-level C/C++ module
-if __package__ or "." in __name__:
-    from . import _swigfaiss
-else:
-    import _swigfaiss
+import os
+import ctypes
+dll = ctypes.PyDLL('../lib/python3.9/site-packages/faiss/_swigfaiss.so')
+init = dll.PyInit__swigfaiss
+init.restype = ctypes.py_object
+_swigfaiss = init()
 
 try:
     import builtins as __builtin__
```

**Comment by mdouze** [comment]
I'm afraid we don't have too much expertise on this, but thanks for trying!

Another problem that was reported before on iOS is that the BLAS wrapping conventions are not the same

https://github.com/facebookresearch/faiss/projects/3

**Comment by aehlke** [comment]
how have you found this in the time since @teticio ? is it working well with your workarounds? I also want to embed it in iOS and macOS. thanks.

**Comment by teticio** [comment]
Nah, sorry. I moved on to other things. It sounded too like too much
effort. Good luck!
