### ISSUE TITLE
Dose concurrent save/reconstrut supported?

### ISSUE THREAD

**Issue by Texas-NO1** [facebookresearch/faiss#1987]
# Summary
Can reconstruct and add_with_ids be executed concurrently? It is possible that both methods will operate on the same id.

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
no, see https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls

**Comment by Texas-NO1** [comment]
> no, see https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls

ok, thanks
