### ISSUE TITLE
there is a problem when set the parameter parallel_mode is 2 

### ISSUE THREAD

**Issue by Aurevoir-68** [facebookresearch/faiss#1988]
# Summary

# Platform

OS: Centos8.2

Faiss version: faiss 1.6.3

Installed from:  

Faiss compilation options: docker

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

 

When I run the program tutorial/cpp/2-IVFFlat.cpp, I set the parameter parallel_ mode = 2, an error occurred during searching. The error information is as follows：

**terminate called after throwing an instance of 'faiss::FaissException'
terminate called recursiely**

I set the parameter parallel_ mode = 0 or 1 ，there is no problem. 

Look forward to your reply！！！

**Comment by mdouze** [comment]
Could you try to run with a single Openmp thread so that the exception is propagated properly?
