### ISSUE TITLE
`reconstruct_n` is slow for large indexes

### ISSUE THREAD

**Issue by JamesDeAntonis** [facebookresearch/faiss#1990]
# Summary

# Platform

OS: 

Faiss version: 1.7.0

Installed from: pip

Faiss compilation options: None

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

(1) load an ivfpq faiss index with `self.ntotal` on the order of 2.5 billion
(2) load the direct map (`idx.make_direct_map()`)
(3) observe that `idx.reconstruct_n(0, 10)` is slower than `[idx.reconstruct(i) for i in range(10)]`

**Comment by mdouze** [comment]
Yes, reconstuct_n systematically scans the whole index. So it is efficient only when reconstructing a significant subset of the index. 
https://github.com/facebookresearch/faiss/blob/master/faiss/IndexIVF.cpp#L809
