### ISSUE TITLE
Error of remove ids not implemented for this type of index IVF1024,PQ64x4fs,RFlat

### ISSUE THREAD

**Issue by nvlong21** [facebookresearch/faiss#1991]
# Summary
Hi,
I'm using this setup with conda: faiss version 1.7.3 running on CPU
When I try to run remove_ids with "IVF1024,PQ64x4fs,RFlat" I get this error:
RuntimeError: Error in virtual size_t faiss::Index::remove_ids(const faiss::IDSelector&) at /__w/faiss-wheels/faiss-wheels/faiss/faiss/Index.cpp:43: remove_ids not implemented for this type of index

Does anyone know what can be the problem?

# Platform

OS: ubuntu 20.04

Faiss version: 1.7.3

Running on: CPU

Interface: Python

**Comment by mdouze** [comment]
as the message says, it is not implemented.
