### ISSUE TITLE
Question about IVF accuracy

### ISSUE THREAD

**Issue by phosphorylation** [facebookresearch/faiss#1999]
Hi,
I was a bit surprised when testing IVF indexes accuracy. Turns out when you train, add and search on the same set of data, you always get 100% accuracy. On a 1M dataset, I can go for nprobe=1, k=1, nlist = a few thousands, and that still gives me 100%! This even goes for PQ and SQ, which confuses me even further. Shouldn't the quantization introduce some error when calculating distance? Moreover, if the centroids is an average over many vectors, How did the query always land in the correct cluster on the first hit?

**Comment by mdouze** [comment]
hmmm that seems weird indeed. What code do you use?

**Comment by phosphorylation** [comment]
here's the testing code, it's based on a recent master (last pulled in a month).

`
#include <cstdio>
#include <cstdlib>
#include <random>
#include <iostream>

#include <faiss/IndexFlat.h>
#include <faiss/IndexIVFPQ.h>
#include <faiss/index_io.h>
#include <faiss/IndexIVFFlat.h>
#include <faiss/IndexScalarQuantizer.h>
#include <chrono>

using namespace std;

int main() {
    // dimension of the vectors to index
    int d = 64;

    // size of the database we plan to index
    size_t nb = 100000;

    // make a set of nt training vectors in the unit cube
    // (could be the database)
    size_t nt = 100000;

    // make the index object and train it
    faiss::IndexFlatL2 index_gt(d);
    faiss::IndexFlatL2 coarse(d);
    //faiss::IndexIVFScalarQuantizer index(&coarse,d,10000,faiss::ScalarQuantizer::QT_4bit);
    faiss::IndexIVFPQ index(&coarse,d,1024,16,8);

    std::mt19937 rng;
    std::uniform_real_distribution<> distrib;
    using namespace std::chrono;

        std::vector<float> trainvecs(nt * d);
        for (size_t i = 0; i < nt * d; i++) {
            trainvecs[i] = distrib(rng);
        }
        index.verbose = true;

        milliseconds ivfbegin = duration_cast< milliseconds >(system_clock::now().time_since_epoch());
        index.train(nt, trainvecs.data());
        milliseconds ivfend = duration_cast< milliseconds >(system_clock::now().time_since_epoch());

        std::vector<float> database(nb * d);
        for (size_t i = 0; i < nb * d; i++) {
            database[i] = trainvecs[i];
        }

        index.add(nb, database.data());
        index_gt.add(nb, database.data());


    int nq = 10000;

    { // searching the database

        std::vector<float> queries(nq * d);
        for (size_t i = 0; i < nq * d; i++) {
            queries[i] = trainvecs[i];
        }


        index.nprobe = 1;
        int k = 1;
        std::vector<faiss::Index::idx_t> nns(k * nq);
        std::vector<float> dis(k * nq);
        std::vector<faiss::Index::idx_t> gt_nns(nq * k);
        std::vector<float> gt_dis(nq * k);

        index_gt.search(nq, queries.data(), k, gt_dis.data(), gt_nns.data());
        index.search(nq, queries.data(), k, dis.data(), nns.data());

        float ivf =0;

        for (int q = 0; q < nq; q++) {
            cout<<"standard  result "<<gt_nns[q*k]<<"\n";
            cout<<"ivf result"<<nns[q*k]<<"\n";
            for (int i = 0; i < k; i++) {
                if (gt_nns[q * k] == nns[q * k+i]) {
                    ivf += 1;
                }
            }
        }
        std::cout<<"ivf acc:"<<ivf/nq;
    }
}
`

**Comment by Zhylkaaa** [comment]
Hey, I was about to open new issue, but topic seems suitable. I am trying to get maximum accuracy from IVFFlat indexer, because I would love to integrate it into DPR for datasets that cannot fit into RAM. So I thought that using `index = faiss.index_factory(vectors.shape[1], "IVF1,Flat", faiss.METRIC_INNER_PRODUCT)` should work as `IndexFlatIP` because 1 centroid will give me 1 giant Voronoi cell, but I am actually getting accuracy about `0.99778`. Which is not the case for L2 metric. 
I know that this is a bit hacky solution and this is not the intended usage, but maybe someone can help me with this? Or should I just use dot -> L2 transform and use L2 indexer?

P.S. The reason I am doing this is fact that IVF indexers can be mmaped and `IndexFlatIP` cannot (at least on my machine). 
faiss version: 1.7.0
installed via: conda 
OS: macOS 10.15.2

**Comment by phosphorylation** [comment]
@Zhylkaaa Hi, I'm guessing the 0.99778 is due to the way you're calculating accuracy. Are you using a groundtruth table produced in L2? in that case then you shouldn't expect IP result to match the L2 table. I'd suggest feeding the same dataset and query to a IndexFlatIP and your IVFFLatIP to see if you're getting 1 acc.

**Comment by Zhylkaaa** [comment]
Hi @phosphorylation, sorry I've added a bit of confusion, I am taking `IndexFlatIP` as a ground truth and compare results to `faiss.index_factory(vectors.shape[1], "IVF1,Flat", faiss.METRIC_INNER_PRODUCT)`.

You can test this with small example:
```
import faiss
import numpy as np
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'TRUE'

vecs = np.random.rand(10000, 768).astype('float32')
flat_index = faiss.IndexFlatIP(768)
flat_index.add(vecs)
index_ivf = faiss.index_factory(vecs.shape[1], "IVF1,Flat", faiss.METRIC_INNER_PRODUCT)
index_ivf.train(vecs)
index_ivf.add(vecs)

test_vecs = np.random.rand(1000, 768).astype('float32')
flat_results = flat_index.search(test_vecs, 100)
ivf_results = index_ivf.search(test_vecs, 100)

np.sum(np.array(flat_results[1]) == np.array(ivf_results[1])) / len(flat_results[1])
```

**Comment by mdouze** [comment]
Could you check if there are ties or very close distances?  The way the inner products are computed is a little different between Flat and IVF.
