### ISSUE TITLE
Is there a persistence function [python]?

### ISSUE THREAD

**Issue by HengDing890** [facebookresearch/faiss#20]
Hi everyone

whether there is a way to save cluster/index into a local file? 

For example:

```
ncentroids = 1024
niter = 20
verbose = true
d = x.shape[1]
kmeans = faiss.Kmeans(d, ncentroids, niter, verbose)
kmeans.train (x)
```
after `kmeans.train(x)`, I want to save the result into a local file, then next time I only need to load the file, and search cluster as follows (instead of re-run the clustering on the original data)

```
D, I = kmeans.index.search(x, 1)
```

**Comment by mdouze** [comment]
Hi, 

You can save `index` to a file with `write_index` and load it with `read_index`, see 

https://github.com/facebookresearch/faiss/wiki/High-level-interface-and-auto-tuning#io-and-deep-copying-indexes

**Comment by seriousran** [comment]
Above link has changed. Check this out.

https://github.com/facebookresearch/faiss/wiki/Index-IO,-cloning-and-hyper-parameter-tuning
