### ISSUE TITLE
Seg Fault while using in python in version 1.7.1

### ISSUE THREAD

**Issue by Jyoti1009** [facebookresearch/faiss#2001]
# Summary

While running index.search in python code, seg fault occurs. This seems to be an [old issue](https://github.com/facebookresearch/faiss/issues/540) that was solved in 1.4.0 but is occurring again in 1.7.1. 

The version 1.7.0 works fine.

# Platform

OS: MacOS 10.15.1

Faiss version: 1.7.1

Installed from: pip 

Running on: CPU

Interface:  Python

# Reproduction instructions
```
index = faiss.IndexFlatL2(d)
index.add(embeds)
k = 50
index.search(query_embedding, k))
```

**Comment by mdouze** [comment]
no activily, closing
