### ISSUE TITLE
What does the last part of labels in benchmark mean?

### ISSUE THREAD

**Issue by ArtanisCV** [facebookresearch/faiss#2003]
For example, the benchmark result of bigann10M 64 bytes / code is as followed:
![image](https://user-images.githubusercontent.com/3304030/127590339-3030540e-c422-4985-9e36-ad7f1e06ea0c.png)

Labels in the figure consists of two parts: the index type and a number (e.g., 16m12 for OPQ64_128,IVF65536,PQ64). What does the number mean?

**Comment by mdouze** [comment]
This is the index building time, ie. 16m12 is 16 minutes and 12 sec.

**Comment by ArtanisCV** [comment]
Thanks for your explanation!
