### ISSUE TITLE
Change number of clusters of IVFIndex and re-train

### ISSUE THREAD

**Issue by javierjuan** [facebookresearch/faiss#2004]
Hi,
I have an IVFIndex that is continuosly growing over time and at some point I want to re-train the index changing the number of clusters originally set. I don't know if changing the attribute `nlist` and training the index is enough to achieve what I want. To illustrate the problem, this is a short code snippet:
```
dimensions = 384
num_clusters = 500
quantizer = faiss.IndexFlatIP(dimensions)
index = faiss.IndexIVFFlat(quantizer, dimensions, num_clusters, faiss.METRIC_INNER_PRODUCT)
index.set_direct_map_type(faiss.DirectMap.Hashtable)
...
Do a lot of stuff adding elements over time
and at some point I want to change from the original 500 clusters to 1500
...
index.nlist = 1500
embeddings = np.random.randn([500000, 384], dtype=np.float32)
index.train(embeddings)
```
The idea is to preserve the elements that were added over time, but re-train the index (perhaps only the quantizer) with a different number of clusters. Is it correct?

Thank you very much.
Javier

**Comment by mdouze** [comment]
No you can't change the number of clusters dynamically. A new index needs to be built. Fortunately, for IndexIVFFlat, the vectors are stored uncompressed so it is possible to get the stored vectors from it with eg. `reconstruct_n`.
