### ISSUE TITLE
Support of float16 search on CPU (IVFPQ)

### ISSUE THREAD

**Issue by jingtaozhan** [facebookresearch/faiss#2005]
I'm using IVFPQ. I wonder whether I can use float16 to search on CPU.

**Comment by mdouze** [comment]
The only index that supports float16 compression is Index(IVF)ScalarQuantizer, see Sqfp16 in https://github.com/facebookresearch/faiss/wiki/The-index-factory#encodings

**Comment by munael** [comment]
@mdouze - This doesn't seem to support passing in float16 tensors as is. They have to be float32 and are converted internally, which seems quite wasteful if we already have them in float16 (same goes for `.train` and `.add`, just like `.search`).
