### ISSUE TITLE
There are a few vectors in the invlists that are closer to the center of other lists.

### ISSUE THREAD

**Issue by alwayslove2013** [facebookresearch/faiss#2006]
# Summary

index: IVF_Flat

There are a few vectors in the invlists that are closer to the center of other lists. It seems to be a little different from KMEANS.

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

![image](https://user-images.githubusercontent.com/22510720/127820806-37f289ed-d284-409d-85de-5b6629c7276e.png)

**Comment by mdouze** [comment]
Interesting. This could be due to roundoffs in float32 distance computations, see https://github.com/facebookresearch/faiss/wiki/FAQ#why-do-i-get-weird-results-with-brute-force-search-on-vectors-with-large-components

**Comment by alwayslove2013** [comment]
Thanks~
