### ISSUE TITLE
Ondisk Memory Overhead with Product Quantizer

### ISSUE THREAD

**Issue by codykingham** [facebookresearch/faiss#2007]
# Summary

When loading and searching ondisk with an IVF index that has been saved using merge_ondisk, the memory overload is significantly higher than a non-quantized version. Maybe this is obvious, but it should at least be noted in the guidelines for choosing an index based on memory contraints. A non-quantized, ondisk IVFK has nearly ~10x less memory overhead it seems—this despite the fact that quantizers are chosen specifically for their memory efficiency.

# Platform

OS: Mac OS 11.5.1
Faiss version: 1.7.1
Installed from: conda
Running on:
- CPU
Interface: 
- Python

# Reproduction instructions
Load `IVFK,Flat` index that has been merged on disk from shards; check memory usage in mac activity monitor
Load `OPQM_D,IVFK,PQM` index that has been merged on disk from shards; check memory usage in activity monitor

E.g.:

`IVF16000,Flat` loads with 19.2 MB (D=100)
`OPQ16_64,IVF16000,PQ16` loads with 267 MB

**Comment by mdouze** [comment]
Are you sure this is due to the merge operation? The IVFPQ also stores precomputed tables that can be bulky (https://github.com/facebookresearch/faiss/wiki/Implementation-notes#precomputed-tables-in-ivfpq). The proper test is to compare IVFx,PQ16 with merge vs. when constructed in a single run.

**Comment by codykingham** [comment]
@mdouze Thanks for the reply. I don't think it is due to the merge operation. But maybe it is worth mentioning under the `guidelines` that if memory constraints are very important, it sometimes might pay off better to use a non PQ version of IVF that is searched on-disk since it has a lot less overhead. This is a bit counter-intuitive since PQ is chosen specifically for memory conservation. Hope what I'm saying makes sense.

I'll also run the test you mentioned.
