### ISSUE TITLE
Issue While building faiss. 

### ISSUE THREAD

**Issue by AdityaWasnik91** [facebookresearch/faiss#2009]
OS: Ubuntu 18.04

Installed from: compiled by Myself

Faiss compilation options: sudo cmake -B build . -DFAISS_ENABLE_GPU=OFF -DFAISS_ENABLE_PYTHON=OFF -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON 

Running on:
- [o] CPU
- [ ] GPU

Interface: 
- [0] C++
- [ ] Python

# Reproduction instructions
1)Step One:- sudo cmake -B build . -DFAISS_ENABLE_GPU=OFF -DFAISS_ENABLE_PYTHON=OFF -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON
2)Step Two:- make -C build -j4 faiss
3)Step three:- make -C build install 
>>>>> ../faiss/libfaiss.so: undefined reference to `vaddq_u16(__Uint16x8_t, __Uint16x8_t)'
            ../faiss/libfaiss.so: undefined reference to `vandq_u8(__Uint8x16_t, __Uint8x16_t)'
            ../faiss/libfaiss.so: undefined reference to `vcleq_u16(__Uint16x8_t, __Uint16x8_t)'
            ../faiss/libfaiss.so: undefined reference to `vminq_u16(__Uint16x8_t, __Uint16x8_t)'
            ../faiss/libfaiss.so: undefined reference to `vsubq_u16(__Uint16x8_t, __Uint16x8_t)'
            ../faiss/libfaiss.so: undefined reference to `vmaxq_u16(__Uint16x8_t, __Uint16x8_t)'
            ../faiss/libfaiss.so: undefined reference to `vpaddq_f32(__Float32x4_t, __Float32x4_t)'
            ../faiss/libfaiss.so: undefined reference to `vcgeq_u16(__Uint16x8_t, __Uint16x8_t)'
            ../faiss/libfaiss.so: undefined reference to `vsubq_f32(__Float32x4_t, __Float32x4_t)'
            ../faiss/libfaiss.so: undefined reference to `vdupq_n_u16(unsigned int)'
            ../faiss/libfaiss.so: undefined reference to `vqtbl1q_u8(__Uint8x16_t, __Uint8x16_t)'
            ../faiss/libfaiss.so: undefined reference to `vmulq_f32(__Float32x4_t, __Float32x4_t)'
            collect2: error: ld returned 1 exit status
            tests/CMakeFiles/faiss_test.dir/build.make:309: recipe for target 'tests/faiss_test' failed
            make[2]: *** [tests/faiss_test] Error 1
            make[2]: Leaving directory '/home/nano/faiss/build'
            CMakeFiles/Makefile2:1291: recipe for target 'tests/CMakeFiles/faiss_test.dir/all' failed
            make[1]: *** [tests/CMakeFiles/faiss_test.dir/all] Error 2
            make[1]: Leaving directory '/home/nano/faiss/build'
            Makefile:145: recipe for target 'all' failed
            make: *** [all] Error 2 
            make: Leaving directory '/home/nano/faiss/build'

**Comment by vorj** [comment]
@AdityaWasnik91 https://github.com/facebookresearch/faiss/issues/1916#issuecomment-850768877

**Comment by beauby** [comment]
Could you try `-DCMAKE_BUILD_TYPE=Release`?
