### ISSUE TITLE
Could I get the structure of HNSW?

### ISSUE THREAD

**Issue by alwayslove2013** [facebookresearch/faiss#2011]
I want to know what each layer looks like on my data, and I need to get the "links" of each layer. Does faiss support to get the exact structure of HNSW now? something like "invlist" in ivf_xxx.

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by mdouze** [comment]
I added a FAQ entry about this: 

https://github.com/facebookresearch/faiss/wiki/Python-C---code-snippets#how-can-i-get-the-link-structure-of-a-hnsw-index
