### ISSUE TITLE
The search time when parallel mode is set to 1 is the same as that set to 2

### ISSUE THREAD

**Issue by Aurevoir-68** [facebookresearch/faiss#2012]
# Summary

# Platform

OS: Centos 

Faiss version: faiss1.7.0

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

I tested faiss1.7.0/tutorial/cpp 2-ivfflat.cpp, I modified d
=512, nb = 1000000, **and then set  the values of parallel_mode are 1 and  the value of parallel_mode is 2. It is found that the search time of the two is the same. I**f so,  Can't the meaning of parallel_mode (value of parallel_mode is  set 1 or 2 )be reflected?

We look forward to your reply.

**Comment by mdouze** [comment]
What did you expect?

**Comment by Aurevoir-68** [comment]
parallel_mode is set to different values, and their search time should be significantly different,  The search time with parallel_mode is set to 2 should be shorter than parallel_ Mode is set to the search timeof 1
while There is no difference when parallel_ mode is set to 1 and 2 according to my  results.
What is the reason？ We look forward to your reply.

**Comment by mdouze** [comment]
I don't have more clues than you about this behavior.
