### ISSUE TITLE
FAISS on ARM (Jetson Nano)

### ISSUE THREAD

**Issue by AdityaWasnik91** [facebookresearch/faiss#2013]
/usr/local/lib/libfaiss.a(distances_simd.cpp.o): In function `faiss::simd8float32::operator*(faiss::simd8float32 const&) const':
distances_simd.cpp:(.text._ZNK5faiss12simd8float32mlERKS0_[_ZNK5faiss12simd8float32mlERKS0_]+0x2c): undefined reference to `vmulq_f32(__Float32x4_t, __Float32x4_t)'
distances_simd.cpp:(.text._ZNK5faiss12simd8float32mlERKS0_[_ZNK5faiss12simd8float32mlERKS0_]+0x30): undefined reference to `vmulq_f32(__Float32x4_t, __Float32x4_t)'
//usr/local/lib/libfaiss.a(distances_simd.cpp.o): In function `faiss::simd8float32::operator-(faiss::simd8float32 const&) const':
distances_simd.cpp:(.text._ZNK5faiss12simd8float32miERKS0_[_ZNK5faiss12simd8float32miERKS0_]+0x2c): undefined reference to `vsubq_f32(__Float32x4_t, __Float32x4_t)'
distances_simd.cpp:(.text._ZNK5faiss12simd8float32miERKS0_[_ZNK5faiss12simd8float32miERKS0_]+0x30): undefined reference to `vsubq_f32(__Float32x4_t, __Float32x4_t)'
//usr/local/lib/libfaiss.a(distances_simd.cpp.o): In function `faiss::hadd(faiss::simd8float32 const&, faiss::simd8float32 const&)':
distances_simd.cpp:(.text._ZN5faiss4haddERKNS_12simd8float32ES2_[_ZN5faiss4haddERKNS_12simd8float32ES2_]+0x2c): undefined reference to `vpaddq_f32(__Float32x4_t, __Float32x4_t)'
distances_simd.cpp:(.text._ZN5faiss4haddERKNS_12simd8float32ES2_[_ZN5faiss4haddERKNS_12simd8float32ES2_]+0x30): undefined reference to `vpaddq_f32(__Float32x4_t, __Float32x4_t)'
//usr/local/lib/libfaiss.a(partitioning.cpp.o): In function `faiss::simd16uint16::accu_min(faiss::simd16uint16 const&)':
partitioning.cpp:(.text._ZN5faiss12simd16uint168accu_minERKS0_[_ZN5faiss12simd16uint168accu_minERKS0_]+0x30): undefined reference to `vminq_u16(__Uint16x8_t, __Uint16x8_t)'
partitioning.cpp:(.text._ZN5faiss12simd16uint168accu_minERKS0_[_ZN5faiss12simd16uint168accu_minERKS0_]+0x34): undefined reference to `vminq_u16(__Uint16x8_t, __Uint16x8_t)'
//usr/local/lib/libfaiss.a(partitioning.cpp.o): In function `faiss::simd16uint16::accu_max(faiss::simd16uint16 const&)':
partitioning.cpp:(.text._ZN5faiss12simd16uint168accu_maxERKS0_[_ZN5faiss12simd16uint168accu_maxERKS0_]+0x30): undefined reference to `vmaxq_u16(__Uint16x8_t, __Uint16x8_t)'
partitioning.cpp:(.text._ZN5faiss12simd16uint168accu_maxERKS0_[_ZN5faiss12simd16uint168accu_maxERKS0_]+0x34): undefined reference to `vmaxq_u16(__Uint16x8_t, __Uint16x8_t)'

Can you help me solve this ? or give me any leads???

**Comment by mdouze** [comment]
Support for neon instructions seems to be missing. Could you check your compiler settings?

**Comment by AdityaWasnik91** [comment]
I was able to solve it

**Comment by derneuere** [comment]
Could you explain what solved the issue?
