### ISSUE TITLE
GPU version IndexFlatIP will be is_trained==False after reset()

### ISSUE THREAD

**Issue by tansor** [facebookresearch/faiss#2014]
# Summary

GPU version IndexFlatIP will be is_trained==False after reset()

# Platform

OS: centOS/macOS

Faiss version: 1.5.3

Installed from: pip

Running on:
- [ ] CPU
- [X] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

```
index = faiss.IndexFlatIP(1024)
print(index.is_trained)
>>> True
index.reset()
print(index.is_trained)
>>> True
index = faiss.index_cpu_to_all_gpus(index)
print(index.is_trained)
>>> True
index.reset()
print(index.is_trained)
>>> False
```

**Comment by mdouze** [comment]
I can't repro this on Faiss 1.7.0
