### ISSUE TITLE
Question: Preserve original index of the vectors during search?

### ISSUE THREAD

**Issue by maggiex** [facebookresearch/faiss#2016]
I am using Spark (distributed) to save text info (an index) and embeddings. Is there a way I could add these indices as an id before Faiss indexing? I would like to keep the key value relationship between the embeddings and their original index. Then when Faiss provides the index of neighboring embedding vectors ("values"), I could find out their original indices ("key").

**Comment by uestc-lfs** [comment]
@MaggieX You can assign an id to each key, then use `add_with_ids` to add the values.
https://github.com/facebookresearch/faiss/blob/b4eb51dae81084b29ca77834fd9b0537045853e5/faiss/Index.h#L101
