### ISSUE TITLE
'is_trained' Failed

### ISSUE THREAD

**Issue by DaanS8** [facebookresearch/faiss#2019]
# Summary

# Platform

OS: Windows 10

Faiss version: 1.7.0

Installed from: miniconda (conda install -c conda-forge faiss-gpu cudatoolkit=11.1)

Running on:
- [x] CPU
- [x] GPU (NVIDIA GeForce GTX 1060 with Max-Q Design)

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

Code:
```
    index = faiss.index_factory(128, "OPQ32_64,IVF262144(IVF512,PQ32x4fs,RFlat),PQ32x4fsr")
    res = faiss.StandardGpuResources()  # use a single GPU

    index_ivf = faiss.extract_index_ivf(index)
    clustering_index = faiss.index_cpu_to_gpu(res, 0, faiss.IndexFlatL2(64))
    index_ivf.clustering_index = clustering_index
    
    des = load_my_sift_des()  # shape ≈ (20_000_000, 128), dtype=np.float32
    
    index.train(des)   # failes here
    faiss.write_index(index, "index.f")
```
This crashed after about 8h of runtime with error log:

```
Traceback (most recent call last):
	 File "C:\...\main.py", line 61, in <module>
		 main()
	 File "C:\...\main.py", line 44, in main
		 index.train(des)
	 File "C:\...\miniconda3\envs\LOPQ\lib\site-packages\faiss\__init__.py", line 129, in replacement_train
		 self.train_c(n, swig_ptr(x))
	 File "C:\...\miniconda3\envs\LOPQ\lib\site-packages\faiss\swigfaiss_avx2.py", line 1872, in train
		 return _swigfaiss_avx2.IndexPreTransform_train(self, n, x)
RuntimeError: Error in void __cdec1 fais::IndexRefine::add(__int64,const float *) at D:\bld\fais-split_1618468643904\f
ork\faiss\IndexRefine.cpp:55: Error: 'is_trained' Failed
```

## Note:
~~My guess is, that's because I can't train my product quantizer `(IVF512,PQ32x4fs,RFlat)` on my GPU, or I'm doing my `index_cpu_to_gpu` wrong. Is this correct? (used from https://gist.github.com/mdouze/46d6bbbaabca0b9778fca37ed2bcccf6):~~
```
    # zoomed in code sample from above
    index_ivf = faiss.extract_index_ivf(index)
    clustering_index = faiss.index_cpu_to_gpu(res, 0, faiss.IndexFlatL2(64))
    index_ivf.clustering_index = clustering_index
```
## Edit
I tried running the whole data just on CPU with the following code:

     index = faiss.index_factory(128, "OPQ32_64,IVF262144(IVF512,PQ32x4fs,RFlat),PQ32x4fsr")
     des = load_my_sift_des()  # shape ≈ (20_000_000, 128), dtype=np.float32
    
     index.train(des)   # failes here
     faiss.write_index(index, "index.f")

Which exited with the same exit code after running for almost 3 days. So it isn't a GPU problem. Do you know how I can fix this?

PS: could you give a typical runtime for training 20M and adding 200M vectors to an index (single GPU)? (accuracy not important, just somewhere in the ballpark)

**Comment by mdouze** [comment]
OK I can repro (in 10s) with 

```
index = faiss.index_factory(128, "PCAR64,IVF2000(IVF512,PQ32x4fs,RFlat),PQ32x4fsr")
des = faiss.rand((10000, 128))
index.train(des) 
```
Will investigate...

**Comment by mdouze** [comment]
This bug is fixed, closing.
