### ISSUE TITLE
memory issue with gpu

### ISSUE THREAD

**Issue by ml3958** [facebookresearch/faiss#2020]
# Summary

# Platform

OS: Ubuntu 20.04.2 LTS

GPU: NVIDIA GeForce RTX3090.

Faiss version: 1.7.0  

Installed from: condo  

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

I have been using faiss to perform `kmeans`. It ran without problems on cpu.

However, when I use gpu with `gpu=True`, it works for a few times, then start to fail with the following memory error:

`RuntimeError: Error in virtual void* faiss::gpu::StandardGpuResourcesImpl::allocMemory(const faiss::gpu::AllocRequest&) at /home/conda/feedstock_root/build_artifacts/faiss-split_1618468126454/work/faiss/gpu/StandardGpuResources.cpp:443: Error: 'err == cudaSuccess' failed: Failed to cudaMalloc 536870912 bytes on device 1 (error 2 out of memory
Outstanding allocations:`

Thanks so much!

**Comment by mdouze** [comment]
So that is with a 24G GPU? It should not fail and especially not after the first iteration.
