### ISSUE TITLE
INTEL MKL ERROR with faiss installed from pytorch channel, in Google Colab

### ISSUE THREAD

**Issue by wjx** [facebookresearch/faiss#2021]
In Google Colab env, faiss installed from *pytorch channel* crashes when doing kmeans train. Following mkl errors are reported from Google Colab log:
`Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so.1 or libmkl_def.so.1.`
`NTEL MKL ERROR: /usr/local/lib/python3.7/site-packages/faiss/../../.././libmkl_avx2.so.1: undefined symbol: mkl_sparse_optimize_bsr_trsm_i8.`

For those who encounter the same issue, faiss installed from *conda-forge channel* **don't** have this issue:  
`conda install -c conda-forge faiss-gpu`

For those who have the specific knowledge to fix this, the reproducing steps are as follows:
1. Open a Colab
2. Install conda
```
%%bash
MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.12-Linux-x86_64.sh
MINICONDA_PREFIX=/usr/local
wget https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT
chmod +x $MINICONDA_INSTALLER_SCRIPT
./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX

conda install --channel defaults conda python=3.7 --yes
conda update --channel defaults --all --yes

sudo apt-get install libomp-dev
```
`!conda --version # conda 4.10.3`
`!python --version # Python 3.7.11`

3. Install faiss from pytorch channel
```
!conda install --yes -c pytorch faiss-gpu
```
4. Run kmeans with faiss
```
import faiss
import numpy as np

values=np.random.random_sample((100, 3)).astype("float32")

kmeans = faiss.Kmeans(values.shape[-1], 8, niter=100, verbose=True)
kmeans.train(values)
```
5. Colab kernel crashes with the log metioned above

**Comment by gaoyibin0001** [comment]
same here. reinstall from conda-forge channel resolve this
