### ISSUE TITLE
Code Crashes with no error message during Kmeans.train()

### ISSUE THREAD

**Issue by mlittmanabbvie** [facebookresearch/faiss#2023]
# Summary

Code always crashes during kmeans.train() right after the "preprocessing in __ s" part. 
![image](https://user-images.githubusercontent.com/79881628/131197410-ba6be1a6-0c58-4810-a2ca-554f6dd77eb1.png)

Every time that I run my code (optimizing inputs to faiss Kmeans), it will work for the first few iterations and then crash at the same part. It is not a memory overload, cpu overload or anything. The program just abruptly ends with no error message. I traced down the issue to the above mentioned spot, but can not figure out why it keeps crashing here. 

OS: Windows 10

Faiss version: 1.7

Installed from: conda pytorch 

Running on:
- [ X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X ] Python

# Reproduction instructions

I am running a multiprocessing portion and then feeding the result of this into this code. If I skip the multiprocessing portion, I have no issues, but if I include, it always breaks at the same spot in the faiss Kmeans.train function

 **df1 is a 16,388 X 500 Pandas dataframe originally.

      df1 = np.ascontiguousarray(np.float32(df1.to_numpy()))
      D = df1.shape[1]
      kmeans = faiss.Kmeans(d=D, k=n,niter = 5,verbose = True, min_points_per_centroid = 200)
      N_small = len(df1)
      kmeans.train(df1[:N_small])   ------------- Always breaks on this step.
      _, ids = kmeans.index.search(df1, 1)
      ids = ids.reshape(1,N_small)[0]

**Comment by mlittmanabbvie** [comment]
Would you be able to help with this? I can't figure out why it continues to fail in this way

**Comment by mlittmanabbvie** [comment]
@mdouze I think this may have been given the wrong label. I don't believe this is an installation issue

**Comment by mdouze** [comment]
May be a win10 specific issue see also #1992
