### ISSUE TITLE
Asssertion failed in InvertedLists::get_single_id: "offset < list_size (list_no)"

### ISSUE THREAD

**Issue by yutkin** [facebookresearch/faiss#2028]
# Summary
We have sudden crashes of an index under "RemoveIDs" queries:

```
InvertedLists.cpp:36: virtual faiss::InvertedLists::idx_t faiss::InvertedLists::get_single_id(size_t, size_t) const: Assertion `offset < list_size (list_no)' failed.
SIGABRT: abort
```

Whereas "Add" and "Search" queries perform well.

# Platform

Faiss version: v1.6.3

Installed from: compiled from src

Faiss compilation options: `./configure --prefix=/opt/faiss --without-cuda`

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [x] Python

Index type:
- faiss::IndexIVFPQ
- ndim 512

# Reproduction instructions
There is a snapshot of the index right before the failed assertion. All queries (even "Search") are performed under a scoped lock, so I assume that the index is in a consistent state. URL to the saved index at the bottom of this issue.

```Python
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import faiss
>>> import numpy as np
>>> bad_index = faiss.read_index("bad_index.bin")
>>> bad_index.ntotal
9949483
>>> bad_index.remove_ids(np.array([1,]))
0
>>> bad_index.remove_ids(np.array([386509832285,]))
0
>>> bad_index.remove_ids(np.array([386509832285, 386509832284]))
1
>>> bad_index.remove_ids(np.array([386509832286]))
Segmentation fault (core dumped)
```

 
[Index @ Google Drive 909Mb](https://drive.google.com/file/d/1BnFLnHaVTLM0Sq73_PAPZSREJH2RozRT/view?usp=sharing)

**Comment by mdouze** [comment]
Would it be possible to repro with a smaller index?
