### ISSUE TITLE
GpuIndexIVFFlat train method

### ISSUE THREAD

**Issue by windweller** [facebookresearch/faiss#203]
Hi,

I'm using the Python API of faiss with PyTorch on GPU. I'm curious about the `train` function in  `faiss.GpuIndexIVFFlat`. The example I found wrote:

```python
index = faiss.GpuIndexIVFFlat(...)
norm_vec = torch.randn(10000, 500) # some PyTorch stuff
norm_vec_numpy = _to_numpy(norm_vec)
index.train(norm_vec_numpy)
index.add(norm_vec_numpy)
```

```python
def _to_numpy(x):
    return _to_tensor(x).cpu().numpy()
```

It seems like the code retrieved PyTorch tensor from GPU to CPU and then passed to faiss. Is there a way to directly pass a PyTorch CUDA pointer to faiss' train and add method?

If I pass a PyTorch CUDA object to FAISS, does it incur copying?

Is `res.syncDefaultStreamCurrentDevice()` doing copying between FAISS and PyTorch?

**Comment by mdouze** [comment]
Hi 
Please see 
https://github.com/facebookresearch/faiss/blob/master/gpu/test/test_pytorch_faiss.py
for Faiss / pytorch interop. It is not implemented for `train` and `add`, but it should be relatively easy to extend to these cases.

**Comment by windweller** [comment]
Yes. I'm able to extend to `train` and `add`, but it seems like in both cases, I cannot simply pass in a Torch tensor because the underlying code checks for `variable.flags.contiguous`, which only exists for Numpy array but not for Torch tensor.

This means I have to move Torch tensor into CPU, turn into numpy array, and pass it to FAISS' `train` and `add` method, and FAISS moves them to GPU again.

**Comment by mdouze** [comment]
Yes you have to call `add_c` and `train_c` with the  `faiss.cast_integer_to_float_ptr(x.storage().data_ptr())`  trick.

**Comment by windweller** [comment]
Hi Matthijs,

    Thank you for the pointer! I did see that this is how the API works with `search_c` and this function definitely works. However, when I'm trying to do exactly this for `add_c` and `train_c`, I get a segmentation fault. 

    To ensure nothing is interfering, I used python REPL. Here's my execution code:
```python
>>> import faiss; import torch
>>> d = 128; nq=5; nb=1000
>>> xb = faiss.rand(nb * d).reshape(nq, d) * 10
>>> xb_t = torch.FloatTensor(xb).cuda()
>>> xb_t.storage().data_ptr()
77398409216
>>> casted = faiss.cast_integer_to_float_ptr(xb_t.storage().data_ptr())
>>> casted
<Swig Object of type 'faiss::HeapArray< faiss::CMax< float,long > >::T *' at 0x7f484b091d80>
>>> res = faiss.StandardGpuResources()
>>> index = faiss.GpuIndexIVFFlat(res, d, 5, faiss.METRIC_INNER_PRODUCT)
>>> index.setNumProbes(12)
>>> index.train_c(nb, casted)
Segmentation fault (core dumped)
```

If `xb` is not on `cuda()`, segmentation fault would not happen.

**Comment by windweller** [comment]
I'm closing this thread and moved the problem to a new issue :)
