### ISSUE TITLE
module 'faiss' has no attribute 'cast_integer_to_long_ptr'

### ISSUE THREAD

**Issue by berylyellow** [facebookresearch/faiss#2031]
When I install faiss by running :  conda install -c conda-forge faiss-gpu, it succeed.
But when I run my code, it occured :
module 'faiss' has no attribute 'cast_integer_to_long_ptr' .

I have tried many ways installing faiss via conda or pip but failed, could you please help?

**Comment by mdouze** [comment]
Pelase use the issue template to give install info.

**Comment by berylyellow** [comment]
It‘s because of  the version. Solved it, thanks.

**Comment by suzhansz** [comment]
I also met the same problem, how did you solve it

**Comment by SuperbTUM** [comment]
Seems that the latest version (1.7.4) removed this operator already... at least I did not find it on the master branch. Is there any alternative?

**Comment by SuperbTUM** [comment]
@mdouze ^

**Comment by BonGum** [comment]
@SuperbTUM have you slove this problem？ did you use faiss in windows platform？
