### ISSUE TITLE
Error: Error in faiss::Index* faiss::read_index(faiss::IOReader*, int) at index_io.cpp:1014: Index type 0x78038001 not supported

### ISSUE THREAD

**Issue by Mike201456** [facebookresearch/faiss#2033]
# Summary
Got the following error when reading a pre-built FAISS index: 
Error: Error in faiss::Index* faiss::read_index(faiss::IOReader*, int) at index_io.cpp:1014: Index type 0x78038001 not supported
@Matthijs Douze, could you please take a look? Thanks!

# Platform
Unix

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [x ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x ] Python

# Reproduction instructions

This FAISS index was built by multi-GPU, and could be loaded successfully with the same FAISS environment. However, once deployed to Production environment, got the above error during loading process. 

 

Error: Error in faiss::Index* faiss::read_index(faiss::IOReader*, int) at index_io.cpp:1014: Index type 0x78038001 not supported

**Comment by mdouze** [comment]
Could you confirm that the same version of Faiss was used for reading and writing?
