### ISSUE TITLE
when i add faiss-master\gpu\test\TestGpuSelect.cu to cmakelist  error happens

### ISSUE THREAD

**Issue by zjuchenwei** [facebookresearch/faiss#204]
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o：‘_start’：
(.text+0x20)：对‘main’ undefined

**Comment by mdouze** [comment]
@hlzz, would you mind taking a look?

**Comment by hlzz** [comment]
@zjuchenwei Can you provide a more detailed description of your problem? Thanks.

**Comment by zjuchenwei** [comment]
here is my cmakelist.txt
![image](https://user-images.githubusercontent.com/4024185/30013265-2d08dde0-9178-11e7-9a85-4417eadf0a6f.png)
here is the error.
![image](https://user-images.githubusercontent.com/4024185/30013296-5a3c5382-9178-11e7-9f7d-cfc1b367140b.png)

**Comment by zjuchenwei** [comment]
the problem is solved, when i change nvcc to 8.0,the problem is gone, but the new problem is appear.
![image](https://user-images.githubusercontent.com/4024185/30013500-90b0cd7a-9179-11e7-9373-66c1380c5a3c.png)
that seems to be a Gtest problem

**Comment by hlzz** [comment]
@zjuchenwei guess this is related to your gtest installation. Depending on your configuration, there are two possibilities: 1. you have multiple gtest installed; 2. you didn't link gtest explicitly in the cmake file.

**Comment by zjuchenwei** [comment]
i do install multiple gtest version .how to link gtest explicitly in the cmake file.

**Comment by hlzz** [comment]
@zjuchenwei This might be one of the errors: In your cmake file line 13, you should link the lib symbol (i think it's GTEST_BOTH_LIBRARIES), not the include directory (GTEST_INCLUDE_DIRS). And it's safe to have only one gtest version, otherwise the dependencies are very tricky sometimes.

**Comment by zjuchenwei** [comment]
oh,that might be the reason of the problem, thank you very much.
the prolem is solved .
![image](https://user-images.githubusercontent.com/4024185/30015863-2a3f6310-9185-11e7-8893-cff222f8602c.png)

**Comment by mdouze** [comment]
Thanks a lot @hlzz !
Closing the issue.
