### ISSUE TITLE
How to run Faiss1.7.1 based on Python2？

### ISSUE THREAD

**Issue by Sweetheartman** [facebookresearch/faiss#2040]
### Discussed in https://github.com/facebookresearch/faiss/discussions/2039

<div type='discussions-op-text'>

<sup>Originally posted by **Sweetheartman** September  6, 2021</sup>
The Faiss version used by the project is 1.6.1 and is based on Python2. After the project is iterated, Faiss 1.7.1 is needed, but when I install it with conda, I can only use it under Python3. Is there any other way to use it? Used under Python2.</div>

**Comment by mdouze** [comment]
We do not provide python 2 packages anymore. Normally, the core Faiss (excluding contrib) should work with python 2 but you'll have to compile it yourself.

**Comment by Sweetheartman** [comment]
> We do not provide python 2 packages anymore. Normally, the core Faiss (excluding contrib) should work with python 2 but you'll have to compile it yourself.

Alright, thank you very much!
