### ISSUE TITLE
make py errors

### ISSUE THREAD

**Issue by Sweetheartman** [facebookresearch/faiss#2042]
# Summary

# Platform

OS: Ubuntu18.04

Faiss version: 1.6.3

Installed from: source code

Faiss compilation options: ./configure --without-cuda    make      make install

Running on:
- [* ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ *] Python

# Reproduction instructions

swigfaiss.cpp: In function ‘PyObject* _wrap_RangeQueryResult_qno_get(PyObject*, PyObject*)’:
swigfaiss.cpp:107035:3: error: ‘idx_t’ was not declared in this scope
   idx_t result;
   ^~~~~
swigfaiss.cpp:107035:3: note: suggested alternative:
In file included from swigfaiss.cpp:3438:0:
../faiss/IVFlib.h:49:22: note:   ‘faiss::ivflib::idx_t’
 typedef Index::idx_t idx_t;
                      ^~~~~
swigfaiss.cpp:107043:3: error: ‘result’ was not declared in this scope
   result =  ((arg1)->qno);
   ^~~~~~
swigfaiss.cpp:107044:39: error: expected type-specifier before ‘idx_t’
   resultobj = SWIG_NewPointerObj((new idx_t(static_cast< const idx_t& >(result))), SWIGTYPE_p_idx_t, SWIG_POINTER_OWN |  0 );
                                       ^
swigfaiss.cpp:1186:89: note: in definition of macro ‘SWIG_NewPointerObj’
 #define SWIG_NewPointerObj(ptr, type, flags)            SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
                                                                                         ^~~
swigfaiss.cpp:107044:39: error: expected ‘)’ before ‘idx_t’
   resultobj = SWIG_NewPointerObj((new idx_t(static_cast< const idx_t& >(result))), SWIGTYPE_p_idx_t, SWIG_POINTER_OWN |  0 );
                                       ^
swigfaiss.cpp:1186:89: note: in definition of macro ‘SWIG_NewPointerObj’
 #define SWIG_NewPointerObj(ptr, type, flags)            SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
                                                                                         ^~~
swigfaiss.cpp: In function ‘PyObject* _wrap_RangeQueryResult_add(PyObject*, PyObject*)’:
swigfaiss.cpp:107159:3: error: ‘idx_t’ was not declared in this scope
   idx_t arg3 ;
   ^~~~~
swigfaiss.cpp:107159:3: note: suggested alternative:
In file included from swigfaiss.cpp:3438:0:
../faiss/IVFlib.h:49:22: note:   ‘faiss::ivflib::idx_t’
 typedef Index::idx_t idx_t;
                      ^~~~~
swigfaiss.cpp:107189:15: error: ‘temp’ was not declared in this scope
       idx_t * temp = reinterpret_cast< idx_t * >(argp3);
               ^~~~
swigfaiss.cpp:107189:40: error: ‘idx_t’ does not name a type
       idx_t * temp = reinterpret_cast< idx_t * >(argp3);
                                        ^~~~~
swigfaiss.cpp:107189:46: error: expected ‘>’ before ‘*’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp3);
                                              ^
swigfaiss.cpp:107189:46: error: expected ‘(’ before ‘*’ token
swigfaiss.cpp:107189:48: error: expected primary-expression before ‘>’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp3);
                                                ^
swigfaiss.cpp:107189:56: error: expected ‘)’ before ‘;’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp3);
                                                        ^
swigfaiss.cpp:107190:7: error: ‘arg3’ was not declared in this scope
       arg3 = *temp;
       ^~~~
swigfaiss.cpp:107191:39: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
       if (SWIG_IsNewObj(res3)) delete temp;
                                       ^~~~
swigfaiss.cpp:107194:20: error: ‘arg3’ was not declared in this scope
   (arg1)->add(arg2,arg3);
                    ^~~~
swigfaiss.cpp: In function ‘PyObject* _wrap_DistanceComputer___call__(PyObject*, PyObject*)’:
swigfaiss.cpp:107711:3: error: ‘idx_t’ was not declared in this scope
   idx_t arg2 ;
   ^~~~~
swigfaiss.cpp:107711:3: note: suggested alternative:
In file included from swigfaiss.cpp:3438:0:
../faiss/IVFlib.h:49:22: note:   ‘faiss::ivflib::idx_t’
 typedef Index::idx_t idx_t;
                      ^~~~~
swigfaiss.cpp:107734:15: error: ‘temp’ was not declared in this scope
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
               ^~~~
swigfaiss.cpp:107734:40: error: ‘idx_t’ does not name a type
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
                                        ^~~~~
swigfaiss.cpp:107734:46: error: expected ‘>’ before ‘*’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
                                              ^
swigfaiss.cpp:107734:46: error: expected ‘(’ before ‘*’ token
swigfaiss.cpp:107734:48: error: expected primary-expression before ‘>’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
                                                ^
swigfaiss.cpp:107734:56: error: expected ‘)’ before ‘;’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
                                                        ^
swigfaiss.cpp:107735:7: error: ‘arg2’ was not declared in this scope
       arg2 = *temp;
       ^~~~
swigfaiss.cpp:107736:39: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
       if (SWIG_IsNewObj(res2)) delete temp;
                                       ^~~~
swigfaiss.cpp:107739:39: error: ‘arg2’ was not declared in this scope
   result = (float)(arg1)->operator ()(arg2);
                                       ^~~~
swigfaiss.cpp: In function ‘PyObject* _wrap_DistanceComputer_symmetric_dis(PyObject*, PyObject*)’:
swigfaiss.cpp:107750:3: error: ‘idx_t’ was not declared in this scope
   idx_t arg2 ;
   ^~~~~
swigfaiss.cpp:107750:3: note: suggested alternative:
In file included from swigfaiss.cpp:3438:0:
../faiss/IVFlib.h:49:22: note:   ‘faiss::ivflib::idx_t’
 typedef Index::idx_t idx_t;
                      ^~~~~
swigfaiss.cpp:107751:9: error: expected ‘;’ before ‘arg3’
   idx_t arg3 ;
         ^~~~
swigfaiss.cpp:107777:15: error: ‘temp’ was not declared in this scope
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
               ^~~~
swigfaiss.cpp:107777:40: error: ‘idx_t’ does not name a type
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
                                        ^~~~~
swigfaiss.cpp:107777:46: error: expected ‘>’ before ‘*’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
                                              ^
swigfaiss.cpp:107777:46: error: expected ‘(’ before ‘*’ token
swigfaiss.cpp:107777:48: error: expected primary-expression before ‘>’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
                                                ^
swigfaiss.cpp:107777:56: error: expected ‘)’ before ‘;’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp2);
                                                        ^
swigfaiss.cpp:107778:7: error: ‘arg2’ was not declared in this scope
       arg2 = *temp;
       ^~~~
swigfaiss.cpp:107779:39: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
       if (SWIG_IsNewObj(res2)) delete temp;
                                       ^~~~
swigfaiss.cpp:107790:15: error: ‘temp’ was not declared in this scope
       idx_t * temp = reinterpret_cast< idx_t * >(argp3);
               ^~~~
swigfaiss.cpp:107790:40: error: ‘idx_t’ does not name a type
       idx_t * temp = reinterpret_cast< idx_t * >(argp3);
                                        ^~~~~
swigfaiss.cpp:107790:46: error: expected ‘>’ before ‘*’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp3);
                                              ^
swigfaiss.cpp:107790:46: error: expected ‘(’ before ‘*’ token
swigfaiss.cpp:107790:48: error: expected primary-expression before ‘>’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp3);
                                                ^
swigfaiss.cpp:107790:56: error: expected ‘)’ before ‘;’ token
       idx_t * temp = reinterpret_cast< idx_t * >(argp3);
                                                        ^
swigfaiss.cpp:107791:7: error: ‘arg3’ was not declared in this scope
       arg3 = *temp;
       ^~~~
swigfaiss.cpp:107792:39: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
       if (SWIG_IsNewObj(res3)) delete temp;
                                       ^~~~
swigfaiss.cpp:107795:41: error: ‘arg2’ was not declared in this scope
   result = (float)(arg1)->symmetric_dis(arg2,arg3);
                                         ^~~~
swigfaiss.cpp:107795:46: error: ‘arg3’ was not declared in this scope
   result = (float)(arg1)->symmetric_dis(arg2,arg3);
                                              ^~~~
In file included from ../faiss/impl/ThreadedIndex.h:80:0,
                 from swigfaiss.cpp:3420:
../faiss/impl/ThreadedIndex-inl.h: In instantiation of ‘void faiss::ThreadedIndex<IndexT>::onAfterAddIndex(IndexT*) [with IndexT = faiss::Index]’:
../faiss/impl/ThreadedIndex-inl.h:84:18:   required from ‘void faiss::ThreadedIndex<IndexT>::addIndex(IndexT*) [with IndexT = faiss::Index]’
swigfaiss.cpp:87032:28:   required from here
../faiss/impl/ThreadedIndex-inl.h:164:48: warning: unused parameter ‘index’ [-Wunused-parameter]
 ThreadedIndex<IndexT>::onAfterAddIndex(IndexT* index) {
                                                ^~~~~
../faiss/impl/ThreadedIndex-inl.h: In instantiation of ‘void faiss::ThreadedIndex<IndexT>::onAfterRemoveIndex(IndexT*) [with IndexT = faiss::Index]’:
../faiss/impl/ThreadedIndex-inl.h:104:25:   required from ‘void faiss::ThreadedIndex<IndexT>::removeIndex(IndexT*) [with IndexT = faiss::Index]’
swigfaiss.cpp:87081:31:   required from here
../faiss/impl/ThreadedIndex-inl.h:169:51: warning: unused parameter ‘index’ [-Wunused-parameter]
 ThreadedIndex<IndexT>::onAfterRemoveIndex(IndexT* index) {
                                                   ^~~~~
../faiss/impl/ThreadedIndex-inl.h: In instantiation of ‘void faiss::ThreadedIndex<IndexT>::onAfterAddIndex(IndexT*) [with IndexT = faiss::IndexBinary]’:
../faiss/impl/ThreadedIndex-inl.h:84:18:   required from ‘void faiss::ThreadedIndex<IndexT>::addIndex(IndexT*) [with IndexT = faiss::IndexBinary]’
swigfaiss.cpp:87624:28:   required from here
../faiss/impl/ThreadedIndex-inl.h:164:48: warning: unused parameter ‘index’ [-Wunused-parameter]
 ThreadedIndex<IndexT>::onAfterAddIndex(IndexT* index) {
                                                ^~~~~
../faiss/impl/ThreadedIndex-inl.h: In instantiation of ‘void faiss::ThreadedIndex<IndexT>::onAfterRemoveIndex(IndexT*) [with IndexT = faiss::IndexBinary]’:
../faiss/impl/ThreadedIndex-inl.h:104:25:   required from ‘void faiss::ThreadedIndex<IndexT>::removeIndex(IndexT*) [with IndexT = faiss::IndexBinary]’
swigfaiss.cpp:87673:31:   required from here
../faiss/impl/ThreadedIndex-inl.h:169:51: warning: unused parameter ‘index’ [-Wunused-parameter]
 ThreadedIndex<IndexT>::onAfterRemoveIndex(IndexT* index) {
                                                   ^~~~~
Makefile:22: recipe for target 'swigfaiss.o' failed
make[1]: *** [swigfaiss.o] Error 1
make[1]: Leaving directory '/home/appops/faiss-1.6.3/python'
Makefile:83: recipe for target 'py' failed
make: *** [py] Error 2

**Comment by Sweetheartman** [comment]
I very much hope to be able to solve this problem, this problem has bothered me for a long time

**Comment by xiaodongww** [comment]
@Sweetheartman How do you solve it? I also meet this problem.
