### ISSUE TITLE
range_search doesn't search outside single cluster

### ISSUE THREAD

**Issue by drewbo** [facebookresearch/faiss#2043]
# Summary

It seems like `range_search`, even when given a huge radius, won't search outside a single cluster. This may be intentional but should likely be noted in the docs.

# Platform

OS: macOS 10.15.4

Faiss version: `faiss-cpu==1.7.1.post2`

Installed from: pip

Faiss compilation options: N/A

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

```python
import faiss
import numpy as np

# create two indices with different number of clusters
xt = np.random.rand(10000, 128).astype(np.float32)
index1 = faiss.index_factory(xt.shape[1], 'IVF32,Flat')
index2 = faiss.index_factory(xt.shape[1], 'IVF4,Flat')
index1.train(xt)
index2.train(xt)
index1.add(xt)
index2.add(xt)

# range search with a random vector and a large radius
# each index returns roughly N / K results where N is the dataset size and K is the number of clusters 
np.random.seed(42)
q = np.random.rand(1, 128).astype(np.float32)
index1.range_search(q, 1000000000)[0][1]
>>> 335
index2.range_search(q, 1000000000)[0][1]
>>> 1982
```

**Comment by mdouze** [comment]
please increase  `nprobe` 
https://github.com/facebookresearch/faiss/wiki/Faster-search#this-is-too-slow-how-can-i-make-it-faster

**Comment by drewbo** [comment]
Thanks!
