### ISSUE TITLE
IndexIVFPQ returns infinite distances

### ISSUE THREAD

**Issue by s4chin** [facebookresearch/faiss#2045]
# Summary

I have an `IndexIVFPQ` with around 6.5M vectors. On searching, the result looks like -
```
D, I = [[9.9182504e-01 3.4028235e+38 3.4028235e+38 3.4028235e+38 3.4028235e+38]] [[207336276        -1        -1        -1        -1]]
```

All vectors(query and index) are L2 normalized. Finding nearest neighbors using `numpy`(without faiss) works fine.
Relevant faiss index code
```
quantizer = faiss.IndexFlatL2(512) 
index = faiss.IndexIVFPQ(quantizer, dim=512, ncentroids=50000, code_size, 8) # I tried 8, 32, 64 for code_size, with same error
index = faiss.IndexIDMap(index)
```

Other info that might be relevant - 
I have two sets of vectors returned by two different models(same architecture). One set works fine, the other one has the above issue while using the same code.

# Platform

OS: `Ubuntu 18.04.5`

Faiss version: `1.7.1`

Installed from: `conda`

Faiss compilation options: NA

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

 

I cannot reproduce this using random vectors, it only happens with my vectors. But I'm happy to run experiments and report results here.

**Comment by mdouze** [comment]
See
https://github.com/facebookresearch/faiss/wiki/FAQ#what-does-it-mean-when-a-search-returns--1-ids

**Comment by s4chin** [comment]
Used  `faiss.ParameterSpace().set_index_parameter(index, 'nprobe', 100)` on CPU index before moving to GPU and that worked.
