### ISSUE TITLE
How to use index in GPU after loading index using read_index_binary()?

### ISSUE THREAD

**Issue by TaeWoo21** [facebookresearch/faiss#2046]
# Summary
I want to use IndexBinaryFlat in GPU after loading the index using faiss.read_index_binary().

I've already read about this issue(#1428),  
but my situation is a little different and I need some more explanation.

here is the code:
```python
# Load the index
res = faiss.StandardGpuResources()
base_index = faiss.read_index_binary("test.idx")

# How to construct the binary index manually?
config = faiss.GpuIndexBinaryFlatConfig()
embeddings_size = 768
dim_size = embeddings_size * 8
idx_gpu = faiss.GpuIndexBinaryFlat(res, dim_size, config)
...  # I don't know what to do after that...
```

c.f. base_index : <br/>
<faiss.swigfaiss_avx2.IndexBinaryIDMap; proxy of <Swig Object of type 'faiss::IndexIDMapTemplate< faiss::IndexBinary > *' at 0x7fc1a021d630> >

# Platform

OS: Ubuntu 18.04.3

Faiss version: faiss-gpu==1.7.1

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
```python
# Load the index
res = faiss.StandardGpuResources()
base_index = faiss.read_index_binary("test.idx")
index = faiss.index_cpu_to_gpu(res, 0, base_index.index)
```
TypeError: Wrong number or type of arguments for overloaded function 'index_cpu_to_gpu'.
&nbsp;&nbsp;&nbsp;&nbsp;Possible C/C++ prototypes are:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;faiss::gpu::index_cpu_to_gpu(faiss::gpu::GpuResourcesProvider *,int,faiss::Index const *,faiss::gpu::GpuClonerOptions const *)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;faiss::gpu::index_cpu_to_gpu(faiss::gpu::GpuResourcesProvider *,int,faiss::Index const *)

**Comment by mdouze** [comment]
index_cpu_to_gpu works only for floating-point indexes. 

The GPU index can be constructed from the CPU index with 

```
idx_gpu = faiss.GpuIndexBinaryFlat(res, base_index)
```

https://faiss.ai/cpp_api/class/classfaiss_1_1gpu_1_1GpuIndexBinaryFlat.html#_CPPv4N5faiss3gpu18GpuIndexBinaryFlat18GpuIndexBinaryFlatEP20GpuResourcesProviderPKN5faiss15IndexBinaryFlatE24GpuIndexBinaryFlatConfig

**Comment by TaeWoo21** [comment]
Thank you for your reply @mdouze.

I followed your advice and tried it. 
But the following error occurred.

```python
>> res = faiss.StandardGpuResources()
>> base_index = faiss.read_index_binary("test.idx")
>> idx_gpu = faiss.GpuIndexBinaryFlat(res, base_index)
TypeError: Wrong number or type of arguments for overloaded function 'new_GpuIndexBinaryFlat'.
  Possible C/C++ prototypes are:
    faiss::gpu::GpuIndexBinaryFlat::GpuIndexBinaryFlat(faiss::gpu::GpuResourcesProvider *,faiss::IndexBinaryFlat const *,faiss::gpu::GpuIndexBinaryFlatConfig)
    faiss::gpu::GpuIndexBinaryFlat::GpuIndexBinaryFlat(faiss::gpu::GpuResourcesProvider *,faiss::IndexBinaryFlat const *)
    faiss::gpu::GpuIndexBinaryFlat::GpuIndexBinaryFlat(faiss::gpu::GpuResourcesProvider *,int,faiss::gpu::GpuIndexBinaryFlatConfig)
    faiss::gpu::GpuIndexBinaryFlat::GpuIndexBinaryFlat(faiss::gpu::GpuResourcesProvider *,int)
```

c.f. 
```python
>> base_index
<faiss.swigfaiss_avx2.IndexBinaryIDMap; proxy of <Swig Object of type 'faiss::IndexIDMapTemplate< faiss::IndexBinary > *' at 0x7fc1a021d630> >
```

**Comment by mdouze** [comment]
Right, the id_map part cannot be converted to binary. So `faiss.GpuIndexBinaryFlat(res, base_index.index)` should work.

**Comment by astar10239** [comment]
@mdouze  i am doing 
faiss.GpuIndexBinaryFlat(res, base_index.index)

Index is getting loaded as well

but while searching it crashes the GPU, index size 2gb in gpu and gpu is 16gb tesla v100
