### ISSUE TITLE
Splitting an index over multiple GPUs?

### ISSUE THREAD

**Issue by JulesGM** [facebookresearch/faiss#2048]
Hello @wickedfoo, 
I was wondering if there was a way to split a single large index that is too big for a single GPU over more than one GPUs, other than just creating separate indexes. 

DPR https://github.com/facebookresearch/DPR is too big to fit in a single GPU. I'm doing research with it. Using a flat index is important to be able to compare the numbers with those of other publications.

**Comment by mdouze** [comment]
See https://github.com/facebookresearch/faiss/wiki/Faiss-on-the-GPU#using-multiple-gpus
