### ISSUE TITLE
ModuleNotFoundError: No module named 'faiss.contrib'

### ISSUE THREAD

**Issue by CarinaXZZ** [facebookresearch/faiss#2051]
# Summary

Hi,

I'm trying to train the IVF index on disk. But I have the following error that occurred while calling merge_ondisk.
# Platform

OS:  CentOS

Faiss version: 

Installed from:   `conda install -c pytorch faiss-gpu`

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

 

```
>>> faiss.__version__
'1.6.3'
>>> faiss.contrib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'faiss' has no attribute 'contrib'
>>> from faiss.contrib.ondisk import merge_ondisk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'faiss.contrib'
```

Thanks

**Comment by mdouze** [comment]
Please upgrade your Faiss version.
