### ISSUE TITLE
Faiss failed to build due to error C3861: '_BitScanForward64': identifier not found with MSVC on windows

### ISSUE THREAD

**Issue by spacelg** [facebookresearch/faiss#2052]
Hi All,

Environment:
VS 2019 + Windows Server 2016

Faiss failed to build due to error C3861: '_BitScanForward64': identifier not found with MSVC on windows. This issue can be reproduced on latest version eba1cb1 on main branch. Could you please help look at this issue?

Running on:

[o] CPU
 GPU
Interface:

[0] C++
 Python

**Repro steps:**
1. git clone https://github.com/facebookresearch/faiss F:\gitP\facebookresearch\faiss
2. Install Intel MKL v10 on F:\gitP\MKL\oneAPI
3. Open a vs2019 x86 Command Prompt && cd F:\gitP\facebookresearch\faiss
4. mkdir build && cd F:\gitP\facebookresearch\faiss\build
5. cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DFAISS_ENABLE_GPU=OFF -DFAISS_ENABLE_PYTHON=OFF  -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON -DFAISS_OPT_LEVEL=avx2 -DBLA_VENDOR=Intel10_64_dyn -DMKL_LIBRARIES=F:\gitP\MKL\oneAPI\mkl\latest\lib\intel64 ..
6. msbuild /m /p:Platform=Win32 /p:Configuration=Release faiss.sln /t:Rebuild

**Build log:**
[build.log](https://github.com/facebookresearch/faiss/files/7176520/build.log)

**Error info:**
    17>F:\gitP\facebookresearch\faiss\faiss/impl/platform_macros.h(37,5): error C3861: '_BitScanForward64': identifier not found [F:\gitP\facebookresearch\faiss\build\faiss\faiss_avx2.vcxproj]
    17>F:\gitP\facebookresearch\faiss\faiss/impl/platform_macros.h(51,17): error C3861: '__lzcnt64': identifier not found [F:\gitP\facebookresearch\faiss\build\faiss\faiss_avx2.vcxproj]
    18>F:\gitP\facebookresearch\faiss\faiss/impl/platform_macros.h(37,5): error C3861: '_BitScanForward64': identifier not found [F:\gitP\facebookresearch\faiss\build\faiss\faiss.vcxproj]
    18>F:\gitP\facebookresearch\faiss\faiss/impl/platform_macros.h(51,17): error C3861: '__lzcnt64': identifier not found

**Comment by mdouze** [comment]
see https://stackoverflow.com/questions/10145805/cant-use-bitscanforward64

Building on 32-bit platforms might work but is not supported.

**Comment by spacelg** [comment]
@mdouze Thanks for your reply and info. We decided to abandon 32-bit and use 64-bit to build. But it failed with the following LNK2001 errors.  Could you please help look at this issue?

Re-adjust the 64-bit build steps:
1. git clone https://github.com/facebookresearch/faiss F:\gitP\facebookresearch\faiss
2. Install Intel MKL v10 on F:\gitP\MKL\oneAPI
3. Open a vs2019 x64 Command Prompt && cd F:\gitP\facebookresearch\faiss
4. mkdir build_amd64 && cd F:\gitP\facebookresearch\faiss\build_amd64
5. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DFAISS_ENABLE_GPU=OFF -DFAISS_ENABLE_PYTHON=OFF -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON -DFAISS_OPT_LEVEL=avx2 -DBLA_VENDOR=Intel10_64_dyn -DMKL_LIBRARIES=F:\gitP\MKL\oneAPI\mkl\latest\lib\intel64 ..
6. msbuild /m /p:Platform=x64 /p:Configuration=Release faiss.sln /t:Rebuild

[build_amd64.log](https://github.com/facebookresearch/faiss/files/7208886/build_amd64.log)

**Error info:**
17>ResidualQuantizer.obj : error LNK2001: unresolved external symbol sgemm_ [F:\gitP\facebookresearch\faiss\build_amd64\faiss\faiss_avx2.vcxproj]
    17>LocalSearchQuantizer.obj : error LNK2001: unresolved external symbol sgemm_ [F:\gitP\facebookresearch\faiss\build_amd64\faiss\faiss_avx2.vcxproj]
    17>distances.obj : error LNK2001: unresolved external symbol sgemm_ [F:\gitP\facebookresearch\faiss\build_amd64\faiss\faiss_avx2.vcxproj]
    17>IndexHNSW.obj : error LNK2001: unresolved external symbol sgemm_ [F:\gitP\facebookresearch\faiss\build_amd64\faiss\faiss_avx2.vcxproj]
    17>VectorTransform.obj : error LNK2001: unresolved external symbol sgemm_ [F:\gitP\facebookresearch\faiss\build_amd64\faiss\faiss_avx2.vcxproj]
    17>ProductQuantizer.obj : error LNK2001: unresolved external symbol sgemm_ [F:\gitP\facebookresearch\faiss\build_amd64\faiss\faiss_avx2.vcxproj]
    17>AdditiveQuantizer.obj : error LNK2001: unresolved external symbol sgemm_ [F:\gitP\facebookresearch\faiss\build_amd64\faiss\faiss_avx2.vcxproj]
    17>VectorTransform.obj : error LNK2019: unresolved external symbol dgemm_ referenced in function "public: virtual void __cdecl faiss::ITQMatrix::train(__int64,float const *)" (?train@ITQMatrix@faiss@@UEAAX_JPEBM@Z) [F:\gitP\facebookresearch\faiss\build_amd64\faiss\faiss_avx2.vcxproj]

**Comment by mdouze** [comment]
Looks like a problem with the MKL flags.
