### ISSUE TITLE
QUESTION: Can I create an IndexIVFPQ object with custom centroids?

### ISSUE THREAD

**Issue by anirudhajith** [facebookresearch/faiss#2057]
Hello. I'm trying to run an experiment that involves using some custom centroids (that I generate) with the IVFPQ indexing structure. Since faiss provides highly optimised infrastructure and support for IVFPQ indexing, I would like to use it to perform my experiments.

Is it possible to to create an `IndexIVFPQ` object whose coarse and fine quantizer centroids are initialised to vectors I provide?

Here's what I tried doing to achieve this:

```python
quantizer = faiss.IndexFlatL2(d)  
index = faiss.IndexIVFPQ(quantizer, d, nlist, m, 8)
custom_coarse_centroids = <a numpy array>
custom_pq_centroids = <a numpy array>
quantizer.add(custom_coarse_centroids)
index.train(custom_coarse_centroids)
faiss.copy_array_to_vector(custom_pq_centroids.ravel(), index.pq.centroids)
```

After doing this, I verified by reading the corresponding centroids using `index.quantizer.reconstruct_n(0, index.nlist)` and `faiss.vector_to_array(index.pq.centroids).reshape(index.pq.M, index.pq.ksub, index.pq.dsub)` that the centroids are correctly set to what I want them to be. However, when I try to perform a query, I get nonsensical results such as negative distance estimates.

```python
index.add(xb)
D, I = index.search(xb[:5], k) # sanity check
print(I)
print(D)
```
I understand that certain distances and inner products are precomputed and stored inside an `IndexIVFPQ` object when the index is trained. Am I correct in thinking that what remains to be done to make my custom `IndexIVFPQ` object work correctly is to perform those precomputations? How can I make the `IndexIVFPQ` object carry out the relevant precomputations with the centroids I've just inserted?

Alternatively, is there a better way to achieve this? My end goal is to create a queryable `IndexIVFPQ` object with my own custom centroids instead of relying on `.train()` to learn them.

Thanks in advance for any help you can offer!

**Comment by mdouze** [comment]
A few things to keep in mind: 

- by default the IVFPQ encodes the residual of the vectors wrt. the centroids they are assigned to, not the vectors themselves

- the precomputed tables (used only for L2 search with residuals) are initialized after training so if you update the coarse or fine centroids after training you should call 

```
index.verbose = True # to see what happens
index.precompute_table()
```

**Comment by anirudhajith** [comment]
`index.precompute_table()` is exactly what I was looking for! It's working exactly as expected now. Thanks a lot!

I'm aware of the bit about the residuals being encoded, thanks.
