### ISSUE TITLE
Index large dataset, search on subset of variables

### ISSUE THREAD

**Issue by inti** [facebookresearch/faiss#2061]
Hi, 
I have a large dataset of N rows and p columns. 

for each pair of columns I need to find the k-nn for each of the N data points. At the moment I am building a `IndexFlatL2` for each  pair of columns and extracting the k-nn. 
At the moment I am doing this
```
N,p = 50, 150

data = np.random.random((N,p)
index = faiss.IndexFlatL2(2)
index.add(data[:,:2]) 
D, I = index.search(data, 3)
```
Is it possible to index the whole data and then search the k-nn using only a subset of the columns? something that would look like this

```
N,p = 50, 150

data = np.random.random((N,p)
index = faiss.INDEX(
index.add(data) 
D, I = index.search(data[:,:2], 3, cols = [0,1])

```

Thanks in advance

**Comment by mdouze** [comment]
Faiss is optimized for high-dimensional data. The performance on 2-dimensional vectors will be no better or worse than what you can code in numpy.

**Comment by inti** [comment]
Thanks for your response.
