### ISSUE TITLE
Sorting/combining search results across multiple indexes

### ISSUE THREAD

**Issue by khieu** [facebookresearch/faiss#2068]
### This is not an issue
Hi all, 
I am working on a large text classification dataset using FAISS search that does not fit into the memory. Thus, I index each class of data. For each query, I sequentially perform a FAISS knn search (L2 distance) in each chunk (class) of data. I want to aggregate all the search results across all the indexes but looking at the search results, it seems that the L2 distance does not carry the same meaning across different indexes. Specifically, with query `q_i, Index_j , top_k ->D_ij, I_ij`, a small value `D_i` in index `j` does not mean that query `i` is closer to top k in index `j` than say index `j'` because the distance is normalized in each index. 
Has anyone faced the same issue and would be so kind to share how to compare / sort or combine the search results across different indexes in a meaningful way?

Thank you so much in advance!

**Comment by mdouze** [comment]
Keep in mind that the search functions return approximate distances (except the flat indexes). 
The distances estimates between different types of indexes are not necessarily comparable. 
To make them comparable, you should train the index once and re-use the same trained index for all per-class indexes.
