### ISSUE TITLE
Documentation mentions a file that doesn't exist

### ISSUE THREAD

**Issue by israelg99** [facebookresearch/faiss#2073]
The documentation [here](https://github.com/facebookresearch/faiss/wiki/Index-IO,-cloning-and-hyper-parameter-tuning#example-usage) mentions a file `faiss/tests/demo_sift1M.cpp` that doesn't exist, not even a file with a string `sift1M` exists.

![image](https://user-images.githubusercontent.com/2307599/136099622-15e512fc-9d5c-4598-974a-fb2f8d9be17e.png)

Quick update: the file seems to currently reside in `faiss/demos/demo_sift1M.cpp`. GitHub doesn't allow PRs on Wikis.

**Comment by mdouze** [comment]
Fixed. Thanks for flagging!
