### ISSUE TITLE
Weird results on A100 when using faiss-gpu==1.6.3. All distances are 2.0.

### ISSUE THREAD

**Issue by zhangxinyu-xyz** [facebookresearch/faiss#2076]
# Summary

I got weird results, i.e., all distances are 2.0, when using faiss.bruteForceKnn function on A100. The faiss-gpu version is 1.6.3.

When using P40 or K40, results are normal.

The differences of A100 and P40 are:
pytorch version: A100-1.9.0-cuda11.1   P40-1.4.0-cuda10.0
system cuda version: A100-cuda11.2   P40-cuda10.1
ubuntu version: A100-18.04.5  P40-16.04.6

# Platform
Ubuntu

#Faiss version: pip install faiss-gpu==1.6.3

#Running on:
GPU

#Interface: 
Python

**Comment by mdouze** [comment]
could you post some reproduction code?

**Comment by mdouze** [comment]
code is not self-contained.
