### ISSUE TITLE
How to save faiss index to use later?

### ISSUE THREAD

**Issue by arian1020** [facebookresearch/faiss#2078]
I have a  huge amount of data and I want to train the index and search using the trained index later. 
For instance, you can save sklearn knn since it can be pickled, but is there a solution to save faiss index as well?

**Comment by arian1020** [comment]
@mdouze Thank you very much. I used it as follow:
from faiss import write_index, read_index
write_index(index, "large.index")
index = read_index("large.index")
and it works fine.
but in the documentation it is written as :
Index * index = read_index("large.index")
What it means by "Index * index"?

**Comment by SuoSiFire** [comment]
> @mdouze Thank you very much. I used it as follow: from faiss import write_index, read_index write_index(index, "large.index") index = read_index("large.index") and it works fine. but in the documentation it is written as : Index * index = read_index("large.index") What it means by "Index * index"?

I think that is c++ code。 @arian1020

**Comment by ArturPevko** [comment]
https://python.langchain.com/docs/integrations/vectorstores/faiss check that, if you use langchain

**Comment by tengwang0318** [comment]
> https://python.langchain.com/docs/integrations/vectorstores/faiss check that, if you use langchain

Langchain doesn't support for index search, and it only supports for Inner product and L2 distance search
