### ISSUE TITLE
Is it possible to slice index along dimension??

### ISSUE THREAD

**Issue by mingi3314** [facebookresearch/faiss#2079]
I want to search for similarity when the dimension of the query vector is not equal to that of the database. 

For example, let
```
d_db = 64                           # dimension of database
d_q = 30                            # dimension of query
nb = 100000                         # database size
nq = 1                              # nb of query

xb = np.random.random((nb, d_db)).astype('float32')
xq = np.random.random((nq, d_q)).astype('float32')

index = faiss.IndexFlatL2(d_db)
index.add(xb)
```

In this case, I wonder is it possible to slice the index along dimensions. I hope to make the shape of the sliced array become `(nb, d_q)`. If possible, I'd appreciate it if you tell me how to do it.

**Comment by mdouze** [comment]
No this is not supported.
