### ISSUE TITLE
Conda version has significant better performance

### ISSUE THREAD

**Issue by Zhehao-P** [facebookresearch/faiss#2080]
# Summary

When I build the Faiss python package using source code, the performance is 2x slower than using Conda installed Faiss package. (Index: IVFFLAT, Test dataset: SIFT1M)

# Platform

OS: Ubuntu 20.04.3 LTS

Faiss version: Faiss 1.7.1

Installed from: anaconda & compiled by myself

Faiss compilation options: cmake -B build . -DFAISS_ENABLE_GPU=OFF -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DFAISS_OPT_LEVEL=avx2 -DBLA_VENDOR=Intel10_64_dyn -DMKL_LIBRARIES=/usr/lib/x86_64-linux-gnu/mkl/libblas64.so

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [X] C++
- [X] Python

# Reproduction instructions

I installed the anaconda version using: conda install -c pytorch faiss-cpu. And compiled the 1.7.1 Faiss release zip file from https://github.com/facebookresearch/faiss/releases using the above command. 

The python test file I made is https://github.com/Zhehao-P/Faiss_test/blob/main/faiss_test.py

On my machine, the version that was compiled by myself takes 2x times to run. I have tried to switch between different -DBLA_VENDOR options and -DMKL_LIBRARIES options, but none of them can improve the self-compiled version's performance. And I have tried to add compiler options like using clang instead of using GNU to compile. The clang version has even worse performance.

I also tried to run tests using the c++ interface only to see if the problem is caused by python. But there is no performance change. Here is my c++ test code: https://github.com/Zhehao-P/faiss/blob/updated/tutorial/cpp/2-IVFFlat.cpp

I think this question might relate to one of the previously closed issues 1620. I'm wondering if anyone can help? Thanks.

**Comment by beauby** [comment]
> -DMKL_LIBRARIES='/usr/lib/x86_64-linux-gnu/libmkl_intel_lp64.so;/usr/lib/x86_64-linux/gnu/libmkl_sequential.so;/usr/lib/x86_64-linux-gnu/libmkl_core.so;-lpthread;-lm;-ldl'.

`libmkl_sequential.so` means single-threaded MKL implementation, this could contribute to lower performances.
