### ISSUE TITLE
Is there a way to iteratively train large indices on smaller machines?

### ISSUE THREAD

**Issue by abhinavkulkarni** [facebookresearch/faiss#2089]
# How to train (and update) large indices on smaller machines?

Hi,

Is there a way to iteratively train large indices? I have lots of data (3.5M high dimensional vectors) on a smaller machine (8GB of RAM).

Is there a way to iteratively train larger indices?

I am using the following snippet to train the index, however, I am running out of memory.

Thanks!

```python
d = 384
nlist = 50  # how many cells
quantizer = faiss.IndexFlatL2(d)
index = faiss.IndexIVFFlat(quantizer, d, nlist)

index.train(tensors)
index.add(tensors)
```

**Comment by mdouze** [comment]
Please bear in mind that it is useless to train on 3.5M vectors to get just 50 centroids. The ratio of nb of train vectors over nb centroids should be 30-1000.
This being said, there is a hard limitation on the number of training vectors that you can use: they need to fit in RAM: 3.5e6 * 384 * 4 is 5G of RAM so already a good fraction of available RAM. Then there is speed, if  the number of centroids is high, training will be very slow.
