### ISSUE TITLE
python api packing problem

### ISSUE THREAD

**Issue by boostlee** [facebookresearch/faiss#209]
Dear all,
       I am packing faiss python api for testing, but there exists some problems listed following. Looking forward your helps.

Here is my python method which call the faiss api.

************
      class faiss_index (object):
    def __init__(self, dim = 128, index_name = 'IVF4096,PQ64', device = 0, meanVal = None, eigVec = None, xtrain = None, xbase = None, xquery = None):
        Process.__init__(self)
        self._queryqueue = gQueryQueue
        self._resultqueue = gResultQueue
        self._pcaMeanVal = meanVal
        self._pcaEigVec = eigVec
        self._dim = dim
        self._index_name = index_name
        self._device = device
        self._oindex = None
        self._index = None
        self._nprob = 2
        self._verbose = True
        self._running = True
        self.init(xtrain = xtrain, xbase = xbase, xquery = xquery)
        
    def init(self, xtrain = None, xbase = None, xquery = None):
        res = faiss.StandardGpuResources()
        self._oindex = faiss.index_factory(self._dim, self._index_name)
        self._oindex.own_fields = True
        self._oindex.this.disown()
        co = faiss.GpuClonerOptions()
        co.useFloat16 = True
        co.device = self._device
        self._index = faiss.index_cpu_to_gpu(res, self._device, self._oindex, co)
        self._index.this.disown()
        self._index.own_fields = True
        self._index.setNumProbes(1 << self._nprob)
        print('faiss index init over, dim:', self._dim, ' @', self._index_name)
        if xtrain is not None:
            self.train(xtrain = xtrain)
            if xbase is not None:
                self.load_base(xbase = xbase)
                if xquery is not None:
                    print('search demo:')
                    self.search(xquery = xquery)

    def set_verbose(self, verbose = True):
        self._verbose = verbose
        
    def set_nprob(self, prob):
        self._nprob = prob
        self._index.setNumProbes(1 << self._nprob)
     
    def get_nprob(self):
        return self._index.getNumProbes()
        
    def train(self, xtrain):
        xtrain = xtrain.astype('float32')
        t0 = time.time()
        print('index train with ', xtrain.shape ,' ...')
        print(self._index)
        self._index.train(xtrain)
        print('index train over, used %0.3f sec' %(time.time() - t0))
        
    def load_base(self, xbase):
        xbase = xbase.astype('float32')
        print('index base loading with ', xbase.shape, ' ...')
        t0 = time.time()
        self._index.add(xbase)
        print('index base load over, used %0.3f sec' %(time.time() - t0))
        
    def search(self, xquery):
        xquery = xquery.astype('float32')
        print('index searching with ', xquery.shape, ' ...')
        t0 = time.time()
        D, I = self._index.search(xquery, 100)
        if self._verbose:
            print('nprobes=%4d' %(self._nprob))
            print(I[:,:5])
        print('search over, used %0.3f sec' %(time.time() - t0))
        return D, I
**********
Code in init method runs ok with xtrain, xbase and xquery supplied, but  after init called, calling the faiss search() in another method failed with SEGMENT FAULT, I tracked the dumped core and got the error within GpuIndexFlat.cu:GpuIndexFlat::search  auto outDistances = toDevice<...>
Besides, if the self._index.train() were not called in init method, it will be SEGMENT FAULT when faiss train() called outside of init.
Please help, thanks a lot.
***********
index = faiss_index(dim = 128, index_name='IVF4096,PQ64', device = 0, meanVal = meanVals, eigVec = redEigVects)
    print(index)
    print('nbrobe:', index.get_nprob())
    index.train(xt) #segment fault here
***********

**Comment by boostlee** [comment]
It seems that the FAISS index can only be used in one function domain.
In init method, the FAISS index is created, and used. Segment fault when calling train or search in another method. Does these phenomenon related with FAISS index scope, how to use FAISS python api in different methods?

**Comment by wickedfoo** [comment]
The problem here is almost certainly that the faiss.StandardGpuResources is not being kept in scope for the lifetime of the index. Unfortunately the underlying Faiss API is not reference counted, so you need to hold onto this object as long as the index is around.

**Comment by wickedfoo** [comment]
i.e., you need `self._res = faiss.StandardGpuResources()`

**Comment by boostlee** [comment]
@wickedfoo, thanks, I did find this problem too, _res has been released out of init method.
