### ISSUE TITLE
Does the Conda installation work in Cpp?

### ISSUE THREAD

**Issue by Gian-Alessio** [facebookresearch/faiss#2090]
# Summary
Hey guys so your recommended of installing faiss is using conda. Now after installing faiss with conda, how exactly would I import it into my cpp file? Is that even possible or is the conda installation python only?

Running on:
- [X] CPU
- [X] GPU

Interface: 
- [X] C++

**Comment by mdouze** [comment]
Conda is python only. 
For C++ you should use the cmake compilation.

**Comment by h-vetinari** [comment]
> Conda is python only.

That is not true, conda can handle pretty much arbitrary languages & build-dependencies. In fact, conda-forge is building the CPP lib as `libfaiss` and can be installed as usual `conda install -c conda-forge libfaiss`. This has all the headers under `$PREFIX/include/faiss`, and this is [checked](https://github.com/conda-forge/faiss-split-feedstock/blob/master/recipe/meta.yaml#L165) in the CI of the conda-forge feedstock.

**Comment by h-vetinari** [comment]
This doesn't come with a "convenience wrapper" around gpu/cpu variants (like `faiss-cpu` & `faiss-cpu`). By default the GPU variant should be picked, but you can force one or the other by using the build string to differentiate, e.g. `conda install -c conda-forge libfaiss=*=*cuda` resp. `libfaiss=*=*cpu`.

**Comment by ChenZhongPu** [comment]
`lib` and `include` folders are found after installing faiss with `conda install -c pytorch faiss-gpu`. Can I directly specify the path using：

```
set(FAISS_INCLUDE_DIR "xxx/miniconda/envs/faiss/include")
set(FAISS_LIBRARY "xxx/miniconda/envs/faiss/lib/libfaiss.so")
include_directories(${FAISS_INCLUDE_DIR})
```
