### ISSUE TITLE
faiss:HNSWStats SIGILL

### ISSUE THREAD

**Issue by Gian-Alessio** [facebookresearch/faiss#2094]
# Summary
Hey guys! I just build faiss.1.5.2 for the first time by myself to use it in Cpp. 
My CmakeLists.txt:
find_library(LibFaiss faiss HINT /home/tim/faiss/faiss-1_5_3/faiss-1.5.3/)
catkin_add_gtest(test_inverted_ndex test/test_inverted-index.cc
                 WORKING_DIRECTORY ${CMAKE_BINARY_DIR}})
target_link_libraries(test_inverted_index ${LIBRARY_NAME} ${LibFaiss})

And I am just trying to use the Index
`faiss::IndexFlatL2 ` just like in your tutorial.

But I am getting an 

> SIGILL illegal instuction Error
looking into GDB the illegal expression is at:

> faiss::HNSWStats::reset HNSW.h:263
faiss::HNSWStats::HNSWStats HNSW.h:259
__static_initialization_and_destruction_0 IndexHNSW.cpp:59
_GLOBAL__sub_I_IndexHNSW.cpp(void) IndexHNSW.cpp:1082
call_init 0x00007f6db4db18d3
_dl_init 0x00007f6db4db18d3
_dl_start_user 0x00007f6db4da20ca
<unknown> 0x0000000000000003
<unknown> 0x00007fffa2525c56
<unknown> 0x00007fffa2525ca3
<unknown> 0x00007fffa2525d1d
<unknown> 0x0000000000000000

looking into the code its the following:
`  void reset() {
    **n1 = n2 = n3 = 0;**
    ndis = 0;
    nreorder = 0;
    view = false;
  }`

# Platform

Ubuntu 18.04

Faiss version: git commit efa81eec762e79d26121de56a58c325ee3ca0f83 1.5.3

Installed from: compiled myself

Running on:
- [ x] CPU
- [x ] GPU

Interface: 
- [x ] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
It may be because you are building with AVX2 but your CPU does not support it...
