### ISSUE TITLE
CUDA error 77

### ISSUE THREAD

**Issue by sharthZ** [facebookresearch/faiss#210]
Hello everyone, got this error when load 1M index.

> > Faiss assertion 'err__ == cudaSuccess' failed in faiss::gpu::DeviceTensor<T, Dim, Contig, IndexT, 
> PtrTraits>::~DeviceTensor() [with T = float; int Dim = 3; bool Contig = true; IndexT = int; PtrTraits = faiss::gpu::traits::DefaultPtrTraits] at impl/../utils/DeviceTensor-inl.cuh:61; details: CUDA error 77
> > Aborted (core dumped)

Hardware: GTX 1070, compiled with 

> -gencode arch=compute_61,code="compute_61"

Index key - "OPQ16_64,IVF32768,PQ16"

**Comment by sharthZ** [comment]
There is nothing special:
``` python
for i in range(faiss.get_num_gpus()):
    res = faiss.StandardGpuResources()
    if self.tempmem >= 0:
        res.setTempMemory(self.tempmem)
    self.gpu_resources.append(res)

co = faiss.GpuClonerOptions()
co.useFloat16 = self.use_float16
co.useFloat16CoarseQuantizer = False
co.usePrecomputed = self.use_precomputed_tables
indexall = faiss.read_index(str(index_cachefile)) #just load stored index
self.index = faiss.index_cpu_to_gpu(self.gpu_resources[0], 0, indexall, co)
```
Error occured, when i try move index to GPU (faiss.index_cpu_to_gpu).

**Comment by wickedfoo** [comment]
How was the CPU index constructed?

Are precomputed tables enabled? Try turning that off and see if it works (`co.usePrecomputed = False`).

Precomputed table computation requires 1 GB of memory here, which while not close to your memory limit, could be causing problems.

It would help if you could attach a debugger like gdb to the run and get a C++ callstack at the point which it crashed.

**Comment by mdouze** [comment]
Closing. Please re-open to follow up @wickedfoo's question.
