### ISSUE TITLE
How to get returned scores in terms of 0-1 range instead of L2 distances?

### ISSUE THREAD

**Issue by kaleemiqb** [facebookresearch/faiss#2100]
# Summary
I am using Huggingface dataset to add FAISS index to sentence embeddings (dataset.add_faiss_index (column="embeddings", metric_type= faiss.METRIC_L2).  I am using dataset.get_nearest_neighbors to retrieve the scores and matches.

It works fine and returns scores in terms of L2 distance values (queries for which exact match is found return distance value of 0 and for queries which are very different than any entries in dataset it returns larger values of around 12-14 range)  

I need returned scores to be between 0-1 range with 1 being perfect match. How can I achieve this?

I tried using metric_type=faiss.METRIC_INNER_PRODUCT but it does not return correct matches. 
Is there a way to correctly use faiss.normalize_l2 to get cosine similarity returned from .get_nearest_neighbors? If yes, do we use faiss.normalize_l2 with dataset before adding faiss index? and do we have to normalize the queries too? 

I also tried a crude way of 1/(1+d)  where d is the distance score returned by above. It would work for exact matches (1/(1+0) =100%) but those queries which were almost identical to an entry in dataset and had a distance score of say 0.8, will have a very less score (1/1.8= 55% only, which shoud ideally be much higher in terms of percentage).

# Platform

Running on:
- [v ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ v] Python

# Reproduction instructions

**Comment by mdouze** [comment]
This is a score normalization question, not really related to Faiss itself...

**Comment by opokualbert** [comment]
@kaleemiqb have you been able to figure this out?

**Comment by cao-nv** [comment]
As mdouze stated above, this is a problem related to how you normalize your vector. 
Let's say you normalized all your vectors to unit magnitude, the maximum L2-distance between 2 arbitrary points is 2. Hence, you can do simple math to make the final output score to 0-1. 
If you didn't make any normalization, there is no correct way to make the output to the expected range.

**Comment by opokualbert** [comment]
This did the trick: 
index = faiss.index_factory(d, "Flat", faiss.METRIC_INNER_PRODUCT)
index.ntotal
faiss.normalize_L2(doc_embeddings)
index.add(doc_embeddings)
faiss.normalize_L2(xq)
distance, index = index.search(xq, 5)
print('Distance by FAISS:{}'.format(distance))

**Comment by Cognitus-Stuti** [comment]
what about when you are using int8 or ubinary indexes?
