### ISSUE TITLE
Can I try larger k (>2048) on GPU? 

### ISSUE THREAD

**Issue by ruizewang** [facebookresearch/faiss#2103]
# Summary

What should I do if I want to use Faiss k>2048 on GPU?

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU
- [√] GPU

Interface: 
- [ ] C++
- [√] Python

**Comment by wickedfoo** [comment]
no, unfortunately not supported

**Comment by DennisZhao168** [comment]
may I know if this limitation is still effective in the latest Faiss GPU as we need to return more than 2048 top candidates?

**Comment by haok1402** [comment]
@DennisZhao168 

I can confirm that this is still a hard limit on the latest version,

```
faiss-gpu                 1.8.0           py3.11_h4c7d538_0_cuda12.1.1    pytorch
```

```
/home/circleci/miniconda/conda-bld/faiss-pkg_1709244513520/work/faiss/gpu/impl/IndexUtils.cu:26: Error: 'k > 0 && k <= 
getMaxKSelection()' failed: GPU index only supports min/max-K selection up to 2048 (requested 4096)
```

**Comment by zhaojinzhou** [comment]
what's the motivation of the confination of top k  on gpu search?
Since the gpu search is so fast? why can't we search a large top k?

**Comment by raraz15** [comment]
I may have missed something in the documentation, but I feel this limitation wasn’t clearly indicated. 
It would be really helpful if this limitation were documented more explicitly or surfaced earlier in the tutorials or API docs to help others avoid similar frustration.
