### ISSUE TITLE
cudaMalloc error out of memory

### ISSUE THREAD

**Issue by ViokingTung** [facebookresearch/faiss#2105]
# Summary

I used index **IndexFlatL2**,and write_index on the disk after build index,it comes to **cudaMalloc error out of memory** when I search 

# Platform

OS: centos 7.6

Faiss version: 1.7.1

Installed from: anaconda

Faiss compilation options: 

Running on:

- [× ] CPU
- [ ] GPU

Interface: 

- [ ×] C++
- [ ] Python

# Reproduction instructions

code:

```python
k = 5

res = faiss.StandardGpuResources()

index = faiss.read_index(index_file_path)

gpu_index_flat = faiss.index_cpu_to_gpu(res, 0, index)

D, I = gpu_index_flat.search(np.load(search_vector_path), k)



RuntimeError: Error in virtual void* faiss::gpu::StandardGpuResourcesImpl::allocMemory(const faiss::gpu::AllocRequest&)
              at /root/miniconda3/conda-bld/faiss-pkg_1623030479928/work/faiss/gpu/StandardGpuResources.cpp:452: 
              Error: 'err == cudaSuccess' failed: StandardGpuResources: alloc fail type TemporaryMemoryBuffer 
              dev 0 space Device 	stream 0x7f7b46ba9a60 size 1610612736 bytes (cudaMalloc error out of memory [2])
```

**Comment by wickedfoo** [comment]
Your index is probably too large? How many vectors and what is the dimensionality?

**Comment by ViokingTung** [comment]
> Your index is probably too large? How many vectors and what is the dimensionality?

vectors: 10k
dimension: 2048
but i need to load different index from disk many times(this operation may be cause this error),do you have any idea?

**Comment by ViokingTung** [comment]
> Your index is probably too large? How many vectors and what is the dimensionality?

hello，how to remove index from cuda

**Comment by mdouze** [comment]
So the problem seems to be that the index is re-created several times?

**Comment by mdouze** [comment]
Tried in a loop: [track_mem.py](https://gist.github.com/mdouze/fc84b3e7d6d8c5e9cabf22e737da7d27)
It does not seem to leak mem
