### ISSUE TITLE
"import faiss" works in jupyternotebook but doesn't work in VS Code

### ISSUE THREAD

**Issue by Nandu-H** [facebookresearch/faiss#2107]
# Summary

 I met a strenge problem, when i installed faiss, I found that "import faiss" works in jupyternotebook but doesn't work in VS Code. How could it happen? Please help me figure it out.

# Platform

OS:  Windows 10 

Faiss version: faiss-cpu    1.7.1        hf9c7e24_1    conda-forge

Installed from: anaconda?

Faiss compilation options: mkl 2021.4.0  haa95532_640
Running on:
- [-] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [-] Python

# Reproduction instructions

File "e:/****/retrieval/hnsw_faiss.py", line 23, in <module>
    import faiss
  File "D:\Users\Nandu\AppData\Local\Continuum\anaconda3\envs\faiss\lib\site-packages\faiss\__init__.py", line 18, in <module>
    from .loader import *
  File "D:\Users\Nandu\AppData\Local\Continuum\anaconda3\envs\faiss\lib\site-packages\faiss\loader.py", line 65, in <module>
    from .swigfaiss import *
  File "D:\Users\Nandu\AppData\Local\Continuum\anaconda3\envs\faiss\lib\site-packages\faiss\swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: DLL load failed: The specified module could not be found。

**Comment by Nandu-H** [comment]
I‘m sure that that the python interpreter in VS Code  is same with anaconda envs

**Comment by h-vetinari** [comment]
It's possible that VS Code does not recognize the environment correctly. In particular, the PATH to where the libraries (e.g. that DLL) are saved within the conda environment must be correct.

Can you do something like `print('\n'.join(os.environ["PATH"].split(';')))` within VS Code?

**Comment by Nandu-H** [comment]
it says : SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

------------
here is the code : 
import os
print('\n'.join(os.environ("D:\Users\Nandu\AppData\Local\Continuum\anaconda3\envs\pytorch-gpu\lib\site-packages\faiss\swigfaiss.py").split(';')))

**Comment by Nandu-H** [comment]
> it says : SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
> 
> here is the code : import os print('\n'.join(os.environ("D:\Users\Nandu\AppData\Local\Continuum\anaconda3\envs\pytorch-gpu\lib\site-packages\faiss\swigfaiss.py").split(';')))

**Comment by Nandu-H** [comment]
> It's possible that VS Code does not recognize the environment correctly. In particular, the PATH to where the libraries (e.g. that DLL) are saved within the conda environment must be correct.
> 
> Can you do something like `print('\n'.join(os.environ["PATH"].split(';')))` within VS Code?

it says : SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

here is the code :
import os
print('\n'.join(os.environ("D:\Users\Nandu\AppData\Local\Continuum\anaconda3\envs\pytorch-gpu\lib\site-packages\faiss\swigfaiss.py").split(';')))

**Comment by h-vetinari** [comment]
Please do not replace the `"PATH"` bit in the command I posted. `os.environ["PATH"]` will give the equivalent of `echo %PATH%`, the environment variable (and not your current working directory or anything else).

**Comment by Nandu-H** [comment]
> print('\n'.join(os.environ["PATH"].split(';')))

got it ! here is the output:
>>>>>
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\libnvvp

C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
C:\Program Files (x86)\Graphviz2.38\bin
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files\NVIDIA Corporation\Nsight Compute 2020.2.0\
C:\tools\cuda\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\extras\CUPTI\lib64
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include
D:\Program Files\Git\cmd
D:\Users\Nandu\AppData\Local\Continuum\anaconda3\envs\pytorch-gpu\Lib\site-packages\cmake\data\bin
D:\Users\Nandu\AppData\Local\Continuum\anaconda3\Library\bin
C:\Program Files\Microsoft VS Code\bin
D:\Users\Nandu\AppData\Local\Continuum\anaconda3
D:\Users\Nandu\AppData\Local\Continuum\anaconda3\Library\mingw-w64\bin
D:\Users\Nandu\AppData\Local\Continuum\anaconda3\Library\usr\bin
D:\Users\Nandu\AppData\Local\Continuum\anaconda3\Scripts
C:\Users\Nandu\AppData\Local\Microsoft\WindowsApps
C:\Program Files\JetBrains\PyCharm 2021.1\bin

**Comment by Nandu-H** [comment]
> Please do not replace the `"PATH"` bit in the command I posted. `os.environ["PATH"]` will give the equivalent of `echo %PATH%`, the environment variable (and not your current working directory or anything else).

got it ! here is the output:
>>>>>>>
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\libnvvp

C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0
C:\Windows\System32\OpenSSH
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
C:\Program Files (x86)\Graphviz2.38\bin
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0
C:\WINDOWS\System32\OpenSSH
C:\Program Files\NVIDIA Corporation\Nsight Compute 2020.2.0
C:\tools\cuda\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\extras\CUPTI\lib64
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include
D:\Program Files\Git\cmd
D:\Users\Nandu\AppData\Local\Continuum\anaconda3\envs\pytorch-gpu\Lib\site-packages\cmake\data\bin
D:\Users\Nandu\AppData\Local\Continuum\anaconda3\Library\bin
C:\Program Files\Microsoft VS Code\bin
D:\Users\Nandu\AppData\Local\Continuum\anaconda3
D:\Users\Nandu\AppData\Local\Continuum\anaconda3\Library\mingw-w64\bin
D:\Users\Nandu\AppData\Local\Continuum\anaconda3\Library\usr\bin
D:\Users\Nandu\AppData\Local\Continuum\anaconda3\Scripts
C:\Users\Nandu\AppData\Local\Microsoft\WindowsApps
C:\Program Files\JetBrains\PyCharm 2021.1\bin

**Comment by h-vetinari** [comment]
It looks very much like the case I described above:
> It's possible that VS Code does not recognize the environment correctly. In particular, the PATH to where the libraries (e.g. that DLL) are saved within the conda environment must be correct.

You can compare by running the same command in a normal conda-environment, and you will see that the first few entries will look different - pointing to the conda environment, which is necessary for the libraries to be found, etc. (though there's more to setting up an environment than just changing the `%PATH%`.)

I suggest googling "vs coda conda environment" - literally the first [link](https://medium.com/@udiyosovzon/how-to-activate-conda-environment-in-vs-code-ce599497f20d) looks pretty useful already.

**Comment by Nandu-H** [comment]
> It looks very much like the case I described above:
> 
> > It's possible that VS Code does not recognize the environment correctly. In particular, the PATH to where the libraries (e.g. that DLL) are saved within the conda environment must be correct.
> 
> You can compare by running the same command in a normal conda-environment, and you will see that the first few entries will look different - pointing to the conda environment, which is necessary for the libraries to be found, etc. (though there's more to setting up an environment than just changing the `%PATH%`.)
> 
> I suggest googling "vs coda conda environment" - literally the first [link](https://medium.com/@udiyosovzon/how-to-activate-conda-environment-in-vs-code-ce599497f20d) looks pretty useful already.

>>> Thanks bro !  You're brilliant! Though I met some other problems , I figured it out at last, and it was exactly what you said !
Thank you so much , have a nice day!

**Comment by wwdok** [comment]
This issue still exists in today's @[vscode](https://github.com/microsoft/vscode). I run `print('\n'.join(os.environ["PATH"].split(';')))` in vscode python file and in vscode jupyter notebook, jupyter notebook print out more PATHs. I hope faiss not to require users to use faiss only in conda env. Because when i open windows terminal(or power shell), i also have to `conda activate base` at first, this is not convinient.
