### ISSUE TITLE
How can I update FAISS index that on disk ?

### ISSUE THREAD

**Issue by abdullahbas** [facebookresearch/faiss#2109]
# Summary
Q1
I am trying to update my blocks on disk with respect to the index that is currently running on the script. I am capable to add new blocks but I have doubts on does FAISS saves all of the index to the new block or does it save only newly added data to the new block?  
Q2
Is there any way to save FAISS index (loaded from the disk /from blocks) after adding new data without creating new blocks?  

Faiss version: <faiss-gpu=1.7.1>

Installed from: <pip> 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by mdouze** [comment]
What are blocks? Are you referring to an OnDisk index built from several indexes?

**Comment by mdouze** [comment]
It is not practical to add vectors to an OnDisk index. I would suggest that you keep an in-RAM index for the additional vectors and merge the results from the static OnDisk index and the in-RAM index.

**Comment by abdullahbas** [comment]
Ok, I will update my pipe like that. Thanks for the help and FAISS.

**Comment by abdullahbas** [comment]
Ok, I will update my pipe like that. Thanks for the help and FAISS.

**Comment by gustavz** [comment]
>  It is not practical to add vectors to an OnDisk index. I would suggest that you keep an in-RAM index for the additional vectors and merge the results from the static OnDisk index and the in-RAM index.

@mdouze is this still the preferred approach or are there now supported ways to update OnDisk indexes?
