### ISSUE TITLE
what's the relationship between IndexHNSW and impl/HNSW?

### ISSUE THREAD

**Issue by fgheng** [facebookresearch/faiss#2110]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

 

I want to use indexHNSW but i can not find where to set efconstruction.

**Comment by mdouze** [comment]
it is in `index.hnsw.efConstruction`
