### ISSUE TITLE
Is there a more efficient way to load raw vector files from disk？

### ISSUE THREAD

**Issue by SuoSiFire** [facebookresearch/faiss#2116]
The original vector data is stored on the disk. When the amount of data is large, it takes a lot of time to read. Is there a better way to read it? Language is c++.

**Comment by mdouze** [comment]
If the data format on disk is raw, then you are limited by the disk I/O speed. 
For some types of data it may be efficient to load from disk and decompress on-the-fly.

**Comment by SuoSiFire** [comment]
Thanks， I tried to use fwrite to write the raw vector to stream and use fread to read it. It takes 1 min to read a 10M 256-dimensional vector, which seems acceptable.
