### ISSUE TITLE
download googletest failed

### ISSUE THREAD

**Issue by se7enXF** [facebookresearch/faiss#2118]
# Summary
After entering `cmake -B build .`, the process is stuck after `-- A library with LAPACK API found.`. About 30 
minutes later, Error appears with `download googletest failed`. I download `googletest` from web using VPN and put it into directory where 
it shoud be, but the same error appear again. Could I skip downloading googletest and build faiss? My network cannot access.

# Platform

OS: 
ARM Linux 64
Faiss version: 
1.7.1
Installed from:  
CMake
Faiss compilation options: 
cmake -B build . -DFAISS_ENABLE_GPU=OFF -DFAISS_ENABLE_PYTHON=OFF -DBUILD_SHARED_LIBS=ON
Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

[root@localhost faiss-1.7.1]# cmake -B build . -DFAISS_ENABLE_GPU=OFF -DFAISS_ENABLE_PYTHON=OFF -DBUILD_SHARED_LIBS=ON
-- The CXX compiler identification is GNU 4.8.5
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_CXX: -fopenmp (found version "3.1")
-- Found OpenMP: TRUE (found version "3.1")
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Could NOT find MKL (missing: MKL_LIBRARIES)
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /usr/lib64/libopenblas.so
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
[here, stuck a very long time until Error]

**Comment by beauby** [comment]
You can skip testing (which will avoid downloading gtest) by supplying `-DBUILD_TESTING=OFF` to cmake.
