### ISSUE TITLE
GPU compile error

### ISSUE THREAD

**Issue by IrvingShu** [facebookresearch/faiss#212]
I download the faiss, follow the install instruction and when compile the GPU folder, meet the follow error:

-Xlinker /usr/local/lib/libopenblas.so.0 /usr/lib/lapack/liblapack.so.3
nvcc fatal   : Don't know what to do with '/usr/lib/lapack/liblapack.so.3'
Makefile:90: recipe for target 'test/demo_ivfpq_indexing_gpu' failed
make: *** [test/demo_ivfpq_indexing_gpu] Error 1

Can anyone help?

**Comment by mdouze** [comment]
Hi
Please add `-Xlinker` before '/usr/lib/lapack/liblapack.so.3'

**Comment by IrvingShu** [comment]
Solve, THX mdouze
