### ISSUE TITLE
NSG + Quantization

### ISSUE THREAD

**Issue by Nickedude** [facebookresearch/faiss#2128]
# Summary

For HNSW one can use e.g IndexHNSWSQ to apply quantization to the data in the index. This option does not seem to exist for NSG, as there is only IndexNSGFlat.  

Are there any fundamental blockers for adding e.g IndexNSGSQ?

# Platform

Running on:
- [X] CPU
- [X] GPU

Interface: 
- [X] C++
- [X] Python

**Comment by mdouze** [comment]
Not really. Marking as an enhancement. Feel free to submit a PR if you want to work on it.

**Comment by KinglittleQ** [comment]
Actually you could build an IndexNSGSQ by:
```python
indexsq = faiss.IndexScalarQuantizer(d, qtype, metric)
index = faiss.IndexNSG(indexsq, M)
```

If you'd like to create a PR, please refer to this:

https://github.com/facebookresearch/faiss/blob/7492d233541acdab1fc8c7e7a6bb02b8ad535e1f/faiss/IndexHNSW.cpp#L934-L942

Otherwise, I would take some time to do it.

**Comment by Nickedude** [comment]
I'll give it a shot!
