### ISSUE TITLE
Force index to be deleted

### ISSUE THREAD

**Issue by billyean** [facebookresearch/faiss#2131]
# Summary

Our application is based on Faiss. We create many indices and put them into Python map with corresponding key, the application have to change the data from time to time, the way we did is recreate indices and replace them into the map with corresponding key. We found the memory usage jump in every replacement, and it will reach 3 times of data eventually. We think the reason is Python's GC won't release the indices' memory. Is the any way we can force index to release memory, we've tried to explicitly call del index, but it seems it doesn't work.

# Platform

Linux

OS: 

Faiss version: 

Installed from:  anaconda

Faiss compilation options: 

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

**Comment by mdouze** [comment]
You can try gc.collect() but usually if the index is not released, it means there is some reference to it.
