### ISSUE TITLE
 FAISS-GPU cannot be used with GPU version 30xx

### ISSUE THREAD

**Issue by phanxuanduc1996** [facebookresearch/faiss#2139]
Hi @facebookresearch and everyone,

I'm writing Python source code and using Faiss. I can use Faiss on CPU, 20xx GPU eg: RTX 2080Ti,... However, when I run on devices like RTX 3060, RTX 3070, the system freezes and I can't kill the program by Ctrl + C.
Here is the source code I use: https://github.com/facebookresearch/faiss/blob/main/tutorial/python/5-Multiple-GPUs.py

If anyone has encountered this error and successfully fixed it, please share how to do it with me.
Thanks so much.

OS: Ubuntu 20.04
Faiss version: release 1.7.1
Running on: GPU + Python

**Comment by phanxuanduc1996** [comment]
I used Anaconda, I installed bellow, it worked. If you use Docker, please install Miniconda.
`conda install faiss-gpu cudatoolkit=11.1 -c pytorch-gpu`
`conda install -c anaconda pytorch-gpu`

**Comment by toshalpatel** [comment]
faiss not working with gpu, but working using CPU.
