### ISSUE TITLE
Error:'nullptr' was not declared in this scope

### ISSUE THREAD

**Issue by hengshanji** [facebookresearch/faiss#214]
I build faiss in docker. And i want rebuild some demos. After i install gtest and run "cmake and make", this error happens. I think i need compile the demo with  -std=c++0x or -std=gnu++0x, but i know how to add these parameters.

**Comment by mdouze** [comment]
Hi 
See here
https://github.com/facebookresearch/faiss/wiki/Troubleshooting#nullnullptr0

**Comment by mdouze** [comment]
Please see the cmake manual to add new flags.
