### ISSUE TITLE
Implement K-means with GPU-tensors (Pytorch)

### ISSUE THREAD

**Issue by czhaneva** [facebookresearch/faiss#2140]
I am a new one to faiss. My faiss version is **1.7.1** with **gpu**. My operating system is **Ubuntu**. The language I would like to use is **python**.

Recently, I'd like to implement K-means with GPU-tensors, I found that the faiss mainly support numpy array, I have achieved it with numpy array. It's very inefficient because the conversion of data between GPU and CPU, numpy and tensor.
I recently discovered that faiss seems to support tenors in GPU. but I didn't find a clear tutorial.

 The follow is my numpy version code, I think it achieves 
1. clustering x 
2. finding the index of the topk vectors closest to the centroid of the cluster where the query is assigned.
```
@torch.no_grad()
def run_kmeans(self, x, query, topk, args=None):
        '''
        :param x:   Tensor (C, K) 
        :param args:  cluster args 
        :param query: Temspr (N, C) 
        :param topk: int num 
        :return:    topk index for query 
        '''
        x = x.T.cpu().numpy() 
        query = query.detach().cpu().numpy()
        d = x.shape[1]
        k = args.num_cluster
        clus = faiss.Clustering(d, k)
        clus.verbose = args.verbose
        clus.niter = args.niter
        clus.nredo = args.nredo
        clus.seed = args.seed
        clus.max_points_per_centroid = args.max_points_per_centroid
        clus.min_points_per_centroid = args.min_points_per_centroid

        res = faiss.StandardGpuResources()
        cfg = faiss.GpuIndexFlatConfig()
        cfg.useFloat16 = False
        cfg.device = args.gpu
        index = faiss.GpuIndexFlatL2(res, d, cfg)
        clus.train(x, index)
        D, I = index.search(query, topk)
        return (torch.from_numpy(I)).cuda()
```
I hope to directly use gpu-tensors instead of transfering it to numpy. I would like to know if faiss currently supports this operation, and if so, how do I do it. I'm looking forward to your help.

**Comment by mdouze** [comment]
The only expensive operation in k-means is the assignment step. You can do it on GPU directly from tensors with `knn_gpu`, see https://github.com/facebookresearch/faiss/blob/main/faiss/gpu/test/torch_test_contrib_gpu.py#L255

some doc here: 
https://github.com/facebookresearch/faiss/blob/151e3d7be54aec844b6328dc3e7dd0b83fcfa5bc/contrib/README.md#torch_utilspy

However, for non-trivial k-means, the speed is compute-bound, so don't expect much speedup because you avoid CPU-GPU transfers or numpy-pytorch conversions.

**Comment by czhaneva** [comment]
Thanks for your help, it's great help~
