### ISSUE TITLE
GPU topK=1 slower than topK=100

### ISSUE THREAD

**Issue by WenqiJiang** [facebookresearch/faiss#2141]
Dear Faiss team, 

I just found that if I set topK = 1 during the GPU search, the performance is lower than 2 <= topK <=100. I used SIFT500M dataset with IVF65536,PQ16, nprobe=46. Other settings show a similar phenomenon. 

On the other hand, the performance when 2 <= K <= 100 remains stable (almost a constant), which I assume is due to the implementation. But is there any reason leading to a slower K=1?

Some performance results:

```
  probe=46 : 0.851 s (QPS=11746.480) 1-R@1: 0.3427 

  probe=46 : 0.576 s (QPS=17368.042) 1-R@1: 0.3426 1-R@2: 0.4860 

  probe=46 : 0.585 s (QPS=17089.872) 1-R@1: 0.3427 1-R@10: 0.7930 1-R@100: 0.9500 
```

Thanks a lot!

**Comment by wickedfoo** [comment]
Are you running the k=1 version first in the program? There might be startup overhead, is best to perform a search before timing it for real.
