### ISSUE TITLE
Cannot use float16 arrays and tensors directly for storage, computation, and as arguments on CPU/GPU indexes

### ISSUE THREAD

**Issue by munael** [facebookresearch/faiss#2149]
# Summary

Is there a way to use fp16/float16 numpy arrays and torch tensors directly as arguments for `train`, `add`, and `search` on indexes without scalar quantization (as opposed to converting to fp32 and back to fp16 through scalar quantization)?

# Platform

OS: 

Faiss version: 1.7.1

Installed from: pip 

Faiss compilation options: 

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

```py
import faiss.contrib.torch_utils
import faiss, torch
D = 32
idx = faiss.index_factory(D, 'IVF384,Flat')
res = faiss.StandardGpuResources()
gidx = faiss.index_cpu_to_gpu(res, 0, idx)
bank = torch.randn(1000, D).to('cuda', torch.float16)
query = torch.randn(100, D).to('cuda', torch.float16)
gidx.train(bank) # AssertionError ---> 49     assert x.dtype == torch.float32
```

**Comment by mdouze** [comment]
It's not supported. However, I am not sure this matters that much in terms of performance or memory usage. Even a GPU->CPU->GPU roundtrip is rarely a performance bottleneck.

**Comment by munael** [comment]
For some context, I've tried clustering (using `Kmeans`), then moving the cluster vectors to GPU and using:

- `faiss.knn_gpu`
- `torch.mm` followed by `torch.topk`

This doesn't make sense given that the clustering is L2-based. But the source of the `xb` vectors doesn't matter. Just specify `metric=faiss.METRIC_INNER_PRODUCT` for `knn_gpu`.

And then, even with the all tensors already on (the same) GPU, `faiss.knn_gpu` is slower than `mm` and `topk`.

On a V100:
1. torch ops get: 976 micro sec
2. faiss knn_gpu gets: 2230 micro sec

There's also consideration for memory usage given the intermediate tensors needed for the torch version, but that still doesn't explain the difference in speed compared to faiss' optimized kernel (although I've _no_ idea what it's doing or guaranteeing, exactly).

Code:
```py
B, D = 100_000, 1024
Xb = torch.randn(512, D, device='cuda', dtype=torch.float16)
Xq = torch.randn(B, D, device='cuda', dtype=torch.float16)

def faiss_knn(res, xb, xq, k):
    return faiss.knn_gpu(res, xb=xb, xq=xq, k=k, metric=faiss.METRIC_INNER_PRODUCT)
def torch_knn(res, xb, xq, k):
    dists = torch.mm(xq, xb.t())
    return torch.topk(dists, k=k, dim=-1, sorted=True, largest=True)
```

**Comment by mdouze** [comment]
The dataset is very small so the cpu-gpu transfer becomes dominant. 
It can be considered a corner case in the Faiss use cases.
