### ISSUE TITLE
Question: meaning/effect of index.train

### ISSUE THREAD

**Issue by khieu** [facebookresearch/faiss#2150]
# Summary

THIS IS NOT AN ISSUE. 

I have a general question about FAISS search. When adding the vectors to FAISS index before performing knn search, why do we need to check `index.istrained` and then `train` the index with the vector spaces ? Would anyone be so kind to give a short explanation on the effect of this `train` step and what would happen if I don't `train` the index and just add the vectors directly?

thank you so much!

**Comment by mdouze** [comment]
https://github.com/facebookresearch/faiss/wiki/FAQ#can-i-used-an-index-trained-on-some-kind-of-data-to-index-some-other-type-of-data-of-the-same-dimension
