### ISSUE TITLE
how to read on-disk index from read-only file system?

### ISSUE THREAD

**Issue by simanw304** [facebookresearch/faiss#2153]
# Summary
I created an on-disk index and corresponding ivf data file following this [demo](https://github.com/facebookresearch/faiss/blob/151e3d7be54aec844b6328dc3e7dd0b83fcfa5bc/demos/demo_ondisk_ivf.py). 
The on-disk index and `merged_index.ivfdata` are saved to a persistent disk. The issue is if I mount the disk to a VM instance in ReadOnly mode, an error will be thrown when reading the index:
```
IO_FLAG_ONDISK_SAME_DIR: updating ondisk filename from merged_index.ivfdata to /mnt/merged_index.ivfdata
...
 RuntimeError: Error in void faiss::OnDiskInvertedLists::do_mmap() at OnDiskInvertedLists.cpp:278: Error: 'f' failed: could not open /mnt/merged_index.ivfdata in mode r+: Read-only file system 
```
If I mount the disk in ReadWrite mode it will work. I wonder whether there are any parameters that I can set to read on-disk index from read only file system. I found there is a flag `IO_FLAG_READ_ONLY` but I didn't see how or when to use it from documentation.

Here is how I read the index now:
```
index = faiss.read_index(local_index_path, faiss.IO_FLAG_ONDISK_SAME_DIR)
```

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
You can use IO_FLAG_READ_ONLY

so that's `io_flags = IO_FLAG_READ_ONLY | IO_FLAG_ONDISK_SAME_DIR`

https://github.com/facebookresearch/faiss/blob/main/faiss/invlists/OnDiskInvertedLists.cpp#L696
