### ISSUE TITLE
Eigen vs. Intel MKL benchmark for FAISS

### ISSUE THREAD

**Issue by anoubhav** [facebookresearch/faiss#2154]
Q1. Are there any speed benchmarks using the Eigen vs. Intel MKL BLAS implementation for FAISS? 
The installation page mentions that Intel MKL is faster than Open BLAS. But no information on Eigen is present. <br>
Q2. Does FAISS support Eigen?

https://github.com/facebookresearch/faiss/blob/main/INSTALL.md

**Comment by mdouze** [comment]
I am not familiar with eigen but from this doc it seems that it uses MKL as backend for dense matrix multiplication, so it does not make sense to add it as an intermediate library layer.

https://eigen.tuxfamily.org/dox/TopicUsingBlasLapack.html
