### ISSUE TITLE
Building IVFIndex via dataset.add_faiss_index on a server farm is very slow

### ISSUE THREAD

**Issue by philippmtk** [facebookresearch/faiss#2156]
# Summary

Hi,

I am observing a very long time for building the IVFIndex. 

In my setup, I use Huggingface's library and build the IVFIndex via dataset.add_faiss_index. With a small test set of 20k indices the process was finished within some minutes (on a development computer). But for our full size dataset with 32 Million indices, it is running already for 14 days on our training farm and no end is insight. I do not even see a progress bar (which I got after a couple of minutes with the small test set).

The code I am running is as follows:

```
d=512
m=128
nlist=262144

start = time.time()
quantizer = faiss.IndexFlatIP(d)
index = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_INNER_PRODUCT)
dataset_cc.add_faiss_index("index", custom_index=index, train_size=len(dataset_cc))
end = time.time()
print("elapsed time - add_faiss_index IndexIVFFlat: ", end-start)
```

The process takes 64 GB of RAM and has 32 CPU cores available. It runs on a server farm where storage and CPU are not within the same machine (maybe this is the issue?).

Maybe someone can provide me an intuition about how long building this index could take? I am wondering if I should just stop the process because something is going wrong but I am also worried of loosing 14 days. 

# Platform

OS: Ubuntu 16.04
Faiss version: 1.7.1.post2 (installed via pip install faiss-cpu)

Hardware: Intel Ice Lake(6334, 3.6Ghz) servers with 32 cores assigned to this job, 256 GB RAM

Installed from: pip install faiss-cpu

Running on:
- [ x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ x] Python

# Reproduction instructions

see above code snipplet

**Comment by mdouze** [comment]
`dataset_cc.add_faiss_index` is not part of Faiss. 
Here I suspect that training with nlist = 262144 may be the slow component. 
You could try to train it on GPU: https://gist.github.com/mdouze/46d6bbbaabca0b9778fca37ed2bcccf6
