### ISSUE TITLE
Bug on L2 distances for certain dimensions

### ISSUE THREAD

**Issue by jurrutiag** [facebookresearch/faiss#2158]
# Summary

Bug when calculating L2 distances with high dimensional vectors.

# Platform

OS: Ubuntu 20.04 

Faiss version: 1.7.1 

Installed from: anaconda from conda-forge  

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

Defining each vector to be each row, the following code finds the 10 nearest neighbors' distances for a matrix of shape (n_rows, n_cols) using numpy and using faiss. I'm printing the 10 nearest neighbors of the first vector using both methods. We should expect similar results but for certain values of rows and cols, the results differ by a lot.

If we set `n_rows = 129` and `n_cols = 256`, we will obtain similar results for both methods, but if we increase n_cols to 257 we now obtain only zeros on faiss' results. The following code reproduces the case where `n_rows = 129` and `n_cols = 257` (the failing case):

```
import faiss
import numpy as np

np.random.seed(0)

k = 10

n_rows = 129
n_cols = 257

X = np.random.random((n_rows, n_cols)).astype(np.float32)

# Numpy method
total = []
for i in range(X.shape[0]):
    total.append(np.sqrt(np.sum((X[i] - X[0])**2)))

numpy_kndistances = np.array(list(sorted(total)))[:k]

# faiss method
index = faiss.IndexFlatL2(X.shape[1])
index.add(X)
d, i = index.search(X, k=k)
faiss_kn_distances = np.sqrt(d)[0]

print("X shape:", X.shape)
print("Numpy K neighbors:", numpy_kndistances)
print("faiss K neighbors:", faiss_kn_distances)
```

The output of this code is:
```
X shape: (129, 257)
Numpy K neighbors: [0.        5.761359  5.896104  6.0360684 6.0725994 6.1008687 6.12219
 6.127646  6.1280384 6.1292977]
faiss K neighbors: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```

But if we set n_cols = 256, the output is:
```
X shape: (129, 256)
Numpy K neighbors: [0.        5.9614496 5.989949  5.9935446 6.0029216 6.0379467 6.0802736
 6.0919733 6.114578  6.121979 ]
faiss K neighbors: [0.00676582 5.9614496  5.9899464  5.9935446  6.0029216  6.037948
 6.0802746  6.0919757  6.1145797  6.1219807 ]
```

This also happens for other values. If we change n_rows to 128, then both results are similar except for values of n_cols greater than or equal to 1512

**Comment by mdouze** [comment]
Thanks for the clear report. 
With my install of 1.7.1, I get: 
```
X shape: (129, 257)
Numpy K neighbors: [0.        5.761359  5.896104  6.0360684 6.0725994 6.1008687 6.12219
 6.127646  6.1280384 6.1292977]
faiss K neighbors: [0.        5.761361  5.896105  6.036069  6.072601  6.100872  6.1221905
 6.127645  6.1280375 6.129301 ]
```
and 
```
X shape: (129, 256)
Numpy K neighbors: [0.        5.9614496 5.989949  5.9935446 6.0029216 6.0379467 6.0802736
 6.0919733 6.114578  6.121979 ]
faiss K neighbors: [0.00676582 5.9614496  5.9899464  5.9935446  6.0029216  6.037948
 6.0802746  6.0919757  6.1145797  6.1219807 ]
```
Ie. I can repro the second bug. Will investigate.

**Comment by jurrutiag** [comment]
I looked into why you weren't able to reproduce the bug, and it turns out that i was running this script on a code that had other imports, so i isolated which import was the cause. It turns out that importing torch caused the issue. I tried to reproduce it with an environment from scratch but i couldn't. I tried installing torch from conda and from pip using the same version i had on the other environment and i wasn't able to reproduce the bug. Anyways, reinstalling torch worked for me in this case.

**Comment by jurrutiag** [comment]
I got this error again and was able to reproduce it. I can't upload exactly the data i used when i obtained this error, but i managed to reproduce it in another way.

1. I created a new conda environment and ran only the command `conda install -c conda-forge faiss-gpu`
2. Executed the following code:

```
import faiss
import numpy as np

np.random.seed(100)

k = 10

X_scale = np.array([
    3.731249265115366e-08, 2.2128782362074162e-08, 8.896762437871075e-08, 7.551757619239652e-08,
    1.677437495573031e-07, 1.1830810109358936e-07, 3.252374369822064e-08, 2.5996088837132447e-08,
    1.3205714299857618e-10, 9.129308864430641e-08, 1.3762826434060571e-08, 3.0746907242473753e-09,
    -1.1010084222107253e-07, -157.97201538085938, -232.6477813720703, -116.49260711669922,
    -2.0235047340393066, -22.950162887573242, -0.19891536235809326, -3.1738903522491455,
    2.884276568693167e-07, 3.0142771834107407e-07, 2.655183095612301e-07, -8.927499850486242e-10,
    -4.1164170738738903e-08, -32218898.0, 1.5291972133013587e-09, 9.600875650050966e-10,
    1.3487060357419978e-08, 7.193984963294042e-09, 3.3702065138641046e-08, 3.337663201818941e-06,
    -5.307200900972475e-09, -1.892660428381987e-08, 2.203906834807867e-09, 7.884995767426517e-09,
    7.459298068113185e-09, 3.1831912661317574e-09, 3.000160830879395e-08, 2.9525473621561105e-08,
    8.291276998306785e-08, 7.960233716630682e-08, 3.68122456961828e-08, 2.0812265688618936e-08,
    2.2386185349887455e-08, 5.619478926632837e-08, 8.112319704878246e-09, -2.3591624209728934e-09,
    4.1642857695478597e-07, 4.737789538467041e-07, -0.0004482393560465425, -0.0010772745590656996,
    3.078926269495241e-08, 2.8931651741004316e-08, 7.96384392742766e-06, 6.427167591027683e-06,
    -1.2421403994267166e-07, -4.684763155182736e-08, 2.4390951480768308e-08, 1.4656347246955193e-08,
    7.282973513156321e-08, 8.547565499839038e-08, 5.710656481028309e-08, -4.273173908586614e-05,
    -3.4738437534542754e-05, 5.782274103971474e-10, 6.533799705721322e-07, 1.3006238077650778e-05,
    -4.1040213545784354e-05, 1.9739129584195325e-06, -3.322372867842205e-05, 4.340707619121531e-06,
    5.647382863571693e-07, 4.4088022121968606e-08, 9.278225832076714e-08, -3.640872492383096e-08,
    8.3686082064105e-08, 2.6704159949986206e-07, 2.8956984010619635e-07, 6.48830678073864e-07]).astype(np.float32)

n_rows = 2964
n_cols = 80

X = np.random.random((n_rows, n_cols)).astype(np.float32)
X = X * X_scale

# Numpy method
total = []
for i in range(X.shape[0]):
    total.append(np.sqrt(np.sum((X[i] - X[0])**2)))

numpy_kndistances = np.array(list(sorted(total)))[:k]

# faiss method
index = faiss.IndexFlatL2(X.shape[1])
index.add(X)
d, i = index.search(X, k=k)
faiss_kn_distances = np.sqrt(d)[0]

print("X shape:", X.shape)
print("Numpy K neighbors:", numpy_kndistances)
print("faiss K neighbors:", faiss_kn_distances)
```

My output was:

```
X shape: (2964, 80)
Numpy K neighbors: [    0.      2346.5315  3687.0442 22630.578  24064.19   24184.404
 25874.291  29114.121  32262.348  40498.266 ]
faiss K neighbors: [    0.        0.        0.    21673.994 23883.578 23883.578 25249.44
 28963.094 32251.936 40548.332]
```

**Comment by mdouze** [comment]
That last error is because the vector components have different magnitudes, see 

https://github.com/facebookresearch/faiss/wiki/FAQ#why-do-i-get-weird-results-with-brute-force-search-on-vectors-with-large-components

you have to be a little bit careful with the conditioning of the data.

**Comment by mdouze** [comment]
This is probably a roundoff error because the squared norm of X[0] is ~83 and 83 / 0.00676582 is around 1e5, the precision of float32.

> Thanks for the clear report. With my install of 1.7.1, I get:
> 
> ```
> X shape: (129, 257)
> Numpy K neighbors: [0.        5.761359  5.896104  6.0360684 6.0725994 6.1008687 6.12219
>  6.127646  6.1280384 6.1292977]
> faiss K neighbors: [0.        5.761361  5.896105  6.036069  6.072601  6.100872  6.1221905
>  6.127645  6.1280375 6.129301 ]
> ```
> 
> and
> 
> ```
> X shape: (129, 256)
> Numpy K neighbors: [0.        5.9614496 5.989949  5.9935446 6.0029216 6.0379467 6.0802736
>  6.0919733 6.114578  6.121979 ]
> faiss K neighbors: [0.00676582 5.9614496  5.9899464  5.9935446  6.0029216  6.037948
>  6.0802746  6.0919757  6.1145797  6.1219807 ]
> ```
> 
> Ie. I can repro the second bug. Will investigate.
