### ISSUE TITLE
Read index by c_api

### ISSUE THREAD

**Issue by nguyentrongnhat4869** [facebookresearch/faiss#2161]
# Summary

# Platform

OS: ubuntu 18.04

Faiss version: 

Installed from: build from source 

Faiss compilation options: c_api 

Running on:
- [x ] CPU
- [ ] GPU

Interface: 
- [x ] C++
- [ ] Python

i trained an index in python, now i want to read the index up using c_api. But I see the function that reads the index as int faiss_read_index(FILE* f, int io_flags, FaissIndex** p_out). What is the third parameter p_out, why is it a 2-way pointer FaissIndex**, while the function writes int faiss_write_index_fname(const FaissIndex* idx, const char* fname) then FaissIndex is a normal 1-way pointer. Is there an example that shows how to read the index using c_api. Thanks!

**Comment by Enet4** [comment]
That is the output by pointer pattern, which is also seen in other parts of the C API. You'd use that function like this:

```c
FaissIndex* index = NULL;
int err = faiss_read_index(f, io_flags, &index);
```

There is another example using the C API [here](https://github.com/facebookresearch/faiss/blob/main/c_api/example_c.c).

**Comment by nguyentrongnhat4869** [comment]
Thank you for your reply. I want to ask more how can I try set nprobe. I tried index.nprobe, but it gives me an error.

**Comment by Enet4** [comment]
Downcasting the index to a more specific implementation would give you access to parameter setter methods.

```c
FaissIndexIVFFlat* ivf_index = faiss_IndexIVFFlat_cast(index);
if (!ivf_index) {
   // illegal cast, handle accordingly
}

faiss_IndexIVFFlat_set_nprobe(ivf_index, 10);
```

I also think that using the parameter space API could work here.

```c
FaissParameterSpace* param_space = NULL;
faiss_ParameterSpace_new(&param_space);

int err = faiss_ParameterSpace_set_index_parameter(param_space, index, "nprobe", 10);
```
