### ISSUE TITLE
search_centroid on GpuIndexIVFPQ

### ISSUE THREAD

**Issue by cmacdonald** [facebookresearch/faiss#2173]
# Summary

I have a GPU index. I wish to perform `faiss.search_centroids()` on it, and benefit from GPU parallelism. How do to so (using Python)?

# Platform

Installed from: anaconda (conda-forge), also same thing on Colab.

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

The following code will work on a cpu index, or a GPU index if it has been converted to a CPU index (via `cpuindex = faiss.index_gpu_to_cpu(index)`).

```python
import numpy as np
I = np.empty(n, dtype=np.int64)
I[:] = -1
faiss.search_centroid(
    cpuindex,
    faiss.swig_ptr(query_embs),
    n,
    faiss.swig_ptr(I)
    )
```

However, applying it on a GPU index results in a segfault. I can provide a Colab notebook if necessary?

**Comment by wickedfoo** [comment]
The IVFLib functions such as search_centroid are unfortunately not implemented on the GPU, sorry.

**Comment by cmacdonald** [comment]
So, to be clear, the best option is to extract the trained centroids from the existing trained index and put them in a new GPU FAISS index?

**Comment by mdouze** [comment]
yes that should work.

**Comment by cmacdonald** [comment]
and that's what we did. Thanks.
