### ISSUE TITLE
Can I distribute searching probes between multiple threads/processes?

### ISSUE THREAD

**Issue by AbdallahHefny** [facebookresearch/faiss#2176]
# Summary

From [here](https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls), it appears that having more than one thread will not help in doing ONE query at a time. 
So is it possible to access the nprobes one-by-one and divide that amongst multiple threads to increase the speed of one query?

**Comment by mdouze** [comment]
If you provide the queries by batches, the searching is threaded internally by Faiss.
Otherwise you can also call search vector per vector with a thread pool. 
See 
https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls

**Comment by AbdallahHefny** [comment]
@mdouze  Thanks for the reply. Yes I will try that.

However, if I have an IVF index with nlist = 16 (i.e. 16 clusters). Is there a way to access and search individual clusters?

Thanks

**Comment by QwertyJack** [comment]
I believe the param `parallel_mode` could help: https://github.com/facebookresearch/faiss/blob/04d31fac53c609b6487a4cd6ead1c8b4ad926b0c/faiss/IndexIVF.h#L115
