### ISSUE TITLE
why SQ8 faster than float version ？

### ISSUE THREAD

**Issue by NJU-yasuo** [facebookresearch/faiss#2177]
I see in  faiss/impl/scale_quantizer.cpp , to compute distance between a float query and a uint_8  code, FAISS first decode the code and then compute distance with float query and float data. Compared with the float version, this equal to  decode + float computation, so why SQ8 index is fatser than float version?

**Comment by mdouze** [comment]
In practical use cases, SQ8 is usually faster because the limiting factor is memory access time rather than floating-point computations.
