### ISSUE TITLE
Enlarge the GPU memory reserved in StandardGpuResources (I need 5G instead of 1.5G)

### ISSUE THREAD

**Issue by namespace-Pt** [facebookresearch/faiss#2179]
# Summary

I used `faiss.index_cpu_to_gpu` to move a `IndexFlatIP` index of size `1101852 * 768` to gpu. My gpu is A100 with 40GB memory. I think the index should only consume `3.15GB` formatted in `float32`. But it gave me the following error:
```
Error in virtual void* faiss::gpu::StandardGpuResourcesImpl::allocMemory(const faiss::gpu::AllocRequest&) at /home/conda/feedstock_root/
build_artifacts/faiss-split_1636459980553/work/faiss/gpu/StandardGpuResources.cpp:452: Error: 'err == cudaSuccess' failed: StandardGpuResources: alloc
 fail type FlatData dev 2 space Device stream 0 size 2764800000 bytes (cudaMalloc error out of memory [2])
```

I found in the documentation that `StandardGpuResources` reserves a maximum 1536 MB on each GPU. However I want to enlarge this number by `res.setTempMemory(5*2**30)` but it didn't work as I checked `res.getTempMemoryAvailable(0)`. I wonder **How to reserve more memory on each GPU?**

# Platform

OS: 

Faiss version: 1.7.1+cuda11.1

Installed from: conda-forge 

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
This is not the problem because the GpuResources object is only for temporary memory. The index data memory will increase as needed. 
What call exactly produces the error above?

**Comment by namespace-Pt** [comment]
I will check my code.

**Comment by anoubhav** [comment]
@namespace-Pt were you able to resolve this? I am receiving a similar error while using GPU.

**Comment by namespace-Pt** [comment]
@anoubhav I double checked my code and found that I loaded too much vectors on one single gpu by mistake. So @mdouze is right, the gpu memory will increase as needed. 

I think you can check your code twice.
