### ISSUE TITLE
Install.MD Basic GPU example: error: ‘index_gpu_to_cpu’ is not a member of ‘faiss::gpu’

### ISSUE THREAD

**Issue by eusip** [facebookresearch/faiss#2184]
# Summary

I was able to build the [basic example](https://github.com/facebookresearch/faiss/blob/main/INSTALL.md#basic-example) but for the [GPU example](https://github.com/facebookresearch/faiss/blob/main/INSTALL.md#basic-gpu-example) I get the following error message.

`/home/ubuntu/faiss/faiss/gpu/test/demo_ivfpq_indexing_gpu.cpp:85:47: error: ‘index_gpu_to_cpu’ is not a member of ‘faiss::gpu’
   85 |         faiss::Index* cpu_index = faiss::gpu::index_gpu_to_cpu(&index);
`

# Platform

OS: Linux/5.11.0-1023-aws ubuntu/20.04.3
NVIDIA Driver Version: 495.29.05
CUDA Toolkit Version: 11.5 

Faiss version: 1.7.1

Installed from: Compiled from source
Faiss compilation options: -DFAISS_ENABLE_GPU=ON -DFAISS_ENABLE_PYTHON=ON -DBUILD_TESTING=ON -DBUILD_SHARED_LIBS=ON (Intel MKL BLAS by system default)

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

In root directory of repo:
```
$ make -C build demo_ivfpq_indexing_gpu
$ ./build/demos/demo_ivfpq_indexing_gpu
```

**Comment by HossamAmer12** [comment]
Any updates on this issue? I am facing the same error.

**Comment by mdouze** [comment]
should be fixed now.
