### ISSUE TITLE
IndexFlatL2 return different results

### ISSUE THREAD

**Issue by ZhiZhongWan** [facebookresearch/faiss#2186]
# Summary
IndexFlatL2 didn't return correct similar vector.

Windows 10

Faiss version: 1.7.1

Running on:
CPU

Interface: 
Python

# Reproduction instructions
```
import faiss
import json
import numpy as np
import tqdm
import pandas as pd
df = portrait
ids = df["user_id"].values.astype(np.int64)
ids_size = ids.shape[0]
datas = []
for x in df["features"]: 
    datas.append(x)
datas = np.array(datas).astype(np.float32)
print(datas.shape)#(592917, 128)
dimension = datas.shape[1]
index = faiss.IndexFlatL2(dimension)
index2 = faiss.IndexIDMap(index)
index2.add_with_ids(datas, ids)

user_embedding = np.array(df_user["features"].values.tolist()).astype('float32')
print(user_embedding.shape) #(14864, 128)
topk = 50
D, I = index2.search(user_embedding, topk)     
s=set()
for i in I:
    for j in i:
        s.add(j)
print(len(s))#the result is 359655

uid_list = df_user["user_id"].values.tolist()
s=set()
for i in tqdm.tqdm(range(len(uid_list))):
    user_embedding = np.array(df_user[df_user["user_id"] == uid_list[i]]["features"].iloc[0])#(1,128)
    user_embedding = np.expand_dims(user_embedding, axis=0).astype(np.float32)
    topk = 50
    D, I = index2.search(user_embedding, topk)
    for j in I[0]:
        s.add(j)
len(s)#the result is 399101
```

I have 2 embedding sets , the embedding set A contains around 15000\*128 vectors and the embedding set B contains nearly 600000\*128 vectors.  All vectors in A appears in B. 
I want to search top 50 similar vectors in set B, but I found some queries didn't return the query vectors themselves. I tried a for loop to  search top 50 similar vectors of a single 1\*128 vec in set A one by one and got a much larger result than using a 15000\*128  directly. Is some accelerating tech causes a lower accuracy?  I'm really confused about the results, which one should I trust?

**Comment by mdouze** [comment]
Please check if there are duplicate embeddings and see 
https://github.com/facebookresearch/faiss/wiki/FAQ#why-do-i-get-weird-results-with-brute-force-search-on-vectors-with-large-components
