### ISSUE TITLE
Segfault for some index factory strings in demo_ondisk_ivf.py

### ISSUE THREAD

**Issue by 8enmann** [facebookresearch/faiss#2188]
# Summary

I tried a few other index types other than `IVF4096,Flat` in https://github.com/facebookresearch/faiss/blob/main/demos/demo_ondisk_ivf.py
It didn't actually error until I called `index.search(...)`. I'd prefer if it failed early somewhere inside `merge_ondisk` with a descriptive error.

Works:
`OPQ16,IMI2x10,Flat` 
Didn't work:
`OPQ16,IMI2x10,PQ16+16`
`OPQ16,IVF4096,PQ16+16`

How can I predict which factory strings I'll get a segfault on?

# Platform

OS: Ubuntu 18.04.5 LTS

Faiss version: faiss-cpu 1.7.1.post3

Installed from: pip

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

Run demo with other index factory strings noted above.

**Comment by mdouze** [comment]
Should add an assertion here to guard against IVFPQR: 
https://github.com/facebookresearch/faiss/blob/main/contrib/ondisk.py#L17

**Comment by 8enmann** [comment]
mailed PR. Thanks for this library, it is awesome!!
