### ISSUE TITLE
[Question] does it support billion level vectors?

### ISSUE THREAD

**Issue by yiwc** [facebookresearch/faiss#2189]
Dear Faiss team,
thanks for your great work!
let's say each vector has 512 float32, and we have 1 billion vectors. What's the recommended solution using faiss? Thanks!

**Comment by mdouze** [comment]
see
https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index#if-100m---1b-ivf1048576_hnsw32
also
https://github.com/harsha-simhadri/big-ann-benchmarks/tree/main/track1_baseline_faiss
