### ISSUE TITLE
Problem with Clustering::train when nredo>1

### ISSUE THREAD

**Issue by Subenle** [facebookresearch/faiss#219]
In function [Clustering::train](https://github.com/facebookresearch/faiss/blob/master/Clustering.cpp#L121)
At the end of each redo`for (int redo = 0; redo < nredo; redo++)`

there is a judge whether the objective is improved
```
        if (nredo > 1) {
            if (err < best_err) {
                if (verbose)
                    printf ("Objective improved: keep new clusters\n");
                centroids = buf_centroids;
                best_err = err;
            }
            index.reset ();
        }
```

when `nredo > 1`, index.reset() will always be  executed, so the index will be empty instead of saving the centroids.

In my test case, when I set `index.cp.nredo=3;`, the quantizer will be empty after training and index will add nothing into it when execute `index.add(n,xb);`. Some of my output is listed as following:
```
after train: quantizer ntotal: 0, index ntotal: 0
IndexIVFFlat::add_core: added 0 / 100000 vectors


after add: quantizer ntotal: 0, index ntotal: 0
[3.373 s] start search,probe = 1
[3.382 s] end search,probe = 1
I=
query 9995:   -1    -1    -1    -1 
query 9996:   -1    -1    -1    -1 
query 9997:   -1    -1    -1    -1 
query 9998:   -1    -1    -1    -1 
query 9999:   -1    -1    -1    -1 
```

**Comment by mdouze** [comment]
Should be fixed in latest version.
