### ISSUE TITLE
Python example api error

### ISSUE THREAD

**Issue by caydyn-skd** [facebookresearch/faiss#22]
I encountered some problems while running the python example

CaydynMacbookPro:faiss caydyn$ python python/demo_auto_tune.py
load data
load GT
prepare criterion
Traceback (most recent call last):
  File "python/demo_auto_tune.py", line 73, in <module>
    crit.set_groundtruth(None, gt)
  File "/Users/caydyn/Development/faiss/python/swigfaiss.py", line 2053, in set_groundtruth
    def set_groundtruth(self, *args): return _swigfaiss.AutoTuneCriterion_set_groundtruth(self, *args)
TypeError: AutoTuneCriterion_set_groundtruth() takes exactly 4 arguments (3 given)

CaydynMacbookPro:faiss caydyn$ python ./python/demo_ivfpq.py 
loading database
Traceback (most recent call last):
  File "./python/demo_ivfpq.py", line 43, in <module>
    gt_index.add(xb)
  File "/Users/caydyn/Development/faiss/python/swigfaiss.py", line 1143, in add
    def add(self, *args): return _swigfaiss.IndexFlat_add(self, *args)
TypeError: IndexFlat_add() takes exactly 3 arguments (2 given)

How to deal with such mistakes?

**Comment by mdouze** [comment]
Hi 

This seems is related to the SWIG wrapper. Could you check which swig version you are using?

```
swig -version
```

then restore the machine-generated files from the ones provided in the repo, see 

https://github.com/facebookresearch/faiss/wiki/Troubleshooting#swig-error

**Comment by caydyn-skd** [comment]
Sorry i was wrong, i used the wrong file
