### ISSUE TITLE
[Question] Search a faiss::gpu::GpuIndexIVFPQ with a given list of coarse centroids

### ISSUE THREAD

**Issue by viniciussn** [facebookresearch/faiss#2201]
Hello,

Is it possible to search a faiss::gpu::GpuIndexIVFPQ with a given list of coarse centroids? That is, I already have the indexes of the inverted lists that each query needs to access. If it hasn't been implemented yet, can it be done relatively easily? If yes, can anyone guide a way to do this?

Thank you.

**Comment by mdouze** [comment]
This functionality is planned in the near future.

**Comment by viniciussn** [comment]
Thank you.

**Comment by anoubhav** [comment]
Is this functionality already available for faiss.IndexIVFFlat?

**Comment by mdouze** [comment]
Not yet.

**Comment by anoubhav** [comment]
Does the index.search_preassigned() achieve this to some extent? Or is it used for something else?
