### ISSUE TITLE
Poor results when reading saved index, however results fine when first trained.

### ISSUE THREAD

**Issue by ryanon4** [facebookresearch/faiss#2202]
# Summary

# Platform

OS: Windows 10 Pro Edition (All python configured in VirtualEnv)

Faiss version: 1.7.1.post2

Installed from: pip version:   21.3.1 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

I have encountered problems when performing evaluation of a saved index. For reproducibility, I do two evaluations, one straight after the index is trained and stored in memory, and once again in a separate program using the same evaluation data after loading the saved index. 
Results from the second experiment appear completely random

**Training:**
```
d = vectors[0].size

# initialize index
self.index = faiss.index_factory(d, "Flat", faiss.METRIC_INNER_PRODUCT)
faiss.normalize_L2(vectors)
self.index.add(vectors)
print("Training Complete")
write_index(self.index, str(filename))
for query in eval_data:
     faiss.normalize_L2(query)
     D, results = self.index.search(query, num_results)
```
**Evaluation**
```
self.index = read_index(str(filename))
for query in eval_data:
     faiss.normalize_L2(query)
     D, results = self.index.search(query, num_results)
```

The vectors in question are generated from the MP-NET transformer architecture.

**Comment by clarezei** [comment]
I have the same issue, I cannot reproduce the results, and using the same model the results I got are completely random.
