### ISSUE TITLE
Search queries are not thread safe

### ISSUE THREAD

**Issue by yutkin** [facebookresearch/faiss#2204]
[Wiki](https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls) says:

> Faiss CPU indices are thread-safe for concurrent searches, and other operations that do not change the index. A multithreaded use of functions that change the index needs to implement mutual exclusion.

But it is not always true. If we have two concurrent search queries with different `nprobes` we should use mutual exclusion because **nprobe is not a local argument of search function but it is a field of the index struct**. This fact leads to different problems in working with the index in a production environment. For example, except for the aforementioned mutexes for searches with different nprobes, we cannot write an index to a filesystem with simultaneous searches because de facto it is a data race, and search queries wait many seconds during snapshots creation.

It seems like these issues can be overcome if make `nprobe` the local argument of the search function but it can break the API.

What do you think about this? What is the cause of such a design decision to make `npobe` as a struct field?

**Comment by yutkin** [comment]
Thank you for your answer!
> put the index behind a single-threaded actor and perform searches with the same options in batches.
Yes, our index service already processes search queries as batches, but our business logic requires different "depth of search" for different types of content, so we are passing nprobe as an argument in our search queries and therefore should use locks inside (which conceptually not necessary for search algorithm).

**Comment by yutkin** [comment]
Thank you for your answer!

> put the index behind a single-threaded actor and perform searches with the same options in batches.

Yes, our index service already processes search queries as batches, but our business logic requires different "depth of search" for different types of content, so we are passing nprobe as an argument in our search queries and therefore should use locks inside (which conceptually not necessary for search algorithm).

**Comment by mdouze** [comment]
Right, nprobe (and max_codes and other search parameters like efSearch) are index parameters. 

For nprobe there is a lower level API to override the nprobe, see `IVFSearchParameters` and this test: 

https://github.com/facebookresearch/faiss/blob/151e3d7be54aec844b6328dc3e7dd0b83fcfa5bc/tests/test_params_override.cpp
