### ISSUE TITLE
Advice about C++ GPU Faiss and Index Choice

### ISSUE THREAD

**Issue by HossamAmer12** [facebookresearch/faiss#2207]
I am dealing with a huge vector dataset ( > 20M) for which I want to cluster to 100 centroids. Each vector consists of 1024 floating point features. Normally, I would like to retrieve the closest centroid for a given batch of 20 vectors on GPU. 

Guidance would be appreciated via these questions:

_1- Is there an example I can follow for using search GPU C++ faiss?_
_2- I would like to have search time for the given batch in the order of microseconds. Is that even possible? Are there tutorials to follow? What would be the index? Can IVF, HNSW index be used for this purpose?_

Would appreciate your advice on my questions :))

**Comment by HossamAmer12** [comment]
@mdouze

**Comment by mdouze** [comment]
First, you should subsample your dataset if you need just 100 centroids. 

Here is a GPU C++ example: 
https://github.com/facebookresearch/faiss/blob/main/faiss/gpu/perf/PerfClustering.cpp

**Comment by HossamAmer12** [comment]
Also, the compile command for this file?

**Comment by HossamAmer12** [comment]
_nvcc -o msd <>/PerfClustering.cpp -I <>/faiss/faiss/gpu/perf/ -lcublas_

**Output:**
/usr/bin/ld: /tmp/tmpxft_0000614f_00000000-5_PerfClustering.o: in function `main::{lambda(faiss::gpu::GpuResourcesProvider*, int)#1}::operator()(faiss::gpu::GpuResourcesProvider*, int) const':
PerfClustering.cpp:(.text+0xf3e): undefined reference to `faiss::gpu::StandardGpuResources::setPinnedMemory(unsigned long)'
/usr/bin/ld: PerfClustering.cpp:(.text+0xfa9): undefined reference to `faiss::gpu::GpuIndexFlatL2::GpuIndexFlatL2(faiss::gpu::GpuResourcesProvider*, int, faiss::gpu::GpuIndexFlatConfig)'
/usr/bin/ld: PerfClustering.cpp:(.text+0xfe5): undefined reference to `faiss::gpu::GpuIndexFlatIP::GpuIndexFlatIP(faiss::gpu::GpuResourcesProvider*, int, faiss::gpu::GpuIndexFlatConfig)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1021): undefined reference to `faiss::gpu::GpuIndex::setMinPagingSize(unsigned long)'
/usr/bin/ld: /tmp/tmpxft_0000614f_00000000-5_PerfClustering.o: in function `main':
PerfClustering.cpp:(.text+0x10eb): undefined reference to `google::ParseCommandLineFlags(int*, char***, bool)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x11ba): undefined reference to `faiss::float_rand(float*, unsigned long, long)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1337): undefined reference to `faiss::gpu::synchronizeAllDevices()'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1352): undefined reference to `faiss::ClusteringParameters::ClusteringParameters()'
/usr/bin/ld: PerfClustering.cpp:(.text+0x13a3): undefined reference to `faiss::Clustering::Clustering(int, int, faiss::ClusteringParameters const&)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x13b2): undefined reference to `faiss::gpu::CpuTimer::CpuTimer()'
/usr/bin/ld: PerfClustering.cpp:(.text+0x13f7): undefined reference to `faiss::Clustering::train(long, float const*, faiss::Index&, float const*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1406): undefined reference to `faiss::gpu::CpuTimer::elapsedMilliseconds()'
/usr/bin/ld: /tmp/tmpxft_0000614f_00000000-5_PerfClustering.o: in function `__static_initialization_and_destruction_0(int, int)':
PerfClustering.cpp:(.text+0x19c3): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x19f2): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1a21): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1a50): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1a7f): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1aae): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1add): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1b0c): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1b3b): undefined reference to `google::FlagRegisterer::FlagRegisterer<long>(char const*, char const*, char const*, long*, long*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1b6a): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1b99): undefined reference to `google::FlagRegisterer::FlagRegisterer<long>(char const*, char const*, char const*, long*, long*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1bc8): undefined reference to `google::FlagRegisterer::FlagRegisterer<long>(char const*, char const*, char const*, long*, long*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1bf7): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/usr/bin/ld: /tmp/tmpxft_0000614f_00000000-5_PerfClustering.o: in function `faiss::Clustering::~Clustering()':
PerfClustering.cpp:(.text._ZN5faiss10ClusteringD2Ev[_ZN5faiss10ClusteringD5Ev]+0x13): undefined reference to `vtable for faiss::Clustering'
/usr/bin/ld: /tmp/tmpxft_0000614f_00000000-5_PerfClustering.o: in function `faiss::gpu::IndexWrapper<faiss::gpu::GpuIndexFlat>::IndexWrapper(int, std::function<std::unique_ptr<faiss::gpu::GpuIndexFlat, std::default_delete<faiss::gpu::GpuIndexFlat> > (faiss::gpu::GpuResourcesProvider*, int)>)':
PerfClustering.cpp:(.text._ZN5faiss3gpu12IndexWrapperINS0_12GpuIndexFlatEEC2EiSt8functionIFSt10unique_ptrIS2_St14default_deleteIS2_EEPNS0_20GpuResourcesProviderEiEE[_ZN5faiss3gpu12IndexWrapperINS0_12GpuIndexFlatEEC5EiSt8functionIFSt10unique_ptrIS2_St14default_deleteIS2_EEPNS0_20GpuResourcesProviderEiEE]+0x54): undefined reference to `faiss::gpu::getNumDevices()'
/usr/bin/ld: PerfClustering.cpp:(.text._ZN5faiss3gpu12IndexWrapperINS0_12GpuIndexFlatEEC2EiSt8functionIFSt10unique_ptrIS2_St14default_deleteIS2_EEPNS0_20GpuResourcesProviderEiEE[_ZN5faiss3gpu12IndexWrapperINS0_12GpuIndexFlatEEC5EiSt8functionIFSt10unique_ptrIS2_St14default_deleteIS2_EEPNS0_20GpuResourcesProviderEiEE]+0xc5): undefined reference to `faiss::gpu::StandardGpuResources::StandardGpuResources()'
/usr/bin/ld: PerfClustering.cpp:(.text._ZN5faiss3gpu12IndexWrapperINS0_12GpuIndexFlatEEC2EiSt8functionIFSt10unique_ptrIS2_St14default_deleteIS2_EEPNS0_20GpuResourcesProviderEiEE[_ZN5faiss3gpu12IndexWrapperINS0_12GpuIndexFlatEEC5EiSt8functionIFSt10unique_ptrIS2_St14default_deleteIS2_EEPNS0_20GpuResourcesProviderEiEE]+0x174): undefined reference to `faiss::IndexReplicasTemplate<faiss::Index>::IndexReplicasTemplate(bool)'
/usr/bin/ld: /tmp/tmpxft_0000614f_00000000-5_PerfClustering.o: in function `faiss::ThreadedIndex<faiss::Index>::addIndex(faiss::Index*)':
PerfClustering.cpp:(.text._ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_[_ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_]+0x185): undefined reference to `faiss::FaissException::FaissException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)'
/usr/bin/ld: PerfClustering.cpp:(.text._ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_[_ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_]+0x193): undefined reference to `typeinfo for faiss::FaissException'
/usr/bin/ld: PerfClustering.cpp:(.text._ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_[_ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_]+0x2a9): undefined reference to `faiss::FaissException::FaissException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)'
/usr/bin/ld: PerfClustering.cpp:(.text._ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_[_ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_]+0x2b7): undefined reference to `typeinfo for faiss::FaissException'
/usr/bin/ld: PerfClustering.cpp:(.text._ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_[_ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_]+0x3ed): undefined reference to `faiss::FaissException::FaissException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)'
/usr/bin/ld: PerfClustering.cpp:(.text._ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_[_ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_]+0x3fb): undefined reference to `typeinfo for faiss::FaissException'
/usr/bin/ld: PerfClustering.cpp:(.text._ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_[_ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_]+0x447): undefined reference to `faiss::WorkerThread::WorkerThread()'
/usr/bin/ld: /tmp/tmpxft_0000614f_00000000-5_PerfClustering.o: in function `std::default_delete<faiss::WorkerThread>::operator()(faiss::WorkerThread*) const':
PerfClustering.cpp:(.text._ZNKSt14default_deleteIN5faiss12WorkerThreadEEclEPS1_[_ZNKSt14default_deleteIN5faiss12WorkerThreadEEclEPS1_]+0x22): undefined reference to `faiss::WorkerThread::~WorkerThread()'
/usr/bin/ld: /tmp/tmpxft_0000614f_00000000-5_PerfClustering.o: in function `faiss::FaissException::~FaissException()':
PerfClustering.cpp:(.text._ZN5faiss14FaissExceptionD2Ev[_ZN5faiss14FaissExceptionD5Ev]+0x13): undefined reference to `vtable for faiss::FaissException'
collect2: error: ld returned 1 exit status
hossamamer@4175afbd627502fed411b1c766f55108-master-0:~/young/cpp_faiss/2-faiss/faiss$ nvcc /home/hossamamer/young/cpp_faiss/2-faiss/faiss/faiss/gpu/perf/PerfClustering.cpp -lcublas -o myCublasApp
/usr/bin/ld: /tmp/tmpxft_000061d5_00000000-5_PerfClustering.o: in function `main::{lambda(faiss::gpu::GpuResourcesProvider*, int)#1}::operator()(faiss::gpu::GpuResourcesProvider*, int) const':
PerfClustering.cpp:(.text+0xf3e): undefined reference to `faiss::gpu::StandardGpuResources::setPinnedMemory(unsigned long)'
/usr/bin/ld: PerfClustering.cpp:(.text+0xfa9): undefined reference to `faiss::gpu::GpuIndexFlatL2::GpuIndexFlatL2(faiss::gpu::GpuResourcesProvider*, int, faiss::gpu::GpuIndexFlatConfig)'
/usr/bin/ld: PerfClustering.cpp:(.text+0xfe5): undefined reference to `faiss::gpu::GpuIndexFlatIP::GpuIndexFlatIP(faiss::gpu::GpuResourcesProvider*, int, faiss::gpu::GpuIndexFlatConfig)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1021): undefined reference to `faiss::gpu::GpuIndex::setMinPagingSize(unsigned long)'
/usr/bin/ld: /tmp/tmpxft_000061d5_00000000-5_PerfClustering.o: in function `main':
PerfClustering.cpp:(.text+0x10eb): undefined reference to `google::ParseCommandLineFlags(int*, char***, bool)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x11ba): undefined reference to `faiss::float_rand(float*, unsigned long, long)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1337): undefined reference to `faiss::gpu::synchronizeAllDevices()'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1352): undefined reference to `faiss::ClusteringParameters::ClusteringParameters()'
/usr/bin/ld: PerfClustering.cpp:(.text+0x13a3): undefined reference to `faiss::Clustering::Clustering(int, int, faiss::ClusteringParameters const&)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x13b2): undefined reference to `faiss::gpu::CpuTimer::CpuTimer()'
/usr/bin/ld: PerfClustering.cpp:(.text+0x13f7): undefined reference to `faiss::Clustering::train(long, float const*, faiss::Index&, float const*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1406): undefined reference to `faiss::gpu::CpuTimer::elapsedMilliseconds()'
/usr/bin/ld: /tmp/tmpxft_000061d5_00000000-5_PerfClustering.o: in function `__static_initialization_and_destruction_0(int, int)':
PerfClustering.cpp:(.text+0x19c3): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x19f2): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1a21): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1a50): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1a7f): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1aae): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1add): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1b0c): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1b3b): undefined reference to `google::FlagRegisterer::FlagRegisterer<long>(char const*, char const*, char const*, long*, long*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1b6a): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1b99): undefined reference to `google::FlagRegisterer::FlagRegisterer<long>(char const*, char const*, char const*, long*, long*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1bc8): undefined reference to `google::FlagRegisterer::FlagRegisterer<long>(char const*, char const*, char const*, long*, long*)'
/usr/bin/ld: PerfClustering.cpp:(.text+0x1bf7): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/usr/bin/ld: /tmp/tmpxft_000061d5_00000000-5_PerfClustering.o: in function `faiss::Clustering::~Clustering()':
PerfClustering.cpp:(.text._ZN5faiss10ClusteringD2Ev[_ZN5faiss10ClusteringD5Ev]+0x13): undefined reference to `vtable for faiss::Clustering'
/usr/bin/ld: /tmp/tmpxft_000061d5_00000000-5_PerfClustering.o: in function `faiss::gpu::IndexWrapper<faiss::gpu::GpuIndexFlat>::IndexWrapper(int, std::function<std::unique_ptr<faiss::gpu::GpuIndexFlat, std::default_delete<faiss::gpu::GpuIndexFlat> > (faiss::gpu::GpuResourcesProvider*, int)>)':
PerfClustering.cpp:(.text._ZN5faiss3gpu12IndexWrapperINS0_12GpuIndexFlatEEC2EiSt8functionIFSt10unique_ptrIS2_St14default_deleteIS2_EEPNS0_20GpuResourcesProviderEiEE[_ZN5faiss3gpu12IndexWrapperINS0_12GpuIndexFlatEEC5EiSt8functionIFSt10unique_ptrIS2_St14default_deleteIS2_EEPNS0_20GpuResourcesProviderEiEE]+0x54): undefined reference to `faiss::gpu::getNumDevices()'
/usr/bin/ld: PerfClustering.cpp:(.text._ZN5faiss3gpu12IndexWrapperINS0_12GpuIndexFlatEEC2EiSt8functionIFSt10unique_ptrIS2_St14default_deleteIS2_EEPNS0_20GpuResourcesProviderEiEE[_ZN5faiss3gpu12IndexWrapperINS0_12GpuIndexFlatEEC5EiSt8functionIFSt10unique_ptrIS2_St14default_deleteIS2_EEPNS0_20GpuResourcesProviderEiEE]+0xc5): undefined reference to `faiss::gpu::StandardGpuResources::StandardGpuResources()'
/usr/bin/ld: PerfClustering.cpp:(.text._ZN5faiss3gpu12IndexWrapperINS0_12GpuIndexFlatEEC2EiSt8functionIFSt10unique_ptrIS2_St14default_deleteIS2_EEPNS0_20GpuResourcesProviderEiEE[_ZN5faiss3gpu12IndexWrapperINS0_12GpuIndexFlatEEC5EiSt8functionIFSt10unique_ptrIS2_St14default_deleteIS2_EEPNS0_20GpuResourcesProviderEiEE]+0x174): undefined reference to `faiss::IndexReplicasTemplate<faiss::Index>::IndexReplicasTemplate(bool)'
/usr/bin/ld: /tmp/tmpxft_000061d5_00000000-5_PerfClustering.o: in function `faiss::ThreadedIndex<faiss::Index>::addIndex(faiss::Index*)':
PerfClustering.cpp:(.text._ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_[_ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_]+0x185): undefined reference to `faiss::FaissException::FaissException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)'
/usr/bin/ld: PerfClustering.cpp:(.text._ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_[_ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_]+0x193): undefined reference to `typeinfo for faiss::FaissException'
/usr/bin/ld: PerfClustering.cpp:(.text._ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_[_ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_]+0x2a9): undefined reference to `faiss::FaissException::FaissException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)'
/usr/bin/ld: PerfClustering.cpp:(.text._ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_[_ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_]+0x2b7): undefined reference to `typeinfo for faiss::FaissException'
/usr/bin/ld: PerfClustering.cpp:(.text._ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_[_ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_]+0x3ed): undefined reference to `faiss::FaissException::FaissException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)'
/usr/bin/ld: PerfClustering.cpp:(.text._ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_[_ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_]+0x3fb): undefined reference to `typeinfo for faiss::FaissException'
/usr/bin/ld: PerfClustering.cpp:(.text._ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_[_ZN5faiss13ThreadedIndexINS_5IndexEE8addIndexEPS1_]+0x447): undefined reference to `faiss::WorkerThread::WorkerThread()'
/usr/bin/ld: /tmp/tmpxft_000061d5_00000000-5_PerfClustering.o: in function `std::default_delete<faiss::WorkerThread>::operator()(faiss::WorkerThread*) const':
PerfClustering.cpp:(.text._ZNKSt14default_deleteIN5faiss12WorkerThreadEEclEPS1_[_ZNKSt14default_deleteIN5faiss12WorkerThreadEEclEPS1_]+0x22): undefined reference to `faiss::WorkerThread::~WorkerThread()'
/usr/bin/ld: /tmp/tmpxft_000061d5_00000000-5_PerfClustering.o: in function `faiss::FaissException::~FaissException()':
PerfClustering.cpp:(.text._ZN5faiss14FaissExceptionD2Ev[_ZN5faiss14FaissExceptionD5Ev]+0x13): undefined reference to `vtable for faiss::FaissException'
collect2: error: ld returned 1 exit status
