### ISSUE TITLE
Faiss on M1 has to be configed as DCMAKE_BUILD_TYPE=Release

### ISSUE THREAD

**Issue by windsorwho** [facebookresearch/faiss#2210]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:   compiled my self.

Faiss compilation options:  no MKL, using libblas and liblapack

Running on:
- [ x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x ] Python

# Reproduction instructions

Just follow the standard steps for compilling from the source on the INSTALL.md
I am compiling on my M1 chip Mac in a Ubuntu20.04 based image, so I choose to config the project as:

cmake -B build . -DBUILD_TESTING=ON -DBUILD_SHARED_LIBS=ON -DFAISS_ENABLE_GPU=OFF -DFAISS_ENABLE_PYTHON=ON

After typing 
make -C build install

The compilation proceeds till the linking error  msg:

[100%] Linking CXX executable faiss_test
/usr/bin/ld: ../faiss/libfaiss.so: undefined reference to `vaddq_u16(__Uint16x8_t, __Uint16x8_t)'
/usr/bin/ld: ../faiss/libfaiss.so: undefined reference to `vdupq_n_u16(unsigned short)'
/usr/bin/ld: ../faiss/libfaiss.so: undefined reference to `vandq_u8(__Uint8x16_t, __Uint8x16_t)'
/usr/bin/ld: ../faiss/libfaiss.so: undefined reference to `vcleq_u16(__Uint16x8_t, __Uint16x8_t)'
/usr/bin/ld: ../faiss/libfaiss.so: undefined reference to `vminq_u16(__Uint16x8_t, __Uint16x8_t)'
/usr/bin/ld: ../faiss/libfaiss.so: undefined reference to `vaddq_f32(__Float32x4_t, __Float32x4_t)'
/usr/bin/ld: ../faiss/libfaiss.so: undefined reference to `vsubq_u16(__Uint16x8_t, __Uint16x8_t)'
/usr/bin/ld: ../faiss/libfaiss.so: undefined reference to `vmaxq_u16(__Uint16x8_t, __Uint16x8_t)'
/usr/bin/ld: ../faiss/libfaiss.so: undefined reference to `vpaddq_f32(__Float32x4_t, __Float32x4_t)'
/usr/bin/ld: ../faiss/libfaiss.so: undefined reference to `vcgeq_u16(__Uint16x8_t, __Uint16x8_t)'
/usr/bin/ld: ../faiss/libfaiss.so: undefined reference to `vsubq_f32(__Float32x4_t, __Float32x4_t)'
/usr/bin/ld: ../faiss/libfaiss.so: undefined reference to `vqtbl1q_u8(__Uint8x16_t, __Uint8x16_t)'
/usr/bin/ld: ../faiss/libfaiss.so: undefined reference to `vmulq_f32(__Float32x4_t, __Float32x4_t)'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/faiss_test.dir/build.make:318: tests/faiss_test] Error 1
make[2]: Leaving directory '/faiss/build'
make[1]: *** [CMakeFiles/Makefile2:1527: tests/CMakeFiles/faiss_test.dir/all] Error 2
make[1]: Leaving directory '/faiss/build'
make: *** [Makefile:160: all] Error 2
make: Leaving directory '/faiss/build'

 

Then I tried to config the project with an extra flag DCMAKE_BUILD_TYPE=Release and seems everything is fine and faiss test passes.

**Comment by mdouze** [comment]
see #2195

**Comment by windsorwho** [comment]
So it is working as intended while cmake with default arguments would not build the libraries?
