### ISSUE TITLE
Training time benchmarks?

### ISSUE THREAD

**Issue by mataney** [facebookresearch/faiss#2211]
Hi, thanks for the really great job!
Wondering if you can share benchmarks of the time it took to train different models*?
That will be very helpful, thank you.

*Longer training time should not be a major consideration when choosing an index algorithm, but it is still worth knowing what to expect when training a model and comparing it to other repositories.

**Comment by mdouze** [comment]
We are logging that info for the different bechmarks, see eg. the times in the plots of 

https://github.com/facebookresearch/faiss/wiki/Indexing-1G-vectors

**Comment by mataney** [comment]
Hi @mdouze, thanks for your reply!

Interesting, I see quite a bit of difference from what I'm experiencing and I'd love your input on what I'm missing.

I have a dataset of ~110M vectors of size 786, and I'm training the following a `PCA256,IVF65536_HNSW32,Flat` index, with `len(training) = 40.8M`.
It's already training for ~48h on a 96 cpus machine (no GPU)
In [here](https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index) you wrote it should take very long, but when looking at the times in the plot you linked here, it looks like it should be fairly quick (indices are not exactly like what I choose).

What seem to be the reason for the very long training times?
Thanks again!

**Comment by mataney** [comment]
Training on GPUs made all the difference (used to take a few days. With GPUs only a few hours).
Closing.
