### ISSUE TITLE
Is there a way to get top 8k vectors in gpu IVFFlat index?

### ISSUE THREAD

**Issue by BXDimmortal** [facebookresearch/faiss#2216]
I am dealing with a huge vector dataset ( ~ 10M) for which I want to get top 8k vectors. Each vector consists of 64 floating point features. I am working on IvfFFlat index, and to accelerate I use gpu to compute.

But i notice that only at most top 2048 vectors is supported,  is there any way to get top 8k vectors?

Would appreciate your advice on my questions :)

**Comment by mdouze** [comment]
This is not supported on GPU. Possible solutions: 

- work on CPU, possibly with a speed and/or accuracy degradation.

- split the 10M vectors in 8 indexes of 1.25M vectors, query 2048 neighbors from each, merge results and keep the 8k smallest. If the vectors are in a random order it is almost impossible that more than 2048 out of the 8k vectors are in a single shard (proof left to the reader).
