### ISSUE TITLE
Most efficient way to do a kNN search on an array using points from another array?

### ISSUE THREAD

**Issue by pastore97** [facebookresearch/faiss#2221]
I am using faiss for a problem and I have a question on how I could speed it up.
I have two arrays, one big and the other smaller, each consisting of independent measurements. I would like to do a kNN search on the larger array using points from the smaller one. The issue for me is how to do this most efficiently, given that each row in these arrays consists of independent measurements.

An example using toy data:
```python
# 1000 independent measurements of 100 data points each.
m, d, s = 1000, 100, 10
t = np.random.random(m * d * 3).reshape(m, d, 3).astype('float32')
q = np.random.random(m * s * 3).reshape(m, s, 3).astype('float32')

# objective: find nearest neighbors for s:
res = faiss.StandardGpuResources()
if_flat = faiss.index_factory(3, 'Flat')  # always 3 dim 
co = faiss.GpuClonerOptions()
co.useFloat16 = True

for mi in range(m):
    index = faiss.index_cpu_to_gpu(res, 1, if_flat, co)
    xb, xq = t[mi, :], q[mi, :]
    index.train(xb)
    index.add(xb)
    index.search(xq, 20)
```
Is there a way I can avoid looping over the measurements? Or better yet, generate an index that treats all m measurements independently, i.e. confine searches for each q[mi, :] array to only the corresponding t[mi, :]?

**Comment by mdouze** [comment]
Faiss is not well optimized for low-dimensional data (like dim=3)
What I don't get is which dimension of the problem gets large, is it m ? because in your example no dimension is large enough to even bother using a GPU.

**Comment by pastore97** [comment]
@mdouze Thank you so much for your response!

I have done benchmarks and confirmed that there are significant performance gains to using GPUs (even using the code block in the toy example I presented). Using the toy data above, the dimension that increases is `d`. Its size can be well above 10^7. And we would like to explicitly support this and allow for even larger values (10^8 or more).

Despite the clear performance gains that we get, I suspect it should be possible to achieve further optimization. Perhaps by being smarter in how we generate the index? Initially, I thought we could use dynamic indexing (which would be extremely helpful since our measurements are independent, but still highly correlated), but reading through other issues here, I understand that that seems to be, understandably, not supported by `faiss`. But there may be other ways to speed things up, perhaps?
Our current code may also not be the most optimal for the current problem (e.g. after setting `d=10**6`).
