### ISSUE TITLE
KNN Imputer

### ISSUE THREAD

**Issue by jpetot** [facebookresearch/faiss#2222]
# Summary

Is there a way to adapt FAISS as a KNN imputation function? if so, how?

## Context 

I am using Faiss algorithm as a knn as describe in this [post](https://towardsdatascience.com/make-knn-300-times-faster-than-scikit-learns-in-20-lines-5e29d74e76bb). 

KNN algorithms can also be used as an imputer. It is done in scikit learn [here](https://scikit-learn.org/stable/modules/generated/sklearn.impute.KNNImputer.html).
But it itakes lot of time to compute. 

So I am interesting to know if there is a way to use Faiss to impute missing values.

**Comment by mdouze** [comment]
I don't understand the question.

**Comment by jpetot** [comment]
Sorry, I put some context to clarify my question. Thanks

**Comment by mdouze** [comment]
No this is not supported.
