### ISSUE TITLE
Cannot install faiss-gpu

### ISSUE THREAD

**Issue by bluster1000** [facebookresearch/faiss#2223]
# Summary
I tried to install faiss-gpu on my system (Jetson Xavier).
But I can not install.

`conda install faiss-gpu cudatoolkit=10.0 -c pytorch`

result  :
```
PackageNotFoundError: The following packages are not available from current channels:
 - faiss-gpu
 - cudatoolkit=10.0
```

# Platform

Jetson Xavier (arm architecture)

OS: ubuntu 20.04

Faiss version: maybe 1.7.2

Installed from: miniconda 

Faiss compilation options: 

Running on:

- [ ] CPU
- [v] GPU

Interface: 
- [ ] C++
- [v] Python

# Reproduction instructions

`conda install faiss-gpu cudatoolkit=10.0 -c pytorch`

result  :
```
PackageNotFoundError: The following packages are not available from current channels:
 - faiss-gpu
 - cudatoolkit=10.0
```

**Comment by mdouze** [comment]
I think only cuda 10.2 and 11.3 are supported.

**Comment by rpsikka** [comment]
were you able to solve this issue?
