### ISSUE TITLE
FAISS C API does not support Binary Indices

### ISSUE THREAD

**Issue by CarterMcClellan** [facebookresearch/faiss#2225]
# Summary
Currently, I am using the `c_api` and noticed there is no support for Binary Index io. 

Is there a reason for this?

**Comment by CarterMcClellan** [comment]
Also, this seems like a simple enough issue, I was wondering if I could contribute.

**Comment by Enet4** [comment]
> Is there a reason for this?

It did not exist back when the C API was made, and it just hasn't been ported yet. But yet, it would be nice to have.

**Comment by Enet4** [comment]
I think this can be closed. The Binary Index C API was added in #2233.
