### ISSUE TITLE
Conflict in IndexIVFFlat, remove_ids & reconstruct

### ISSUE THREAD

**Issue by Subenle** [facebookresearch/faiss#223]
In function [IndexIVFFlat::reconstruct](https://github.com/facebookresearch/faiss/blob/master/IndexIVF.cpp#L610), it requires `direct_map.size() == ntotal`, that means `maintain_direct_map` should be true. 

In function [IndexIVF::remove_ids](https://github.com/facebookresearch/faiss/blob/master/IndexIVF.cpp#L121), it requires `maintain_direct_map=true`.

So, I cannot call remove_ids() if I want to call reconstruct()?

I want to retrain index, so first i call reconstruct_n() to get all the vectors in the index. Now, it seems this is impossible if I also want the fuction remove_ids().

**Comment by mdouze** [comment]
Hi 
Sorry, reconstruct is not supported in computation with remove_ids.
It would be an enhancement to implement it, but it is low-priority for us.

**Comment by krishperumal** [comment]
Any work in progress on this?

**Comment by mdouze** [comment]
Supported in 1.6.3, see 
https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes#reconstruct-some-vectors
