### ISSUE TITLE
Update the overview figure

### ISSUE THREAD

**Issue by matsui528** [facebookresearch/faiss#2230]
# Summary

I have updated the overview figure because AQ and 4-bit PQ have been implemented. Let me know if there're papers that should appear in this figure :)

![teaser2_main_202220225](https://user-images.githubusercontent.com/2842345/155660185-5f33d9cd-1f9c-4d95-8be1-8e25d4a74016.png)

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [x] C++
- [x] Python

# Reproduction instructions
None

**Comment by mdouze** [comment]
That looks very good! Thanks!
Maybe you could add the paper 

The residual quantizer implementation from ["Improved Residual Vector Quantization for High-dimensional Approximate Nearest Neighbor Search"](https://arxiv.org/abs/1509.05195), Shicong Liu et al, AAAI'15.

which is currently the best additive quantization option for Faiss. I could be added after the Martinez' papers.

**Comment by matsui528** [comment]
![teaser2_main_20220301](https://user-images.githubusercontent.com/2842345/156081600-cce627f8-4fe2-45f0-938a-3d637aabf6dd.png)

Here it is :)  Please also update the reference list:
```
...
Ozan+, “Competitive Quantization for Approximate Nearest Neighbor Search”, IEEE TKDE 16
Shicong+, “Improved Residual Vector Quantization for High-dimensional Approximate Nearest Neighbor Search”, AAAI 15
Spyromitros-Xious+, “A Comprehensive Study over VLAD and Product Quantization in Large-scale Image Retrieval”, IEEE TMM 14
...
```

**Comment by mdouze** [comment]
Updated, thanks!
