### ISSUE TITLE
CUDA error 35 - pytorch, docker, rocm 5.0.1

### ISSUE THREAD

**Issue by MagicFeeling** [facebookresearch/faiss#2235]
# Summary
I am trying to setup Faiss with the newest rocm-5.0.1 inside the docker image from here [rocm/pytorch
](https://hub.docker.com/r/rocm/pytorch)

# Platform
System: Ubuntu 20.04.4 LTS
Docker: Ubuntu 18.04.6 LTS

Faiss version: faiss 1.7.2 py37cuda102haa52d2d_0_cuda    conda-forge
GPU: gfx1030 AMD Radeon RX 6900 XT

Installed from: conda install -c conda-forge faiss-gpu

# Reproduction instructions
- import numpy as np
- import faiss
- res = faiss.StandardGpuResources()
- index_flat = faiss.IndexFlatL2(2)
- gpu_index_flat = faiss.index_cpu_to_gpu(res, 0, index_flat)
**Error Message**
Faiss assertion 'err__ == cudaSuccess' failed in int faiss::gpu::getNumDevices() at /home/conda/feedstock_root/build_artifacts/faiss-split_1644327786058/work/faiss/gpu/utils/DeviceUtils.cu:36; details: CUDA error 35 CUDA driver version is insufficient for CUDA runtime version
Aborted (core dumped)

The error messages seems quite clear that I need to update my GPU drivers, but I already have the latest version installed.

**Within docker when opening a python console:**
```
torch.cuda.is_available() -> True
print(torch.version.cuda) -> None
torch.cuda.device_count() -> 1
```
**On System**
```
sudo /opt/rocm-5.0.1/bin/rocminfo
ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE 
```

Hope someone could give a hint where my mistake is.

**Comment by mdouze** [comment]
Only NVIDIA GPUs are supported, sorry. 
I am surprised that torch returns a device count > 0.
