### ISSUE TITLE
Meaning of -DFAISS_USE_FLOAT16

### ISSUE THREAD

**Issue by Gold-Sea** [facebookresearch/faiss#2236]
# Summary

I wonder -DFAISS_USE_FLOAT16 in makefile.inc(afer ./configure) means. Does it means faiss only adopts float16 in seach process?

Faiss version:1.15.2

Running on:
- [*] CPU
- [ ] GPU

Interface: 
- [*] C++
- [ ] Python

# Reproduction instructions

**Comment by Gold-Sea** [comment]
> I am asking a similar question here: #2234

I figure out this question. Faiss uses float16 in GPU Index. Thanks for replying!

**Comment by HossamAmer12** [comment]
Can you please explain a bit more? Do you mean the input to the index could be float16?

Your answer/insight about my issue would be greatly appreciated
