### ISSUE TITLE
Windows not building with faiss::OnDiskInvertedLists::OnDiskInvertedLists

### ISSUE THREAD

**Issue by robmang** [facebookresearch/faiss#2239]
# Summary

# Platform
Windows 64 bit

OS: 

Faiss version: 
1.7.1_2021_05_27

Installed from:  
compiled myself

Faiss compilation options: 

cmake -DBUILD_TESTING=OFF -DFAISS_ENABLE_PYTHON=OFF -DBUILD_SHARED_LIBS=ON -DFAISS_ENABLE_GPU=ON -DCMAKE_BUILD_TYPE=Release -DBLA_VENDOR=Intel10_64lp_seq -DMKL_LIBRARIES="C:\Program Files (x86)\Intel\oneAPI\mkl\2022.0.0\lib\intel64\mkl_sequential.lib;C:\Program Files (x86)\Intel\oneAPI\mkl\2022.0.0\lib\intel64\mkl_rt.lib" -DCMAKE_CUDA_ARCHITECTURES="60;61;62;70;72;75;80;86" CUDAToolkit_ROOT=C:\Program Files\NVIDIA GPU Computing Toolkit\11.4\v11.4 -B build . 

Running on:
- [X ] CPU
- [ ] GPU

Interface: 
- [ X] C++
- [ ] Python

# Reproduction instructions

Linking error:
 
 error LNK2019: unresolved external symbol "public: __cdecl faiss::OnDiskInvertedLists::OnDiskInvertedLists(unsigned __int64,unsigned __int64,char const *)" (??0OnDiskInvertedLists@faiss@@QEAA@_K0PEBD@Z) referenced in function "int __cdecl CatMain(int,char * *)" (?CatMain@@YAHHPEAPEAD@Z)
main.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl faiss::OnDiskInvertedLists::~OnDiskInvertedLists(void)" (??1OnDiskInvertedLists@faiss@@UEAA@XZ) referenced in function "int __cdecl CatMain(int,char * *)" (?CatMain@@YAHHPEAPEAD@Z)

For a very simple program calling OnDiskinvertedLists:

int main(int argc, char** argv)
{
	auto invlists = faiss::OnDiskInvertedLists(100, 256, "whatever");

	DebugF(INFO, "%p, %d", &invlists, invlists.totsize);
	return 0;
}

I am able to compile and run faiss successfully on Ubuntu20, including doing on disk searches (using OnDiskInvertedLists in the process).

I can't find the external symbol in faiss.dll. I'm not sure what I'm missing to build with OnDiskInvertedLists on windows.

Here is the cmake output:

-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The CXX compiler identification is MSVC 19.26.28805.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The CUDA compiler identification is NVIDIA 11.4.48
-- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4/bin/nvcc.exe
-- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4/bin/nvcc.exe - works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - not found
-- Found Threads: TRUE
-- Found MKL: C:\Program Files (x86)\Intel\oneAPI\mkl\2022.0.0\lib\intel64\mkl_sequential.lib;C:\Program Files (x86)\Intel\oneAPI\mkl\2022.0.0\lib\intel64\mkl_rt.lib
-- Found CUDAToolkit: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4/include (found version "11.4.48")
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_BUILD_TYPE
    CMAKE_CUDA_ARCHITECTURES

-- Build files have been written to: S:/faiss-main/build

**Comment by mdouze** [comment]
`OnDiskInvertedLists` is not supported on windows.

**Comment by robmang** [comment]
Thanks for the reply. Are there any plans to support it in the future?

Before I forget thanks for the great library :)

**Comment by mdouze** [comment]
The problem is that mmap mechanism does not seem to be available on Windows. 
There is a file mapping API 
https://docs.microsoft.com/en-us/windows/win32/memory/file-mapping
Not sure this is equivalent.
