### ISSUE TITLE
There will exist Repeated ids in indexIVFFlat when add ids after remove_ids.

### ISSUE THREAD

**Issue by Subenle** [facebookresearch/faiss#224]
When remove some ids, other ids will not be changed, but ntotal is reduced.

When add new n vectors, their id is set to ntotal, ntotal+1,...,ntotal+n respectly.

Assuming there ntotal = 100 now, their id is 0, 1, 2, ... , 99.

After removing first 5 ids, remained ids are 5, 6, ... , 99. ntotal = 95 .

now, if we add new 5 vectors, their id will be set to 95, 96, 97, 98, 99. ntotal = 100.   
There will exist id 95-99 twice.

If I want to remove id 95, which one will be removed?

**Comment by wickedfoo** [comment]
You would need to use the add_with_ids function instead to provide the ID for the data.

@mdouze Maybe we should add ID management to the IndexFlat* so we can just remove outright the ID-less functions? This would make the IndexFlat/GpuIndexFlat slightly slower, but not having user-managed IDs for everything causes issues with sharding and other cases as well.

**Comment by mdouze** [comment]
Please use an IDMap 

https://github.com/facebookresearch/faiss/wiki/Pre--and-post-processing#faiss-id-mapping
