### ISSUE TITLE
Error: 'std::isfinite(x[i])' failed: input contains NaN's or Inf's"

### ISSUE THREAD

**Issue by siyuanWang** [facebookresearch/faiss#2240]
# Summary
faiss version is v1.7.1
Training level-1 quantizer
Training level-1 quantizer on 32000 vectors in 32D
unknown file: Failure
C++ exception with description "Error in void faiss::Clustering::train_encoded(faiss::Clustering::idx_t, const uint8_t*, const faiss::Index*, faiss::Index&, const float*) at faiss/faiss/Clustering.cpp:305: Error: 'std::isfinite(x[i])' failed: input contains NaN's or Inf's" thrown in the test body.

the vector example:
`{"poiId":12776638,"spuId":6034833203,"geoHash":"wtm90","spuEmb":[0.20313291439554274,-0.2021541053574589,-0.19149257348371263,0.3273307490267441,-0.12689672263045047,0.0816080880156526,0.09788737374537025,-0.2659855793698378,0.36760980386211369,0.06592588504193324,-0.053182882012601666,0.1780933339888102,-0.32555891056970279,0.037058874770512058,-0.06688343571563944,0.2794744737058112,0.09254413007288416,-0.08344832294938723,-0.03026359238336142,-0.020377528671043256,-0.09578371994869521,-0.10805903896171855,0.23278740842564897,-0.18330902747503043,0.008802811405770215,0.17240256227258517,-0.21822820165709665,-0.10942511994216042,0.24415416343070588,0.08533846882557371,0.15768715273969273,0.01826185927711129]}`

when I use std::mt19937 success train and write index.
`std::mt19937 rng;
std::vector<float> trainvecs(1000 * 32);
std::uniform_real_distribution<> distrib;
for (size_t i = 0; i < 1000 * 32; i++) {
  trainvecs[i] = distrib(rng);
  std::cout << trainvecs[i] << std::endl;
}
index.train(1000, trainvecs.data());`

# Platform

linux

Running on:
- [ 1] CPU
- [ ] GPU

Interface: 
- [ 1] C++
- [ ] Python

**Comment by siyuanWang** [comment]
I solved this question.
the first param of Train，should be vector.size/dimension, not vector.size.

**Comment by vkgo** [comment]
I also encountered the same problem. My data's shape is [39. 2240] (2240 is the demention of faiss index) . I use 
`print(np.any(np.isnan(data_vectors)))`
`print(np.all(np.isfinite(data_vectors)))`
to check the data It returns False and True, which means data is not problematic.

section of my code: 
```
nlist = 8
quantizer = faiss.IndexFlatL2(dimention)
index = faiss.IndexIVFFlat(quantizer, dimention, nlist, faiss.METRIC_L2)
index.train(data_vectors)
index.add(data_vectors)
return index
```

section of my error:
```
RuntimeError                              Traceback (most recent call last)
[<ipython-input-23-c1515856ed2c>](https://localhost:8080/#) in <cell line: 21>()
     19 index = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_L2)
     20 # here we specify METRIC_L2, by default it performs inner-product search
---> 21 index.train(xb)

1 frames
[/usr/local/lib/python3.10/dist-packages/faiss/swigfaiss_avx2.py](https://localhost:8080/#) in train(self, n, x)
   5496     def train(self, n, x):
   5497         r""" Trains the quantizer and calls train_residual to train sub-quantizers"""
-> 5498         return _swigfaiss_avx2.IndexIVF_train(self, n, x)
   5499 
   5500     def add(self, n, x):

RuntimeError: Error in void faiss::Clustering::train_encoded(faiss::idx_t, const uint8_t*, const faiss::Index*, faiss::Index&, const float*) at /project/faiss/faiss/Clustering.cpp:303: Error: 'std::isfinite(x[i])' failed: input contains NaN's or Inf's
```

I can't solve it.

**Comment by Inverse-function** [comment]
hello, I have also encountered the same problem. Have you resolved it? How to solve it？
