### ISSUE TITLE
Faiss assertion idxf->xb.size() == idxf->ntotal * idxf->d

### ISSUE THREAD

**Issue by lidongliang** [facebookresearch/faiss#225]
Hello,

nb is 3000W, dim is 400 ，use IndexRefineFlat IndexIDMap
when nb is 300W， it is all ok，but when nb is 3000w

Faiss assertion idxf->xb.size() == idxf->ntotal * idxf->d failed in faiss::Index* faiss::read_index(FILE*, bool) at external/faiss_repo/index_io.cpp:502.

I can not analyze what causes this result, is it same with **https://github.com/facebookresearch/faiss/issues/169**?

thx~

**Comment by mdouze** [comment]
Hi 
What is the W in 300W? 

Could you post a minimal test that reproduces the issue?

**Comment by lidongliang** [comment]
i am sorry，1W = ten thousand，the datasets  is not big, but we need IndexRefineFlat , so the final index is 25GB

**Comment by lidongliang** [comment]
I updated to the latest faiss code, solved, thanks！！！

**Comment by Hugh0120** [comment]
By W it means 10k in Chinese
