### ISSUE TITLE
how can i reproduce the experiment on sift1m and sift1b claimed in your paper

### ISSUE THREAD

**Issue by zjuchenwei** [facebookresearch/faiss#226]
hi 
i have download the code and the sift dataset, i compiled the code, but i don't know how to run the code to get the recall result on sift1m and sift1b. Because I want  to compare the experiment data with my own approach. Please give me some instruction, Thank you very much.

**Comment by mdouze** [comment]
Hi 
See 
https://github.com/facebookresearch/faiss/tree/master/benchs

**Comment by zjuchenwei** [comment]
i see，thank you very much.
