### ISSUE TITLE
Allow setting 'hnsw.search_bounded_queue' for IndexIDMap->IndexHNSWFlat

### ISSUE THREAD

**Issue by raulcarlomagno** [facebookresearch/faiss#2265]
# Summary

# Platform

OS:  Linux

Faiss version:  1.7.2

Installed from: pip

Faiss compilation options: 

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

I would like to use IndexHNSWFlat with IndexIDMap or IndexIDMap2, that is OK and working
but at search time i would like to set 'hnsw.search_bounded_queue' parameter to False to do a full scan on IndexHNSWFlat, i tried with ParameterSpace() without luck

```
index_hnsw = faiss.IndexHNSWFlat(1024, 32, faiss.METRIC_INNER_PRODUCT)
index_hnsw.hnsw.efConstruction = 40
index = faiss.IndexIDMap(index_hnsw)

vectors = np.random.normal(0, 1, (5,1024)).astype('float32')
ids=np.random.randint(1000000, size=vectors.shape[0])
index.add_with_ids(vectors, ids)

#this works
index.search(np.random.normal(0, 1, (1, 1024)).astype('float32'), 10)

#but now before searching i would to do
#index_hnsw.hnsw.search_bounded_queue = False
#for a full scan

#i tried all of them
faiss.ParameterSpace().set_index_parameter(index, "hnsw.search_bounded_queue", 0)
faiss.ParameterSpace().set_index_parameter(index, "search_bounded_queue", 0)

#but i got
RuntimeError: Error in virtual void faiss::ParameterSpace::set_index_parameter(faiss::Index*, const string&, double) const at /project/faiss/faiss/AutoTune.cpp:547: ParameterSpace::set_index_parameter:could not set parameter search_bounded_queue

```
parameter should be added here like the others?
https://github.com/facebookresearch/faiss/blob/main/faiss/AutoTune.cpp#L539

faiss.ParameterSpace().get_index_parameter() should exist to check current parameters
or
maybe a function like extract_index_ivf() called extract_index_hnsw() could be useful

**Comment by mdouze** [comment]
I assume you loaded the index from a file and want to access the underlying hnsw structure. 
This is possible via: 
```
index_hnsw = faiss.downcast_index(index.index)
index_hnsw.hnsw.search_bounded_queue = False
```
see 
https://github.com/facebookresearch/faiss/wiki/Python-C---code-snippets#how-to-explore-the-contents-of-an-opaque-index
