### ISSUE TITLE
How can I read the centroid vectors from the index file?

### ISSUE THREAD

**Issue by HossamAmer12** [facebookresearch/faiss#2266]
How can I read the centroid vectors from the index file? kmeans.index is generated from the following code:

ncentroids = 1024
niter = 20
verbose = True
d = x.shape[1]
kmeans = faiss.Kmeans(d, ncentroids, niter=niter, verbose=verbose)
kmeans.train(x)

**Comment by KinglittleQ** [comment]
```
# assume index = kmeans.index
centroids = faiss.vector_to_array(index.xb).reshape(-1, d)
```

**Comment by HossamAmer12** [comment]
That's what happens when I try the code snippet:
'IndexFlat' object has no attribute 'xb'

**Comment by HossamAmer12** [comment]
This should be the code:
index = faiss.read_index(index_fname)
centroids = faiss.rev_swig_ptr(index.get_xb(), nCentroids * dim)
centroids = centroids.reshape(nCentroids, dim)

**Comment by HossamAmer12** [comment]
Want to give feedback about this --> get_xb() function name is really ambiguous to what it really does.

**Comment by KinglittleQ** [comment]
> This is the correct code:
> 
> ```
> index     = faiss.read_index("your/index/file")
> centroids = faiss.rev_swig_ptr(index.get_xb(), nCentroids * dim)
> centroids = centroids.reshape(nCentroids, dim)
> ```

Yes, you're right. I forgot that `IndexFlat.xb` has been changed to `get_xb()` since `IndexFlatCodes` was introduced.
