### ISSUE TITLE
Question about faiss.IO_FLAG_MMAP

### ISSUE THREAD

**Issue by OmniscienceAcademy** [facebookresearch/faiss#2271]
in the script https://github.com/facebookresearch/faiss/blob/main/demos/demo_ondisk_ivf.py
the flag is not used (line 77, `index = faiss.read_index(tmpdir + "populated.index")`)

Why not using instead `faiss.read_index(path, faiss.IO_FLAG_MMAP)` ?
The flag could reduce the RAM usage, which is the aim of this script, right ?

I ask because I do not find an example of this flag in the documentation, even in https://github.com/facebookresearch/faiss/wiki/Indexes-that-do-not-fit-in-RAM.

Thank you

**Comment by mdouze** [comment]
the IO_FLAG_MMAP is not necessary here because it is already an ondisk index, so it will be loaded with mem mapping anyways.

**Comment by anubhav562** [comment]
@mdouze Can you specify what exactly does the faiss.IO_FLAG_MMAP do?

**Comment by fabiozappo** [comment]
@mdouze thanks for your answer. I am trying to follow the faiss documentation but I am a bit lost, can you point me out if there is  any way to load an on disk index into memory?

I have a machine with lots of ram and I would like to be faster, would it help? 

Thanks
