### ISSUE TITLE
question about distance acquisition between vectors

### ISSUE THREAD

**Issue by Learningisboundless** [facebookresearch/faiss#2275]
index.search(q,k) returns the distance and id of the k nearest neighbors of the query vector. What if I want to get the distance between the query vector q and all the vectors in the dataset.
Thank you for your help!

**Comment by mdouze** [comment]
You could use `pairwise_distances`, see https://github.com/facebookresearch/faiss/blob/main/faiss/python/__init__.py#L1246
(also accessible on GPU and in C++)

**Comment by Learningisboundless** [comment]
Thanks for your help! But what I meant was getting the distance of the query vector to all the vectors in the IVFPQ indexed dataset

**Comment by mdouze** [comment]
It's a bit of a corner case. What about searching with nprobe = nlist and k=ntotal ?

**Comment by Learningisboundless** [comment]
Yes, I do. In order to get the distance between the query vector and each vector in the dataset, I first use the dataset to train indexIVFPQ, let nprobe=nlist,k=1, and then add one vector in the dataset each time to perform ANNsearch. After that, use index.reset() to clear the data. And so on, get all the distances

**Comment by mdouze** [comment]
Well this is a bit overkill. You could also compute 
```
faiss.pairwise_distances(query[1, :], index.reconstruct_n(0, index.ntotal))
```
