### ISSUE TITLE
range_search

### ISSUE THREAD

**Issue by anapaulaappel** [facebookresearch/faiss#2278]
Hi, I need to get all the tie lists, so I get the k=1 neighbor, add a small value to the distance of this neighbor (0.000001) and then do a range_search to get all vectors that are in the same distance. 

For range_search how does IndexIVFFlat perform? it is useful ? or does not matter if I am using IndexFlatL2 or IndexIVFFlat? 

Any suggestion on how do I scale this better? 

thanks

**Comment by mdouze** [comment]
your application context should dictate if you need IP or L2 search.
