### ISSUE TITLE
failed to check out tag: master

### ISSUE THREAD

**Issue by Kunlun-Zhu** [facebookresearch/faiss#2279]
fatal: unable to access 'https://github.com/facebookresearch/faiss.git/': GnuTLS         recv error (-110): The TLS connection was non-properly terminated.
Cloning into 'faiss'...
-- Had to git clone more than once:
          3 times.
fatal: invalid reference: master

is here an different release error?

**Comment by Kunlun-Zhu** [comment]
Cloning into 'faiss'...
fatal: invalid reference: master

**Comment by mdouze** [comment]
The relevant branch is called main not master.

**Comment by Kunlun-Zhu** [comment]
> The relevant branch is called main not master.
yeah, the command is from a cmake file using git, but it seem faiss is no longer support install from git, is that so

**Comment by mdouze** [comment]
There is no reference to master branch in the current Faiss version.
