### ISSUE TITLE
ProductQuantizer  compute_codes get wrong codes when nbits not 8

### ISSUE THREAD

**Issue by jasstionzyf** [facebookresearch/faiss#2285]
d = 10
    n = 400000
    cs = 5
    np.random.seed(123)
    x = np.random.random(size=(n, d)).astype('float32')
    testInputs=np.random.random(size=(1, d)).astype('float32')
    print(testInputs)
    pq = faiss.ProductQuantizer(d, cs,6)
    pq.verbose=True
    pq.train(x)
    codes=pq.compute_codes(testInputs)
    #here expect 5 code range from 0-64, but get 4 and also code number not range 0-64
    print(codes.shape)

**Comment by mdouze** [comment]
This is because the codes are packed into ceil(5 * 6) / 8 = 4 bytes.  
To access the individual codes, use `BitstringReader`: 

```python
bs = faiss.BitstringReader(faiss.swig_ptr(codes[0]), codes.shape[1])
for i in range(cs): 
    print(bs.read(6)).  # read 6 bits at a time
````

**Comment by jasstionzyf** [comment]
@mdouze   thanks very much!
