### ISSUE TITLE
`index_gpu_to_cpu` is not a member of `faiss::gpu`

### ISSUE THREAD

**Issue by tanmoyio** [facebookresearch/faiss#2293]
# Summary

Error:
```
/home/misha/faiss/faiss/gpu/test/demo_ivfpq_indexing_gpu.cpp: In function ‘int main()’:
/home/misha/faiss/faiss/gpu/test/demo_ivfpq_indexing_gpu.cpp:85:47: error: ‘index_gpu_to_cpu’ is not a member of ‘faiss::gpu’
   85 |         faiss::Index* cpu_index = faiss::gpu::index_gpu_to_cpu(&index);
      |                                               ^~~~~~~~~~~~~~~~
make[3]: *** [faiss/gpu/test/CMakeFiles/demo_ivfpq_indexing_gpu.dir/build.make:76: faiss/gpu/test/CMakeFiles/demo_ivfpq_indexing_gpu.dir/demo_ivfpq_indexing_gpu.cpp.o] Error 1
```
Running on:
- [ ] CPU
- [X] GPU

Interface: 
- [X] C++
- [ ] Python

# Reproduction instructions

I was following the `build from source` guide, everything went perfect, I managed to run the demo cpu test file mentioned in the doc. But I am facing issue while running `make -C build demo_ivfpq_indexing_gpu`

**Comment by bhatiaharsh** [comment]
see the cause of this error: https://github.com/facebookresearch/faiss/issues/2300 and https://github.com/facebookresearch/faiss/issues/1191
