### ISSUE TITLE
Can't run faiss example on CPU with MKL 

### ISSUE THREAD

**Issue by gf0507033** [facebookresearch/faiss#230]
I'm trying to run faiss with mkl. [MKL linking is nightmare](https://github.com/facebookresearch/faiss/blob/master/example_makefiles/makefile.inc.Linux#L33-L34).

**Problem**: I have built faiss with mkl and either [cpp demo](https://github.com/facebookresearch/faiss/blob/master/tests/demo_ivfpq_indexing.cpp) or python test script raises segfault:
```python
import faiss
import numpy
faiss.Kmeans(10, 20).train(numpy.random.rand(1000, 10).astype('float32'))
```
Full backtrace with gdb is [here](https://gist.github.com/gf0507033/12571c3653dddb80170961aa7c7a8e94). Segfault is here:
```
pi@pi:~/faiss$ MKLROOT=/opt/intel/compilers_and_libraries/linux/mkl LD_LIBRARY_PATH=$MKLROOT/lib/intel64 LD_PRELOAD=$MKLROOT/lib/intel64/libmkl_core.so:$MKLROOT/lib/intel64/libmkl_sequential.so:$MKLROOT/lib/intel64/libmkl_avx.so gdb
... (gdb info)
(gdb) file python
Reading symbols from python...(no debugging symbols found)...done.
(gdb) run 1.py
Starting program: /usr/bin/python 1.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffee8bd700 (LWP 10552)]
[New Thread 0x7fffec0bc700 (LWP 10553)]
[New Thread 0x7fffe98bb700 (LWP 10554)]
Failed to load GPU Faiss: No module named swigfaiss_gpu
Faiss falling back to CPU-only.
[New Thread 0x7fffe2922700 (LWP 10555)]
[New Thread 0x7fffe2121700 (LWP 10556)]
[New Thread 0x7fffe1920700 (LWP 10557)]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff2d34ba2 in mkl_blas_avx_sgemm_copybn () from /opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_avx.so
```

**Configuration**: Core i3-3217U, ubuntu 16.04 64-bit, gcc 5.4.0

The installation was smooth, checking `tests/test_blas` done.

Steps I have done to install faiss with mkl:
1. Install mkl from its apt repo:
    ```
    sudo apt install intel-mkl-64bit-2018.0-033
    source /opt/intel/compilers_and_libraries_2018.0.128/linux/mkl/bin/mklvars.sh intel64 mod ilp64
    ```
2. Uncomment [this line](https://github.com/facebookresearch/faiss/blob/master/example_makefiles/makefile.inc.Linux#L45) and remove trailing slash.
3. `make -j4`
4. `make py`

By the way, recompilation faiss with openblas works without such problems (on the same machine).

Could you share your success story with mkl?

**Comment by olalonde** [comment]
Here's the script I'm using (tested on Ubuntu 16.04). It assumes you are using a pyenv virtual environment named `faiss` and have a `~/code` directory.

https://gist.github.com/0fc6cfe12a0c1355a2c200ac0fb414fb

You're welcome :)

**Comment by mdouze** [comment]
Closing.
