### ISSUE TITLE
FAISSDocumentStore " TypeError: load() missing 1 required positional argument: 'index'"

### ISSUE THREAD

**Issue by ShabRa1365** [facebookresearch/faiss#2302]
# Summary
I am running the following code and facing this error, which wasn't appear in last 3 weeks, using same code. 

```
from haystack.retriever.dense import DensePassageRetriever

retriever = DensePassageRetriever(
    document_store=document_store,
    query_embedding_model='facebook/dpr-question_encoder-single-nq-base',
    passage_embedding_model='facebook/dpr-ctx_encoder-single-nq-base',
    use_gpu=True,
    embed_title=True
)

document_store.update_embeddings(retriever=retriever)
document_store.save(f'{path}/quality_CD1.faiss')
del document_store, retriever
document_store = FAISSDocumentStore.load(f'{path}/quality_CD1.faiss', f'sqlite:///{path}/quality_CD1.db')

retriever = DensePassageRetriever(
    document_store=document_store,
    query_embedding_model='facebook/dpr-question_encoder-single-nq-base',
    passage_embedding_model='facebook/dpr-ctx_encoder-single-nq-base',
    use_gpu=True,
    embed_title=True
)
```
Error I am facing is : 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-ad13332cd646> in <module>()
----> 1 document_store = FAISSDocumentStore.load(f'{path}/quality_CD1.faiss', f'sqlite:///{path}/quality_CD1.db')
      2 
      3 retriever = DensePassageRetriever(
      4     document_store=document_store,
      5     query_embedding_model='facebook/dpr-question_encoder-single-nq-base',

TypeError: load() missing 1 required positional argument: 'index'
-------------------------------------------------------------------------------
# Platform

I am running this sample code in jupyter lab  connected to GCP Deep learning VM tesla 100 GPU, Debina Linux

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU
- [X ] GPU

Interface: 
- [ ] C++
- [X ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
This is not the Faiss library. Please see 

https://haystack.deepset.ai

**Comment by ShabRa1365** [comment]
thanks
