### ISSUE TITLE
TypeError: in method 'fvec_L2sqr', argument 1 of type 'float const *'

### ISSUE THREAD

**Issue by suibianmzl** [facebookresearch/faiss#2303]
Excuse me, FVEC_ What are the first two parameters of the l2sqr function

if __name__ == '__main__':
    d = 384  # dimension
    nb = 1  # database size
    nq = 1  # nb of queries
    np.random.seed(1234)  # make reproducible
    xb = np.random.random((nb, d)).astype('float32')
    xb[:, 0] += np.arange(nb) / 1000.
    xq = np.random.random((nq, d)).astype('float32')
    xq[:, 0] += np.arange(nq) / 1000.
    res = faiss.fvec_L2sqr(xb[0], xq[0], d)
    print(res)

<img width="981" alt="image" src="https://user-images.githubusercontent.com/6262877/164707565-b51fbc29-19e7-42a1-9e40-ca08978a68d8.png">

**Comment by mdouze** [comment]
The correct way of calling it is 

`res = faiss.fvec_L2sqr(faiss.swig_ptr(xb[0]), faiss.swig_ptr(xq[0]), d)`

but it is easier and less error-prone to compute it in python: `res = ((xb[0] - xq[0])**2).sum()`

**Comment by suibianmzl** [comment]
> Thank you very much for your answer
