### ISSUE TITLE
Return ALL the indices falling into the nearest IVF cell

### ISSUE THREAD

**Issue by lindsey98** [facebookresearch/faiss#2304]
Hi, may I ask: 
   Given a query vector, how do I return ALL the indices falling into the nearest IVF cell?

**Comment by mdouze** [comment]
you could get the invlist index with `index.quantizer.search(q,1)` then get the IVF cell content with 
`get_invlist` in 
https://github.com/facebookresearch/faiss/blob/main/contrib/inspect_tools.py#L10

**Comment by lindsey98** [comment]
Hi thanks for your reply, then I guess the full code will be like this?
`  _, list_nos = index.quantizer.search(q, 1)
  closest_NN, _ = get_invlist(index.invlists, int(list_nos[0][0]))
`

**Comment by mdouze** [comment]
yes that looks good.
