### ISSUE TITLE
Failed to cudaMalloc

### ISSUE THREAD

**Issue by hengshanji** [facebookresearch/faiss#231]
I got an error "Faiss assertion 'cudaMalloc(p, size) == cudaSuccess' failed in void faiss::gpu::allocMemorySpace(faiss::gpu::MemorySpace, void**, size_t) at utils/MemorySpace.cpp:20; details: Failed to cudaMalloc 4294967296 bytes"  when i use nvidia GTX1080 with 8G memory to build faiss index. How this problem happens and how to solve this?  
I want to build a index with d=32768 nb=2M.

**Comment by wickedfoo** [comment]
This is likely the same issue as #220.

What kind of index are you building?

**Comment by hengshanji** [comment]
I use the GpuIndexFlatL2. 
I just want to test how many data can my gpu can handle. Is there some examples to build 10M vectors with dimention like 32768 using one gpu?

**Comment by wickedfoo** [comment]
GpuIndexIVFFlat should work.

This is a known issue with GpuIndexFlatL2 / GpuIndexFlatIP, am working on fixing it.

**Comment by reshu-b7** [comment]
Hi @wickedfoo 

I have been facing the same issue while running the bench_gpu_1bn.py on SIFT1B dataset. The script is running on 4 NVIDIA-SMI Tesla GPUs with 24 GB memory for each. The tempmem for each is set as per the command below. I have been noticing this error after index.add() and once the script tries copying loaded index to GPUs.

`python bench_gpu_1bn.py SIFT1000M IVF16384,PQ64 -nnn 1 -ngpu 4 -tempmem $[20 * 1024 * 1024 * 1024] -float16 -noptables -altadd`

```
Preparing dataset SIFT1000M
sizes: B (1000000000, 128) Q (10000, 128) T (100000000, 128) gt (10000, 1000)
cachefiles:
None
/mnt/sift1B/cent_SIFT1000M_IVF16384.npy
/mnt/sift1B/SIFT1000M_IVF16384,PQ64.index
preparing resources for 4 GPUs
load centroids /mnt/sift1B/cent_SIFT1000M_IVF16384.npy
making an IVFPQ index, m =  64
Training vector codes
  done 87.849 s
add...
999981056/1000000000 (18103.801 s)   Add time: 18103.801 s
store /mnt/sift1B/SIFT1000M_IVF16384,PQ64.index
CPU index contains 1000000000 vectors, move to GPU
copying loaded index to GPUs
IndexShards shard 0 select modulo 4 = 0
  IndexIVFPQ size 250000000 -> GpuIndexIVFPQ indicesOptions=0 usePrecomputed=0 useFloat16=1 reserveVecs=0
Faiss assertion 'cudaMalloc(p, size) == cudaSuccess' failed in void faiss::gpu::allocMemorySpace(faiss::gpu::MemorySpace, void**, size_t) at utils/MemorySpace.cpp:20; details: Failed to cudaMalloc 1042048 bytes
```

Would appreciate any suggestion.

Thanks.

**Comment by hot-cheeto** [comment]
have this issue been fixed ? :(
