### ISSUE TITLE
Can FAISS be installed on Jetson by using conda?

### ISSUE THREAD

**Issue by mjack3** [facebookresearch/faiss#2312]
# Summary

I have a pytorch neural network using FAISS that need to be deployed in a Jetson NX. How can I install it?

Thank you

# Platform

Jetson NX

Faiss version: v1.7.2

Installed from: anaconda

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by mdouze** [comment]
Short answer is no. 
Long answer is: not out-of-the-box. 
How is Faiss used in your neural net?

**Comment by mjack3** [comment]
well I'm using FAISS to do a GpuIndexFlatL2 search. The code is this:

```
resources = faiss.StandardGpuResources()
gpu_cfg = faiss.GpuIndexFlatConfig()
index = faiss.GpuIndexFlatL2(resources, bank_embeddings.shape[-1], gpu_cfg)
index.add(bank_embeddings)

 D, _ = index.search(embedding, 5)
```

**Comment by mjack3** [comment]
I will create a new post to better title

**Comment by mdouze** [comment]
TBH for a flat index you may be better off using an explicit distance computation and topk search. 
See [demo_pytorch_knn.ipynb](https://gist.github.com/mdouze/551ef6fa0722f2acf58fa2c6fce732d6#file-demo_pytorch_knn-ipynb)

**Comment by mjack3** [comment]
Thank you!.
I will test and would let you know
