### ISSUE TITLE
Why the max and min sample per center I set are not working？

### ISSUE THREAD

**Issue by jianxiangyu** [facebookresearch/faiss#2314]
# Platform

Faiss version:  1.7.2 

Running on: GPU

Interface:  Python

# Summary

I import faiss and use Kmeans clustering, and set the maximum and minimum number of each center, but in the actual operation process, the results obtained have many samples of their own kind, where am I wrong? , the code is as follows

        clus = faiss.Clustering(d, k)
        clus.verbose = False
        clus.niter = 20
        clus.nredo = 5
        clus.seed = seed
        clus.gpu = True
        clus.max_points_per_centroid = 10000
        clus.min_points_per_centroid = 5
        res = faiss.StandardGpuResources()
        cfg = faiss.GpuIndexFlatConfig()
        cfg.useFloat16 = False
        cfg.device = 0
        index = faiss.GpuIndexFlatL2(res, d, cfg)  

        clus.train(x, index)   
        D, I = index.search(x, 1)
        im2cluster = [int(n[0]) for n in I]

I have set  'clus.max_points_per_centroid = 10000' and 'clus.min_points_per_centroid = 5', but it doesn't work.
The result of 'im2cluster' is like [1,1,1,1,1,1,1,1000,1,1,1,1,1,2000], that too many of a class contains a sample. I don't want to get results like this. 
Is there something wrong with my settings, or is there something wrong with my data?

**Comment by mdouze** [comment]
min_/max_points_per_centroid just sets the ratio of nb of training points over number of centroids. 
It does not guarantee that the clusters are balanced. 
You probably have many duplicates or near-duplicates in your dataset, or outliers that are far away.

**Comment by jasonffk** [comment]
> min_/max_points_per_centroid just sets the ratio of nb of training points over number of centroids. 
> 
> It does not guarantee that the clusters are balanced. 
> 
> You probably have many duplicates or near-duplicates in your dataset, or outliers that are far away. 

Thanks for your reply! I will check my dataset.
