### ISSUE TITLE
Is there a way to retrieve a quantized representation of the vector being submitted? 

### ISSUE THREAD

**Issue by beviah** [facebookresearch/faiss#2325]
i.e. if I am submitting a 300 dimensional vector, can I get back the integer value for it that FAISS uses after quantization(s)?

**Comment by beviah** [comment]
If I am not mistaken, this provides an answer to my question: 

https://github.com/matsui528/nanopq

Though it is not done on residual vector after coarse quantizer.. So maybe my question still remains :)

**Comment by mdouze** [comment]
Not sure what you need exactly but `index.sa_encode` should give you what you want. 
For IVFPQ, the first bytes are for the coarse quantizer and the remainder for the residual.

**Comment by beviah** [comment]
Awesome! Thanks a lot!

**Comment by beviah** [comment]
@mdouze , I just realized, nlist is often >> 2**8, so how can coarse quantizer fit into a single byte?

**Comment by beviah** [comment]
@mdouze python wrappers for encode are definitely broken.. have tried all the examples i found on github.. all failed..

**Comment by beviah** [comment]
hmm, from another machine all works well.. not sure what was the problem..
