### ISSUE TITLE
Python equivalent of faiss::gpu::getMaxKSelection()

### ISSUE THREAD

**Issue by anferico** [facebookresearch/faiss#2330]
What is the equivalent Python function of the C++ function [faiss::gpu::getMaxKSelection()](https://faiss.ai/cpp_api/namespace/namespacefaiss_1_1gpu.html#_CPPv4N5faiss3gpu16getMaxKSelectionEv)? I can't seem to find it anywhere.
I'd like to know what's the maximum value of **k** that I can specify when calling `index.search(...)`, where **k** is the amount of similar vectors to retrieve for each query.

**Comment by mdouze** [comment]
It is 1024 on GPU.
