### ISSUE TITLE
Faiss IndexIP has overflow distance

### ISSUE THREAD

**Issue by UnicornGHP** [facebookresearch/faiss#2333]
# Summary
I have L2 normalized vectors in Faiss IndexIP and I use other L2 normalized vector to search nearest neighbor. If query batch for the input is equal to 1, then everything is fine with reasonable distance. However, if query batch for the input is greater than 1, then distance values are overflow. Sometimes, all of them are overflow. Sometimes, one or some of them are.

# Platform

OS: Ubuntu 18.04

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

**Comment by mdouze** [comment]
This should not happen. Could you post a short code that reproduces this?
