### ISSUE TITLE
Will your team consider implementing faiss on FPGA(Field Programmable Gate Array)?

### ISSUE THREAD

**Issue by SupermeReturns** [facebookresearch/faiss#234]
GPU memory is limited and more data  can not fit in GPU. FPGA is fast and has low latency. And FPGA with commodity memory such as Double Data Rate (DDR) SDRAM is cheap and fully scalable and would appear to be the best solution. Microsoft Bing search engine is already using FPGA to accerlate searching. Will your team consider implementing faiss on FPGA(Field Programmable Gate Array)? Can you throw light upon these problems? Thank you

**Comment by wickedfoo** [comment]
I don't think this is appropriate.

Faiss algorithms are mostly memory bandwidth limited, and the working set size of the memory that is required is way larger than the size available in any FPGA’s block SRAM (unless there is a hot subset of the data that is constantly being touched), so it is really bound by the bandwidth to main (DRAM) memory.

Most/all available FPGA dev environments that I am aware of use DDR3 or DDR4 at best, so a GPU’s HBM memory will mean a much faster implementation.
