### ISSUE TITLE
How to use faiss with more threads on multi gpus?

### ISSUE THREAD

**Issue by GlennCGL** [facebookresearch/faiss#2342]
# Summary

I want to use 4 gpus and faiss_multigpu on slurm cluster environment. Here is my srun script: srun --gres=gpu:4 -n1 --ntasks-per-node=1 python xx.py. If in this way, what is the default number of threads? How can I check the number of threads?
If I want to use more threads to speed up in parallel, how to change the code or script?
Many thanks!

# Platform

OS: <cluster, slurm>

Faiss version: <version 1.6.5>

Installed from: < anaconda> 

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

```python
ngpus = faiss.get_num_gpus()
cpu_index = faiss.index_factory(D, "Flat") #use exact search

co = faiss.GpuMultipleClonerOptions()
co.useFloat16 = True
co.usePrecomputed = False
co.shard = True
gpu_index = faiss.index_cpu_to_all_gpus(cpu_index, co, ngpu=ngpus)
gpu_index.add(features) 
dists, nbrs = gpu_index.search(query, k=k)
```

**Comment by GlennCGL** [comment]
> There is one thread per GPU and adding more threads will not speed up the search because the GPU is doing all the computations.

The time-consuming of using multiple gpus is not as small as I thought. What is the matter with this?

**Comment by mdouze** [comment]
> > There is one thread per GPU and adding more threads will not speed up the search because the GPU is doing all the computations.
> 
> When I search a dataset about **600000** features, it cost about **37.7642s for 1 gpus** and **33.7777s for 2 gpus**. Do you think this is reasonable? **If the codes and scripts above correct? If not, what is the best way to use?**

yes because you shard the dataset rather than replicating it (co.shards=True). Sharding is useful only if the dataset does not fit on the GPU.
