### ISSUE TITLE
Faiss: how to count Euclidean distance

### ISSUE THREAD

**Issue by ldevyataykina** [facebookresearch/faiss#2347]
I have two vectors

    a = array([ 5.00000000e+00,  5.60000000e+01, -3.05346221e-05,  2.27957207e-04,
        1.08395798e-04,  1.06920903e-04, -4.08892462e-04, -8.78322899e-05,
        6.80192665e-04,  3.32406489e-04, -5.32560080e-05,  1.24421727e-04,
       -7.55389992e-05,  3.67591274e-04,  2.44108640e-04,  3.20396328e-04,
       -3.08895600e-04,  1.20941702e-04, -3.01520390e-06, -3.36959085e-04,
        6.62388396e-04,  2.09437319e-04,  5.20801928e-04, -1.74579822e-04,
        2.50260637e-04,  4.59187606e-04,  5.93216755e-05, -2.68452859e-04,
       -7.14879061e-05, -1.26210361e-04,  4.59579533e-05, -2.78545835e-04,
        1.96518857e-04,  2.00679744e-04, -1.74629997e-04, -1.46402352e-04,
        1.73549983e-04, -2.57993361e-06,  4.08159278e-04, -2.00136037e-05,
        3.73761395e-05,  4.41685464e-04,  3.01405264e-04, -1.58497845e-04,
       -1.69425490e-04, -2.50656899e-06,  2.78263964e-04, -4.48697421e-04,
       -9.46737418e-05, -2.06503668e-04,  2.83674919e-04, -6.22806692e-05,
        6.99463490e-05,  4.89320018e-06, -2.82633235e-04, -1.44967635e-04,
       -4.10622568e-04,  6.64352032e-04, -5.06282260e-04,  1.73872977e-04,
       -4.76709247e-05, -8.81068772e-05,  2.82439170e-04, -8.43883172e-05,
        1.13919514e-05,  1.51750559e-04, -4.76656242e-05, -3.14259669e-04,
        4.90785285e-04,  2.48499942e-04,  6.23276428e-05, -1.20650970e-04,
       -2.74756549e-05,  2.00494537e-06, -1.10852969e-04,  1.93565284e-04,
       -2.94418103e-04, -1.91532876e-04,  6.75584999e-07, -2.99960702e-05,
       -1.17232477e-04,  1.37663519e-04,  1.00160185e-04,  3.69900197e-04,
        1.66014666e-04, -9.95581649e-05, -1.58413110e-04,  2.23749841e-04,
       -5.00751426e-04, -2.77587475e-04,  4.09778935e-04,  4.56032227e-04,
       -7.06943043e-04, -1.95935456e-04,  4.19925964e-05,  1.85226760e-04,
        3.24553752e-04, -3.17002377e-06, -2.23288182e-04, -1.27612249e-04,
        8.79685467e-05,  2.05529195e-05], dtype=float32)

and

    b = array([ 5.00000000e+00,  5.60000000e+01, -4.93110681e-04, -4.80463466e-04,
        2.22629722e-04,  1.30495208e-03,  3.42394982e-04,  6.24750333e-04,
        7.52990774e-04,  9.52379487e-04, -3.83697101e-04,  3.63726649e-05,
       -1.06124229e-04,  4.18595999e-04, -9.71906993e-05,  1.41314371e-03,
       -3.01639811e-04,  5.21359092e-04,  8.48083815e-04,  8.34418461e-05,
       -2.89290794e-04,  4.79217706e-04,  4.37101553e-04, -7.35441572e-05,
        8.08713317e-04, -6.94889168e-04, -7.62873155e-04, -4.85854922e-04,
       -1.40286269e-04, -2.92266835e-04,  1.41423394e-03, -2.91358301e-04,
       -1.86691163e-04, -8.33551108e-04, -2.05978387e-04, -7.55004352e-04,
        7.50020496e-04, -8.06101889e-04, -2.63082562e-04,  2.07166901e-04,
       -5.94258599e-04,  7.41241907e-04, -3.06798174e-04,  4.84313117e-04,
        5.54781640e-04,  9.16764475e-05, -5.32745849e-04, -4.68981656e-04,
       -5.14168991e-04,  7.85363896e-04, -6.66610838e-04,  1.11327194e-04,
       -3.45449458e-04, -5.06935212e-05, -3.75450880e-04, -5.20885733e-05,
       -6.61014754e-04, -4.34476242e-05, -7.71435036e-04, -3.18870734e-05,
        6.94373681e-04,  8.57607301e-05, -4.57006186e-04, -1.61796488e-04,
        2.20948568e-04, -1.20980030e-05, -2.34652573e-04, -2.60421308e-04,
       -9.69141984e-05, -1.83231095e-04, -6.57126307e-04, -3.96148593e-04,
       -1.03770243e-03,  8.34746344e-04, -4.12137102e-04, -2.51460406e-05,
        3.50769144e-04, -3.40059603e-04,  6.13220676e-04,  9.98003525e-04,
       -2.36301858e-04,  9.97885596e-04,  1.95924644e-04,  4.41285898e-04,
       -4.97553730e-04,  3.07404953e-05,  4.69280116e-04, -3.09369294e-04,
        1.15101167e-03, -8.12438666e-04, -6.12439762e-04,  3.75226256e-04,
       -9.32931202e-04, -2.23719835e-04, -5.41583926e-04,  4.11298330e-04,
        1.34949150e-04,  1.49794985e-04,  6.66729175e-04,  1.83589815e-04,
        8.11503385e-04,  4.88200021e-04], dtype=float32)

And according to `IndexFlatL2` they are equal because the distance between them is 0.

When I use `spacy.spatial.distance.euclidean(a, b)` I get value 0.005837273318320513.

How can I get real values of the distances using faiss?
And what I get right now using faiss?

I've read about using square root, but it still returns 0.
I know that the cosine distance between these 2 vectors is 0.
Maybe faiss count cosine similarity and then convert it into euclidean?

**Comment by mdouze** [comment]
This is a floating-point accuracy issue, see: 
https://github.com/facebookresearch/faiss/wiki/FAQ#why-do-i-get-weird-results-with-brute-force-search-on-vectors-with-large-components

**Comment by mdouze** [comment]
See also issue #297

**Comment by ldevyataykina** [comment]
@mdouze thank you! It's very helpful
