### ISSUE TITLE
Discrepancy in the results of IndexFlat and IndexFlatIP

### ISSUE THREAD

**Issue by kai5gabriel** [facebookresearch/faiss#2349]
# Summary
I have created an flat index wrapped with IndexIDMap so that I can add custom Ids to it. The code which I have used to create is attached below

```
cc_index = faiss.IndexIDMap(faiss.IndexFlatIP(model.get_dimension()))
#conversion required for the integer type
ids = np.array(transaction_ids)
ids = np.asarray(ids.astype('int64'))
emb = np.array(address_embedding)
emb = np.asarray(emb.astype('float32'))
cc_index.add_with_ids(emb,ids)
```

Running on:
- [x] CPU

Interface: 
- [x] Python

# Reproduction instructions

I see that IndexFlat has two subclasses IndexFlatIp and IndexFlatL2. However when the index is created using IndexFlatIP, I am seeing the rank order of results is wrong. But if I choose IndexFlat instead of the IndexFlatIP I see the results ranked correctly in the top_k. I calculated the cosine similarity using python code and the same ranking order I am able to find in IndexFlat.
What is causing the discrepancy in the results rank order?
cc_index = faiss.IndexIDMap(faiss.IndexFlatIP(model.get_dimension()))
vs
cc_index = faiss.IndexIDMap(faiss.IndexFlat(model.get_dimension()))

**Comment by mdouze** [comment]
For `faiss.IndexFlat` the default distance measure is L2. To get IP just do

`faiss.IndexFlat(model.get_dimension(), faiss.METRIC_INNER_PRODUCT)`
