### ISSUE TITLE
Similarity Search why Faiss over lucene/Solr?

### ISSUE THREAD

**Issue by sunil0791** [facebookresearch/faiss#235]
Hi,

1. Lucene/SOLR provides "more like this" feature. Could you please explain how faiss similarity search is more efficient than Lucene/SOLR?.
2. Why and when to choose faiss over Lucene/SOLR?.

Awaiting your response.

Thanks,
Sunil

**Comment by jegou** [comment]
I think comparing Faiss to Lucene is a bit apples-to-oranges comparison. 

1. Faiss provides the state-of-the-art algorithms for exact and approximate similarity search on the GPU, as well as as the state-of-the-art compressed domain search for billion size datasets. It includes most recent algorithms for these very large scale settings. This is demonstrated on public benchmarks used by the scientific community, and the corresponding papers are state-of-the-art in the aforementioned setting. 

I don't know Lucene in details, but I have not seen it proposed as a baseline in any of the comparisons done by the researchers working in this area, while I read dozens about similarity search paper every month. After a rapid check, trying to find which algorithms are used, I could not find to which functions you might refer and that could compete with Faiss. Could you elaborate?

2. Lucene is a framework for information retrieval. I would say that it is intended to be used as a higher-level for general retrieval task for reasonable size collections. In contrast, Faiss only provides the core similarity search primitives such as nearest neighbor and graph computation, but the library certainly provides much higher performance and can scale more.

**Comment by sunil0791** [comment]
Hi Jegou,

Thanks a lot!! for the reply.

We (my team) are new to similarity search.
For our use-case, we have a data set of around 1 to 5 Million Text Documents and when a new document comes in we wanted to suggest similar documents.
For this we came across Lucene/SOLR providing similarity search (More like this) feature
https://lucene.apache.org/solr/guide/6_6/morelikethis.html 

We came across Faiss providing similarity search on huge data-set efficiently. So, We were trying to evaluate which one would fit our requirement.

Please let us know your thoughts on the same.

Thanks & Regards,
Sunil

**Comment by jegou** [comment]
But I can not really tell, since I don't know how you describe your document and for which purpose. 
*  Lucene integrates vanilla text ranking methods like BM25.  Considering your small volume, and the fact that you handle text documents, it sounds like Lucene would deserve a first.
* with Faiss we would assume that YOU know how to handle the document description. Typically Faiss is interesting if you use text embeddings methods. But we consider that making the description part is out the scope of Faiss maintainers.

**Comment by rmayer-sst** [comment]
Worth noting that Amazon's fork of ElasticSearch (OpenSearch) now has FAISS indexes:

https://opensearch.org/docs/latest/search-plugins/knn/knn-index/

>> The Approximate k-NN search methods leveraged by OpenSearch use approximate nearest neighbor (ANN) algorithms from the [nmslib](https://github.com/nmslib/nmslib), [faiss](https://github.com/facebookresearch/faiss), and [Lucene](https://lucene.apache.org/) libraries to power k-NN search
>>
>> ...
>>
>> * The faiss engine performs exceptionally well (on orders of magnitude) with hardware that includes a GPU. When cost is not the first concern, this is the recommended engine.
>> * When only a CPU is available, nmslib is a good choice. In general, it outperforms both faiss and Lucene.

Wonder if this is worth re-opening with that context.


>
