### ISSUE TITLE
Correct pronunciation

### ISSUE THREAD

**Issue by jankrepl** [facebookresearch/faiss#2359]
Sorry for such a stupid question. I was not able to find this information anywhere.

What is the right  way to pronounce `faiss`?

1. Like the word `facebook`
2. Like the word `feisty`

Thanks in advance

**Comment by mdouze** [comment]
there is no agreed upon pronunciation ;-)

**Comment by jankrepl** [comment]
> there is no agreed upon pronunciation ;-)

OK then! Thank you!
