### ISSUE TITLE
Can Anyone explain the IVFADC+R for me?

### ISSUE THREAD

**Issue by 0DF0Arc** [facebookresearch/faiss#236]
I don't really understand the R in the IndexIVFPQR, does it mean another product quantization for the residual? or for the residual of the residual? or something else?

and by the way, can anyone explain the parameters of IndexIVFPQR for me?  like x, y, and z in "IVFx,PQy+z"
, also the coarse_quantizer in' coarse_quantizer = faiss.IndexFlatL2 (d)' has to be FLatL2？

**Comment by jegou** [comment]
Right, there is another level of residual with +R, which was first proposed in this ICASSP'2011 paper:
https://arxiv.org/pdf/1102.3828.pdf 

x=number of coarse centroids
y=byte budget for the "regular" ADC distance estimation
z=byte budget for the refinement stage.

**Comment by mdouze** [comment]
closing.
