### ISSUE TITLE
search_and_reconstruct slow for IndexIVFPQ when queried with >= 20 queries

### ISSUE THREAD

**Issue by TobiasNorlund** [facebookresearch/faiss#2360]
# Summary

I have an IndexIFVPQ with `ntotal = 3062380902` that I want to search and reconstruct nearest neighbours from. However calling `index.search_and_reconstruct(queries, k=1)` is significantly slower when there are **20** or more elements in `queries` compared to 19 or less. 19 queries take ~50ms whereas 20 queries take over 5s. When querying with 20 queries, the CPU goes up to 100% utilization on all cores, so there is something heavy going on.

Side note: I don't see this phenomena if I manually run `index.reconstruct(i)` in a python for loop for each index retrieved by `index.search(queries)`. I find it strange that this approach is faster.

Does anyone know what this is caused by?

# Platform

OS: Linux

Faiss version: 1.7.2

Installed from: anaconda

Faiss compilation options: 

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

```python
import numpy as np
from time import time

index = faiss.read_index("<path>")

query_embeddings = np.random.randn(25, 384).astype(np.float32)
query_embeddings /= np.linalg.norm(query_embeddings, ord=2, axis=-1, keepdims=True)

# 15 queries
start_t = time()
distances, indices, embeddings = index.search_and_reconstruct(query_embeddings[:15, :], k=1)
print("15 queries time:", time() - start_t)

# 19 queries
start_t = time()
distances, indices, embeddings = index.search_and_reconstruct(query_embeddings[:19, :], k=1)
print("19 queries time: ", time() - start_t)

# 20 queries
start_t = time()
distances, indices, embeddings = index.search_and_reconstruct(query_embeddings[:20, :], k=1)
print("20 queries time:", time() - start_t)

# 25 queries
start_t = time()
distances, indices, embeddings = index.search_and_reconstruct(query_embeddings[:25, :], k=1)
print("25 queries time:", time() - start_t)

```

This produces the following output:

```
15 queries time: 0.04751777648925781
19 queries time: 0.054619550704956055
20 queries time: 5.278900623321533
25 queries time: 5.793105840682983
```

**Comment by mdouze** [comment]
Are you using a flat coarse quantizer? The threshold 20 queries swtiches between 2 implementations at 20 queries, see 

https://github.com/facebookresearch/faiss/wiki/Implementation-notes#matrix-multiplication-to-do-many-l2-distance-computations

this does not explain why the BLAS implementation is so slow though, the BLAS shipped with anaconda is MKL, that  very efficient.

**Comment by TobiasNorlund** [comment]
Thanks for letting me know this! For the time being raising the threshold for the first implementation works well enough, but I might investigate if I have messed up my conda environment if the need arises.
