### ISSUE TITLE
Does kmeans support INNER_PRODUCT distance?

### ISSUE THREAD

**Issue by zhanghan9797** [facebookresearch/faiss#2363]
Hi, I want to know if the `faiss.IndexIVFFlat` index is using the kmeans method during training, can the distance calculation only use L2? Is it possible to use INNER_PRODUCT?
Can I use INNER_PRODUCT as distance for kmeans?

I want to implement it this way, is this correct?
```
quantizer = faiss.IndexFlatIP(emb_size)
index = faiss.IndexIVFFlat(quantizer, emb_size, ivf_centers_num,faiss.METRIC_INNER_PRODUCT)
```
At the same time I also want to know what does `quantizer ` and `faiss.METRIC_INNER_PRODUCT` mean here?

Looking forward to your reply！

**Comment by mdouze** [comment]
Inner product is supported.
It does not use L2 at search time, but inner product, as expected.

**Comment by meghbhalerao** [comment]
Hi - I am not sure this is the right place to ask this, but I would like to know the exact place in the source code where the k means clustering is happening which is using inner product as a similarity metric rather than the Euclidean L2 distance.
If inner product is being used as a similarity metric, then how are the cluster centers being calculated - since I dont think it makes sense to use the arithmetic mean as the cluster center since that is specific to the Euclidean space and distance metric. Thanks and please let me know if I am missing something.

--Megh

**Comment by mdouze** [comment]
Yes the arithmetic mean is used to compute centroids. 

Indeed the decreasing mean squared error guarantee does not hold with anything else than L2 assignment. However the inner product assignment is useful, especially in combination with the L2 normalization of the centroids after each iteration.

**Comment by mertozlutiras-hyrd** [comment]
Could you briefly describe how we can assign the inner product assignment in the python interface?

> Yes the arithmetic mean is used to compute centroids.
> 
> Indeed the decreasing mean squared error guarantee does not hold with anything else than L2 assignment. However the inner product assignment is useful, especially in combination with the L2 normalization of the centroids after each iteration.

**Comment by subminu** [comment]
According to this post (https://stats.stackexchange.com/questions/299013/cosine-distance-as-similarity-measure-in-kmeans), I think, you can implement kmeans clustering on inner product metric space (not actually but it has a linear relationship with the cosine similarity metric space) as following process.

There are two requirement.
1. normalized vectors
2. set spherical option as True

```python
NUM_VECS = 1024
DIM_VECS = 512

np_vecs = np.random.rand(NUM_VECS, DIM_VECS)
faiss.normalize_L2(np_vecs)

ncentroids = 4
niter = 20
verbose = True
d = 512
kmeans = faiss.Kmeans(d, ncentroids, niter=niter, verbose=verbose, spherical=True, gpu=True)
kmeans.train(np_vecs)
```
