### ISSUE TITLE
Search Knn With One Piece Of Data  Optimization

### ISSUE THREAD

**Issue by suwen-ux** [facebookresearch/faiss#2365]
# Summary

I want to speed up when building knn with one piece of data .
In theory, the optimal implementation requires only half the amount of computation of the existing implementation.
So I want to ask if there is any other way to speed up the construction of knn.

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:这是我目前的实现，想请问一下有没有更好的方法
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

This is my current implementation, would like to ask if there is a better way

res = faiss.StandardGpuResources()
index = faiss.GpuIndexFlatIp(res,dim)
index.add(feat)
sims,nbrs = index.search(feat,k=k)

I try to get close to optimal speed by splitting to reduce the number of alignments,just like

res = faiss.StandardGpuResources()
feat = np.split(feat,2)
a = feat[0]
b = feat[1]
index1 = faiss.GpuIndexFlatIp(res,dim)
index2 = faiss.GpuIndexFlatIp(res,dim)
index1.add(a)
index2.add(b)
sims1,nbrs1 = index.search(a,k=k)
sims2,nbrs2 = index.search(b,k=k)
sims3,nbrs3 = index.search(b,k=k)

The number of alignments is reduced by a*b but there is a problem in organizing the results

In theory, a*b only needs to be compared once, which can reduce the comparison of a*b. However, because the returned topk has only one b to a

So I want to ask if there is another way to write it?

Thanks

**Comment by mdouze** [comment]
you probably want to split the search over sub-datasets. For this you can just do

index = faiss.index_cpu_to_all_gpus(faiss.IndexFlatIP(dim))

which will use all GPUs by default

**Comment by suwen-ux** [comment]
Thanks
