### ISSUE TITLE
Farthest point search support further ?

### ISSUE THREAD

**Issue by DonaldRR** [facebookresearch/faiss#2366]
Hi!

I think a high efficient farthest neighbor searching algorithm is good for some research (at least for me ^-^), that does the argmax ||·|| or argmin -||·|| instead.
Is it possible this function would be supported in the further version ?

Thank you!

**Comment by mdouze** [comment]
This is not supported for L2 distance search (for Inner product it's simple to just query -x). I don't see an easy workaround for L2.
