### ISSUE TITLE
Getting the centroids of an IndexBinaryIVF

### ISSUE THREAD

**Issue by cxmscb** [facebookresearch/faiss#2369]
How do I get the value of IVF centroids from a trained IndexBinaryIVF file with python?

I did not deal with it based on the link https://github.com/facebookresearch/faiss/issues/961.

**Comment by cxmscb** [comment]
@mdouze Sorry, I did not find the function “array_to_vector”.  The python version of Faiss is 1.7.2.

**Comment by mdouze** [comment]
ah right, it is the opposite: 
```
faiss.vector_to_array(faiss.downcast_IndexBinary(index.quantizer)).reshape(index.nlist, -1)
```

**Comment by cxmscb** [comment]
Thx, it works!!!
