### ISSUE TITLE
'nx >= k' failed: need at least as many training points as clusters

### ISSUE THREAD

**Issue by logidelic** [facebookresearch/faiss#237]
Just getting started with faiss, and trying to understand the error below. Any ideas?

```
int d  = 128;
int nb = 111;
float* xb = new float[d * nb];
// init data...

int nlist = 1; // just for testing purposes; also tried higher numbers

faiss::IndexFlatL2 quantizer(d);
faiss::IndexIVFPQ index(&quantizer, d, nlist, 8, 8);
index.verbose = true;

m_index.train(nb, xb);

> Training IVF residual
> computing residuals
> training 8x256 product quantizer on 111 vectors in 128D
> Training PQ slice 0/8
```
And then the exception:

```
virtual void faiss::Clustering::train(faiss::Clustering::idx_t, const float*, faiss::Index&) at /home/logidliec/dev/faiss/Clustering.cpp:68:
Error: 'nx >= k' failed: need at least as many training points as clusters
```
A bit of debugging shows `nx==111` (good) and `k==256` (`1 << nbits` in ProductQuantizer::set_derived_values). I can fix the issue by setting the number of bits per subvector to 4, instead of 8, as in:

`faiss::IndexIVFPQ index(&quantizer, d, nlist, 8, 4);`

But I'd still like to understand what the limitation is here more generally...

**Comment by wickedfoo** [comment]
Each product quantizer has 2^nbits centroids. k-means is used to produce the centroids. In your case, you are running k-means (where k is 256) on 111 values which doesn't make sense.

You need at least as many training vectors as centroids as you are calculating, preferably more.

**Comment by logidelic** [comment]
Thanks for that, makes sense. However, I'm not specifying k=256 anywhere - it gets derived based on the number of bits. I think the docs should mention this and make explicit the limitation, otherwise the only way to know what's going on is to debug the faiss code...
