### ISSUE TITLE
C++ alternative to faiss.normalize_L2(xb) ?

### ISSUE THREAD

**Issue by Kapil-23** [facebookresearch/faiss#2375]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

 

Hello,
I was able to calculate the cosine similarity between two vectors using [95#issuecomment-714562162](https://github.com/facebookresearch/faiss/issues/95#issuecomment-714562162)
I want to perform the same thing using C++.
But to normalize the value there is no api faiss::faiss.normalize_L2.

**Comment by mdouze** [comment]
The C++ equivalent is `fvec_renorm_L2`
