### ISSUE TITLE
Flat + IDMap index when adding with ids copy itself inside the GPU? 

### ISSUE THREAD

**Issue by LazyDBA247-Anyvision** [facebookresearch/faiss#2382]
# Summary
Flat+IDMap index:
it looks like each add_with_ids to the GPU index is copying the index inside the GPU memory, so it means the max size of the index is less than half of the GPU RAM (NVIDIA M60 -> 7680MB), I can only add 3.5M+- vectors of 1KB (256 f32) and not around 6M+-.
doesn't happen on IVF index

OS:  ubuntu22.04
Faiss version: 1.7.2 

Installed from: anaconda & compiled locally

Faiss compilation options: cmake -B build . -DFAISS_ENABLE_GPU=ON -DFAISS_ENABLE_PYTHON=ON -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON -DFAISS_OPT_LEVEL=avx2 -Wno-dev -DCMAKE_CUDA_COMPILER=/usr/local/cuda-11.7/bin/nvcc

Running on:
- [ ] CPU
- [*] GPU

Interface: 
- [ ] C++
- [*] Python

# Reproduction instructions

create a "IDMap,Flat" index using index factory and move to the GPU
then bulk loop add_with_ids, when the size of the index is half of the GPU (reduce the working memory 1.5GB +-)
the "error" occurs.

example code:
```
import faiss
import time
import numpy as np

d = 256
metric = faiss.METRIC_INNER_PRODUCT
index = faiss.index_factory(d, 'IDMap,Flat', metric)
res = faiss.StandardGpuResources()
res.setLogMemoryAllocations(enable=True)
gpu_index = faiss.index_cpu_to_gpu(res, 0, index)
gpu_index.verbose = True

N = pow(2, 18)

idsN = N
for i in range(1,100):
    xb = np.random.random((N, d)).astype('float32')
    ids = range(idsN, idsN+N)
    n_ids = np.asarray(ids)
    idsN += N
    gpu_index.add_with_ids(xb, n_ids)
    print(f"loaded # of ids = {idsN}")
```

output of verbose & error:

```
loaded # of ids = 2883584
StandardGpuResources: alloc ok type FlatData dev 0 space Device stream 0x55ec800a5f70 size 2952790016 bytes ptr 0x0x3f488e0000
StandardGpuResources: dealloc type FlatData dev 0 space Device stream 0x55ec800a5f70 size 2684354560 bytes
StandardGpuResources: alloc ok type FlatData dev 0 space Device stream 0x55ec800a5f70 size 11534336 bytes ptr 0x0x3f01660000
StandardGpuResources: dealloc type FlatData dev 0 space Device stream 0x55ec800a5f70 size 10485760 bytes
loaded # of ids = 3145728
StandardGpuResources: alloc ok type FlatData dev 0 space Device stream 0x55ec800a5f70 size 3221225472 bytes ptr 0x0x3ff88e0000
StandardGpuResources: dealloc type FlatData dev 0 space Device stream 0x55ec800a5f70 size 2952790016 bytes
StandardGpuResources: alloc ok type FlatData dev 0 space Device stream 0x55ec800a5f70 size 12582912 bytes ptr 0x0x3f02160000
StandardGpuResources: dealloc type FlatData dev 0 space Device stream 0x55ec800a5f70 size 11534336 bytes
loaded # of ids = 3407872
StandardGpuResources: alloc fail type FlatData dev 0 space Device stream 0x55ec800a5f70 size 3489660928 bytes (cudaMalloc error out of memory [2])
Traceback (most recent call last):
  File "test5.py", line 21, in <module>
    gpu_index.add_with_ids(xb, n_ids)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/faiss-1.7.2-py3.8.egg/faiss/__init__.py", line 235, in replacement_add_with_ids
    self.add_with_ids_c(n, swig_ptr(x), swig_ptr(ids))
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/faiss-1.7.2-py3.8.egg/faiss/swigfaiss.py", line 8397, in add_with_ids
    return _swigfaiss.IndexIDMap_add_with_ids(self, n, x, xids)
RuntimeError: Error in virtual void* faiss::gpu::StandardGpuResourcesImpl::allocMemory(const faiss::gpu::AllocRequest&) at /home/ubuntu/faiss/faiss/gpu/StandardGpuResources.cpp:452: Error: 'err == cudaSuccess' failed: StandardGpuResources: alloc fail type FlatData dev 0 space Device stream 0x55ec800a5f70 size 3489660928 bytes (cudaMalloc error out of memory [2])
```

**Comment by wickedfoo** [comment]
It is best to add vectors all at once instead of incrementally, if you know what you are adding in advance. Otherwise, incremental ads require keeping around the allocation for the previous set until the new allocation has been added and everything can be coalesced together.

This is similar to the limitation that C++ std::vector<> or most any array primitive has as well, as the in-memory storage is contiguous, not a linked list.

**Comment by wickedfoo** [comment]
IVF indices don't have nearly the same issue because instead of adding to a single multi-GB sized list, you are instead adding to tens/hundreds/thousands of smaller lists in a similar but serial fashion, so the memory hit is not as big.
