### ISSUE TITLE
FAISS INDEX BINARY ON GPU - CRASHES WHILE SEARCHING

### ISSUE THREAD

**Issue by astar10239** [facebookresearch/faiss#2385]
Hi,

I have a centos server with TESLA V100 16GB.

I have a binary flat index of 2.5gb disk size, which i am loading to GPU via

res = faiss.StandardGpuResources()
self.index = faiss.GpuIndexBinaryFlat(res, self.index)

now, while searching the gpu becomes 100% and the code crashes,

i tried with small index of 1 mb, its the same.

I am using python3.7, faiss-gpu latest version

**Comment by mdouze** [comment]
please post a short self-contained reproduction script
