### ISSUE TITLE
How to exclude some index during search

### ISSUE THREAD

**Issue by TerryLiu18** [facebookresearch/faiss#2387]
Let's say we have an index trained already, now I want to query a vector of size (1, 128), from a matrix of size (100,000,000, 128). Meanwhile, I have already filtered out some index, so my candidate index number is only about 100,000.

Basically what I am trying to implement is:
```
Index = faiss.index_factory(d, xxx)
new_index = index[candidate_indices]   # of course this is not subscriptable
D, I = new_index.search(query, 100)
```
Is there any possible way to realize that? Thank you in advance!

**Comment by mdouze** [comment]
Working on it https://github.com/facebookresearch/faiss/pull/2483

**Comment by TerryLiu18** [comment]
Nice work! This is a useful function I think vector search library should add. I have also been thinking about some solution these days. Looking forward to it!

**Comment by TerryLiu18** [comment]
> Working on it #2483

Nice work! This is a useful function I think vector search library should add. I have also been thinking about some solution these days. Looking forward to it!

**Comment by ShubhamSalokhe** [comment]
```
import numpy as np
import faiss

filter_out_ids = [154, 172, 146]
filter_ids  = [id_ for id_ in range(index_interval.ntotal) if id_ not in filter_out_ids]

id_selector = faiss.IDSelectorArray(filter_ids)

xq:np.ndarray # shape : (d, )
k= 5
filtered_distances, filtered_indices = index_interval.search(xq.reshape(1,-1), k, params=faiss.SearchParametersIVF(sel=id_selector))
```

**Comment by 999jmsx** [comment]
Can IndexIDMap support id_selector when searching?
I tried to do it this way, but I got the following error:
RuntimeError: Error in void faiss::IndexIDMapTemplate<IndexT>::search(faiss::IndexIDMapTemplate<IndexT>::idx_t, const typename IndexT::component_t*, faiss::IndexIDMapTemplate<IndexT>::idx_t, typename IndexT::distance_t*, typename IndexT::idx_t*, const faiss::SearchParameters*) const [with IndexT = faiss::Index; faiss::IndexIDMapTemplate<IndexT>::idx_t = long int; typename IndexT::component_t = float; typename IndexT::distance_t = float; typename IndexT::idx_t = long int] at /project/faiss/faiss/IndexIDMap.cpp:82: Error: '!params' failed: search params not supported for this index

**Comment by Charlyo** [comment]
Still happening. Would 100% love to be able to filter in indexmap based indexs.
