### ISSUE TITLE
Can someone give me some examples codes of faiss?

### ISSUE THREAD

**Issue by opentld** [facebookresearch/faiss#239]
I have compiled faiss and run 1-Flat  2-IVFFlat  3-IVFPQ  and demo_sift1M examples, but I need to use faiss for image search, that is, given an image file from some image files Data set to search, get the highest confidence image file from the data set.

Can someone provide C ++ code for image search? Thanks a lot!

**Comment by mdouze** [comment]
Hi, 
You will need to extract image descriptors from the images, Faiss is not doing that. 
You may want to use OpenCV or Caffe to extract the image descriptors.

**Comment by opentld** [comment]
Thank you very much for your help!
I carefully read the tutorial codes again,  the following is my understanding, I do not know whether it is correct:
1, use SIFT / SURF / ORB to extract the eigenvector of the image dataset , put them into the xb array, and then create the faiss :: IndexFlatL2 index, add xb to the index;
2, for the images to be retrieved, also create the eigenvector array xq;
3, using index.search (nq, xq, k, D, I) to retrieve, get the nearest image vector.

But I still have a problem, using SIFT to extract the feature vector,may have 2000 dimensions or more,does faiss supports such a high dimension?

Thanks again for your help!

James Michael

**Comment by honghande** [comment]
@opentld Open CV feature vectors such as surf and sift have been extracted. How to use faiss for vector index? Do you have any reference cases? Thank you!
