### ISSUE TITLE
Repeatly searching within a batch

### ISSUE THREAD

**Issue by RitchieQi** [facebookresearch/faiss#2394]
# Summary

Hi there, I'm pretty new to faiss. I was trying to search nearest points for every centroid-set in a mini-batch from a larger pointcloud. There is my implementation:
```python 
import faiss
res = faiss.StandardGpuResources()
index_flat = faiss.IndexFlatL2(3)

for i,centroids in enumerate(batch):
    gpu_index_flat = faiss.index_cpu_to_gpu(res, 0, index_flat)
    gpu_index_flat.add(pointcloud[i].cpu().numpy()) # pointcloud(1024,3)
    D, I = gpu_index_flat.search(centroids.cpu().detach().numpy(), 64) #centroids(n,3) I(n,64)
    del gpu_index_flat
```
I just feel weird that I have to delete the index from GPU everytime and move another one from CPU. Is there any other better solution? like some auto-iterator?  Thanks in advance.

# Platform

x86_64

OS: Ubuntu18.04

Faiss version: 1.7.2

Installed from: conda

Faiss compilation options: conda install -c pytorch faiss-gpu

Running on:
- [ ] CPU
- [X] GPU

Interface: 
- [ ] C++
- [X] Python

**Comment by mdouze** [comment]
For this use case It's probably better to not use an index:
https://github.com/facebookresearch/faiss/wiki/Brute-force-search-without-an-index#brute-force-search-on-gpu
see also 
https://github.com/facebookresearch/faiss/wiki/Faiss-on-the-GPU#passing-in-pytorch-tensors

**Comment by RitchieQi** [comment]
> For this use case It's probably better to not use an index: https://github.com/facebookresearch/faiss/wiki/Brute-force-search-without-an-index#brute-force-search-on-gpu see also https://github.com/facebookresearch/faiss/wiki/Faiss-on-the-GPU#passing-in-pytorch-tensors

Thanks for the answer! I'll give it a go.

**Comment by RitchieQi** [comment]
> For this use case It's probably better to not use an index: https://github.com/facebookresearch/faiss/wiki/Brute-force-search-without-an-index#brute-force-search-on-gpu see also https://github.com/facebookresearch/faiss/wiki/Faiss-on-the-GPU#passing-in-pytorch-tensors

Thanks for the answer! I'll give it a go.

**Comment by RitchieQi** [comment]
No more help needed, Thanks. Close issue.
