### ISSUE TITLE
GPU resource vector not found

### ISSUE THREAD

**Issue by FatimaArshad-DS** [facebookresearch/faiss#2397]
Hi everyone,

I installed FAISS using:
pip install faiss-gpu
conda install faiss-gpu cudatoolkit=11 -c pytorch --y

However, it is giving following error:
NameError                                 Traceback (most recent call last)
/tmp/ipykernel_11042/297671848.py in <module>
----> 1 build_index(sap_model_cfg, sap_model.to(device))
      2 build_index(base_model_cfg, base_model.to(device))

/tmp/ipykernel_11042/1132246397.py in build_index(cfg, model)
     10     quantizer = faiss.IndexFlatL2(cfg.index.dims)
     11     index = faiss.IndexIVFFlat(quantizer, cfg.index.dims, cfg.index.nlist)
---> 12     index = faiss.index_cpu_to_all_gpus(index)
     13     index.train(embeddings)
     14 

~/miniconda3/envs/aemap/lib/python3.7/site-packages/faiss/__init__.py in index_cpu_to_all_gpus(index, co, ngpu)
    885 
    886 def index_cpu_to_all_gpus(index, co=None, ngpu=-1):
--> 887     index_gpu = index_cpu_to_gpus_list(index, co=co, gpus=None, ngpu=ngpu)
    888     return index_gpu
    889 

~/miniconda3/envs/aemap/lib/python3.7/site-packages/faiss/__init__.py in index_cpu_to_gpus_list(index, co, gpus, ngpu)
    897         gpus = range(ngpu)
    898     res = [StandardGpuResources() for _ in gpus]
--> 899     index_gpu = index_cpu_to_gpu_multiple_py(res, index, co, gpus)
    900     return index_gpu
    901 

~/miniconda3/envs/aemap/lib/python3.7/site-packages/faiss/__init__.py in index_cpu_to_gpu_multiple_py(resources, index, co, gpus)
    875     if gpus is None:
    876         gpus = range(len(resources))
--> 877     vres = GpuResourcesVector()
    878     vdev = Int32Vector()
    879     for i, res in zip(gpus, resources):

NameError: name 'GpuResourcesVector' is not defined

Im using Ubuntu 16 and Python 3.7.

**Comment by mdouze** [comment]
Please use conda to install Faiss (not pip)

**Comment by Mohit-robo** [comment]
uninstall all the previously install `faiss` packages.
`pip install faiss-gpu=1.6.3` worked for me, check for the version.
