### ISSUE TITLE
Tensorflow inception3 integration

### ISSUE THREAD

**Issue by iNDicat0r** [facebookresearch/faiss#24]
I have got a set of 10k images and extract their features using the inception v3 model with tensorflow. 
I use spatial.distance.cdist() from scipy to perform the knn, and i am wondering if faiss can be integrated or even replaced with my current approach.

Regards

**Comment by mdouze** [comment]
Hi, 

I guess you are doing `cdist` then `argmax` over the the lines of the distance matrix. 

Faiss should be able to do this in a way that is less prone to memory overflows. You can use an `IndexFlatL2` which is equivalent to `cdist`'s `'sqeuclidean'`.

**Comment by iNDicat0r** [comment]
Ok thanks. Is there any limitation with the number of dimentions of the vectors in Faiss? Google's inception model feature extraction for each image gets you a high dimentional vector, i dont recall its exact size but it was mentioned that applying knn to the feature set output isnt a good idea.

**Comment by mdouze** [comment]
Hi, 

Please try it out. There is no arbitrary limit on the dimension.
