### ISSUE TITLE
some error with compiling the python interface

### ISSUE THREAD

**Issue by zhiminfeng** [facebookresearch/faiss#240]
when I ran make py, it occur some errors . I had update the swig to 3.0+ version , and don't know how to solve these problem

$ make py
g++ -I. -fPIC -m64 -Wall -g -O3 -mavx -msse4 -mpopcnt -fopenmp -Wno-sign-compare -std=c++11 -fopenmp -g -fPIC  -fopenmp -I/home/bigdata/python2.7/include/python2.7/ -I/home/bigdata/python2.7/lib/python2.7/site-packages/numpy/core/include -shared \
        -o python/_swigfaiss.so python/swigfaiss_wrap.cxx libfaiss.a /usr/lib64/libopenblas.so.0
python/swigfaiss_wrap.cxx: In function ‘PyObject* _wrap_BufferList_buffers_set(PyObject*, PyObject*)’:
python/swigfaiss_wrap.cxx:50608:16: error: ‘Buffer’ was not declared in this scope
   std::vector< Buffer > *arg2 = (std::vector< Buffer > *) 0 ;
                ^
python/swigfaiss_wrap.cxx:50608:23: error: template argument 1 is invalid
   std::vector< Buffer > *arg2 = (std::vector< Buffer > *) 0 ;
                       ^
python/swigfaiss_wrap.cxx:50608:23: error: template argument 2 is invalid
python/swigfaiss_wrap.cxx:50608:31: error: invalid type in declaration before ‘=’ token
   std::vector< Buffer > *arg2 = (std::vector< Buffer > *) 0 ;
                               ^
python/swigfaiss_wrap.cxx:50608:47: error: the value of ‘Buffer’ is not usable in a constant expression
   std::vector< Buffer > *arg2 = (std::vector< Buffer > *) 0 ;
                                               ^
python/swigfaiss_wrap.cxx:50608:16: note: ‘Buffer’ was not declared ‘constexpr’
   std::vector< Buffer > *arg2 = (std::vector< Buffer > *) 0 ;
                ^
python/swigfaiss_wrap.cxx:50608:54: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp, class _Alloc> class std::vector’
   std::vector< Buffer > *arg2 = (std::vector< Buffer > *) 0 ;
                                                      ^
python/swigfaiss_wrap.cxx:50608:54: error:   expected a type, got ‘Buffer’
python/swigfaiss_wrap.cxx:50608:54: error: template argument 2 is invalid
python/swigfaiss_wrap.cxx:50608:57: error: expected primary-expression before ‘)’ token
   std::vector< Buffer > *arg2 = (std::vector< Buffer > *) 0 ;
                                                         ^
python/swigfaiss_wrap.cxx:50626:41: error: the value of ‘Buffer’ is not usable in a constant expression
   arg2 = reinterpret_cast< std::vector< Buffer > * >(argp2);
                                         ^
python/swigfaiss_wrap.cxx:50608:16: note: ‘Buffer’ was not declared ‘constexpr’
   std::vector< Buffer > *arg2 = (std::vector< Buffer > *) 0 ;
                ^
python/swigfaiss_wrap.cxx:50626:48: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp, class _Alloc> class std::vector’
   arg2 = reinterpret_cast< std::vector< Buffer > * >(argp2);
                                                ^
python/swigfaiss_wrap.cxx:50626:48: error:   expected a type, got ‘Buffer’
python/swigfaiss_wrap.cxx:50626:48: error: template argument 2 is invalid
python/swigfaiss_wrap.cxx:50626:50: error: expected ‘>’ before ‘*’ token
   arg2 = reinterpret_cast< std::vector< Buffer > * >(argp2);
                                                  ^
python/swigfaiss_wrap.cxx:50626:50: error: expected ‘(’ before ‘*’ token
python/swigfaiss_wrap.cxx:50626:52: error: expected primary-expression before ‘>’ token
   arg2 = reinterpret_cast< std::vector< Buffer > * >(argp2);
                                                    ^
python/swigfaiss_wrap.cxx:50626:60: error: expected ‘)’ before ‘;’ token
   arg2 = reinterpret_cast< std::vector< Buffer > * >(argp2);
                                                            ^
python/swigfaiss_wrap.cxx:50627:29: error: no match for ‘operator=’ (operand types are ‘std::vector<faiss::BufferList::Buffer>’ and ‘int’)
   if (arg1) (arg1)->buffers = *arg2;
                             ^
python/swigfaiss_wrap.cxx:50627:29: note: candidates are:
In file included from /usr/local/include/c++/4.8.2/vector:69:0,
                 from ./IndexFlat.h:15,
                 from python/swigfaiss_wrap.cxx:2929:
/usr/local/include/c++/4.8.2/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = faiss::BufferList::Buffer; _Alloc = std::allocator<faiss::BufferList::Buffer>]
     vector<_Tp, _Alloc>::
     ^
/usr/local/include/c++/4.8.2/bits/vector.tcc:160:5: note:   no known conversion for argument 1 from ‘int’ to ‘const std::vector<faiss::BufferList::Buffer>&’
In file included from /usr/local/include/c++/4.8.2/vector:64:0,
                 from ./IndexFlat.h:15,
                 from python/swigfaiss_wrap.cxx:2929:
/usr/local/include/c++/4.8.2/bits/stl_vector.h:439:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = faiss::BufferList::Buffer; _Alloc = std::allocator<faiss::BufferList::Buffer>]
       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
       ^
/usr/local/include/c++/4.8.2/bits/stl_vector.h:439:7: note:   no known conversion for argument 1 from ‘int’ to ‘std::vector<faiss::BufferList::Buffer>&&’
/usr/local/include/c++/4.8.2/bits/stl_vector.h:461:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = faiss::BufferList::Buffer; _Alloc = std::allocator<faiss::BufferList::Buffer>]
       operator=(initializer_list<value_type> __l)
       ^
/usr/local/include/c++/4.8.2/bits/stl_vector.h:461:7: note:   no known conversion for argument 1 from ‘int’ to ‘std::initializer_list<faiss::BufferList::Buffer>’
python/swigfaiss_wrap.cxx: In function ‘PyObject* _wrap_BufferList_buffers_get(PyObject*, PyObject*)’:
python/swigfaiss_wrap.cxx:50641:16: error: ‘Buffer’ was not declared in this scope
   std::vector< Buffer > *result = 0 ;
                ^
python/swigfaiss_wrap.cxx:50641:23: error: template argument 1 is invalid
   std::vector< Buffer > *result = 0 ;
                       ^
python/swigfaiss_wrap.cxx:50641:23: error: template argument 2 is invalid
python/swigfaiss_wrap.cxx:50641:33: error: invalid type in declaration before ‘=’ token
   std::vector< Buffer > *result = 0 ;
                                 ^
python/swigfaiss_wrap.cxx:50649:26: error: the value of ‘Buffer’ is not usable in a constant expression
   result = (std::vector< Buffer > *)& ((arg1)->buffers);
                          ^
python/swigfaiss_wrap.cxx:50641:16: note: ‘Buffer’ was not declared ‘constexpr’
   std::vector< Buffer > *result = 0 ;
                ^
python/swigfaiss_wrap.cxx:50649:33: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp, class _Alloc> class std::vector’
   result = (std::vector< Buffer > *)& ((arg1)->buffers);
                                 ^
python/swigfaiss_wrap.cxx:50649:33: error:   expected a type, got ‘Buffer’
python/swigfaiss_wrap.cxx:50649:33: error: template argument 2 is invalid
python/swigfaiss_wrap.cxx:50649:36: error: expected primary-expression before ‘)’ token
   result = (std::vector< Buffer > *)& ((arg1)->buffers);
                                    ^
python/swigfaiss_wrap.cxx: In function ‘PyObject* _wrap_RangeSearchPartialResult_queries_set(PyObject*, PyObject*)’:
python/swigfaiss_wrap.cxx:50953:16: error: ‘QueryResult’ was not declared in this scope
   std::vector< QueryResult > *arg2 = (std::vector< QueryResult > *) 0 ;
                ^
python/swigfaiss_wrap.cxx:50953:28: error: template argument 1 is invalid
   std::vector< QueryResult > *arg2 = (std::vector< QueryResult > *) 0 ;
                            ^
python/swigfaiss_wrap.cxx:50953:28: error: template argument 2 is invalid
python/swigfaiss_wrap.cxx:50953:36: error: invalid type in declaration before ‘=’ token
   std::vector< QueryResult > *arg2 = (std::vector< QueryResult > *) 0 ;
                                    ^
python/swigfaiss_wrap.cxx:50953:52: error: the value of ‘QueryResult’ is not usable in a constant expression
   std::vector< QueryResult > *arg2 = (std::vector< QueryResult > *) 0 ;
                                                    ^
python/swigfaiss_wrap.cxx:50953:16: note: ‘QueryResult’ was not declared ‘constexpr’
   std::vector< QueryResult > *arg2 = (std::vector< QueryResult > *) 0 ;
                ^
python/swigfaiss_wrap.cxx:50953:64: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp, class _Alloc> class std::vector’
   std::vector< QueryResult > *arg2 = (std::vector< QueryResult > *) 0 ;
                                                                ^
python/swigfaiss_wrap.cxx:50953:64: error:   expected a type, got ‘QueryResult’
python/swigfaiss_wrap.cxx:50953:64: error: template argument 2 is invalid
python/swigfaiss_wrap.cxx:50953:67: error: expected primary-expression before ‘)’ token
   std::vector< QueryResult > *arg2 = (std::vector< QueryResult > *) 0 ;
                                                                   ^
python/swigfaiss_wrap.cxx:50971:41: error: the value of ‘QueryResult’ is not usable in a constant expression
   arg2 = reinterpret_cast< std::vector< QueryResult > * >(argp2);
                                         ^
python/swigfaiss_wrap.cxx:50953:16: note: ‘QueryResult’ was not declared ‘constexpr’
   std::vector< QueryResult > *arg2 = (std::vector< QueryResult > *) 0 ;
                ^
python/swigfaiss_wrap.cxx:50971:53: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp, class _Alloc> class std::vector’
   arg2 = reinterpret_cast< std::vector< QueryResult > * >(argp2);
                                                     ^
python/swigfaiss_wrap.cxx:50971:53: error:   expected a type, got ‘QueryResult’
python/swigfaiss_wrap.cxx:50971:53: error: template argument 2 is invalid
python/swigfaiss_wrap.cxx:50971:55: error: expected ‘>’ before ‘*’ token
   arg2 = reinterpret_cast< std::vector< QueryResult > * >(argp2);
                                                       ^
python/swigfaiss_wrap.cxx:50971:55: error: expected ‘(’ before ‘*’ token
python/swigfaiss_wrap.cxx:50971:57: error: expected primary-expression before ‘>’ token
   arg2 = reinterpret_cast< std::vector< QueryResult > * >(argp2);
                                                         ^
python/swigfaiss_wrap.cxx:50971:65: error: expected ‘)’ before ‘;’ token
   arg2 = reinterpret_cast< std::vector< QueryResult > * >(argp2);
                                                                 ^
python/swigfaiss_wrap.cxx:50972:29: error: no match for ‘operator=’ (operand types are ‘std::vector<faiss::RangeSearchPartialResult::QueryResult>’ and ‘int’)
   if (arg1) (arg1)->queries = *arg2;
                             ^
python/swigfaiss_wrap.cxx:50972:29: note: candidates are:
In file included from /usr/local/include/c++/4.8.2/vector:69:0,
                 from ./IndexFlat.h:15,
                 from python/swigfaiss_wrap.cxx:2929:
/usr/local/include/c++/4.8.2/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = faiss::RangeSearchPartialResult::QueryResult; _Alloc = std::allocator<faiss::RangeSearchPartialResult::QueryResult>]
     vector<_Tp, _Alloc>::
     ^
/usr/local/include/c++/4.8.2/bits/vector.tcc:160:5: note:   no known conversion for argument 1 from ‘int’ to ‘const std::vector<faiss::RangeSearchPartialResult::QueryResult>&’
In file included from /usr/local/include/c++/4.8.2/vector:64:0,
                 from ./IndexFlat.h:15,
                 from python/swigfaiss_wrap.cxx:2929:
/usr/local/include/c++/4.8.2/bits/stl_vector.h:439:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = faiss::RangeSearchPartialResult::QueryResult; _Alloc = std::allocator<faiss::RangeSearchPartialResult::QueryResult>]
       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
       ^
/usr/local/include/c++/4.8.2/bits/stl_vector.h:439:7: note:   no known conversion for argument 1 from ‘int’ to ‘std::vector<faiss::RangeSearchPartialResult::QueryResult>&&’
/usr/local/include/c++/4.8.2/bits/stl_vector.h:461:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = faiss::RangeSearchPartialResult::QueryResult; _Alloc = std::allocator<faiss::RangeSearchPartialResult::QueryResult>]
       operator=(initializer_list<value_type> __l)
       ^
/usr/local/include/c++/4.8.2/bits/stl_vector.h:461:7: note:   no known conversion for argument 1 from ‘int’ to ‘std::initializer_list<faiss::RangeSearchPartialResult::QueryResult>’
python/swigfaiss_wrap.cxx: In function ‘PyObject* _wrap_RangeSearchPartialResult_queries_get(PyObject*, PyObject*)’:
python/swigfaiss_wrap.cxx:50986:16: error: ‘QueryResult’ was not declared in this scope
   std::vector< QueryResult > *result = 0 ;
                ^
python/swigfaiss_wrap.cxx:50986:28: error: template argument 1 is invalid
   std::vector< QueryResult > *result = 0 ;
                            ^
python/swigfaiss_wrap.cxx:50986:28: error: template argument 2 is invalid
python/swigfaiss_wrap.cxx:50986:38: error: invalid type in declaration before ‘=’ token
   std::vector< QueryResult > *result = 0 ;
                                      ^
python/swigfaiss_wrap.cxx:50994:26: error: the value of ‘QueryResult’ is not usable in a constant expression
   result = (std::vector< QueryResult > *)& ((arg1)->queries);
                          ^
python/swigfaiss_wrap.cxx:50986:16: note: ‘QueryResult’ was not declared ‘constexpr’
   std::vector< QueryResult > *result = 0 ;
                ^
python/swigfaiss_wrap.cxx:50994:38: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp, class _Alloc> class std::vector’
   result = (std::vector< QueryResult > *)& ((arg1)->queries);
                                      ^
python/swigfaiss_wrap.cxx:50994:38: error:   expected a type, got ‘QueryResult’
python/swigfaiss_wrap.cxx:50994:38: error: template argument 2 is invalid
python/swigfaiss_wrap.cxx:50994:41: error: expected primary-expression before ‘)’ token
   result = (std::vector< QueryResult > *)& ((arg1)->queries);
                                         ^
python/swigfaiss_wrap.cxx: In function ‘PyObject* _wrap_RangeSearchPartialResult_new_result(PyObject*, PyObject*)’:
python/swigfaiss_wrap.cxx:51012:3: error: ‘QueryResult’ was not declared in this scope
   QueryResult *result = 0 ;
   ^
python/swigfaiss_wrap.cxx:51012:16: error: ‘result’ was not declared in this scope
   QueryResult *result = 0 ;
                ^
python/swigfaiss_wrap.cxx:51025:26: error: expected primary-expression before ‘)’ token
   result = (QueryResult *) &(arg1)->new_result(arg2);
                          ^
make: *** [python/_swigfaiss.so] Error 1

**Comment by mdouze** [comment]
Hi 
We can't repro this. What about using 

https://github.com/facebookresearch/faiss/blob/master/python/swigfaiss_wrap.cxx

included with the package?

**Comment by mdouze** [comment]
Closing.
