### ISSUE TITLE
Can I search only the specified group when using IndexIVF 

### ISSUE THREAD

**Issue by lynnliu030** [facebookresearch/faiss#2403]
The IndexIVF class (and its children) is used for all large-scale applications of Faiss. It clusters all input vectors into nlist groups (nlist is a field of IndexIVF). 
I was wondering, when doing search on an IVF index using the python interface, is it possible to specifiy the group id and only scan exhaustively all the vectors within this group? i.e. can I skip the step to find the closest nprobe groups and instead specify the group ids that I want to search on?

**Comment by mdouze** [comment]
Please use the contrib function search_preassigned

https://github.com/facebookresearch/faiss/blob/151e3d7be54aec844b6328dc3e7dd0b83fcfa5bc/contrib/ivf_tools.py#L26
