### ISSUE TITLE
Faiss assertion 'centroidDistances.getSize(0) == productDistances.getSize(1)' failed

### ISSUE THREAD

**Issue by LiaoSS07** [facebookresearch/faiss#2404]
# Summary

Faiss assertion 'centroidDistances.getSize(0) == productDistances.getSize(1)' failed in void faiss::gpu::runL2SelectMin(faiss::gpu::Tensor<T, 2, true>&, faiss::gpu::Tensor<T, 1, true>&,  faiss::gpu::Tensor<T, 2, true>&, faiss::gpu::Tensor<int, 2, true>&, int, cudaStream_t) [with T = float; cudaStream_t = CUstream_st*] at gpu/impl/L2Select.cu:172
OS: 
ubuntu 18.04.3 LTS
Faiss version: 
faiss 1.7.2(#2384)

Installed from: 
compiled by myself

Faiss compilation options: 
cmake -B build -DFAISS_ENABLE_GPU=ON
                -DFAISS_ENABLE_PYTHON=ON
                -DBUILD_TESTING=OFF
                -DBUILD_SHARED_LIBS=ON
                -DCMAKE_BUILD_TYPE=Release
                -DCUDAToolkit_ROOT=/usr/local/cuda-10.1
                -DCMAKE_CUDA_ARCHITECTURES="75;72"
                -DPython_EXECUTABLE=/usr/bin/python3.7

Running on:
GPU

Interface:
Python

# Reproduction instructions

my code:
my_index = fiass.index_factory(512, "IDMap,Flat")
my_index.add_with_ids(my_features, ids)
res = my_index.search(feature_querry, top_n)

note:
my_features.shape[0] = 200k
TPS: ~5

In this case, the following problem will be prompted：
Faiss assertion 'centroidDistances.getSize(0) == productDistances.getSize(1)' failed in void faiss::gpu::runL2SelectMin(faiss::gpu::Tensor<T, 2, true>&, faiss::gpu::Tensor<T, 1, true>&, faiss::gpu::Tensor<T, 2, true>&, faiss::gpu::Tensor<int, 2, true>&, int, cudaStream_t) [with T = float; cudaStream_t = CUstream_st*] at gpu/impl/L2Select.cu:172

Faiss with other version also has the same question.

**Comment by mdouze** [comment]
The code is incomplete. 
The error message is weird because there are no centroids in the indexes used here.
