### ISSUE TITLE
How to capture the output of faiss.OperationPoints().display() to file?

### ISSUE THREAD

**Issue by Beau-Yang** [facebookresearch/faiss#2406]
Hello, I'm confronted with a problem when trying to save the output of `faiss.OperationPoints().display()` to a log file. Hope you can help me solve this. Thanks in advance.

It seems that the code `faiss.OperationPoints().display()` prints the description on stdout. So I try these two ways to capture the output.

```python
op = faiss.OperationPoints()
sys.stdout = open(filename, "a")
op.display()
```

and

```python
with open(filename, "a") as f:
    with contextlib.redirect_stdout(f):
        op.display()
```

However, both two ways don't work. The output still shows in the console instead of the file. The only way that works is to redirect the output stream in the console.

```bash
python main.py > a.log
```

But I want to seek a more direct way of code so that I can save the output to the file instead of running the python file in the console every time. 

By the way, I also tried to replace the `stdout` with `stderr` but it didn't work either.

- OS: Archlinux
- Faiss version: 1.7.2

Interface: 
- Python

**Comment by mdouze** [comment]
Yes that's because some error messages and functions directly use the printf routine in C. 
The best to do here is to manually get the operating points in python. 

See example here: 
https://github.com/facebookresearch/faiss/blob/151e3d7be54aec844b6328dc3e7dd0b83fcfa5bc/demos/demo_auto_tune.py#L36
