### ISSUE TITLE
How are HNSW and PQ combined in HNSWPQ?

### ISSUE THREAD

**Issue by calvinmccarter** [facebookresearch/faiss#2411]
How exactly are HNSW and PQ combined in HNSWPQ? I suspect that vectors are PQ-encoded, and HNSW builds a graph over these PQ-encoded vectors, ie HNSW(PQ(x)). Is this correct? 

Or, is PQ somehow applied to HNSW residuals? Or, is HNSW somehow applied to PQ subspaces? 

Apologies if I missed an answer to this in the documentation!

**Comment by mdouze** [comment]
yes the first explanation. 
See here for more details: 
https://openaccess.thecvf.com/content_cvpr_2018/html/Douze_Link_and_Code_CVPR_2018_paper.html
