### ISSUE TITLE
How to visualize the progress of several faiss functions?

### ISSUE THREAD

**Issue by Yb-Z** [facebookresearch/faiss#2414]
# Summary

# Platform 

 

OS:  Linux Ubuntu 18.04 LTS

Faiss version:  1.7.2

Installed from:  pip install faiss-gpu

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

 

Hi, is there any way to visualize the progress of faiss functions e.g., search, index_gpu_to_cpu and write_index?

For example, can we use faiss with tqdm?

Thank you for your help!

**Comment by mdouze** [comment]
No the Faiss functions are viewed as atomic from the python side. 
If you want to follow the progress of a search  search, it's simple to batch queries.
