### ISSUE TITLE
PackagesNotFoundError: The following packages are not available from current channels:    - faiss-gpu

### ISSUE THREAD

**Issue by zeliangDing** [facebookresearch/faiss#2416]
when i use :  conda install faiss-gpu
occur: 
PackagesNotFoundError: The following packages are not available from current channels:    - faiss-gpu

**Comment by mdouze** [comment]
please use `-c pytorch`

**Comment by LuDaPiaoLiang** [comment]
after adding -c pytorch, it still report this error, what to do?

**Comment by ufodriverr** [comment]
Same issue:
My CMD:
conda install faiss-gpu -c pytorch -c nvidia

Error:
PackagesNotFoundError: The following packages are not available from current channels:

  - faiss-gpu

Current channels:

  - https://conda.anaconda.org/pytorch/win-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://conda.anaconda.org/nvidia/win-64
  - https://conda.anaconda.org/nvidia/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
