### ISSUE TITLE
Potential resource leak (file not closed)

### ISSUE THREAD

**Issue by ilikesearch** [facebookresearch/faiss#2427]
There might be a resource leak in function `OnDiskInvertedLists::do_mmap`. The file is not closed when `mmap` fails.

**Comment by mdouze** [comment]
Did you check the relevant code?

**Comment by ilikesearch** [comment]
Yes, the relevant code is pretty simple, just several lines of code.

**Comment by AbdelrahmanElmeniawy** [comment]
This issue got fixed 👍
