### ISSUE TITLE
Make Faiss support python > 3.8

### ISSUE THREAD

**Issue by jonporterjones** [facebookresearch/faiss#2431]
# Faiss on Python only support 3.6-3.8

This request is to make it work for python 3.10 (might as well include 3.9).

Running on:
- [ x] CPU
- [ x] GPU

Interface: 
- [ ] C++
- [x ] Python

To reproduce:
Try to pip or conda install faiss on python 3.10

**Comment by mdouze** [comment]
we'll consider it.

**Comment by vrdn-23** [comment]
Hey, 
Is this something that is still being considered? It would be a great help to the community if we can keep up with the latest Python versions

**Comment by mlomeli1** [comment]
1.7.4 is compatible with 3.10 @vrdn-23
