### ISSUE TITLE
Strange GPU memory usage

### ISSUE THREAD

**Issue by netw0rkf10w** [facebookresearch/faiss#2438]
# Summary

I observe a "strange" GPU memory usage so I would like to ask if this is expected behaviors.

I use the following code to perform K-Means on my data represented by an array `X` of shape `(N, 192)`:

```python
    kmeans = faiss.Kmeans(X.shape[-1], K, niter=20, gpu=True, max_points_per_centroid=int(1e7))
    kmeans.train(X)
```

where `K` is 1e4 or 2e4.

When launching the training on a server with 8 GPUs:

- If N = 784e4 and K = 1e4, then each GPU consumes 2385MB.
- If I increase the number of clusters to K = 2e4, then GPU consumption only slightly increases: 2393MB per GPU. Is this normal?
- If I increase the number of data points by ten times, i.e., N = 784e5 and K = 1e4, then only 2385MB per GPU. Why is the number of data points irrelevant?

I'm asking these questions to make sure that all my data were actually used for the training.

Thank you very much in advance for your responses!

Best regards.

# Platform

Installed from: anaconda  

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by mdouze** [comment]
The training set is processed by batches, so the size of the training set is largely irrelevant to GPU mem usage. 
If you want to be absolutely confident that data has been used for training, you can strategically insert a few NaN values in the input ;-)

**Comment by mdouze** [comment]
Well the limiting factor of k-means is computation not IO or bandwidth so the 32GB will be useless in this case I'm afraid.

**Comment by netw0rkf10w** [comment]
Thanks, @mdouze!
