### ISSUE TITLE
How to generate random hyperplane LSH

### ISSUE THREAD

**Issue by samhuang17** [facebookresearch/faiss#2440]
# Summary

I wanted to create, say 16 different set of 8 random hyperplanes to hash a target x.
However, if I initiate a new instance of faiss.IndexLSH and faiss.IndexLSH.add(x), then do search, the same nearest neighbors are found, so obviously the 16 instances of faiss.IndexLSH used the same hashed functions.
This may be optimal for some purposes, but is there a way to generate vanilla random hyperplane hash functions?

# Platform

OS: macOS 12.3.1 

Faiss version: 1.7.2 

Installed from: conda  

Faiss compilation options: 

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

```
q_vecs = np.random.normal(size=(10, 300)).astype("float32")
for _ in range(16):
    RP = faiss.IndexLSH(300, 8)
    RP.add(x)
    _, I = RP.search(q_vecs, 10)
    print(I)
```
Then all the outputs are the same.

**Comment by mdouze** [comment]
The random seed can be changed via 

```
RP.rrot.init(seed) 
```

where seed is an integer.
