### ISSUE TITLE
Specifying GPU ID

### ISSUE THREAD

**Issue by kwonmha** [facebookresearch/faiss#2452]
# Summary

I have 4 GPUs on my server and I want faiss to use only one GPU that I specified.
How can set the id of GPU that faiss will use?

These are what I tried.
```
gpu_config = faiss.GpuIndexFlatConfig()
gpu_config.device = 1  # The ID of the GPU
resource = faiss.StandardGpuResources()
index = faiss.GpuIndexFlatIP(resource, dim, gpu_config)

```
```
resource = faiss.StandardGpuResources()
index = faiss.IndexFlatIP(dim)
index = faiss.index_cpu_to_gpu(resource, 1, index) # 1 as ID

```
I got same error messages for both trials.
```
Faiss assertion 'err__ == cudaSuccess' failed in int faiss::gpu::getNumDevices() at /root/miniconda3/conda-bld/faiss-pkg_1641228905850/work/faiss/gpu/utils/DeviceUtils.cu:36; details: CUDA error 3 initialization error
```

The successful one is the combination of the code below
```
index = faiss.IndexFlatIP(dim)
index = faiss.index_cpu_to_all_gpus(index)
```
with command
`CUDA_VISIBLE_DEVICES=1 python myprogram.py`

# Platform

OS: Rocky Linux 9.0

Faiss version: 1.7.2

Installed from: pip

Running on:
- [ ] CPU
- [O] GPU

Interface: 
- [ ] C++
- [O] Python

**Comment by mdouze** [comment]
It works for me. Please check your install

https://gist.github.com/mdouze/dc4d2e629c2098e6a7e5be458d3f7056

**Comment by kwonmha** [comment]
Thanks, it worked.
The cuda version of installed faiss mismatched with that of my server.

But another issue with the same code came out.

`RuntimeError: Error in virtual void faiss::gpu::StandardGpuResourcesImpl::initializeForDevice(int) at /root/miniconda3/conda-bld/faiss-pkg_1639741185190/work/faiss/gpu/StandardGpuResources.cpp:283: Error: 'err == cudaSuccess' failed: failed to cudaHostAlloc 268435456 bytes for CPU <-> GPU async copy buffer (error 2 out of memory)`

This doesn't occur when I run the codes on your gist independently.
But It occurs when the codes are inserted between other codes and also GPU 0 is allocated for other process.
If GPU0 is free, I can run my program with the codes.

This looks hard to reproduce but if you have any suggestions, let me know.
Thanks.
