### ISSUE TITLE
How to fix warnings called No-value-for-parameter

### ISSUE THREAD

**Issue by DrewdropLife** [facebookresearch/faiss#2453]
# Summary

When I use pylint or write code in Pycharm, it got warnings called "No-value-for-parameter", I want to fix it. So what should I do? Thanks.

# Platform

OS:  Ubuntu 18.04.1 LTS

Faiss version:  1.6.3

Installed from:  pip

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

 

Warnings: No value for argument 'x' in method call (no-value-for-parameter)

```
index = faiss.IndexFlat(d)
index.add(data)  # warnings
# usage:
faiss.swigfaiss.IndexFlat def add(self,
        n: Any,
        x: Any) -> Any
```
Another case:
Warnings: No value for argument 'k' in method call (no-value-for-parameter)
Warnings: No value for argument 'distances' in method call (no-value-for-parameter)
Warnings: No value for argument 'labels' in method call (no-value-for-parameter)

```
search_distances, search_indexes = index.search(query_feature, k)  # warnings
# usage:
faiss.swigfaiss.IndexFlat def search(self,
           n: Any,
           x: Any,
           k: Any,
           distances: Any,
           labels: Any) -> Any

```

**Comment by mdouze** [comment]
Please use the template to submit an issue.

**Comment by DrewdropLife** [comment]
> Please use the template to submit an issue.

up

**Comment by mdouze** [comment]
Static analysis works well for the Faiss python interface because methods are replaced dynamically in 

https://github.com/facebookresearch/faiss/blob/main/faiss/python/__init__.py#L587

there is no easy fix for that.
