### ISSUE TITLE
How to check if an index was built using IDMaps?

### ISSUE THREAD

**Issue by rinze** [facebookresearch/faiss#2459]
Using Python: is there any way to check if an index was built using `add()` or `add_with_ids()`? I'm been browsing the documentation but I haven't been able to find the answer.

Thanks!

**Comment by mdouze** [comment]
There is no general way, for example because `add_with_ids(x, np.arange(len(x))` on an empty IVF index or IDMap will give exactly the same result as `add(x)`

**Comment by mdouze** [comment]
about the question in the title, see 
https://github.com/facebookresearch/faiss/wiki/Python-C---code-snippets#how-to-explore-the-contents-of-an-opaque-index

**Comment by rinze** [comment]
Ok, that makes sense. Thanks for your quick anser.
