### ISSUE TITLE
AttributeError: module 'faiss' has no attribute 'IndexFlatL2'

### ISSUE THREAD

**Issue by bird1235456** [facebookresearch/faiss#246]
![screen shot 2017-11-08 at 10 33 56 am](https://user-images.githubusercontent.com/7435346/32561134-1e49fa10-c471-11e7-9d8f-4ffe3e6a0a6e.png)

**Comment by jegou** [comment]
From the code, it looks like you have directly downloaded the github without installing Faiss, which requires a few installation steps (in particular compiling the C++ part). 

See installation instructions:
https://github.com/facebookresearch/faiss/blob/master/INSTALL.md

**Comment by saiveeranki9996** [comment]
I have the same error from FAISS that i import from langchain.vectorstores. Any suggestion?
