### ISSUE TITLE
Is there a way to obtain codebook in product quantization index?

### ISSUE THREAD

**Issue by SubjectNoi** [facebookresearch/faiss#2468]
# Summary

I want to get the trained codebook in IVFPQ (the data of 256 centroids of M lists), is there a convenient way by using python API?

# Platform

OS: Ubuntu 18.04 LTS

Faiss version: 2cd84aa66308143d00aa0f39ccf29cbf48d243a6

Installed from: source

Faiss compilation options: 

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
please use 
```
faiss.contrib.inspect_tools.get_pq_centroids(index.pq)
```

**Comment by SubjectNoi** [comment]
> please use
> 
> ```
> faiss.contrib.inspect_tools.get_pq_centroids(index.pq)
> ```

Thanks, I will try it
