### ISSUE TITLE
How to use merge_from in python

### ISSUE THREAD

**Issue by hengshanji** [facebookresearch/faiss#247]
I have many index files, how to merge them into one index?
I find a function merge_from ,how to use it to do merge index works?

**Comment by mdouze** [comment]
Hi 
Here is the doc: https://rawgit.com/facebookresearch/faiss/master/docs/html/structfaiss_1_1IndexIVF.html#a0f22cc237c30c935df5b6560aecf8f01

**Comment by hengshanji** [comment]
Thank you very much, i try it and it woks for IndexIVFFlat, IndexIVFPQ, that's enough.

**Comment by pasa13142** [comment]
@hengshan123 Hello, could you please share how you handle it on python ? :(

**Comment by oatmeal3000** [comment]
this link does not work any more, could the solution be pasted here?
