### ISSUE TITLE
Does FAISS support merging of flat indices?

### ISSUE THREAD

**Issue by avidale** [facebookresearch/faiss#2472]
# Summary

I try to train two `Flat` indices and then to merge them.
It fails. 
With `IVF` indices, however, it works. 

Is there any convenient way to merge Flat indices?

# Platform

OS: `Ubuntu 18.04.6 LTS`

Faiss version: `faiss-cpu-1.7.2`

Installed from: `pip`

Faiss compilation options: none (installed from pip)

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

my input:

```python
import faiss
import numpy as np

dim = 32
n = 100
np.random.seed(1)
data1 = np.random.random([n, dim]).astype(np.float32)
data2 = np.random.random([n, dim]).astype(np.float32)

for idx_type in ['IVF32,Flat', 'Flat']:
    idx = faiss.index_factory(dim, idx_type)
    idx.train(data1)
    idx.add(data1)
    idx2 = faiss.index_factory(dim, idx_type)
    idx2.train(data2)
    idx2.add(data2)
    faiss.merge_into(idx, idx2, True)
    print(idx_type, 'succesfully merged')
```

Expected output:
```
IVF32,Flat succesfully merged
Flat succesfully merged
```
Real output:
```
IVF32,Flat succesfully merged
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-39-1d9354e49f31>](https://localhost:8080/#) in <module>
      6     idx2.train(data2)
      7     idx2.add(data2)
----> 8     faiss.merge_into(idx, idx2, True)
      9     print(idx_type, 'succesfully merged')

[/usr/local/lib/python3.7/dist-packages/faiss/swigfaiss.py](https://localhost:8080/#) in merge_into(index0, index1, shift_ids)
   4879     :param shift_ids:: translate the ids from index1 to index0->prev_ntotal
   4880     """
-> 4881     return _swigfaiss.merge_into(index0, index1, shift_ids)
   4882 
   4883 def search_centroid(index, x, n, centroid_ids):

RuntimeError: Error in const faiss::IndexIVF* faiss::ivflib::extract_index_ivf(const faiss::Index*) at /project/faiss/faiss/IVFlib.cpp:79: Error: 'ivf' failed
```

Here is [a Colab notebook](https://colab.research.google.com/drive/1Ip-HqH2i3ru09rZ8tP6LBKJT7HupkFsE?usp=sharing) in which you can reproduce this error.

**Comment by mdouze** [comment]
Yes merging non-IVF indexes is not supported currently. 
Let's mark this as an enhancement.

**Comment by mdouze** [comment]
Works now, thanks @AbdelrahmanElmeniawy

**Comment by aliforgetti** [comment]
Hi @mdouze was this change made on faiss-cpu or was this made on faiss-gpu as well? Currently not able to use `merge_ino` on two indices I created.

**Comment by mdouze** [comment]
merging gpu indexes is not supported. Move them to CPU first.
