### ISSUE TITLE
Getting at underlying index with "IDMap,..."

### ISSUE THREAD

**Issue by maksle** [facebookresearch/faiss#2475]
# Summary

How do I get at the underlying hnsw index so that I can inspect or change the `efSearch` parameters? I want to be able to change the `efConstruction` before training, or change `efSearch` before searching. For the former, I suspect that I can do it by not using the index_factory, so that I get a handle on the underlying index directly, but I'm sure what to do for the latter if I'm reading the index in with read_index.

# Platform

OS: 

Faiss version: 
1.7.2

Installed from:  
pip

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

 

```
index = faiss.index_factory(512, "IDMap,HNSW128")
index.hnsw
AttributeError: 'IndexIDMap' object has no attribute 'hnsw'
index.index.hnsw
AttributeError: 'Index' object has no attribute 'hnsw'
```

**Comment by mdouze** [comment]
please apply faiss.downcast_index() to index.index
see https://github.com/facebookresearch/faiss/wiki/Python-C---code-snippets#how-to-explore-the-contents-of-an-opaque-index

**Comment by maksle** [comment]
Thanks that worked. Sadly I already switched to hnswlib due to this issue. I suggest it should be made a bit more apparent in the docs.
