### ISSUE TITLE
Faiss tests failing 

### ISSUE THREAD

**Issue by katiekrause** [facebookresearch/faiss#2476]
# Summary

We have installed faiss with GPU and without from source on an nvidia xavier machine. The build is completing however, despite best efforts, the following tests continue to fail. 

These fail with both GPU turned on and off: 

          2 - TestIvlistDealloc.IVFFlat (Failed)
          3 - TestIvlistDealloc.IVFSQ (Failed)
          4 - TestIvlistDealloc.IVFPQ (Failed)
          7 - TestLowLevelIVF.IVFFlatL2 (Failed)
          8 - TestLowLevelIVF.PCAIVFFlatL2 (Failed)
          9 - TestLowLevelIVF.IVFFlatIP (Failed)
         10 - TestLowLevelIVF.IVFSQL2 (Failed)
         11 - TestLowLevelIVF.IVFSQIP (Failed)
         12 - TestLowLevelIVF.IVFPQL2 (Failed)
         13 - TestLowLevelIVF.IVFPQIP (Failed)
         15 - TestLowLevelIVF.ThreadedSearch (Failed)
         16 - MERGE.merge_flat_no_ids (Failed)
         17 - MERGE.merge_flat (Failed)
         19 - MERGE.merge_flat_ondisk (Failed)
         20 - MERGE.merge_flat_ondisk_2 (Failed)
         27 - test_search_and_return_centroids.IVFFlat (Failed)
         28 - test_search_and_return_centroids.PCAIVFFlat (Failed)
         29 - TPO.IVFFlat (Failed)
         30 - TPO.IVFPQ (Failed)
         31 - TPO.IVFSQ (Failed)
         32 - TPO.IVFFlatPP (Failed)
         37 - SlidingWindow.IVFFlat (Failed)
         39 - SlidingInvlists.IVFFlat (Failed)

The following tests additional fail when GPU is turned on: 

         87 - TestGpuIndexFlat.IP_Float32 (Failed)
         90 - TestGpuIndexFlat.L2_Float32 (Failed)
         91 - TestGpuIndexFlat.L2_Float32_K1 (Failed)
        100 - TestGpuIndexIVFFlat.Float32_32_Add_L2 (Failed)
        101 - TestGpuIndexIVFFlat.Float32_32_Add_IP (Failed)
        104 - TestGpuIndexIVFFlat.Float32_Query_L2 (Failed)
        105 - TestGpuIndexIVFFlat.Float32_Query_IP (Failed)
        108 - TestGpuIndexIVFFlat.Float32_Query_L2_64 (Failed)
        109 - TestGpuIndexIVFFlat.Float32_Query_IP_64 (Failed)
        110 - TestGpuIndexIVFFlat.Float32_Query_L2_128 (Failed)
        111 - TestGpuIndexIVFFlat.Float32_Query_IP_128 (Failed)
        145 - TestGpuDistance.Transposition_RR (Failed)
        146 - TestGpuDistance.Transposition_RC (Failed)
        147 - TestGpuDistance.Transposition_CR (Failed)
        148 - TestGpuDistance.Transposition_CC (Failed)

# Platform

Jetson AGX Xavier, architecture: aarch64

OS: Ubuntu 20.04.4

Faiss version: Faiss 1.7.2

Installed from: built from source following instructions here: https://github.com/facebookresearch/faiss/blob/2cd84aa66308143d00aa0f39ccf29cbf48d243a6/INSTALL.md 

Faiss compilation options: 
-DFAISS_ENABLE_GPU=OFF  and -DFAISS_ENABLE_GPU=ON
-DBUILD_TESTING=ON 
-DFAISS_ENABLE_PYTHON=ON 
-DBUILD_SHARED_LIBS=ON 
-DCMAKE_BUILD_TYPE=Release 
-DMKL_LIBRARIES=/usr/lib/aarch64-linux-gnu/openblas-pthread/libopenblas.so  
-DPython_EXECUTABLE=/usr/bin/python3.8 
-DPython_INCLUDE_DIR=/usr/include/python3.8 . 

Running on:
- [x ] CPU
- [ x] GPU

Interface: 
- [ x] C++
- [ x] Python

# Reproduction instructions
1. Flash the machine with Ubuntu 20.04.4 and CUDA 11.4
2. Install Pip: sudo apt-get -y install python3-pip
3. install cython: pip3 install cython
4. install swig: sudo apt-get install swig
5. install libopenblas: sudo apt install -y libopenblas-dev
6. become root: sudo su
7. cmake -DFAISS_ENABLE_GPU=ON  -DBUILD_TESTING=ON -DFAISS_ENABLE_PYTHON=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DMKL_LIBRARIES=/usr/lib/aarch64-linux-gnu/openblas-pthread/libopenblas.so  -DPython_EXECUTABLE=/usr/bin/python3.8 -DPython_INCLUDE_DIR=/usr/include/python3.8 .
8. make -j faiss
9. make -j swigfaiss
10. cd faiss/python and ran python3 setup.py install
11. make install 
12. make test 

make tests causes all the tests listed above to fail.

**Comment by mdouze** [comment]
what is nvidia xavier?

**Comment by beauby** [comment]
```
-DMKL_LIBRARIES=/usr/lib/aarch64-linux-gnu/openblas-pthread/libopenblas.so
```

This is the likely culprit: OpenBLAS is not MKL. You can use OpenBLAS with Faiss but setting `MKL_LIBRARIES` is not the way (cf. https://github.com/facebookresearch/faiss/blob/main/INSTALL.md#step-1-invoking-cmake which points to https://cmake.org/cmake/help/latest/module/FindBLAS.html, which points to using `-DBLA_VENDOR=OpenBLAS`).

**Comment by katiekrause** [comment]
Thank you for your responses. 

I added the -DBLA_VENDOR=OpenBLAS flag and removed the MKL Libraries flag and the tests continue to fail. 

This is the machine we are using: https://developer.nvidia.com/embedded/jetson-agx-xavier-developer-kit 

Any additional suggestions are appreciated.
