### ISSUE TITLE
gpu question shard =true

### ISSUE THREAD

**Issue by michaelbstek** [facebookresearch/faiss#2484]
When I use 100 million data volume and 4 GPU for query, dim =128 index type (IVF10000, FLat) nprobe=100, when query increases batchsize >40000, error will be reported as follows:

index batch search begin.vector type:cps_vec2,index desc:IVF10000,Flat,query vector num:104735603

terminate called after throwing an instance of 'faiss::FaissException'

what(): Exception thrown from index 0: Error in virtual void* faiss::gpu::StandardGpuResourcesImpl::allocMemory(const faiss::gpu::AllocRequest&) at /root/miniconda3/conda-bld/faiss-pkg_1641228905850/work/faiss/gpu/StandardGpuResources.cpp:452: Error: 'err == cudaSuccess' failed: StandardGpuResources: alloc fail type TemporaryMemoryOverflow dev 0 space Device stream 0x7f5e2536d060 size 20040000000 bytes (cudaMalloc error out of memory [2])

The core code:

std::vector res;

std::vector devs;

for(int i = 0; i < ngpus; i++) {

faiss::gpu::StandardGpuResources *standRes = new faiss::gpu::StandardGpuResources;

standRes->setTempMemory(FLAGS_temp_memory);

res.push_back(standRes);

devs.push_back(i);

}

index = index_factory(storer.GetVecDim(), description.c_str(), metric);

faiss::Index * gpuIndex;

faiss::gpu::GpuMultipleClonerOptions *option;

option = new faiss::gpu::GpuMultipleClonerOptions();

option->shard = true;

gpuIndex = faiss::gpu::index_cpu_to_gpu_multiple(

res,

devs,

index,

option

);

I want to  increases batchsize when search ? I should do?

**Comment by mdouze** [comment]
Admittedly the library code should split the queries in batches. 
However, the workaround is quite simple: just call the search function with smaller batches.

**Comment by michaelbstek** [comment]
thanks bro,if with smaller batches and ivf+n is bigger ，For example ，IVF1000 and nprobe=100,  eight gpus is very low utilization. 
I want to prompt usage of gpu ，How should I set the parameters?

**Comment by michaelbstek** [comment]
thanks bro,if with smaller batches and ivf+n is bigger ，For example ，IVF10000 and nprobe=100, eight gpus is very low utilization.
I want to prompt usage of gpu ，How should I set the parameters?

**Comment by mdouze** [comment]
I don't understand the question. 
It crashes with batches of size 40000. What about 1000?

**Comment by michaelbstek** [comment]
1000 、10000 、20000 、 30000 all  is ok，but because of IVF10000 ，nprobe =100，I think that this isn't  give full play to  （A100）GPU of calculation power，so I want to set batchsize is bigger,  Can it be done？

**Comment by mdouze** [comment]
Well no, since you observed it crashes.
