### ISSUE TITLE
Mismatch of the distribution of codebook and origin points.

### ISSUE THREAD

**Issue by SubjectNoi** [facebookresearch/faiss#2494]
# Summary

I use the tutorial code in faiss/tutorial/python/3-IVFPQ.py, setting Dimension to 2, M (codebook number) to 1, and the number of original points to 1,000,000. After I trained the index, I invoke `faiss.contrib.inspect_tools.get_pq_centroids(index.pq)` to check the codebook. I find a wield mismatch between the codebook and the original 1,000,000 points as the figure I attach in following comment (where blue points are 256 centroids of the codebook, and origin points are 1,000,000 original points)

Why does the trained codebook have a shift of (-0.5, -0.5) against the original 1,000,000 points (I guess the shift is -0.5, -0.5 from the figure)? Or where can I access the true shift? Moreover why there is such a shift?

# Platform

OS: 

Faiss version: https://github.com/facebookresearch/faiss/commit/2cd84aa66308143d00aa0f39ccf29cbf48d243a6

Installed from: source

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by SubjectNoi** [comment]
![Fig_0_Origin](https://user-images.githubusercontent.com/23569127/192096486-f8a24fd5-0f73-40ee-a254-b8313f99030f.png)

**Comment by mdouze** [comment]
please post minimal code to reproduce.

**Comment by SubjectNoi** [comment]
Reproduce Code:

```
import numpy as np
import faiss
from faiss.contrib import inspect_tools
import matplotlib.pyplot as plt

d, nb = 2, 10000
nlist, m= 1, 1
np.random.seed(114514)            
xb = np.random.random((nb, d)).astype('float32')

quantizer = faiss.IndexFlatL2(d)
index = faiss.IndexIVFPQ(quantizer, d, nlist, m, 8)
fig = plt.figure(figsize=(10, 10))
index.train(xb)
index.add(xb)
codebook = inspect_tools.get_pq_centroids(index.pq)
Codebook_X, Codebook_Y = [], []
for c in codebook:      # There's only one codebook with 256 entries
    for x in c:
        # Every entry of the codebook is 2 dimension
        Codebook_X.append(x[0])
        Codebook_Y.append(x[1])
# Plot the codebook entries in 2D space
plt.scatter(Codebook_X, Codebook_Y, s=10, marker='x', label='Codebook Centroids')

Original_X, Original_Y = [], []
for p in xb:
    Original_X.append(p[0])
    Original_Y.append(p[1])
# Plot all search points in 2D space
plt.scatter(Original_X, Original_Y, s=2, label='Search Points')
plt.legend()
plt.savefig("Diff.png", dpi=600)

```

**Comment by mdouze** [comment]
This is normal because the PQ codebook is relative to the coarse quantizer centroids. 
Here the coarse quantizer has a single centroid at approx (0.5, 0.5) 
If you want just the PQ without centroids, use `IndexPQ` instead or set `index.by_residual = False`.

**Comment by SubjectNoi** [comment]
Okay, thanks. BTW I'm curious why faiss currently support only 8 bits centroids indices (256 centroids). Is this a consideration of performance-accuracy trade-off or something else?

**Comment by mdouze** [comment]
Faiss *does* support up to 16-bit centroid indices. 
If you found otherwise in the doc, please tell us, that info is outdated.
The 8-bit imoplementation is the fastest though because it aligns on bit boundaries.

**Comment by SubjectNoi** [comment]
Hello, it's been a long national day holiday.
Okay, I will check the docs, it's because I use the current FAISS and change the bit width parameter in IVFPQ from 8 to 16 like this:
```
quantizer = faiss.IndexFlatL2(d)
 index = faiss.IndexIVFPQ(quantizer, d, nlist, m, 8->16)
```
FAISS raises an error: 
```
RuntimeError: Error in faiss::IndexIVFPQ::IndexIVFPQ(faiss::Index*, size_t, size_t, size_t, size_t, faiss::MetricType) at /root/miniconda3/conda-bld/faiss-pkg_1641228905850/work/faiss/IndexIVFPQ.cpp:47: Error: 'nbits_per_idx <= 8' failed
```
Looks like the assertion still failed.

**Comment by SubjectNoi** [comment]
Okay, I will check the doc and src. BTW, given I achieved the PQ index of the query by my own methods, is it possible to pass this PQ index to FAISS for further index-point mapping by the current python API? Or how can I achieve the PQ index of the query of FAISS computed (I want to check the PQ index achieved by my own methods is correct or not)?
