### ISSUE TITLE
index.add_with_ids  add ids error

### ISSUE THREAD

**Issue by thbqlf** [facebookresearch/faiss#25]
Faiss assertion !"add_with_ids not implemented for this type of index" failed in virtual void faiss::Index::add_with_ids(faiss::Index::idx_t, const float*, const long int*) at Index.cpp:34
ids is long Array,  why error?

**Comment by mdouze** [comment]
Hi 
Not all indexes support `add_with_ids`. However, there is a wrapper class that adds a translation table on top of any index to support `add_with_ids`. See 

https://github.com/facebookresearch/faiss/wiki/Pre--and-post-processing#faiss-id-mapping

**Comment by thbqlf** [comment]
import numpy as np
d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

ids=(np.random.random(nb)).astype(int)
for i in range(0,100000):
    ids[i]=long(i)


import faiss                   # make faiss available
index = faiss.IndexIVF(d)   # build the index
print index.is_trained
# index.add(xb)                  # add vectors to the index
index.add_with_ids(xb,ids)

print index.ntotal

k = 2                          # we want to see 4 nearest neighbors
print  xb[:1]
D, I = index.search(xb[:5], k) # sanity check
print I
print D

print "========================================="

print xq
D, I = index.search(xq, k)     # actual search
print I[:5]                    # neighbors of the 5 first queries
print I[-5:]                   # neighbors of the 5 last queriess
print I[:1][0][0]

I read it, or do not understand, do you have this example
