### ISSUE TITLE
Centroid IDs for vectors returned from using quantizer and inspecting invlists are different

### ISSUE THREAD

**Issue by frances1005** [facebookresearch/faiss#2501]
# Summary

I have a trained IVF index and a batch of vectors that I need to find the centroids for. The vectors are already in the index but I only need the centroids for a small subset of them. 

Therefore, I am retrieving the centroids using
`_, centroids = index.quantizer.search(vectors, 1)`

To verify, I have also tried using [`get_invlist` ](https://github.com/facebookresearch/faiss/blob/c0052c15336a57f7068a7d098d5ce5b6234a2d70/contrib/inspect_tools.py#L10) and I have noticed that for a very small % (1%) of vectors, the centroid result I get is different from the two methods. 

Is that expected and if so, which one is correct? 

Running on:
- [ x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ x] Python

**Comment by frances1005** [comment]
I think I figured out what was wrong. I had some index parameters set before a search and set some values for `nprobe` and `quantizer_efSearch` using `faiss.ParameterSpace().set_index_parameters`. It seems that if I skip this step, the centroids are the same. Would that explain it?

**Comment by mdouze** [comment]
yes, especially the efSearch parameter is important there.
