### ISSUE TITLE
Is there a way to perform Iterative IVF partitioning?

### ISSUE THREAD

**Issue by Vikasdubey0551** [facebookresearch/faiss#2503]
Hello, 
I have a 1M+ plus vector of size 64. I am using the `IndexIVFFlat` index on a 4-core CPU machine and only interested to get invlists (clustering output).  

I am looking for granular IVF cells/partitions, therefore, I am using a high value of `nlist=29000`. Using such a high value of `nlist`, obviously slows down the faiss quite a bit. Therefore, I am thinking of an iterative way, which works as the following:

1) start with a low value of `nlist` e.g.<100.
2) Get invlists for the cells.
3) For each cell, perform another round of IVF partitioning. Perhaps, do this parallel.

The question is:
1) Is there a utility that does this already? 
2) any suggestions for improving on this? 

Increasing the CPU size or switching to GPU is definitely an option.

# Platform

OS: Ubuntu 20.04

Faiss version: 1.7.2
Installed from: pip 

Faiss compilation options: 
Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by mdouze** [comment]
You are suggesting to do a hierarchical clustering. 
What's not clear is whether you want to speed up the training or the assignment. 
For training, you can refer to [[demo_two_level_clustering.ipynb](https://gist.github.com/mdouze/1b2483d72c0b8984dd152cd81354b7b4)
For the assignment, there is no 2-level assignment available.

**Comment by Vikasdubey0551** [comment]
@mdouze  Thanks for the answer. I will check out the notebook. I am suggesting to speed up the training part. I have noticed that index training with `nlist=100` is way faster than `nlist=29000` as you can imagine. Therefore, I am thinking it to do in 2 steps.
