### ISSUE TITLE
KMeans Convergence Criteria

### ISSUE THREAD

**Issue by ghost** [facebookresearch/faiss#2510]
In some other implementations I used, KMeans has a convergence criteria based on updates. If the update is smaller than a set fixed hyperparameter, the convergence is assured and KMeans is stopped.

As far as I know, in FAISS KMeans the only stopping criteria is niter (max_iterations). What would be the ideal way to choose the niter? Does it depend on number of data points or n_clusters?

**Comment by mdouze** [comment]
For large kmeans the number of iterations is usually set to how much you can afford computationally.

**Comment by mdouze** [comment]
There is a Python implementation of k-means that can be tuned more precisely to the user's needs, see 

https://github.com/facebookresearch/faiss/blob/main/contrib/clustering.py#L321

There is no (or negligible) performance impact compared to the C++ version.
