### ISSUE TITLE
Get the IVF assignment in an IVFOPQ index.

### ISSUE THREAD

**Issue by namespace-Pt** [facebookresearch/faiss#2515]
# Summary

I want to restore the IVF assignment, that is, which cluster does the query probe, after training an IVFOPQ index. Currently my solution is 
```
index = faiss.read_index("my_IVFOPQ_matrix")
ivf_index = faiss.downcast_index(index.index)
ivf = faiss.downcast_index(ivf_index.quantizer)

vt = faiss.downcast_VectorTransform(index.chain.at(0))
new_vt = faiss.LinearTransform(vt.d_in, vt.d_out, vt.have_bias)
new_vt.A = vt.A
new_vt.b = vt.b
new_vt.is_trained = True
ivf = faiss.IndexPreTransform(new_vt, ivf)

query = np.random.rand(10000, ivf.d).astype(np.float32)
ivf.search(query, 10)
```
However, the generated `ivf` index (actually its a Flat index prepended by an OPQ transformation) runs very slow. Why?
# Platform

OS: Ubuntu 20.04

Faiss version: faiss-gpu==1.7.2

Installed from: anaconda

Faiss compilation options: 

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
As the snippet showed above.

**Comment by mdouze** [comment]
I don't know why it would be slow. It should be faster than running `index.sa_encode(query)`.
