### ISSUE TITLE
Saving GPU and CPU index composite

### ISSUE THREAD

**Issue by anasali90** [facebookresearch/faiss#2517]
# Summary

Hi, 
I have trained an index consisting of IVFFlat ( on GPU ) and Refineindex  ( on CPU). 
In order to save GPU index it must be converted back to CPU, but faiss.index_gpu_to_cpu throws an error because RFlat is already on CPU and not supported on GPU.
Is there a way to save it ? 
Thanks
# Platform

Linux: Ubuntu 22.04.1 LTS
Faiss version: 1.7.2

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

import faiss

import math
import numpy as np

res = faiss.StandardGpuResources()

features = np.random.random((1000, 20)).astype(np.float32)
flat = faiss.IndexFlat(features.shape[1])
nlist = int(0.5 * math.sqrt(features.shape[0]))
ivf_index = faiss.IndexIVFFlat(flat, features.shape[1], nlist, faiss.METRIC_L2)
gpu_index = faiss.index_cpu_to_gpu(res, 0, ivf_index)

postprocess_index = faiss.IndexRefineFlat(gpu_index)
postprocess_index.train(features)
postprocess_index.add(features)
cpu_index = faiss.index_gpu_to_cpu(postprocess_index)

Traceback (most recent call last):
  File "test_faiss_gpu_cpu_combo.py", line 18, in <module>
    cpu_index = faiss.index_gpu_to_cpu(postprocess_index)
  File "/opt/conda/lib/python3.8/site-packages/faiss-1.7.2-py3.8.egg/faiss/swigfaiss.py", line 9588, in index_gpu_to_cpu
    return _swigfaiss.index_gpu_to_cpu(gpu_index)
RuntimeError: Error in virtual faiss::Index* faiss::Cloner::clone_Index(const faiss::Index*) at /opt/faiss/faiss/clone_index.cpp:147: clone not supported for this type of Index

**Comment by mdouze** [comment]
It is not specific to GPU, IndexRefine is not supported in clone_index. Marking as enhancement.
