### ISSUE TITLE
Question Regarding 4-bit Comparison With ScaNN

### ISSUE THREAD

**Issue by ShikharJ** [facebookresearch/faiss#2518]
I was looking at the comparison results that the maintainers have very generously provided with respect to SCANN [here](https://github.com/facebookresearch/faiss/wiki/Indexing-1M-vectors#4-bit-pq-comparison-with-scann). I wished to know whether the comparison was made keeping the underlying ANNS data structure to be FAISS itself, or do the SCANN results make use of the quantization tree that it comes with?

**Comment by mdouze** [comment]
It's SCANN's.  We found that SCANN's anistotropic vector quantization (https://arxiv.org/abs/1908.10396) makes a difference only for a few types of data distributions.

**Comment by ShikharJ** [comment]
I see. I would imagine that keeping the underlying ANNS data structure same for both sets of experiments could offer more insights. Since the authors on the [quantization tree](https://papers.nips.cc/paper/2017/file/b6617980ce90f637e68c3ebe8b9be745-Paper.pdf) that SCANN uses are common across the two papers.
