### ISSUE TITLE
Different behavior of merged IVFFlat indices when created with index_factory and when created with IndexIVFFlat function

### ISSUE THREAD

**Issue by AntonioLopardo** [facebookresearch/faiss#2520]
# Summary
I'm trying to build different IVFFlat indices that I want to merge, the `IndexIVFFlat` function works just fine with `IndexFlatL2` as quantizer, but I want to also add specific Ids to the vectors to keep track of them once the indices are merged. So I want to use indices built with `index_factory` using `f"IVF{n_clusters},Flat"` as key. I verified that the indices built using `index_factory` return the same results as the ones built with the function, but once I merge them with `merge_into`, the results diverge and the merged index built with the index_factory performs much worse. 

# Platform

OS: Ubuntu 22.04.1

Faiss version: faiss-cpu 1.7.2 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
I'm working with the sift1M dataset and splitting it in partitions then building the indices from the partitions and merging them, idk if this is the best way to do it, but the merging behavior is still worth figuring out.

```
vec_dim = 128
n_clusters = 256
sharded_index = None
sharded_index_comp = None
quantizer = faiss.IndexFlatL2(vec_dim)
for i in range(npartitions):
    index_comp = faiss.index_factory(vec_dim, f"IVF{n_clusters},Flat")
    index = faiss.IndexIVFFlat(quantizer, vec_dim, n_clusters)
    index.train(partitions[i])
    index.add(partitions[i])
    index_comp.train(partitions[i])
    index_comp.add(partitions[i])
    
    if None in [sharded_index, sharded_index_comp]:
        sharded_index = index
        sharded_index_comp = index_comp
    else:
        faiss.merge_into(sharded_index, index, True)
        faiss.merge_into(sharded_index_comp, index_comp, True)
```

Using this code `sharded_index` and `sharded_index_comp` don't return the same results and when checking its accuracy `sharded_index_comp` is much worse.

Any idea for why that might be? Thanks for any help

**Comment by mdouze** [comment]
The training should be the same, ie. the index should be saved after `index.train` and re-used for all partitions. Otherwise the indexes are not compatible. 
Maybe `merge_into` should check that.

**Comment by AntonioLopardo** [comment]
Wouldn't that be the same as training only one index? In my experiment, I'm thinking that the indexes would be trained on different machine on different data and then merged, is the code above not a smart way to do that? 

I've tried different options for slightly different setups. For example, If I decide that I'm ok with not merging the indices but only the results I could use `merge_results_table_with` but I'm having issues with that too, I'm always getting wrong number or types of parameters errors but the signature of the function is not particularly difficult to understand just n, the number of queries, k the number of results per query, I0 the numpy array containing the ids of the top-k for each result, D0 the distances for the top-k to the query and similarly I1 and D1, keep_min and translation shouldn't matter for making the function run. Any clarification on the use of this function? 
I'm using the same indices trained above.

`TypeError: Wrong number or type of arguments for overloaded function 'merge_result_table_with'.
  Possible C/C++ prototypes are:
    faiss::merge_result_table_with(size_t,size_t,int64_t *,float *,int64_t const *,float const *,bool,int64_t)
    faiss::merge_result_table_with(size_t,size_t,int64_t *,float *,int64_t const *,float const *,bool)
    faiss::merge_result_table_with(size_t,size_t,int64_t *,float *,int64_t const *,float const *)`

**Comment by mlomeli1** [comment]
I ran the example provided (replacing it with synthetic data) and it seems that it already checks that the coarse quantisers are the same and throws and error:
````
import faiss
import numpy as np

vec_dim = 128
n_clusters = 16
n = 1000000
partitions = []
npartitions = 4
for i in range(npartitions):
    partitions.append(np.random.random((n // npartitions, vec_dim)).astype("float32"))

sharded_index = None
sharded_index_comp = None
quantizer = faiss.IndexFlatL2(vec_dim)
for i in range(npartitions):
    index_comp = faiss.index_factory(vec_dim, f"IVF{n_clusters},Flat")
    index = faiss.IndexIVFFlat(quantizer, vec_dim, n_clusters)
    index.train(partitions[i])
    index.add(partitions[i])
    index_comp.train(partitions[i])
    index_comp.add(partitions[i])

    if None in [sharded_index, sharded_index_comp]:
        sharded_index = index
        sharded_index_comp = index_comp
    else:
        faiss.merge_into(sharded_index, index, True)
        faiss.merge_into(sharded_index_comp, index_comp, True)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_660770/1654454498.py in ?()
     24         sharded_index = index
     25         sharded_index_comp = index_comp
     26     else:
     27         faiss.merge_into(sharded_index, index, True)
---> 28         faiss.merge_into(sharded_index_comp, index_comp, True)

~/.conda/envs/oivf_nightly_latest/lib/python3.10/site-packages/faiss/swigfaiss_avx2.py in ?(index0, index1, shift_ids)
   6470 
   6471     :type shift_ids: boolean
   6472     :param shift_ids:: translate the ids from index1 to index0->prev_ntotal
   6473     """
-> 6474     return _swigfaiss_avx2.merge_into(index0, index1, shift_ids)

RuntimeError: Error in virtual void faiss::IndexIVF::check_compatible_for_merge(const faiss::Index&) const at /home/circleci/miniconda/conda-bld/faiss-pkg_1691366670475/work/faiss/IndexIVF.cpp:1134: Error: 'v == v2' failed: coarse quantizers should be the same
````
I think this is what you had in mind @mdouze , so we can close the issue.

**Comment by mlomeli1** [comment]
For completeness,  I am adding the code that uses `partition[0]` to train the IVFFlat indexes so they have the same coarse quantiser
````
import faiss
import numpy as np

vec_dim = 128
n_clusters = 16
n = 100000
partitions = []
npartitions = 4
for i in range(npartitions):
    partitions.append(np.random.random((n // npartitions, vec_dim)).astype("float32"))

sharded_index = None
sharded_index_comp = None
quantizer = faiss.IndexFlatL2(vec_dim)
index = faiss.IndexIVFFlat(quantizer, vec_dim, n_clusters)
index.train(partitions[0])
index_comp = faiss.index_factory(vec_dim, f"IVF{n_clusters},Flat")
index_comp.train(partitions[0])
for i in range(npartitions):
    index.add(partitions[i])
    index_comp.add(partitions[i])

    if None in [sharded_index, sharded_index_comp]:
        sharded_index = index
        sharded_index_comp = index_comp
    else:
        faiss.merge_into(sharded_index, index, True)
        faiss.merge_into(sharded_index_comp, index_comp, True)
````
