### ISSUE TITLE
Shard FlatIndexIP across 3 GPUs

### ISSUE THREAD

**Issue by SohamTamba** [facebookresearch/faiss#2523]
# Summary

# Platform

OS: Ubuntu 16

Faiss version: 1.7.2

Installed from: anaconda

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

 

I am trying to shard a dataset of 25M items across 3  v100 GPUs. The dataset is ~77GB big (32 bit floats) and each GPU has 32GB of RAM, 96GB in total.

```
index = faiss.IndexFlatIP(768)
co = faiss.GpuClonerOptions()
co.shard = True
index = faiss.index_cpu_to_all_gpus(index, co, ngpu=3)
```

I get the error:
`Wrong number or type of arguments for overloaded function 'index_cpu_to_gpu_multiple'` from line 887 of faiss/__init__.py

Please help me fix this error. Any other advise on improving runtime is appreciated.

**Comment by SohamTamba** [comment]
cc: @wickedfoo since you have responded to similar questions :)

**Comment by mdouze** [comment]
Please use [GpuMultipleClonerOptions](https://faiss.ai/cpp_api/file/GpuClonerOptions_8h.html#_CPPv4N5faiss3gpu24GpuMultipleClonerOptionsE)

**Comment by SohamTamba** [comment]
@mdouze 
Thanks for the response 

That resolved my issue
