### ISSUE TITLE
could not parse index string IDMap2,Flat

### ISSUE THREAD

**Issue by big-bao** [facebookresearch/faiss#2527]
# Summary
reference code:   https://github.com/facebookresearch/faiss/blob/main/tests/test_index_composite.py
I don't know how to fix it, can any one give me a hand, thks

# Platform

OS: Win10 

Faiss version: 1.7.2 

Installed from: anaconda env python3.7  conda install faiss-cpu==1.7.2 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

code :
```python

# reference code:   https://github.com/facebookresearch/faiss/blob/main/tests/test_index_composite.py

xb = np.zeros((10, 5), dtype='float32')
xb[:, 0] = np.arange(10) + 1000
index = faiss.index_factory(5, "IDMap2,Flat")
ids = np.arange(10, dtype='int64') + 100
index.add_with_ids(xb, ids)
assert index.reconstruct(109)[0] == 1009
index.remove_ids(np.array([100], dtype='int64'))
assert index.reconstruct(109)[0] == 1009
```
issue:
```shell
RuntimeError: Error in std::unique_ptr<faiss::Index> faiss::{anonymous}::index_factory_sub(int, std::string, faiss::MetricType) at /home/conda/feedstock_root/build_artifacts/faiss-split_1644327719156/work/faiss/index_factory.cpp:690: could not parse index string IDMap2,Flat
```

but use below is ok
```
index = faiss.IndexIDMap2(faiss.index_factory(5, "Flat"))
```

**Comment by mdouze** [comment]
It is not supported in 1.7.2, please use a nightly build.

**Comment by big-bao** [comment]
> It is not supported in 1.7.2, please use a nightly build.

OK, thks
