### ISSUE TITLE
What is the best index if the data is not constant?

### ISSUE THREAD

**Issue by floschne** [facebookresearch/faiss#2530]
Hi, I'm having troubles to choose the correct index for my scenario. In my use case, the data to be indexed is not constant. That is, data is added and deleted at irregular intervals.

Usually, regarding the expected average size of the data I'd usually choose an IVF index. However, when adding (and also removing data(?)) from the index, it has to be (re-)trained.
So the only index I see working here is a brute-force FlatL2 or FlatIP index. Or am I missing something?

**Comment by mdouze** [comment]
If the data distribution does not change, you can still use an IndexIVF (probably with DirectMap = hashtable), and add and remove from it. 
See 
https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes#removing-elements-from-an-index

**Comment by floschne** [comment]
Thanks for your answer and hi! I'll check it out :)
