### ISSUE TITLE
Using faiss to compute hashes of embeddings 

### ISSUE THREAD

**Issue by rom1504** [facebookresearch/faiss#2531]
Hello,

I am trying to figure out if any of the internal structures of faiss indices (say an ivf pq or a lsh) could be used to compute hashes of embeddings with the property that they should be equal if similar enough in cosine distance

I am aware this is not a normal use of faiss, but I am wondering if this is something that has been tried before.

Thanks

**Comment by mdouze** [comment]
With hashes you mean binary vectors? 
Then can use IndexLSH and sa_encode to get the vectors.

**Comment by rom1504** [comment]
I'm trying to find a function f such that for an embedding e of size let's say 1024 floats i have for most e1, e2 in the space of my embeddings :
h1 = f(e1)
h2 = f(e2)
Such that if sim(e1, e2) > threshold then h1 = h2
With h preferably encoded as a small amount of bytes

One use case of such a function f would be to perform efficient deduplication of items represented by embeddings.

I think it would be possible to directly train a neural net to be f. But I'm wondering if using the quantization techniques implemented in faiss could be also a good technique.

Maybe the encodings produced by IndexLSH could work. Maybe ones produced by PQ index could be helpful too.

If you're aware of any previous use of faiss for this kind of use case / or have any idea if that makes sense to try, I'd be interested.
