### ISSUE TITLE
neighbours by index; features by index

### ISSUE THREAD

**Issue by andreRibeiro1989** [facebookresearch/faiss#254]
Hi,

1) is there any way in the python wrapper (and how) to get the nearest neighbours given the index entry (such as the one given in add_with_ids)

2) is there any way in the python wrapper to get the feature vector added given the index entry?

Thanks.

**Comment by mdouze** [comment]
Hi 

2. no, you can only get an approximation with the `reconstruct` method. For an IndexIVF, you need to call `make_direct_map` beforehand

1. reconstruct then search.

**Comment by mdouze** [comment]
Closing.
