### ISSUE TITLE
Missing entries in tabular data

### ISSUE THREAD

**Issue by yagmur-q** [facebookresearch/faiss#2540]
Hi,

I have tabular data with >100k data points and >20 attributes. The problem is when new user information enters to the system, faiss model should retrieve the most similar users to the query user. However, there are too many missing values in data. At this point, should I use standard imputation techniques(mean, median etc) to replace the NaN values in data when using faiss? 

Thanks

**Comment by mdouze** [comment]
This is not really in the scope of Faiss. Please check what is the best way of replacing missing values before using optimized search with faiss.

**Comment by asadoughi** [comment]
faiss.METRIC_NaNEuclidean was implemented in #3414
