### ISSUE TITLE
IndexIDMap needs resize on remove_ids

### ISSUE THREAD

**Issue by fishcorn** [facebookresearch/faiss#255]
When adding, removing, and adding again with IndexIDMap, the indices get out of sync:

```python
In [1]: import faiss
   ...: import numpy as np
   ...: X = np.random.randn(10,10).astype(np.float32)
   ...: idx = np.array([0,10,20,30,40,5,15,25,35,45], np.int64)
   ...: remove_set = np.array([10,30], dtype=np.int64)
   ...: index = faiss.index_factory(10,'IDMap,Flat')
   ...: index.add_with_ids(X[:5,:], idx[:5])
   ...: index.remove_ids(remove_set)
   ...: index.add_with_ids(X[5:,:], idx[5:])
   ...: for i in range(10):
   ...:     if idx[i] in remove_set:
   ...:         print('_')
   ...:         continue
   ...:     print(index.search(X[i,:][np.newaxis,:].astype(np.float32), 1)[1][0,0])
   ...:     
0
_
20
_
40
30
40
5
15
25
```

The problem is in this function: https://github.com/facebookresearch/faiss/blob/8e3dc6f2b0b736d043370eb1ee23892bcf2838b9/MetaIndexes.cpp#L95-L113

There should be a `id_map.resize(ntotal)` call at line 112. What happens is that the entries are shifted, but `id_map` still thinks that it has its original size. So when new entries are added with `push_back`, they're added too far down the vector and are in the wrong place.

**Comment by mdouze** [comment]
Hi 
Thanks, excellent bug report and solution! I will add it to Faiss and use your example as a unit test.

**Comment by mdouze** [comment]
Should be fixed in latest version.
