### ISSUE TITLE
How to build source code on windows

### ISSUE THREAD

**Issue by ziqi-jin** [facebookresearch/faiss#2551]
# Summary

Hi~, I want to use C++ Faiss on Windows, so I tried to compile it on windows, but I can not compile it succeed, do you have a tutorial for compiling C++ Faiss on windows?
# Platform
Windows

OS: 
Win10
Faiss version: 

Installed from:  
compiled by myself
Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

**Comment by linonetwo** [comment]
@mdouze Do you have idea on this? This is blocking ecosystem like https://github.com/asg017/sqlite-vss/issues/15 to be build.

**Comment by mdouze** [comment]
Please refer to the windows section of the contbuild config 

https://github.com/facebookresearch/faiss/blob/main/.circleci/config.yml

it is based on conda but starting from the cmake should also work.

**Comment by mdouze** [comment]
I think for windows we fully rely on anaconda. @algoriddle  ?

**Comment by asadoughi** [comment]
Windows builds are being run via Github Actions & Conda now as demonstrated here: https://github.com/facebookresearch/faiss/actions/runs/9540625564/workflow#L98-L111
