### ISSUE TITLE
FAISS in Python segfaults if `torch` is imported before `faiss`

### ISSUE THREAD

**Issue by johanrosenkilde** [facebookresearch/faiss#2555]
# Summary

If `torch` is imported before `faiss` when executing a Python program, then `faiss` is extremely prone to segfaulting. Extremely simple things, like using only the `Flat` index without remap seems to work, but most things beyond that segfaults almost all the time

# Platform

OS: macOS 12.6
Faiss version: git commit c08cbff1a4d6c9afb6b8f69004c5530aaf80237a 

Installed from: Python pip `faiss-cpu`

Faiss compilation options: Don't know

Running on:
- [x ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x ] Python

# Reproduction instructions

This is a minimal failing example script:

```python

import faiss
import torch

import numpy

if __name__ == "__main__":
    index = faiss.index_factory(3, f"IVF2,Flat")
    vectors = [
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 1.0],
    ]
    index.train(numpy.array(vectors[:2], dtype=numpy.float32))
    index.add(numpy.array(vectors, dtype=numpy.float32))
    faiss.write_index(index, "tmp.index")
```

**Comment by mdouze** [comment]
pip is not supported to install Faiss.
