### ISSUE TITLE
Error when querying large number of points with ```GpuIndexIVFFlat```

### ISSUE THREAD

**Issue by iam4wardto** [facebookresearch/faiss#2561]
# Summary

I am using ```GpuIndexIVFFlat``` and add tensor to the index. It happens that the index can query at most 65535 points at once. Beyond that this error will occur. I tried both CPU and GPU tensors.

```python
Faiss assertion 'err__ == cudaSuccess' failed in void faiss::gpu::ivfInterleavedScanImpl_32_(faiss::gpu::Tensor<float, 2, true>&, faiss::gpu::Tensor<long int, 2, true>&, faiss::gpu::DeviceVector<void*>&, faiss::gpu::DeviceVector<void*>&, faiss::gpu::IndicesOptions, faiss::gpu::DeviceVector<int>&, int, faiss::MetricType, bool, faiss::gpu::Tensor<float, 3, true>&, faiss::gpu::GpuScalarQuantizer*, faiss::gpu::Tensor<float, 2, true>&, faiss::gpu::Tensor<long int, 2, true>&, faiss::gpu::GpuResources*) at /root/miniconda3/conda-bld/faiss-pkg_1667409974121/work/faiss/gpu/impl/scan/IVFInterleaved32.cu:13; details: CUDA error 9 invalid configuration argument
Aborted
```

# Platform

OS: Linux 4.19.0-22-amd64

Faiss version:  1.7.2 & 1.7.3

Installed from:  ```conda install -c pytorch faiss-gpu==1.7.3 cudatoolkit=11.3```

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
```python
import faiss
import torch
import faiss.contrib.torch_utils


d = 3                            
nb = 100000                      
nq = 65536
nlist = 100

xb = torch.rand((nb, d))
xq = torch.rand((nq, d))

res = faiss.StandardGpuResources()  
quantizer = faiss.IndexFlatL2(d)
index = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_L2)
index = faiss.index_cpu_to_gpu(res, 0, index)

index.train(xb)
index.add(xb)
D, I = index.search(xq, 4)
```

**Comment by wickedfoo** [comment]
https://github.com/facebookresearch/faiss/pull/2572 will fix this problem

By the way, Faiss is not really designed for such low-dimensional data (here d = 3), as there exist efficient algorithms in low dimensions for exact nearest neighbor queries such as k-D trees and BSP trees. The algorithms in Faiss are meant for sufficiently high-dimensional (d > 20 or so) data.

**Comment by iam4wardto** [comment]
Thanks!
