### ISSUE TITLE
Update the Index factory wiki page (prefixes section)

### ISSUE THREAD

**Issue by javiabellan** [facebookresearch/faiss#2569]
# Summary

The [Prefixes section of the Index factory wiki page](https://github.com/facebookresearch/faiss/wiki/The-index-factory#prefixes) only shows `IDMap`. I think the codumentation for `IDMap2` is missing.

> Note: I think Github doesn't allow pull requests on wiki pages.

**Comment by mdouze** [comment]
right, it was added recently but the doc was not updated.
