### ISSUE TITLE
gpu memory not freed after reset

### ISSUE THREAD

**Issue by gliese581gg** [facebookresearch/faiss#257]
I ran following code :
```
import faiss
import numpy as np
import time

d = 64
nb = 100000
nq = 10000

xb = np.random.random((nb,d)).astype('float32')
xq= np.random.random((nq,d)).astype('float32')

res = faiss.StandardGpuResources()
flat_config = faiss.GpuIndexFlatConfig()
flat_config.device = 0
index = faiss.GpuIndexFlatL2(res, d, flat_config)

ss = time.time()
index.add(xb[:50000])
print ('Add : ' , time.time()-ss)

ss = time.time()
k  = 50
D,I = index.search(xq,k)
print ('Query : ',time.time()-ss)
print(D[0])
print(I[0])

ss = time.time()
index.reset()
print('reset : ',time.time()-ss)
print(index.ntotal)
time.sleep(30) #to check if gpu memory is freed
```
I expected the reset code to free gpu memory but the memory is not freed for 30 secs.

How can I free gpu memory??

I would like to rebuild entire indexes but 'reset and add ' consumes additional gpu memory for now.

**Comment by wickedfoo** [comment]
reset() on a GPU index frees all memory immediately that is in use by the index.

You are likely seeing the GPU memory reservation made by StandardGpuResources being kept around. Faiss allocates a scratch space that by default is 18% of all GPU memory in order to have a place to perform temporary calculations without calling cudaMalloc/cudaFree. This will not go away unless all indices go away, as well as the resources object.

**Comment by gliese581gg** [comment]
I tested with another add after reset and indeed it was memory reservation.

Thanks a lot:)

**Comment by twistedcubic** [comment]
@wickedfoo how does one reduce this 18% of GPU memory used for scratch space? I have yet to find an answer.

I also explicitly call `index.reset()` after an `index` is no longer needed, but the amount of GPU memory occupied still increases linearly with respect to the number of indices initialized. I don't declare any other cuda tensors. Are there other things one can do to ensure GPU memory is properly freed for each `index` and `Clustering` object?

Thank you.

**Comment by Enet4** [comment]
@twistedcubic [These functions](https://github.com/facebookresearch/faiss/blob/master/gpu/StandardGpuResources.h#L28-L42) in `StandardGpuResources` should be what you are looking for. I am not entirely sure of whether these are accessible from the Python bindings, but I would start with the assumption that they are.

**Comment by twistedcubic** [comment]
@Enet4 thanks, these are helpful, and they are available through the Python wrappers as well.

**Comment by youngjae-avikus** [comment]
If you delete the faiss object, it disappears

**Comment by tsdev** [comment]
I have the same issue, deleting the faiss objects does not free up the scratch GPU memory.
