### ISSUE TITLE
[Question] Best Practice for retrieving data from FAISS output index

### ISSUE THREAD

**Issue by SohamTamba** [facebookresearch/faiss#2574]
# Summary

Hi everyone, thanks for the incredible work.

As you know FAISS returns the index corresponding to the most similar embedding. I was wondering what is the recommended method for storing and retrieving the metadata from the index (provided by FAISS).

**Input**

DataFrame `df` (parquet/csv file) with columns `query` and `data`. The query column contains the embeddings on which Nearest Neighbor will be computed

**Run FAISS**

I load the embeddings in the query column into a numpy array and then execute FAISS on it. Faiss provides me the integer index of nearest neighbor - `corresponding to I in the tutorial`: [https://github.com/facebookresearch/faiss/wiki/Getting-started#in-python-2](https://github.com/facebookresearch/faiss/wiki/Getting-started#in-python-2)

**Retrieve Meta Data**

What is the most efficient method for retrieving the cells of the data column corresponding to the integer index in `I`?
Using Pandas, a straightforward way to do it is `df.iloc[I]` but that is very inefficient - it loads the entire dataframe into RAM to retrieve only a few rows.
˜

An alternative that comes to mind is to store everything as a separate pickle file and load as needed. Something like:

Prepare Pickle FIles:
```
import pickle

for idx, row in enumerate( df.to_dict(orient='records') ):
    pickle.dump(
        row, open(str(idx)+'.pkl', 'wb')
    )
```
Retrieve data:
```
def get_data(idx):
    return pickle.load(
        opme(str(idx)+'.pkl', 'rb')
    )
```

I was wondering if any of the developers have a recommendation for this task. Feel free to close this question if it is not relevant.

Interface: 
Python

**Comment by mdouze** [comment]
This is out of scope for Faiss, since it's about retrieving metadata. 
I believe hdf5 can store tabular data and supports memory-mapping. So maybe that could work for your use case.

**Comment by zalo** [comment]
You can also read and write numpy arrays as memory mapped .npy’s:
https://numpy.org/devdocs/reference/generated/numpy.lib.format.open_memmap.html
