### ISSUE TITLE
Search not the same for reconstructed vector with same codes

### ISSUE THREAD

**Issue by kushalkafle** [facebookresearch/faiss#2576]
# Summary

I want to try to store "commonly used query features", but I would like to store just the codes for them rather than actual vectors. However, I noticed that searching using the reconstructed vector from code produces different results than using the actual vector -- Even though they would produce identical codes when encoded with the index.  Please see the reproduction/questions below. 

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

The index is `OPQ128_896,IVF131072_HNSW32,PQ128x8`

```
query_vector = query_features

scores, ids1 = index.search(query_vector, 5)
print(scores,ids)

query_vector_codes = index.sa_encode(query_vector)
query_vector_reconstructed = index.sa_decode(query_vector_codes)

assert((query_vector_reconstructed != query_vector).all()) # Obviously, they won't be the same, this is not what I'm asking

scores, ids2 = index.search(query_vector_reconstructed, 5)
print(scores,ids2)

query_vector_reconstructed_code = index.sa_encode(query_vector_reconstructed)
assert((query_vector_codes == query_vector_reconstructed_code).all()) # The code themselves are identical

```

This prints: 

```
[[0.3513104  0.3488012  0.34232056 0.34232056 0.3411945 ]] [[ 653121285  882035430  744347972 1104332371 1057005735]]
[[0.43092442 0.4273418  0.42380556 0.41789317 0.4178322 ]] [[1057005735  653121285  882035430 1463000747  798803609]]
```
Not only are the top-k results different, but even for the same index. E.g., `653121285`, the scores are different.

Both reconstructed and actual vectors produce the same codes. Since the index isn't storing any actual vectors, why are the search results for the reconstructed vector different from the "real" vector? As far as the index is concerned they should be the same right?

Is it because of the OPQ pre-transformation? I am not sure I understand the mechanism at play here.

**Comment by mdouze** [comment]
There are two levels of quantization in the IVFPQ index type, but even with a single level of quantization, the search with a decoded vector does not give the same result as with the original vector. This is the difference between symmetric distance computations (SDC) and asymmetric distance computations (ADC), see https://hal.inria.fr/inria-00514462/document section II

**Comment by kushalkafle** [comment]
Thanks for the info! That is very helpful and perfectly answers my question.

Could you also tell me a bit more about the two-level quantization and how it might further affect distance computations? Are you referring to the coarse quantization (cells) + PQ compression or something else? For (hypothetical) SDC distance computations, the two stage quantization wouldn't really cause different results searching with original vs. reconstructed vectors right?

I think my original question is sufficiently answered by ADC so you should feel free to close this. Thanks again!

**Comment by mdouze** [comment]
Please read the paper.
