### ISSUE TITLE
compiler failed when undef  FAISS_USE_FLOAT16

### ISSUE THREAD

**Issue by cyyever** [facebookresearch/faiss#258]
/opt/faiss/gpu/GpuIndexIVF.cu(32): error: class "faiss::gpu::GpuIndexFlatConfig" has no member "useFloat16CoarseQuantizer"

**Comment by cyyever** [comment]
another error:
/opt/faiss/gpu/GpuIndexIVFPQ.cu(63): error: identifier "useFloat16LookupTables_" is undefined

**Comment by cyyever** [comment]
another error:
/opt/faiss/gpu/impl/IVFFlat.cu(50): error: expression must be a modifiable lvalue

**Comment by wickedfoo** [comment]
I'll work on fixing this, thanks!

**Comment by wickedfoo** [comment]
This should work now.
