### ISSUE TITLE
help with ragged array

### ISSUE THREAD

**Issue by JGuibone** [facebookresearch/faiss#2596]
# Summary

I have a nested array of ragged list. Let me explain

# Platform

PC

OS: 

WIN and google colab(some version of linux)

Faiss version: 
PC = Faiss-CPU (1.7.2) ive try'd to enable cuda by following windows installation but still cant do it.
Google Colab = Faiss-GPU (1.7.2)

Installed from:
PC = %pip install faiss-cpu (using VSCode notebook)
Google Colab = !pip install faiss-gpu
 

Faiss compilation options: none.. i dont know T^T 

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
the way i generate my embeddings is like this

`fullDocumentEmbeddings = []
for doc in tqdm(nestedListOfSentence):
        fullDocumentEmbeddings.append(model.encode(doc, batch_size=16))`

doc contains a list of sentences or phrases extracted from documents.
so depending on the number of sentences the array would have different lengths

this is how the list of embeddings look like.
[array of embeddings](https://gist.github.com/JGuibone/25a6c784744d1a39b157ba07a995e143)

i think the problem is i dont know which index type i should be using and how to implement my embeddings

im following the examples online and ive also tried debugging myself but after 2 days of searching and debugging i just have no idea how i could possibly implement the index using this array.

so im reaching out for help.

**Comment by mdouze** [comment]
You can probably use `np.vstack`
