### ISSUE TITLE
adding other distance metrics

### ISSUE THREAD

**Issue by wesboyt** [facebookresearch/faiss#2597]
I'm hoping to use earth movers distance for a project. Can you give me a brief outline of what would be involved? I can implement it myself and submit a PR, any help would be appreciated.

**Comment by mdouze** [comment]
The EMD is not defined between vectors without context, ie. you need to have a distance measure between buckets. 
Therefore, I am not sure where it would fit in Faiss, not just as an additinoal distance in 
https://github.com/facebookresearch/faiss/blob/main/faiss/MetricType.h

**Comment by wesboyt** [comment]
Thanks for responding! I'm probably missing 90% of the problem you're describing but in my use case these are all discrete density functions with an ordinal relationship of "strength" (and rarity). Maybe in my use case they all share context? I'm hoping to search for similar distributions and having context over weights being closer together ordinally.

**Comment by wesboyt** [comment]
maybe using centroids of buckets could work
