### ISSUE TITLE
faiss ids 

### ISSUE THREAD

**Issue by thbqlf** [facebookresearch/faiss#26]
Faiss assertion !"add_with_ids not implemented for this type of index" failed in virtual void faiss::Index::add_with_ids(faiss::Index::idx_t, const float*, const long int*) at Index.cpp:34

I read it, or do not understand, do you have this example

my test code：

import numpy as np
d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

ids=(np.random.random(nb)).astype(int)
for i in range(0,100000):
    ids[i]=long(i)

import faiss                   # make faiss available
index = faiss.IndexIVF(d)   # build the index
print index.is_trained
index.add_with_ids(xb,ids)

print index.ntotal

k = 2                          # we want to see 4 nearest neighbors
print  xb[:1]
D, I = index.search(xb[:5], k) # sanity check
print I
print D

print "========================================="

print xq
D, I = index.search(xq, k)     # actual search
print I[:5]                    # neighbors of the 5 first queries
print I[-5:]                   # neighbors of the 5 last queriess
print I[:1][0][0]

**Comment by mdouze** [comment]
NB you cannot instantiate an IndexIVF which is an abstract class. I added an example to 

https://github.com/facebookresearch/faiss/wiki/Pre--and-post-processing

```python
index = faiss.IndexFlatL2(xb.shape[1]) 
ids = np.arange(xb.shape[0])
index.add_with_ids(xb, ids)  # this will crash, because IndexFlatL2 does not support add_with_ids
index2 = faiss.IndexIDMap(index)
index2.add_with_ids(xb, ids) # works, the vectors are stored in the underlying index
```
