### ISSUE TITLE
Replace Inverted Lists in Python

### ISSUE THREAD

**Issue by CosimoRulli** [facebookresearch/faiss#2600]
Hello developers,

I have an IVFPQ index and I need to change its inverted lists without modifying its centroids. I want to replace the original inverted lists with manually generated ones, possibly in python.  
I know that I can erase the lists by using 
```
for list_no in tqdm(range(index.nlist)):
    index.invlists.resize(list_no, 0)
```
and then add all my new vectors. Anyway, this implies to re-add all the vectors to the index which may take a while.
Each of my inverted list is a list or tuples $(ev_i, id_i)$, where $ev_i$ is the newly encoded vector and $id_i$ is the corresponding id. I already know to which centroid every list belongs, so I was wondering if there is a more efficient solution, maybe leveraging the ```replace_invlists``` function.

**Comment by mdouze** [comment]
Here is function + small demo on how to do that: 
[demo_replace_invlists.ipynb](https://gist.github.com/mdouze/aef2078afdb12c027ed93672d9801399#file-demo_replace_invlists-ipynb)
