### ISSUE TITLE
This PR adds conda recipe for `aarch64-linux` .

### ISSUE THREAD

**Issue by Prettytasha** [facebookresearch/faiss#2601]
This PR adds conda recipe for `aarch64-linux` .

- This PR just adds conda recipe and Dockerfile, no CI jobs.
    - It needs to create a Docker image for aarch64 like `beauby/faiss-circleci:cpu`, but this PR doesn't.
- This PR doesn't add conda recipe for Windows/macOS, because we have no envs to check the behavior for them.

```console
$ uname -a
Linux ubuntu 5.4.0-1034-raspi #37-Ubuntu SMP PREEMPT Mon Apr 12 23:14:49 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
$ pwd
/path/to/faiss
$ which conda
/path/to/miniforge3/bin/conda
$ conda create -y -n py37 python=3.7
$ conda activate py37
$ which python3
/path/to/miniforge3/envs/py37/bin/python3
$ python3 --version
Python 3.7.10
$ conda install -y numpy blas
$ conda install -y scipy --no-deps  # prevent to install pypy as dependency
$
$ docker build -t faiss-conda-linux-aarch64 -f conda/Dockerfile.cpu.aarch64 .
$ CONTAINER_ID=$(docker create faiss-conda-linux-aarch64)
$ docker cp ${CONTAINER_ID}:/opt/conda/conda-bld/linux-aarch64 .
$ docker rm ${CONTAINER_ID}
$ conda install linux-aarch64/libfaiss-1.7.0-*_cpu.tar.bz2
$ conda install linux-aarch64/faiss-cpu-1.7.0-py3.7*_cpu.tar.bz2
$ python3
>>> import faiss
>>> faiss.__version__
'1.7.0'
```

### FAQ

- Q. Why has CMake been updated the version from v3.17.1 to v3.20.2?
    - A. Because [there is no pre-built binary release for linux-aarch64 on v3.17.1](https://github.com/Kitware/CMake/releases/tag/v3.17.1) (v3.20.2 is newest one at today).
- Q. Why have tests for `pytorch` been omitted?
    - A. Because [there is no `pytorch` conda package for linux-aarch64](https://anaconda.org/pytorch/pytorch).
- Q. Why is the numpy version specified to be `=1.16.5` instead of `=1.11` ?
    - A. Because [there is no `numpy=1.11` conda package for Python 3.8 at `conda-forge` channel](https://anaconda.org/conda-forge/numpy/files?page=18).
        - [The oldest `numpy` conda package for Python 3.8 at `conda-forge` channel is `1.16.5`](https://anaconda.org/conda-forge/numpy/files?page=10) as I confirmed.
            - Additionaly, now [all packages on `conda-forge` uses numpy `1.17` ](https://github.com/facebookresearch/faiss/pull/1894#issuecomment-843421783), so it seems that this setting will be conflicted with some other packages in the near future.
        - The solutions in order to specify `numpy=1.11` are below:
            1. Giving up on packaging for Python 3.8 on aarch64
                - I don't know how to do that without editing `faiss/conda/conda_build_config.yaml` , but the file is also referred by conda for x86, so if the file will be edited, `faiss` conda packages for Python3.8 on x86 also disabled. I think that this is not good choice.
            1. Providing `numpy=1.11` package for Python 3.8 on aarch64 at `pytorch` channel
            1. Contributing to [`numpy-feedstock`](https://github.com/conda-forge/numpy-feedstock) for adding `numpy-1.11-py3.8*` into `conda-forge` channel.
- Q. Why you use miniforge? There is miniconda for linux-aarch64
    - A. Whoops, I didn't know that...
        - However, there is no `numpy` for Python 3.6 on [`pkgs/main/linux-aarch64`](https://repo.anaconda.com/pkgs/main/linux-aarch64), so anyway `faiss/conda/conda_build_config.yaml` is needed to edit as removing Python 3.6 when using miniconda for linux-aarch64, or it is needed to provide `numpy` for Python 3.6 of linux-aarch64 at `pytorch` channel, etc.

__Originally posted by @vorj in https://github.com/facebookresearch/faiss/pull/1911__

**Comment by vorj** [comment]
@algoriddle This issue should also be closed (I'm not sure what this issue is intended to do in the first place, but anyway). Would you please do that?
