### ISSUE TITLE
What does the IVF index training process actually do?

### ISSUE THREAD

**Issue by ahndroo** [facebookresearch/faiss#2607]
I can't seem to find any documentation about what the training process does for the IVF?  It looks like in some examples you need to train with the data ahead of time before adding?  Does that mean I can't initialize an empty index, and dynamically add items?  

I have a very dynamic database where items will be added and removed sporadically.  I'm not sure which index type is best suited for my needs

**Comment by anubhav562** [comment]
Hi @ahndroo!

First you create an empty index. Then you load the data and train the IVF index, the training process internally initiates training of K means clustering, which results in the formation of k centroids (k = the number of inverted lists that you want in the IVF). Once it is trained you need to add the vectors to the index. 

Think of it in this way: Before adding the vectors, you are creating k buckets. While adding vectors you assign each vector to the closest bucket (based on euclidean distance). So even if you have more data flowing-in in the future, you can simply keep on adding them to the trained index.
Note: If you feel that your data distribution changes, you can re-train the index once in a while.
