### ISSUE TITLE
Semlock leak when trying to determine optimal k for faiss.Kmeans

### ISSUE THREAD

**Issue by hwrightson** [facebookresearch/faiss#2612]
Double question here, I hope that's ok. Apologies if there's a discord or somewhere more appropriate for these questions.

I'm trying to cluster ~75k 50 dimension FastText vectors using the following code which appears to work in a notebook but not in VScode. I'm trying to visualise an elbow to determine the best _k_ to use on my data.

The code below is returning the following errors: 

```
python(9146,0x700007642000) malloc: *** error for object 0xc0: pointer being freed was not allocated
python(9146,0x700007642000) malloc: *** set a breakpoint in malloc_error_break to debug
resource_tracker: There appear to be 18 leaked semlock objects to clean up at shutdown
```

I originally thought this was due to how I was passing some arguments into _test_faiss_kmeans but having amended this the issue persists. 

Question 1 - Please could you let me know what I might be doing wrong that's causing this error?
Question 2 - Please could you let me know whether my implementation of faiss.Kmeans looks correct? I cannot see any coherent clusters in my data (testing with max_points_per_centroid at 10000000 and 256, and various _k_).

Many thanks for any help

```
def _test_faiss_kmeans(embeddings: np.ndarray, k: int) -> dict:
    ncentroids = k
    niter = 20
    verbose = True
    d = embeddings.shape[1]
    kmeans = faiss.Kmeans(d, ncentroids, niter=niter, verbose=verbose, max_points_per_centroid=10000000)
    kmeans.train(embeddings)
    inertia = kmeans.obj[-1]
    D1, embedding_labels = kmeans.index.search(embeddings, 1)
    index = faiss.IndexFlatL2(d)
    index.add(embeddings)
    D2, centroid_labels = index.search(kmeans.centroids, 10)
    return {"embedding_labels": embedding_labels, "centroid_labels": centroid_labels, "intertia": inertia}


def _create_intertia_chart(max_k: int, embeddings: np.ndarray) -> None:
    inertia_list = []
    k_list = []

    for k in range(5, max_k):
        faiss_dict = _test_faiss_kmeans(embeddings, k)
        inertia_list.append(faiss_dict["inertia"])
        k_list.append(k)

    inertia_df = pd.DataFrame({"n_topics": k_list, "inertia": inertia_list})
    fig = px.line(inertia_df, x="n_topics", y="inertia")
    fig.show()
```

**Comment by mdouze** [comment]
Marking as install because Faiss is probably not installed correctly. 
Could you fill in the issue template?

**Comment by hwrightson** [comment]
# Summary
Summary as above.

# Platform
OS: macOS Monterey 12.6

Faiss version: **faiss-cpu 1.7.3** I guess this is the issue!

Installed from: https://pypi.org/project/faiss-cpu/

Faiss compilation options: 

Running on:
- [x] CPU
- [  ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
Code as above

Looking at it I guess that project I'm using is bad and I should install using conda from your actual repo?

**Comment by mdouze** [comment]
Please use conda to install.
