### ISSUE TITLE
reproduce 4bit pq performance

### ISSUE THREAD

**Issue by chasingegg** [facebookresearch/faiss#2615]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [x] Python

# Reproduction instructions

4ibt PQ SIMD is super fast, and I can easily reproduce the result with the conda package. However, when I try to reproduce the result by building from source, I just fail to reproduce, about 0.15s -> 2.5s degration. And I find out the mkl is successfully found by cmake. There is also a similar issue https://github.com/facebookresearch/faiss/issues/1609 but could be fixed by setting mkl lib path. Anyone knows why?  
![image](https://user-images.githubusercontent.com/18375889/206856720-ee079c6c-78d0-4911-898e-11afe55c83ca.png)

**Comment by alexanderguzhva** [comment]
Is it possible that your build command line does not enable AVX2?

**Comment by chasingegg** [comment]
I see the reason.. There are two libs named faiss and faiss_avx2, although I enabled AVX2, I didn't link the avx2 version faiss... It is kind of weird that we have two libs.
