### ISSUE TITLE
Search time in IndexFlatL2 increases as the number of nearest neighbors to return increases

### ISSUE THREAD

**Issue by saramont** [facebookresearch/faiss#2627]
# Summary

I built three IndexFlatL2 indexes: first one with 1000 vectors indexed, second one with 30000 vectors and the third one with 1000000 vectors. Then, I performed searches of k nearest neighbors on all of them for a dataset of 10000 queries, with k varying between 1 and 50. I noticed that, for the two smaller indexes, the mean search time per query slightly increases as k increases: the search time with k=50 is almost three times the search time with k=1. However, in the larger index search times remain almost constant.
 
I thought that the search times in the IndexFlatL2 were independent from k. Is this due to some overhead? 

# Platform

OS: Ubuntu 22.04.1 LTS

Faiss version: 1.7.3

Installed from: anaconda

Running on:
- [ ] CPU

Interface: 
- [ ] Python

# Reproduction instructions

This is the code in Python that I used to perform the search and take the mean search time for query . I set to use only one thread.

```
times = {}
for k in range(1,51):
    st = time.time()
    D, I = index.search(queries, k)
    et = time.time()
    times[k] = ((et-st)/queries.shape[0]) * 10**3 
}
```
The mean times measured for the three indexes are plotted in the figures below: the first figure refers to the index with 1000 vectors, the second figure refers to the index with 30000 vectors and the third figure refers to the index with 1000000 vectors.

![1000](https://user-images.githubusercontent.com/31258173/208062173-ec3460de-6a64-46c0-b84e-6a5277f6a05f.png)
![30000](https://user-images.githubusercontent.com/31258173/208062182-b7af63ad-8bb9-4645-8501-96295e591bcc.png)
![1000000](https://user-images.githubusercontent.com/31258173/208062187-18ec485f-f0d0-4397-a52d-b387471eafcb.png)

**Comment by mdouze** [comment]
Of course, collecting top-k elements has a cost proportional to k. 
The cost is more significant for small datasets where the search time is low.
