### ISSUE TITLE
segment fault for standalone OPQMatrix training with dimension 768

### ISSUE THREAD

**Issue by yunjiangster** [facebookresearch/faiss#2637]
# Summary

When running a OPQMatrix training for even a single iteration, I encounter a segmentation fault (or `invalid pointer` for `free()`), when the matrix dimension goes up from 512 to 768.

# Platform

* Ubuntu 18.04.6 LTS (Bionic Beaver)

* Python 3.7.12

* 4 CPUs only in a jupyterhub environment.

Faiss version: 

faiss-gpu==1.7.2

Installed from: 

`pip install faiss-gpu==1.7.2`

Faiss compilation options: 

N/A

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

```
import faiss
import numpy as np
d, m, num_examples = 768, 32, 1<<8
opq = faiss.OPQMatrix(d, m)
opq.niter = 1
rng = np.random.default_rng()
xb = rng.standard_normal((num_examples, d), dtype=np.float32)
opq.train(xb)
```

**Comment by mdouze** [comment]
please install via anaconda.
