### ISSUE TITLE
build error MKL python; build myself cpp use libfaiss.a

### ISSUE THREAD

**Issue by yja1** [facebookresearch/faiss#264]
I have two question.
I have install mkl(from source make install),swig(conda install swig),cuda8
when I run "locate libmkl_avx2.so",the output is:
---------------------
/mnt/dataa/publib/anaconda3/envs/gluon/lib/libmkl_avx2.so
/mnt/dataa/publib/anaconda3/lib/libmkl_avx2.so
/mnt/dataa/publib/anaconda3/pkgs/mkl-2017.0.3-0/lib/libmkl_avx2.so
/mnt/dataa/publib/anaconda3/pkgs/mkl-2018.0.0-hb491cac_4/lib/libmkl_avx2.so
/opt/intel/compilers_and_libraries_2017.4.196/linux/mkl/lib/ia32_lin/libmkl_avx2.so
/opt/intel/compilers_and_libraries_2017.4.196/linux/mkl/lib/intel64_lin/libmkl_avx2.so
---------------------

(1)I have correctly run demo_ivfpq_indexing and ivfpq_indexing_gpu.
when I try run"python tutorial/python/1-Flat.py" 
the error is:
-------------------
True
100000
[[  0 393 363  78]
 [  1 555 277 364]
 [  2 304 101  13]
 [  3 173  18 182]
 [  4 288 370 531]]
[[ 0.          7.17517376  7.20763016  7.25116253]
 [ 0.          6.32356453  6.6845808   6.79994583]
 [ 0.          5.79640865  6.39173603  7.28151226]
 [ 0.          7.27790546  7.527987    7.66284657]
 [ 0.          6.76380348  7.29512024  7.36881447]]
**Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.**
----------------

(2)I want use faiss in myself cpp. so I wirte a makefile for https://github.com/facebookresearch/faiss/tree/master/tutorial/cpp/1-Flat.cpp. 
my directory like this:
1-Flat.cpp  libfaiss.a  makefile
my makefile is:
-----------------------------
CC = g++
CXXFLAGS = -O3  -I/mnt/datab/faiss_code/faiss-master
LDLIBS = -L. libfaiss.a
LDFLAGS = -Wl,-rpath .

.PHONT : all

all : 1-Flat
1-Flat : 1-Flat.o
clean:
        -rm 1-Flat *.o
-----------------------------

when I run make,got the error:
---------------------
**libfaiss.a(Heap.o):/mnt/datab/faiss_code/faiss-master/Heap.cpp:26: more undefined references to `GOMP_parallel' follow
libfaiss.a(AuxIndexStructures.o): In function `faiss::RangeSearchPartialResult::finalize()':
/mnt/datab/faiss_code/faiss-master/AuxIndexStructures.cpp:128: undefined reference to `GOMP_barrier'
/mnt/datab/faiss_code/faiss-master/AuxIndexStructures.cpp:128: undefined reference to `GOMP_single_start'
/mnt/datab/faiss_code/faiss-master/AuxIndexStructures.cpp:128: undefined reference to `GOMP_barrier'
/mnt/datab/faiss_code/faiss-master/AuxIndexStructures.cpp:133: undefined reference to `GOMP_barrier'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target '1-Flat' failed
make: *** [1-Flat] Error 1**
------------------------------------------------

thank you very much

**Comment by zeynepkoyun** [comment]
Hi @yja1  
I'm getting this error too, how did you solve it?
the command I'm running is:
 g++ faiss/tutorial/cpp/1-Flat.cpp   libfaiss.a
