### ISSUE TITLE
what kind of  vector representation should be the data set input file for fast  reading?

### ISSUE THREAD

**Issue by igor-87** [facebookresearch/faiss#265]
Hi, I just discovered this great library and I am trying to build a dataset from some images, currently, I just read the images features and descriptions using sift by opencv and just write the descriptor vector representation to a file.
when I trying to read the file using faiss in case of small files it works fine, but in case of thousands of images the file size is growing about 1.5 g and when I am trying to read the file by faiss its stuck.
how should I represent the data set if I want to use sift feature and descriptor for faster reading on faiss?
and which tools/libraries should I use to do that?
thanks

**Comment by mdouze** [comment]
Hi 
You should write the vectors in a binary format (not text) and manipulate the file by chunks, eg. by adding 10000 vectors at a time to the index. See for example 

https://github.com/facebookresearch/faiss/blob/master/benchs/bench_polysemous_1bn.py#L188

**Comment by mdouze** [comment]
Closing. Re-open if follow-up question.
