### ISSUE TITLE
Precompute table should be enabled only if l2 quantizer and by_residual is true

### ISSUE THREAD

**Issue by chasingegg** [facebookresearch/faiss#2658]
# Summary

There are comments which show that the `// Pre-compute distance tables for IVFPQ with by-residual and METRIC_L2`, but actually we do not precompute distance tables only if quantizer metric type is METRIC_INNER_PRODUCT in faiss/IndexIVFPQ.cpp's `initialize_IVFPQ_precomputed_table`, this would cause memory overhead for other cases. 

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
Why do you say that? Here is the code that decides about precomputing the tables: https://github.com/facebookresearch/faiss/blob/main/faiss/IndexIVFPQ.cpp#L436

**Comment by chasingegg** [comment]
Yeah, but if we choose L2 and by_residual=false, faiss will still precomputing the table, but it will not be used but only involve the memory overhead.
