### ISSUE TITLE
 run  ./tests/test_blas  and some other test examples,while there is an error:Illegal instruction

### ISSUE THREAD

**Issue by ss3377** [facebookresearch/faiss#266]
![image](https://user-images.githubusercontent.com/34080863/33354022-b959ac50-d4eb-11e7-8bbd-697412e39806.png)

**Comment by mdouze** [comment]
Hi 
Please do not post screenshots as bug reports, copy-paste instead.
Your machine probably does not support avx, try removing the `-mavx` compile flag.

**Comment by mdouze** [comment]
No follow-up. Closing.
