### ISSUE TITLE
Searching most distant vector

### ISSUE THREAD

**Issue by EnricoBeltramo** [facebookresearch/faiss#2663]
Is it possible to search more distant elements instead the nearest? I looked in the documentation but I didn't find any option for a similar search.

**Comment by mdouze** [comment]
same as #2366

There is nothing to do that currently, except with INNER_PRODUCT or cosine distance, where one can just query the opposite vector.

**Comment by mdouze** [comment]
Just realized you can find the farthest away vector by restating it as a max inner product search problem with one additional dimension. 
[demo_farthest_L2.ipynb](https://gist.github.com/mdouze/c7653aaa8c3549b28bad75bd67543d34#file-demo_farthest_l2-ipynb)

**Comment by EnricoBeltramo** [comment]
Thank you! It's an amazing solution. It's not really clear how equivalence comes from, is it possible to see all calculation steps (or the mathematical reference) in order to understand it better ?
I tried to move values in different ranges and I found that with i.e. :
ds = SyntheticDataset(200, 0, 2000, 100)
k = 200
The ordering not match completely. Is it an exact formula or an approximation?

**Comment by EnricoBeltramo** [comment]
I understood the calculation: q^2 is a constant term added to any vector so doesn't matter if I'm interested only to order.
About that sometimes the order doesn't match with ground truth I found that when is different is always two vector with a very close distance that are inverted, I suppose is only a numerical issue due flow32 resolution
