### ISSUE TITLE
How to get high recall results at the billion scale

### ISSUE THREAD

**Issue by magdalendobson** [facebookresearch/faiss#2669]
I'm doing some work with the datasets from the [Big ANN Benchmarks](https://github.com/harsha-simhadri/big-ann-benchmarks) competition and I am trying to modify the index builds for a higher recall regime. What I want to do is get the maximum recall possible at the highest possible QPS while keeping the index build time under, say, 20 hours, on a machine with 1 TB RAM and 72 cores. 

For example, the string suggested for SIFT1B in big-ann-benchmarks is "OPQ64_128,IVF1048576_HNSW32,PQ64x4fsr"; on the machine I'm working with it took about 4 hours to build the index. If I am willing to increase the build time, should I start by adding more centroids? Decreasing compression? Increasing the max degree of HNSW? If anyone could comment specifically suggesting an index factory, and/or on the general approach towards this goal, I would really appreciate it!

**Comment by mdouze** [comment]
The topline recall is obtained with a larger encoding. In your case you do not seem to be constrained by amount of RAM. 
Therefore you can:
- increase the size of the codes 
- maybe increase the number of centroids
To improve accuracy you can also increase the efConstruction.

This gives 

IVF4194304_HNSW32,PQ128x4fsr

or 

RR256,IVF4194304_HNSW32,PQ256x4fsr

and set the efConstruction with 

faiss.downcast_index(faiss.extract_index_ivf(index).quantizer).hnsw.efConstruction = 200

**Comment by celsofranssa** [comment]
> The topline recall is obtained with a larger encoding. In your case you do not seem to be constrained by amount of RAM. Therefore you can:
> 
> * increase the size of the codes
> * maybe increase the number of centroids
>   To improve accuracy you can also increase the efConstruction.
> 
> This gives
> 
> IVF4194304_HNSW32,PQ128x4fsr
> 
> or
> 
> RR256,IVF4194304_HNSW32,PQ256x4fsr
> 
> and set the efConstruction with
> 
> faiss.downcast_index(faiss.extract_index_ivf(index).quantizer).hnsw.efConstruction = 200

Hello @mdouze , I am very interested in improving the recall too. Therefore, what do you mean when you say "increase the size of the codes"? Could you provide a minimal example explaining the parameters that control the recall?
