### ISSUE TITLE
HNSW index parameter problem，How to modify max_level ？

### ISSUE THREAD

**Issue by myazi** [facebookresearch/faiss#2688]
# Summary

We found that hnsw has a low recall rate on some data sets, and the difference in recall rate under different query retrievals is very obvious. 
We guess that on some query retrievals, hnsw got stuck in false local neighbors.

1) Is it possible to increase the randomness of HNSW by increasing the number of layers of HNSW to avoid falling into local neighbors?

2) Python environment, how to modify max_level, max_level is determined in set_default_probas, is it supported to modify?

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [✓] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [✓] Python

# Reproduction instructions

**Comment by mdouze** [comment]
`max_level` is determined automatically at build time. 
The parameter that affects the exploration at construction time is `efConstruction`. It may be useful to increase that.
