### ISSUE TITLE
Clarification requested on number of centroids to use when training IVF index for a distributed index

### ISSUE THREAD

**Issue by leothomas** [facebookresearch/faiss#2692]
# Summary
The [Guidelines to choosing an index](https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index#if-below-1m-vectors-ivfk) page suggest that for an IVF index, the number of centroids to use (K) should be: 

> Where K is 4*sqrt(N) to 16*sqrt(N), with N the size of the dataset.

If we're making use of a [distributed index](https://github.com/facebookresearch/faiss/wiki/Indexes-that-do-not-fit-in-RAM) should N be the size of the entire dataset? Or the size of the subset hosted on each machine/shard?  

# Platform

N/A

# Reproduction instructions

N/A

**Comment by mdouze** [comment]
IF you shard the dataset over several machines, then they act as independent datasets so the relevant size is that of a single shard.

**Comment by leothomas** [comment]
Awesome, thank you! 

And just to confirm, the index should be trained once using a randomly selected subset of the total dataset and re-used for each shard, rather than training a different index for each shard. Is correct/

**Comment by mdouze** [comment]
yes. See also https://github.com/facebookresearch/faiss/wiki/Indexes-that-do-not-fit-in-RAM

**Comment by leothomas** [comment]
Thank you for the clarification!
