### ISSUE TITLE
Faiss how to use real image sift keypoint data

### ISSUE THREAD

**Issue by caydyn-skd** [facebookresearch/faiss#27]
I have a lot of pictures to extract the key points based on OpenCV sift algorithm, how to use these data in faiss, whether examples can refer to?

**Comment by mdouze** [comment]
Hi, 

Could you clarify the question?

Thanks

**Comment by iNDicat0r** [comment]
@caydyn-skd the process is to extract the features which results to a vector of n dimentions. Feed those numbers to faiss and you'll get the desired result.

I tried faiss with a set of 100000 vectors of 2048dimentions and the output was accurate.

**Comment by wanghaisheng** [comment]
@iNDicat0r  could you share more details about how to extract features from images?

**Comment by jegou** [comment]
There are many ways depending on the application (semantic bases, similar places, never seen objects in 0-shot learning context, etc). This makes your question too broad, and anyway out of the scope of this wiki.
In case it is what you are looking for, I just give you two related references for particular object retrieval
https://arxiv.org/pdf/1511.05879.pdf
https://arxiv.org/pdf/1604.01325.pdf

**Comment by wanghaisheng** [comment]
@jegou   sir   can this faiss be used in the OCR or scene text recognition 
lets say we have 10 fonts and 6000 words .when we can generate 60000 images 。then  we can extract feactures from these images and get vector for each one .
for an input image we can segment each word in this image  and  with some image processing techniche we can go through the  same feature extration to get vector  then we can use faiss to find the similar one and know  the most possible one

**Comment by tim-hilt** [comment]
@jegou do you actively work in the field? Can you tell something about the current SOTA? Would really be interested in talking to you about that.

I'm in the process of building an object-retrieval-application currently based on feature-descriptors/ -matchers and am not really sure whether that's the best way to go about it regarding all advances in CNNs and Deep Learning in general.

**Comment by jegou** [comment]
@tim-hilt 

Q> @jegou do you actively work in the field? 
A> yes

Q> Can you tell something about the current SOTA? Would really be interested in talking to you about that.
A> I would suggest that you look at the excellent tutorial by Yusuke Matsui (@matsui528 ). https://matsui528.github.io/cvpr2020_tutorial_retrieval/

**Comment by tim-hilt** [comment]
@jegou thanks for the pointer! Also your paper on aggregating local descriptors might come in handy! Glad that i found FAISS and have you responding. :100:
