### ISSUE TITLE
shared library compile error

### ISSUE THREAD

**Issue by 0DF0Arc** [facebookresearch/faiss#270]
I'm trying to compile gpu-faiss to shared library, and meet this error, not happened for static library

CMakeFiles/gpufaiss.dir/GpuAutoTune.cpp.o: In function `faiss::gpu::GpuClonerOptions::GpuClonerOptions()':
/root/workspace/faiss-master/gpu/GpuAutoTune.cpp:107: multiple definition of `faiss::gpu::GpuClonerOptions::GpuClonerOptions()'
CMakeFiles/gpufaiss.dir/GpuClonerOptions.cpp.o:/root/workspace/faiss-master/gpu/GpuClonerOptions.cpp:21: first defined here
CMakeFiles/gpufaiss.dir/GpuAutoTune.cpp.o: In function `faiss::gpu::GpuClonerOptions::GpuClonerOptions()':

**Comment by 0DF0Arc** [comment]
BTW, I'm using cmake, simply change STATIC to SHARED, and remove all tutorial and test directory

**Comment by mdouze** [comment]
Are you sure you used the last version of Faiss? At some point it was indeed defined twice, but this should be fixed in the current version.

**Comment by 0DF0Arc** [comment]
Sorry to response this late, I already download the latest version, and no more multi-defined error. Thanks.
