### ISSUE TITLE
Prefiltering without search, just compute distances

### ISSUE THREAD

**Issue by javiabellan** [facebookresearch/faiss#2702]
In FAISS we can prefilter for a given search using `index.search()` with `IDSelector`

Sometimes it's useful prefilter and **not do the search, but just compute the distances**. Such as the following scenario:

Imagine we have items with different modalities representations (eg. Image-Text pairs) **with shared ids**.
In the code, we have both  `image_idx` and `text_idx` FAISS indexes. And the query input is a pair of `image_vector, text_vector`.

1. Call `image_idx.search(q=image_vector, k=10)` and get top10 ids of similar images.
2. Then use `text_idx` just for sorting the previous results (by computing distances on selected ids).

For doing the 2nd step in FAISS we can call `text_idx.search()` with `IDSelector` and **setting the `k` parameter equals to the number of selected Ids**. I think `search()` a bad interface for this problem, because this is not a search, it is just a distance comptutation of a given query vector on selected ids. Maybe a simple method could solve this problem.

I also have thought about manually getting the vectors with `reconstruct` and do the INNER_MUL in numpy, but i think this is also a bad interface aswell.

Maybe is interesting to create a new method for the FAISS index like `index.get_distances(q=query_vector, sel=list_of_selected_ids)`

---

### Update

I think [`faiss.fvec_inner_products_by_idx`](https://github.com/facebookresearch/faiss/blob/771b1a8e3746583bf76629a22249e2177b3e310d/faiss/utils/distances.h#L164) is the function I am looking for. But still dont know how to invoque it for a given (IDMap) index in python. But the ids of this function are sequential (not working with IDMap). Here is how to call it with raw numpy vectors:

```python
query   = np.array([1,2,3,4]).astype('float32')
vectors = np.array([[4,5,6,7],
                   [10,20,30,40],
                   [1,1,1,1]]).astype('float32')
ids = np.array([0,2])
out = np.array([0,0]).astype('float32')

ptr = faiss.swig_ptr
faiss.fvec_inner_products_by_idx(
        ip = ptr(out), # output inner product
        x = ptr(query),
        y=ptr(vectors),
        ids=ptr(ids),
        d=4,
        nx=1,
        ny=3)

# out = array([60., 10.], dtype=float32)
```

**Comment by mdouze** [comment]
This is a Python / C++ interface problem. For this complex use case could manage the id <-> sequential id mapping in Python. __
