### ISSUE TITLE
Support of SearchParameter for IDMap2 indexes

### ISSUE THREAD

**Issue by javiabellan** [facebookresearch/faiss#2703]
# Summary

I would like to know if there is any plan to support `SearchParameters` for indexes based on `IDMap2`. I find very useful the possibility of prefiltering (`IDSelector`) for these types of indexes with custom ids.

# Reproduction instructions

```python
embs  = np.random.randn(10,500)
ids   = np.array([1,2,3,4,5,6,7,8,9,10])
index = faiss.index_factory(embs.shape[1], "IDMap2,Flat", faiss.METRIC_INNER_PRODUCT)
index.add_with_ids(embs,ids)

sel  = faiss.IDSelectorArray(np.array([1,2,3,4,5]))
index.search(x=np.random.randn(1,500), k=3, params=faiss.SearchParameters(sel=sel))
```

Error: `search params not supported for this index`

**Comment by mdouze** [comment]
It is supported now, see 
[issue_2703.ipynb](https://gist.github.com/mdouze/e5cf49184a47d8e60fddb92d5ac1c940#file-issue_2703-ipynb)
