### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by harishankar-gopalan** [facebookresearch/faiss#2708]
This is a totally code based report. I have not run this extensively but I would be using it in the near future.

In [this](https://github.com/facebookresearch/faiss/blob/62c7342db12fd4d0784dfb7a03dc3d979c3ef332/faiss/IndexIVFPQ.cpp#L47) line of `IndexIVFPQ` implementation a `*quantizer` object is being taken as input and used within the constructor.

But there is no way to attach the destruction of this `*quantizer` object along with the deletion of the `IndexIVFPQ` object. I presume this would lead to some memory leak.

Can this be handled similar to the handling done [here](https://github.com/facebookresearch/faiss/blob/main/faiss/IndexHNSW.cpp#L267) for `IndexHNSW` where the storage is deleted in the destructor of `IndexHNSW` whenever `own_fields` is set to `true` ?

**Comment by mdouze** [comment]
sure, see here: https://github.com/facebookresearch/faiss/blob/main/faiss/IndexIVF.cpp#L51
