### ISSUE TITLE
Use IndexIVFFlat as quantizer of IndexIVFFlat?

### ISSUE THREAD

**Issue by moshangcheng** [facebookresearch/faiss#271]
For large data set needs more than 10000 clusters, can we use IndexIVFFlat as quantizer of IndexIVFFlat to improve query performance?

**Comment by jegou** [comment]
Yes, definitively. In this case you need to use it also at training time. 

From my experience, this works well but requires much more data and significantly longer training time than an IMI to train the index. But at query time you should obtain better timings/accuracy trade-offs.

**Comment by moshangcheng** [comment]
Got it! Thanks for quick response.
