### ISSUE TITLE
Example in wiki/Vector-codecs is broken

### ISSUE THREAD

**Issue by gitgithan** [facebookresearch/faiss#2711]
```
# generate some data
x = np.random.rand(1000, 20).astype('float32')
# prepare codec
codec = faiss.index_factory(20, "SQ4")
codec.train(x)
# encode
code = codec.encode(x)
print(x.nbytes)
# decode
x_decoded = codec.decode(code)
```
https://github.com/facebookresearch/faiss/wiki/Vector-codecs#example-usage
Above example gives `AttributeError: 'IndexScalarQuantizer' object has no attribute 'encode'`.
Is there something wrong with the factory string?

**Comment by mdouze** [comment]
The function name is `compute_codes`.
