### ISSUE TITLE
Miscellaneous Wiki errors (typos, wrong expressions)

### ISSUE THREAD

**Issue by gitgithan** [facebookresearch/faiss#2713]
- https://github.com/facebookresearch/faiss/wiki/The-index-factory
    - `In NSG32, 32 encodes the number of links per vertex directly so 32 means 32 * 2 * 4 = 128 bytes per vector.` Equation doesn't look right, expecting = 256 
- https://github.com/facebookresearch/faiss/wiki/Index-IO,-cloning-and-hyper-parameter-tuning
    - Typo separated at `
The parameters are separaded with a comma`
    - `This means that experiment 8 tests parameter combination 247 which sets nprobe to 128 and the Hamming threshold to 42. Previous experiments show that the performance is below 0.282 and the runtime above 0.064 s.` This sentence was referencing both index 7 and 8, i guess it intended to interpret only one of them when discussing `experiment 8`
- https://github.com/facebookresearch/faiss/wiki/How-to-make-Faiss-run-faster
    - Missing noun after `use of`: `It was observed that the use of helps in certain cases`
- https://github.com/facebookresearch/faiss/wiki/FAQ#searching-duplicate-vectors-is-slow
    - The 2nd `index.pq.cp` should be `index.cp`? IDE shows pq attribute doesn't exist on IndexIVF::cp `the appropriate ClusteringIndex is accessible as IndexPQ::pq::cp and IndexIVF::cp (index.pq.cp and index.pq.cp in Python).`

**Comment by mdouze** [comment]
Thanks for all the comments. I fixed most of them, not necessarily in the way you suggest.
