### ISSUE TITLE
IVFFLAT is slower than IVFPQ

### ISSUE THREAD

**Issue by David-Q** [facebookresearch/faiss#272]
I used 90 million data to create IVFFlatIndex and IVFPQIndex, but when do performance test with 100 threads or more, I find IVFPQ is much faster than IVFFLAT.  
For Example, IVFFLAT provides 160ms / 660qps  while IVFPQ provides 10ms / 5000qps. 
In my Understanding, PQ is just smaller than flat in size, why can it be so much faster ?  Is there anything I missed in IVFFLAT?

**Comment by David-Q** [comment]
in addition... I use it in GPU, the nprobe is 1 and the nlist is 40000, d of the data is 32

**Comment by wickedfoo** [comment]
Both indices are more or less memory bandwidth limited. For some / most? parameters, IVFFlat will be slower than IVFPQ (especially for smaller encodings), as IVFFlat has to traverse more memory, but IVFFlat will be more accurate. For larger PQ encodings, IVFFlat stands a chance at being faster.

**Comment by David-Q** [comment]
thx to your answer~ !
