### ISSUE TITLE
IndexHNSWPQ how to assign a PQ centroids in python and cpp

### ISSUE THREAD

**Issue by bit-pku-zdf** [facebookresearch/faiss#2720]
IndexHNSWPQ how to assign a PQ centroids in python and cpp

**Comment by bit-pku-zdf** [comment]
we train PQ centroids using some data, and want to assign them to HNSWPQ instead of using default trained PQ，Which Index meets my demand? Thanks~

**Comment by mdouze** [comment]
I don't understand the question.
