### ISSUE TITLE
sample_weight for KMeans

### ISSUE THREAD

**Issue by bjwie** [facebookresearch/faiss#2733]
Hey Faiss Team,

is there a chance to get sample_weight into the faiss.Kmeans function?

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by mdouze** [comment]
What does sample_wheights mean? 
You can provide weights at Kmeans training time see 

https://github.com/facebookresearch/faiss/blob/main/faiss/python/extra_wrappers.py#L414

**Comment by bjwie** [comment]
Thank you!
Sorry my bad, my autocompletion massed up.
