### ISSUE TITLE
wrong result when reconstruct vector of PQFastScan

### ISSUE THREAD

**Issue by ctrajan** [facebookresearch/faiss#2739]
# Summary
I need the reconstructed feature of the encoded PQFastScan code, but when I use function `reconstruct` (for IndexPQFastScan) and `reconstruct_from_offset`(for IndexIVFFastScan), i got the wrong result. I'm not sure if I use the right function to reconstruct the pqfs codes.
Reproduction instructions are provided (IndexPQFastScan case only)

# Platform

OS:  Ubuntu16.04 

Faiss version: latest version (code) 

Installed from: compile from code  

Faiss compilation options: MKL 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions
* dataset: GIST1M (dimension = 960)
* Index: IndexPQFastScan (same problem is also accured in IndexIVFFastScan)
* train the index
* the index is empty, then i call function `add` for adding ONE data

1. in function `IndexFastScan::add`, i add the following code after function `compute_codes(tmp_codes.get(), n, x);` (line 85) for  reconstructing vector from tmp_code(flat-codes)
`float *re_feat_1 = new float[d]; sa_decode(1, tmp_codes.get(), re_feat_1);`

2. then, the following codes are added after function `pq4_pack_codes_range`:  for reconstructing from fast-scan packed-code
`float *re_feat_2 = new float[d]; reconstruct(0, re_feat_2);`
(in IndexIVFFastScan, i use `reconstruct_from_offset` for reconstruct the code in IVFFastScan)

3. the following codes are used for comparing the two reconstructed result (not every dimension, just 0th, 100th, 200th ... 900th dimension data, in my opinion its should be the same)
```
for (int i = 0; i < d / 100; ++i) 
    printf(" dim %3d: %.5f vs %.5f, diff: %.5f\n", i * 100, re_feat_1[i * 100], re_feat_2[i * 100], re_feat_1[i * 100] - re_feat_2[i * 100]);
```

4. then i found the reconstructed result re_feat_1  and re_feat_2 are different in the following condition
   * if M = 16, re_feat_1 and re_feat_2 are SAME
   * if M = 32, re_feat_1 and re_feat_2 are DIFERRENT since 500th dimensions
   * if M = 96, re_feat_1 and re_feat_2 are DIFERRENT since 200th dimensions
   * the compare result for M=32 likes this:
```
dim   0: 0.03352 vs 0.03352, diff: 0.00000
dim 100: 0.04941 vs 0.04941, diff: 0.00000
dim 200: 0.22829 vs 0.22829, diff: 0.00000
dim 300: 0.11935 vs 0.11935, diff: 0.00000
dim 400: 0.06494 vs 0.06494, diff: 0.00000
dim 500: 0.07640 vs 0.05348, diff: 0.02292
dim 600: 0.12157 vs 0.01822, diff: 0.10335
dim 700: 0.10486 vs 0.14021, diff: -0.03536
dim 800: 0.03287 vs 0.04595, diff: -0.01308
```
total ```IndexFastScan::add``` function like this:

``` 
void IndexFastScan::add(idx_t n, const float* x) {
    FAISS_THROW_IF_NOT(is_trained);

    // do some blocking to avoid excessive allocs
    constexpr idx_t bs = 65536;
    if (n > bs) {
        for (idx_t i0 = 0; i0 < n; i0 += bs) {
            idx_t i1 = std::min(n, i0 + bs);
            if (verbose) {
                printf("IndexFastScan::add %zd/%zd\n", size_t(i1), size_t(n));
            }
            add(i1 - i0, x + i0 * d);
        }
        return;
    }
    InterruptCallback::check();

    AlignedTable<uint8_t> tmp_codes(n * code_size);
    compute_codes(tmp_codes.get(), n, x);

    // [debug] reconstruct-1
    float *re_feat_1 = new float[d];
    sa_decode(1, tmp_codes.get(), re_feat_1);

    ntotal2 = roundup(ntotal + n, bbs);
    size_t new_size = ntotal2 * M2 / 2; // assume nbits = 4
    size_t old_size = codes.size();
    if (new_size > old_size) {
        codes.resize(new_size);
        memset(codes.get() + old_size, 0, new_size - old_size);
    }

    pq4_pack_codes_range(
            tmp_codes.get(), M, ntotal, ntotal + n, bbs, M2, codes.get());

    // [debug] reconstruct-2 and compare
    float *re_feat_2 = new float[d];
    reconstruct(0, re_feat_2);
    for (int i = 0; i < d / 100; ++i)
        printf(" dim %3d: %.5f vs %.5f, diff: %.5f\n", i * 100, re_feat_1[i * 100], re_feat_2[i * 100], re_feat_1[i * 100] - re_feat_2[i * 100]);

    ntotal += n;
}
```

**Comment by ctrajan** [comment]
I found this problem is caused by function ```get_vector_specific_address``` in file ```pq4_fast_scan.cpp```, which should return a `size_t` variable, but it return a `uint8_t` data, so the returning address is always limited in range [0,255], that makes the decode data wrong

**Comment by mdouze** [comment]
Thanks for the very clear report. We will fix this.

**Comment by mdouze** [comment]
I can repro
```
import numpy as np 
import faiss
from faiss.contrib.datasets import SyntheticDataset

ds = SyntheticDataset(960, 200, 1, 0)
M = 32
index = faiss.index_factory(ds.d, f"PQ{M}x4fs")
index.train(ds.get_train())
index.add(ds.get_database())

index.pq.decode(index.pq.compute_codes(ds.get_database()))[:, ::100] - index.reconstruct(0)[::100]
```
