### ISSUE TITLE
`faiss.merge_into` gives Error: 'ivf' failed

### ISSUE THREAD

**Issue by koren-v** [facebookresearch/faiss#2744]
Hi, I would like to know how can I concatenate to indexes. I found [PR](https://github.com/facebookresearch/faiss/pull/2491) where mentioned that "Make merge_into support all types of Index as it implements merge_from" and I hoped the following code will do it for me, but no...

Faiss version: `1.7.3`

Installed from: `pip`

Running on:
* CPU

Interface: 
* Python

# Reproduction instructions

```
>>> import faiss
>>> import numpy as np
>>> 
>>> 
>>> index1 = faiss.IndexFlatIP(4)
>>> index2 = faiss.IndexFlatIP(4)
>>> arr1 = np.array([[1., 0., 0., 0.], [0., 1., 0., 0.]], dtype=np.float32)
>>> arr2 = np.array([[0., 0., 1., 0.], [0., 0., 0., 1.]], dtype=np.float32)
>>> 
>>> index1.add(arr1)
>>> index2.add(arr2)
>>> 
>>> faiss.merge_into(index1, index2, True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vitaliy/learning/search/venv/lib/python3.9/site-packages/faiss/swigfaiss_avx2.py", line 5520, in merge_into
    return _swigfaiss_avx2.merge_into(index0, index1, shift_ids)
RuntimeError: Error in const faiss::IndexIVF* faiss::ivflib::extract_index_ivf(const faiss::Index*) at /project/faiss/faiss/IVFlib.cpp:82: Error: 'ivf' failed
```

**Comment by mdouze** [comment]
Please use `index1.merge_from(index2)`

**Comment by sanasz91mdev** [comment]
> Please use `index1.merge_from(index2)`

@mdouze  this does not work
db.merg_from(db2)

**Comment by mlomeli1** [comment]
@sanasz91mdev please do not install faiss via pip, use conda. In the error you are printing here, it seems you missed and 'e' it is `merge_from` not `merg_from` .
