### ISSUE TITLE
Is GpuSelect fast when number of rows equals 1

### ISSUE THREAD

**Issue by zuowang** [facebookresearch/faiss#275]
In file gpu/test/TestGpuSelect.cu, I found GpuSelect is used to select top k element for multi rows at a time.

Would it fast if I want to select top k elements from one array? Great thanks!

**Comment by wickedfoo** [comment]
No, the implementation is built for bulk selection, it will have very low performance if used for a single problem as written.

One can use the implementation present to be efficient at single row selection via recursive decomposition which I have done before but I don't think the code exists in Faiss today.
