### ISSUE TITLE
Was 1.7.3 retagged?

### ISSUE THREAD

**Issue by SMillerDev** [facebookresearch/faiss#2759]
# Summary

Homebrew added 1.7.3 on the 9th of November with sha256: `3e4fac26d8c9e9008ecea4ae5fc414c658998fce4ba75835058b1a71d3516002` but that is not the hash of the current 1.7.3 release, which according to GitHub was released on the 30th of November.

# Platform

Faiss version: 1.7.3

Installed from: Downloaded from GitHub

Faiss compilation options: N/A

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

Download the 1.7.3 release and note how it does not have the same hash as Homebrew recorded before.

**Comment by mlomeli1** [comment]
hi @SMillerDev , yes, it was re-tagged!
