### ISSUE TITLE
how to build for arm? the mkl do not  support  arm

### ISSUE THREAD

**Issue by XiaBing992** [facebookresearch/faiss#2760]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
See 
https://github.com/facebookresearch/faiss/wiki/Installing-Faiss#compiling-faiss-on-arm
