### ISSUE TITLE
Differences between faiss.Kmeans class and kmeans in contrib

### ISSUE THREAD

**Issue by AntonioLopardo** [facebookresearch/faiss#2764]
# Summary

I'm clustering 1B points with 10M centroids, I'm very happy to use faiss for how quick it is but because of how lengthy training the clustering is, I would like to have some checkpoints after every iteration. Is there any way to natively do that in faiss or should I break up the clustering training in python by initializing a model for every iteration and passing to the new model the centroids from the previous iteration? I noticed that later iterations of the clustering take significantly longer than the first one, is this something specific to my system or built in the C++clustering? If this is the case, breaking up the clustering per iteration wouldn’t work. 

I've seen the kmeans function written in python in contrib in faiss 1.7.3 but because of the scale of my problem, I would like to stay in C++ to get as fast clustering as possible. 

Thanks for any info!

PS
I did some tests with the python clustering, and it is almost as fast as the native C++ version, so I'll use the one in contrib for my use case. But I would still be interested in knowing why later iterations take longer than the first, aren't they all doing the same operations on the same amount of data?

PPS
I might have just realized that it is always a cumulative time, so it is just total elapsed time. Sorry 
for the issue, but I'm still interested in understanding the differences between the native C++ clustering and python clustering.
# Platform

OS: 

Faiss version: 1.7.2

Installed from: from pip 

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

Any usage of the Kmeans clustering object from the faiss-gpu python package.

**Comment by mdouze** [comment]
The Python implementation should follow the C++ quite closely. 
The C++ implementation exists because python is not available in all contexts.
