### ISSUE TITLE
Importing faiss before torch works on the CPU, while importing it after torch allows it to work on the GPU

### ISSUE THREAD

**Issue by abulus** [facebookresearch/faiss#2765]
# Summary
Hello,

I've removed faiss to not get in conflict with faiss and faiss-cpu and re-installed faiss-gpu.
 When I import `faiss` before `torch`, `torch.cuda.is_available()` returns `False` and it works with cpu. But when I import after `torch` it actually sees the GPU and works fine. 
 
 Thanks in advance!

What might the problem is?

# Platform

Windows 10 WSL2: Ubuntu-22.04

Faiss version:  faiss-gpu   1.7.3   py3.8_h28a55e0_0_cuda11.3  pytorch

Installed from:  conda install -c pytorch faiss-gpu   

Running on:
- [. ] CPU
- [. ] GPU
- (both)

Interface: 
- [ .] Python

# Reproduction instructions

**import faiss first:** 
_Using device: cpu_
 _12/230 [00:56<15:38,  4.31s/it]_

**import torch first:**
_Using device: cuda:0
57/230 [00:51<02:33,  1.13it/s]_

**Comment by mdouze** [comment]
Faiss is probably not installed via our pytorch channel because we don't support GPU on windows. 
Please check where the package comes from.
