### ISSUE TITLE
The delay is too large when service online

### ISSUE THREAD

**Issue by Subenle** [facebookresearch/faiss#277]
I use faiss to compare the similarity of vectors, when service online, there are many call of `search` operation, and some  call of `add` operation。 

Every time search a vector, we lock a read_lock, and when add a vector, we lock a write_lock.

We found that in this case, if we want to add 100 vectors, it will cost 500s to add all those vectors.

How do you deal with the problem? Can anyone help me? 

Thanks in advance!

**Comment by mdouze** [comment]
Hi
Please give more context.

**Comment by Subenle** [comment]
@mdouze 

Now vectors in faiss are around 30,000, the dimention is 4096.

There will be many thread to do search operation，and some add operation will also happen simultaneously.

`inputs` may have 100 vectors.

Part of my code:
```cpp
pthread_rwlock_t rwlock_flatL2_;
k_nearest=5;

void process(const Inputs &inputs, Outputs &outputs){
  for(int i = 0; i < inputs.size(); i++){
    process_core(inputs[i], outputs[i]);
  }
}

void process_core(const Input &input, Output &output){
  ...
  if(input.type == SEARCH){
    vector<float> distances(k_nearest);
    vector<long> ids(k_nearest);
    pthread_rwlock_rdlock(&rwlock_flatL2_);
    indexFlatL2_.search(1, input.data(), k_nearest, distances.data(), ids.data());
    pthread_rwlock_unlock(&rwlock_flatL2_);
    output.dis = vec_to_string(distances);
    output.ids = vec_to_string(ids);
  }
  else if(input.type == ADD){
    pthread_rwlock_wrlock(&rwlock_flatL2_);
    indexFlatL2_.add(1, input.data());
    pthread_rwlock_unlock(&rwlock_flatL2_);
  }
  ...
}
```

How do you deal with multi-thread search and add?

**Comment by wickedfoo** [comment]
For multi-threading, you want to add or search for more than one vector at the same time. This is the most inefficient regime for Faiss.

Why are you adding a vector one at a time, furthermore with multithread locks? Just pass the whole 100 (or 1000, or whatever) to add() at once. Similarly, search should be batched as well.

**Comment by Subenle** [comment]
@wickedfoo 
Thanks.
