### ISSUE TITLE
_mm256_set_m128 undefined for gcc 7.5.0

### ISSUE THREAD

**Issue by Catoverflow** [facebookresearch/faiss#2770]
# Summary

`_mm256_set_m128` is added to supported intrinsics since gcc-8, please update the minimun support version.

Accouding to this [thread](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80582), patch was applied in 2017, May. but I'm not familiar with gcc releases enough to get the minimun supported version.

# Platform

OS: Ubuntu 18.04.6 LTS
Faiss version: 2d7dd5b0a6d5e75e3a0bcc88be122fa5a748833e

# Reproduction instructions

~~~~shell
$ cmake -B build . -DFAISS_ENABLE_GPU=OFF -DFAISS_ENABLE_PYTHON=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DFAISS_OPT_LEVEL=avx2
$ make -j && make install
~~~~

Produces:

~~~~
faiss/faiss/cppcontrib/sa_decode/Level2-avx2-inl.h: In function ‘__m256 faiss::cppcontrib::{anonymous}::elementaryBlock4x2b(const float*, const float*, const float*)’:
~/faiss/faiss/cppcontrib/sa_decode/Level2-avx2-inl.h:128:38: error: ‘_mm256_set_m128’ was not declared in this scope
     const __m256 combinedFineValue = _mm256_set_m128(fineValue1, fineValue0);
~~~~

Solved by replacing bundled `g++-7` with `g++-8`

**Comment by mdouze** [comment]
Not sure we want to proactively support such an old compiler.

**Comment by CloudsRL** [comment]
你好，我现在解决了。GCC、G++版本太低了，这个函数至少在8版本才有，所以需要升级你的GCC
