### ISSUE TITLE
ivf index question

### ISSUE THREAD

**Issue by juyunsang** [facebookresearch/faiss#2776]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU
- [ x ] GPU

Interface: 
- [ ] C++
- [ x ] Python

# Reproduction instructions

 

Hello.
I would like to know if IVF Flat or IVF PQ is more accurate than IVF PQ.
As I understand it, Flat should always have the highest accuracy, is this possible?

- IVF Flat
```python
        faiss_cfg = faiss.GpuIndexFlatConfig()
        faiss_cfg.useFloat16 = True
        faiss_cfg.device = 0
        index = faiss.GpuIndexFlatIP(res, dim, faiss_cfg)
        index.add(embeddings)
```

- IVF PQ
```python
        nlist = 1024
        nprobe = 1024
        sub_quantizers = 48
        bits_per_code = 8
        faiss_cfg = faiss.GpuIndexIVFPQConfig()
        faiss_cfg.useFloat16 = True
        faiss_cfg.useFloat16LookupTables = True
        index = faiss.GpuIndexIVFPQ(res, dim, nlist, sub_quantizers, bits_per_code, faiss.METRIC_INNER_PRODUCT, faiss_cfg)
        index.train(embeddings)
        index.add(embeddings)
        index.nprobe = nprobe
```

**Comment by mdouze** [comment]
yes

**Comment by juyunsang** [comment]
@mdouze 
Thank you for your reply.
I would appreciate it if you could share any organized articles on the principle that PQ can be higher than Flat.

**Comment by mdouze** [comment]
MAybe https://www.jstage.jst.go.jp/article/mta/6/1/6_2/_pdf
