### ISSUE TITLE
Bug: Build Frome Srouce 'GpuIndexIVFPQ' object has no attribute 'setNumProbes'

### ISSUE THREAD

**Issue by matchyc** [facebookresearch/faiss#2790]
# Summary

Building Frome Srouce 'GpuIndexIVFPQ' object has no attribute 'setNumProbes'

Run `bench_gpu_sift1m.py` 
**Exact Search** Totally OK
**Approximate Search** with IVFPQ  **NO**:  'GpuIndexIVFPQ' object has no attribute 'setNumProbes'

# Platform

OS:  Ubuntu 20.04

Faiss version: 1.7.3 (main branch)

Installed from:  Build From Source
 

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Strictly** Follow `INSTALL.md` Section "Building from source"

except cmake step command:
cmake -B build . -DFAISS_ENABLE_GPU=ON -DFAISS_ENABLE_PYTHON=ON -DCMAKE_BUILD_TYPE=Release -DPython_EXECUTABLE=\<my conda environment interpreter path\>

- cmake version: cmake version 3.26.0
- gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 
- CUDA version: 11.4

Note: 
1. Working well using GpuFlatIndex
2. Working well if faiss installed by conda (conda install faiss-gpu)

**Comment by mdouze** [comment]
the function was removed, please set the number of probes directly, with 

```
index.nprobe = 123
```
