### ISSUE TITLE
<command-line>:0:10: error: expected identifier before numeric constant utils.cpp:47:53: note: in expansion of macro ‘FINTEGER’

### ISSUE THREAD

**Issue by zgsxwsdxg** [facebookresearch/faiss#28]
Hi!

when I compile the project，an error has occured as follow:
 g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c hamming.cpp -o hamming.o  
g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c utils.cpp -o utils.o  -DFINTEGER=64
g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c IndexFlat.cpp -o IndexFlat.o  
g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c IndexIVF.cpp -o IndexIVF.o  
g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c IndexLSH.cpp -o IndexLSH.o  
<command-line>:0:10: error: expected identifier before numeric constant
utils.cpp:47:53: note: in expansion of macro ‘FINTEGER’
 int sgemm_ (const char *transa, const char *transb, FINTEGER *m, FINTEGER *
                                                     ^
<command-line>:0:10: error: expected ‘,’ or ‘...’ before numeric constant
utils.cpp:47:53: note: in expansion of macro ‘FINTEGER’
 int sgemm_ (const char *transa, const char *transb, FINTEGER *m, FINTEGER *
                                                     ^
utils.cpp:54:24: error: ‘m’ was not declared in this scope
 int sgeqrf_ (FINTEGER *m, FINTEGER *n, float *a, FINTEGER *lda,
                        ^
utils.cpp:54:37: error: ‘n’ was not declared in this scope
 int sgeqrf_ (FINTEGER *m, FINTEGER *n, float *a, FINTEGER *lda,
                                     ^
utils.cpp:54:40: error: expected primary-expression before ‘float’
 int sgeqrf_ (FINTEGER *m, FINTEGER *n, float *a, FINTEGER *lda,
                                        ^
utils.cpp:54:60: error: ‘lda’ was not declared in this scope
 int sgeqrf_ (FINTEGER *m, FINTEGER *n, float *a, FINTEGER *lda,
                                                            ^
utils.cpp:55:18: error: expected primary-expression before ‘float’
                  float *tau, float *work, FINTEGER *lwork, FINTEGER *info);
                  ^
utils.cpp:55:30: error: expected primary-expression before ‘float’
                  float *tau, float *work, FINTEGER *lwork, FINTEGER *info);
                              ^
utils.cpp:55:53: error: ‘lwork’ was not declared in this scope
                  float *tau, float *work, FINTEGER *lwork, FINTEGER *info);
                                                     ^
utils.cpp:55:70: error: ‘info’ was not declared in this scope
                  float *tau, float *work, FINTEGER *lwork, FINTEGER *info);
                                                                      ^
utils.cpp:55:74: error: expression list treated as compound expression in initializer [-fpermissive]
                  float *tau, float *work, FINTEGER *lwork, FINTEGER *info);
                                                                          ^
utils.cpp:57:23: error: ‘m’ was not declared in this scope
 int sorgqr_(FINTEGER *m, FINTEGER *n, FINTEGER *k, float *a,
                       ^
utils.cpp:57:36: error: ‘n’ was not declared in this scope
 int sorgqr_(FINTEGER *m, FINTEGER *n, FINTEGER *k, float *a,
                                    ^
utils.cpp:57:49: error: ‘k’ was not declared in this scope

  I've got a Ubuntu 14.04 system . Any idea what I am doing wrong?

**Comment by mdouze** [comment]
Hi 

Please do not forget to set -DFINTEGER=int in the BLASCFLAGS, see

https://github.com/facebookresearch/faiss/blob/master/example_makefiles/makefile.inc.Linux#L60

**Comment by zgsxwsdxg** [comment]
Hi,@mdouze 
Thanks. 
 For "BLASCFLAGS=-DFINTEGER=int", does the int need to be set a specific value： 32 or 64？
