### ISSUE TITLE
CUDA error 209

### ISSUE THREAD

**Issue by mrcmoresi** [facebookresearch/faiss#2802]
# Summary
I'm facing the following problem, I have created and Index and I want to move it to the GPU
 when I call faiss.index_cpu_to_gpu() I get the following error

```
Faiss assertion 'err__ == cudaSuccess' failed in void faiss::gpu::runL2Norm(faiss::gpu::Tensor<T, 2, true, IndexType>&, bool, faiss::gpu::Tensor<float, 1, true, IndexType>&, bool, cudaStream_t) [with T = float; TVec = float4; IndexType = int; cudaStream_t = CUstream_st*] at /home/conda/feedstock_root/build_artifacts/faiss-split_1673008980431/work/faiss/gpu/impl/L2Norm.cu:323; details: CUDA error 209 no kernel image is available for execution on the device
```

# Platform

OS:  Ubuntu 20.04

Faiss version:  1.7.2

Installed from:  anaconda

Faiss compilation options: 

Running on:
- [x ] CPU
- [ x] GPU (Trying on a Tesla K80)

Interface: 
- [ ] C++
- [ x] Python

# Reproduction instructions

 

The code is as follow, where encoded_data is a list of embeddings
```
index = faiss.IndexIDMap(faiss.IndexFlatIP(768))
ids = np.array(range(0, len(df)))
ids = np.asarray(ids.astype('int64'))
index.add_with_ids(encoded_data, ids)

res = faiss.StandardGpuResources() 
gpu_index_flat = faiss.index_cpu_to_gpu(res, 0, index)


```

To add more info, from /usr/local/cuda/version.json

`
"cuda" : {
      "name" : "CUDA SDK",
      "version" : "11.3.1"
   }
`

**Comment by mdouze** [comment]
K80 should be supported. 
@wickedfoo ?

**Comment by mrcmoresi** [comment]
Thanks for the comment @mdouze 
does it mean then I have a problem with my installation of CUDA? 
I could try re-installing it

**Comment by wickedfoo** [comment]
K80 (compute capability 3.5 I believe) should still theoretically compile but I believe we are not building conda packages with it anymore?

https://github.com/facebookresearch/faiss/blob/3219e3d12e6fc36dfdfe17d4cf238ef70bf89568/.circleci/config.yml#L288

**Comment by mdouze** [comment]
probably not the same error. Please submit an issue with more complete info.
