### ISSUE TITLE
GPU Memory when transfer cpu_index to gpu_index

### ISSUE THREAD

**Issue by 0DF0Arc** [facebookresearch/faiss#281]
Hi, 
I add about 5.2 million vectors in 144 dims into cpu_index, (IVF2500, PQ48), the cput_index size is actually about 270M , when using cpu_to_gpu to transfer the index to GPU,  how can the GPU Memory Usage show a total memory about 4800MiB?

**Comment by 0DF0Arc** [comment]
BTW, that's the transfer code:
faiss::gpu::GpuClonerOptions* options = new faiss::gpu::GpuClonerOptions();
        options->indicesOptions=faiss::gpu::INDICES_64_BIT;
        options->useFloat16CoarseQuantizer = false;
        options->useFloat16 = false;
        options->usePrecomputed = false;
        options->reserveVecs = 0;
        options->storeTransposed = false;
        options->verbose = true;
        faiss::gpu::StandardGpuResources resources;
        faiss::gpu::GpuIndexIVFPQ* index = dynamic_cast<faiss::gpu::GpuIndexIVFPQ*>   (faiss::gpu::index_cpu_to_gpu(&resources, gpu_id ,cpu_index, options));

**Comment by mdouze** [comment]
Hi 
There is a fixed temporary storage. You may want to tune it in the `StandardGpuResources` object.

**Comment by wickedfoo** [comment]
For good performance you shouldn't lower the temporary memory in StandardGpuResources below 1 GB of usage.
Faiss performs a lot of its temporary calculations here.

**Comment by 0DF0Arc** [comment]
OK, I'd better keep it un-changed, THX
