### ISSUE TITLE
Wiki documentation typo/bug describing index_factory options

### ISSUE THREAD

**Issue by IanMichaelAsh** [facebookresearch/faiss#2824]
# Summary

The [https://github.com/facebookresearch/faiss/wiki/Faiss-indexes](https://github.com/facebookresearch/faiss/wiki/Faiss-indexes) page gives 'HNWSx,Flat' as the value to pass to `index_factory()` for Hierarchical Navigable Small World graph exploration. 

That value is rejected by the function with an error "could not parse index string HNSWx,Flat", but passing the value  "HNSW,Flat" to `index_factory()` works correctly and (presumably) is what should be given in the documentation.

# Platform

N/A

OS: Ubuntu 22.04

Faiss version: 1.7.3

Installed from: Compiled myself and using c_api

Faiss compilation options: -DFAISS_ENABLE_GPU=OFF -DFAISS_ENABLE_PYTHON=OFF -DBUILD_SHARED_LIBS=ON -DFAISS_ENABLE_C_API=ON -DCMAKE_BUILD_TYPE=Release -DBLA_VENDOR=OpenBLAS

Running on:
- [ X] CPU
- [ ] GPU

Interface: 
- [X X C++
- [ ] Python

# Reproduction instructions

Call index_factory with the description parameter set to "HNSWx,Flat"

**Comment by mdouze** [comment]
Sorry I don't see where HNWSx,Flat is mentioned.

**Comment by mlomeli1** [comment]
it's fixed now
