### ISSUE TITLE
GpuIndexBinaryIVF implementation

### ISSUE THREAD

**Issue by AmineDiro** [facebookresearch/faiss#2829]
# Summary

Hello, 
I want to contribute to the project by implementing a `GpuIndexBinaryIVF` index. I wanted to get some directions if possible on the  index implementation. As I understand it, Faiss already has a GpuIndexIVFFlat which is limited to  `METRIC_L2` and `METRIC_INNER_PRODUCT` so to implement a binary version I could check the vector dimension to be a multiple of 8, change search distance to be GPU `binary distance`, and use same interface as `GpuIndexBinaryIVF`  ? 🤔 

Also looking at the CPU implementation `IndexBinaryIVF` I saw that it inherits from `IndexBinary` and not the  `IndexIVF` | `IndexIVFInterface`, is there a reason for this separation in implementation? 

Thank you all for your help, 
Interface: 
- [X] C++
- [X] Python

**Comment by mdouze** [comment]
Thanks for your interest in contributing to Faiss. 
`IndexBinaryIVF` does not inherit from `IndexIVF` because the coarse quantizer is an `IndexBinary`.
