### ISSUE TITLE
Update or remove id in the index

### ISSUE THREAD

**Issue by David-Q** [facebookresearch/faiss#283]
I am using ivfqp index of GPU for realtime search.
But sometimes i need to update or remove some vector... or just the id in id_map.
Is there any way to do that ?

**Comment by wickedfoo** [comment]
remove/update is unimplemented for the GPU at present. It may be implemented at some undetermined future date.

If it's just IDs that need to be updated, then you can handle this yourself with a translation layer i your own code to convert to/from old <-> new ID on top of the index.

**Comment by David-Q** [comment]
thank you for quick response, i will try it
