### ISSUE TITLE
Wiki typo on page with faiss indexes

### ISSUE THREAD

**Issue by slavafive** [facebookresearch/faiss#2833]
# Summary

There is a wiki page containing the [table](https://github.com/facebookresearch/faiss/wiki/Faiss-indexes) with the summary of methods.

For method *"Product quantizer (PQ) in flat mode"* the column **Main parameters** contains the parameter ```nbits```. At the same time the column **Bytes/vector** contains the ```nbit``` parameter (not ```nbits```).

**Comment by mdouze** [comment]
should be fixed now
