### ISSUE TITLE
Filtering Support on Index Created using IndexIDMap

### ISSUE THREAD

**Issue by navneet1v** [facebookresearch/faiss#2843]
### Description
I am from OpenSearch Team. We are using Faiss Library C++ code to enable the K-NN search in OpenSearch via [k-NN Plugin](http://github.com/opensearch-project/k-NN). At the bottom we create the faiss index and then do the search on those indices. 

### Question
Currently we have different types of indices(hnsw, IVF and IVF-PQ) we create based on customer parameters, and we want to support filtering using IDSelector on those indices. But currently when I tried to enable it I am getting exception which is coming from [here.](https://github.com/facebookresearch/faiss/blob/1c4cb6785585c45919b079873b869f872674cb68/faiss/IndexIDMap.cpp#L82)

Based on the above context I have few questions:
1. Why filtering is not supported on indices created using: IndexIDMap?
2. Is there any plan to support the filtering on indices created using IndexIDMap?

**Comment by mdouze** [comment]
There is no particular reason other than the we did not have a use case for it so far. 
I will implement this with a wrapped IDSelector that uses the id_map to translate indices.

**Comment by navneet1v** [comment]
@mdouze thanks this will be very useful. 

Please let us know once it is implemented.

**Comment by navneet1v** [comment]
Thanks @mdouze for raising the PR.

I can see the PR here:  https://github.com/facebookresearch/faiss/pull/2848
