### ISSUE TITLE
Unnecessary include or wrong RAFT version

### ISSUE THREAD

**Issue by S-o-T** [facebookresearch/faiss#2844]
# Summary

faiss/gpu/GpuDistance.cu:39:10: fatal error: raft/core/temporary_device_buffer.hpp: No such file or directory

# Platform

Faiss version: 4f574d59b047a133eb4f56e6202b24c2ee26fb31

Faiss compilation options: -DFAISS_ENABLE_GPU=ON -DFAISS_ENABLE_RAFT=ON -DCMAKE_BUILD_TYPE=Release -DFAISS_OPT_LEVEL="avx2" -DFAISS_ENABLE_PYTHON=OFF -DBUILD_TESTING=ON -DFAISS_ENABLE_C_API=OFF -DCMAKE_CUDA_ARCHITECTURES="86-real"

# Reproduction instructions

Checkout 4f574d59b047a133eb4f56e6202b24c2ee26fb31 and try to build.

https://github.com/facebookresearch/faiss/blob/4f574d59b047a133eb4f56e6202b24c2ee26fb31/cmake/thirdparty/fetch_rapids.cmake#L18  RAFT 23.02 indeed [does not](https://github.com/rapidsai/raft/tree/v23.02.00/cpp/include/raft/core) contain a raft/core/temporary_device_buffer.hpp

**Comment by alexanderguzhva** [comment]
Thanks, a good catch.
We use 23.06 version internally
