### ISSUE TITLE
How to use IndexHNSWFlat.search_level_0 in python

### ISSUE THREAD

**Issue by devjiang** [facebookresearch/faiss#2845]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [x] CPU

Interface: 
- [x] Python

# Reproduction instructions
An HNSW index has been built already and I want to search from the layer 0 directly. My python code is as follows: 

import numpy as np
import faiss
index = faiss.read_index("my_hnsw.index", 0)  # load the index
xq = np.random.normal(0, 1, [3, 128])              # generate three queries randomly 
nearest = np.array([ [0], [0], [0] ], dtype=np.int64) # search from the vertex 0. Just for demonstration, ignore the values of nerest and nearest_d please
nearest_d = np.array([ [1000.0], [1000.0], [1000.0] ], dtype=np.float32)
distances = np.zeros(3, dtype=np.float32).reshape(3, 1) # make room for the results
labels = np.zeros(3, dtype=np.int64).reshape(3, 1)
res = index.search_level_0(n=3, x=xq, k=1, nearest=faiss.swig_ptr(nearest), nearest_d=faiss.swig_ptr(nearest_d), distances=faiss.swig_ptr(distances), labels=faiss.swig_ptr(labels))

 
When running the code above, I get the following error: 
Traceback (most recent call last):
  File "model_eval.py", line 13, in <module>
    res = index.search_level_0(n=3, x=xq, k=1, nearest=faiss.swig_ptr(nearest), nearest_d=faiss.swig_ptr(nearest_d), distances=faiss.swig_ptr(distances), labels=faiss.swig_ptr(labels))
  File "/data/nfs/miniconda/envs/faiss_opt/lib/python3.7/site-packages/faiss/swigfaiss_avx2.py", line 6446, in search_level_0
    return _swigfaiss_avx2.IndexHNSW_search_level_0(self, n, x, k, nearest, nearest_d, distances, labels, nprobe, search_type)
TypeError: Wrong number or type of arguments for overloaded function 'IndexHNSW_search_level_0'.
  Possible C/C++ prototypes are:
    faiss::IndexHNSW::search_level_0(faiss::idx_t,float const *,faiss::idx_t,faiss::IndexHNSW::storage_idx_t const *,float const *,float *,faiss::idx_t *,int,int) const
    faiss::IndexHNSW::search_level_0(faiss::idx_t,float const *,faiss::idx_t,faiss::IndexHNSW::storage_idx_t const *,float const *,float *,faiss::idx_t *,int) const
    faiss::IndexHNSW::search_level_0(faiss::idx_t,float const *,faiss::idx_t,faiss::IndexHNSW::storage_idx_t const *,float const *,float *,faiss::idx_t *) const

**Comment by devjiang** [comment]
@mdouze After the xq is decorated with swig_ptr，the error still occurs.  If I call index.search(x=xq, k=1), a successful response is returned. However, I need to search the layer 0 directly in my setups.

**Comment by mdouze** [comment]
See this example: [demo_search_level_0.ipynb](https://gist.github.com/mdouze/f1480ec0ef4e6d3e7ccf3895e0bc2ac8#file-demo_search_level_0-ipynb)

**Comment by devjiang** [comment]
@mdouze, I 'm sorry that I replied too late. Thank you for your big help. The question can be closed :-)
