### ISSUE TITLE
C++ index_cpu_to_gpu_multiple error

### ISSUE THREAD

**Issue by 0DF0Arc** [facebookresearch/faiss#285]
I tried to using 2 gpus to do the search, when run the code, get a coredumped. I tried to use /not use the GpuMultipleClonerOptions, makes no difference, 

Here is the code i used to test, can anyone help me to solve the issue? BTW, the cpu_index works OK on single GPU(index_cpu_to_gpu)
        faiss::gpu::StandardGpuResources* res;
        std::vector<faiss::gpu::StandardGpuResources*> resources;
        resources.push_back(res);
        resources.push_back(res);

        std::vector<int> dev;
        dev.push_back(0);
        dev.push_back(1);          
        faiss::gpu::GpuIndexIVFPQ* index = dynamic_cast<faiss::gpu::GpuIndexIVFPQ*>(faiss::gpu::index_cpu_to_gpu_multiple((std::vector<faiss::gpu::GpuResources*> &)resources, dev, cpu_index));

**Comment by 0DF0Arc** [comment]
BTW, the cpu_index is reloaded from disk

**Comment by 0DF0Arc** [comment]
BTW, the cpu_index is reloaded from disk and the faiss source code is cloned from git on 5/Dec

**Comment by mdouze** [comment]
Hi
`res` is not initialized in your code.
