### ISSUE TITLE
Is it possible to get slightly different result with same vector data on different machine

### ISSUE THREAD

**Issue by zhenglaizhang** [facebookresearch/faiss#2854]
With same vector data, and build the hnswflat index on different k8s pods, then searching with same input data, I will get slightly different results when k is pretty large, however when k is small <= 100, the looks the same (I did only a few test data check). I am wondering from faiss perspective, is it possible?  If not I will try to dig out what's wrong with my setup.

**Comment by mdouze** [comment]
See 
https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls#reproducibility-with-multiple-threads

**Comment by zhenglaizhang** [comment]
Thanks for providing the great link!

> the HNSW add function is performed in an unspecified order. Implementing it with a static thread scheduling is too inefficient. Search is deterministic.

So for the same input embedding data, if I have multiple machines build it separately I will get slightly different result. Unless I have a single HNSW index built in one machine, and distribute it to the target machines, I can get the same result across different machines. And this seems to be the only approach to achieve this.
