### ISSUE TITLE
faiss-cpu does not work under Windows

### ISSUE THREAD

**Issue by johann-petrak** [facebookresearch/faiss#2859]
Installed faiss-cpu under Windows 10 using exactly the steps given in the installation instructions:

```
conda create -y -n faiss python=3.10
conda activate faiss
conda install -c pytorch faiss-cpu
```
Which works without error.

However after this running python and executing `import faiss`  results in this error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\johann\anaconda3\envs\faiss\lib\site-packages\faiss\__init__.py", line 16, in <module>
    from .loader import *
  File "C:\Users\johann\anaconda3\envs\faiss\lib\site-packages\faiss\loader.py", line 65, in <module>
    from .swigfaiss import *
  File "C:\Users\johann\anaconda3\envs\faiss\lib\site-packages\faiss\swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: DLL load failed while importing _swigfaiss: The specified module could not be found.
```

**Comment by johann-petrak** [comment]
When instead installing using these steps (using the conda-forge instead of pytorch channel):

```
conda create -y -n faiss python=3.10
conda activate faiss
conda install -c conda-forge faiss-cpu
```

Version 1.7.2 (the above procedure seems to try to install 1.7.3) is installed and importing faiss now works without that error message.

It is odd that the method which does NOT work on Windows is the recommended procedure in the installation instructions. https://github.com/facebookresearch/faiss/blob/main/INSTALL.md

**Comment by johann-petrak** [comment]
Tried to specifically install faiss-cpu==1.7.2 via the pytorch channel which apparently does not work with python 3.10 (though that worked via the conda-forge channel) 

Retried with Python 3.8: 
```
conda create -y -n faiss python=3.8
conda activate faiss
conda install -c pytorch faiss-cpu=1.7.2
```

This succeeds in installing 1.7.2 from the pytorch channel and it allows importing without the problem shown above. 
So maybe the problem IS related the the faiss version really?

**Comment by AshwinSarath** [comment]
In Windows, faiss-cpu==1.7.4 and Python 3.10 is working for me (globally). Initially when I tested it, it was not working for me. After re-starting my system, for Python > 3.8 is working. So it should not be a problem though.
