### ISSUE TITLE
Can I obtain the completion time of index construction when I create an index or add data to the index, such as HNSW index

### ISSUE THREAD

**Issue by ly7354820** [facebookresearch/faiss#2869]
Running on:
- [✓] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [✓] Python

**problem:**
When I create an index or add data to an index, I want to obtain the completion time of index construction, especially for HNSW. Is there a way to obtain it, or do you have any suggestions

**Comment by ly7354820** [comment]
> 
Sorry, I didn't describe it clearly enough.
In my database, I want to add a new field called index_time.This time is the timestamp of the operations that occur when I create an index or add data to the index,can I get these data?

**Comment by ly7354820** [comment]
> I don't understand the question. Just see the difference between `time.time()` before and after the call no?

Sorry, I didn't describe it clearly enough.
In my database, I want to add a new field called index_time.This time is the timestamp of the operations that occur when I create an index or add data to the index,can I get these data?

**Comment by mlomeli1** [comment]
I echo Matthijs's suggestion to use the `time` library to obtain it before and after calling `index.add()` and adding it to your database.
