### ISSUE TITLE
Question on GPUCloneOptionMultiple

### ISSUE THREAD

**Issue by paryang** [facebookresearch/faiss#287]
Hey, 
I'm trying to use index_cpu_to_gpu_multiple(4 GPUs), I set the option->shard to true, and I found that the GPU Memory usage is no difference with shard = false, both about 4800MiB(Tesla M40). 
I though using shard = true should split the index memory to 4 GPUs( like totally 1GiB, and now 256MiB each), but in my case, no matter I set shard = ture or shard = false,, the Memory usage of each single GPU is SAME as using one GPU (index_gpu_to_gpu) all of them are 4800MiBs.

One more thing, can you give me a instruction on the parameter of variable "shard_type"? I did not find anything on this.

**Comment by mdouze** [comment]
Hi, 
There is a significant per-GPU fixed cost associated to the indexes. It could be that the dataset is not large enough to make a difference between shards and replicas. 
The shard types are listed here: https://github.com/facebookresearch/faiss/blob/master/IndexIVF.h#L130
The default (1) will distribute the index evenly if the distribution of id modulo 4 is uniform.

**Comment by paryang** [comment]
get it ,thx
