### ISSUE TITLE
 Could not load library with AVX2 support

### ISSUE THREAD

**Issue by Magicen0722** [facebookresearch/faiss#2872]
# Summary

I have installed faiss using the command "pip install faiss-cpu" on Windows with Python 3.9.
However, I am unable to import AVX2 support.
Upon inspecting the "site-packages/faiss" directory, I couldn't find any relevant library files related to AVX2 support.
The error log I encountered was generated by the "loader.py" file.
I want to know if AVX2 support needs to be manually included and how to obtain it.
Possibly related content:
https://github.com/kyamagu/faiss-wheels/issues/39
https://github.com/facebookresearch/faiss/issues/1711
# Platform

OS: windows 10

Faiss version: faiss-cpu-1.7.4

Installed from: pip install 

Faiss compilation options:

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

```
2023-05-23 16:28:27,716 - INFO - Loading faiss with AVX2 support.
2023-05-23 16:28:27,716 - INFO - Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-23 16:28:27,716 - INFO - Loading faiss.
2023-05-23 16:28:27,755 - INFO - Successfully loaded faiss.
```
```
has_AVX2 = "AVX2" in supported_instruction_sets()
if has_AVX2:
    try:
        logger.info("Loading faiss with AVX2 support.")
        from .swigfaiss_avx2 import *
        logger.info("Successfully loaded faiss with AVX2 support.")
    except ImportError as e:
        logger.info(f"Could not load library with AVX2 support due to:\n{e!r}")
        # reset so that we load without AVX2 below
        has_AVX2 = False

if not has_AVX2:
    # we import * so that the symbol X can be accessed as faiss.X
    logger.info("Loading faiss.")
    from .swigfaiss import *
    logger.info("Successfully loaded faiss.")
```

I've heard that not introducing this support can lead to more than a 10-fold reduction in the efficiency of vector searches...
Any kind of help would be appreciated!

**Comment by mdouze** [comment]
pip is not supported to install Faiss. Please use conda.
