### ISSUE TITLE
Wiki: The first link is broken (404)

### ISSUE THREAD

**Issue by PeterMortensen** [facebookresearch/faiss#2875]
# Summary

The first link on [the wiki main page](https://github.com/facebookresearch/faiss/wiki) is broken (404).

# Reproduction instructions

Open the *[Facebook AI Research](https://research.fb.com/category/facebook-ai-research-fair/)* link.

Result: *"404 Page Not Found"*

**Comment by mlomeli1** [comment]
thank you for flagging this @PeterMortensen , I've updated the link.
