### ISSUE TITLE
Segfault when searching an index

### ISSUE THREAD

**Issue by jsilter** [facebookresearch/faiss#2878]
# Summary

Segfault when searching an index after importing a module from the [transformers library](https://huggingface.co/docs/transformers/index). 

# Platform

OS: (edit: ) MacOS 13.2.1 (have not tested other OSes)

Faiss version: 1.7.4

Installed from: pip

Faiss compilation options: None

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

```
import transformers.modeling_tf_utils  # <-- comment this statement and it runs fine
import transformers
import tensorflow

import numpy as np
d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

import faiss                   # make faiss available
index = faiss.IndexFlatL2(d)   # build the index
print(index.is_trained)
index.add(xb)                  # add vectors to the index
print(index.ntotal)

k = 4                          # we want to see 4 nearest neighbors
D, I = index.search(xb[:5], k) # sanity check
print(I)
print(D)
D, I = index.search(xq, k)     # actual search
print(I[:5])                   # neighbors of the 5 first queries
print(I[-5:])                  # neighbors of the 5 last queries
```

With this import in place I get the following output:

> True
> 100000
> zsh: segmentation fault

After commenting out the import at the top, the output is as expected:

> True
> 100000
> [[  0 393 363  78]
>  [  1 555 277 364]
>  [  2 304 101  13]
>  [  3 173  18 182]
>  [  4 288 370 531]]
> [[0.        7.1751733 7.20763   7.2511625]
>  [0.        6.3235645 6.684581  6.7999454]
>  [0.        5.7964087 6.391736  7.2815123]
>  [0.        7.2779055 7.5279875 7.6628466]
>  [0.        6.7638035 7.2951202 7.368815 ]]
> [[ 381  207  210  477]
>  [ 526  911  142   72]
>  [ 838  527 1290  425]
>  [ 196  184  164  359]
>  [ 526  377  120  425]]
> [[ 9900 10500  9309  9831]
>  [11055 10895 10812 11321]
>  [11353 11103 10164  9787]
>  [10571 10664 10632  9638]
>  [ 9628  9554 10036  9582]]

The `transformers` and `tensorflow` imports don't cause an error by themselves.

**Comment by mdouze** [comment]
This is presumably on a Mac. Please install faiss via anaconda.

**Comment by jsilter** [comment]
Yup it's a Mac. Error does not occur in a conda environment.

**Comment by mdouze** [comment]
only installing via (ana)conda is supported.
