### ISSUE TITLE
Why IndexHNSWPQ does not accept nbits as argument in constructor?

### ISSUE THREAD

**Issue by hazzus** [facebookresearch/faiss#2888]
I am not sure why 8 is hardcoded as IndexPQ constructor calling from IndexHNSWPQ constructor, [exact location in code](https://github.com/facebookresearch/faiss/blob/main/faiss/IndexHNSW.cpp#L890).  

Is there any purpose why nbits are fixed to 8, if I change it, will it affect? I see that other indexes that use ProductQuantizer accept nbits as argument for constructor.

**Comment by mdouze** [comment]
Absolutely, it's a limitation that dates back to the time when nbits=8 was the only supported setting. 

It is possible to work around this by changing the number of bits after construction. If you tell me if python or C++ I can give some code for that. 

Enhancement is to add nbits to the constructor (and index_factory).

**Comment by hazzus** [comment]
We already tried and implemented in our project something like this snippet, maybe you can tell if it's ok
```c++

struct IndexHNSWPQ : ::faiss::IndexHNSWPQ {
  IndexHNSWPQ() = default;
  IndexHNSWPQ(int d, int M, int pq_m, int nbits, ::faiss::MetricType metric);
  void train(int64_t n, const float* x) override;
};

IndexHNSWPQ::IndexHNSWPQ(int d, int M, int pq_m, int nbits, ::faiss::MetricType metric)
  : ::faiss::IndexHNSWPQ(d, pq_m, M) {
  delete storage;
  storage = new ::faiss::IndexPQ(d, pq_m, nbits, metric);
}

void IndexHNSWPQ::train(int64_t n, const float* x) {
  ::faiss::IndexHNSW::train(n, x);
  (dynamic_cast<::faiss::IndexPQ*>(storage))->pq.compute_sdc_table();
}
```

**Comment by mdouze** [comment]
the tricky decision is whether to up the nbits first or the metric
* nbits first --> more logical 
* metric first --> backwards compatibility.

**Comment by hazzus** [comment]
Thx for answers!

**Comment by KeyiChen** [comment]
experiencing the same issue, @mdouze 

> It is possible to work around this by changing the number of bits after construction. If you tell me if python or C++ I can give some code for that.

can you help point out how to edit pqindex's nbits in python, in order to use IndexHNSWPQ()? BTW I tried API IndexHNSW(index, M), where index i passed in a indexPQ, but it's aborted when invoking add.
