### ISSUE TITLE
module 'faiss' has no attribute 'StandardGpuResources'

### ISSUE THREAD

**Issue by whu-lyh** [facebookresearch/faiss#2892]
I have already installed faiss-gpu(1.7.2) using pip install, seen as followings:
`Requirement already satisfied: faiss-gpu in /opt/conda/lib/python3.7/site-packages (1.7.2)`
But, I still meet this error, someone could help me? thanks
```
res = faiss.StandardGpuResources()
flat_config = faiss.GpuIndexFlatConfig()
flat_config.useFloat16 = True
flat_config.device = 0
faiss_index = faiss.GpuIndexFlatL2(res, global_feature_dim, flat_config)
```

**Comment by mlomeli1** [comment]
hi @whu-lyh , could you show me your environment's packages via `pip freeze` and `conda list`? I suspect you have installed `faiss-cpu` that is conflicting with `faiss-gpu`. If so, please delete `faiss-cpu` and try running your code again.

**Comment by whu-lyh** [comment]
Thanks @mlomeli1 , It works! I found that the cpu version is mis-installed after gpu version installation. And, only one version could be installed? Once the cpu version has been installed, the gpu version doesn't work anymore.

**Comment by mlomeli1** [comment]
That's great! You only need to install faiss-gpu and you will have access to both cpu and gpu functionalities @whu-lyh

**Comment by Minalinnski** [comment]
Hi! I was facing the same issue when faiss-gpu 1.7.2 is installed, and after I remove faiss-cpu package, It throws the error:
`ModuleNotFoundError: No module named 'faiss'` for line `import faiss`
My Python version is 3.9.17 and I'm working on Linux environment. Would you please help me with this?

**Comment by whu-lyh** [comment]
reinstall the fass-gpu, and it works.

**Comment by binwensun** [comment]
> 你好@whu-lyh，您能通过`pip freeze`和向我展示您环境的软件包`conda list`吗？我怀疑您安装了`faiss-cpu`与 冲突的`faiss-gpu`。如果是这样，请删除`faiss-cpu`并尝试再次运行您的代码。 另请注意，我们不支持 pip 安装，我们首选 faiss-gpu 的 conda 安装方法。

thx! it works!
