### ISSUE TITLE
Question on add/search for gpu index multiple

### ISSUE THREAD

**Issue by paryang** [facebookresearch/faiss#291]
Hi,
I use index_cpu_to_gou_multiple to convert index to 4 gpus, and then Failed to use index->add and index->search which gives a 'segmentation fault(coredumped). However, when use 1 gpus for index_cpu_to_gpu_multiple and index_cpu_to_gpu, both give correct results. 
Is there anything special todo for add/search operation for multiple gpus index?or would mind to tell me how to do it. Thx

**Comment by mdouze** [comment]
Hi
Please see 
https://github.com/facebookresearch/faiss/wiki/Troubleshooting
on how to report bugs.

**Comment by paryang** [comment]
Hi, Here is the c++ code i used to do the cpu2gpu_multiple: 

when use only one gpu, it's ok , but with gpus more than 2, it crashed.

void cpu2gpu4search_mul(faiss::Index* cpu_index, std::vector<float> query_vecs, const int k, std::vector<int> devices , const int nq, std::vector<faiss::Index::idx_t>* ref_indices)
{
        faiss::gpu::StandardGpuResources* res = new faiss::gpu::StandardGpuResources;
        std::vector<faiss::gpu::StandardGpuResources*> resources;
        faiss::gpu::GpuMultipleClonerOptions* options = new faiss::gpu::GpuMultipleClonerOptions();
        options->indicesOptions=faiss::gpu::INDICES_64_BIT;
        options->useFloat16CoarseQuantizer = false;
        options->useFloat16 = false;
        options->usePrecomputed = false;
        options->reserveVecs = 0;
        options->storeTransposed = false;
        options->verbose = true;
        options->shard = false;
        //options->shard_type = 1;
        for(auto i = devices.begin(); i != devices.end(); i++)
        {       
                resources.push_back(res);
        }
        faiss::gpu::GpuIndexIVFPQ* index = dynamic_cast<faiss::gpu::GpuIndexIVFPQ*>(faiss::gpu::index_cpu_to_gpu_multiple((std::vector<faiss::gpu::GpuResources*> &)resources, devices, cpu_index));
        index->setNumProbes(_NumProbes_);
        std::vector<float> ref_distance(nq * k, 0);
        index->search(nq, query_vecs.data(), k, ref_distance.data(), ref_indices->data());
        delete options;
        delete res;
}
here is how i set the devices. 
std::vector<int> dev;
dev.push_back(2);

**Comment by paryang** [comment]
@mdouze
 Hi, Here is the c++ code i used to do the cpu2gpu_multiple:

when use only one gpu, it's ok , but with gpus more than 2, it crashed.

void cpu2gpu4search_mul(faiss::Index* cpu_index, std::vector query_vecs, const int k, std::vector devices , const int nq, std::vectorfaiss::Index::idx_t* ref_indices)
{
        faiss::gpu::StandardGpuResources* res = new faiss::gpu::StandardGpuResources;
        std::vectorfaiss::gpu::StandardGpuResources* resources;
        faiss::gpu::GpuMultipleClonerOptions* options = new faiss::gpu::GpuMultipleClonerOptions();
        options->indicesOptions=faiss::gpu::INDICES_64_BIT;
        options->useFloat16CoarseQuantizer = false;
        options->useFloat16 = false;
        options->usePrecomputed = false;
        options->reserveVecs = 0;
        options->storeTransposed = false;
        options->verbose = true;
        options->shard = false;
        //options->shard_type = 1;
        
        for(auto i = devices.begin(); i != devices.end(); i++)
        {
                resources.push_back(res);
        }
        faiss::gpu::GpuIndexIVFPQ* index = dynamic_castfaiss::gpu::GpuIndexIVFPQ*     (faiss::gpu::index_cpu_to_gpu_multiple((std::vectorfaiss::gpu::GpuResources* &)resources, devices, cpu_index));
        index->setNumProbes(NumProbes);
        std::vector ref_distance(nq * k, 0);
        index->search(nq, query_vecs.data(), k, ref_distance.data(), ref_indices->data());
        delete options;
        delete res;
}
here is how i set the devices.
        std::vector dev;
         @dev.push_back(2);
        //dev.push_back(3);

**Comment by mdouze** [comment]
You should use one separate resource object per GPU.

**Comment by paryang** [comment]
@mdouze I don't really understang your suggestions. I tried to to this and keep other codes unchagned:
faiss::gpu::StandardGpuResources* res_0 = new faiss::gpu::StandardGpuResources();
faiss::gpu::StandardGpuResources* res_1 = new faiss::gpu::StandardGpuResources();

std::vector<faiss::gpu::StandardGpuResources*> resources;
resources.push_back(res_0);
resources.push_back(res_1);
I think these two resources are separated per GPU. 

still get a core dumped at index->setNumProbes(NumProbes) or index->search, index->add() as well.

And can you give me a sample of using multi gpus? I get quite confused with it. In python, it works quite ok.

**Comment by mdouze** [comment]
`index_cpu_to_gpu_multiple` does not return a `GpuIndexIVFPQ`. Please do not cast it.

**Comment by paryang** [comment]
@mdouze 
I know index_cpu_to_gpu_multiple returns  faiss:index*, but if not return support GPUIndexIVFPQ, how can I get a IVFPQ index? the index saved in trained by GPUIndexIVFPQ. I mean, in this case, how to keep the Index format same as trained.

**Comment by mdouze** [comment]
index_cpu_to_gpu_multiple returns an IndexShards. To save the result you should: 
- move all the shard indexes to CPU 
- merge them together into a single IndexIVFPQ 
- save the IndexIVFPQ
