### ISSUE TITLE
Does the faiss library have plans to support scalar filtering?

### ISSUE THREAD

**Issue by anlongfei** [facebookresearch/faiss#2912]
Does the faiss library have plans to support scalar filtering functionality?
In actual production processes, vector queries and scalar filtering are often used in combination. In the vector query process, the scalar is first checked to see if it meets the requirements. If it does not meet the requirements, vector similarity calculation is not performed, which can greatly improve retrieval speed.

**Comment by asadoughi** [comment]
See `IDSelector` in https://github.com/facebookresearch/faiss/wiki/Setting-search-parameters-for-one-query#searching-in-a-subset-of-elements
