### ISSUE TITLE
Different word vectors have different memories

### ISSUE THREAD

**Issue by CodePythonFollow** [facebookresearch/faiss#2915]
index type IndexHNSWFlat 
Wondering if different word vectors take up different amounts of memory?

I add the same number of word vectors to two servers, the one normal and the other bad alloc error. 
I wonder if the index adds a certain amount of data will rebuild a new index. It is the reason for alloc error，this is the cause of an index allocation error.

**Comment by mdouze** [comment]
Allocation for the arrays in IndexHNSW relies on std::vector. 
Depending on the platform, reallocation policies may change.

**Comment by CodePythonFollow** [comment]
Thank you for your reply. I built an index with larger memory and performed great when deployed on a machine that is suitable for memory.
