### ISSUE TITLE
Support for MacOS Metal (MPS) as GPU

### ISSUE THREAD

**Issue by slavag** [facebookresearch/faiss#2928]
# Summary

Support for MacOS Metal (MPS) as GPU

# Platform

OS: Macbook pro M1 Max macOS 13.4

Is there's plans to support Mac metal (mps) as GPU ?

Thanks

**Comment by mdouze** [comment]
Not on our side.

**Comment by LRancez** [comment]
Hi there, pytorch now supports Metal out of the box under the mps backend `torch.mps.is_available()`
But the `pip install faiss-gpu` is complaining that no version is available on MacOS with Metal.
Is there any way to make faiss work with torch.mps ?

**Comment by n0kovo** [comment]
BUMP

**Comment by ShalomRochman** [comment]
BUMP

**Comment by DimitrisAlivas** [comment]
Any update on this one?

**Comment by jolespin** [comment]
This would be great to have for Mac users without access to Nvidia...

**Comment by rjurney** [comment]
Please!

**Comment by openSourcerer9000** [comment]
Add MPS or faiss the consequences!
