### ISSUE TITLE
Plain C interface

### ISSUE THREAD

**Issue by Enet4** [facebookresearch/faiss#293]
Faiss is quite an impressive library, and I was hoping to be able to use it in more development environments other than C++ or Python. I'm particularly interested in using this library in Rust. Writing bindings for Rust is easy when a library provides a plain C API. Unfortunately, SWIG does not support Rust, and as far as I can tell, there is currently no C interface available which Rust could link against.

With that in mind, I'm slowly making a C wrapper of Faiss by hand ([branch](https://github.com/Enet4/faiss/tree/c_api)). I got enough of it covered in order to build and run the example program below. I'm writing an issue here in case more people are interested in this becoming part of the main repository eventually. I'm also open to feedback, since I might be taking an unnecessarily tedious approach. Edit: I found [this](https://github.com/facebookresearch/faiss/issues/228#issuecomment-341038240) in one of the other issues, which is an interesting minimalist approach, but I'm hoping for a _de facto_ wrapper with good error handling and completeness.

```c
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#include "error_c.h"
#include "Index_c.h"
#include "IndexFlat_c.h"
#include "AutoTune_c.h"

inline double drand() {
    return (double)rand() / (double)RAND_MAX;
}

int main() {
    time_t seed = time(NULL);
    srand(seed);
    printf("Generating some data...\n");
    int d = 128;                           // dimension
    int nb = 100000;                       // database size
    int nq = 10000;                        // nb of queries
    float *xb = malloc(d * nb * sizeof(float));
    float *xq = malloc(d * nq * sizeof(float));

    for(int i = 0; i < nb; i++) {
        for(int j = 0; j < d; j++) xb[d * i + j] = drand();
        xb[d * i] += i / 1000.;
    }
    for(int i = 0; i < nq; i++) {
        for(int j = 0; j < d; j++) xq[d * i + j] = drand();
        xq[d * i] += i / 1000.;
    }

    printf("Building an index...\n");

    FaissIndex* index = NULL;
    int c = faiss_index_factory(&index, d, "Flat", METRIC_L2);  // use factory to create index
    if (c) {
        fprintf(stderr, "%s", faiss_get_last_error());
        exit(-1);
    }
    printf("is_trained = %s\n", faiss_Index_is_trained(index) ? "true" : "false");
    faiss_Index_add(index, nb, xb);                     // add vectors to the index
    printf("ntotal = %ld\n", faiss_Index_ntotal(index));

    printf("Searching...\n");
    int k = 5;

    {       // sanity check: search 5 first vectors of xb
        long *I = malloc(k * 5 * sizeof(long));
        float *D = malloc(k * 5 * sizeof(float));
        int c = faiss_Index_search(index, 5, xb, k, D, I);
        if (c != 0) {
            fprintf(stderr, "%s", faiss_get_last_error());
            exit(-1);
        }
        printf("I=\n");
        for(int i = 0; i < 5; i++) {
            for(int j = 0; j < k; j++) printf("%5ld (d=%2.3f)  ", I[i * k + j], D[i * k + j]);
            printf("\n");
        }
        free(I);
        free(D);
    }
    {       // search xq
        long *I = malloc(k * nq * sizeof(long));
        float *D = malloc(k * nq * sizeof(float));
        int c = faiss_Index_search(index, 5, xb, k, D, I);
        if (c != 0) {
            fprintf(stderr, "%s", faiss_get_last_error());
            exit(-1);
        }
        printf("I=\n");
        for(int i = 0; i < 5; i++) {
            for(int j = 0; j < k; j++) printf("%5ld (d=%2.3f)  ", I[i * k + j], D[i * k + j]);
            printf("\n");
        }
        free(I);
        free(D);
    }

    printf("Freeing index...\n");
    faiss_Index_free(index);
    printf("Done.\n");

    return 0;
}
```

**Comment by mdouze** [comment]
Hi 
Thanks for the C interface. The `faiss_Index_search`, `faiss_Index_add` and `faiss_IndexFlat_free` look reasonable. 

I  would suggest to use the faiss::index_factory and the `faiss::ParameterSpace` objects to be able to construct all types of Faiss objects and change their parameters. 

The relevant functions would look like: 
```
FaissIndex *faiss_Index_factory(int d, const char *key, int metric_type);
void set_index_parameter(FaissIndex *index, const char *name, double value);
```

This would avoid having to define sub-classes and cast back and forth between them.

About integration: we welcome pull requests, and there is certainly an interest to have a pure C interface. We expect you to maintain the interface though.

**Comment by Enet4** [comment]
@mdouze Thanks for the feedback! Indeed, I think I included (or at least planned to include) that factory function in my branch, and `set_index_parameter` can follow suit.

There are yet two concerns here that I would like to address before any PR takes place. Namely, there should be access to GPU implementations (as far as I understand, this involves implementing the `index_cpu_to_gpu` adaptor and a C-compatible type for representing the GPU resources); and although exceptions are being captured, retrieving the full error content is not very trivial. I'm thinking about building a new error type built from exceptions, and exposing a `last_error()` function.

Once that is done, I should be comfortable with sending a PR and maintaining this API. If all goes well, I might also make the respective bindings for Rust, as an external crate.

**Comment by Enet4** [comment]
A status update: the essential parts of the API are done, including GPU support. They are all in [this branch](https://github.com/Enet4/faiss/tree/c_api), and I'll be sending a PR soon.

**Comment by mdouze** [comment]
Thanks, looks like a considerable body of code...

**Comment by Enet4** [comment]
The API is in, so I'm closing this issue. I'll try to pay attention to new issues related to the C interface for the time being.
