### ISSUE TITLE
PQ fvec_inner_products_ny

### ISSUE THREAD

**Issue by shiwanghua** [facebookresearch/faiss#2938]
for function 'fvec_inner_products_ny', does it worth to consider d==2 in particularly since d is always very small for PQ dsub ?

```
void fvec_inner_products_ny (float * ip,
                             const float * x,
                             const float * y,
                             size_t d, size_t ny)
{
    if(d == 2){
        for (size_t i = 0; i < ny; i++) {
            ip[i] = x[0] * y[0] + x[1] * y[1];
            y += 2;
        }
        return;
    }
    for (size_t i = 0; i < ny; i++) {
        ip[i] = fvec_inner_product (x, y, d);
        y += d;
    }
}
```

**Comment by mdouze** [comment]
If the performance of this code is critical, it's probably better to implement it in SIMD in 
https://github.com/facebookresearch/faiss/blob/main/faiss/utils/distances_simd.cpp

**Comment by alexanderguzhva** [comment]
It is questionable whether a compiler is smart enough to optimize this case via SIMD. Maybe, you'll need to write SIMD code manually.

**Comment by shiwanghua** [comment]
> If the performance of this code is critical, it's probably better to implement it in SIMD in https://github.com/facebookresearch/faiss/blob/main/faiss/utils/distances_simd.cpp

Test using sse or avx does not get clear improvement compared to the special consideration for d=2.
