### ISSUE TITLE
A potentially misleading point in the arxiv paper

### ISSUE THREAD

**Issue by Stonesjtu** [facebookresearch/faiss#294]
Hi, I read the preprint paper on arxiv and found the `overview of GPU` part very descriptive. However there's one point I can't agree on.

The paper says at `3.1 architecture` -> `grid and kernels`
>Grids and kernels. Blocks are organized in a grid of blocks in a kernel. Each block is assigned a grid relative ID. The kernel is the unit of work (instruction stream with arguments) scheduled by the host CPU for the GPU to execute. **After a block runs through to completion, new blocks can be scheduled. Blocks from different kernels can run concurrently.** Ordering between kernels is controllable via ordering primitives such as streams and events.

But the blocks are arranged in random order and blocks from the same kernels can also run concurrently.
As documented by CUDA programming guide:
>Thread blocks are required to execute independently: It must be possible to execute them in any order, in parallel or in series. This independence requirement allows thread blocks to be scheduled in any order across any number of cores as illustrated by Figure 5, enabling programmers to write code that scales with the number of cores.

I think the original text may be somehow misleading that blocks will run in serial order.
Correct me if i misunderstand anything.
Ref: http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html

**Comment by wickedfoo** [comment]
The original text doesn't imply that blocks run in serial order; it implies that once a block is instantiated, it runs to completion, thus (partially) occupying the SM until it finishes. The Cooperative Groups API I believe changes this a bit (that blocks can be pre-empted, and possibly the state is serialized somewhere, freeing the SM to run other blocks / kernels).
