### ISSUE TITLE
Approx top k

### ISSUE THREAD

**Issue by AlbeLepi** [facebookresearch/faiss#2954]
# Summary

Hi! I saw that faiss provides an approximate version of the top k search. Unfortunately, I wasn't able to find how to execute this search with my queries. Can you help me?

Running on: CPU

Interface: Python

**Comment by mlomeli1** [comment]
Please have a look at our wiki: https://github.com/facebookresearch/faiss/wiki/Getting-started
and https://github.com/facebookresearch/faiss/wiki/Faster-search

**Comment by alexanderguzhva** [comment]
@AlbeLepi , if you're talking about approximate topk search facilities that were added in 1.7.4 (I think), then it is available for IndexBinaryIVF, IndexResidualQuantizer and IndexProductResidualQuantizer.
