### ISSUE TITLE
Query 1000 vector in 0.1 billion dataset failed using multi-gpus shard

### ISSUE THREAD

**Issue by 0DF0Arc** [facebookresearch/faiss#296]
Hi, 
I'm using multi gpus to do add and search with option.shard = true. when query, get a warning message like 'increase tmp memory to avoid cudaMalloc or decrease query/add size'. 
Is there any connection between query and data ? or what's the relation between dataset size with tmp memory? 

Besides, this not occured when option.shard =false

**Comment by wickedfoo** [comment]
Can you copy the warning that is being given here (i.e., the sizes reported)?, and which function you are calling when it prints the warning?

The temporary memory is a region of memory (1 - 2 GB) that Faiss GPU grabs up front on the GPU for performing temporary calculations in. Typically most everything you do should fit into this space. If you have disabled the temporary memory, the warning will print for everything.

Faiss will still calculate things correctly when the warning goes off (as long as the cudaMalloc request can be satisfied; i.e., you have enough GPU memory), it will just be slower.
