### ISSUE TITLE
add_with_ids does not work for IndexIVFPQ when it should according to documentation

### ISSUE THREAD

**Issue by siddhsql** [facebookresearch/faiss#2963]
using `IVF250,PQ64x4fs,RFlat` as example I get this:

```
RuntimeError: Error in virtual void faiss::Index::add_with_ids(faiss::idx_t, const float *, const faiss::idx_t *) at /Users/runner/work/faiss-wheels/faiss-wheels/faiss/faiss/Index.cpp:45: add_with_ids not implemented for this type of index
```

but the [docs](https://github.com/facebookresearch/faiss/wiki/Pre--and-post-processing#ids-in-the-indexivf) say:

>The IndexIVF sub-classes always store vector IDs. Therefore, the IndexIDMap's additional table is a waste of space. The IndexIVF offers add_with_ids natively.

what gives?

**Comment by mdouze** [comment]
It's the Rflat that does not support `add_with_ids` because it needs sequential ids. 
If you want to remap the ids, please use `IVF250,PQ64x4fs,RFlat,IDMap`
