### ISSUE TITLE
Can IVFPQ merge index like IndexIVF::merge_from ?

### ISSUE THREAD

**Issue by shiwanghua** [facebookresearch/faiss#2970]
It seems like the IndexIVFPQ::merge_from() does not be implemented ?

https://github.com/facebookresearch/faiss/blob/main/faiss/IndexIVFPQ.cpp

**Comment by mdouze** [comment]
It is implemented in the parent class IndexIVF.

**Comment by shiwanghua** [comment]
> It is implemented in the parent class IndexIVF.

IndexIVF only merges the IVF list, what about the PQ centroids when the centroids of each index are different ?

Each index maybe trained from one slice of a big dataset because the dataset is too big to train all at once.

https://github.com/facebookresearch/faiss/blob/821a401ae9ecee7f6b18c5dea70021a88acbc88b/faiss/IndexIVF.cpp#L1143

**Comment by mdouze** [comment]
You cannot merge IVFPQ indexes with different PQ centroids.

**Comment by shiwanghua** [comment]
> You cannot merge IVFPQ indexes with different PQ centroids.

But I can collect all the PQ centroids in one index, for each IVF list, use a prefix array to record the No. of the PQ centroids.

**Comment by mdouze** [comment]
That's not a regular IVFPQ.
