### ISSUE TITLE
TypeError: Wrong number or type of arguments for overloaded function 'index_cpu_to_gpu_multiple'.

### ISSUE THREAD

**Issue by zkllong-21** [facebookresearch/faiss#2976]
# origin code
xb, xq = vec.copy(), vec.copy()
normalize_L2(xb)
normalize_L2(xq)
nlist, dim = 1000, 100
quantizer = faiss.IndexFlatL2(dim)  # the other index
index = faiss.IndexIVFFlat(quantizer, dim, nlist, faiss.METRIC_INNER_PRODUCT)
gpu_index = faiss.index_cpu_to_all_gpus(index, co=res)
gpu_index.train(xb)
gpu_index.add(xb)
print(gpu_index.is_trained)

# Summary
TypeError: Wrong number or type of arguments for overloaded function 'index_cpu_to_gpu_multiple'.
  Possible C/C++ prototypes are:
    faiss::gpu::index_cpu_to_gpu_multiple(std::vector< faiss::gpu::GpuResourcesProvider * > &,std::vector< int > &,faiss::Index const *,faiss::gpu::GpuMultipleClonerOptions const *)
    faiss::gpu::index_cpu_to_gpu_multiple(std::vector< faiss::gpu::GpuResourcesProvider * > &,std::vector< int > &,faiss::Index const *)

**Comment by zkllong-21** [comment]
version
faiss-gpu：1.7.3

**Comment by mlomeli1** [comment]
could you please submit a complete minimal example @zkllong-21 and carefully check which methods you want to use? The code you pasted is incomplete and you are using `faiss.index_cpu_to_all_gpus()` but you are reporting an error from `faiss.index_cpu_to_gpu_multiple()`. Thanks

**Comment by zkllong-21** [comment]
I made a mistake，actually my issue is the same problem [https://github.com/facebookresearch/faiss/issues/1793](url)

**Comment by HarryCaveMan** [comment]
Still getting this issue and the referenced issue no longer exists in github. There seems to be a mismatch between the  two available signatures shown for `faiss::gpu::index_cpu_to_gpu_multiple` and this call inside `index_cpu_to_gpu_multiple_py`:
`index_cpu_to_gpu_multiple(vres, vdev, index, co)`
Because neither of those signatures take 4 args
