### ISSUE TITLE
Need for custom index size storage 

### ISSUE THREAD

**Issue by lekhit** [facebookresearch/faiss#2977]
# summary
Need to create index files that are small about 10MB ( storage limitation ) . Currently there is a single method to save index. No documentation was found regarding. 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
What is the size of the data you want to index? 
Please refer to 
https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index
