### ISSUE TITLE
Accessing SwigPythonObject

### ISSUE THREAD

**Issue by SilvioM97** [facebookresearch/faiss#2979]
Hi there,
I'm working, in Python, with the NSG index and I want to take a look at the adjacency lists of the nodes in my graph.
This is what I do:

```
import faiss
import numpy as np

D = 128
N = 1000
X = np.random.random((N, D)).astype(np.float32)
nlist = 1000  
R = 32
index = faiss.IndexNSGFlat(D, R, faiss.METRIC_L2)
index.build_type = 1 # use NNDescent to build the kNNG
index.add(X)
graph = index.nsg.final_graph # accessing to graph structure of NSG index
print(graph.data) # trying to access adjacency lists
```

and I get this error message: 

```
    print(graph.data) # trying to access data
AttributeError: 'SwigPyObject' object has no attribute 'data'
```
How can I access adjacency lists?

**Comment by mdouze** [comment]
This is not possible directly because the shared_ptr implementation is not exposed to SWIG. Marking as an enhancement to expose it, that could be useful.

**Comment by SilvioM97** [comment]
@mdouze thanks for your answer!
