### ISSUE TITLE
Updating pip package with changes in "Support Selector for IDMap #2848"

### ISSUE THREAD

**Issue by ariaattar** [facebookresearch/faiss#2988]
Hi, could you please update the python pip package with the changes in this PR #2848 

Currently building from source in a Docker container but the container startup time is very slow!

Thank you.

**Comment by mlomeli1** [comment]
hi @ariaattar , we don't support installation via pip, please use conda.

**Comment by vaaliferov** [comment]
Hi! The latest version of faiss-cpu is 1.7.4 (for both pip and conda). And there are no changes from PR #2848 included. Any info on the next release timeline ? Are there any options available except building from source or waiting for the next release ?

**Comment by mlomeli1** [comment]
hi @vaaliferov , thanks for checking, I can get back to you about when we will publish the next release. In the meantime, you can just use the nightly package that is published daily and includes all commited changes (until the day before), use:
````
conda install -c pytorch/label/nightly faiss-cpu
````

**Comment by ariaattar** [comment]
@mlomeli1 

With the conda nightly version of faiss 

`
if isinstance(faiss_index, faiss.swigfaiss.IndexIDMap
`

Raises an error

"module 'faiss' has no attribute 'swigfaiss'"

But when built from source ti

**Comment by ariaattar** [comment]
Accidentally closed ^

**Comment by mlomeli1** [comment]
@ariaattar why would you need to call faiss.swigfaiss in the first place? Can you try 
````
if isinstance(faiss_index, faiss.IndexIDMap)
````
