### ISSUE TITLE
Runnning Faiss on high dimensional dataset

### ISSUE THREAD

**Issue by nash169** [facebookresearch/faiss#2989]
Hi,
I am trying to run Faiss on a very high dimensional dataset (>40000). On the other hand the number of samples is relatively contained (in between 10k and 100k). I was testing different indexes implementations but when I perform the search they all return very wrong values of distances. Is it possible that I am incurring in some kind of max limit for the dimension of the feature space?

Thanks a lot.

**Comment by mdouze** [comment]
Faiss indexes are typically used for vector sized in the 100-1000 range. 
If the number of dimensions d is larger than index size n, then you can PCA down the vector size to n without loss of accuracy.

**Comment by nash169** [comment]
Thanks a lot for the quick answer! I'll try that.
