### ISSUE TITLE
Hamming distance

### ISSUE THREAD

**Issue by doublex** [facebookresearch/faiss#299]
Hello,

I have 64 bit hashes - using hamming distance.
As far as I understand I have to index the hashes as "float[64]" array: Every float reflects a bit - either 0.0 or 1.0.

Question:
Is there a chance to index the 64 bit hashes directly?

Best wishes
Marcus

**Comment by wickedfoo** [comment]
The main index types in Faiss are not oriented around binary hashes. This is something that we will likely not provide. How are you producing your binary hashes in the first place? Are they generated from floating-point vector data? If so, you'd have better luck operating on the original floating-point data.

**Comment by doublex** [comment]
Thanks!

**Comment by m0rtalis** [comment]
For anyone stumbling across this it's now supported [Wiki/Binary-indexes](https://github.com/facebookresearch/faiss/wiki/Binary-indexes)
