### ISSUE TITLE
Alternative in C for an edge device ? 

### ISSUE THREAD

**Issue by linux-devil** [facebookresearch/faiss#3000]
Do we have an alternative in C, as we look forward to integrate FAISS on the edge device running Ambarella CV 25 ?

**Comment by mdouze** [comment]
I am very interested in ports of Faiss to all kinds of architectures. However, a C++ compiler is the minimum requirement currently. It would not make sense to rewrite everything in C.

**Comment by junjieqi** [comment]
closed since C++ compiler is minimum requirement
