### ISSUE TITLE
Can the query vector be multiple vectors?

### ISSUE THREAD

**Issue by LionLion888** [facebookresearch/faiss#3001]
Hi there,

I'm using faiss to calculate the similarity in order to idfetify the person is in the database or not, but I'm wondering to know can the query vector be multiple vectors or it can only be one vector?

If the query vector is multiple vectors, that means I give more than one image (same person) to search the person is in the database or not.

Code:
query_vector = [vector_1, vector_2, vector_3, vector_4]
distances, indices = index.search(**query_vector**, k)

**Comment by mlomeli1** [comment]
@LionLion888  yes it can, as per our wiki "xq for the query vectors, for which we need to find the nearest neighbors. Its size is nq-by-d if we have a single query vector, nq=1." 
wiki: https://github.com/facebookresearch/faiss/wiki/Getting-started

**Comment by LionLion888** [comment]
Hi mlomeli1,

Thanks for your reply, I got it!
Another question, if the query vectors is multiply, how to calculate the top k value? Is it take each of the distance or score and get the **average** distance or score then rank them to get the top k value?

**Comment by cydu-cloud** [comment]
@LionLion888 if you look at the Searching section of the wiki link above, you'll notice the format of the output. 

It won't do any magic average for you, instead it output all the raw data: 
two outputs: distances and index of vectors, in the format of nq rows, each raw with k values there. 

nq => the number of query you put in, default to be 1.
k => the top K nearest neighbors.  

https://github.com/facebookresearch/faiss/wiki/Getting-started#searching
