### ISSUE TITLE
What is the GPU version of product quantizer?  

### ISSUE THREAD

**Issue by zsk97** [facebookresearch/faiss#3003]
Hi there,

I am new to Faiss and I try to check the implementation of GpuIndexIVFPQ. However, it looks like that the GPU version can only receive a CPU coarser quantizer in all examples and test files. Does it mean that the training of production quantizer cannot be executed in GPU so far? I am not sure whether I missing anything. Thank you!

**Comment by mdouze** [comment]
The PQ codebooks are on GPU, see https://github.com/facebookresearch/faiss/blob/main/faiss/gpu/impl/IVFPQ.cuh#L163

At training time, it could be that the PQ codes are trained on CPU. It does not matter much as PQ codebooks are small so they are cheap to compute.

**Comment by zsk97** [comment]
> The PQ codebooks are on GPU, see https://github.com/facebookresearch/faiss/blob/main/faiss/gpu/impl/IVFPQ.cuh#L163
> 
> At training time, it could be that the PQ codes are trained on CPU. It does not matter much as PQ codebooks are small so they are cheap to compute.

Thank you for your reply. I am sorry about that I do not clarify my question. In the search function, we need to first search the coarse quantizer. Please look at here. https://github.com/facebookresearch/faiss/blob/88b7255830d7c087847b9b839ad94affa4d8f104/faiss/gpu/impl/IVFPQ.cu#L517

The details implementation can be found here. https://github.com/facebookresearch/faiss/blob/88b7255830d7c087847b9b839ad94affa4d8f104/faiss/gpu/impl/IVFBase.cu#L502

However, I do not find the GPU implementation of this coarse quantizer. I am not sure if I miss anything. Thank you!

**Comment by mdouze** [comment]
This is a virtual function so it depends on the coarse quantizer type. 
Typically the GPU coarse quantizer is a GpuIndexFlat.
