### ISSUE TITLE
RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) at /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open vectorstore/db_faiss/index.faiss for reading: No such file or directory

### ISSUE THREAD

**Issue by vishnumur777** [facebookresearch/faiss#3004]
# Summary

# Platform

OS: Endeavour OS

Faiss version: 

Installed from: pip

Running on:
- [x] CPU

Interface: 
- [x] Python

# Reproduction instructions

RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) at /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open vectorstore/db_faiss/index.faiss for reading: No such file or directory

at line 'db=FAISS.load_local(FAISS_PATH,embeddings) '
also I have run ingest.py before running this

**Comment by vishnumur777** [comment]
Traceback (most recent call last):
  File "/home/hdd/MLProjects/yellow-paper-physics-bot/models.py", line 61, in <module>
    f=final_result("Define Weight")
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdd/MLProjects/yellow-paper-physics-bot/models.py", line 57, in final_result
    qa_result = qa_bot()
                ^^^^^^^^
  File "/home/hdd/MLProjects/yellow-paper-physics-bot/models.py", line 49, in qa_bot
    db = FAISS.load_local(DB_FAISS_PATH, embeddings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/varun/.local/lib/python3.11/site-packages/langchain/vectorstores/faiss.py", line 696, in load_local
    index = faiss.read_index(
            ^^^^^^^^^^^^^^^^^
  File "/home/varun/.local/lib/python3.11/site-packages/faiss/swigfaiss_avx2.py", line 10206, in read_index
    return _swigfaiss_avx2.read_index(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) at /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open vectorstore/db_faiss/index.faiss for reading: No such file or directory

**Comment by mdouze** [comment]
what did you expect? 
Besides this is probably related to the langchain wrapper of Faiss. Please submit the report there.

**Comment by umerkhan0298** [comment]
Make sure you save the database locally first.

db = FAISS.from_documents(texts, embeddings)
db.save_local(DB_FAISS_PATH)
db = FAISS.load_local(DB_FAISS_PATH, embeddings, allow_dangerous_deserialization=True)

I was getting the same error but when i added this db.save_local line. The error got resolve.

**Comment by Coollaitar** [comment]
```
import pathlib 

FAISS_INDEX_PATH = pathlib.Path("faiss_index")

new_db = FAISS.load_local(str(FAISS_INDEX_PATH), embeddings, allow_dangerous_deserialization=True)
vector_store = FAISS.from_texts(text_chunks,embeddings)
vector_store.save_local(str(FAISS_INDEX_PATH))
```

Above Worked For Me!

**Comment by PalashDS** [comment]
RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open C:\Users\palas\Desktop\AIP\Streamlit app\faiss_index for reading: Permission denied

Any clue in this how to solve this issue
