### ISSUE TITLE
Is there a way to find the m cluster_ids of each original data after building an index?

### ISSUE THREAD

**Issue by estella778** [facebookresearch/faiss#3005]
When using IndexIVFPQ to build an index, kmeans algorithm is used to generate m cluster_ids ranging from 0 to 255 for each original data.
After using IndexIVFPQ to build an index, is there a convenient way to find the m cluster_ids of each original data?

**Comment by mdouze** [comment]
It is unclear whether you want:

- the cluster ids from the inverted file, which you get with `index.quantizer.search(x, 1)[1]`

- the PQ codes, that you can get with `index.pq.compute_codes(x)`
