### ISSUE TITLE
add with ids over 2^32 will get wrong id

### ISSUE THREAD

**Issue by David-Q** [facebookresearch/faiss#301]
hello, I am using faiss to create index for user feature. when using add_with_ids in creating ivfpq index, I find that user_id less than 2^32=4294967296 can work well but over 4294967296, will get a wrong id.  
for example, id= 7080030971,  i get a wrong result of 2785063675, which is actually the value of 7080030971 - 2^32.
Is this a bug or a limit of index?  thank you

**Comment by mdouze** [comment]
Hi, 
This code should be 64-bit safe. Are you using IndexIVFPQ or the GPU version? If GPU then what GPUIndicesOptions is it using?
https://github.com/facebookresearch/faiss/blob/master/gpu/GpuIndicesOptions.h#L16

**Comment by David-Q** [comment]
oh! i have found the point,  something wrong with my compile environment.

**Comment by David-Q** [comment]
really sorry to disturb...
after i fix the environment, it works~ 
thank you~
