### ISSUE TITLE
How does the similarity search calculate the distance or score with multiple query vectors?

### ISSUE THREAD

**Issue by LionLion888** [facebookresearch/faiss#3010]
When we select the similarity search function, such as IndexFlatL2, IndexHNSWFlat. How does it calculate the distance or score with multiple query vectors? 

If I have two query vectors, using cosine similarity as similarity search.

query vector 1:
rank1: database A image
rank2: database C image
rank3: database B image

query vector 2:
rank1: database A image
rank2: database B image
rank3: database D image

How does it combine the two query vector and get the final rank?

**Comment by mdouze** [comment]
The results are ranked independently. If you want to combine several query vectors, you have to do it yourself.
