### ISSUE TITLE
IndexFlatIP for 15 Mil (768D) vectors. 

### ISSUE THREAD

**Issue by rafayaar** [facebookresearch/faiss#3018]
# Summary

I want to store 15 Million 768 Dimensional vectors. Obviously it wont fit in RAM. For IndexPQ, we have to train the vectors.
Training can be done only on few vectors out of total, cause all 15M cant fit in RAM. I have to read in chunks
I tried training few vectors and adding all of them, but results are poor.
I want high accuracy index. 
What if of every chunk of data, I train the IndexPQ again and add same chunk afterwards, and do this whole 15M?

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

Each jsonl contains 1000 vectors. And I have 15000 of them.
Current implementation.
I have also tried IndexPQ method. 

```
%%time
vecs_count = 0
INDEX = faiss.IndexFlatIP(768)
for i in range(0,15000):
    vecs = np.zeros((1000,768),dtype='float32')
    
    filename = f"GPT-Neo-Output-Chunks/chunk_{i}.jsonl.out"
    
    with open(filename) as f:
        for i in range(0, 1000):
            data = ujson.loads(f.readline())
            vector = data['vectors'][0]
            vecs[vecs_count] = vector
            vecs_count += 1
    
    faiss.normalize_L2(vecs)
    INDEX.add(vecs)
    
    vecs_count = 0
    gc.collect()
```

**Comment by mdouze** [comment]
Please refer to https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index for general guidelines. 

You cannot retrain an index and IndexPQ has a small training capacity so it is not useful to train it on a large number of vectors.
