### ISSUE TITLE
Index search has return number limitation

### ISSUE THREAD

**Issue by Megan-xu** [facebookresearch/faiss#3022]
# Summary

The background is that we need to do the filtering based on data's metadata (other dimension) after the faiss index search. Therefore, we need to retrieval 10000+ results (the index has over 1 million data in total). But it is observed that the max return data count from the index (faiss.IndexHNSWFlat) search is around 1500. 
Would like to know the reason of the return number limitation and the way to work around (e.g., using the search params of PyCallbackIDSelector, the IDSelector is applied on the limited return or is applied on the whole dataset?)

# Platform

OS:  windows

Faiss version:  faiss-cpu==1.7.3

Installed from:  conda

Faiss compilation options:  N/A

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

\###### build index ######
input_list = []
sample_data = ['hello world']
for ii in range (1000000):
   input_list.append(embedding_generator(sample_data))
index = faiss.IndexHNSWFlat(dim, M)
index.hnsw.efConstruction = efConstruction
index.hnsw.efSearch = efSearch
index.add(np.array(input_list)) 

\##### search ########
request_return = 10000
test_query = ['hello new world']
test_list = embedding_generator(test_query)
sel = faiss.PyCallbackIDSelector(test_condition)
D, I = index.search(np.array(test_list), request_return, params=faiss.SearchParametersHNSW(sel=sel))

\#### return limitation: actual return is less than request return #####
len(I[0]) < request_return

**Comment by mdouze** [comment]
What is the number of final results that you need? I suspect that if you need to query 10k pre-filtering results, it means that the filter keeps <1% of the results. In that case it is probably better to apply the filter first (using eg. an inverted file) and do an exhaustive search on the filtered out results. 

Both options are implemented for the Big ANN 23 challenge, see here

https://github.com/harsha-simhadri/big-ann-benchmarks/blob/main/neurips23/filter/faiss/faiss.py

Unfortunately it is not well documented yet. I will add more explanations at some point.

**Comment by mdouze** [comment]
It is probably because the HNSW graph is disconnected.

**Comment by asadoughi** [comment]
Closing as the question is answered and no update from OP: HNSW has no limit in the size of the result list
