### ISSUE TITLE
Faiss use depreciated tistutils Version classes

### ISSUE THREAD

**Issue by kolergy** [facebookresearch/faiss#3025]
# Summary

Depreciation warning when using Faiss:
faiss/loader.py:28: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(numpy.__version__) >= "1.19":

# Platform
OS: pop-os 22.04 LTS (ubuntu based)

Faiss version: faiss-cpu               1.7.4

Installed from: pip
Python 3.11.4
numpy  1.24.3

Faiss compilation options: ?

Running on:
- [x ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x ] Python

# Reproduction instructions
load documents in a python 3.11.4 environement

**Comment by mdouze** [comment]
TODO fix this for py > 3.8

**Comment by mlomeli1** [comment]
This has been sorted in https://github.com/facebookresearch/faiss/pull/3191, closing.
