### ISSUE TITLE
Can HNSWPQ nbits parameter be made configurable?

### ISSUE THREAD

**Issue by jmazanec15** [facebookresearch/faiss#3027]
# Summary
For [IndexHNSWPQ](https://github.com/facebookresearch/faiss/blob/v1.7.4/faiss/IndexHNSW.cpp#L879),  I see the value for [`nbits`](https://github.com/facebookresearch/faiss/blob/v1.7.4/faiss/IndexPQ.h#L36) is hardcoded to 8. I wanted to know if this could possibly be made configurable?

I saw this issue from several years ago: #259, where reasoning for not going above 8 nbits on CPU was over concerns of keeping table in l1/l2 cache. However, I am wondering if improved recall may be worth the tradeoff in additional latency. Additionally, for graph-based algorithms, where fewer distance computations are made, I am wondering if the latency impact from not fitting table in l1 cache may not be as pronounced.

**Comment by mdouze** [comment]
Suppport for >8 bits per PQ has improved a lot, so we should support it in HNSW as well. 

Easy to address here with a default value of 8 

https://github.com/facebookresearch/faiss/blob/main/faiss/IndexHNSW.cpp#L889

the only issue is that the PQ parameters are intermixed with the HNSW parameters but there is no easy way around it wihtout breaking compatibiiuty.

**Comment by jmazanec15** [comment]
Sure, let me see if I can make the change without breaking bwc. I assume that we could use default of 8 as a way to avoid this in most cases.
