### ISSUE TITLE
A question of gpu clustering synchronization

### ISSUE THREAD

**Issue by zhaokang0826** [facebookresearch/faiss#303]
I want to use GPU to cluster, so I use the function: kmeans_clustering_gpu(...) in IndexProxy.h.

When I read the codes, I find a question:
kmeans_clustering_gpu(...) : ...clus.train (n, x, *index);... 
-> Clustering::train(...) : ...index.search (nx, x, 1, dis, assign);...
-> GpuIndexFlat::search(...) : ...fromDevice<faiss::Index::idx_t, 2>(outIndices, labels, stream);

As we can see above, In the function GpuIndexFlat::search(...), the last code copy "outIndices" in GPU to "labels" in CPU asynchronously. And then the code go back to the function Clustering::train(...), and use the "labels" data to do something else.

We do not use any stream synchronization commands to wait for the copy completed, why?

Hope to get the response, THX.

**Comment by mdouze** [comment]
Hi 
All GPU search functions that take CPU pointers have return when the whole result has been copied. to CPU.

**Comment by zhaokang0826** [comment]
If I use one GPU to cluster, which means the function Clustering::train() get a GpuIndexFlatL2 instance as it's parameter index (void Clustering::train (idx_t nx, const float* x_in, Index& index)). When the code goes to line 166 in Clustering.cpp, the function GpuIndexFlat::search is called actually. And the end of the function GpuIndexFlat::search (line 283 and 284 in file gpu/GpuIndexFlat.cu), two cudaMemcpyAsync commands happen, and then the code goes back to line 166 in Clustering.cpp without any stream synchronization.
How do you make the search function return when the whole result has been copied to CPU, can you give more details or tell me where am I wrong?

**Comment by zhaokang0826** [comment]
If I use one GPU to cluster, which means the function Clustering::train() get a GpuIndexFlatL2 instance as it's parameter index (void Clustering::train (idx_t nx, const float* x_in, Index& index)). 
When the code goes to line 166 in Clustering.cpp, the function GpuIndexFlat::search is called actually. And at the end of the function GpuIndexFlat::search (line 283 and 284 in file gpu/GpuIndexFlat.cu), two cudaMemcpyAsync commands happen, then the code goes back to line 166 in Clustering.cpp without any stream synchronization.

How do you make the search function return when the whole result has been copied to CPU, can you give me more details or educate me if I'm wrong?

Thank your very much.

**Comment by wickedfoo** [comment]
The copies are to non-pinned memory on the CPU, so the copy is always synchronous (despite the use of cudaMemcpyAsync), but still ordered with respect to the stream (vs. cudaMemcpy).

see the "Synchronous" section of this:
http://docs.nvidia.com/cuda/cuda-runtime-api/api-sync-behavior.html#api-sync-behavior__memcpy-async
