### ISSUE TITLE
Not found faiss_Index_free realisation 

### ISSUE THREAD

**Issue by fkurushin** [facebookresearch/faiss#3037]
Hi, I have seen `faiss_Index_free` used in examples: [1](https://github.com/facebookresearch/faiss/blob/main/c_api/example_c.c#L179), [2](https://github.com/facebookresearch/faiss/blob/main/c_api/gpu/example_gpu_c.c#L113) , but **I can't find realisation of this function.** I want to see, how such a big professionals did it, because I want to create an analogue in me fasttext-go-wrapper

Please, can someone shed some light on this?

**Comment by mdouze** [comment]
It is implemented here https://github.com/facebookresearch/faiss/blob/main/c_api/Index_c.cpp#L32

**Comment by fkurushin** [comment]
And `DEFINE_DESTRUCTOR ` defined in `macros_impl.h `
