### ISSUE TITLE
feature request: train progress or better docs on train progress.    Lesson learned:  no output in jupyter notebooks, but works in python regular

### ISSUE THREAD

**Issue by qrdlgit** [facebookresearch/faiss#3039]
I searched, googled, asked GPT4 - looked through C++ docs.  turned index.verbose to true, but I can't find anything which reports on progress during training.

faiss hangs in weird spots for strange reasons (eg: https://github.com/kyamagu/faiss-wheels/issues/54)

Also different indexes can take a lot more time.  

Is there any way to get progress / time estimates out of train?

**Comment by qrdlgit** [comment]
yeaaah... I was doing everything inside jupyter.  Didn't occur to me to try in regular python.  Apologies for the ping

**Comment by qrdlgit** [comment]
I had to re-open this, as tbh, I can't really follow the logging

Is there a way to calculate things like
- how long the rest of training will take 
- how much memory it consumes at present and how much more memory it will consume one embeds are added
- very roughly, how accurate it will be
- very roughly, how fast it will perform


```
IndexPreTransform::train: training chain 0 to 1
   Training chain component 0/1
  Input training set too big (max size is 65536), sampling 65536 / 6439924 vectors
OPQMatrix::train: training an OPQ rotation matrix for M=64 from 65536 vectors in 384D -> 512D
  OPQMatrix::train: making random 512*512 rotation
Training PQ slice 0/64
Clustering 65536 points in 8D to 256 clusters, redo 1 times, 40 iterations
  Preprocessing in 0.00 s
  Iteration 6 (7.64 s, search 6.83 s): objective=8064.75 imbalance=1.033 nsplit=0       
```

**Comment by mdouze** [comment]
It is on our roadmap to report resource consumption in a more predictable way. 
For now, the memory usage of the index should be quite easy to predict: it's the size per vector * nb vectors + size of index after training. That's the file size of the index. Unfortunately when loaded in RAM there are various overheads that get added, in particular the std::vector over-allocation buffers.

**Comment by qrdlgit** [comment]
Thanks.  One last question-  I was wondering about  'objective=8064.75' and if it had any meaning I could usefully interpret.  

For example, let's say I trained and  graphed the objective by parsing it out.  If I didn't like the curve (accuracy, wasn't improving fast enough), would it make sense to stop it and try a different index specification?    Any hints and how I should think about it?
