### ISSUE TITLE
can't display ParameterSpace

### ISSUE THREAD

**Issue by qrdlgit** [facebookresearch/faiss#3040]
# Summary

I got the code from here https://github.com/facebookresearch/faiss/issues/1653#issuecomment-768327762
```
import faiss
index = faiss.index_factory(256, "OPQ32_64,IVF65536_HNSW32,PQ32")
params = faiss.ParameterSpace()
params.initialize(index)
print(params.display())
```

params.display() returns None

# Platform

OS: ubuntu 

Faiss version: 1.7.4

Installed from: anaconda  

Faiss compilation options: 

Running on:
- [ x] CPU
- [ x] GPU

Interface: 
- [ ] C++
- [ x] Python

# Reproduction instructions

Just run the code above

**Comment by mdouze** [comment]
You are probably running this code in a notebook. 
In that case, the printed values go to the console where the notebook runs, not within the notebook. 
At some point we have to take care of this, but it means replacing all the printf/fprintf statements of Faiss with a wrapper.
