### ISSUE TITLE
How to update efSearch

### ISSUE THREAD

**Issue by qrdlgit** [facebookresearch/faiss#3041]
# Summary

I'm not sure if I'm updating efSearch correctly.

```
ndex65536_ivf = faiss.extract_index_ivf(index65536)
index65536_ivf.nprobe=1024
index65536_ivf.efSearch=256
```

The index was "OPQ64_512,IVF65536_HNSW,PQ64" and the recall rate is very inferior to "OPQ64_512,IVF65536,PQ64"

I was hoping boosting the efSearch would help, but I am not sure if I am doing it right.

It's (6800000,1024) embeddings

# Platform

OS: 

Faiss version: 1.7.4

Installed from: anaconda  

Faiss compilation options: 

Running on:
- [ x] CPU
- [x ] GPU

Interface: 
- [ ] C++
- [ x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
https://github.com/facebookresearch/faiss/wiki/Index-IO,-cloning-and-hyper-parameter-tuning#auto-tuning-the-runtime-parameters

use `ParameterSpace().set_index_parameter(index, "quantizer_efSearch")`
