### ISSUE TITLE
faiss = FAISS.from_documents(docs, embeddings) takes too long for a large dataset

### ISSUE THREAD

**Issue by BKTripathy-Git** [facebookresearch/faiss#3043]
# Summary

faiss = FAISS.from_documents(docs, embeddings)  takes too long for a large dataset.
For 35k records to store into vectordb, it takes 1 hour.

# Platform : Windows

Faiss version: faiss cpu

Installed from:  compiled by myself

Running on:
- [ ] CPU

Interface: Python

# Reproduction instructions
loader = CSVLoader(file_path="Dirctory\\Rdata.csv",encoding="utf8") 
pages = loader.load_and_split()
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1500, chunk_overlap=0)
docs = text_splitter.split_documents(documents) 
embeddings = OpenAIEmbeddings(deployment="deployment"_name,chunk_size=16) 
faiss = FAISS.from_documents(docs, embeddings)

**Comment by BKTripathy-Git** [comment]
The code was running on my local laptop, But after moving to a server having 4 CPU(core), it ran 5x faster.

Would appreciate, anyone can provide any other optimization tips and techniques while working with FAISS(langchain)
Many thanks in advance.

**Comment by BKTripathy-Git** [comment]
I was running the code on my local laptop, But after moving to a server having 4 CPU(core), it ran 5x faster.

Would appreciate, anyone can provide any other optimization tips and techniques while working with FAISS(langchain)
Many thanks in advance.

**Comment by mlomeli1** [comment]
This issue related to the langchain FAISS wrapper that was not written by us. I would advise you to open an issue in the langchain repo @BKTripathy-Git . Thanks.

**Comment by mlomeli1** [comment]
Please direct these questions to the langchain, here is the link for your reference:

https://github.com/langchain-ai/langchain
