### ISSUE TITLE
[CGO]: Fetching Centroids from `Index_c.h`

### ISSUE THREAD

**Issue by arjunsk** [facebookresearch/faiss#3052]
Thank you for this library.

Does FAISS expose any API for fetching centroids in [c_api](https://github.com/facebookresearch/faiss/blob/main/c_api/Index_c.h)?

I looked into, 
1. [Getting centroids from Index Quantizer](https://github.com/facebookresearch/faiss/issues/961)
2. [Clusting_c API](https://github.com/technicolor-research/faiss-quickeradc/blob/e72bc81e93bc8c50e716c36d3bd3c7024d1b01d7/c_api/Clustering_c.cpp#L127)

But I did not find the exact thing I was looking for
1. Is there any other FAISS API that exposes only the centroids created after the IVF `train()`? Could someone kindly help me with fixing the 1st code example below?
2. Is using K-Means as shown in the code below (CGO code from Clustering) the right way to fetch centroids? Or should I fetch centroids from other parent entities supporting Quantizer, etc. like the IVF Index? Or should I create a `Clustering` object and then [use it for](https://github.com/technicolor-research/faiss-quickeradc/blob/e72bc81e93bc8c50e716c36d3bd3c7024d1b01d7/c_api/Clustering_c.cpp#L71C7-L71C7) fetching centroids?

### Code
<details>
<summary> CGO code from Index</summary>

```go

package main

/*
#cgo LDFLAGS: -lfaiss_c

#include <stdlib.h>
#include <faiss/c_api/Index_c.h>
#include <faiss/c_api/impl/AuxIndexStructures_c.h>
#include <faiss/c_api/index_factory_c.h>
#include <faiss/c_api/error_c.h>
*/
import "C"
import (
	"errors"
	"math/rand"
)

// CGO code for https://github.com/facebookresearch/faiss/blob/main/c_api/Index_c.h functions
func main() {

	// data
	vectorDims := 64
	rows := 1000
	vectorIds := make([]int64, rows)
	vectorsFlattened := make([]float32, vectorDims*rows)
	loadData(rows, vectorDims, vectorsFlattened, vectorIds)

	// init faiss index
	centroidCount := 100 //IVF100,PQ4np
	var idx *C.FaissIndex
	// 100 is the number of clusters/centroids
	indexType := C.CString("IVF100,PQ4np")
	indexDistanceMetrics := C.METRIC_L2
	c := C.faiss_index_factory(&idx, C.int(vectorDims), indexType, C.FaissMetricType(indexDistanceMetrics))
	if c != 0 {
		panic(getLastError())
	}

	// train
	if c := C.faiss_Index_train(idx, C.idx_t(rows), (*C.float)(&vectorsFlattened[0])); c != 0 {
		panic(getLastError())
	}

	// fetch centroids
	//TODO:
	//1. Need the right syntax to fetch centroids from the quantizer.
	//2. I only need centroids. In that case, is there any other class that has the BuildCenter functionality alone?
	centroids := make([]float32, vectorDims*centroidCount)
	if c := C.faiss_Index_reconstruct_n(idx.quantizer, (*C.float)(&centroids[0])); c != 0 {
		panic(getLastError())
	}

	// add with ids
	if c := C.faiss_Index_add_with_ids(
		idx,
		C.idx_t(rows),
		(*C.float)(&vectorsFlattened[0]),
		(*C.idx_t)(&vectorIds[0]),
	); c != 0 {
		panic(getLastError())
	}
}

func getLastError() error {
	return errors.New(C.GoString(C.faiss_get_last_error()))
}

func loadData(nb int, d int, xb []float32, x []int64) {
	for i := 0; i < nb; i++ {
		for j := 0; j < d; j++ {
			xb[i*d+j] = rand.Float32()
		}
		xb[i*d] += float32(i) / 1000
		x[i] = int64(i)
	}
}

```
</details>

<details>
<summary>CGO code from Clustering</summary>

```go
/*
#cgo LDFLAGS: -lfaiss_c

#include <stdlib.h>
#include <faiss/c_api/Clustering_c.h>
#include <faiss/c_api/impl/AuxIndexStructures_c.h>
#include <faiss/c_api/index_factory_c.h>
#include <faiss/c_api/error_c.h>
*/
import "C"
import (
	"errors"
	"fmt"
	"math/rand"
)

// CGO code for https://github.com/facebookresearch/faiss/blob/main/c_api/Clustering_c.h functions
// K-means : https://github.com/facebookresearch/faiss/wiki/Faiss-building-blocks:-clustering,-PCA,-quantization
func main() {

	// data
	rowCnt := 3000
	vectorDims := 5
	vectorsFlattened := make([]float32, vectorDims*rowCnt)
	loadData(rowCnt, vectorDims, vectorsFlattened)

	// build centroids
	centroidCount := 3
	centroids := make([]float32, vectorDims*centroidCount)
	var qError float32
	c := C.faiss_kmeans_clustering(
		C.ulong(vectorDims),              // d dimension of the data
		C.ulong(rowCnt),                  // n nb of training vectors
		C.ulong(centroidCount),           // k nb of output centroids
		(*C.float)(&vectorsFlattened[0]), // x training set (size n * d)
		(*C.float)(&centroids[0]),        // centroids output centroids (size k * d)
		(*C.float)(&qError),              // q_error final quantization error
		//@return error code
	)
	if c != 0 {
		panic(getLastError())
	}

	if qError <= 0 {
		//final quantization error
		panic("final quantization error >0")
	}

	fmt.Println("data")
	for r := int64(0); r < int64(centroidCount); r++ {
		for c := int64(0); c < int64(vectorDims); c++ {
			fmt.Printf("%5f ", vectorsFlattened[r*int64(vectorDims)+c])
		}
		fmt.Println()
	}

	fmt.Println("centroids")
	for r := int64(0); r < int64(centroidCount); r++ {
		for c := int64(0); c < int64(vectorDims); c++ {
			fmt.Printf("%5f ", centroids[r*int64(vectorDims)+c])
		}
		fmt.Println()
	}

}

func getLastError() error {
	return errors.New(C.GoString(C.faiss_get_last_error()))
}

func loadData(nb int, d int, xb []float32) {
	for i := 0; i < nb; i++ {
		for j := 0; j < d; j++ {
			xb[i*d+j] = rand.Float32()
		}
		xb[i*d] += float32(i) / 1000
	}
}

```
</details>

**Comment by mdouze** [comment]
The C interface of Faiss is not guaranteed to be complete. It is possible that there are etnry points missing. 
Normally centroids are obtained by reconstructing the vectors of the IVF quantizer.

**Comment by arjunsk** [comment]
Thank you for your response.

Is there any C API (code) that exposes the IVF Index quantizer, that I can use in `faiss_Index_reconstruct_n`?

Or is this API only available in [Python clients](https://github.com/facebookresearch/faiss/issues/961)?

**Comment by Enet4** [comment]
If calling `reconstruct_n` on the quantizer is enough, then that is already possible.

```c
// downcast to IVF index (dynamic check)
FaissIVFIndex* ivf_index = faiss_IVFIndex_cast(index);
// get the quantizer
FaissIndex* quantizer = faiss_IVFIndex_quantizer();
// use it
float* recons = malloc(d * sizeof(float));
int e = faiss_Index_reconstruct(quantizer, 0, &recons);
```

**Comment by arjunsk** [comment]
Thank you @Enet4 . However, I could not find any API reference for [faiss_IVFIndex_cast](https://github.com/search?q=repo%3Afacebookresearch%2Ffaiss%20faiss_IVFIndex_cast&type=code) and [faiss_IVFIndex_quantizer](https://github.com/search?q=repo%3Afacebookresearch%2Ffaiss+faiss_IVFIndex_quantizer&type=code). Could you please point me to the function signature in the FAISS code?

**Comment by Enet4** [comment]
That is because the two methods are behind macros.

- `faiss_*_cast` is created via [`FAISS_DECLARE_INDEX_DOWNCAST`](https://github.com/facebookresearch/faiss/blob/main/c_api/IndexIVF_c.h#L57) as a means for C code to safely perform a `dynamic_cast` to a more specific index type.
- The other one was declared as a property getter via [`FAISS_DECLARE_GETTER`](https://github.com/facebookresearch/faiss/blob/main/c_api/IndexIVF_c.h#L64). They all have the form `T faiss_«IndexType»_«propertyName»(«IndexType»*)`.

**Comment by arjunsk** [comment]
Thank you for clarifying!
