### ISSUE TITLE
Question about own_fields of Level1Quantizer ?

### ISSUE THREAD

**Issue by shiwanghua** [facebookresearch/faiss#3061]
https://github.com/facebookresearch/faiss/blob/d85601d972af2d64103769ab8d940db28aaae2a0/faiss/IndexIVF.cpp#L52

Why the 'own_fields' is false in default ?

When newing an index as the quantizer of an IVF/IVFPQ index, who is responsible for the destruction task of the quantizer ?

Should we proactively set the "own_fields" to true ?

**Comment by mdouze** [comment]
see 
https://github.com/facebookresearch/faiss/wiki/FAQ#in-c-do-i-need-to-keep-a-reference-to-the-coarse-quantizer-around-for-an-indexivfflatindexivfpqindexivfpqr-index
