### ISSUE TITLE
How can I use the c++ wrapper to use in swift can I just get the general method how can I do that ? 

### ISSUE THREAD

**Issue by Omkar19202** [facebookresearch/faiss#3063]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by LLMUSER** [comment]
I want to use this in swift hence wanted to create a c++ wrapper for that

**Comment by mdouze** [comment]
I don't understand the question.

**Comment by junjieqi** [comment]
closed if there is further question
