### ISSUE TITLE
IndexIVFPQ: Two-Level (Inverted-Index based) PQ ANNS algorithm

### ISSUE THREAD

**Issue by Yan-J-lee** [facebookresearch/faiss#3065]
Hi! I got some questions about the class "IndexIVFPQ". The first question is: how can I use "IndexIVFPQ" to access the centroid vectors generated by K-Means Clustering? And can I retrieve the encoded residual vectors in each cluster? By the way, I adopted the following method to get access to the codebooks, which would be used to calculate the lookup tables during the second step of the algorithm: Lookup Table Construction. Is this correct?

```
def get_codebooks(d, nlist, m, nbits, xb, xt):
    # Initialize the quantizer
    quantizer = faiss.IndexFlatL2(d)  # the index that uses the squared L2 (Euclidean) distance.

    # Initialize the index
    index = faiss.IndexIVFPQ(quantizer, d, nlist, m, nbits)

    # Train the index
    print("\nTraining the Two-Level PQ index...")
    index.train(xt)

    # Add the base set's vectors to the index
    index.add(xb)

    # Extract the codebooks
    # NumPy array with shape (m, 2 ** nbits, d / m)
    codebooks = index.pq.centroids
    codebooks = faiss.vector_to_array(codebooks)
    codebooks = codebooks.reshape(m, 2 ** nbits, nbits)

    return codebooks
```
And the second question is: I want to extract the lookup tables and convert all the floating-point values in the tables into integers because I want to test the performance on an integer-only hardware platform. Where is the code implementation of the lookup table construction step in the algorithm? Also, can I retrieve the lookup tables via "IndexIVFPQ"?

Hope to receive your reply soon.
Thank you in advance!

**Comment by mdouze** [comment]
To get the centroids, use `index.quantizer.reconstruct_n()`. For the PQ codes, see 
https://github.com/facebookresearch/faiss/wiki/Python-C---code-snippets#how-can-i-get-the-content-of-inverted-lists
The look-up tables are computed here: 

https://github.com/facebookresearch/faiss/blob/592f3016d1089bf9353560bce87adf13f86fcb67/faiss/IndexIVFPQ.cpp#L634

A bit harder to call from python. 

NB that there is a version with int8 look-up tables implemented in IVFPQFastScan here: 

https://github.com/facebookresearch/faiss/blob/592f3016d1089bf9353560bce87adf13f86fcb67/faiss/IndexIVFPQ.cpp#L634

https://github.com/facebookresearch/faiss/blob/main/faiss/IndexIVFFastScan.cpp#L245

There is very little loss in accuracy.

**Comment by Yan-J-lee** [comment]
Thanks for your reply! I find that `index.quantizer.reconstruct()` and `index.quantizer.reconstruct_n()` generates different centroids for the same training data. For example, I used the training data "xt" from the SIFT1M dataset to train the "IndexIVFPQ" object with the metric squared L2 distance. `index.quantizer.reconstruct()` corresponds to the following code:
`
centroids = np.empty((nCentroids, d), dtype=np.float32)
for i in range(nCentroids):
    centroids[i] = index.quantizer.reconstruct(i)
print("\nThe centroids are:\n", centroids, centroids.shape)
`
And it generates the following centroids:
![image](https://github.com/facebookresearch/faiss/assets/71831411/3a0dfbb7-d652-4f67-a511-3169ac0775e0)
`index.quantizer.reconstruct_n()` corresponds to the following code:
`
for centroid in centroids:
    centroid = index.quantizer.reconstruct_n()
print("\nThe centroids are:\n", centroids, centroids.shape)
`
It generates the following centroids:
![image](https://github.com/facebookresearch/faiss/assets/71831411/65e9e2a2-1d4d-45cf-9c70-db4cf9d875cd)
I think the centroids generated by the `index.quantizer.reconstruct()` seems more reasonable. Could you tell me how do you think of this?

**Comment by Yan-J-lee** [comment]
I tried several approaches to retrieve lookup tables directly from the "IndexIVFPQ" API, but none of the methods work. I find it hard to obtain LUTs directly from the API.
Could you tell me how can I access the lookup tables directly from the "IndexIVFPQ" API?
I hope to receive your response soon. Thanks for your warm help!

**Comment by Yan-J-lee** [comment]
I've resolved my issues. Thanks for your warm help!
