### ISSUE TITLE
How to build in msys2

### ISSUE THREAD

**Issue by thewh1teagle** [facebookresearch/faiss#3067]
Hello
I would like to build faiss on windows using mingw64 in msys2 with mkl / openblas

Is there some place with instructions for that? 
I already tried and currently I'm facing issues with cmake which doesn't find mkl or openblas.

**Comment by mdouze** [comment]
Please let us know if any progress in this environment.

**Comment by thewh1teagle** [comment]
@mdouze 
I managed to configure the environment to build faiss on windows using ucrt-64 from msys2.
But looks like there's some errors in the code itself related to using it on windows, in some macros:

```console
User@DESKTOP-HPEE9O3 UCRT64 /tmp/sqlite-vss
$ mingw32-make.exe -C build_release
mingw32-make: Entering directory 'C:/msys64/tmp/sqlite-vss/build_release'
[  1%] Built target sqlite-vector
[  2%] Built target sqlite-vector-static
[  2%] Building CXX object vendor/faiss/faiss/CMakeFiles/faiss_avx2.dir/AutoTune.cpp.obj
In file included from C:/msys64/tmp/sqlite-vss/vendor/faiss/faiss/IndexIVFPQ.h:18,
                 from C:\msys64\tmp\sqlite-vss\vendor\faiss\faiss\AutoTune.cpp:28:
C:/msys64/tmp/sqlite-vss/vendor/faiss/faiss/utils/AlignedTable.h: In member function 'void faiss::AlignedTableTightAlloc<T, A>::resize(size_t)':
C:/msys64/tmp/sqlite-vss/vendor/faiss/faiss/utils/AlignedTable.h:50:23: error: there are no arguments to 'posix_memalig ' that depend on a template parameter, so a declaration of 'posix_memalign' must be available [-fpermissive]
   50 |             int ret = posix_memalign((void**)&new_ptr, A, n * sizeof(T));
      |                       ^~~~~~~~~~~~~~
C:/msys64/tmp/sqlite-vss/vendor/faiss/faiss/utils/AlignedTable.h:50:23: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
mingw32-make[2]: *** [vendor\faiss\faiss\CMakeFiles\faiss_avx2.dir\build.make:76: vendor/faiss/faiss/CMakeFiles/faiss_avx2.dir/AutoTune.cpp.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:333: vendor/faiss/faiss/CMakeFiles/faiss_avx2.dir/all] Error 2
mingw32-make: *** [Makefile:135: all] Error 2
mingw32-make: Leaving directory 'C:/msys64/tmp/sqlite-vss/build_release'
```

The error comes from 
https://github.com/facebookresearch/faiss/blob/main/faiss/impl/platform_macros.h#L32

**Comment by thewh1teagle** [comment]
I managed to build it on Windows in msys2 environemnt!
I had to change a little the source code to support mingw compiler.

1. Download msys2 from https://www.msys2.org/

2. Open `UCRT64` terminal Install dependencies
```console
pacman --needed -S $MINGW_PACKAGE_PREFIX-{toolchain,cmake,make,swig,autotools,lapack} git
```

4. Clone & Build
```console
git clone https://github.com/thewh1teagle/faiss -b windows-mingw-support
mkdir -p faiss/build && cd faiss/build
cmake -G "MinGW Makefiles" .. -DFAISS_ENABLE_GPU=OFF -DFAISS_ENABLE_PYTHON=OFF -DCMAKE_CXX_FLAGS="-march=x86-64" -DCMAKE_C_FLAGS="-march=x86-64" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=off
mingw32-make.exe -j16
```

**Comment by JAicewizard** [comment]
I am trying to compile under mingw as well, but am hitting the issue that mingw doesn't define `posix_memalign` (used in `AlignedTable.h`). Did you hit the same issue?

**Comment by thewh1teagle** [comment]
> I am trying to compile under mingw as well, but am hitting the issue that mingw doesn't define `posix_memalign` (used in `AlignedTable.h`). Did you hit the same issue?

Try in ucrt.
Anyway, compiling this in msys2 environment is not something I would recommend, as in the end you'll need the DLLs of that environment so you will be able to run it outside of the environment.
I would switch to other libs with better support for Windows such as [spotify/annoy](https://github.com/spotify/annoy)

**Comment by mengdilin** [comment]
We only support installing and building FAISS through conda on Windows. Here is an example nightly build that compiles FAISS on Microsoft Windows Server 2019: https://fburl.com/hbbh3ndc

You can step through the instructions there which provide all of the related conda installation commands and the compilation arguments.
