### ISSUE TITLE
(Help Needed) TypeError: in method 'IndexIDMap_search', argument 4 of type 'faiss::IndexIDMapTemplate< faiss::Index >::idx_t'

### ISSUE THREAD

**Issue by priyankaiiit14** [facebookresearch/faiss#3069]
# Summary
I am using IndexIVFFlat followed by IndexIDMap to add the ids. It runs fine on the same platform and databricks notebook but when I try to use this in a script to log the same index in mlflow and load the index from mlflow, it throws type error

Faiss version:  faiss-gpu     1.7.2

Installed from: !pip install faiss-gpu

Faiss compilation options: 

Running on:
 - GPU

Interface: 
- Python

# Reproduction instructions

#preparing  embeddings
faiss_embedding_dict has embeddings along with id column
embeddings_list=list()
ids_list=list()
for key, value in faiss_embedding_dict.items():
    embedding = np.array(value.get("embedding")[0], dtype=np.float32)  # Convert to NumPy array
    embeddings_list.append(embedding)
    ids_list.append(key)
# Stack the embeddings along a new axis to form a 2D array
all_embeddings = np.stack(embeddings_list)
# Convert the IDs to a numpy array
ids = np.array(ids_list)

count=all_embeddings.shape[0]
dimensions=all_embeddings.shape[1] #512

def create_ivfflatindex():
  # Define the number of clusters for ivf
  nlist = math.ceil(4 * math.sqrt(count))

  quantizer = faiss.IndexFlatL2(dimensions)
  print(dimensions,nlist)
  index = faiss.IndexIVFFlat(quantizer,dimensions,nlist,faiss.METRIC_INNER_PRODUCT)

  # Add the data to the index
  index.train(all_embeddings)
  index = faiss.IndexIDMap(index)
  index.add_with_ids(all_embeddings, ids)
  return index

#create the index and save them
index_ivfflat = create_ivfflatindex()
faiss.write_index(index_ivfflat, index_path)

#create the query embedding
query_embedding = model.get_text_features(**processor("black",padding=True, return_tensors="pt").to(device))
query_embedding_array = query_embedding.detach().cpu().numpy()

#read the index and search
dbfs_ivfflat_index = faiss.read_index(index_path)
 distances,ids = dbfs_ivfflat_index.search(query_embedding_array, num_of_results) 

**Error log:**
TypeError                                 Traceback (most recent call last)
<command-1787498931992782> in <cell line: 2>()
      1 query=pd.DataFrame({"query":["fre@ky fucer"],"num_results":150,"ui_flag":1})
----> 2 predicted_image_list=loaded_model.predict(query)
      3 print(predicted_image_list)

/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py in predict(self, data)
    411         if input_schema is not None:
    412             data = _enforce_schema(data, input_schema)
--> 413         return self._predict_fn(data)
    414 
    415     @experimental

/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/mlflow/pyfunc/model.py in predict(self, model_input)
    303 
    304     def predict(self, model_input):
--> 305         return self.python_model.predict(self.context, model_input)

<command-1787498931992778> in predict(self, context, model_input)
     52         # Perform your inference using the loaded models and other resources
     53         # You can access the loaded models and resources using self.img_model, self.text_model, self.annoy_index, etc.
---> 54         return self.index_search(model_input)
     55 
     56     def index_search(self, model_input):

<command-1787498931992778> in index_search(self, model_input)
    121 
    122       #We use faiss ivf flat index to find the num_results
--> 123       distances,index_ids = self.dbfs_ivfflat_index.search(query_embedding_array, num_results)
    124       distances=distances[0]
    125       index_ids=index_ids[0]

/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/faiss/__init__.py in replacement_search(self, x, k, D, I)
    320             assert I.shape == (n, k)
    321 
--> 322         self.search_c(n, swig_ptr(x), k, swig_ptr(D), swig_ptr(I))
    323         return D, I
    324 

/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/faiss/swigfaiss.py in search(self, n, x, k, distances, labels)
   8402 
   8403     def search(self, n, x, k, distances, labels):
-> 8404         return _swigfaiss.IndexIDMap_search(self, n, x, k, distances, labels)
   8405 
   8406     def train(self, n, x):

TypeError: in method 'IndexIDMap_search', argument 4 of type 'faiss::IndexIDMapTemplate< faiss::Index >::idx_t'

**Comment by mdouze** [comment]
make sure num_of_results is an int
