### ISSUE TITLE
Can't compile test_blas.cpp

### ISSUE THREAD

**Issue by sbmaruf** [facebookresearch/faiss#307]
`make tests/test_blas`

in the response to the command given above, I get the following output.

```
g++     test_blas.cpp   -o test_blas
/tmp/cc3aL3kc.o: In function `main':
test_blas.cpp:(.text+0x187): undefined reference to `sgemm_'
test_blas.cpp:(.text+0x346): undefined reference to `sgeqrf_'
collect2: error: ld returned 1 exit status
make: *** [test_blas] Error 1
```
Can anyone help me to install faiss? I don't have anaconda in my server and I'm not sudo-er in the server. Is there any reasonable way to install it or I've to request to the admin for some installing additional apis/library?

**Comment by mdouze** [comment]
Hi 
You probably erased or overwrote the Makefile.

**Comment by sbmaruf** [comment]
Yes. Finally successfully compiled.

**Comment by yangsuo** [comment]
@sbmaruf 
            Hi 
            I have the same problem as you. How did you solve it?

**Comment by ahappycutedog** [comment]
> 是。终于成功编译了。

How do you solve this problem? Can you describe it in detail?

**Comment by keything** [comment]
i solve it by add --with-lapack .  it refers to https://github.com/facebookresearch/faiss/issues/15
