### ISSUE TITLE
Feature Request: Batch Retrieval Support for 'index.reconstruct()'

### ISSUE THREAD

**Issue by Waleed794** [facebookresearch/faiss#3078]
# Summary
Feature Request: Batch Retrieval Support for `index.reconstruct()`

# Platform

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

## Description:
Currently, the `index.reconstruct()` method in FAISS allows users to retrieve a single vector at a time, requiring multiple function calls to retrieve multiple vectors. In scenarios where there is a need to retrieve a batch of vectors, this can result in suboptimal performance and increased overhead.

## Feature Request:
I would like to propose the addition of batch retrieval support for the `index.reconstruct()` method. Specifically, I suggest enhancing the method to accept a list of indices or positions and return a corresponding list of retrieved vectors in a single function call.

## Use Case:
This feature would be particularly valuable in scenarios where users need to retrieve multiple vectors simultaneously, such as when working with large datasets or conducting batch inference with embeddings stored in FAISS.

## Benefits:
1. Improved Efficiency: Batch retrieval reduces the number of function calls and potentially enhances the performance of retrieval operations, especially when dealing with large datasets.

2. Simplified Code: Users can simplify their code by avoiding repetitive calls to `index.reconstruct()` for each vector.

### Current Usage (Sequential Retrieval)
retrieved_vectors = [index.reconstruct(i) for i in indices]

### Proposed Usage (Batch Retrieval)
retrieved_vectors = index.reconstruct_batch(indices)

- Proposed Method Signature: reconstruct_batch(indices: List[int]) -> List[Tensor]
- The function would take a list of indices (positions) as input and return a list of tensors (vectors) as output.
- The existing index.reconstruct() method can continue to be supported for single-vector retrieval.

**Comment by mdouze** [comment]
How is it different from reconstruct_batch ? 
https://github.com/facebookresearch/faiss/blob/main/faiss/Index.h#L181
