### ISSUE TITLE
how to get IVFPQScanner->sim_table?

### ISSUE THREAD

**Issue by Cass998** [facebookresearch/faiss#3081]
# Summary

I want to get a sim_table(nlist * M * ksub) of a query. But it seems not be accessible.
# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [-] CPU
- [ ] GPU

Interface: 
- [-] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
You probably mean `nprobe * M * ksub`. The IVFPQScanner computes it on-the-fly here 

https://github.com/facebookresearch/faiss/blob/main/faiss/IndexIVFPQ.cpp#L648 

Here is a small demo on how to obtain this in Python. The translation to C++ should be straightforward: 

[demo_ivfpq_distance_tables.ipynb](https://gist.github.com/mdouze/08b3aaec6bf4a82994d89cb955ac1c57#file-demo_ivfpq_distance_tables-ipynb)

**Comment by Cass998** [comment]
> You probably mean `nprobe * M * ksub`. The IVFPQScanner computes it on-the-fly here
> 
> https://github.com/facebookresearch/faiss/blob/main/faiss/IndexIVFPQ.cpp#L648
> 
> Here is a small demo on how to obtain this in Python. The translation to C++ should be straightforward:
> 
> [demo_ivfpq_distance_tables.ipynb](https://gist.github.com/mdouze/08b3aaec6bf4a82994d89cb955ac1c57#file-demo_ivfpq_distance_tables-ipynb)

Thanks! But I try to get sim_table in C++. It seems not be be straightforward. "sim_table" in IndexIVFPQ.cpp is defined in anonymous namespace. There is no interface to get "sim_table".

**Comment by Cass998** [comment]
> You probably mean `nprobe * M * ksub`. The IVFPQScanner computes it on-the-fly here
> 
> https://github.com/facebookresearch/faiss/blob/main/faiss/IndexIVFPQ.cpp#L648
> 
> Here is a small demo on how to obtain this in Python. The translation to C++ should be straightforward:
> 
> [demo_ivfpq_distance_tables.ipynb](https://gist.github.com/mdouze/08b3aaec6bf4a82994d89cb955ac1c57#file-demo_ivfpq_distance_tables-ipynb)

Thanks! But I try to get sim_table in C++. It seems not be straightforward. "sim_table" in IndexIVFPQ.cpp is defined in anonymous namespace. There is no interface to get "sim_table".
