### ISSUE TITLE
Error while searching documents  using langchain.vectorstores (BaseLLM.__call__() missing 1 required positional argument: 'prompt')

### ISSUE THREAD

**Issue by gduchate** [facebookresearch/faiss#3085]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Running on:
- [ X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ X] Python

# Reproduction instructions
 I am running the following Code but I am getting an error " BaseLLM.__call__() missing 1 required positional argument: 'prompt'" 
I am not able to find the correct way to build  the prompt,

**Comment by gduchate** [comment]
Hi 
I reduce the code to a simple example  as follows:


           retriever = self.db.as_retriever(
                search_type="mmr",
                search_kwargs={'k': 5, 'fetch_k': 10}
            )

            prompt = [
                ("human", "Hello"),
                ("assistant", "Hi there!"),
            ]


            qa = RetrievalQA.from_chain_type(
                llm=self.llm,
                chain_type="refine",
                retriever=retriever,
                return_source_documents=True,
                chain_type_kwargs={"prompt": prompt}
            )

            res = qa({
                "query": query,
                "prompt": prompt,
                "context": "You are helpful"
            })


The error nows is the following:

([ErrorWrapper(exc=ExtraError(), loc=('prompt',))], <class 'langchain.chains.combine_documents.refine.RefineDocumentsChain'>)

**Comment by mdouze** [comment]
Please post on the langchain issues.

**Comment by Spinachboul** [comment]
From the code you provided, it seems that the prompt variable is being used both while initializing the retrieval chain (chain_type_kwargs={"prompt": prompt}) and later when making the query ("prompt" : prompt). This might be causing confusion in the library's handling of the prompt.

```
retriever = self.db.as_retriever(
    search_type="mmr",
    search_kwargs={'k': 5, 'fetch_k': 10}
)

prompt_chain = [
    ("human", "Hello"),
    ("assistant", "Hi there!"),
]

qa = RetrievalQA.from_chain_type(
    llm=self.llm,
    chain_type="refine",
    retriever=retriever,
    return_source_documents=True,
    chain_type_kwargs={"prompt": prompt_chain}
)

query = "Can you help me?"
context = "You are helpful"

res = qa({
    "query": query,
    "prompt": prompt_chain,
    "context": context
})

```

Please look into this code and test it into your environment!

**Comment by mlomeli1** [comment]
@gduchate Please direct these questions as an issue in the langchain repo, here is the link for your reference:

https://github.com/langchain-ai/langchain
