### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by Pe4enIks** [facebookresearch/faiss#3086]
# Summary

The documentation contains errors.

The [IndexPQ](https://faiss.ai/cpp_api/struct/structfaiss_1_1IndexPQ.html) constructor has duplicate parameter descriptions, metric parameter description doesn't exist.

```
IndexPQ(int d, size_t M, size_t nbits, MetricType metric = METRIC_L2)
  Constructor.
  
  Parameters:
  - d – dimensionality of the input vectors
  - M – number of subquantizers
  - nbits – number of bit per subvector index
  - d – dimensionality of the input vectors
  - M – number of subquantizers
  - nbits – number of bit per subvector index
```

Should I write about this here, or maybe fill in a form that I haven't found yet, because there are several such bugs.?

**Comment by mdouze** [comment]
Right, this is because the doc is duplicated in Doxygen. 

https://github.com/facebookresearch/faiss/blob/main/faiss/IndexPQ.h#L28

If you want to fix it, please submit a PR. Thanks!
