### ISSUE TITLE
GPU has zero utilization and memory usage

### ISSUE THREAD

**Issue by Pe4enIks** [facebookresearch/faiss#3088]
# Summary

I tried to train index_factory with OPQ and PQ on GPU, I didn't get any errors, but my GPU had zero utulization and memory usage. The code below shows the number of GPUs = 1.
```python
faiss.get_num_gpus()
```

[Wiki](https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index) says that OPQM_D,...,PQM is supported on GPU.

# Platform

OS:  ubuntu 22.04.3

Faiss version:  faiss-gpu==1.7.2 c08cbff1a4d6c9afb6b8f69004c5530aaf80237a

Installed from:  pip

Faiss compilation options: 

Running on:
- [ ] CPU
- [X] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

1. Install FAISS
```bash
pip install faiss-gpu==1.7.2 numpy==1.23.5
```

2. Run python code
```python
import faiss
import numpy as np

index = faiss.index_factory(1024, 'OPQ64_256,PQ64x10')
device = faiss.StandardGpuResources()
gpu_index = faiss.index_cpu_to_gpu(device, 0, index)

vcts = np.random.rand(100000, 1024).astype(np.float32)
gpu_index.train(vcts)
```

**Comment by mdouze** [comment]
Actually, IVFPQ is supported but pure PQ is not. You can simulate it with a 1-centroid IVF, see 

[demo_1_centroid_PQ.ipynb](https://gist.github.com/mdouze/1627af05a2e064a6280f9ba1fb04934e#file-demo_1_centroid_pq-ipynb)

**Comment by Xp-speit2018** [comment]
Thank you @mdouze for the previous discussion and resolution. Just out of curiosity, why is IVFPQ supported on GPU but pure PQ is not? Is there a specific reason or technical limitation that makes it so? I thought IVFPQ might wrap PQ in some way. Any insights would be appreciated.
