### ISSUE TITLE
Index Type after load from disk?

### ISSUE THREAD

**Issue by 0DF0Arc** [facebookresearch/faiss#309]
Hi, I'm using IMI2_8, PQ2_16 to create an index, and then convert to gpu to training, back to cpu for wriring. And I got sereval questions:
1. when using index_cpu_index_to_gpu_multiple to convert cpu index to gpu index, how can i get the origin IMI2_8, PQ2_16 type index? because this API return a faiss::Index* type index
2. when load index from disk, get a faiss::Index*, how can I cast it to  IMI2_8, PQ2_16, since I didn't find a index type for IMI2_8, PQ2_16.
3. how many index types can I using dynamic_cast to cast.

**Comment by 0DF0Arc** [comment]
one more question, how to search in a specified index? like IMI2_8, PQ2_16.

**Comment by wickedfoo** [comment]
IMI is not supported on the GPU.

**Comment by mdouze** [comment]
Hi 
When an unsupported index is encountered during conversion, the index is just copied without moving it to GPU.
