### ISSUE TITLE
Running FAISS on NVIDIA A100 GPUs

### ISSUE THREAD

**Issue by karthik86248** [facebookresearch/faiss#3091]
# Summary

The FAISS GPU paper and the readme in benchmarks page on GitHub page specify the commandline arguments for running FAISS on TITAN GPUs. Wanted to know if there are any suggestions on using the right set of parameters for running the experiments on an A100 GPU card with 80GB device memory? This is for both the large datasets i.e. SIFT1B and DEEP1B

# Platform

A100 GPU with 80 GB Device Memory

OS: Ubuntu 22.04.1 LTS

Faiss version: 1.7.4

Installed from: conda / python 3.9

Faiss compilation options: n/a

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

The README (under the section : Benchmarking Scripts) specifies the commandline argument to be used for SIFT1B on TITAN GPUs. Using the same commandline arguments on our A100 GPU, below results are obtained:

---

<span style="font-family:Courier; font-size:1em;">
python bench_gpu_1bn.py SIFT1000M OPQ8_32,IVF262144,PQ8 -nnn 10 -ngpu 1 -tempmem $[1536*1024*1024]

Preparing dataset SIFT1000M

sizes: B (1000000000, 128) Q (10000, 128) T (100000000, 128) gt (10000, 1000)

cachefiles:

/tmp/bench_gpu_1bn/preproc_SIFT1000M_OPQ8_32.vectrans

/tmp/bench_gpu_1bn/cent_SIFT1000M_OPQ8_32,IVF262144.npy

/tmp/bench_gpu_1bn/SIFT1000M_OPQ8_32,IVF262144,PQ8.index

preparing resources for 1 GPUs

load /tmp/bench_gpu_1bn/preproc_SIFT1000M_OPQ8_32.vectrans

load /tmp/bench_gpu_1bn/SIFT1000M_OPQ8_32,IVF262144,PQ8.index

CPU index contains 1000000000 vectors, move to GPU

copying loaded index to GPUs

  IndexIVFPQ size 1000000000 -> GpuIndexIVFPQ indicesOptions=0 usePrecomputed=1 useFloat16=0 reserveVecs=0

move to GPU done in 15.249 s

search...

0/10000 (0.047 s)      probe=1  : 0.170 s 1-R@1: 0.0787 1-R@10: 0.1952

0/10000 (0.005 s)      probe=2  : 0.046 s 1-R@1: 0.0957 1-R@10: 0.2666

0/10000 (0.003 s)      probe=4  : 0.045 s 1-R@1: 0.1111 1-R@10: 0.3373

0/10000 (0.004 s)      probe=8  : 0.065 s 1-R@1: 0.1213 1-R@10: 0.3898

0/10000 (0.012 s)      probe=16 : 0.105 s 1-R@1: 0.1253 1-R@10: 0.4237

0/10000 (0.020 s)      probe=32 : 0.170 s 1-R@1: 0.1302 1-R@10: 0.4452

0/10000 (0.010 s)      probe=64 : 0.239 s 1-R@1: 0.1310 1-R@10: 0.4535

0/10000 (0.025 s)      probe=128: 0.355 s 1-R@1: 0.1317 1-R@10: 0.4586

0/10000 (0.024 s)      probe=256: 0.786 s 1-R@1: 0.1320 1-R@10: 0.4589
</span>
   
---
Since the GPU we are using is A100 (and not Titan, A100 has more memory etc than TITAN) we were curious to know whether the search parameters provided in the commandline are the best for A100. E.g. We tried increasing the tempmem  but did not see any considerable change in the results (presented below). Maybe that's because the max allowed value for  tempmem is only 1.5 GB.

---
<span style="font-family:Courier; font-size:1em;">
 python bench_gpu_1bn.py SIFT1000M OPQ8_32,IVF262144,PQ8 -nnn 10 -ngpu 1

 -tempmem $[10*4*1536*1024*1024]

Preparing dataset SIFT1000M

sizes: B (1000000000, 128) Q (10000, 128) T (100000000, 128) gt (10000, 1000)

cachefiles:

/tmp/bench_gpu_1bn/preproc_SIFT1000M_OPQ8_32.vectrans

/tmp/bench_gpu_1bn/cent_SIFT1000M_OPQ8_32,IVF262144.npy

/tmp/bench_gpu_1bn/SIFT1000M_OPQ8_32,IVF262144,PQ8.index

preparing resources for 1 GPUs

load /tmp/bench_gpu_1bn/preproc_SIFT1000M_OPQ8_32.vectrans

load /tmp/bench_gpu_1bn/SIFT1000M_OPQ8_32,IVF262144,PQ8.index

CPU index contains 1000000000 vectors, move to GPU

copying loaded index to GPUs

  IndexIVFPQ size 1000000000 -> GpuIndexIVFPQ indicesOptions=0 usePrecomputed=1 useFloat16=0 reserveVecs=0

move to GPU done in 13.825 s

search...

0/10000 (0.046 s)      probe=1  : 0.118 s 1-R@1: 0.0787 1-R@10: 0.1952

0/10000 (0.021 s)      probe=2  : 0.073 s 1-R@1: 0.0957 1-R@10: 0.2666

0/10000 (0.018 s)      probe=4  : 0.070 s 1-R@1: 0.1111 1-R@10: 0.3373

0/10000 (0.021 s)      probe=8  : 0.075 s 1-R@1: 0.1213 1-R@10: 0.3898

0/10000 (0.021 s)      probe=16 : 0.088 s 1-R@1: 0.1253 1-R@10: 0.4237

0/10000 (0.021 s)      probe=32 : 0.123 s 1-R@1: 0.1302 1-R@10: 0.4452

0/10000 (0.021 s)      probe=64 : 0.214 s 1-R@1: 0.1310 1-R@10: 0.4535

0/10000 (0.017 s)      probe=128: 0.346 s 1-R@1: 0.1317 1-R@10: 0.4586

0/10000 (0.030 s)      probe=256: 0.826 s 1-R@1: 0.1320 1-R@10: 0.4589
</span>
     
---
To improve the results, not sure if we should try a different vector transform used for building the index e.g. OPQ64_128 or a different IVF index type.

Please let us know the right set of arguments to be used for the SIFT1B/DEEP1B dataset running on an A100 GPU card

**Comment by mdouze** [comment]
You could try to use more memory, see 
https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index

**Comment by karthik86248** [comment]
Thank you. That is helpful info.
