### ISSUE TITLE
How to build k neighbor graph based on faiss?

### ISSUE THREAD

**Issue by HelloWorldLTY** [facebookresearch/faiss#3098]
Hi, I intend to acclecrate my neighbor graph construction process absed on faiss:

https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.kneighbors_graph.html

I did not find related codes. Could you please help me? Thanks.

**Comment by mdouze** [comment]
see https://github.com/facebookresearch/faiss/tree/main/benchs#knn-graph-on-deep1b
