### ISSUE TITLE
GPU Index not support add_with_ids?

### ISSUE THREAD

**Issue by 0DF0Arc** [facebookresearch/faiss#311]
reference to issue 295.
Hey, sorry about late response, was sick for a short time. found the issue is closed, open a new one.

Index is trained by index_facroty('IMI2*8, PQ2_16') and then saved. the load the index from disk and get the error message:

  what():  Error in virtual void faiss::Index::add_with_ids(faiss::Index::idx_t, const float*, const long int*) at /root/workspace/faiss-cmake/src/Index.cpp:34: add_with_ids not implemented for this type of index

this is my code:
faiss::Index* cpu_index = faiss::read_index(index_file);
std::vectorfaiss::gpu::StandardGpuResources* resources;
faiss::gpu::GpuMultipleClonerOptions* options = new faiss::gpu::GpuMultipleClonerOptions();
code for multi gpu resources & options*
faiss::Index* gpu_index = faiss::gpu::index_cpu_to_gpu_multiple((std::vectorfaiss::gpu::GpuResources* &)resources, devices, cpu_index, options);

std::vector ids;
for (int i = 0; i < nb_1; i++)
{
ids.push_back(i);
}
}
index->add_with_ids(nb_1, baseVecs_1.data(), ids.data());

**Comment by 0DF0Arc** [comment]
by the way, i set options->shard = false, when set it is true, add_with_ids works ok.

**Comment by wickedfoo** [comment]
IMI is not supported on GPU.

Also, this cannot be your entire code, as `index` is not defined above, only `gpu_index` and `cpu_index` are listed. Do you have more of the code?
