### ISSUE TITLE
HNSW as post index for IVF

### ISSUE THREAD

**Issue by kimihailv** [facebookresearch/faiss#3111]
# Summary

I want to create a HNSW index with IVF, but index factory can't parse "IVF5000_HNSW16,HNSW"
# Platform

OS: Ubuntu

Faiss version: 1.7.4

Installed from: pip

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

```python
import faiss

faiss.index_factory(16, "IVF5000_HNSW16,HNSW") # returns Error: 'index_ivf' failed: could not parse code description HNSW in IVF5000_HNSW16,HNSW
```
I've also tried "IVF5000_HNSW16,HNSW,Flat", but faced the same problem.

**Comment by shiwanghua** [comment]
How about 'HNSWFlat' ?

**Comment by kimihailv** [comment]
I want to use IVF with HNSW as coarse quantizer and HNSW as index for post-verification. Maybe I don't understand the idea of IVF:

1) Train Kmeans
2) Find the nearest cluster for a query vector using coarse quantizer (HNSW in my case because k is large).
3) Find the neighbours in the nearest cluster from 2) using HNSW

**Comment by mdouze** [comment]
Sorry for not answering. This is not supported in Faiss (although this method is used in some research works).
