### ISSUE TITLE
Incorrect implementation of search_preassigned

### ISSUE THREAD

**Issue by mdouze** [facebookresearch/faiss#3113]
# Summary

Faiss version: 1.7.4

Installed from: anaconda

Running on:
- [* ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ *] Python

`ivf_tools.search_preassigned` *does not* support pretransforms in splite of what the doc says. 
Besides it would be nice to pass on the `store_pairs` parameter.

https://github.com/facebookresearch/faiss/blob/main/contrib/ivf_tools.py#L29

**Comment by mdouze** [comment]
Let's please the submitter!

**Comment by mlomeli1** [comment]
Solved.
