### ISSUE TITLE
`faiss::IndexRefineFlat::search()` accepts the new `SearchParameters` struct but throws an error

### ISSUE THREAD

**Issue by cjnolet** [facebookresearch/faiss#3118]
The `search()` APIs accept a `SearchParameters` struct directly but the refinement index doesn't propagate it down to the internal index type. This makes it hard to use the refinement API with IVFPQ, for example. There's an assertion that throws an error if the params passed into search.

There might be another way to use this API in the C++ layer but it's not immediately obvious. I can open a PR to propagate the params down to the internal index.

**Comment by alexanderguzhva** [comment]
I have a code that does it, let me create a PR

**Comment by alexanderguzhva** [comment]
@cjnolet please check #3122
