### ISSUE TITLE
Slower SIFT1M benchmarks results on GTX Geforce 1060

### ISSUE THREAD

**Issue by sourabhd** [facebookresearch/faiss#312]
Benchmark Approximate SIFT 1M runs slower than exact search on

GPU: GeForce GTX 1060 
CPU: Intel Core i7-6700HQ CPU @ 2.60GHz
RAM: 16GB

It also show a segmentation fault on nprobe=512.

Please see the logs below:

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

$ python bench_gpu_sift1m.py 
load data
load GT
============ Exact search
add vectors to index
warmup
benchmark
k=1 1.094 s, R@1 0.9914
k=2 1.124 s, R@1 0.9930
k=4 1.126 s, R@1 0.9932
k=8 1.126 s, R@1 0.9932
k=16 1.128 s, R@1 0.9932
k=32 1.135 s, R@1 0.9922
k=64 1.165 s, R@1 0.9931
k=128 1.193 s, R@1 0.9932
k=256 1.317 s, R@1 0.9931
k=512 1.676 s, R@1 0.9923
k=1024 2.764 s, R@1 0.9931
============ Approximate search
train
WARNING clustering 100000 points to 4096 centroids: please provide at least 159744 training points
add vectors to index
warmup
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 655360000 B, highwater 0 B)
benchmark
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 655360000 B, highwater 655360000 B)
nprobe=   1 7.809 s recalls= 0.3181 0.4210 0.4305 
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 655360000 B, highwater 655360000 B)
nprobe=   2 7.815 s recalls= 0.3835 0.5422 0.5621 
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 655360000 B, highwater 655360000 B)
nprobe=   4 7.834 s recalls= 0.4357 0.6514 0.6866 
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 655360000 B, highwater 655360000 B)
nprobe=   8 7.866 s recalls= 0.4759 0.7436 0.7959 
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 655360000 B, highwater 655360000 B)
nprobe=  16 7.918 s recalls= 0.5078 0.8125 0.8838 
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 655360000 B, highwater 655360000 B)
nprobe=  32 8.018 s recalls= 0.5257 0.8563 0.9410 
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 655360000 B, highwater 655360000 B)
nprobe=  64 8.244 s recalls= 0.5317 0.8742 0.9660 
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 655360000 B, highwater 655360000 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 6459392 B, highwater 655360000 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 6459392 B, highwater 655360000 B)
nprobe= 128 8.637 s recalls= 0.5347 0.8819 0.9762 
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 655360000 B, highwater 655360000 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 327680000 B, highwater 655360000 B)
nprobe= 256 9.398 s recalls= 0.5353 0.8845 0.9794 
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 655360000 B, highwater 655360000 B)
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 327680000 B, highwater 655360000 B)
nprobe= 512 10.951 s recalls= 0.5352 0.8846 0.9799 
Segmentation fault (core dumped)

**Comment by wickedfoo** [comment]
Hi,

Your GPU doesn't have enough memory (typically >8 GB is required). You'll need to disable precomputed codes for the test.

See the:
WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size (alloc 327680000 B, highwater 655360000 B)
warnings
