### ISSUE TITLE
Faiss in python segfaults if faiss is imported before open3d

### ISSUE THREAD

**Issue by cansik** [facebookresearch/faiss#3120]
# Summary

As mentioned in #2555, `faiss` can lead to a segfault if the import order is not correct. The problem for me is the [open3d](https://pypi.org/project/open3d/) (`0.17.0`)  module by Intel which can not be imported after `faiss`. Otherwise the import of open3d is crashing with a segfault.

Since there are known library compatibility issues with `faiss`, I would guess this is more on the `faiss` side, than on the open3d side.

# Platform

OS: macOS Sonoma but also on Windows 11

Faiss version:  `1.7.4`

Installed from: `pip install faiss-cpu`

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

First install the dependencies:

```
pip install open3d==0.17.0 faiss-cpu==1.7.4
```

And run the following code snippet:

```python
import faulthandler
faulthandler.enable()

import faiss
import open3d

print("worked")
```

Results in the following error message:

```
Fatal Python error: Segmentation fault

Thread 0x00000001e0919300 (most recent call first):
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>"
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

The following works without a problem:

```python
import open3d
import faiss
```

**Comment by mdouze** [comment]
please install Faiss (and possibly open3d) with anaconda
