### ISSUE TITLE
[Question] Can I use FAISS to do balanced clustering?

### ISSUE THREAD

**Issue by Ishitori** [facebookresearch/faiss#3123]
# Summary

I have a few hundred million vectors of 32d and for one use case I would like to split them into N clusters which are approximately of the same size. I know that clustering is a backbone for FAISS, but I am not sure, can I instruct FAISS to do balanced clustering? If  it is possible, how do I do that?

**Comment by mdouze** [comment]
Faiss supports only k-means clustering that is not balanced by design.
