### ISSUE TITLE
Remove ids from IVFPQFastScan index

### ISSUE THREAD

**Issue by aguerreb** [facebookresearch/faiss#3128]
Hi, 

Is it possible to remove ids from a IVFPQFastScan index? I noticed that the add_with_ids() function works, but I keep getting error messages with remove_ids(). 

Thanks!

**Comment by mdouze** [comment]
Right, this support is missing. Marking as enhancement.

**Comment by aguerreb** [comment]
Great, thanks!

**Comment by mdouze** [comment]
hmm this is *not* completed
