### ISSUE TITLE
Using Mahalanobis distance but with multiple covariances

### ISSUE THREAD

**Issue by HarshitGupta29** [facebookresearch/faiss#3130]
I have a set of Gaussians in 3D, X, and a set of points P. 
For each point I want to compute closest gaussian in X with Mahalanobis distance. Since every gaussian has his own covariance, it is not possible to whiten whole data and run faiss search ([https://github.com/facebookresearch/faiss/issues/478]). 

Any suggestions how can I approximate this ?

**Comment by mdouze** [comment]
There is no way to do this exactly. 
If speed is important, I would try to find a shortlist of candidates using Euclidean distances then rerank with Mahalanobis. 
Note that Faiss is not designed to handle low-dimensional vectors efficiently, so you may be better off using kd-trees from another package.

**Comment by HarshitGupta29** [comment]
I implemented it and the code is available here: [https://github.com/HarshitGupta29/3D-Chamfer-Loss-with-Mahalanobis-Distance](https://github.com/HarshitGupta29/3D-Chamfer-Loss-with-Mahalanobis-Distance)
