### ISSUE TITLE
Is it possible to use faiss to reduce the size of vectors?

### ISSUE THREAD

**Issue by matveymotyvin** [facebookresearch/faiss#3131]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by mlomeli1** [comment]
depending on what exactly you need to do @matveymotyvin, see for example, https://github.com/facebookresearch/faiss/wiki/Vector-codecs or https://github.com/facebookresearch/faiss/wiki/Lower-memory-footprint
