### ISSUE TITLE
GPU KMeans reports TypeError

### ISSUE THREAD

**Issue by xuguangning1218** [facebookresearch/faiss#3136]
# Summary

When I set `gpu=True` in `faiss.Keams` it reports a Type Error. This error still exists even I have added `import faiss.contrib.torch_utils`  referring to issues [#3127](https://github.com/facebookresearch/faiss/issues/3127) and [#2902](https://github.com/facebookresearch/faiss/issues/2902)

# Platform

OS: 
Ubuntu 20.04.1 LTS

Faiss version: 
faiss-gpu                1.7.4
pytorch                   2.1.1
pytorch-cuda         12.1
cudatoolkit              11.4.1

Installed from:  
`conda install faiss-gpu=1.7.4 mkl=2021 pytorch pytorch-cuda numpy -c pytorch -c nvidia`

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

I refer to the example from [here](https://github.com/facebookresearch/faiss/wiki/Faiss-building-blocks:-clustering,-PCA,-quantization) and change it to GPU version. Besides, I have added `import faiss.contrib.torch_utils`  referring to issues [#3127](https://github.com/facebookresearch/faiss/issues/3127) and [#2902](https://github.com/facebookresearch/faiss/issues/2902)

```
import faiss
import torch
import faiss.contrib.torch_utils 

ncentroids = 1024
niter = 20
verbose = True
x = torch.rand(2000, 2).cuda()
d = x.shape[1]
kmeans = faiss.Kmeans(d, ncentroids, niter=niter, verbose=verbose, gpu=True)
kmeans.train(x)
```

 
I receive this error:
```
TypeError                                 Traceback (most recent call last)
Cell In[4], line 7
      5 d = x.shape[1]
      6 kmeans = faiss.Kmeans(d, ncentroids, niter=niter, verbose=verbose, gpu=True)
----> 7 kmeans.train(x)
File ~/anaconda3/envs/new_typhoon/lib/python3.10/site-packages/faiss/extra_wrappers.py:440, in Kmeans.train(self, x, weights, init_centroids)
    414 def train(self, x, weights=None, init_centroids=None):
    415     """ Perform k-means clustering.
    416     On output of the function call:
    417 
   (...)
    438 
    439     """
--> 440     x = np.ascontiguousarray(x, dtype='float32')
    441     n, d = x.shape
    442     assert d == self.d

File ~/anaconda3/envs/new_typhoon/lib/python3.10/site-packages/torch/_tensor.py:1032, in Tensor.__array__(self, dtype)
   1030     return self.numpy()
   1031 else:
-> 1032     return self.numpy().astype(dtype, copy=False)

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

**Comment by mdouze** [comment]
You can convert to numpy, for Kmeans, the overhead w.r.t. the execution runtime should be minimal.
