### ISSUE TITLE
How to convert distance values into 0-100 similarity?

### ISSUE THREAD

**Issue by hipitt** [facebookresearch/faiss#315]
CODE：
>D, I = index.search(xq, k)     # actual search

How can ‘D’ be converted to 0-100 (similarity)?

**Comment by mdouze** [comment]
Hi 
If the vectors are L2-normalized and the index is a L2 index (the default) then you can just do 

sim = 100 * (4-D)

**Comment by hipitt** [comment]
@mdouze copy that

**Comment by jcmvc** [comment]
@mdouze Hey Matthijs, could you help to explain what does "4" means in sim = 100 * (4-D)? Why not "1"? Thank you!

**Comment by mdouze** [comment]
The squared distances between normalized vectors are between 0 (same vector) and 4 (opposite vectors), so the linear operation to convert them to a similarity [0, 100] is 

25 * (4 - D)

(my previous formula was wrong)

**Comment by gauravgund** [comment]
@mdouze : I am using faiss.IndexIDMap and I want to obtain scores to apply thresholding. So, i converted my word vectors into L2-norm and then used the operation i.e. 25*(4-D) but it is giving more similarity scores for bad values in the topk values. Ideally, it should give a higher value to top1 value but it is the other way round using the operation you suggested. Any workaround for this?

**Comment by tempdeltavalue** [comment]
> Hi If the vectors are L2-normalized and the index is a L2 index (the default) then you can just do
> 
> sim = 100 * (4-D)

You can do it if you have vectors normalised in range 0 - 4 . Does l2_normalize in faiss normalised in this range ?

**Comment by akhilanaz** [comment]
I have used :
index_L2 = faiss.IndexFlatL2(vectormatrix.shape[1])   
print(index_L2.is_trained)
faiss.normalize_L2(vectormatrix)
index_L2.add(vectormatrix)                
print(index_L2.ntotal),

where my vector is of shape 768,
and for the nearest neighbors I am receiving a shortest distance from the range of 212, instead of zero.
Can you explain why is it so.
