### ISSUE TITLE
IndexIDMap2Template does not override get_distance_computer, which may cause a problem

### ISSUE THREAD

**Issue by RongchunYao** [facebookresearch/faiss#3153]
get_distance_computer uses "d" that IndexIDMap2Template inherits from faiss::Index, while the real index that takes effect is the sub index (that pointer) of struct IndexIDMap2Template. 
So the distance computer returned by get_distance_computer would cause a segment fault for my faiss-1.6.2.
Thank you so much.

**Comment by mdouze** [comment]
would you mind posting a small repro script? 
Thanks
