### ISSUE TITLE
Question: How to merge many IndexFlat with constant memory usage?

### ISSUE THREAD

**Issue by liamvdv** [facebookresearch/faiss#3155]
# Summary
Hey, I'm having a memory constraint machine that creates a plain faiss.IndexFlatL2, which might later be run on a different machine with more memory (or mmap).

I'm unable to produce the necessary code to merge these indexes into a single index on disk with constant memory usage. How do I merge the indexes on disk? I've tried mmap the other indexes and then 
```py
for other in others:
    idx.merge_from(other)
```
but memory_profile shows significant memory usage. 
Help is highly appreciated 👋🏻 

# Platform

OS: 

Faiss version: 

Installed from:   pip install faiss-cpu

Faiss compilation options: 

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

**Comment by mdouze** [comment]
mmap is not supported yet for flat indexes (somewhat counter-intuitively)
did not check the mem usage issue yet...

**Comment by liamvdv** [comment]
@mdouze thanks for the reply. Let me approach this form two different angles then:

# 1 faiss.write_file binary format
I want to write a python `.append` function that uses constant memory to append to an disk IndexFlat(L2), readable by faiss.read_index(). Where can I find the binary format definition of faiss.write_index() for IndexFlat? I've done some searching on the code base myself, there is what I think I know: 
Format: Little Endian
```
32b fourcc Index Type Identifier, e. g. b'IxF2' for FlatIndex
32b signed int dimension
64b signed int ntotal 
64b dummy: 1 << 20
64b dummy: 1 << 20
8b    bool is_trained
32b enum metric_type [0, 1, ...]; 1 for METRIC_L2
# ---- from here on I get flake results ----
32b float32 metric_arg
32b verbose
```
This makes the total header size 45 bytes. Looking at the binary file however, It seems to do some alignment if ntotal > 0 with 0x000080 to get to 48 bytes.  Where is that alignment placed? Where am I misreading the code?

# 2 Alternative Index / Implementation for MMap
I would like to heavily oversubscribe the machines memory with indexes. I though I could use mmap for that. IndexFlat has acceptable latency for our expected index sizes. Now you tell me that it is not supported. I might be asking the wrong question here, and would highly appreciate your take on the best setup for the described case, but to my mind this means:

    Straw Man: I should use IndexIVF and and always search all centroids? Should I expect a runtime penalty? Afaik this will require all indexes to be in memory for training. *Does IndexIVF support memory mapping?** 
    Suggestions: Make `faiss.read_index(path, faiss.IO_FLAG_MMAP)` throw an error for non-memory-mapped files. Optionally just add a stricter flag`IO_FLAG_MMAP_STRICT` to preserver backwards compat.

**Comment by liamvdv** [comment]
Context: I've now found https://github.com/facebookresearch/faiss/wiki/Indexes-that-do-not-fit-in-RAM#on-disk-storage

**Comment by liamvdv** [comment]
Leave It Better Than You Found It: https://github.com/facebookresearch/faiss/wiki/Indexes-that-do-not-fit-in-RAM#on-disk-storage apparently does not refer to 'IndexFlat' as a standard index. Maybe you could sharpen the wording to generally say what indexes support memory mapping 🤗
