### ISSUE TITLE
QUESTION: Is it possible to do Kernel PCA with faiss?

### ISSUE THREAD

**Issue by dominiquegarmier** [facebookresearch/faiss#3176]
In short: Is it possible to do Kernel PCA in faiss?
I.e. we have `faiss.PCAMatrix`, is there an analogous way to kernel PCA?

**Comment by dominiquegarmier** [comment]
I can see how this might be enirely inpossible and would anyways depend on the kernel function that is chosen.

**Comment by mdouze** [comment]
It is not implemented. Could you use that as a pre-processing prior to calling Faiss?

**Comment by dominiquegarmier** [comment]
Well im unsure if this would be possible, as applying the kernel to my data would already blow up the memory.

I also dont really know how faiss's PCA is implemented. I assume that it's not doing a full SVD?
However im unaware of any way of computing a kernel PCA without computing the kernel matrix and the SVD of it.
