### ISSUE TITLE
When new release (1.7.5) ?

### ISSUE THREAD

**Issue by snehalpatel-8451** [facebookresearch/faiss#3177]
# Summary

# Platform

OS: 

Faiss version:  1.7.5

Installed from:  

Faiss compilation options: 

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [x] C++
- [x] Python

Just wanted to know if there's any plan to do an official 1.7.5 release or not. I'm having hard time building from source and I can also see 100+ commits fixing many stuff in the main branch.

**Comment by mdouze** [comment]
Next release will probably be 1.8.0, in a few months. 

Don't hesitate to use nightly builds, they are up-to-date with the current version, see 
https://github.com/facebookresearch/faiss/blob/main/INSTALL.md#installing-faiss-via-conda
