### ISSUE TITLE
How faiss do the search in gpu shard/replicate mode?

### ISSUE THREAD

**Issue by paryang** [facebookresearch/faiss#318]
Hi, I try to read the code to find how multi-gpus do the search, i think should be something like this(say 4 gpus):
for replicate mode : each single gpu returns k results with distance & indices, and then merge or reduce results of 4 gpus(like 4* k results to k results). but i didn't find the code doing the merge/reduce. 
for shard mode : 4 gpus doing the search process simultaneously, and return k results with disatnce & indices in one shot.
Am I right, and can you tell me where the code is? I didn't find it

**Comment by mdouze** [comment]
Hi 
They are supported respectively by `IndexProxy` and `IndexShards`

https://rawgit.com/facebookresearch/faiss/master/docs/html/classfaiss_1_1gpu_1_1IndexProxy.html

https://rawgit.com/facebookresearch/faiss/master/docs/html/structfaiss_1_1IndexShards.html
