### ISSUE TITLE
where is python documentation? I confuse a parameter about index.search?

### ISSUE THREAD

**Issue by ciaoyizhen** [facebookresearch/faiss#3180]
In the code prompt, the input parameters of index.search are n, x, k and others. I saw that the input parameters in some tutorials directly write index.search(xq, k), but the corresponding relationship is n->xq. , x->k And when I pass parameter k=k through keywords, the results are consistent? I'm very confused. Can you give me an answer or provide python documentation? Thank you so much

**Comment by mdouze** [comment]
Please use the index.search docstrings in Python, eg. with ?index.search in a notebook.
