### ISSUE TITLE
faiss-gpu ist not using gpu but cpu

### ISSUE THREAD

**Issue by flexobrain** [facebookresearch/faiss#3181]
# Summary

# Platform

OS: Linux-Ubuntu-22.04

Faiss version: 1.7.4

Installed from: anaconda

Faiss compilation options: mlk and blas

Running on:
- [ o] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ o] Python

Install faiss-gpu and just utilize it with Ubuntu and gradio. I don't know how one could reproduce it.

 

The problem is that it isn't utilizing the GPU (i got this information via watch nvidia-smi). And thus is way slower.

**Comment by rangehow** [comment]
you may need to explicitly to code like this :

```
res = faiss.StandardGpuResources()
index = faiss.index_cpu_to_gpu(res, which gpu you want to use (like 0),index)
```

**Comment by mlomeli1** [comment]
@flexobrain  If you install faiss-gpu, it includes both faiss-gpu and cpu. In order to use the GPU functionalities you either instantiate the required GPU index directly, for example, ` idx_gpu = faiss.GpuIndexIVFFlat(res, d, nlist)` or you can use a CPU index and explicitely move it to the GPU as rangehow suggests. Please read the wiki for further details: 
https://github.com/facebookresearch/faiss/wiki/Running-on-GPUs

**Comment by a2082761** [comment]
@mlomeli1  I used StandardGpuResources and index_cpu_to_gpu as you suggested, but my code still uses 100% of the CPU, and torch recognizes CUDA well. Could you please suggest another solution?

**Comment by rangehow** [comment]
> @mlomeli1 I used StandardGpuResources and index_cpu_to_gpu as you suggested, but my code still uses 100% of the CPU, and torch recognizes CUDA well. Could you please suggest another solution?

I guess we need more info to make the question clear. Did you observe an increase in GPU memory usage? Could you please share the relevant code snippet for review?

What I’m suggesting is that you could copy a GPU sample snippet from the wiki [mlomeli1](https://github.com/mlomeli1) mentioned to see if it works. That would help identify the issue more quickly.

**Comment by mlomeli1** [comment]
I echo @rangehow 's suggestions, please provide more details of your issue, for instance, i)what index are  you using? Some index are not supported on gpu. That's why I suggested to have a look at the wiki as well
