### ISSUE TITLE
Is there a tutorial on importing images available

### ISSUE THREAD

**Issue by monkeycc** [facebookresearch/faiss#3184]
Is there a tutorial on importing images available

```

A folder

1. jpg

2. jpg


B folder

1. jpg

2. jpg


C folder

1. jpg

2. jpg
```

How to import corresponding images by number

How to convert it into a vector

How to save

```
ID_ Map.pkl

Vector. index

```

Finally, how to call images for image comparison and return results

I need a tutorial

**Comment by mdouze** [comment]
Faiss can import only vectors, ie. pre-computed image embeddings.
