### ISSUE TITLE
IndexHNSWFlat index empty result with IDSelectorBitmap

### ISSUE THREAD

**Issue by dshkliarenko** [facebookresearch/faiss#3186]
# Summary
IndexHNSWFlat index when used with IDSelectorBitmap in some cases returns empty result (-1) with negative similarity values although search on the same index without selector and applying filter manually on top does return correct items.
I noticed this behavior depends on the `m` parameter, if I increase it high enough the problem can be solved, however search time also increases a lot. The question is: is there a way to get the relevant similar items without sacrificing speed?

OS: Linux

Faiss version: 1.7.4

Installed from: PIP

Running on: CPU

Interface: Python

# Reproduction instructions

Vectors have the following shapes:
- vectors: (300,000, 250)
- query_vectors: (k, 250)
- mask: (80,000)

```
index = faiss.IndexHNSWFlat(vectors, m=10, faiss.METRIC_INNER_PRODUCT)
index.hnsw.efConstruction = 1000
index.hnsw.efSearch = 500

sel= faiss.IDSelectorBitmap(mask)
search_params = faiss.SearchParametersHNSW(sel=sel)
index.nprobe = 10
similarity, indices = index.search(query_vectors, k=40, params=search_params)
```
Result sample

similarity:
2.175009e+00,-3.402823e+38,-3.402823e+38,-3.402823e+38,-3.402823e+38,...
2.463270e+00,7.428635e-01,-3.402823e+38,-3.402823e+38,-3.402823e+38,...
-3.402823e+38,-3.402823e+38,-3.402823e+38,-3.402823e+38,-3.402823e+38,...
7.740420e-01,6.313836e-01,-3.402823e+38,-3.402823e+38,-3.402823e+38,...

indices:
172935,-1,-1,-1,-1,...
142230,53895,-1,-1,-1,...
-1,-1,-1,-1,-1,...
253016,161894,-1,-1,-1,...
...

**Comment by kuarora** [comment]
I am not able to reproduce the issue.  Could you provide a repro?

""":py"""
import numpy as np
d = 250
nt = 0
nb = 300000
nq = 40


""":py"""
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

""":py"""
import faiss
index = faiss.IndexHNSWFlat(d, 10, faiss.METRIC_INNER_PRODUCT)
index.hnsw.efConstruction = 1000
index.hnsw.efSearch = 500
index.add(xb)



""":py"""
bitmap = np.full(80000, True, dtype=bool)
bitmap = np.packbits(bitmap, bitorder='little')
sel = faiss.IDSelectorBitmap(bitmap)
search_params = faiss.SearchParametersHNSW(sel=sel)


""":py"""
index.nprobe = 10

similarity, indices = index.search(xq, k=40, params=search_params)
# similarity, indices = index.search(self.xq, k=1)
np.set_printoptions(threshold=np.inf)
print(indices.shape)
print(indices)

""":py"""
