### ISSUE TITLE
IndexIVF does not pass verbosety onto the clustering

### ISSUE THREAD

**Issue by JAicewizard** [facebookresearch/faiss#3188]
# Summary

As can be seen at https://github.com/facebookresearch/faiss/blob/b7681bef4018ddd99fa4e4784d3de19320d29943/faiss/IndexIVF.cpp#L100 the verbosity level is not passed on to the cluster training.

Sorry for removing half of the template, however I do not think this bug requires much more information.

# Platform

commit b7681bef4018ddd99fa4e4784d3de19320d29943 (latest on github)

# Reproduction instructions

Can easily be seen from the source code

**Comment by mdouze** [comment]
To make clustering verbose, please set `index.cp.verbose` to true.

**Comment by JAicewizard** [comment]
Since I am working with generic indexes, I am unable to set this (and I wasn't aware of this for the same reason), however for my usecase I can am fine with editing the faiss code for this.

I would appreciate to be able to set verbose for everything in an index (including clustering) for generic indexes.

I hope this explains my request well enough
