### ISSUE TITLE
AVX2 support doesn't compile with MSVC

### ISSUE THREAD

**Issue by borrrden** [facebookresearch/faiss#3193]
# Summary

The AVX2 implementation of FAISS appears to use intrinsics that are GNU specific (or at least don't port to Windows via MSVC).

# Platform

Windows 10.0.19045 
MSVC 2022

Faiss version: git tag v1.7.4

Installed from: Attempting to compile

Faiss compilation options:  

Probably doesn't much matter but using OpenBLAS compiled myself
CMake `set(FAISS_OPT_LEVEL "avx2" CACHE INTERNAL "")` and link with faiss_avx2 instead of faiss

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [X] C++
- [ ] Python

# Reproduction instructions

1. Get any BLAS implementation in order to satisfy the dependency requirements for building this library
2. Standard CMake dance (build directory, etc)
3. `cmake -DFAISS_OPT_LEVEL=avx2 -DFAISS_ENABLE_GPU=OFF -DFAISS_ENABLE_PYTHON=OFF ..` (assuming the source directory is one level up from the build directory)
4. `cmake --build . --config Release --target faiss_avx2 ..`

# Fix instructions

This boils down to 3 distinct issues:

1. The definition of `_mm_prefetch` in MSVC (and actually in the [Intel Intrinsics Guide](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_prefetch) suggesting GCC / clang are mistaken) takes a `const char *` as the first argument, not `const void *`.  This base is peppered with calls directly passing float pointers.
2. `__m128i_u` and `__m256i_u` are not portable.  However they are the exact same datatype as the non `_u` variants, just with some [implied side effects](https://stackoverflow.com/a/68939636/1155387) so I'm guessing it is safe to define them away to their non `_u` variants `#if defined(_MSC_VER) && !defined(__clang__)`.
3. By default Visual Studio implemented OpenMP 2.0, which doesn't allow signed indexes in for loops.  The following code violates this https://github.com/facebookresearch/faiss/blob/d87888b13e7eb339bb9c45825e9d20def6665171/faiss/utils/distances_fused/simdlib_based.cpp#L262-L266  

However, issue 3 can be worked around with some trickery, involving override CMake's FindMP module by setting `OpenMP_CXX_FLAGS="-openmp:llvm"`.  This turns on the "better" support (which is OpenMP 2.5 with a few 3.1 features including unsigned index types) for OpenMP in Visual Studio as noted [here](https://devblogs.microsoft.com/cppblog/openmp-task-support-for-c-in-visual-studio/)

**Comment by algoriddle** [comment]
I will add AVX2 to our contbuild to verify.

**Comment by algoriddle** [comment]
Confirmed that MSVC is not supported by the current implementation of AVX2. We welcome any PRs.

**Comment by borrrden** [comment]
Any opinions on the way to approach this?  I had simply cast all the prefetch calls blindly from `float *` to `char *`.  I'm assuming that this function, taking a `void *` in the case of Linux, is not going to be doing anything special due to the fact that it is a float.  It compiles and appears to function but if someone who knows better than me has a different approach let me know.  

Also do you care if the iterator above is signed or unsigned?  Does it have any implications?  Because as I mentioned it can be either fixed in code or in build option (though the build option will create a dependency on LLVM libomp which I think at this point might be included in the MSVC runtime but I haven't looked carefully into that yet)
