### ISSUE TITLE
What indexes does the faiss database use by default? Do you have any visual management tools for the faiss database?

### ISSUE THREAD

**Issue by qianbaidu1266** [facebookresearch/faiss#3194]
What indexes does the faiss database use by default? Do you have any visual management tools for the faiss database?

**Comment by algoriddle** [comment]
What do you mean 'by default'? The client code must specify the index type during index construction. 

For the second question, Faiss is not a full-fledged database, it 'only' provides the core functionality for vector search. As such, there are no visual management tools.
