### ISSUE TITLE
Question about SQ decode and search

### ISSUE THREAD

**Issue by xinhuitian** [facebookresearch/faiss#3205]
Hello，I have two questions about SQ:
1 Why we need to add 0.5 when doing decode here?
```
struct Codec8bit {
...

    static float decode_component(const uint8_t* code, int i) {
        return (code[i] + 0.5f) / 255.0f;
    }
}
```
2 I see we use the raw query vector to search quantized vectors in SQ, the quantized vectors will be decoded back during distance computation. Since SQ is a lossy compression technique, when searching a vector with itself, the L2 distance may not be zero,  so is it possible to encode query vector first, then decode it with the same quantizer before using it for search, to make the distance zero with two same vectors, when the distance value is meaningful as a similarity score? Or is there any other way to get an accurate distance value when the memory resource is limited?

Thanks for any help :-)

**Comment by mdouze** [comment]
1/ that's because if

i = floor(x)

if x is distributed uniformly, then the expected value of all x'es that are quantized to i is i + 0.5. 

2/ sure, you can use ```index.sa_decode(index.sa_encode(query_vector))``` to quantize the queries and perform symmetric distance comparisons (SDC) instead of asymmetric ones (ADC)

**Comment by xinhuitian** [comment]
> 1/ that's because if
> 
> i = floor(x)
> 
> if x is distributed uniformly, then the expected value of all x'es that are quantized to i is i + 0.5.
> 
> 2/ sure, you can use `index.sa_decode(index.sa_encode(query_vector))` to quantize the queries and perform symmetric distance comparisons (SDC) instead of asymmetric ones (ADC)

Thanks a lot!
