### ISSUE TITLE
search result issue

### ISSUE THREAD

**Issue by keithbyr** [facebookresearch/faiss#323]
Hi all, I have a very simple question. I trained a index containing features fetched from the same CNN extractor.  I need to continually add the new feature into index by index.add(new_feature).  When using index.search and obtained the nearest feature index. How can I get the nearest feature itself ?  Any attribution available for fetching the nearest feature ?

**Comment by mdouze** [comment]
Hi 
You can call `search_and_reconstruct` instead of just `search`. NB that for IVFPQ this will return an approximation of the stored vector because it uses a lossy codec.
