### ISSUE TITLE
Assigning New Indices to Pre-existing Clusters

### ISSUE THREAD

**Issue by whatsbirddd** [facebookresearch/faiss#3232]
# Summary

I want to assign newly created indices to the clusters I previously made using kmeans.centroids. Can you provide me with any reference materials to implement this?

When I perform k-means clustering, I use the following code:
```
kmeans = faiss.Kmeans(768, ncentroids, niter=niter, verbose=verbose)
kmeans.train(allNonMasked.astype("float32"))

```
# Platform

OS: ubuntu 18.04

Faiss version: faiss-gpu==1.7.2

Installed from: 

Faiss compilation options: 

Running on:
- [] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [✅ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
use `kmeans.assign`
https://github.com/facebookresearch/faiss/blob/main/faiss/python/extra_wrappers.py#L578
