### ISSUE TITLE
Indexed vectors are not seen in the search results using Faiss SQfp16 if any vector value is outside of FP16 Range

### ISSUE THREAD

**Issue by naveentatikonda** [facebookresearch/faiss#3244]
# Summary
While using the Scalar Quantizer SQfp16 if the input vectors has any value that is outside of FP16 range appx. [-65504, 65504], then [while decoding the vector back](https://github.com/facebookresearch/faiss/blob/main/faiss/utils/fp16-fp16c.h#L24) it is returned as +inf (if the value is above FP16_MAX) or -inf (if the value is less than FP16_MIN) and the distance computed on top of this is infinite. During the search operation, for HNSW if the computed distance (in this case `infinite`) is [greater than the threshold ](https://github.com/facebookresearch/faiss/blob/main/faiss/impl/HNSW.cpp#L614)(FP32_MAX), then those vectors are not returned in the results.

Is this an expected behaviour or a defect ?

**Comment by naveentatikonda** [comment]
@mdouze Did you get a chance to look into this issue?
@alexanderguzhva as you have contributed to SQ. Do you know if this is the expected behavior of this feature?

**Comment by naveentatikonda** [comment]
> Thanks for noticing this. What would be the alternative behavior? Clipping out-of-range values to the [min, max] range of fp16 ? This is actually what the other scalar quantizers do (because there is no notion of infinity for these cases).

I could think of two alternatives:
1. Normalize or clip out of range values to [FP16_MIN, FP16_MAX] values like you mentioned. But, this approach will impact recall badly if most of the input vectors lies between [FP16_MIN, FP16_MAX] to [FP32_MIN, FP32_MAX]. Still we can specify these limitations clearly in the documentation so that users can use this feature at their own risk or interest.

2. An other way is to validate the input data and reject it with an exception if it is out of [FP16_MIN, FP16_MAX] range. But, the downside here is user needs to do the normalization on their end to bring it down to that range.

@mdouze WDYT ?
@alexanderguzhva Do you have any suggestions ?

**Comment by alexanderguzhva** [comment]
@naveentatikonda The somewhat limited range is the natural property of fp16 data type. So, I would see the situation as an inappropriate use of the SQfp16 for such a case. So, the control over the range of the values needs to be performed outside of Faiss, no doubt. 
I personally would go with the rescaling of the data, because fp16 data type has a sufficiently long mantissa. So, during the training stage you compute the [min, max] range of the data, and if [min, max] lies outside / close to fp16 range, then you scale the data down, say, by multiplying by 0.25 or some other `1/2^N` value, and go ahead with the training. Such a `1/2^N` multiplier becomes a bound constant of the particular index, and it used to in-scaling (input data) and out-scaling (output data).

**Comment by naveentatikonda** [comment]
> @naveentatikonda The somewhat limited range is the natural property of fp16 data type. So, I would see the situation as an inappropriate use of the SQfp16 for such a case. So, the control over the range of the values needs to be performed outside of Faiss, no doubt. I personally would go with the rescaling of the data, because fp16 data type has a sufficiently long mantissa. So, during the training stage you compute the [min, max] range of the data, and if [min, max] lies outside / close to fp16 range, then you scale the data down, say, by multiplying by 0.25 or some other `1/2^N` value, and go ahead with the training. Such a `1/2^N` multiplier becomes a bound constant of the particular index, and it used to in-scaling (input data) and out-scaling (output data).

I agree with your point on controlling the range of input. But, what does `N` refers to in `1/2^N`

**Comment by alexanderguzhva** [comment]
@naveentatikonda `N` is an integer that is computed in the way, so that `[min/2^N, max/2^N]` range is inside fp16 range, and, possible, not super close to fp16 border values
