### ISSUE TITLE
New release plans?

### ISSUE THREAD

**Issue by plurch** [facebookresearch/faiss#3263]
Hello, thanks for the great package that is widely used 👍 

I am curious to know if there are any plans for a new release/version number for faiss?

v1.7.4 was released on Apr 20, 2023 which is almost a year old by now. There have been many improvements merged in
 the `main` branch since then (including MKL installation fix).

It would be nice to have an up to date version number available for installation via `conda`, rather than having to install via `nightly` which could introduce issues for production systems.

**Comment by Charlyo** [comment]
I second this! Would like to have a release with the already merged indexidmap pre-search filtering.

**Comment by mlomeli1** [comment]
The new version of faiss is coming out very soon!

**Comment by Charlyo** [comment]
Can you give us an ETA?

**Comment by mlomeli1** [comment]
@Charlyo we expect to do the release in two weeks time.

**Comment by Charlyo** [comment]
Thank you for the answer, @mlomeli1 !

**Comment by mlomeli1** [comment]
https://github.com/facebookresearch/faiss/releases/tag/v1.8.0

**Comment by Charlyo** [comment]
Awesome, thank you @mlomeli1 & co.

**Comment by plurch** [comment]
Thanks @mlomeli1 ! 🚀
