### ISSUE TITLE
Does IndexHNSW work on GPU? (Python)

### ISSUE THREAD

**Issue by jeyendranbalakrishnan** [facebookresearch/faiss#3264]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by mlomeli1** [comment]
see "implemented indexes" in https://github.com/facebookresearch/faiss/wiki/Faiss-on-the-GPU

**Comment by jeyendranbalakrishnan** [comment]
Thanks!
From that reference, it looks the answer is no :-)
