### ISSUE TITLE
Fix warning for deprecated storage in Pytroch interface

### ISSUE THREAD

**Issue by mdouze** [facebookresearch/faiss#3273]
# Summary

For all methods that use the torch_utils package, there is a warning 

```
faiss/contrib/torch_utils.py:44: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
```

This is annoying and will break in the future, so let's address this (we tried to do it before, but it *did* break with older pytorch)

**Comment by ramilbakhshyiev** [comment]
Fixed in https://github.com/facebookresearch/faiss/pull/3301
