### ISSUE TITLE
Intel CPU vs AMD Ryzen performance

### ISSUE THREAD

**Issue by OrkhanHI** [facebookresearch/faiss#3277]
# Platform

OS: Ubuntu 22.04

Running on:
- [ ] CPU

Interface: 
- [ ] C++
- [ ] Python

Hi, did anybody benchmark FAISS performace on Intel i9-14 vs AMD Ryzen 7800x3d performance.

I know that FAISS is using Intel MKL library, but is there big difference in performance between that two CPUs?

Thanks.

**Comment by Gca43** [comment]
- [ ] Cry @tomdyson was a very c@_[](https://github.com/dataprofessor/code/issues/31)_

**Comment by Gca43** [comment]
4a

**Comment by Gca43** [comment]
> - [ ] Cry @tomdyson was a very c@_[](https://github.com/dataprofessor/code/issues/31)_
