### ISSUE TITLE
Perform IVF first, then PQ within each region.

### ISSUE THREAD

**Issue by taylorgoolsby** [facebookresearch/faiss#3283]
I have a need for fast insert times, so I am thinking about using IVF because it does not need to be retrained when adding a point. The new point simply needs to be categorized.

I would also like to use PQ to save on memory. However, I think the recall performance using PQ is too poor for my use case (long term memory system).

Instead, I would like to first train an IVFFlat Index, and then perform PQ Encoding within each IVF Cluster. I believe this will give good recall performance, good insert speed, and still provide benefits for memory, albeit, less than PQ first. Here I have attached some sketches to give an idea of how it would work, and how it compares to PQ first.

Is this currently possible with the index factory?

<img width="1054" alt="image" src="https://github.com/facebookresearch/faiss/assets/14286600/cc9aa736-28ee-43bc-8408-5477b61ec93a">
<img width="1256" alt="image" src="https://github.com/facebookresearch/faiss/assets/14286600/3bbae043-fa9f-4a5a-8080-2fc05af2018d">
<img width="1523" alt="image" src="https://github.com/facebookresearch/faiss/assets/14286600/ccf7d835-e4fa-44d4-811f-fce807a1ca19">

**Comment by taylorgoolsby** [comment]
I have included a video where I explain myself: https://youtu.be/58AFEGpqoHM
There is a second video explaining more found in the video's description.

**Comment by mdouze** [comment]
AFAIU this is the IVFADC index described in  
https://inria.hal.science/inria-00514462/file/jegou_pq_postprint.pdf
(called IVFPQ in Faiss). If not please explain the difference.
