### ISSUE TITLE
Is normalization required for SPACEV1B Dataset

### ISSUE THREAD

**Issue by karthik86248** [facebookresearch/faiss#3287]
# Summary

GloVe and NYTimes dataset require to be normalized before adding to the index with FAISS. More details : https://github.com/facebookresearch/faiss/issues/1639

Any recommendation for the SPACEV1B dataset (https://github.com/microsoft/SPTAG/tree/main/datasets/SPACEV1B) ?

Since SPACEV1B is also a text dataset, I'd guess it has to be normalized before building the index?

# Platform

OS: Ubuntu 22.04.1 LTS

Faiss version:  1.7.4

Installed from:  Conda

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by mdouze** [comment]
I don't think so. The baseline from 
https://github.com/harsha-simhadri/big-ann-benchmarks/blob/main/neurips21/track1_baseline_faiss/baseline_faiss.py
does not mention normalization. 
You can also ask that question on the big-ann-benchmarks github.
