### ISSUE TITLE
How to reset on index ?

### ISSUE THREAD

**Issue by keithbyr** [facebookresearch/faiss#329]
Hey , I have a question about how to reset the index. I have a index continue adding features into itself like index.add().  If the memory occupation of index is larger than 6G, I will reset the index and the ntotal should be reset to 0. Is there any useful function in faiss ? I didn't find it in tutorial... Thank you very much~

**Comment by wickedfoo** [comment]
index.reset() should clear out the contents but keep any learned parameters that it was trained on.
