### ISSUE TITLE
Porting FAISS to Embedded Linux Devices: Feasibility and Recommendations

### ISSUE THREAD

**Issue by BruceYang-yeu** [facebookresearch/faiss#3292]
# Summary

I am currently exploring the possibility of using FAISS for similarity search in an embedded Linux environment. Given the constraints typically associated with embedded systems, such as limited computational power, memory, and storage, I would like to inquire about the feasibility and potential approaches for porting FAISS to such platforms.

# Platform

ARM V7/V8
OS: Linux
Running on:
-  CPU
Interface: 
-  C++

Here are some specific questions I have:

1. Has FAISS been successfully deployed on any embedded Linux platform, and if so, could you provide some details about the hardware specifications and the use case?

2. Are there any known limitations or issues that I should be aware of when considering FAISS for an embedded environment?

3. Could you offer any guidance or recommendations on how to optimize FAISS for use on an embedded device? For instance, are there particular compilation flags, reduced precision modes, or specific components of the library that are more suitable for resource-constrained environments?

4. If direct porting of FAISS is not feasible, do you have any suggestions for alternative approaches or lightweight versions of the library that could serve a similar purpose?

I appreciate any insights or advice you can provide, as it will greatly assist in determining the viability of integrating FAISS into our project.

Thank you for your time and assistance.

Best regards,
cooley

**Comment by mdouze** [comment]
Thanks for this effort. 
ARM64 machines on Linux are supported directly. 
I expect 32 bit or big-endian platforms to be more problematic.
The main constraint is that there should be a BLAS/Lapack implementation and a C++17 compiler  for the target platform. 
Beyond that, the build scripts probably need some hacking to work on exotic environments.

**Comment by BruceYang-yeu** [comment]
Thank you for your prompt response and the valuable information provided.

I would like to clarify that our target embedded Linux system is a 32-bit platform with a CPU that has 4 cores and a clock speed of 1.2 GHz. Additionally, our current toolchain's GCC version supports up to C++14, not C++17.

Given these constraints:
1. Is there a known workaround or a modified version of FAISS that could potentially be compatible with a 32-bit architecture and C++14?
2. Could you suggest any BLAS/Lapack implementation that is known to work well on 32-bit systems?
3. Are there any specific parts of the build scripts or the library itself that you anticipate will require modification to accommodate our environment?

We understand that this setup is not ideal, but any guidance on how we might proceed, or suggestions for alternative solutions, would be greatly appreciated.

Best regards,
cooley

**Comment by mdouze** [comment]
1. we moved to C++17 not too long ago, Faiss 1.7.4 should compile with C++14
2. OpenBLAS is a widely supported BLAS imeplementation https://github.com/OpenMathLib/OpenBLAS
3. normally, all int types are sized (ie. int64 rather than long). So it should work. 
Is the platform big endian? There may be issues with that as well.
