### ISSUE TITLE
Level1Quantizer::train_q1 setting quantizer verbosity after calling quantizer's train method, shouldn't it be otherwise ? 

### ISSUE THREAD

**Issue by moshaad7** [facebookresearch/faiss#3293]
https://github.com/facebookresearch/faiss/blob/e99ad124cbc40c03f72a37032ec25fcabf1479cf/faiss/IndexIVF.cpp#L69-L70

```
void Level1Quantizer::train_q1(
 ...

    quantizer->train(n, x);
    quantizer->verbose = verbose;
}
```

Shouldn't we set `quantizer->verbose = verbose;` before calling train method ?

**Comment by mdouze** [comment]
Yes, ok. You can also set it manually before running the training.
