### ISSUE TITLE
Build from Master Branch Source. FAIL to Install the C++ library and headers.

### ISSUE THREAD

**Issue by Oneiropolo** [facebookresearch/faiss#3298]
# Summary

After invoking cmake & make I tried to build and install c++ library and headers. 
But it fails with the linking error during 'Linking CXX executable TestCodePacking'

There are undefined reference to types of faiss namespace. (Like Below) 
/usr/bin/ld: GpuAutoTune.cpp:(.text+0x8130): undefined reference to `typeinfo for faiss::Index'
/usr/bin/ld: GpuAutoTune.cpp:(.text+0x8194): undefined reference to `typeinfo for faiss::IndexShardsIVF'

# Platform

OS: WSL2 Ubuntu 22.04

Faiss version: Master Branch

Installed from: Build from Source (Master Branch)

Faiss compilation options: with GPU & Intel MKL

Running on:
- [ ] CPU
- [*] GPU

Interface: 
- [*] C++
- [ ] Python

# Reproduction instructions

'make -C build install' 

[ 84%] Building CXX object faiss/gpu/test/CMakeFiles/TestCodePacking.dir/TestCodePacking.cpp.o
[ 84%] Linking CXX executable TestCodePacking
/usr/bin/ld: ../libfaiss_gpu.a(GpuAutoTune.cpp.o): in function `faiss::gpu::GpuParameterSpace::initialize(faiss::Index const*)':
GpuAutoTune.cpp:(.text+0x8129): undefined reference to `typeinfo for faiss::IndexPreTransform'
/usr/bin/ld: GpuAutoTune.cpp:(.text+0x8130): undefined reference to `typeinfo for faiss::Index'
/usr/bin/ld: GpuAutoTune.cpp:(.text+0x8194): undefined reference to `typeinfo for faiss::IndexShardsIVF'
/usr/bin/ld: GpuAutoTune.cpp:(.text+0x819b): undefined reference to `typeinfo for faiss::Index'
/usr/bin/ld: GpuAutoTune.cpp:(.text+0x81d4): undefined reference to `faiss::ParameterSpace::initialize(faiss::Index const*)'
/usr/bin/ld: GpuAutoTune.cpp:(.text+0x81f8): undefined reference to `typeinfo for faiss::Index'
/usr/bin/ld: GpuAutoTune.cpp:(.text+0x826e): undefined reference to `typeinfo for faiss::Index'
/usr/bin/ld: GpuAutoTune.cpp:(.text+0x82e4): undefined reference to `typeinfo for faiss::Index'
/usr/bin/ld: GpuAutoTune.cpp:(.text+0x8344): undefined reference to `faiss::ParameterSpace::add_range(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: GpuAutoTune.cpp:(.text+0x8446): undefined reference to `faiss::ParameterSpace::ParameterSpace()'
/usr/bin/ld: GpuAutoTune.cpp:(.text+0x8460): undefined reference to `faiss::ParameterSpace::initialize(faiss::Index const*)'
/usr/bin/ld: GpuAutoTune.cpp:(.text+0x84e9): undefined reference to `faiss::ParameterSpace::add_range(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: ../libfaiss_gpu.a(GpuAutoTune.cpp.o): in function `faiss::gpu::GpuParameterSpace::set_index_parameter(faiss::Index*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double) const':
GpuAutoTune.cpp:(.text+0x8632): undefined reference to `typeinfo for faiss::Index'

Please help me out.

**Comment by szrr** [comment]
I had the same problem, have you solved it now?

**Comment by Oneiropolo** [comment]
> I had the same problem, have you solved it now?

Yes, I resolved. Must need to build shared Lib.
