### ISSUE TITLE
Missing `faiss-cpu` package for `osx-64` platform

### ISSUE THREAD

**Issue by rafalh** [facebookresearch/faiss#3299]
# Summary

I notices that the latest version of `faiss-cpu` for `osx-64` (x86_64/Intel Mac) platform is `1.7.4` even through the latest version is `1.8.0`. It was removed from Circle CI config in PR #2992. Would you consider bringing the support back?

In my company many people still use Intel Macs so it would be nice to have a bit longer support for this platform.

# Platform

OS: macOS 13

Faiss version: 1.8.0

Installed from: conda

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

```sh
$ conda install pytorch::faiss-cpu=1.8.0

...
PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch::faiss-cpu==1.8.0

...
```

**Comment by mlomeli1** [comment]
hi @rafalh ,@algoriddle can comment more about bringing it back but in the meantime, can you just use 1.7.4?

**Comment by algoriddle** [comment]
CircleCI is pulling support for Intel. This was initially planned for January, and they have pushed it back, but we currently have no plans to re-add.

https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718

**Comment by mdouze** [comment]
And yes some of us also have intel macs :-/

**Comment by rafalh** [comment]
> hi @rafalh ,@algoriddle can comment more about bringing it back but in the meantime, can you just use 1.7.4?

Yes, I could use 1.7.4 or install it through Docker so it's not a blocker for me. I just hoped it would be possible to bring back the support so it's easier to use.

**Comment by mlomeli1** [comment]
@rafalh  please see @algoriddle 's reply to the reason why we stopped supporting intel 
https://github.com/facebookresearch/faiss/issues/3299#issuecomment-2018261838

**Comment by rafalh** [comment]
> @rafalh please see @algoriddle 's reply to the reason why we stopped supporting intel [#3299 (comment)](https://github.com/facebookresearch/faiss/issues/3299#issuecomment-2018261838)

I saw it and I understand the reasoning. Considering they are removing support in June I guess there is not a big benefit to make it work for just 3 moths. Thank you for the explanation. You can close the issue if it's the final answer.
