### ISSUE TITLE
No Derivative license is incompatible with even academic use cases

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [facebookresearch/faiss#33]
Hi, I was interested in using FAISS but the no derivative clause in the license makes it impossible to use, e.g. if I edit the Makefile.inc am I creating a "derivative"?

The creative commons license allows redistribution but no-derivative clause prohibits it if it has been modified. Does that mean I cannot edit the config and then compile-package it in a docker container? 

Also Creative Commons itself discourages its use with software. https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

**Comment by jegou** [comment]
@AKSHAYUBHAT: please see
https://creativecommons.org/licenses/by-nc-nd/4.0/

So, in my understanding, you can modify the library for your research purpose, as long as you do not redistribute the library in a modified form. 
It does not sound very restrictive for research. Nothing prevents you from having a Makefile that you write for your piece of work and linked with Faiss.

**Comment by wickedfoo** [comment]
The license was erroneously listed as the no derivatives version, it has been relaxed to CC-by-NCCreative Commons Attribution-NonCommercial 4.0 (see latest commit).

**Comment by jegou** [comment]
@AKSHAYUBHAT : we just changed the licence to CC-by-NC
See https://creativecommons.org/licenses/by-nc/4.0/legalcode

**Comment by AKSHAYUBHAT** [comment]
Thanks a lot for the quick response ! :)

**Comment by mdouze** [comment]
The license changed to BSD+Patents.
