### ISSUE TITLE
Is the tutorial wrong?

### ISSUE THREAD

**Issue by freezer-glp** [facebookresearch/faiss#330]
In the "Getting started tutorial", section of  [Here](https://github.com/facebookresearch/faiss/wiki/Getting-started-tutorial#results-1) writes: "And within a row, distances are increasing.". 
But the actual search result distance matrix shows:
```
[[ 9900 10500  9309  9831]
 [11055 10895 10812 11321]
 [11353 11103 10164  9787]
 [10571 10664 10632  9638]
 [ 9628  9554 10036  9582]]
```

**Obviously, distances are not increasing within a row**  
Is the tutorial wrong? Or I just misunderstand it? 
Help plz
Thx

**Comment by mdouze** [comment]
Hi 
This is probably a bug, could you give more context (CPU/GPU? which tutorial?). To report bugs: 

https://github.com/facebookresearch/faiss/wiki/Troubleshooting

Thanks!

**Comment by freezer-glp** [comment]
@mdouze 
Hi
The tutorial hyperlink is: 
[https://github.com/facebookresearch/faiss/wiki/Getting-started-tutorial#results-1](https://github.com/facebookresearch/faiss/wiki/Getting-started-tutorial#results-1)

Thanks!

**Comment by mdouze** [comment]
Hi 
This is an index matrix, not a distance matrix.

**Comment by freezer-glp** [comment]
My mistake
Thanks a lot!
