### ISSUE TITLE
Best way to override FINTEGER?

### ISSUE THREAD

**Issue by ChipKerchner** [facebookresearch/faiss#3307]
I'm trying to figure out the best way to override the FINTEGER type in FAISS.

If I define FINTEGER in my flags

```
export CXXFLAGS="-m64 -DFINTEGER=long -fopenmp -I/usr/local/include"
export CFLAGS="-m64 -DFINTEGER=long -fopenmp -I/usr/local/include"
```

I get these at compile time (I'm using a non-x86 system)

```
In file included from <built-in>:622:
<command line>:3:9: warning: 'FINTEGER' macro redefined [-Wmacro-redefined]
    3 | #define FINTEGER long
      |         ^
<command line>:1:9: note: previous definition is here
    1 | #define FINTEGER int
```

My question is my way of overriding FINTEGER the best way or is there another or do changes need to be made to handle this override?  Or is it just a compiler warning?

**Comment by mdouze** [comment]
Are you using the cmake scripts? This seems to indicate that the FINTEGER macro is provided twice.

**Comment by ChipKerchner** [comment]
Yes, I am using the cmake scripts.  That's the issue.  It's defined in cmake and also in my CFLAGS

**Comment by mdouze** [comment]
I'm afraid you will not get away without changing the cmake scripts then...

**Comment by ChipKerchner** [comment]
This is a problem when you compile OpenBLAS with `INTERFACE64=1` to handle 8-byte integers.  I'm not sure how to make the changes.

I'm compiling on PowerPC AIX

**Comment by ChipKerchner** [comment]
Actually if I do this I don't get the messages about FINTEGER being defined more than once.

```
export CXXFLAGS="-m64 -UFINTEGER -DFINTEGER=long -fopenmp -I/usr/local/include"
export CFLAGS="-m64 -UFINTEGER -DFINTEGER=long -fopenmp -I/usr/local/include"
```

**Comment by ChipKerchner** [comment]
https://github.com/facebookresearch/faiss/pull/3322

**Comment by ChipKerchner** [comment]
This can be closed.
