### ISSUE TITLE
Implement reconstruct_n for GPU IVF indexes

### ISSUE THREAD

**Issue by mdouze** [facebookresearch/faiss#3320]
In the current version of Faiss, the reconstruction functions are not imeplemented for GPU IVF indexes because they require to map back from id to entry in the inverted list. 

The exception to this is `reconstruct_n` that just goes over the whole index and keeps ids that are between two bounds. This does not require this mapping. It is useful, in particular, to retrieve the whole dataset or a shard. 

Appropriate test: 

```python
import faiss
import numpy as np



index = faiss.index_factory(4, "IVF10,Flat")
x = np.random.RandomState(123).rand(10, 4).astype('float32')
index.train(x)
index.add(x)
res = faiss.StandardGpuResources()
index2 = faiss.index_cpu_to_gpu(res, 0, index)
recons = index2.reconstruct_n(0, 10)

np.testing.assert_arrays_equal(recons, x)

```

**Comment by junjieqi** [comment]
The change has been merged into master
