### ISSUE TITLE
FAISS.load_local is so slow

### ISSUE THREAD

**Issue by MatteoRiva95** [facebookresearch/faiss#3323]
# Summary

I am trying to run FAISS.load_local after a .save_local on a 60k pdf pickle file in order to not repeat the embedding procedure everytime for a RAG. But it is really slow and I would like to launch all the RAG workflow fastly :( Could it be due to the huge amount of data?

OS: Ubuntu 18.04.6 LTS (Bionic Beaver)

Faiss version: faiss-cpu==1.7.4

Installed from: pip install in conda env

Running on: Cluster with GPU Tesla V100-SXM2-32GB

Interface: Python

# Reproduction instructions

First, I have launched these lines on a py script (ingest.py):

vectorstore = FAISS.from_documents(documents=chunks, embedding=embeddings,)
vectorstore.save_local("./faiss_db")

And then on a different py script (rag.py):

vectorstore = FAISS.load_local("./faiss_db", embeddings, allow_dangerous_deserialization=True)
retriever = vectorstore.as_retriever()

The log file gives me back only this:

"All keys matched successfully"

Can you help me, please?
Thank you in advance!

**Comment by mlomeli1** [comment]
Please direct these questions to the langchain repo, here is the link for your reference:

https://github.com/langchain-ai/langchain
