### ISSUE TITLE
HNSW not support remove_ids? "IDMap2,HNSW32,Flat" also not support remove_ids?

### ISSUE THREAD

**Issue by lgbest123** [facebookresearch/faiss#3339]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
No, HNSW does not support remove_ids. 
It is non-trivial to implement because the graph has to be re-linked after some nodes are removed.
