### ISSUE TITLE
Create mapping between original data and index 

### ISSUE THREAD

**Issue by segalinc** [facebookresearch/faiss#3340]
# Summary

I am trying to understand if there is a way using faiss to create a mapping between the original data (filenames or emebddings list) and the index as a lookup table

**Comment by mdouze** [comment]
This is not supported, see 
https://github.com/facebookresearch/faiss/wiki/FAQ#does-faiss-support-string-ids

**Comment by mdouze** [comment]
If that answers your question, please close the issue.
