### ISSUE TITLE
Fix 4 failing test cases for AIX

### ISSUE THREAD

**Issue by KamathForAIX** [facebookresearch/faiss#3346]
# Summary

# Platform: PowerPC

OS:  AIX

Faiss version:  Master branch

Installed from:  compiled by myself

Faiss compilation options:  Standard instructions using cmake

# Reproduction instructions

Run the test cases in AIX. 4 of them will fail. They are testCppcontribUintreader.Test8bit , testCppcontribUintreader.Test10bit, testCppcontribUintreader.Test12bit and testCppcontribUintreader.Test16bit   

This happened because the Uint8Reader, Uint10Reader, Uint12Reader and Uint16Reader containers are designed for little endian format in faiss/cppcontrib/detail/UintReader.h. 

Handling big endian format has fixed these issues in AIX. Kindly let me know what you think.

**Comment by alexanderguzhva** [comment]
@KamathForAIX I wrote these utilities for x86 needs, indeed. Also, they are not a part of the 'core' Faiss, they belong to optimized vector codecs & decodecs for PQ / IVFPQ part, which is placed in `cppcontrib` directory. So, you may keep it as is, unless you plan to use these related components extensively.
Nevertheless, the code changes are appreciated.
I might update the code if I have some free time.

**Comment by KamathForAIX** [comment]
@alexanderguzhva Thank you for your response. I understand. It will be nice if AIX also passes all test cases, like other platforms. 

Do let me know what you think whenever you are available for the same. Sure, I will wait for your response.

**Comment by mdouze** [comment]
Let's follow up on the PR
