### ISSUE TITLE
Fix two test cases TEST_CPPCONTRIB_SA_DECODE.D64_Residual1x9_PQ8 and TEST_CPPCONTRIB_SA_DECODE.D256_IVF1024_PQ16   for AIX

### ISSUE THREAD

**Issue by KamathForAIX** [facebookresearch/faiss#3352]
# Summary

The two test cases TEST_CPPCONTRIB_SA_DECODE.D256_IVF1024_PQ16   and TEST_CPPCONTRIB_SA_DECODE.D256_IVF1024_PQ16   are failing in AIX due to an endianness issue. 

These two test cases use COARSE BITS = 16 and use unit16_t data type which needs to be aligned correctly to big endian. This issue is similar to #3346 .  

# Platform

OS:  AIX

Faiss version:  Master branch

Installed from:  compiled by yourself

Faiss compilation options:  Standard cmake options

# Reproduction instructions

 

Run ctest after build on any big endian machine. 

I have fixed this issues by making changes in faiss/cppcontrib/sa_decode/Level2-inl.h. Kindly let me know what you think.

**Comment by mdouze** [comment]
follow progress on https://github.com/facebookresearch/faiss/pull/3345
