### ISSUE TITLE
Compiling faiss from source does not get the same performance as pip install faiss-cpu

### ISSUE THREAD

**Issue by xuqianmamba** [facebookresearch/faiss#3356]
# Summary
I've recently been doing ANN testing on faiss for L2 distances, but I've noticed that the faiss packages I'm getting from the two routes are providing different speeds when I run them. Specifically, when using pip install faiss-cpu, querying the msong dataset globally with parameters nlist=999, nprobe=999 (https://www.cse.cuhk.edu.hk/systems/hash/gqr/dataset/msong.tar.gz ) takes as little as 9 seconds, but such a query is 30 seconds when I compile it myself via source code, and I specify the following parameters according to install.md during cmake:

cmake -B build . \      
      -DFAISS_ENABLE_GPU=OFF \
      -DFAISS_ENABLE_PYTHON=ON \
      -DFAISS_ENABLE_C_API=ON \
      -DBUILD_SHARED_LIBS=ON \
      -DCMAKE_BUILD_TYPE=Release \
      -DBLA_VENDOR=Intel10_64lp \
      -DCMAKE_CXX_FLAGS=-march=native -Wno-dev

And no matter I specify set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3") or not in CmakeLists, it doesn't solve the problem, and I want to know if I need to change another parameter to get faster query speed.

Also, I would like to ask if faiss kind of uses this calculation for L2 distance calculation? Since IntelMKL can't calculate L2 distance directly.

(a-b)²=a²+b²-2ab

Have you optimized this calculation? Thank you!

Faiss version: <1.8.0>

Installed from: <pip and source code> 

Faiss compilation options: 
cmake -B build . \      
      -DFAISS_ENABLE_GPU=OFF \
      -DFAISS_ENABLE_PYTHON=ON \
      -DFAISS_ENABLE_C_API=ON \
      -DBUILD_SHARED_LIBS=ON \
      -DCMAKE_BUILD_TYPE=Release \
      -DBLA_VENDOR=Intel10_64lp \
      -DCMAKE_CXX_FLAGS=-march=native -Wno-dev

Running on:
- [*] CPU
- [ ] GPU

Interface: 
- [*] C++
- [*] Python

**Comment by alexanderguzhva** [comment]
@xuqianmamba It seems that you did not enable vectorization (AVX2 / AVX512), use `-DFAISS_OPT_LEVEL` cmake parameter. More information is in `INSTALL.md` file.

**Comment by mdouze** [comment]
please close issue if this fixes it.
