### ISSUE TITLE
RuntimeError: Error in virtual void __cdecl faiss::Index::add_with_ids

### ISSUE THREAD

**Issue by ybshaw** [facebookresearch/faiss#3358]
# Summary
when I use IndexFlatL2 to build faiss, some images have successfully build index, however, when load other image to index, I found some error as following:
`RuntimeError: Error in virtual void __cdecl faiss::Index::add_with_ids(idx_t, const float *, const idx_t *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\Index.cpp:45: add_with_ids not implemented for this type of index`

# Platform
CPU + win10 + faiss-cpu==1.8.0

# My Code
```python
index = faiss.IndexFlatL2(128)
index = faiss.IndexIDMap(index)
 
# build index fisrtly
index.add_with_ids(image_vectors, image_ids)

# update index

index.add_with_ids(image_vectors_new, image_ids_new)	# Error Occured

```

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
Could you post a self-contained reproduction for this?

**Comment by ybshaw** [comment]
> Could you post a self-contained reproduction for this?

I'm sorry, I found some bug in my code and fixed it by google, thankyou
