### ISSUE TITLE
Binary embeddings score normalization

### ISSUE THREAD

**Issue by Cognitus-Stuti** [facebookresearch/faiss#3370]
# Summary

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [- ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [- ] Python

# Reproduction instructions

 

I need help normalizing scores from int8/ubinary embeddings

**Comment by mlomeli1** [comment]
hi @Cognitus-Stuti , please see https://github.com/facebookresearch/faiss/wiki/MetricType-and-distances#how-can-i-index-vectors-for-cosine-similarity
