### ISSUE TITLE
use IndexIVFFlat add_with_ids can't get result

### ISSUE THREAD

**Issue by duothink** [facebookresearch/faiss#338]
i gener a vector with 600*1 size, call add_with_ids index it ,but don't get right result
can someone help me?

all code as follow:

```
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD+Patents license found in the
 * LICENSE file in the root directory of this source tree.
 */

#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <random>
#include <vector>

#include <faiss/IndexFlat.h>
#include <faiss/IndexIVF.h>

using namespace std;

template <typename T>
int gen_random_numbers(T floor, T ceilling, T out[], int len) {
	std::random_device rd;
	std::mt19937 gen(rd());
	std::uniform_real_distribution<T> dis(floor, ceilling);
	for (int i = 0; i < len; ++i) {
		out[i] = dis(gen);
	}
	return 0;
}
auto pFunction = [](float* p, int len) {
	for (int i = 0; i < len; i++) {
		printf("%.4f ", p[i]);
	}
	printf("\n");
};
int main() {
	int d = 600;                            // dimension
	int nb = 1;                       // database size
	int nq = 1;                        // nb of queries
	float *xb = new float[d * nb];
	float *xq = new float[d * nq];
	for (int i = 0; i < nb; i++) {
		gen_random_numbers<float>(-1.0, 1.0, xb + i*d, d);
	}
	for (int i = 0; i < nq; i++) {
		for (int j = 0; j < d; j++)
			xq[d * i + j] = xb[d*i + j];
		pFunction(xq + i*d, 10);
	}
	int nlist = 1;
	int k = 2;
	faiss::IndexFlatL2 quantizer(d);       // the other index
	faiss::IndexIVFFlat index(&quantizer, d, nlist, faiss::METRIC_INNER_PRODUCT);
	long label = 60000000;
	index.train(nb, xb);
	vector<long> ids;
	for (int i = 0; i < nb; i++) {
		ids.push_back(label);
		label += 1;
	}
	index.add_with_ids(nb, xb, ids.data());
	{       // search xq
		long *I = new long[k * nq];
		float *D = new float[k * nq];
		index.search(nq, xq, k, D, I);
		printf("I=\n");
		for (int i = 0; i < nq; i++) {
			for (int j = 0; j < k; j++)
				printf("label=%5ld  distance=%.6f\n", I[i * k + j], D[i*k + j]);
			printf("\n");
		}
		delete[] I;
		delete[] D;
	}
	delete[] xb;
	delete[] xq;
	return 0;
}
```

**Comment by mdouze** [comment]
Hi 
This is due to an inconsistency in the training when nlist == nb of training images. I will fix it. In the meantime, you can just do 

quantizer.add(nb, xb);

after building the quantizer object.

**Comment by mdouze** [comment]
Should be fixed in the latest version of Faiss. Please re-open if it still does not work.

**Comment by duothink** [comment]
Thank you very much for your reply. I'll keep an eye on this bug.

**Comment by duothink** [comment]
@mdouze Thank you very much for your reply. I'll keep an eye on this bug.

**Comment by definesun** [comment]
`const int dim = 4;

int main ()
{

    double t0 = elapsed();

    // dimension of the vectors to index
    int d = dim;

    // size of the database we plan to index
    size_t nb = 5;

    // make a set of nt training vectors in the unit cube
    // (could be the database)
    size_t nt = 100;

    size_t nlist = 1;

    // make the index object and train it
    faiss::IndexFlatIP coarse_quantizer (d);

    faiss::IndexIVFFlat index = faiss::IndexIVFFlat(
        &coarse_quantizer, d, nlist, faiss::METRIC_INNER_PRODUCT);

    { // training
        printf ("[%.3f s] Generating %ld vectors in %dD for training\n",
                elapsed() - t0, nt, d);

        std::vector <float> trainvecs (nt * d);
        for (size_t i = 0; i < nt * d; i++) {
            trainvecs[i] = drand48();
        }

        printf ("[%.3f s] Training the index\n",
                elapsed() - t0);
        index.verbose = true;

        index.train (nt, trainvecs.data());
    }

    { // I/O demo
        const char *outfilename = "/tmp/index_trained.faissindex";
        printf ("[%.3f s] storing the pre-trained index to %s\n",
                elapsed() - t0, outfilename);

        write_index (&index, outfilename);
    }

    size_t nq;
    float que[dim] = {0.12, 0.32, 0.33, -0.12};
    std::vector<float> queries(que, que+dim);
    nq = 1;

    { // populating the database
        printf ("[%.3f s] Building a dataset of %ld vectors to index\n",
                elapsed() - t0, nb);

        std::vector <float> database (nb * d);
        for (size_t i = 0; i < nb * d; i++) {
            database[i] = i/(nb * d-1.0);
        }
        std::vector<long> xids(nb);
        xids.push_back(1354777239);
        xids.push_back(1982282553);
        xids.push_back(1486633334);
        xids.push_back(644481400);
        xids.push_back(644481302);
        printf ("[%.3f s] Adding the vectors to the index\n",
                elapsed() - t0);

        //index.add (nb, database.data());
        index.add_with_ids(nb, database.data(), xids.data());

        printf ("[%.3f s] imbalance factor: %g, ntotal=%ld\n",
                elapsed() - t0, index.imbalance_factor (), index.ntotal);

        const faiss::Index::idx_t *pt = index.invlists->get_ids(nlist-1);
        for (size_t i = 0; i < index.invlists->list_size(nlist-1); ++ i)
        {
            printf ("%ld ", pt[i]);
        }
        printf ("\n");
    }

    { // searching the database
        int k = 3;
        printf ("[%.3f s] Searching the %d nearest neighbors "
                "of %ld vectors in the index\n",
                elapsed() - t0, k, nq);

        std::vector<faiss::Index::idx_t> nns (k * nq);
        std::vector<float>               dis (k * nq);

        index.search (nq, queries.data(), k, dis.data(), nns.data());

        printf ("[%.3f s] Query results (vector ids, then distances):\n",
                elapsed() - t0);

        for (int i = 0; i < nq; i++) {
            printf ("query %2d: ", i);
            for (int j = 0; j < k; j++) {
                printf ("%7ld ", nns[j + i * k]);
            }
            printf ("\n     dis: ");
            for (int j = 0; j < k; j++) {
                printf ("%7g ", dis[j + i * k]);
            }
            printf ("\n");
        }
    }`

I met the same question with the newest version, ask for helper,thanks

**Comment by lijia168** [comment]
@definesun   try this 
xids[0] = 1354777239;
xids[1] = 1982282553;
xids[2] = 1486633334;
xids[3] = 644481400;
xids[4] = 644481302;
