### ISSUE TITLE
Segfault error on faiss.IndexIVFFlat().train

### ISSUE THREAD

**Issue by mkandrewhuang301** [facebookresearch/faiss#3380]
# Summary

when I run #FAISS
    num_vectors,  feat_dim = clip_embeds.shape
    quantize = faiss.IndexFlatIP(feat_dim)
    ivf_index = faiss.IndexIVFFlat(quantize,  feat_dim,int(sqrt(num_vectors)),)
    ivf_index.train(clip_embeds)
    ivf_index.add(clip_embeds)
    FAISS_index = {
        "video_ids": clip_paths,
        "clip_embeds": ivf_index,
    }
    given video embeddings from clip_embeds, why does my compter crash when it runs the ivf_index.train line

# Platform

OS: macOS m1

Faiss version: 

Installed from: pip install faiss-cpu

Faiss compilation options: 

Running on:
**- [ ] CPU**
- [ ] GPU

Interface: 
- [ ] C++
**- [ ] Python**

# Reproduction instructions
pip install faiss-cpu
generate vector embeddings
run code for faiss index building

**Comment by mdouze** [comment]
This should work. 
Please install Faiss with conda, pip is known to cause problems especially on macs.
