### ISSUE TITLE
[Feature Request] GPU indices Provide Interface to Access Resource

### ISSUE THREAD

**Issue by tarang-jain** [facebookresearch/faiss#3425]
# Summary

It would be great if GPU index (`GpuIndex.h`) objects can provide an interface to the underlying memory resource (either through a helper or by making it a public member of the class). That would allow a user to update the stream on the resource. Currently the index is tied to a particular stream. But it is possible that a user wants to build an index with operations ordered on one stream, but search using another stream after the index is built. This utility is also essential for our multi-threaded benchmarks in RAFT.

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [x] C++
- [ ] Python

**Comment by mdouze** [comment]
There seems to be a getter already, see 
https://github.com/facebookresearch/faiss/blob/main/faiss/gpu/GpuIndex.h#L66
isn't that what you need?

**Comment by tarang-jain** [comment]
Thanks! That is what I was looking for. Closing the issue.
