### ISSUE TITLE
is there a plan support integer (INT8) matrix multiplication

### ISSUE THREAD

**Issue by RobitYadda** [facebookresearch/faiss#346]
# is there a plan support integer (INT8) matrix multiplication?
cuda and cublas support integer (INT8) matrix multiplication,I see faiss support fp16,is there a plan support int8? 

Running on :
- [ x] CPU
- [ √] GPU

**Comment by mdouze** [comment]
Hi, 
No we do not plan to support int8 data directly on GPU.

**Comment by RobitYadda** [comment]
Thx! 
Could you explain why?

**Comment by mdouze** [comment]
We do not plan to extend the GPU functionality it for the coming months. 
We welcome pull requests if you want to contribute.

**Comment by ctwd-0** [comment]
what about now

**Comment by kairos03** [comment]
what about now?

**Comment by mdouze** [comment]
For what type of index should it be supported?
