### ISSUE TITLE
The IVFPQ index has inconsistent memory usage when performing search operations.

### ISSUE THREAD

**Issue by Xiongyou-Peng** [facebookresearch/faiss#3496]
# Summary

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [yes ] CPU
- [ ] GPU

Interface: 
- [ yes] C++
- [ ] Python

**Comment by mlomeli1** [comment]
it's hard to say anything about this issue without a reproducible example.

**Comment by Xiongyou-Peng** [comment]
The content of "reproducible steps" was lost for some reason.
There was something wrong with my python test code. I did the test by c++ again, the problem didn't come up.
I'm sorry for my lack of preciseness.
