### ISSUE TITLE
How can I use faiss for faces clustering?

### ISSUE THREAD

**Issue by apollo-time** [facebookresearch/faiss#35]
Hi, I tested faiss to search face in big faces set and got very good result.
A face feature is 128 dim vector and distance use L2 norm.
But I don't know how to clustering faces into similar faces when I don't know cluster count.
More ever the faces set may be grown.
I can set similarity threshold.
Please teach me good clustering method or algorithm.

**Comment by mdouze** [comment]
Hi, 
We have no strong expertise on estimating the number of clusters. Please do some literature review.

**Comment by haggenmatt** [comment]
@apollo-time I wonder if you have managed to make this working and mind if you can share some code on how to glue all of this (DLib 128 face vector plus Faiss insertion/lookup).
