### ISSUE TITLE
Typo in Wiki

### ISSUE THREAD

**Issue by matsui528** [facebookresearch/faiss#350]
In the following page of the wiki, should `index.polysemous_ordering = true` be `index.do_polysemous_training = True`?
https://github.com/facebookresearch/faiss/wiki/Faiss-indexes-(composite)#pre-filtering-pq-codes-with-polysemous-codes

**Comment by mdouze** [comment]
Hi 
That piece of code is in C++, so it is true. 
It would be True in Python.

**Comment by matsui528** [comment]
Hi @mdouze,
Is the name of the variable `index.polysemous_ordering` correct? I cannot find it in IndexIVFPQ.h, and it seems polysemous codes cannot be correctly trained with the flag `index.polysemous_ordering` (Sorry for the confusion, the capital letter of `true` is not my main question)

**Comment by mdouze** [comment]
For `IndexIVFPQ` the correct flag is `do_polysemous_training` to do the training and the filtering is applied if `polysemous_ht` is not 0. I will fix the wiki.

**Comment by matsui528** [comment]
Thank you!
