### ISSUE TITLE
error: ‘nullptr’ was not declared in this scope

### ISSUE THREAD

**Issue by hipitt** [facebookresearch/faiss#352]
# Summary

**New clone, compilation failed.**

# Platform

OS: centos 7.3 1611

Faiss version:commit a280791c83396e5e10d38aaabdae35efcedcea11 (HEAD -> master, origin/master, origin/HEAD)

Faiss compilation options: use example_makefiles/makefile.inc.Linux

Running on :
- [ v] CPU
- [ ] GPU

# Reproduction instructions
**step:**
git clone ....
cp example_makefiles/makefile.inc.Linux makefile.inc
make

g++ -o demos/demo_ivfpq_indexing -fPIC -m64 -Wall -g -O3 -mavx -msse4 -mpopcnt -fopenmp -Wno-sign-compare -fopenmp demos/demo_ivfpq_indexing.cpp libfaiss.a -g -fPIC  -fopenmp /usr/lib64/libopenblas.so.0
In file included from demos/../IndexIVF.h:21:0,
                 from demos/../IndexIVFPQ.h:18,
                 from demos/demo_ivfpq_indexing.cpp:19:
demos/../Heap.h:190:9: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
         const typename C::T * x = nullptr,
         ^
demos/../Heap.h:190:35: error: ‘nullptr’ was not declared in this scope
         const typename C::T * x = nullptr,
                                   ^
demos/../Heap.h:191:38: error: ‘nullptr’ was not declared in this scope
         const typename C::TI * ids = nullptr,
                                      ^
demos/../Heap.h:215:23: error: ‘nullptr’ was not declared in this scope
         const T * x = nullptr,
                       ^
demos/../Heap.h:216:28: error: ‘nullptr’ was not declared in this scope
         const long * ids = nullptr,
                            ^
demos/../Heap.h:228:24: error: ‘nullptr’ was not declared in this scope
          const T * x = nullptr,
                        ^
demos/../Heap.h:229:29: error: ‘nullptr’ was not declared in this scope
          const long * ids = nullptr,
                             ^
demos/../Heap.h:385:52: error: ‘nullptr’ was not declared in this scope
         size_t nj, const T *vin, const TI *id_in = nullptr,
                                                    ^
In file included from demos/../IndexIVFPQ.h:18:0,
                 from demos/demo_ivfpq_indexing.cpp:19:
demos/../IndexIVF.h:82:19: error: ‘uint8_t’ does not name a type
     virtual const uint8_t * get_codes (size_t list_no) const = 0;
                   ^
demos/../IndexIVF.h:91:19: error: ‘uint8_t’ does not name a type
     virtual const uint8_t * get_single_code (
                   ^
demos/../IndexIVF.h:103:37: error: ‘uint8_t’ does not name a type
                               const uint8_t *code);
                                     ^
demos/../IndexIVF.h:103:46: error: ISO C++ forbids declaration of ‘code’ with no type [-fpermissive]
                               const uint8_t *code);
                                              ^
demos/../IndexIVF.h:107:36: error: ‘uint8_t’ does not name a type
            const idx_t* ids, const uint8_t *code) = 0;
                                    ^
demos/../IndexIVF.h:107:45: error: ISO C++ forbids declaration of ‘code’ with no type [-fpermissive]
            const idx_t* ids, const uint8_t *code) = 0;
                                             ^
demos/../IndexIVF.h:110:48: error: ‘uint8_t’ does not name a type
                                idx_t id, const uint8_t *code);
                                                ^
demos/../IndexIVF.h:110:57: error: ISO C++ forbids declaration of ‘code’ with no type [-fpermissive]
                                idx_t id, const uint8_t *code);
                                                         ^
demos/../IndexIVF.h:113:58: error: ‘uint8_t’ does not name a type
                                  const idx_t *ids, const uint8_t *code) = 0;
                                                          ^
demos/../IndexIVF.h:113:67: error: ISO C++ forbids declaration of ‘code’ with no type [-fpermissive]
                                  const idx_t *ids, const uint8_t *code) = 0;
                                                                   ^
demos/../IndexIVF.h:124:31: error: ‘uint8_t’ was not declared in this scope
     std::vector < std::vector<uint8_t> > codes; // binary codes, size nlist
                               ^
demos/../IndexIVF.h:124:38: error: template argument 1 is invalid
     std::vector < std::vector<uint8_t> > codes; // binary codes, size nlist
                                      ^
demos/../IndexIVF.h:124:38: error: template argument 2 is invalid
demos/../IndexIVF.h:124:40: error: template argument 1 is invalid
     std::vector < std::vector<uint8_t> > codes; // binary codes, size nlist
                                        ^
demos/../IndexIVF.h:124:40: error: template argument 2 is invalid
demos/../IndexIVF.h:129:38: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [enabled by default]
     size_t list_size(size_t list_no) const override;
                                      ^
demos/../IndexIVF.h:130:11: error: ‘uint8_t’ does not name a type
     const uint8_t * get_codes (size_t list_no) const override;
           ^
demos/../IndexIVF.h:131:44: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [enabled by default]
     const idx_t * get_ids (size_t list_no) const override;
                                            ^
demos/../IndexIVF.h:135:36: error: ‘uint8_t’ does not name a type
            const idx_t* ids, const uint8_t *code) override;
                                    ^
demos/../IndexIVF.h:135:45: error: ISO C++ forbids declaration of ‘code’ with no type [-fpermissive]
            const idx_t* ids, const uint8_t *code) override;
                                             ^
demos/../IndexIVF.h:135:49: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [enabled by default]
            const idx_t* ids, const uint8_t *code) override;
                                                 ^
demos/../IndexIVF.h:138:50: error: ‘uint8_t’ does not name a type
                          const idx_t *ids, const uint8_t *code) override;
                                                  ^
demos/../IndexIVF.h:138:59: error: ISO C++ forbids declaration of ‘code’ with no type [-fpermissive]
                          const idx_t *ids, const uint8_t *code) override

。。。。。。。。。。。。。。。。。
make: *** [demos/demo_ivfpq_indexing] Error 1

**Comment by ctongfei** [comment]
I had the same problem. Fixed it by adding `-std=c++11` to the `Makefile`:
```
demos/demo_ivfpq_indexing: demos/demo_ivfpq_indexing.cpp $(LIBNAME).a
        $(CXX) -std=c++11 -o $@ $(CFLAGS) $< $(LIBNAME).a $(LDFLAGS) $(BLASLDFLAGS)

demos/demo_sift1M: demos/demo_sift1M.cpp $(LIBNAME).a
        $(CXX) -std=c++11 -o $@ $(CFLAGS) $< $(LIBNAME).a $(LDFLAGS) $(BLASLDFLAGS)
```

**Comment by mixxen** [comment]
```$(CFLAGS)``` should be replaced with ```$(CXXFLAGS)```  in ```Makefile``` where ```$(CXX)``` is the compiler

**Comment by mdouze** [comment]
Hi 
Since the integration of the C interface, the Makefile macros changed. Will fix this.

**Comment by mdouze** [comment]
Should be fixed now.

**Comment by hipitt** [comment]
Thanks  all.
