### ISSUE TITLE
faiss + torch.dist: unable to utilize multiple GPU

### ISSUE THREAD

**Issue by ZexinYan** [facebookresearch/faiss#3530]
# Summary

# Platform

OS: ubuntu 22.04

Faiss version: e758973fa08164728eb9e136631fe6c57d7edf6c

Installed from: miniconda

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

I follow the instructions [(Faiss + PyTorch: interoperability for CPU and GPU)](https://www.facebook.com/groups/faissusers/posts/1025663204524632/?_rdr), but I found that it can't utilize multiple gpu based on torch.dist.
I feel like the reason is current implementation will change all cuda tensor to torch.current_device(by default as 0), ([torch_utils](https://github.com/facebookresearch/faiss/blob/main/contrib/torch_utils.py#L85C1-L86C1)).
Is there any solutions to fix this?

**Comment by mdouze** [comment]
Are you running with one thread per GPU or one process per GPU? I don't know if `torch.cuda.current_device()` is thread-specific.

**Comment by ZexinYan** [comment]
> Are you running with one thread per GPU or one process per GPU? I don't know if `torch.cuda.current_device()` is thread-specific.

One process per GPU by using [torch.distributed](https://pytorch.org/docs/stable/distributed.html#).

**Comment by mdouze** [comment]
In that case you can just define the process' GPU as current device no?

**Comment by ZexinYan** [comment]
Did you think `torchx.distributed.local_rank()`(automatically assigned when using torch.distributed) is better than `torch.cuda.current_device()`(manually setting)?
