### ISSUE TITLE
How to tune recall vs search time?

### ISSUE THREAD

**Issue by burk** [facebookresearch/faiss#355]
How are the graphs produced in [the 1M benchmark](https://github.com/facebookresearch/faiss/wiki/Indexing-1M-vectors)? In other words, what makes the different methods give lines and not just points? Is that the [autotuning](https://github.com/facebookresearch/faiss/wiki/High-level-interface-and-auto-tuning)? (I'm trying to tune for high recall, but so far I've only been changing the IVF parameter).

If yes, is it possible to auto-tune through the Python API?

**Comment by mdouze** [comment]
Hi 
Here is a demo for auto-tuning: https://github.com/facebookresearch/faiss/blob/master/demos/demo_auto_tune.py

**Comment by burk** [comment]
Thanks! Should have seen that. I'd suggest putting a mention of autotuning on the 1M benchmark wiki page.
