### ISSUE TITLE
Cmake build scripts?

### ISSUE THREAD

**Issue by Yangqing** [facebookresearch/faiss#36]
While the current Makefile solution is very nice to tinker with and easy to debug, it might be beneficial if we have a parallel cmake solution - that could potentially benefit a bunch of software packages that uses CMake and wants to depend on faiss.

(chatted with @mdouze offline and maybe this is something that the community can collectively maintain? :) )

**Comment by hlzz** [comment]
@Yangqing submitted a pull request of cmake build. see https://github.com/facebookresearch/faiss/pull/75

**Comment by mdouze** [comment]
Partial support for cmake is in PR #75. Closing issue.
