### ISSUE TITLE
The end of free usage for Anaconda

### ISSUE THREAD

**Issue by matsui528** [facebookresearch/faiss#3612]
# Summary

Dear Faiss team and community,

I am posting this issue to seek opinions from the Faiss community.

In March 2024, [Anaconda's terms of service were updated](https://legal.anaconda.com/policies/), making it difficult for even universities to use the conda package of Faiss for free.

Therefore, I would like to ask the Faiss community: What approaches are you considering to use Faiss?

- Building from the source
    - This is hard. We would like to avoid it if possible.
- Using the pip package of Faiss
    - [faiss-wheels](https://github.com/kyamagu/faiss-wheels) is a well-maintained pip package, but it is unofficial.
- Using miniconda and [conda-forge package of Faiss](https://anaconda.org/conda-forge/faiss)
    - I am not sure whether this is free of charge. Can anyone clarify?
    - There are differences between the conda-forge's and the official conda's package. For example, at this moment, version 1.8.0 is available for the official conda, but only 1.7.4 is available for the conda-forge.
- Using Faiss only in GitHub actions and GitHub codespaces
    - I've heard that [we can use conda inside GitHub actions and GitHub codespaces](https://www.anaconda.com/partners/azure) for free. Does someone know the details of this?
- Using the paid version of Anaconda
    - 🤔 
- Are there any other options?

Best,
Yusuke

# Platform

Installed from: anaconda

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [x] C++
- [x] Python

**Comment by ramilbakhshyiev** [comment]
@matsui528 Are there any issues you are currently experiencing or expecting? According to Anaconda T&C, FAISS qualifies for free tier and we have been ok so far after they started rate-limiting (there was a 24-hour period where we hit rate limits but it was a CDN issue on Anaconda side apparently and it was resolved by the team). Putting this on auto-close.

**Comment by matsui528** [comment]
@ramilbakhshyiev My concern is more about legal issues. If I understand correctly, starting from March 2024, usual users have been required to pay to use the default channel of Anaconda [1, 2]. It seems difficult to install faiss via conda (`conda install -c pytorch faiss-cpu`) without using the default channel. Therefore, I guess installing faiss via conda for free is no longer possible. (Please correct me if I'm wrong...)

[1] https://www.anaconda.com/blog/is-conda-free#summarize
[2] There is no need to pay if the user's organization has less than 200 employees.

I'm currently dealing with the following issue: I have been using faiss daily for my research projects. Typically, I would install faiss for free using conda. However, I am now hesitant to run `conda install -c pytorch faiss-cpu` because it will utilize the default conda channel, potentially resulting in my university having to pay money to Anaconda Inc.

**Comment by ramilbakhshyiev** [comment]
@matsui528 To confirm: you are worried about the consumption of faiss from conda defaults channel; not about the repo being able to publish to conda.

Assuming that, section 2.1 of the T&C is not very clear, it mentions that educational entities are exempt but it does not explicitly cover research activities. Since we have not heard this broadly reported or raised as a concern, would you please check with Anaconda to clarify? Meanwhile, I will bring this up to team's attention that installing through pip might be more important now with Conda going paid.
