### ISSUE TITLE
Outdated version "faiss-gpu" on Pypi

### ISSUE THREAD

**Issue by moria97** [facebookresearch/faiss#3617]
# Summary

The `faiss-gpu` package is outdated on pypi and supports python <= 3.10 only. Can you help upgrade it to newest release?

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by asadoughi** [comment]
faiss-gpu is not supported by us. See https://github.com/kyamagu/faiss-wheels https://pypi.org/project/faiss-gpu/
