### ISSUE TITLE
confused with  IVFFlat's  accuracy 

### ISSUE THREAD

**Issue by yongjunjian** [facebookresearch/faiss#362]
# Summary

# Platform

OS: ubuntu 16.4

Faiss version: 4d440b6698fcc7b08607534bc622902b52bf9c49

Faiss compilation options: default

Running on :
- [  ] CPU
- [ ] GPU

# Reproduction instructions
I use the demo demo/demo_sift1M to test accuracy for different indexes， found that the accuracy of 'IVF4096,Flat'  is lower than  any other IVF index.this is the result:
IVF4096,Flat
R@1 = 0.5610
R@10 = 0.5636
R@100 = 0.5636

IVF4096,PQ8+16
R@1 = 0.5327
R@10 = 0.7983
R@100 = 0.8028

IVF4096,PQ32
R@1 = 0.5700
R@10 = 0.8869
R@100 = 0.8940
 
According to the comment, 'IVF4096,Flat'  Index stores the raw vector ,so it should has the highest accuray compared to other IVF index.
the comment is :

21 /** Inverted file with stored vectors. Here the inverted file
 22  * pre-selects the vectors to be searched, but they are not otherwise
 23  * encoded, the code array just contains the raw float entries.
 24  */
 25 struct IndexIVFFlat: IndexIVF {

so I'm confused! Maybe there is som misunderstanding. Could anyone explain it for me?

**Comment by yongjunjian** [comment]
maybe I found out the reason . I found that autotuning set the nprobe to be a small num(2) .when  I set nprobe to be 128, the accuracy is up to 99%, but cost more time.

**Comment by mdouze** [comment]
Hi 
You probably found the explanation. The accuracy is better for IVFFlat but for the same set of parameters.
