### ISSUE TITLE
Index factory doesn't support nbits for LSH

### ISSUE THREAD

**Issue by irowberryFS** [facebookresearch/faiss#3629]
# Summary

The index factory doesn't support setting  `nbits` for the LSH index.

# Platform

Faiss version: 1.8.0

Installed from: conda

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

Attempt to set `nbits` in some way for LSH index using `index_factory()`

`index = faiss.index_factory(128, 'LSH16rt')`
Returns the following error.
`faiss/index_factory.cpp:880: could not parse index string LSHrt_16`

Expecting behavior to something like this. 
`index = faiss.IndexLSH(128, nbits)`

**Comment by ramilbakhshyiev** [comment]
Thanks for reporting this. Confirmed. `IndexLSH` [takes](https://github.com/facebookresearch/faiss/blob/dd72e4121dc6684c6fbf289949ba4526a54d9f3b/faiss/IndexLSH.cpp#L26) dimension and nbits separately while `index_factory` does not allow for [nbits to be set](https://github.com/facebookresearch/faiss/blob/dd72e4121dc6684c6fbf289949ba4526a54d9f3b/faiss/index_factory.cpp#L533) and uses [d as nbits](https://github.com/facebookresearch/faiss/blob/dd72e4121dc6684c6fbf289949ba4526a54d9f3b/faiss/index_factory.cpp#L537).

Additional steps to repro:
```
import faiss
index = faiss.index_factory(128, "LSHrt")
print("d: %s, nbits: %s" % (index.d, index.nbits))
# outputs: d: 128, nbits: 128
```

```
import faiss
index = faiss.IndexLSH(128, 16)
print("d: %s, nbits: %s" % (index.d, index.nbits))
# outputs: d: 128, nbits: 16
```

**Comment by mdouze** [comment]
I would not label this as a bug. Most use cases of LSH do not need the dimension to be specified as a pre-transform reduces to the proper dimension and the LSH object just converts to binary. See eg. 
https://github.com/facebookresearch/faiss/wiki/Vector-codec-benchmarks#sift1m

**Comment by asadoughi** [comment]
Merged with https://github.com/facebookresearch/faiss/pull/3679
