### ISSUE TITLE
Filtration on the basis of two keys in metadata in fiass

### ISSUE THREAD

**Issue by divrajput** [facebookresearch/faiss#3634]
I am trying to apply a filter on the database according to metadata. The filter works perfectly in chromadb, but it returns an empty list in faiss.
```
def get_metadata_condition(metadata_cond):
    filtered_metadatas = {k: v for k, v in metadata_cond.items() if v is not None}
    if len(filtered_metadatas) == 1:
        cond = filtered_metadatas
    else:
        lst = [{k: v} for k, v in filtered_metadatas.items()]
        cond = {"$and": lst} if lst else None
    return cond
metadata_cond = {'character_chunk_id': 0, 'character_chunks_tokens': None, 'page_number': 1, 'type': None}

cond = get_metadata_condition(metadata_cond)
cond
```

Output:
`{'$and':` [{'character_chunk_id': 0}, {'page_number': `1}]}`
This condition works in chromadb perfectly. However, when using it with faiss, it gives an empty list.

```
retriever = db.as_retriever(search_kwargs={'k': 2, 'filter': cond})
retriever.invoke("What role does fibre play in digestion? Name five fibre containing foods.")
```

**Comment by mnorris11** [comment]
Hi, can you post a minimal repro? I was not sure which part of this is calling FAISS. I don't see an `as_retriever` call in the codebase.

**Comment by asadoughi** [comment]
Filtering in FAISS can be accomplished via the IDSelector-based classes as demonstrated in this unit test here: https://github.com/facebookresearch/faiss/blob/main/tests/test_search_params.py#L25
