### ISSUE TITLE
Can FAISS index be integrated with a vector database?

### ISSUE THREAD

**Issue by blacksmithop** [facebookresearch/faiss#3648]
# Summary

I understand that what FAISS offers an index which can be stored and loaded. I would like to know if this can be integrated with any of the vector databases out there.
 Perhaps such a thing is not currently possible, I would also appreciate it if someone could point me towards a databases that uses a similar indexing algorithm.

# Platform

OS: 

Faiss version: faiss-cpu 1.8.0.post1

Installed from: pypi

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by ramilbakhshyiev** [comment]
Hi @blacksmithop, it is a very broad question but a general answer is yes, it is possible. There many databases implemented with FAISS, Milvus and OpenSearch are some good examples. Moving this to a discussion and closing. Please let me know if you have any additional questions.
