### ISSUE TITLE
Unable to train a PCA transform from 1024 dimensions

### ISSUE THREAD

**Issue by burk** [facebookresearch/faiss#365]
# Summary

Unable to train a PCA transform from 1024 dimensions down to x (somewhere in 10 to 1024 dims).

# Platform

OS: Ubuntu 16.04.3 LTS

Faiss version: 8428f915484eff3f1e7ff4788494c2fcf403f1b0

Faiss compilation options: OpenBLAS and default options.

Running on :
- [x] CPU
- [ ] GPU

# Reproduction instructions

I'm benchmarking some different Faiss index types for our use case. I'm pretty sure I was at some point able to use the `PCARx,...,SQ8` index on our 1024D vectors, but now it consistently fails with

    WARN ssyev info returns 1023, a very bad PCA matrix is learnt

Even this simple test fails with the same error (and prints a lot of `nan`):

    mt = np.random.rand(10000, 1024).astype('float32')
    mat = faiss.PCAMatrix (1024, 100)
    mat.train(mt)
    assert mat.is_trained
    tr = mat.apply_py(mt)
    # print this to show that the magnitude of tr's columns is decreasing
    print((tr ** 2).sum(0))

I've tried different sizes for the training set, and also different dimensions for the result of the transform. Am I completely mis-using the PCA transform? Or is the random data just to high-dimensional? It works for fewer dimensions. I realize the OPQ transform + PQ compression might work better for my vectors, but I wanted to try some different options.

**Comment by mdouze** [comment]
Hi 
I cannot repro the issue 
```
import numpy as np
import faiss
mt = np.random.rand(10000, 1024).astype('float32')
mat = faiss.PCAMatrix (1024, 100)
mat.train(mt)
tr = mat.apply_py(mt)
np.any(np.isnan(tr))
```
It may be a problem with the BLAS/Lapack implementation you are using. Which one is it?

**Comment by burk** [comment]
Thanks for trying! I cannot even reproduce it myself anymore. I was running Openblas from the Ubuntu apt repo, version 0.2.18-1ubuntu1.

I'll re-open if I'm able to reproduce..

**Comment by neouyghur** [comment]
@mdouze @burk I also faced the same problem. It is cuased by the data type. After changing the data type to np.float32, the problem is solved.

**Comment by neouyghur** [comment]
I can reproduce the problem with:
```
import numpy as np
import torch
from skimage.color import gray2rgb
import faiss

if __name__ == '__main__':
    DEVICE = torch.device('cuda')
    mt = np.random.rand(10000, 1024).astype('float32')
    mat = faiss.PCAMatrix(1024, 100)
    mat.train(mt)
    tr = mat.apply_py(mt)
    np.any(np.isnan(tr))
```
