### ISSUE TITLE
Issue with range_search and IndexScalarQuantizer

### ISSUE THREAD

**Issue by arpesenti** [facebookresearch/faiss#3650]
# Summary

I am trying to use range_search with an IndexScalarQuantizer but I get the following exception:

```
  File "/home/brains99/Install/Dragon/Local/Library/virtualenv/lib/python3.10/site-packages/faiss/swigfaiss_avx2.py", line 1961, in range_search
    return _swigfaiss_avx2.Index_range_search(self, n, x, radius, result, params)
RuntimeError: Error in virtual void faiss::Index::range_search(faiss::idx_t, const float*, float, faiss::RangeSearchResult*, const faiss::SearchParameters*) const at /project/faiss/faiss/Index.cpp:33: range search not implemented
```

The documentation says that it should be supported. Am I missing something?

# Platform

OS: Ubuntu 

Faiss version: 1.8.0

Installed from: pip

Running on:
- [X ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X ] Python

# Reproduction instructions

```
import faiss
import numpy as np
vectors = np.random.rand(100, 128).astype('float32')
index = faiss.index_factory(128, 'SQfp16')
index.train(vectors)
index.add(vectors)
query = np.zeros((1, 128)).astype('float32')
index.range_search(query, 0.5)
```

**Comment by kuarora** [comment]
Yes, this is not currently supported. Feel free to add support and send changes for review otherwise someone from our team will look at it.

**Comment by mdouze** [comment]
Range search *is* supported since a few weeks. Please use a nightly build. Note that support relies on decompression so it will not be very efficeint.

**Comment by arpesenti** [comment]
I'll give it try, thank you!
