### ISSUE TITLE
Request for help*****when i do index search，The program terminated directly without any error reporting.

### ISSUE THREAD

**Issue by larksudo** [facebookresearch/faiss#3652]
My program creates an index using index_factory. It runs normally when # INDEX_KEY = "IDMap,Flat", but when I switch to other types of indexes, the index can be created successfully. However, when conducting a search, the program terminates directly, and there is no error reporting in the terminal.

index = faiss.index_factory(self.dimensions, INDEX_KEY)
index.add_with_ids(features, ids)

Because the feature extraction of one of my images is a vector with a shape of (100, 128) using SIFT, so I need a custom ID for IDMap. When I try INDEX_KEY = "IDMap,OPQ16_64,IMI2x8,PQ8+16", or INDEX_KEY = "IDMap,PCA128,IVF2048,PQ16", the program terminates directly during the search.

![image](https://github.com/user-attachments/assets/4cb1a038-be06-4c5f-9461-a40d0333519e)

![image](https://github.com/user-attachments/assets/6b0ca01a-b9cc-4e02-99dc-b17397b05837
![1](https://github.com/user-attachments/assets/cee203e1-73d9-45db-b14b-9fdd956f76be)

****it just break out here.***
![image](https://github.com/user-attachments/assets/17550072-5fda-46c4-bd3b-15b57b32c802)

questions:
whats going on, the index_key is not fit, or what?

Running on:
- [*] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [*] Python

**Comment by mdouze** [comment]
Please post a fully reproducible example (no screenshot) and fill in the version and how installed question.
