### ISSUE TITLE
Using FAISS with Tf-Seq2Seq - Index Errors

### ISSUE THREAD

**Issue by kells94** [facebookresearch/faiss#368]

**Comment by mdouze** [comment]
Hi 
Faiss supports numpy arrays, which is the case here.
Apparently `merged_batch_logits` does not have 128 columns. Have you checked that?

**Comment by kells94** [comment]
hi , sorry , I just updated the code.  this is reproducible. I wanted to predict the value from the decoder output using Faiss. Any pointers or suggestions would be welcome ;)
