### ISSUE TITLE
does ivfflat index with mmap support "add" operation?

### ISSUE THREAD

**Issue by yongjunjian** [facebookresearch/faiss#369]
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on :
- [* ] CPU
- [ ] GPU

# Reproduction instructions

when I add vectors to an ivfflat index opened with mmap,  the exceptions is:

erminate called after throwing an instance of 'faiss::FaissException'
  what():  Error in virtual size_t faiss::OnDiskInvertedLists::add_entries(size_t, size_t, const idx_t*, const uint8_t*) at OnDiskInvertedLists.cpp:396: Error: '!read_only' failed

then I check the source code, I find out that the index is set to be read_only forcely. 

} else if (h == fourcc ("ilar") && (io_flags & IO_FLAG_MMAP)) {
 548         auto ails = new OnDiskInvertedLists ();
 549         READ1 (ails->nlist);
 550         READ1 (ails->code_size);
 551         ails->read_only = true;

so the question is: does ivfflat index loaded with mmap support "add" operation?

**Comment by mdouze** [comment]
Hi 
No it does not, the format is packed and does not offer extra space for extension.
See for example 
https://github.com/facebookresearch/faiss/blob/master/demos/demo_ondisk_ivf.py
--> mmap is used to merge indexes on into an ondisk index.
Note that the ondisk index does support add, but it is inefficient in its current form, so we do not recommend it.
