### ISSUE TITLE
FAISS, OpenMP and OpenBLAS interaction

### ISSUE THREAD

**Issue by alexanderguzhva** [facebookresearch/faiss#3700]
Please add to wiki that in order to have no issues with Faiss, OpenMP and OpenBLAS, one needs to use `libopenblas-openmp-dev` / `libopenblas0-openmp` Ubuntu packages instead of `libopenblas-dev` / `libopenblas0-pthread`. 

I had a weird case where PQ training would trigger an infamous `N^2` threads problem: each of OpenMP `N` threads calls `sgemm()`, and each `sgemm()` instantiates its own `N` OpenBLAS threads. This is because OpenBLAS uses pthread scheduling by default (check https://github.com/OpenMathLib/OpenBLAS/wiki/Faq#multi-threaded), and it may trigger a weird interaction if PQ training is run not from the main thread.

**Comment by mdouze** [comment]
where should we add that?

**Comment by mengdilin** [comment]
Maybe we can do it here: https://github.com/facebookresearch/faiss/wiki/Installing-Faiss as a warning?

**Comment by alexanderguzhva** [comment]
Or maybe [How to make Faiss run faster](https://github.com/facebookresearch/faiss/wiki/How-to-make-Faiss-run-faster) or/and [Troubleshooting](https://github.com/facebookresearch/faiss/wiki/Troubleshooting)

**Comment by mengdilin** [comment]
Done in https://github.com/OpenMathLib/OpenBLAS/wiki/Faq#multi-threaded
