### ISSUE TITLE
DTW distance implementation

### ISSUE THREAD

**Issue by akurniawan** [facebookresearch/faiss#3709]
# Summary

Hi folks, thanks for the great product!

Just wondering if there is any plan to implement DTW (Dynamic Time Warping) soon as one of the distance metric? My use case is related to time series where the timestep is quite important and can't be covered by simple cosine similarity or some metrics that have been implemented in faiss.

Thank you!

**Comment by mdouze** [comment]
Do you have a definition for DTW for vectors? I know it for sequences.
