### ISSUE TITLE
Failure to add vector to HNSW index in Window

### ISSUE THREAD

**Issue by heemin32** [facebookresearch/faiss#3712]
# Summary
It fails to add vector to HNSW index in window platform. Same script works for Mac.

# Platform
x64

OS: Window Server 2022

Faiss version: 1.8.0

Installed from: pip install faiss-cpu

Faiss compilation options: N/A

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions
```
import numpy as np
import faiss

# Minimal example vectors and ids
vectors = np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32)
ids = np.array([1, 2], dtype=np.int64)

# Create an HNSW index using the factory
dimension = vectors.shape[1]
index_description = "HNSW16,Flat"
hnsw_index = faiss.index_factory(dimension, index_description)

# Add vectors
hnsw_index.add(vectors) <-- It seem it fail here

# Example query vector
query_vector = np.array([[1.5, 2.5]], dtype=np.float32)

# Perform a search
k = 2
distances, neighbors = hnsw_index.search(query_vector, k)

print("Distances:", distances)
print("Neighbors:", neighbors)
```
Output
```
PS C:\workspace\faiss> python .\test.py
PS C:\workspace\faiss>
```
Expected Output
```
Distances: [[0.5 4.5]]
Neighbors: [[0 1]]
```

**Comment by mdouze** [comment]
What is the error? A crash? 

NB that `add_with_ids` is not supported for HNSW.

**Comment by heemin32** [comment]
I think it is a crash. It does not print anything after that line. However, there was no exception thrown from that line as well.

**Comment by mengdilin** [comment]
@heemin32  can you try installing `faiss` with conda instead of pip? We do not support installing with pip officially.

I ran your script on a Windows Server 2019 and it produced the right expected output.

Feel free to reopen the issue if you can reproduce this with conda installed faiss
