### ISSUE TITLE
'ProductQuantizer is implemented for L2 only'

### ISSUE THREAD

**Issue by alexanderguzhva** [facebookresearch/faiss#3714]
There is a line in `ProductQuantizer.h` that states the following:
https://github.com/facebookresearch/faiss/blob/b670cb1cc6f07fc2547a92dcbc01b6d64440a53b/faiss/impl/ProductQuantizer.h#L24

@mdouze Would you please explain what this comment means exactly, because it is not clear at all :). Thanks!

**Comment by jiajieyao** [comment]
PQDistanceComputer # float symmetric_dis(idx_t i, idx_t j) only support L2 （computer_sdc_table only init L2 sdc table），not support IP

**Comment by mdouze** [comment]
The comment is outdated. PQ does support IP search. 
The limit is that the k-means training minimizes the L2 distance to centroids, therefore the quantization error is biased towards L2 distance. 
It would be possible to implement SDC for IP distances, but we have not seen a use case for it yet.

**Comment by jiajieyao** [comment]
review pq code，both training and encode are L2，which explain the ip low recall for sift1M .
why is IP distance not supported，is it a mathematical mechanism problem or have not seen a use case for it yet? thanks @mdouze
