### ISSUE TITLE
does faiss support distribute system？

### ISSUE THREAD

**Issue by HuangZhanPeng** [facebookresearch/faiss#372]
Does faiss can run on spark or some like frame？

**Comment by mdouze** [comment]
See #189

**Comment by HuangZhanPeng** [comment]
thx for answering my question，I got that "Faiss can be distributed easily by sharding the database over several machines."，I still have a question is that what is meaning of "sharding the database over several machines"? And is there any example about that? Thank you very much~~

**Comment by mdouze** [comment]
It is not implemented in the core library.

**Comment by MaggieX** [comment]
> Does faiss can run on spark or some like frame？

May I know if you were able to run it with Spark?

**Comment by tomlincr** [comment]
Example of distributed faiss on Spark  using `autofaiss` here: https://github.com/criteo/autofaiss/blob/master/docs/distributed/distributed_autofaiss.md
