### ISSUE TITLE
index file copy

### ISSUE THREAD

**Issue by fuchao01** [facebookresearch/faiss#373]
One server generated index file was copied to another server and reported an error

RuntimeError: Error in faiss::Index* faiss::read_index(FILE*, bool) at index_io.cpp:762: Index type 0x6c467749 not supported

# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on :
- [x ] CPU
- [ ] GPU

# Reproduction instructions

**Comment by mdouze** [comment]
Hi
This is because the Faiss version used on both machines is different. The file was written by a new faiss and read by a old one (the other way round is supported).
