### ISSUE TITLE
Error reconstructing vector: direct map not initialized

### ISSUE THREAD

**Issue by burk** [facebookresearch/faiss#374]
# Summary

I'm trying to get the closest vectors of a given ID that is already in the index. AFAIK Faiss does not contain this type of query. My idea was to then first request a reconstructed vector, and query based on that, but I'm failing to reconstruct the vectors.

# Platform

OS: Ubuntu, Python 2

Faiss compilation options: OpenBlas

Running on :
- [x] CPU
- [ ] GPU

# Reproduction instructions

Calling `index.reconstruct(id)` gives

    RuntimeError: Error in virtual void faiss::IndexIVF::reconstruct(faiss::Index::idx_t, float*) const at IndexIVF.cpp:304: Error: 'direct_map.size() == ntotal' failed: direct map is not initialized

Do I need to do something specific to construct this map?

I've tested this on indexes with these factory strings "OPQ128_512,IMI2x12,SQ8 and "OPQ128_512,IVF16000,SQ8". Adding and searching work fine. Does these indexes not support reconstruction?

Do you have better suggestions for querying for the neighbors of an item already in the index (only based on the ID)?

**Comment by mdouze** [comment]
Hi
IMI and IVF indexes can only reconstruct if the direct map is initialized. 
To initialize it, use the `make_direct_map()` method.
Given that your index is embedded in an `IndexPreTransform`, you have to do:
```
downcast_index(myindex.index).make_direct_map()
```

**Comment by yuyifan1991** [comment]
> Hi
> IMI and IVF indexes can only reconstruct if the direct map is initialized.
> To initialize it, use the `make_direct_map()` method.
> Given that your index is embedded in an `IndexPreTransform`, you have to do:
> 
> ```
> downcast_index(myindex.index).make_direct_map()
> ```
If I use the _use the `make_direct_map()` method._ ,error happened : _RuntimeError: Error in void faiss::IndexIVF::make_direct_map(bool) at IndexIVF.cpp:159: Error: '0 <= idlist [ofs] && idlist[ofs] < ntotal' failed: direct map supported only for seuquential ids_
