### ISSUE TITLE
[From 3692] Improve unit test coverage of HNSW::MinimaxHeap

### ISSUE THREAD

**Issue by asadoughi** [facebookresearch/faiss#3746]
> HNSW::MinimaxHeap requires a dedicated unit test in a separate PR (which may go before my PR), because the problem where caused a recall HUGE regression in the past, See https://github.com/facebookresearch/faiss/pull/2771)

From @alexanderguzhva

**Comment by alexanderguzhva** [comment]
@asadoughi  https://github.com/facebookresearch/faiss/blob/main/tests/test_hnsw.cpp (?)
