### ISSUE TITLE
"index_cpu_to_gpu" has been stuck indefinitely, no error

### ISSUE THREAD

**Issue by weirdo2310** [facebookresearch/faiss#3754]
# Summary

# Platform

OS:  linux 

Faiss version:  faiss-gpu==1.7.2 

Installed from:  pip  

Running on:
- [ ] CPU
- [√ ] GPU

Interface: 
- [ ] C++
- [√ ] Python

# Reproduction instructions
sample code：
import faiss
import numpy as np

gpu_available = faiss.get_num_gpus()
print(f"Number of GPUs available: {gpu_available}")

if gpu_available > 0:
    d = 128
    nb = 100
    x = np.random.random((nb, d)).astype('float32')
    print(x)

    res = faiss.StandardGpuResources()
    print(res)
    index = faiss.IndexFlatL2(d)
    print("index:", index)
    gpu_index = faiss.index_cpu_to_gpu(res, 0, index)
    print("gpu_index:", gpu_index)

    gpu_index.add(x)
    print(f"Total vectors in index: {gpu_index.ntotal}")
else:
    print("No GPUs available.")
-----------------------------------------------------------------------------------------------------------------------------------------
T4：It can output normally.
Number of GPUs available: 2
[[0.17746119 0.9224653  0.24610409 ... 0.5598832  0.51143354 0.5759148 ]
 [0.325566   0.5075256  0.76574343 ... 0.07315133 0.43024534 0.470068  ]
 [0.11001278 0.02229974 0.23993117 ... 0.44794777 0.7898744  0.80646247]
 ...
 [0.07701585 0.6637102  0.9096464  ... 0.53623784 0.9527962  0.48809266]
 [0.47006914 0.25394025 0.9221015  ... 0.57556176 0.02762746 0.83336294]
 [0.06293927 0.6127859  0.2948191  ... 0.11160107 0.40583512 0.92149615]]
<faiss.swigfaiss.StandardGpuResources; proxy of <Swig Object of type 'faiss::gpu::StandardGpuResources *' at 0x7f0a8fb474e0> >
index: <faiss.swigfaiss.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x7f0873f0bba0> >
gpu_index: <faiss.swigfaiss.GpuIndexFlat; proxy of <Swig Object of type 'faiss::gpu::GpuIndexFlat *' at 0x7f0873f0ba80> >
Total vectors in index: 100

Process finished with exit code 0
-------------------------------------------------------------------------------------------------------------------------------------------
L40 and A10："index_cpu_to_gpu" has been stuck indefinitely, no error
Number of GPUs available: 2
[[0.74482864 0.1823411  0.49132434 ... 0.507351   0.79583    0.75722307]
 [0.09028755 0.31245697 0.7102012  ... 0.56431586 0.40372726 0.1361923 ]
 [0.56219476 0.80793947 0.5681971  ... 0.6030558  0.14707372 0.21690033]
 ...
 [0.7042571  0.87766105 0.3640532  ... 0.22029534 0.5318586  0.4514519 ]
 [0.8306828  0.21025237 0.02259618 ... 0.654959   0.615125   0.6751208 ]
 [0.41462666 0.20597364 0.8321564  ... 0.35457563 0.7431336  0.6389154 ]]
<faiss.swigfaiss.StandardGpuResources; proxy of <Swig Object of type 'faiss::gpu::StandardGpuResources *' at 0x7fcfa4b5b300> >
index: <faiss.swigfaiss.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x7fcf8a251650> >

**Comment by asadoughi** [comment]
Please try again installing with conda: https://github.com/facebookresearch/faiss/blob/main/INSTALL.md#installing-faiss-via-conda This repository doesn't support the PyPi page.
