### ISSUE TITLE
Access `nprobe` attribute for an `IndexPreTransform` 

### ISSUE THREAD

**Issue by terencezl** [facebookresearch/faiss#376]
# Summary

Find `nprobe` attribute for an `IndexPreTransform`, such as `OPQ64_256,IVF4096,PQ64`.

# Platform

OS: Linux

Faiss version: 4d440b6698fcc7b08607534bc622902b52bf9c49

Faiss compilation options: from pytorch/faiss-cpu

Running on :
- [x] CPU
- [ ] GPU

# Reproduction instructions

I was able to set/get `nprobe` attribute for an `IndexIVFFlat`, or `IndexIVFScalarQuantizer`, but for an index constructed through factory, or `faiss.load_index()`, such as `OPQ64_256,IVF4096,PQ64`, how can I achieve the same attribute?

**Comment by mdouze** [comment]
Hi 
You can do:
```
faiss.ParameterSpace().set_index_parameter(index, "nprobe", 123)
```
or
```
faiss.downcast_index(index.index).nprobe = 123
```

**Comment by terencezl** [comment]
Thanks!
