### ISSUE TITLE
Index factory string parser convenient abbreviations

### ISSUE THREAD

**Issue by asadoughi** [facebookresearch/faiss#3804]
for convenience it would be nice if the factory string parser would accept strings like IVF65k,Flat or IVF1M,Flat

**Comment by ramilbakhshyiev** [comment]
Could we please add more specifics here? Is the request here to start accepting the number of centroids in human-readable form? Or is there more?

**Comment by asadoughi** [comment]
cc @mdouze for more requirements

**Comment by asadoughi** [comment]
Completed in #3812
