### ISSUE TITLE
how to get KNN graph directly from IndexNNDescentFlat?

### ISSUE THREAD

**Issue by LucasLee-ff** [facebookresearch/faiss#3811]
Hi, how can I get the KNN graph (a 2-d array if I understand correctly) after training an IndexNNDescentFlat? I am running faiss both using C++ and Python; could you provide me with two demos?

Thank you very much!

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [x] Python

**Comment by mdouze** [comment]
see [demo_access_nndescent.ipynb](https://gist.github.com/mdouze/105dd68d8921134e9270e832f4bdbe66#file-demo_access_nndescent-ipynb)

**Comment by LucasLee-ff** [comment]
problem solved, thank you very much!

**Comment by LucasLee-ff** [comment]
problem solved, thank you very much!
