### ISSUE TITLE
FLAT Index with METRIC_INNER_PRODUCT brings different results when using CPU and GPU

### ISSUE THREAD

**Issue by qwevdb** [facebookresearch/faiss#3816]
# Summary

Using FLAT Index with METRIC_INNER_PRODUCT and special data to search brings different results when running on CPU and GPU.

# Platform

OS: Ubuntu 24.04 LTS 

Faiss version: faiss-gpu 1.8.0 

Installed from:  Anaconda

Faiss compilation options: 

Running on:
- [✔] CPU
- [✔] GPU

Interface: 
- [ ] C++
- [✔] Python

# Reproduction instructions

 

1. Run the Python script with special data(data.json) as follow.
2. Search results are different when using CPU and GPU in the Python script, although the configuration parameters are the same including index and metric type.

``` python
import faiss
import numpy as np
import json

dim = 240
metric = faiss.METRIC_INNER_PRODUCT
 
index1 = faiss.IndexFlat(dim, metric)
index2 = faiss.IndexFlat(dim, metric)
with open("data.json", 'r')as file:
    operate_data = json.load(file)    
insert_data = operate_data["param"]["dataset"][0]
insert_data = np.array(insert_data, dtype=np.float32)
index1.train(insert_data)
index1.add(insert_data)
index2.train(insert_data)
index2.add(insert_data)

query_vector = operate_data["param"]["query_vector"]
query_vector = np.array(query_vector, dtype=np.float32)

k = 10
D1, I1 = index1.search(query_vector, k)
print("result1:")
print(I1)
print(D1)
res = faiss.StandardGpuResources()
gpu_index = faiss.index_cpu_to_gpu(res, 0, index2)
D2, I2 = gpu_index.search(query_vector, k)
print("result2:")
print(I2)
print(D2)
```
data.json:
[data.json](https://github.com/user-attachments/files/16830004/data.json)

result:
``` bash
result1:
[[359  90  82  68 392 371 290  52 163 390]]
[[60.614517 60.231094 60.12149  60.02794  59.912674 59.81262  59.812614
  59.492607 59.450783 59.273476]]
result2:
[[359  90  82  68 392 290 371  52 163 390]]
[[60.614517 60.231094 60.121494 60.02794  59.912674 59.81262  59.812614
  59.492607 59.450783 59.273476]]
```

**Comment by asadoughi** [comment]
`np.dot(query_vector, insert_data[371]) == np.dot(query_vector, insert_data[290])` with float32 precision (on CPU) so it's possible you will get an unstable ordering of ids with a similar calculation on GPU.
