### ISSUE TITLE
Question on the meaning of PQ4?

### ISSUE THREAD

**Issue by mucun1988** [facebookresearch/faiss#382]
While I am reading the lower memory footprint tutorial (https://github.com/facebookresearch/faiss/wiki/Lower-memory-footprint), I am wondering why for product quantization with number of bytes per vector as 8 and each sub-vector is encoded as 8 bits, its corresponding index factory is `PQ4`. More generally, I do not quite understand the meaning of `PQx`...

Also there might be a typo that `the factory string to preprocess reduce the vectors to 23D by PCA projection` should be `...32D...`.

Thanks,
Matt

**Comment by mdouze** [comment]
Hi
Thanks for flagging! The correct string is indeed `IVF100,PQ8` and the PCA size is 32, as you say.

**Comment by mucun1988** [comment]
Hi @mdouze 


Many thanks for the reply and now I see the point. 

So, PQx will always use 8 bits (=1 byte) to encode each PQ component.

Then suppose I want to use 16 bits (instead of 8 bits) to encode each PQ component, is it still possible to express that using index factory?


Sincerely,
Matt

**Comment by mdouze** [comment]
See 
https://github.com/facebookresearch/faiss/wiki/FAQ#other-questions
Is PQ encoding with more or less than 8 bits per components supported?

**Comment by mucun1988** [comment]
Cool!
