### ISSUE TITLE
Refine Layer not support `add_with_ids`

### ISSUE THREAD

**Issue by Tickdack** [facebookresearch/faiss#3820]
# Summary

I want to use refine layer to re-order the coarse-results for more accurate output, but I find refine-layer is seemingly not support add_with_ids, I'm a little confused because the raw id should be stored in coarse-grained sorting model, the refine layer just rerank the coarse-result. How can I modify my parameters to use a refine-layer that support `add_with_ids` for improve the accuracy? Do I have to use `IDMap` in refine-layer? I think it's cracy to memory.

# Platform

OS: CentOS

Faiss version: faiss 1.5

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

Here is my index_type parameter: `IVF20480,PQ192x4fs,Refine(PQ96x8)`

**Comment by Tickdack** [comment]
I read the source Cpp file, and I find the class `IndexRefine`, I find `IndexRefine` not support `add_with_ids`, but I want to use `fastscan` index(Refine is necessary), what the general  scheme to use it if i want to get our own assigned id when `search`？thank you.

**Comment by mdouze** [comment]
The `IndexRefine` does not support `add_with_ids` because the ids need to be sequential indices for the refinement index, which is most often an `IndexFlatCodes`. 
If you need `add_with_ids`, please wrap the index in an `IndexIDMap`.

**Comment by Tickdack** [comment]
> The `IndexRefine` does not support `add_with_ids` because the ids need to be sequential indices for the refinement index, which is most often an `IndexFlatCodes`. If you need `add_with_ids`, please wrap the index in an `IndexIDMap`.

Thank you sir, it means I should use "IDMap,IVF20480,PQ192X4fsr,Refine(PQ96x8)" as the index factory key, is that right?

**Comment by mdouze** [comment]
Right, supporting `revove_ids` would be an enhancement. Making a new issue for this.
