### ISSUE TITLE
FAISS Index Factory String equivalent code and vice versa

### ISSUE THREAD

**Issue by ashleyabraham** [facebookresearch/faiss#3843]
Is the FAISS Index Factory string `IVF132_HNSW32,PQ5x8` 

```
D = 128
index = faiss.index_factory(D, `IVF132_HNSW32,PQ5x8`)
```
equivalent to the following code

```
hnsw_m = 32
nlist = 132
M=5
nbits = 8

quantizer = faiss.IndexHNSWFlat(D, hnsw_m)
index = faiss.IndexIVFPQ(quantizer, D, nlist, M, nbits)
```
If not what is the correct code for the above index factory string and also what is the index factory string for the above code

**Comment by mengdilin** [comment]
Yes they are equivalent. The issue here is faiss expects dimension has to be a multiple of M (# of subquantizers). Right now, you set the M to 5 and 128 is not divisible by 5. An example fix would be setting M to 4 

```
D = 128
index = faiss.index_factory(D, "IVF132_HNSW32,PQ4x8")
```

**Comment by ashleyabraham** [comment]
Thank you!
