### ISSUE TITLE
BSD+Patents License

### ISSUE THREAD

**Issue by felipegasparini** [facebookresearch/faiss#385]
# Summary

First of all, kudos for this amazing library. =)

Faiss is currently licensed as BSD + Patents clause. 
Last year there was a huge discussion in the OSS community regarding this license type and Facebook decided to change the license of a few projects (the most notable being React) to solve this discussion.

Is there any plans to change the license of Faiss to something else?

**Comment by mdouze** [comment]
Hi 
We do not have currently plans to change the license. 
In your opinion, what is wrong with the current license, and how should it be changed?

**Comment by felipegasparini** [comment]
Hi!

The problem with the current license is that it creates a risk to other companies that uses Faiss, specially for start-ups.

There is a huge set of articles about the polemics of this licensing model, that I think it is just easier to just point a few of them here so you can have a better picture.

https://medium.com/@raulk/if-youre-a-startup-you-should-not-use-react-reflecting-on-the-bsd-patents-license-b049d4a67dd2

https://github.com/facebook/react/issues/10719

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/

I'm not representing any company here (including my employer), I'm just concerned about adopting/contributing to Faiss due to its license model.

**Comment by Aashit-Sharma** [comment]
@mdouze what is the benefit of keeping it BSD+ ?
If you guys doing the hard work and providing it to everyone , why not keep it no-strings-attached ?

**Comment by jkmarz** [comment]
If you want to make an explicit patent grant, please use an OSI-approved license that includes one. Like maybe this one: https://opensource.org/licenses/BSDplusPatent  Or, you know, the Apache license. 

Indeed, huge sets of articles about this subject, here's one of my favorites: https://meshedinsights.com/2017/07/16/apache-bans-facebooks-license-combo/

**Comment by mdouze** [comment]
Thanks all for the pointers on general context. 
Are there any comments on what an alternative Faiss license would unblock for you or your company specifically?

**Comment by AKSHAYUBHAT** [comment]
University research labs might not be able to use FAISS due to Patents+BSD license since unlike other entities such as corporations or individuals, Universities have a diverse patent portfolio. The additional Patents language makes the resulting license more difficult to use than even GPL 3.0 since it has effect on other intellectual property (non-software patents) that the University might hold. E.g. chip designs, chemicals, drugs etc.

**Comment by jkmarz** [comment]
Dropping the current, separate "+Patents" would be great. Then you'd be left with the OSI-approved 3-clause BSD license, which is totally acceptable. Or, you could follow in the footsteps of React and a number of other Facebook projects and relicense under MIT.

**Comment by kumon** [comment]
Hi.
Which algorithms and implementations in this library are covered with the patents?

**Comment by jkmarz** [comment]
@mdouze -- facebookresearch/fastText just relicensed to MIT a couple of days ago: https://github.com/facebookresearch/fastText/issues/650

**Comment by hyandell** [comment]
+1 for a relicense. This would allow open source organizations, like Apache, to use this, in addition to simplifying review/consideration for company users.

**Comment by jeremyjordan** [comment]
+1 for a relicense to MIT (same as React and fastText)

**Comment by beauby** [comment]
Faiss has been re-licensed to MIT starting with v1.5.2.
