### ISSUE TITLE
Numerous typos in code

### ISSUE THREAD

**Issue by Harry-Chen** [facebookresearch/faiss#3859]
# Summary

Some typos in the code should be handy to fix. They are all detected by Debian's litian with tag `spelling-error-in-binary`.

Faiss version: dc55e11874e4e32d0f04a9d62156ebe2ca25192d

* hanlde -> handle: some files under `faiss/impl/`
* identifer -> identifier: `faiss/AutoTune.h`
* impemented -> implemented: `faiss/IndexIVFFastScan.cpp`, `faiss/invlists/BlockInvertedLists.cpp`
* implemetation -> implementation: `faiss/IndexIVF.h`
* ouptut -> output: `faiss/impl/AuxIndexStructures.h`, `faiss/utils/hamming.cpp`
* strcuture -> structure: some files under `faiss/*.h`
* tranforms -> transforms: `faiss/IndexPreTransform.h`
* neighors -> neighbors: `faiss/utils/distances.h`
       
I can submit a PR if that is acceptable.

**Comment by alexanderguzhva** [comment]
@Harry-Chen yes, please do!
