### ISSUE TITLE
Question on IndexIVFPQ?

### ISSUE THREAD

**Issue by mucun1988** [facebookresearch/faiss#386]
While I am reading lower memory footprint (https://github.com/facebookresearch/faiss/wiki/Lower-memory-footprint), I am confused by the parameter `d` in the following two lines:
`quantizer = faiss.IndexFlatL2(d)  # this remains the same`
`index = faiss.IndexIVFPQ(quantizer, d, nlist, m, 8)`

Basically, I am thinking the`d` in the second line means the same thing as the `d` in the first line. But if that is the case, why it needs to be specified twice?

Thanks,
Matt

**Comment by mucun1988** [comment]
Hi @mdouze 


Cool! 

So if I specify d1 and d2 differently, i.e.,
`quantizer = faiss.IndexFlatL2(d1) # this remains the same`
`index = faiss.IndexIVFPQ(quantizer, d2, nlist, m, 8)`, 
I guess the d2 in the second line will overwrite the d1 in the first one.


Thanks,
Matt

**Comment by wickedfoo** [comment]
> I guess the d2 in the second line will overwrite the d1 in the first one.

It won't overwrite it (it doesn't propagate the value to the quantizer), but it will assert:

https://github.com/facebookresearch/faiss/blob/master/IndexIVF.cpp#L236

**Comment by mucun1988** [comment]
Hi @wickedfoo 


Got it! Many thanks!


Sincerely,
Matt
