### ISSUE TITLE
FAISS MacOS build fail test_index.py

### ISSUE THREAD

**Issue by ailzhang** [facebookresearch/faiss#388]
# Summary

# Platform

OS: macOS

Faiss version: v1.2.1

Faiss compilation options: using provided makefile.inc.brew

Running on :
- [ x] CPU
- [ ] GPU

# Reproduction instructions

python test_index.py

shows the following 
```
======================================================================
FAIL: test_IMI (__main__.EvalIVFPQAccuracy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_index.py", line 110, in test_IMI
    self.assertGreater(n_ok, 169)
AssertionError: 166 not greater than 169

======================================================================
FAIL: test_IMI_2 (__main__.EvalIVFPQAccuracy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_index.py", line 166, in test_IMI_2
    self.assertGreater(n_ok, 169)
AssertionError: 166 not greater than 169

----------------------------------------------------------------------
Ran 15 tests in 4.418s
```

**Comment by mdouze** [comment]
Hi 
The thresholds of the tests were calibrated on Linux.
Why they not work here is either: 
- the random dataset is slightly different 
- the IMI index is slightly different
I will look into it, but it does not seem a serious problem.

**Comment by beauby** [comment]
I successfully reproduced this. Will look into it.

**Comment by beauby** [comment]
After investigation, this is indeed just a difference in the random number generators of the two platforms. I'll fix the tests.
