### ISSUE TITLE
RuntimeError: Error in faiss::Index* faiss::read_index(faiss::IOReader*, int) at /project/faiss/faiss/impl/index_read.cpp:1053: Index type 0x73726576 ("vers") not recognized

### ISSUE THREAD

**Issue by raju-kulkarni** [facebookresearch/faiss#3888]
# Summary

I am reading the faiss index inside the docker but getting above error. I checked the faiss-cpu version where it is created but still having the same problem. when I created a docker locally it is working well but in my platform it is giving error.

# Platform

OS:  Ubuntu 20.04

Faiss version: faiss-cpu==1.8.0.post1

Installed from: pip

Running on:
- [ ] CPU

Interface: 

- [ ] Python

# Reproduction instructions
It is not running to my specific platform.
  |   | 2024-09-25 16:59:48.508 | File "/usr/local/lib/python3.10/site-packages/faiss/swigfaiss_avx2.py", line 10538, in read_index |  
  |   | 2024-09-25 16:59:48.508 | index = faiss.read_index('./image_vector_db/index.bin')

**Comment by asadoughi** [comment]
Hi @raju-kulkarni - Installing faiss via pip is not supported by this repository. Please try installing faiss from conda: https://github.com/facebookresearch/faiss/blob/main/INSTALL.md#installing-faiss-via-conda

**Comment by Tickdack** [comment]
It means your index file is broken, when faiss process read the index file, it discern the tag doesn't contain in code, make sure  train your index with your faiss in docker, but not use other odd files

**Comment by raju-kulkarni** [comment]
@Tickdack  I am able to run this on linux machine, even I am to run the same index with docker also locally it is running but when I put this into my server it is having that index read problem. is index read function require internet access.
