### ISSUE TITLE
k-means memory requirement?

### ISSUE THREAD

**Issue by mrgloom** [facebookresearch/faiss#39]
What if I have matrix m x n and want to perform k-means clustering (k clusters) what will be memory requirement?

**Comment by mdouze** [comment]
Hi 

The m*n matrix must fit in CPU RAM, no other requirement. See 

https://github.com/facebookresearch/faiss/wiki/GPU-k-means-example

**Comment by mrgloom** [comment]
So there is no method to reduce memory usage if I have large matrix that don't fit in memory?
Initially I was looking for somethink like http://scikit-learn.org/stable/modules/generated/sklearn.cluster.MiniBatchKMeans.html to feed data by batches to reduce peak memory usage.

**Comment by Larryjianfeng** [comment]
the same issues here

**Comment by mdouze** [comment]
I added a FAQ entry on this topic: 

https://github.com/facebookresearch/faiss/wiki/FAQ#how-many-training-points-do-i-need-for-k-means
