### ISSUE TITLE
amd cpu nvidia gpu python 3.12

### ISSUE THREAD

**Issue by mylesgoose** [facebookresearch/faiss#3911]
# Summary
Seems to compile okay and work for python 3.12 cuda 12.4 and amd cpu instruction set 
[faiss-gpu.zip](https://github.com/user-attachments/files/17267896/faiss-gpu.zip)
python3 setup.py bdist_wheel
Copying _swigfaiss.so
Copying _swigfaiss_avx2.so
Copying libfaiss_python_callbacks.so
running bdist_wheel
running build
running build_py
copying faiss/loader.py -> build/lib/faiss
copying faiss/gpu_wrappers.py -> build/lib/faiss
copying faiss/__init__.py -> build/lib/faiss
copying faiss/swigfaiss_avx2.py -> build/lib/faiss
copying faiss/swigfaiss.py -> build/lib/faiss
copying faiss/class_wrappers.py -> build/lib/faiss
copying faiss/array_conversions.py -> build/lib/faiss
copying faiss/extra_wrappers.py -> build/lib/faiss
copying faiss/libfaiss_python_callbacks.so -> build/lib/faiss
copying faiss/_swigfaiss_avx2.so -> build/lib/faiss
copying faiss/_swigfaiss.so -> build/lib/faiss
/home/myles/.local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/faiss
copying build/lib/faiss/loader.py -> build/bdist.linux-x86_64/wheel/faiss
copying build/lib/faiss/libfaiss_python_callbacks.so -> build/bdist.linux-x86_64/wheel/faiss
copying build/lib/faiss/_swigfaiss_avx2.so -> build/bdist.linux-x86_64/wheel/faiss
copying build/lib/faiss/gpu_wrappers.py -> build/bdist.linux-x86_64/wheel/faiss
copying build/lib/faiss/__init__.py -> build/bdist.linux-x86_64/wheel/faiss
copying build/lib/faiss/_swigfaiss.so -> build/bdist.linux-x86_64/wheel/faiss
creating build/bdist.linux-x86_64/wheel/faiss/contrib
copying build/lib/faiss/contrib/big_batch_search.py -> build/bdist.linux-x86_64/wheel/faiss/contrib
copying build/lib/faiss/contrib/inspect_tools.py -> build/bdist.linux-x86_64/wheel/faiss/contrib
copying build/lib/faiss/contrib/__init__.py -> build/bdist.linux-x86_64/wheel/faiss/contrib
copying build/lib/faiss/contrib/evaluation.py -> build/bdist.linux-x86_64/wheel/faiss/contrib
copying build/lib/faiss/contrib/vecs_io.py -> build/bdist.linux-x86_64/wheel/faiss/contrib
copying build/lib/faiss/contrib/ivf_tools.py -> build/bdist.linux-x86_64/wheel/faiss/contrib
copying build/lib/faiss/contrib/rpc.py -> build/bdist.linux-x86_64/wheel/faiss/contrib
copying build/lib/faiss/contrib/exhaustive_search.py -> build/bdist.linux-x86_64/wheel/faiss/contrib
copying build/lib/faiss/contrib/datasets.py -> build/bdist.linux-x86_64/wheel/faiss/contrib
copying build/lib/faiss/contrib/clustering.py -> build/bdist.linux-x86_64/wheel/faiss/contrib
copying build/lib/faiss/contrib/ondisk.py -> build/bdist.linux-x86_64/wheel/faiss/contrib
copying build/lib/faiss/contrib/client_server.py -> build/bdist.linux-x86_64/wheel/faiss/contrib
copying build/lib/faiss/contrib/torch_utils.py -> build/bdist.linux-x86_64/wheel/faiss/contrib
copying build/lib/faiss/contrib/factory_tools.py -> build/bdist.linux-x86_64/wheel/faiss/contrib
creating build/bdist.linux-x86_64/wheel/faiss/contrib/torch
copying build/lib/faiss/contrib/torch/quantization.py -> build/bdist.linux-x86_64/wheel/faiss/contrib/torch
copying build/lib/faiss/contrib/torch/__init__.py -> build/bdist.linux-x86_64/wheel/faiss/contrib/torch
copying build/lib/faiss/contrib/torch/clustering.py -> build/bdist.linux-x86_64/wheel/faiss/contrib/torch
copying build/lib/faiss/swigfaiss_avx2.py -> build/bdist.linux-x86_64/wheel/faiss
copying build/lib/faiss/swigfaiss.py -> build/bdist.linux-x86_64/wheel/faiss
copying build/lib/faiss/class_wrappers.py -> build/bdist.linux-x86_64/wheel/faiss
copying build/lib/faiss/array_conversions.py -> build/bdist.linux-x86_64/wheel/faiss
copying build/lib/faiss/extra_wrappers.py -> build/bdist.linux-x86_64/wheel/faiss
running install_egg_info
running egg_info
writing faiss_gpu.egg-info/PKG-INFO
writing dependency_links to faiss_gpu.egg-info/dependency_links.txt
writing requirements to faiss_gpu.egg-info/requires.txt
writing top-level names to faiss_gpu.egg-info/top_level.txt
reading manifest file 'faiss_gpu.egg-info/SOURCES.txt'
writing manifest file 'faiss_gpu.egg-info/SOURCES.txt'
Copying faiss_gpu.egg-info to build/bdist.linux-x86_64/wheel/faiss_gpu-1.9.0-py3.12.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/faiss_gpu-1.9.0.dist-info/WHEEL
creating 'dist/faiss_gpu-1.9.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'faiss/__init__.py'
adding 'faiss/_swigfaiss.so'
adding 'faiss/_swigfaiss_avx2.so'
adding 'faiss/array_conversions.py'
adding 'faiss/class_wrappers.py'
adding 'faiss/extra_wrappers.py'
adding 'faiss/gpu_wrappers.py'
adding 'faiss/libfaiss_python_callbacks.so'
adding 'faiss/loader.py'
adding 'faiss/swigfaiss.py'
adding 'faiss/swigfaiss_avx2.py'
adding 'faiss/contrib/__init__.py'
adding 'faiss/contrib/big_batch_search.py'
adding 'faiss/contrib/client_server.py'
adding 'faiss/contrib/clustering.py'
adding 'faiss/contrib/datasets.py'
adding 'faiss/contrib/evaluation.py'
adding 'faiss/contrib/exhaustive_search.py'
adding 'faiss/contrib/factory_tools.py'
adding 'faiss/contrib/inspect_tools.py'
adding 'faiss/contrib/ivf_tools.py'
adding 'faiss/contrib/ondisk.py'
adding 'faiss/contrib/rpc.py'
adding 'faiss/contrib/torch_utils.py'
adding 'faiss/contrib/vecs_io.py'
adding 'faiss/contrib/torch/__init__.py'
adding 'faiss/contrib/torch/clustering.py'
adding 'faiss/contrib/torch/quantization.py'
adding 'faiss_gpu-1.9.0.dist-info/METADATA'
adding 'faiss_gpu-1.9.0.dist-info/WHEEL'
adding 'faiss_gpu-1.9.0.dist-info/top_level.txt'
adding 'faiss_gpu-1.9.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
myles@ubuntu11:~/faiss/build/faiss/python$ pip3 install /home/myles/fai

ss/build/faiss/python/dist/faiss_gpu-1.9.0-py3-none-any.whl
DEPRECATION: Loading egg at /usr/local/lib/python3.12/site-packages/faiss-1.9.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.12/site-packages/faiss_gpu-1.9.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing ./dist/faiss_gpu-1.9.0-py3-none-any.whl
Requirement already satisfied: numpy in /usr/local/lib/python3.12/site-packages (from faiss-gpu==1.9.0) (2.1.2)
Requirement already satisfied: packaging in /home/myles/.local/lib/python3.12/site-packages (from faiss-gpu==1.9.0) (24.1)
faiss-gpu is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.

python3
Python 3.12.6 (main, Sep  7 2024, 19:24:43) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import faiss
>>> print(faiss.get_num_gpus())
8
>>> 

# Platform

OS: 

Faiss version: 

Installed from:  

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by ramilbakhshyiev** [comment]
Hi @mylesgoose, did you accidentally omit a question or bug report here?

**Comment by mylesgoose** [comment]
> Hi @mylesgoose, did you accidentally omit a question or bug report here?

Is not a bug just letting  you guys know it works with the newer system library's as above. Seems to compile okay and work for python 3.12 cuda 12.4 and amd cpu @ramilbakhshyiev

**Comment by ramilbakhshyiev** [comment]
@mylesgoose Sweet! Thanks for letting us know!
