### ISSUE TITLE
Docstring for python binding?

### ISSUE THREAD

**Issue by yupbank** [facebookresearch/faiss#393]
# Summary
It's not a bug but rather a feature request..

**Comment by mdouze** [comment]
Hi
It would be nice to have a tool that translates the doxygen annotations to docstrings.

**Comment by yupbank** [comment]
something like this https://github.com/BlueBrain/Pydoxine ?

**Comment by yupbank** [comment]
great news!

**Comment by mdouze** [comment]
SWIG 4 can generate docstrings with the new "-doxygen" flag. 
The conda packages are still compiled with SWIG 3 though.

**Comment by mdouze** [comment]
This is implemented in the current version.
