### ISSUE TITLE
Can I install faiss by pip ?

### ISSUE THREAD

**Issue by shiwanghua** [facebookresearch/faiss#3930]
Can I install faiss by pip ?

**Comment by ramilbakhshyiev** [comment]
Hi @shiwanghua, FAISS over pip isn't officially support but is available here thanks to contributors: https://pypi.org/project/faiss-cpu/.

**Comment by serozhenka** [comment]
@ramilbakhshyiev is there a specific reason for not publishing faiss to pypi?

**Comment by ramilbakhshyiev** [comment]
> [@ramilbakhshyiev](https://github.com/ramilbakhshyiev) is there a specific reason for not publishing faiss to pypi?

@serozhenka This is primarily due to bandwidth constraints and initial time investment required to make the initial transition.
