### ISSUE TITLE
FAISS build break in AIX (PowerPC)

### ISSUE THREAD

**Issue by KamathForAIX** [facebookresearch/faiss#3945]
# Summary

The commit https://github.com/facebookresearch/faiss/commit/847cde8652a5a832a4478bb339e1a775b110380e has broken FAISS build in AIX with the following message.

```
-lfaiss_example_external_module ../lib/libgtest_main.a ../lib/libgtest.a
ld: 0706-006 Cannot find or open library file: -l faiss_example_external_module
        ld:open(): A file or directory in the path name does not exist.
.ibm-clang: error: linker command failed with exit code 255 (use -v to see invocation)
gmake[2]: *** [tests/CMakeFiles/faiss_test.dir/build.make:552: tests/faiss_test] Error 1
gmake[2]: Leaving directory '/home/buildusr/jenkins/workspace/faiss-openxl/faiss/build'
gmake[1]: *** [CMakeFiles/Makefile2:1890: tests/CMakeFiles/faiss_test.dir/all] Error 2
gmake[1]: Leaving directory '/home/buildusr/jenkins/workspace/faiss-openxl/faiss/build'
gmake: *** [Makefile:146: all] Error 2
```

This happened because we do not have the swig module built in AIX, and hence the linker will not be able to find it. 

Looking at the code in the commit, it seems like we use it mainly for wrapping python modules. If that is the case, can we avoid linking swig external module to faiss test when FAISS_ENABLE_PYTHON=OFF like shown in the pull request.

# Platform

OS:  AIX

Faiss version:  Master branch

Installed from:  

Faiss compilation options: 
cmake . -B build   -DFAISS_ENABLE_GPU=OFF   -DBLA_VENDOR=OpenBLAS   -DBLAS_LIBRARIES=${OPENBLAS_PATH_SYS}/lib/libopenblas.so   -DLAPACK_LIBRARIES=${OPENBLAS_PATH_SYS}/lib/libopenblas.so   -DFAISS_ENABLE_PYTHON=ON   -DBUILD_TESTING=ON   -DBUILD_SHARED_LIBS=ON   -DCMAKE_BUILD_TYPE=Release   -DCMAKE_INSTALL_PREFIX=${PWD}/install_dir    -DCMAKE_AIX_SHARED_LIBRARY_ARCHIVE=ON 

Running on: CPU
- [ ] CPU
- [ ] GPU

# Reproduction instructions

Build on AIX with 
cmake . -B build   -DFAISS_ENABLE_GPU=OFF   -DBLA_VENDOR=OpenBLAS   -DBLAS_LIBRARIES=${OPENBLAS_PATH_SYS}/lib/libopenblas.so   -DLAPACK_LIBRARIES=${OPENBLAS_PATH_SYS}/lib/libopenblas.so   -DFAISS_ENABLE_PYTHON=ON   -DBUILD_TESTING=ON   -DBUILD_SHARED_LIBS=ON   -DCMAKE_BUILD_TYPE=Release   -DCMAKE_INSTALL_PREFIX=${PWD}/install_dir    -DCMAKE_AIX_SHARED_LIBRARY_ARCHIVE=ON

cmake --build build

**Comment by kuarora** [comment]
Change is already in.  See https://github.com/facebookresearch/faiss/pull/3946
Let me know if you're still seeing the issue.

**Comment by KamathForAIX** [comment]
@kuarora Yes, if we merge #3946 then we are good. Thank you.

**Comment by mnorris11** [comment]
We reverted the external module change in https://github.com/facebookresearch/faiss/pull/3954, so closing the issue.

If/when we re-add it, I will add the logic from your PR https://github.com/facebookresearch/faiss/pull/3946.

**Comment by mnorris11** [comment]
As an FYI: we plan to re-add the external module change in https://github.com/facebookresearch/faiss/pull/3981. I added your logic from https://github.com/facebookresearch/faiss/pull/3946 to it.

**Comment by KamathForAIX** [comment]
Thank you @mnorris11
