### ISSUE TITLE
How to get cosine similarity instead of distances

### ISSUE THREAD

**Issue by kumarivin** [facebookresearch/faiss#396]
# Summary

# Platform

OS:   macOS 10.13.4

Faiss version: 

Faiss compilation options: 

Running on :
- [ ] CPU
- [x] GPU

# Reproduction instructions

When I ran the example mentioned at https://github.com/facebookresearch/faiss/wiki/Getting-started with indexing "IndexFlatIP" I get the below output .

`[[     2      1      4      3      0]
 [  8202  51980  32919  63606  35470]
 [ 87994  86227      2  63606  35470]
 [ 63606  35470   1831   1836   1925]
 [ 63606  35470      4 124025   1831]]
[[ 0.         0.         0.         0.         0.       ]
 [29.168869  12.407899  11.381073  11.376259  11.376259 ]
 [10.275305   7.8386636  5.3935204  5.231113   5.231113 ]
 [15.152941  15.152941  11.073342  11.073342  11.073342 ]
 [11.170039  11.170039   9.986008   9.244003   9.12001  ]]`

I would like to know if there is a way to get the cosine similarity(ranging 0 to 1) measure instead of distances

**Comment by kumarivin** [comment]
I figured it out, from the other tickets. I had to normalize before index.

**Comment by pranavnijampurkar33** [comment]
Just adding example if noob like me came here to find how to calculate the Cosine similarity from scratch

import faiss
dataSetI = [.1, .2, .3]
dataSetII = [.4, .5, .6]
#dataSetII = [.1, .2, .3]

x = np.array([dataSetI]).astype(np.float32)
q = np.array([dataSetII]).astype(np.float32)
index = faiss.index_factory(3, "Flat", faiss.METRIC_INNER_PRODUCT)
index.ntotal
faiss.normalize_L2(x)
index.add(x)
faiss.normalize_L2(q)
distance, index = index.search(q, 5)
print('Distance by FAISS:{}'.format(distance))

#To Tally the results check the cosine similarity of the following example

from scipy import spatial


result = 1 - spatial.distance.cosine(dataSetI, dataSetII)
print('Distance by FAISS:{}'.format(result))
