### ISSUE TITLE
While Auto tuning : TypeError: in method 'OperatingPointVector_at', argument 2 of type 'size_t'

### ISSUE THREAD

**Issue by Aashit-Sharma** [facebookresearch/faiss#397]
# Summary

Error while trying out the autotune demo

# Platform

OS: Ubuntu 16.04

Running on :
- [x] CPU
- [] GPU

# Reproduction instructions
 Tried to run the [demo_auto_tune.py](https://github.com/facebookresearch/faiss/blob/master/demos/demo_auto_tune.py)

Made changes in the print functions(for running it in the python3 env) and added 1 line in the ivecs_read function:
def ivecs_read(fname):
```
    f = open(fname)
    d, = np.fromfile(f, count=1, dtype='int32')
    sz = os.stat(fname).st_size
    assert sz % (4 * (d + 1)) == 0
    n = sz / (4 * (d + 1))
    n = np.asarray(n).astype('int32') # Added because the above line was turning n to float
    f.seek(0)
    a = np.fromfile(f, count=n * (d + 1), dtype='int32').reshape(n, d + 1)
    return a[:, 1:].copy()
```

Here is the traceback:

Traceback (most recent call last):
```
  File "/home/PycharmProjects/faiss_exp/demo_auto_tune.py", line 164, in <module>
    plot_OperatingPoints(opi2, crit.nq, label=i2, marker='o')
  File "/home/PycharmProjects/faiss_exp/demo_auto_tune.py", line 48, in plot_OperatingPoints
    pyplot.plot([ops.at(i / 2).perf for i in range(n)],
  File "/home/PycharmProjects/faiss_exp/demo_auto_tune.py", line 48, in <listcomp>
    pyplot.plot([ops.at(i / 2).perf for i in range(n)],
  File "/home/PycharmProjects/faiss_exp/swigfaiss.py", line 390, in at
    return _swigfaiss.OperatingPointVector_at(self, *args)
TypeError: in method 'OperatingPointVector_at', argument 2 of type 'size_t'
```

I tried with other generated data as well; same error
It throws error after finding the optimal operating points
keys_mem_16 used

**Comment by mdouze** [comment]
Hi 
Use `n = int(sz / (4 * (d + 1)))`.

**Comment by Aashit-Sharma** [comment]
Hi , thanks for the reply
I did the change but am still getting the exact same error
I also tried out with my own custom data but am getting the same error

**Comment by Aashit-Sharma** [comment]
UPDATE: Tried with (small)custom generated data
Used the Index result of Brute force KNN as ground truth and it worked for IVFPQ (Or at least it didnt throw an error :smile: 

This was the output:
```
Tested 2 operating points, 2 ones are optimal:
cno=-1 key= perf=0.0000 t=0.000 
cno=515 key=nprobe=8,ht=512 perf=0.7600 t=0.008 
```

I have a few questions about this output:

1. What does it actually mean when it says tested 2 operating points? Is this output sensible ?
2. From what I read CNO is the index. So why is its value random ?
3. what does crit.nnn mean ?

4. This is an unrelated and basic question: say I have some data I want to put on an IVFPQ index. How do I obtain 'xt' from this data for training ?

Thanks !

**Comment by Aashit-Sharma** [comment]
nvm , It is working now. Thanks!
