### ISSUE TITLE
Floating point precision issue affecting normalisation of vectors

### ISSUE THREAD

**Issue by VSingh-ctrl** [facebookresearch/faiss#3979]
# Summary

Observed that cosine similarity is > 1 for some vectors. Tracing back the problem led to issue with L2 normalisation of vectors, floating point precision limitation is causing vectors to be not correctly normalised (verified by calculating the magnitude, it is not 1).
Is there a solution to this issue? One suggestion was to rescale the vectors, is there any effective way in faiss to do so?

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

**Comment by bshethmeta** [comment]
To better understand your flow, are you using normalize_L2() to normalize your vectors?

**Comment by VSingh-ctrl** [comment]
I am using "fvec_renorm_L2" to normalise the vectors.

**Comment by bshethmeta** [comment]
Can you provide a way to repo this?

**Comment by VSingh-ctrl** [comment]
I can provide an example vector on which fvec_renorm_L2 was used for normalisation:
* Original query vector = [82.0, 106.0, 20.0]
* Post renorm_L2 (calling it "norm1") = [0.60517013, 0.78229314, 0.14760247]
* On running renorm_L2 again, got the vector (calling it "norm2") = [0.6051702, 0.78229326, 0.14760248]

For both the "norm1" and "norm2" vector cosine similarity with normalised vector [0.6038481, 0.7827926, 0.1529601] is > 1 (1.0003815 for "norm2" and normalised vector).
