### ISSUE TITLE
Question on Optimized Product Quantization?

### ISSUE THREAD

**Issue by mucun1988** [facebookresearch/faiss#398]
A quick question. 

I am wondering whether the method proposed in  [“Optimized product quantization”](https://www.robots.ox.ac.uk/~vgg/rg/papers/ge__cvpr2013__optimized.pdf)  by T. Ge et al. (CVPR 2013) is implemented in FAISS or not.

Thanks,
Matt

**Comment by mdouze** [comment]
Hi 
Quick answer: https://github.com/facebookresearch/faiss/wiki/Pre--and-post-processing#pre-transforming-the-data

**Comment by mucun1988** [comment]
Dear @mdouze 

That's exactly what I am looking for!

Many thanks,
Matt

**Comment by yupbank** [comment]
The OPQ is implementing non parametric version or parametric version ?

**Comment by yupbank** [comment]
@mdouze it's the non parametric version right?

**Comment by beauby** [comment]
@yupbank Yes, it is the non parametric version.

**Comment by mucun1988** [comment]
So is there a way to call this optimized product quantization (like the way to use [faiss.ProductQuantizer() function](https://github.com/facebookresearch/faiss/wiki/Faiss-building-blocks:-clustering,-PCA,-quantization))?

Thanks,
Matt

**Comment by yupbank** [comment]
i think somewhere in LOPQ was mentioning non parametric doesn't scale well? what do you think of add a eigenvalue allocation version?

**Comment by mdouze** [comment]
Hi 
The eigenvalue allocation is implemented when setting `PCAMatrix::balanced_bins` to true. We have not tested it thoroughly though.

**Comment by yupbank** [comment]
nice, but since @skamalas also works for facebook now, does it make sense to help out here? i think he also do a lot of PQ, maybe add LOPQ and the latest `Locally Optimized Hashing ` here?

**Comment by mucun1988** [comment]
So is there a way to call this optimized product quantization (like the way to use faiss.ProductQuantizer() function)?

Thanks,
Matt

**Comment by skamalas** [comment]
@yupbank For now there are no plans for adding LOPQ/LOH in FAISS, I don't really have the time for this, sorry. 

In practice I remember I ended up using the parametric version almost everywhere for LOPQ, for efficiency (as the optimization happens locally at each coarse bin and therefore needs to be computed multiple times).
