### ISSUE TITLE
remove_ids through c++ interface

### ISSUE THREAD

**Issue by FlYWMe** [facebookresearch/faiss#399]
### When I want to remove ids through c++ interface ,it is failed.

```
faiss::IDSelector *idsel = 0;
idsel = reinterpret_cast<faiss::IDSelector *>(removeid);
long nremove = faissIndex->remove_ids((faiss::IDSelector const &)idsel);
```

**Comment by FlYWMe** [comment]
Hi,
Thank you very much for your timely reply. I was inspired and solved the problem.
    ```
    shared_ptr<faissSearch> index(new faissSearch("IDMap,Flat", d));
    index->add_with_ids(nb, xb.data(), xid.data()); // add vectors to the index
    cout<<"n:"<<index->ntotal<<endl; // n:nb
    faiss::IDSelectorRange ids(int(nb/2),nb);
    index->remove_ids(ids);
    cout<<"n:"<<index->ntotal<<endl; // n:nb/2
```

**Comment by FlYWMe** [comment]
Hi,
Thank you very much for your timely reply. I was inspired and solved the problem.

```
shared_ptr index(new faissSearch("IDMap,Flat", d));
index->add_with_ids(nb, xb.data(), xid.data()); // add vectors to the index
cout<<"n:"<ntotal<<endl; // n:nb
faiss::IDSelectorRange ids(int(nb/2),nb);
index->remove_ids(ids);
cout<<"n:"<ntotal<<endl; // n:nb/2
```

**Comment by zhongyu2013** [comment]
Hi, quick question, do you know how I should use IDSelectorBatch in C++ since there is no example anywhere online? Thanks!

**Comment by husterlantern1** [comment]
> Hi, quick question, do you know how I should use IDSelectorBatch in C++ since there is no example anywhere online? Thanks!

Hi, do you know how to use IDSelectorBatch in C++ now ? Or do you know some examples about IDSelectorBatch in C++? Thanks!

**Comment by mdouze** [comment]
The example above should work.
