### ISSUE TITLE
Question: Executing FAISS inside an iOS/Android application

### ISSUE THREAD

**Issue by Aashit-Sharma** [facebookresearch/faiss#402]
# Question
Is it possible to call functions from the compiled Faiss files from within an app (or in an environment/OS that is different than what the FAISS files were compiled in) ?

If not ,is there a way to compile Faiss files to execute in an iOS environment ? 
Thanks!

**Comment by beauby** [comment]
You'd need to cross-compile Faiss for the target platform, which may need slight tweaks of parts of the code, but it is technically possible. Feel free to submit a PR!

**Comment by Aashit-Sharma** [comment]
But I can't find an option to compile faiss for iOS. Will MacOS compiled FAISS work in iOS ?

**Comment by beauby** [comment]
Ref for people interested in running Faiss on iOS: https://github.com/facebookresearch/faiss/projects/3.

**Comment by Aashit-Sharma** [comment]
@beauby Thanks for creating a project. I will try to do it myself. 

For others , I found this : https://github.com/szanni/ios-autotools

Haven't tried it yet but looks promising

**Comment by Aashit-Sharma** [comment]
A few more cross compile libraries :
https://github.com/libimobiledevice/libimobiledevice

https://github.com/tpoechtrager/cctools-port/
hope it helps

**Comment by Zumbalamambo** [comment]
+1
