### ISSUE TITLE
unable to install faiss-gpu on windows 11 -- python 3.12.0 -- pytorch 2.5.0+cu118

### ISSUE THREAD

**Issue by MohammadParsaTheFirst** [facebookresearch/faiss#4043]
Well i have tried to install faiss using `pip install faiss-gpu` and `pip install faiss-gpu-cu11` and i always get the same error which is:

ERROR: Could not find a version that satisfies the requirement faiss-gpu-cu11 (from versions: none)
ERROR: No matching distribution found for faiss-gpu-cu11

I would highly appreciate it if someone could help me.
Thanks,

**Comment by mnorris11** [comment]
Hi @MohammadParsaTheFirst please try the install directions in https://github.com/facebookresearch/faiss/blob/main/INSTALL.md to install with conda

**Comment by MohammadParsaTheFirst** [comment]
Thanks for your reply
I did the same with conda and it worked.

Best regards
