### ISSUE TITLE
Got an error when test

### ISSUE THREAD

**Issue by XiaXuehai** [facebookresearch/faiss#406]
# Platform

OS: Red Hat 4.8.5-16

Faiss version: 2.1
 Faiss compilation options: using Openblas with compile flags

Running on :
- [x] CPU

# Reproduction instructions

I can import faiss successfully.But I cannot run this

```
[root@ai-algorithm home]# python -c "import faiss, numpy
faiss.Kmeans(10, 20).train(numpy.random.rand(1000, 10).astype('float32'))"
Traceback (most recent call last):
  File "<string>", line 2, in <module>
AttributeError: module 'faiss' has no attribute 'Kmeans'
```

But when I run the commend line in the ./faiss/ file  is ok.

**Comment by beauby** [comment]
When you do `import faiss` from a path that contains a `faiss` subdirectory, it will load that instead of the installed python module.

**Comment by beauby** [comment]
What error are you getting?
