### ISSUE TITLE
Feature request: linux/arm64 support

### ISSUE THREAD

**Issue by joziahmays** [facebookresearch/faiss#4073]
Hey, my team is trying to build and run a Docker image on a linux/arm64 machine (running Ubuntu), but we cannot do so due to incompatibility issues with `faiss`. We depend on `faiss` via [sqlite-vss](https://github.com/asg017/sqlite-vss). Below are the errors we're seeing:

```
[  0%] Building CXX object vendor/faiss/faiss/CMakeFiles/faiss_avx2.dir/AutoTune.cpp.o
c++: error: unrecognized command-line option '-mavx2'
c++: error: unrecognized command-line option '-mfma'
c++: error: unrecognized command-line option '-mf16c'
c++: error: unrecognized command-line option '-mpopcnt'
```

I assume the culprit is [here](https://github.com/facebookresearch/faiss/blob/2483feaba5da29c2b8a3c63b8e99da131007b919/faiss/CMakeLists.txt#L249-L251). From quick research, the options above look like x86-specific compiler options. If that's true, that makes sense as to why our builds are failing. 

Do you all have any tips on how to avoid this issue, by chance? Thank you!

**Comment by alexanderguzhva** [comment]
@joziahmays faiss supports arm64 (neon and sve), for example https://github.com/facebookresearch/faiss/blob/2483feaba5da29c2b8a3c63b8e99da131007b919/faiss/CMakeLists.txt#L282
Also, please check INSTALL.md file

**Comment by joziahmays** [comment]
thanks for reaching back out @alexanderguzhva! It seems that faiss_sve does indeed support arm64, however, what's causing issues is faiss_avx512: https://github.com/facebookresearch/faiss/blob/2483feaba5da29c2b8a3c63b8e99da131007b919/faiss/CMakeLists.txt#L261-L273

should there still be extra logic here to conditionally exclude those flags for `linux/arm64`? I was able to successfully build an image on my local MacBook (`darwin/arm64` via M3 chip) but not on a `linux/arm64` machine. Please correct me if I'm wrong. Thanks!

**Comment by joziahmays** [comment]
thanks for reaching back out @alexanderguzhva! After reading the INSTALL.md file, we can try playing around with env vars. Thanks again! Will reach back out if we run into any issues.

**Comment by joziahmays** [comment]
hey @alexanderguzhva I'm just a bit confused. Just looking at the logic, it looks like the following check will always be evaluated which is breaking builds specifically on `linux/arm64`: https://github.com/facebookresearch/faiss/blob/2483feaba5da29c2b8a3c63b8e99da131007b919/faiss/CMakeLists.txt#L249-L251

should there not be more logic to check if the arch is `linux/arm64`, `darwin/arm64`, etc.? Or, shouldn't we only add these flags if we've enabled `AVX` via the `FAISS_OPT_LEVEL` env var?

**Comment by alexanderguzhva** [comment]
@joziahmays I'm not sure I follow.
I've just downloaded a master branch of faiss on my ubuntu 22.04 LTS AWS Graviton 3 machine, then run
```bash
cmake -DFAISS_ENABLE_GPU=OFF -DFAISS_ENABLE_PYTHON=OFF -DCMAKE_BUILD_TYPE=Release -B build -G Ninja .
cd build
ninja
```
And I've got everything compiled
```
ubuntu@ip-172-31-5-152:~/zilliz/faiss_arm/faiss$ 
ubuntu@ip-172-31-5-152:~/zilliz/faiss_arm/faiss/build$ ninja
[161/161] Linking CXX executable tests/faiss_test
WARNING clustering 1000 points to 40 centroids: please provide at least 1560 training points
```

**Comment by joziahmays** [comment]
Actually, my team no longer depends on the library that uses this one, but thanks a ton for the help, and my apologies for the confusion.

To close the loop on this: I've tried everything on my graviton instance but to no avail.
