### ISSUE TITLE
https://pypi.org/project/faiss/ doesn't contain 1.9.0

### ISSUE THREAD

**Issue by yurivict** [facebookresearch/faiss#4077]
# Summary
https://pypi.org/project/faiss/ appears to be for the same project but the version there is many years old.

**Comment by ramilbakhshyiev** [comment]
Hi @yurivict, pip installation is not officially supported, however, you can try these packages supported by external contributors:
https://pypi.org/project/faiss-cpu/
https://pypi.org/project/faiss-gpu/
https://pypi.org/project/faiss-gpu-cu12/
