### ISSUE TITLE
[Repetition ids]: add data into trained index

### ISSUE THREAD

**Issue by Suntester** [facebookresearch/faiss#409]
Hi

When I load an trained index from disk, 
1. add 10 vectors into it (actually, this index was empty before) 
query index - the result ids is **[[9 1 2 3 4 5 6 0 8 7]]**
2. remove 2 ids from this index (so index includes 8 ids)
3. add 2 vectors into it again. (I found new 2 ids has come up before)
query index - the result ids is **[[9 8 2 3 4 5 6 9 8 7]]**

I am not sure whether it's a bug.  If no, so how do I get just like index ids "[[9 **10** 2 3 4 5 6 **11** 8 7]]" rather than [[9 8 2 3 4 5 6 9 8 7]]? I think ids should be increasing from current maximum id. 

Thanks in advance.
```
import faiss
import numpy as np

res = faiss.StandardGpuResources()
co = faiss.GpuClonerOptions()
co.useFloat16 = True
co.usePrecomputed = False

# index = faiss.index_factory(d, "IVF128,PQ32")
index_cpu = faiss.read_index('test.index')
index_gpu = faiss.index_cpu_to_gpu(res, 0, index_cpu, co)

# dimension
d = 128
# generate base data
for i in range(1):
    xb = np.random.random((10, d)).astype('float32')
    index_gpu.add(xb)

# one query data
xq = np.random.random((1, d)).astype('float32')

# search all index
# search before remove ids
nprobe = 128
index_gpu.setNumProbes(nprobe)
D, I = index_gpu.search(xq, 10)
# print(D)
print(I)
# [[9 1 2 3 4 5 6 0 8 7]]

index_cpu = faiss.index_gpu_to_cpu(index_gpu)
print('start to remove ids')
index_cpu.remove_ids(np.arange(2))

# add data again after remove ids
index_gpu = faiss.index_cpu_to_gpu(res, 0, index_cpu, co)
index_gpu.add(np.random.random((2, d)).astype('float32'))

# search after add new data
index_gpu.setNumProbes(nprobe)
D, I = index_gpu.search(xq, 10)
# print(D)
print(I)
# [[9 8 2 3 4 5 6 9 8 7]]
```

**Comment by Suntester** [comment]
anyone can help on this ?  Thanks.

**Comment by FlYWMe** [comment]
The index you want to add cannot be repeated by default. 
You can try another index type "IDMap, flat".

**Comment by Suntester** [comment]
@FlYWMe thanks to your reply. 
I built the index using 'IVF128,PQ32' and want to keep the index structure,  and I understand you mean the index type  'IVF128,PQ32'  cause above situation is normal. Am I right ? 
By the way, can index 'IVF128,PQ32' convert to index "IDMap, flat" ? 
Thanks

**Comment by FlYWMe** [comment]
@Suntester You're welcome, I  have not researched faiss for a long time.
In my understanding, yes, you are right. But you should not to convert the index type. Different index using different searching method, the index structure is completely different, the  'IVF128,PQ32' using  IVFADC (coarse quantizer+PQ on residuals) but the "IDMap, flat" using exact search method. However, only the "IDMap, flat" index support add_with_ids. So I suggest you add ids different from others.
You can read Faiss indexes pages in faiss WIKI  :)

**Comment by wickedfoo** [comment]
Remove is not currently implemented on GPU.

**Comment by Suntester** [comment]
@wickedfoo Thanks for your reply.
even if using the index type "IDMap, flat", it can support both add and remove ids operation for only CPU mode. Is it correct ?

**Comment by beauby** [comment]
@Suntester Right, no index has `remove()` implemented on GPU. Closing this.
