### ISSUE TITLE
What is the difference between index_cpu_to_all_gpus() and index_cpu_to_gpu_mutiple()?

### ISSUE THREAD

**Issue by o0fatigue** [facebookresearch/faiss#410]
# Summary

As is said in the title, I am not clear what is the difference between this two methods and which one I should use. These two methods are both mentioned in the wiki.

I was building index on 2 Tesla P40, and I have tried run `index_cpu_to_all_gpus()`, and when I ran `index.add()`, it returned an error of failure on `cudaMalloc()`. 

However,  I was totally able to build the index on only one GPU by `index_cpu_to_gpu()`. This is confusing.

And I have not yet tried build by `index_cpu_to_gpu_mutiple()`.

By the way, will it give better performance if load query matrix into GPU via PyTorch?

Any information will be appreciated. Thank you.

# Platform

OS: CentOS 7.2.1511

Faiss version: 0.1

Faiss compilation options: 

Running on :
- [ ] CPU
- [x] GPU

# Reproduction instructions

**Comment by mdouze** [comment]
Hi 
Both functions map to 
https://github.com/facebookresearch/faiss/blob/master/gpu/GpuAutoTune.h#L33
the only difference is that they a slightly easier to use.

The loading of the query matrix is usually negligible wrt. to computation time, so it is not worth the effort. 

For the `cudaMalloc` problem, please submit a detailed bug report.

**Comment by o0fatigue** [comment]
Okay. Thanks a lot. I will try a few days later, and I may submit a more detailed report, if I cannot handle it by myself.
