### ISSUE TITLE
Can the index file generated in version 1.7.4 be used in version 1.9.0

### ISSUE THREAD

**Issue by rose839** [facebookresearch/faiss#4102]
# Summary

I generated a vector index file using the following C++code on Faiss version 1.7.4:

```
faiss::IndexFlatL2 indexa = faiss::IndexFlatL2(d);
faiss::IndexIVFScalarQuantizer index = faiss::IndexIVFScalarQuantizer(&indexa,d,nlist,faiss::ScalarQuantizer::QuantizerType::QT_8bit); 

index.train(len,vdatas);
index.add(len,vdatas);

faiss::write_index(&index, "ivfsq8.index");
```

Can I load and use the generated index file "ivfsq8.index" on Faiss version 1.9.0？

# Platform

OS: linux

Faiss version: 1.7.4 1.9.0

Installed from: compiled by myself

Faiss compilation options: ignore

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions
ignore

**Comment by mnorris11** [comment]
Hi @rose839, does this not work for you? 

index_read and index_write have to be backwards compatible. If a field is removed then it has to read/write a dummy, like in https://github.com/facebookresearch/faiss/pull/3692.

**Comment by rose839** [comment]
I did a simple test, it works between 1.7.4 and 1.9.0。Thank you very much。
