### ISSUE TITLE
Windows OS: Linker errors when using faiss with go

### ISSUE THREAD

**Issue by DeepakKarMW** [facebookresearch/faiss#4108]
# Summary
I am trying to use [bleve](https://github.com/blevesearch/bleve) and faiss for vector search. For this, I first used Linux and was able to build faiss first, then copy the .so files and build the go program to perform vector search.

Next, I tried doing the same on Windows and am running into linker errors when building the same go code that worked on Linux. I tried to investigate some more and it looks like `faiss_c.lib` is not generated. Also the faiss_c.dll does not seem to have these functions exported.

Some errors:
C:/msys64_new/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\dkar\AppData\Local\Temp\go-link-917172968\000013.o:index.cgo2.c:(.text+0x3b0): undefined reference to `faiss_Index_is_trained'
C:/msys64_new/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\dkar\AppData\Local\Temp\go-link-917172968\000013.o:index.cgo2.c:(.text+0x410): undefined reference to `faiss_Index_merge_from'
C:/msys64_new/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\dkar\AppData\Local\Temp\go-link-917172968\000013.o:index.cgo2.c:(.text+0x45d): undefined reference to `faiss_Index_metric_type'
C:/msys64_new/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\dkar\AppData\Local\Temp\go-link-917172968\000013.o:index.cgo2.c:(.text+0x4aa): undefined reference to `faiss_Index_ntotal'

Could you please let me know if there are existing solutions or patches that address this issue?

# Platform

Windows 11

OS: 

Faiss version: latest of main, https://github.com/blevesearch/faiss/tree/b747c55a93a9627039c34d44b081f375dca94e57

Installed from: compiled myself  

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions
 cmake -B build -G "Visual Studio 17 2022" -A x64 -DFAISS_ENABLE_GPU=OFF -DFAISS_ENABLE_C_API=ON -DBUILD_SHARED_LIBS=ON -DFAISS_ENABLE_PYTHON=OFF -DCMAKE_CXX_FLAGS="-I L:\faiss" -DBUILD_TESTING=OFF
cmake --build build --config Release
I have also installed these using the following and setup ld and cgo flags when building my `main.go`
 cmake --build build --target install --config Release --verbose

I don't know if this will help but here is my `main.go`, I have
```go
//go:build vectors
// +build vectors

/*
#cgo LDFLAGS: -LC:/faiss/lib -lfaiss_c
#cgo CFLAGS: -IC:/faiss/include
#include <faiss/c_api/faiss_c.h>
*/
package main

import "C"

import (
	"fmt"
	"log"
	"os"

	"github.com/blevesearch/bleve/v2"
	"github.com/blevesearch/bleve/v2/mapping"
	"github.com/blevesearch/bleve/v2/search/query"
)

func main() {
	// Delete example.bleve folder before starting
	if err := os.RemoveAll("example.bleve"); err != nil {
		log.Printf("Error deleting example.bleve folder: %v", err)
	}

	// Define multiple documents with vector fields
	docs := []struct {
		Id   string    `json:"id"`
		Text string    `json:"text"`
		Vec  []float32 `json:"vec"`
	}{
		{Id: "doc1", Text: "hello from united states", Vec: []float32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}},
		{Id: "doc2", Text: "greetings from canada", Vec: []float32{10, 11, 12, 13, 14, 15, 16, 17, 18, 19}},
		{Id: "doc3", Text: "bonjour from france", Vec: []float32{20, 21, 22, 23, 24, 25, 26, 27, 28, 29}},
		{Id: "doc4", Text: "hola from spain", Vec: []float32{5, 4, 3, 2, 1, 0, 9, 8, 7, 6}},
		{Id: "doc5", Text: "ciao from italy", Vec: []float32{9, 8, 7, 6, 5, 4, 3, 2, 1, 0}},
	}

	// Define the text field mapping
	textFieldMapping := mapping.NewTextFieldMapping()

	// Define the vector field mapping
	vectorFieldMapping := mapping.NewVectorFieldMapping()
	vectorFieldMapping.Dims = 10
	vectorFieldMapping.Similarity = "cosine" // Euclidean distance

	// Create an index mapping
	bleveMapping := mapping.NewIndexMapping()
	bleveMapping.DefaultMapping = mapping.NewDocumentMapping()
	bleveMapping.DefaultMapping.Dynamic = false
	bleveMapping.DefaultMapping.AddFieldMappingsAt("text", textFieldMapping)
	bleveMapping.DefaultMapping.AddFieldMappingsAt("vec", vectorFieldMapping)

	// Create a new index
	index, err := bleve.New("example.bleve", bleveMapping)
	if err != nil {
		log.Fatal(err)
	}

	// Index the documents
	for _, doc := range docs {
		err = index.Index(doc.Id, doc)
		if err != nil {
			log.Fatal(err)
		}
	}

	// Create a search request with KNN
	searchRequest := bleve.NewSearchRequest(query.NewMatchNoneQuery())
	searchRequest.AddKNN(
		"vec", // Vector field name
		[]float32{10, 11, 12, 13, 14, 15, 16, 17, 18, 19}, // Query vector (ensure this is also 10-dimensional)
		5,   // k (number of nearest neighbors)
		1.0, // Boost (try setting it to 1.0)
	)

	// Execute the search
	searchResult, err := index.Search(searchRequest)
	if err != nil {
		log.Fatal(err)
	}

	// Print the search results
	fmt.Println("KNN search results:")
	for _, hit := range searchResult.Hits {
		fmt.Printf("Document ID: %s, Score: %f\n", hit.ID, hit.Score)
	}
}
```

**Comment by mengdilin** [comment]
@DeepakKarMW C_API is not supported on windows for FAISS officially. We do have enthusiasts that created wrappers of c_api that works on windows if you take a look at a past issue https://github.com/facebookresearch/faiss/issues/2909#issuecomment-1606472157 which points to `FaissMask`: https://github.com/andyalm/faissmask

Perhaps give that a try?
