### ISSUE TITLE
Retrieve vector at index

### ISSUE THREAD

**Issue by Feynman27** [facebookresearch/faiss#412]
# Summary
Is there a method to retrieve the n-dimensional vectors at the indexes returned by `index.search`?

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on :
- [ ] CPU
- [X ] GPU

# Reproduction instructions

**Comment by wickedfoo** [comment]
`reconstruct` is meant to do this, but on GPU it is only implemented on GpuIndexFlat, not the other indices.

Also note that for the PQ indices, the vector returned is a reconstruction of the original vector with the PQ quantization, not the original vector itself.
