### ISSUE TITLE
WINDOWS VERSION OF FAISS BEING AWATED

### ISSUE THREAD

**Issue by Anurag27031994** [facebookresearch/faiss#415]
WINDOWS VERSION OF FAISS IS STILL BEING AWAITED. EXCITED FOR THE DAY OF LAUNCH.

**Comment by jegou** [comment]
See issues #43 and #334 

Note that, as mentioned in #43 , we do not use or have easy access to Windows machines, and supporting Linux and Mac is already difficult. 

we have opened a project about porting to Windows. If you want to contribute, you are most welcome!

**Comment by mohammedayub44** [comment]
Any update on this project ?

**Comment by qhungngo** [comment]
Any update for WINDOWS version?
