### ISSUE TITLE
Serialization support for IndexIDMap

### ISSUE THREAD

**Issue by madisonmay** [facebookresearch/faiss#42]
When trying to serialize a faiss.IndexIDMap instance, I get the following exception:

```
Faiss assertion !"don't know how to serialize this type of index"
```

Reading through your source, it looks like there simply isn't a conditional block that describes how to serialize an IndexIDMap instance to disk.  How you would recommend persisting an IndexIDMap? Is there a timeline for supporting passing IndexIDMap instances to `faiss.write_index`?

**Comment by mdouze** [comment]
Hi!

Yes, serialization of `IndexIDMap` is not implemented currently, serialization support is a bit "lazy" in the sense that we do it for an index type when it is needed. 

I will not have time to work on this soon but if you implement it I'll be happy to accept the diff. You just need to pick an unused 4 character code (fourcc) and implement the relevant `read_index`/`write_index` blocks.

**Comment by madisonmay** [comment]
Thanks for the explanation.  For the moment I've decided to simply maintain my own id mapping, as I likely don't have the time to implement support for this feature myself, but I appreciate the swift response. In the off chance that I do get around to implementing this functionality I'll definitely submit a PR.

**Comment by mdouze** [comment]
Implemented in current version.

**Comment by madisonmay** [comment]
Thanks @mdouze!
