### ISSUE TITLE
Inefficient multi-core usage

### ISSUE THREAD

**Issue by yuzhichang** [facebookresearch/faiss#422]
# Summary

faiss OMP and multi-thread just waste CPU.

# Platform

OS: CentOS 7.5, openblas

Faiss version: ed809ce183ba549b4e87c15ab9ab86db05e8bcec

Running on :
- [X] CPU

# Reproduction instructions

I have a PC with CentOS 7.5 x86_64, openblas installed. The CPU is 4 core(8 super-thread), Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz.
I measured demo_sift1M (index_key: "IVF4096,PQ32") search time with different OMP settings:

- omp_set_num_threads(1); 26s
- omp_set_num_threads(2); 14s
- omp_set_num_threads(4); 10.4s
- omp_set_num_threads(8); 6.3s

Then I disabled OMP with 
`omp_set_num_threads(1); `
Use c++17 multiple threads to do concurrent search.

- 1 thread, 26s
- 2 threads, 6s 
- 4 threads, 6s
- 8 threads, 6s

From above numbers, I conclude that
- multi-thread outperforms OMP if with the same CPU usage quota.
- 2 threads is golden config. More threads just waste CPU.

I retest it on an workstation with the everything the same, and got the same conclusion.
The CPU of the workstation: 48 cores, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz

**Comment by beauby** [comment]
@yuzhichang As mentioned in the [Troubleshooting](https://github.com/facebookresearch/faiss/wiki/Troubleshooting#slow-brute-force-search-with-openblas) you should set `OMP_WAIT_POLICY=PASSIVE` when using OpenBLAS to avoid this issue.

**Comment by yuzhichang** [comment]
@beauby The openblas I'm using (openblas-0.2.20-6.el7.x86_64) is single thread version, build with USE_THREAD=0. And I tried OMP_WAIT_POLICY=PASSIVE, doesn't help.

**Comment by yuzhichang** [comment]
I noticed that `omp_set_num_threads(1)` doesn't disable OMP, The OMP spec says "Sets the number of threads that will be used in the **next parallel region**" The correct way is 

- `setenv OMP_THREAD_LIMIT 1`.
- or remove all `pragma omp` lines from source code.

I retest with all `pragma omp` removed:
Use c++17 multiple threads to do concurrent search.

- 1 thread, 26s
- 2 threads, 13.2s
- 4 threads, 7.2s
- 8 threads, 6s

The result is much reasonable.

**Comment by beauby** [comment]
@yuzhichang According to the spec:
> Affects the number of threads used for subsequent parallel **regions**.

**Comment by beauby** [comment]
Reference: http://www.openmp.org/wp-content/uploads/OpenMP-4.5-1115-CPP-web.pdf
