### ISSUE TITLE
Creating an exact inner product index with the index_factory method in python

### ISSUE THREAD

**Issue by will-ockmore-axomic** [facebookresearch/faiss#423]
# Summary
Using the `index_factory` in python, I'm not sure how you would create an exact index using the inner product metric. According to [this page](https://github.com/facebookresearch/faiss/wiki/Faiss-indexes) in the wiki, the index string for both is the same. I already added some vectors to an exact index (it also uses PCA pretransform) using the L2 metric, then tried changing the metric type on the index itself - the distance results were the same before and after. Do I need to create and train the index, then change the metric type before adding any vectors?

# Platform

OS: Linux

Faiss version: v1.2.1

Faiss compilation options: installed with Conda

Running on :
- [x] CPU
- [ ] GPU

# Reproduction instructions

N/A

**Comment by Enet4** [comment]
[`index_factory`](https://github.com/facebookresearch/faiss/blob/master/AutoTune.h#L204) takes a second optional argument for the metric type. I believe the Python bindings would pass the parameter through with something like this:

```python
index = faiss.index_factory(16, "Flat", faiss.METRIC_INNER_PRODUCT)
```

**Comment by beauby** [comment]
Closing this, as @Enet4 solved it. Feel free to keep commenting if you have related questions.

**Comment by AmberLJC** [comment]
So only " Flat " and "PQ" can support Inner_product_distance ?
If I use Inner_product_distance , will the ground truth be different?
If yes, should I normalize the vector when I calculate the ground truth?
