### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by njsys** [facebookresearch/faiss#43]
Hi
Is there a windows port for this?
or 
any effort done externally that provides instructions for how to build this on windows (using visual studio)?

Thanks

**Comment by jegou** [comment]
Dear @njsys 
We have no plan to support Faiss for Windows in a foreseeable future.

**Comment by mdouze** [comment]
Hi @njsys 

To give a bit more of context: we do not use or have easy access to Windows machines, and supporting Linux and Mac is already difficult. I opened a project about porting to Windows. If you want to contribute, you are most welcome!

**Comment by BeginnerW** [comment]
I also want to know how to build faiss on windows.
