### ISSUE TITLE
Get less than k centroids using Kmeans function

### ISSUE THREAD

**Issue by Ken2yLiu** [facebookresearch/faiss#436]
# Summary

I try to use faiss.Kmeans in Python2.7 to cluster 249 data points with 512 dimensions into k=2 clusters, but I get only 1 cluster result. What cause this and how to solve it?

# Platform

OS: Ubuntu 16.04

Faiss version: git commit, 1ae7494491ecc3f13299e217ea466030980f4a70

Faiss compilation options: docker build -f Dockerfile .

Running on :
- [x] CPU
- [ ] GPU

# Reproduction instructions
code snippet:
    d = data.shape[1]
    clus = faiss.Kmeans(d, 2, d, True)
    clus.train(data)

terminal print:
Clustering 249 points in 512D to 2 clusters, redo 1 times, 512 iterations
    Preprocessing in 0.00s
    Iteration 511 (0.11s, search 0.09s): objective=0.52617, imbalance=2.000 nsplit=1

**Comment by mdouze** [comment]
Hi 
Please check if the 249  points are not all identical.

**Comment by Ken2yLiu** [comment]
Well, I use np.unqiue() to check the 249 points, find that actually there are just 2 points. But why can't it return 2 clusters with one point each?

**Comment by mdouze** [comment]
Don't you think this is a little bit of a corner case ? :-)

**Comment by Ken2yLiu** [comment]
Well, as I am building a hierarchical KMeans using faiss KMeans as backend, so I need to cover all the case that may happend. Anyway, I fix that by just checking if the unique points number is more than the k parameter, otherwise, I terminate that node in hierarchical processing. Thx!
