### ISSUE TITLE
Please perfect the interface file

### ISSUE THREAD

**Issue by Tony-Hou** [facebookresearch/faiss#437]
# Summary

# Platform
Could you to perfect the interface ? please give the function parameter list detaile information,
otherwiese we don't clearly to use them. thanks

for example:
please explain the na, nb instead for what ?
def hammings(a, b, na, nb, nbytespercode, dis):
    return _swigfaiss.hammings(a, b, na, nb, nbytespercode, dis)

/* compute the Hamming distances between two codewords of nwords*64 bits */
hamdis_t hamming (
        const uint64_t * bs1,
        const uint64_t * bs2,
        size_t nwords);

OS: 

Faiss version: 

Faiss compilation options: 

Running on :
- [ ] CPU
- [ ] GPU

# Reproduction instructions

**Comment by mdouze** [comment]
Hi 
This is documented in the C++ code see
https://github.com/facebookresearch/faiss/blob/master/hamming.h#L46
There is an open issue #393 about converting the doxygen to docstrings but we have not figured out how to do it.
