### ISSUE TITLE
How to search the nearest  with hamming distance rather than L2 distance?

### ISSUE THREAD

**Issue by Tony-Hou** [facebookresearch/faiss#438]
# Summary

# Platform
I want  to search the nearest  with the hamming distance.
OS: 

Faiss version: 

Faiss compilation options: 

Running on :
- [ ] CPU
- [ ] GPU

# Reproduction instructions

**Comment by mdouze** [comment]
Binary vectors are not fully supported yet. See 
https://github.com/facebookresearch/faiss/blob/master/tests/test_index.py#L496
for a workaround, but it is not  optimal.

**Comment by zhihuizheng** [comment]
Is there a tutorial for hamming distance?

**Comment by 0ZhangJc0** [comment]
Is there a tutorial for hamming distance?
