### ISSUE TITLE
How to do with a big database with faiss?

### ISSUE THREAD

**Issue by XiaXuehai** [facebookresearch/faiss#441]
I am new about faiss.

There are 2 million vectors in my database.I can't read all of them to RAM,and it also can't read so big data to python `np.ndarray`.
So how to train the data by faiss?

```
index = faiss.index_factory(d, "IVF100,Flat")
index.train(xb)
index.add(xb)
for i in range(20):
	index.train(xbi)
	index.add(xbi)
```
is it above all right?

**Comment by xichen714** [comment]
maybe u can use fromfile/memmap as suggested in this script?
https://github.com/facebookresearch/faiss/blob/master/benchs/bench_polysemous_1bn.py

**Comment by XiaXuehai** [comment]
@xichen714 THX.but np.ndarray don't allow so big of data with the type of float. it's out of memory.

Can I read and train the mini-data time by time,Like the code above?

**Comment by burk** [comment]
Yes you can, but you don't need to re-train the index on each batch. Train your index on a subset of the data (for example the first batch), then add the rest of the batches

    index.train(batch[0])
    for i in range(20):
        index.add(batch[i])

**Comment by XiaXuehai** [comment]
Thank you.@burk

**Comment by XiaXuehai** [comment]
@burk ，thanks a lot. Can you tell me what's the difference between `index.train(x0)` and `index.add(x1)`. Why they can be different?

**Comment by burk** [comment]
You've chosen a IVF100 index. I don't know the details, but I think this gives you an index with 100 clusters. The training `index.train(x0)` will find good parameters for these clusters. After that, your index is still empty. Then you do `index.add(x0)` and your index contains all the items in `x0`.

You _can_ train on the same data that you add to the index later. You _should_ train on some data that has the same properties as the data you add later (the same distribution in space).

The different index types have different requirements for how large the training set optimally should be.

You just need to test how it works for your use case and measure the performance parameters you're interested in.

**Comment by beauby** [comment]
Closing this, as the issue has been addressed. Feel free to keep commenting if you have further questions.

**Comment by reshu-b7** [comment]
Hi @mdouze, 

How can I reproduce the results from [Indexing-1M-vectors](https://github.com/facebookresearch/faiss/wiki/Indexing-1M-vectors) for threading and batching,  specifically `nobatch/nobatch_nt1: queries are submitted 1 by 1`

As described in the wiki, it would be something on the lines of "providing queries one by one". Will this logic suffice for the proposed benchmarking "IVF16834 nobatch" or there is more to it. 

```
t0 = time.time()
for i in range(len(xq)):
    D, I = index.search(xq[i], 100)
    i1 = i + 1
    I[i:i1] = I 
    D[i:i1] = D 
t1 = time.time()

```

It'll be great if you can provide information about the same for CPU implementations.

Thanks for all your help.

**Comment by mdouze** [comment]
That should be work, please add `faiss.omp_set_num_threads(1)` just to make sure.

**Comment by reshu-b7** [comment]
Hi @burk @XiaXuehai 

How can I read a big database (in .bin or .txt format) into a 2D base/query array for C++ using the same memmap technique as used in python?
I am relatively new to C++ and its been a little hard to figure out. Can you please provide some suggestions as benchmarking scripts for c++ are very few.


Thanks

**Comment by lalitpagaria** [comment]
@burk Is checking `is_trained` will be good? like this -
```
for i in range(20):
    if not index.is_trained:
        index.train(batch[i])
    index.add(batch[i])
```
