### ISSUE TITLE
What's the mean of fraction  in 1-recall@1?

### ISSUE THREAD

**Issue by XiaXuehai** [facebookresearch/faiss#447]
> accuracy. We use the //1-NN recall @R// measure with R=1, 10, or 100. This is the fraction of query vectors where the actual nearest-neighbor is ranked in the R first results.

I think the fraction  means the probability of  the nearrest vector returned,when searching 1 vector in the data.Does it right?

**Comment by beauby** [comment]
For details, please refer to [the article](https://hal.inria.fr/inria-00514462v2/document).

**Comment by reshu-b7** [comment]
Hi @beauby 
Hi @XiaXuehai 


Can you please clarify the difference between recall@1 and 1-recall@1? I went through the paper and its clearly says that 1-recall@ is precision. But some of the demo scripts in faiss repository perform a slight confusing evaluation.

For instance the `bench_gpu_sift1m.py` says it provides the recall@r measures whereas the `bench_gpu_1bn.py` says it provides 1-recall@r quality measure, but upon looking the script for both, the evaluation part seems to be doing the same thing.


`bench_gpu_sift1m.py`
```
D, I = index.search(xq, 100)
print "nprobe=%4d %.3f s recalls=" % (nprobe, t1 - t0),
    for rank in 1, 10, 100:
        n_ok = (I[:, :rank] == gt[:, :1]).sum()
        print "%.4f" % (n_ok / float(nq)),
    print
```


`bench_gpu_1bn.py`
```
print "  probe=%-3d: %.3f s" % (nprobe, t1 - t0),
            gtc = gt_I[:, :1]
            nq = xq.shape[0]
            for rank in 1, 10, 100:
                if rank > nnn: continue
                nok = (I[:, :rank] == gtc).sum()
                print "1-R@%d: %.4f" % (rank, nok / float(nq)),
            print
```

**Comment by mdouze** [comment]
Hi 
There is no difference. For SIFT1M, BIGANN and Deep1B, it is always 1-recall@rank that is computed.
