### ISSUE TITLE
Can I save my PCA matrix?

### ISSUE THREAD

**Issue by FeSens** [facebookresearch/faiss#451]
I've trained a PCA matrix, can I dump it to a file and load it latter?
I'm using python. 
Thanks.

**Comment by FeSens** [comment]
Yes, turns out that you can.
```
PCA = faiss.PCAMatrix(2048,256)
faiss.write_VectorTransform(PCA, "PCA.pca")
PCA2 = faiss.read_VectorTransform("PCA.pca")
```

**Comment by ducbluee** [comment]
so the matrix are not PCA matrix, can I dump it into a file and load it later?
I am using python.
Thank you.
