### ISSUE TITLE
CUDA error 30

### ISSUE THREAD

**Issue by qq932546734** [facebookresearch/faiss#454]
# Summary
I followed the instruction in INSTALL.md, also passed tests in step 1 and step2. But when I try to run the GPU demo: `python demos/demo_auto_tune.py `, I got an error:
```
load data
load GT
prepare criterion
============ key PCA64,IVF4096,Flat
Faiss assertion 'err__ == cudaSuccess' failed in virtual void faiss::gpu::StandardGpuResources::initializeForDevice(int) at StandardGpuResources.cpp:134; details: CUDA error 30
Aborted (core dumped)
```

I also tried `python2 benchs/bench_gpu_sift1m.py `, which ends with the same error.
I have checked settings of my CUDA and NVCC. CUDA is version 9.0, CUDA compiler version is 7.5. 
If any other settings need to be provided, let me know. Thanks!

# Platform

OS: Linux, ubuntu 16

Faiss version: the newest

Faiss compilation options: using Openblas with compile flags, installed on python2.7, with gpu 

Running on:
-  GPU： 1080Ti, 12GB

**Comment by beauby** [comment]
@wickedfoo Any idea what might be the cause here?

**Comment by wickedfoo** [comment]
this is "an unknown internal error", likely due to a mismatch between your driver (9.0) and the CUDA toolkit (7.5)? upgrade your toolkit and try again?

**Comment by qq932546734** [comment]
Ok, I will try to reinstall them and upgrad the CUDA toolkit. Will come back to report the result. Thank you very much!

**Comment by MahdiNazemi** [comment]
I get the same error when running `test/demo_ivfpq_indexing_gpu`

I have cuda v9.0 and compiler driver v9.0.

**Comment by mdouze** [comment]
Not enough info to repro. Please open a new issue.
