### ISSUE TITLE
Libgomp: Thread creation failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by fuchao01** [facebookresearch/faiss#458]
Released a faiss service with thrift, my thrift service opened 100 threads, requests more than one, it will give an error:
Libgomp: Thread creation failed: Resource temporarily unavailable

ulimit -u 65535

**Comment by mdouze** [comment]
Hi 
You may want to compile Faiss without threading if you are using thrift to do the multi-threading. OpenMP has a non-trivial overhead when a new non-openmp thread is started.

**Comment by fuchao01** [comment]
@mdouze Thank you for your reply.How to compile faiss without threads

**Comment by mdouze** [comment]
In `makefile.inc` in the `CFLAGS` variable replace `-fopenmp` with `-fno-openmp`. Adding `-Wno-error=unknown-pragmas` will quiet all the warnings.

**Comment by fuchao01** [comment]
This really does. But there is a problem, performance is not as good as before. Can you specify the maximum number of openmp threads?

**Comment by fuchao01** [comment]
faiss.omp_set_num_threads() This parameter is not set openmp open thread number?

**Comment by fuchao01** [comment]
I have 200w indexed data, qps 100/s, thrift server 100 threads. The faiss flat index is used. The server is basically running at full capacity. 32-core cpu, 128g memory, load reaches 40+. Is the amount of data too large for the index?

**Comment by mdouze** [comment]
No clear question. Closing.
