### ISSUE TITLE
TypeError: in method 'IndexFlat_add', argument 3 of type 'float const *'

### ISSUE THREAD

**Issue by mgmayank18** [facebookresearch/faiss#461]
# Summary
While following the tutorial (linked below), I encountered the following error while trying to add to index.

These are my dimensions for the query and database. They are read from .h5 format to numpy ndarrays.

Shape of Database :  (5000000, 512)
Shape of Queries :  (42055, 512)

The following is the error.

![untitled](https://user-images.githubusercontent.com/39636203/40569108-95287b8a-609c-11e8-9e07-94a2de6137be.png)

These are the relevent lines of code in swigfaiss_gpu.py:
    def add(self, n, x):
        return _swigfaiss_gpu.IndexFlat_add(self, n, x)

_swigfaiss_gpu is a module imported from a .so file. What is wrong with my installation?

# Platform

OS: Ubuntu 14.04.5 LTS
Faiss version:  1.2.1-py36_cuda8.0.61_2 pytorch

Faiss compilation options: -c pytorch

Running on :
- [ ] CPU
- [x] GPU

# Reproduction instructions

Link to tutorial: https://github.com/facebookresearch/faiss/wiki/Getting-started

You can use any numpy ndarrays of the specified dimensions for this. I used conda install to install faiss on python3.6. swig version is 4.0.0.

After loading the ndarrays,

d = 512
nb = db.shape[0]
nq = queries.shape[0]

index = faiss.IndexFlatL2(d)   # build the index
print(index.is_trained)
sys.stdout.flush()
index.add(db)                  # add vectors to the index <-- ERROR HERE
print(index.ntotal)

# Nvidia-smi output

![untitled](https://user-images.githubusercontent.com/39636203/40568849-cd31b0fc-609a-11e8-8047-f92efbaa5e5c.png)

**Comment by mgmayank18** [comment]
TypeError: ndarrays must be of numpy.float32, and not float64.

Closing issue.

**Comment by nscozzaro** [comment]
Setting the data type to numpy.float32 fixed the issue for me too, but I just wanted to comment that I think the error message could be updated to clarify the problem.

**Comment by crypdick** [comment]
this error message should be updated

**Comment by xzyaoi** [comment]
+1 for the error message should be changed.

**Comment by Wangsherpa** [comment]
Changing to float32 fixed mine. Thanks!

**Comment by dasupradyumna** [comment]
This error message has still not been updated in `1.7.2`.
