### ISSUE TITLE
Searching time is different for c++ and python.

### ISSUE THREAD

**Issue by XiaXuehai** [facebookresearch/faiss#462]
I test the searching time by the file `tutorial/python/2-IVFFlat.py` and `tutorial/cpp/2-IVFFlat.cpp`. 
For c++,I compiled faiss by INSTALL.md, the ide is codeblocks.For python I using the commend line installed

c++:
```
clock_t start,stop;
start = clock();
index.search(nq, xq, k, D, I);
stop = clock();
printf("time:%f\n",(double)(stop-start)/CLOCKS_PER_SEC);
```
time = 0.692166 (index.nprobe = 1)
time = 1.485702 (index.nprobe = 10)

python:  
```
t0 = time.time()
D, I = index.search(xq, k)     # actual search
t1 = time.time()
print(t1-t0)
```
time = 0.03618192672729492 (index.nprobe = 1)
time = 0.2468726634979248 (index.nprobe = 10)

Why it is different?

**Comment by XiaXuehai** [comment]
It's so weird.I complied python interface instead conda install. It's same.

**Comment by beauby** [comment]
It is not the same because the flags used for compiling the C++ library were probably not the same, thus there's a good change you're using a less performant BLAS/LAPACK implementation.

**Comment by mdouze** [comment]
Please refer to documentation.
