### ISSUE TITLE
Question: How to run FAISS with unified memory support?

### ISSUE THREAD

**Issue by msharmavikram** [facebookresearch/faiss#474]
# Summary

# Platform

OS:  16.04

Faiss version:  NA

Faiss compilation options:  NA

Running on :
- [ ] CPU
- [X] GPU

# Reproduction instructions - NA
Running command: `python bench_gpu_1bn.py SIFT1M OPQ8_32,IVF262144,PQ8 -nnn 10 -ngpu 1 -tempmem $[1536*1024*1024]`
 
I see that the FAISS internally supports unified memory. What I dont understand is, when i profile, I see regular cudaMemcpy getting called. Could you please tell me what stage does FAISS actually use unified memory? (Even if the stage does not fit in GPU memory, I see the algorithm automatically dividing the work into multiple cudamemcpys and using it. )
Or do we have any flags where I can force it to use unified memory and not use repeated cudamemcpys?

**Comment by wickedfoo** [comment]
Unified memory is used for storing the index if you opt into it by setting this to `MemorySpace::Unified`:

https://github.com/facebookresearch/faiss/blob/master/gpu/GpuIndex.h#L32

It is primarily meant for using an index that is too large to fit into GPU memory.

Unified memory is not currently used for input/output data or scratch space memory. Any inputs or outputs are manually copied using cudaMemcpyAsync.

**Comment by wickedfoo** [comment]
By default, unless you opt into it, unified memory is not used.

**Comment by msharmavikram** [comment]
Thanks for pointing that out. 

I am trying to run a large dataset whose cannot fit in the GPU memory. So, in this case, do you suggest by default to use unified memory and not use cudamemcpyasyncs? Or does the FAISS internally support split schemes?

**Comment by wickedfoo** [comment]
Manually splitting the index across multiple GPUs will always be faster than unified memory. If you have a single GPU on which it won't fit, then that's a use case for unified memory, but I would consider approximate indexing or compression with IVFPQ as well.
