### ISSUE TITLE
Mahalanobis distance

### ISSUE THREAD

**Issue by gobbedy** [facebookresearch/faiss#478]
Hello,

Does FAISS support Mahalanobis distance a similarity measure?

In other words say x1 is my basis vector and x2 belongs to the database of reference vectors, the distance / similarity metric is

(x1-x2).transpose() * inv(A) * (x1-x2)

where asterisk is short for matrix multiplication and A is a Hermitian semi-definite matrix.

This a pseudo code of what I currently do in my current algorithm

# cholesky decomposition using LAPACK, one-time before search
upper_diag = potrf(A)

# distance metric / similarity measure
distance_func = lambda x1, x2: (x1-x2).tranpose() * potrs(x1-x2, upper_diag)

# performance distance measurement over database of vectors, X
for i in range(len(X)):
    dist[i] = distance_func(basis_vector, X[i])

# sort database by distance
perm = np.argsort(dist)
dist = dist[perm]
X = X[perm]

# pick nearest k
nk_indices = np.where(dist <= dist[k-1])[0]
nearest_k = X[nk_indices]

Can FAISS be used to do this fast?

Thank you!

**Comment by gobbedy** [comment]
Update: I notice that nmslib is said to be faster for "small scale" databases of vectors (up to 1M), which is my use case. However, I do not see in their documentation that they support GPUs, so I'm assuming that with GPUs FAISS is still faster..

**Comment by mdouze** [comment]
Hi 
You can map back the Mahalanobis distance to L2 distance by multiplying all vectors by A^(-1/2).

**Comment by gobbedy** [comment]
Thank you @mdouze 

Your reply got me googling and it turns out since A is Hermitian I can even multiply by L, where L is the Cholesky factor of A.
Ref: https://blogs.sas.com/content/iml/2012/02/15/what-is-mahalanobis-distance.html

Another question if you'd be so kind:
Given my application what library would you recommend for L2 distance?
- database of vectors between 100,000 and 1M
- access to GPUs
- python

Thanks in advance!

**Comment by Enet4** [comment]
@gobbedy I've been using Faiss under very similar requirements. The `Flat` index type is usually fast enough too.

**Comment by gobbedy** [comment]
@Enet4 Thanks a lot, I'll give it a shot.

**Comment by MohiFaruq** [comment]
Hi, I am trying that too in python. But I dont understand right now how. So I have database of lets say 10000 vectors of shape (10000, 8). So when I a new vector come in shape of (8,), how do I get A (the A you guys are referring to) and eventually how do I get Mahalanobis distance?

**Comment by mdouze** [comment]
A is the covariance matrix of the data, see https://en.wikipedia.org/wiki/Mahalanobis_distance#Definition_and_properties
and indeed you can use the Cholesky decomposition.
