### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'tmp/demo_auto_tune.png'

### ISSUE THREAD

**Issue by BondJYC** [facebookresearch/faiss#48]
Dear contributor,i encountered another problem in step 2.
after using the command `export PYTHONPATH=.`
this command `python python/demo_auto_tune.py` can be executed
however at the end of execution,it reports a error like below:
```
cno=12 key=nprobe=4096 perf=0.9870 t=11.214 
Traceback (most recent call last):
  File "python/demo_auto_tune.py", line 168, in <module>
    fig.savefig('tmp/demo_auto_tune.png')
  File "/usr/lib/pymodules/python2.7/matplotlib/figure.py", line 1421, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 2220, in print_figure
    **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_agg.py", line 510, in print_png
    filename_or_obj = open(filename_or_obj, 'wb')
IOError: [Errno 2] No such file or directory: 'tmp/demo_auto_tune.png'
```
i don't know whether this problem is due to the matplotlib module of my python.
thank you for your patient reply!

**Comment by mdouze** [comment]
Hi

Please do `mkdir tmp`

**Comment by BondJYC** [comment]
i appreciate your help!

thank u!

**Comment by vaibhav14b** [comment]
Where do i have to create tmp directory in the Ubuntu 16.04
Can you please help @mdouze

**Comment by asanakoy** [comment]
Should the `tmp` dir be created automatically if it doesn't exist?
