### ISSUE TITLE
Question: What to do if the index does not fit in the GPU memory

### ISSUE THREAD

**Issue by msharmavikram** [facebookresearch/faiss#482]
# Summary

# Platform

OS:  Ubuntu 16.04

Running on :
- [ ] CPU
- [X] GPU

# Reproduction instructions - NA

I am trying to run a very large dataset that cannot fit in the GPU memory. So, in this case, do you suggest by default to use unified memory and not use cudaMemcpyAsync? Or does the FAISS internally support split schemes?

**Comment by mdouze** [comment]
Hi 
Your options are: 
- use more compression on GPU (move to IVFPQ rather than Flat)
- move to CPU
- use non-uniform memory.
I would try the two first options first, as they are easier to test.
