### ISSUE TITLE
Faiss is optimized for batch search, but looks like during query time, the searches are done in parrel in different threads in OMP

### ISSUE THREAD

**Issue by fishbell** [facebookresearch/faiss#483]
# Summary
why matrix-matrix multiplication is not used in final query. I can see that knn_L2sqr_blas is implemented for IndexFlat search, and this is used to pick up piles of centroids during search. After getting the nprobes of clusters, seperate queries, say, 20 queries are conducted in vector-vector L2 distance comparison with OMP. Is there a reason for this? is blas not efficient for small blocks matrix compution?

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on :
- [x] CPU
- [ ] GPU

# Reproduction instructions

**Comment by mdouze** [comment]
Hi 
You cannot map this to matrix-matrix product unless several vectors get quantized to the same centroids.

**Comment by fishbell** [comment]
yes I did not notice this. Thanks for your answer!
