### ISSUE TITLE
faiss::Clustering::train failed

### ISSUE THREAD

**Issue by sharthZ** [facebookresearch/faiss#49]
Full log: 

> Clustering 138982590 points in 64D to 4096 clusters, redo 2 times, 40 iterations
>   Preprocessing in 17.1445 s
> Outer iteration 0 / 2
>   Iteration 39 (4086.49 s, search 3227.36 s): objective=1.88871e+07 imbalance=1.711 nsplit=0
> Keep new clusters
> Outer iteration 1 / 2
> Faiss assertion index.ntotal == 0 failed in virtual void faiss::Clustering::train(faiss::Clustering::idx_t, const float*, faiss::Index&) at Clustering.cpp:152Aborted (core dumped)

Used code from [https://github.com/facebookresearch/faiss/wiki/GPU-k-means-example](url)

**Comment by mdouze** [comment]
Hi 

I can repro the bug

**Comment by mdouze** [comment]
Should be fixed now.

**Comment by mdouze** [comment]
Should be fixed now.

**Comment by sharthZ** [comment]
Still have this problem.

**Comment by mdouze** [comment]
Could you repro with a clean checkout of Faiss?

**Comment by sharthZ** [comment]
I just did `git pull`, then `make clean`:

> ivan@research.node:~/projects/faiss$ make clean
> rm -f libfaiss.a libfaiss.so* *.o \
> 	   	lua/swigfaiss.so lua/swigfaiss_wrap.cxx \
> 		python/_swigfaiss.so python/swigfaiss_wrap.cxx \
> 		python/swigfaiss.py _swigfaiss.so swigfaiss.py

And `make`:

> ivan@research.node:~/projects/faiss$ make
> g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c hamming.cpp -o hamming.o
> g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c utils.cpp -o utils.o  -DFINTEGER=long
> g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c IndexFlat.cpp -o IndexFlat.o
> g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c IndexIVF.cpp -o IndexIVF.o
> g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c IndexLSH.cpp -o IndexLSH.o
> g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c IndexPQ.cpp -o IndexPQ.o
> g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c IndexIVFPQ.cpp -o IndexIVFPQ.o
> g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c Clustering.cpp -o Clustering.o
> g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c Heap.cpp -o Heap.o
> g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c VectorTransform.cpp -o VectorTransform.o  -DFINTEGER=long
> g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c index_io.cpp -o index_io.o
> g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c PolysemousTraining.cpp -o PolysemousTraining.o
> g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c MetaIndexes.cpp -o MetaIndexes.o
> g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c Index.cpp -o Index.o
> g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c ProductQuantizer.cpp -o ProductQuantizer.o  -DFINTEGER=long
> g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c AutoTune.cpp -o AutoTune.o
> g++ -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp -c AuxIndexStructures.cpp -o AuxIndexStructures.o
> ar r libfaiss.a hamming.o utils.o IndexFlat.o IndexIVF.o IndexLSH.o IndexPQ.o IndexIVFPQ.o Clustering.o Heap.o VectorTransform.o index_io.o PolysemousTraining.o MetaIndexes.o Index.o ProductQuantizer.o AutoTune.o AuxIndexStructures.o
> ar: creating libfaiss.a
> g++ -o tests/demo_ivfpq_indexing -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp tests/demo_ivfpq_indexing.cpp libfaiss.a -g -fPIC  -fopenmp -Wl,--no-as-needed -L/opt/intel/compilers_and_libraries/linux/mkl//lib/intel64   -lmkl_intel_ilp64 -lmkl_core -lmkl_gnu_thread -ldl -lpthread

Code: [pastebin](http://pastebin.com/P9kKa3Ka)
Usage: `kmeans-gpu 4096 /data/index/points.vbin`

**Comment by mdouze** [comment]
What about the GPU part of Faiss?

**Comment by sharthZ** [comment]
Ouch, forgot about it. Got error when i tried do `make` in `gpu/`:

> /usr/local/cuda//bin/nvcc  -I /usr/local/cuda//targets/x86_64-linux/include/ -Xcompiler -fPIC -Xcudafe --diag_suppress=unrecognized_attribute -gencode arch=compute_35,code="compute_35" -gencode arch=compute_52,code="compute_52" -gencode arch=compute_60,code="compute_60" --std c++11 -lineinfo -ccbin g++ -DFAISS_USE_FLOAT16 -g -O3 \
>          -c impl/PQScanMultiPassNoPrecomputed.cu -o impl/PQScanMultiPassNoPrecomputed.o
> impl/PQScanMultiPassNoPrecomputed.cu(42): warning: statement is unreachable
> 
> impl/PQScanMultiPassNoPrecomputed.cu(47): warning: statement is unreachable
> 
> impl/PQScanMultiPassNoPrecomputed.cu(42): warning: statement is unreachable
> 
> impl/PQScanMultiPassNoPrecomputed.cu(47): warning: statement is unreachable
> 
> impl/PQScanMultiPassNoPrecomputed.cu(42): warning: statement is unreachable
> 
> impl/PQScanMultiPassNoPrecomputed.cu(47): warning: statement is unreachable
> 
> impl/PQScanMultiPassNoPrecomputed.cu(42): warning: statement is unreachable
> 
> impl/PQScanMultiPassNoPrecomputed.cu(47): warning: statement is unreachable

> /usr/local/cuda//bin/nvcc  -I /usr/local/cuda//targets/x86_64-linux/include/ -Xcompiler -fPIC -Xcudafe --diag_suppress=unrecognized_attribute -gencode arch=compute_35,code="compute_35" -gencode arch=compute_52,code="compute_52" -gencode arch=compute_60,code="compute_60" --std c++11 -lineinfo -ccbin g++ -DFAISS_USE_FLOAT16 -o test/demo_ivfpq_indexing_gpu test/demo_ivfpq_indexing_gpu.cpp libgpufaiss.a ../libfaiss.a -Xcompiler -fopenmp -lcublas \
> 	-Xlinker -Wl,--no-as-needed -L/opt/intel/compilers_and_libraries/linux/mkl//lib/intel64   -lmkl_intel_ilp64 -lmkl_core -lmkl_gnu_thread -ldl -lpthread
> /usr/bin/ld: unrecognized option '-Wl'
> /usr/bin/ld: use the --help option for usage information
> collect2: error: ld returned 1 exit status
> make: *** [test/demo_ivfpq_indexing_gpu] Error 1

**Comment by sharthZ** [comment]
Fixed problem by removing flags `-Xlinker -Wl,--no-as-needed`. Now kmeans works fine, thanks for quick response.
