### ISSUE TITLE
Problem in using Dockerfile

### ISSUE THREAD

**Issue by MohammadChavosh** [facebookresearch/faiss#494]
https://github.com/facebookresearch/faiss/blob/dd6c9ebf2da3123e055ffdc99f9b597e8b97de04/Dockerfile#L17

After the recent refactorings, shouldn't it be misc/test_blas instead of tests/test_blas?

**Comment by beauby** [comment]
Yes, the Dockerfile is community maintained, i.e. we do not officially support it, and it is currently out of sync.

**Comment by mdouze** [comment]
see #491
