### ISSUE TITLE
Nested Indexes

### ISSUE THREAD

**Issue by kwaibun** [facebookresearch/faiss#495]
# Summary
I am trying to run the demo_ondisk_ivf.py, I want to try the PCA dimension reduction, I replaced this line
index = faiss.index_factory(xt.shape[1], "IVF4096,Flat")

to 

index = faiss.index_factory(xt.shape[1], "PCAR8,IVF4096,Flat")

But then, when in stage 5, how can I merge the images. Now the index is VectorTransform, not a IVFIndex, there's no index.invlists, how can I get index.invlists filed

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on :
- [ ] CPU
- [ ] GPU

# Reproduction instructions

**Comment by mdouze** [comment]
Hi
It is `faiss.downcast_Index(index.index).invlists`.

**Comment by kwaibun** [comment]
Cool, thanks!
