### ISSUE TITLE
Can I run PCA with limited memory?

### ISSUE THREAD

**Issue by LuShengDong** [facebookresearch/faiss#497]
# Summary

I am working on a computer vision project. I have to work with 3 million 2048D vectors with only 16G memory. Since faiss keeps all the vectors in memory, I want to use PCA to reduce the number of dimensions to fit them into small memory. However, it seems that all the vectors have to be loaded into memory before I execute PCA, which is impossible for me.

Is it possiable to run PCA with a stream of vector without loading all the vectors into memory at once?

Thank you.

Best regards,
Shengdong

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on :
- [x] CPU
- [ ] GPU

**Comment by mdouze** [comment]
Hi 
You need only a sample of vectors to train the PCA. Then apply it by batches of say 10k vectors.
