### ISSUE TITLE
A markdown format error on wiki ?

### ISSUE THREAD

**Issue by h-j-13** [facebookresearch/faiss#501]
on this wiki page https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index#if-below-1m-vectors-ivfx  
> Where x is 4*sqrt(N) to 16*sqrt(N), .. 

Maybe it should be written like "Where x is 4\*sqrt(N) to 16\*sqrt(N), .."    ?
 
"Where x is 4\\*sqrt(N) to 16\\*sqrt(N), .. " at Guidelines-to-choose-an-index.md

**Comment by mdouze** [comment]
Thanks, fixed.
