### ISSUE TITLE
The MinimaxHeap of IndexHNSW

### ISSUE THREAD

**Issue by zhaokang0826** [facebookresearch/faiss#502]
# Summary

In the HNSW paper, the author uses a minHeap(candidatesSet) and a maxHeap(resultsSet) to implement the search procedure. But in the faiss, the candidatesSet is a Minimaxheap (In my opinion, It is essentially a maxheap), in which pop_min is an O(n) operation. 
Why not use a minHeap to speed up the pop_min, or do you have any other consideration？

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
Hi
This is a very good remark. It is indeed a sub-optimal implementation, and we plan to improve it.

**Comment by beauby** [comment]
@zhaokang0826 It is indeed on our roadmap. Let's keep this issue open for tracking.

**Comment by beauby** [comment]
The traversal procedure described in the article is now available by setting `index.hnsw.search_bounded_queue = false;`.
