### ISSUE TITLE
Got *Intel MKL FATAL ERROR* when running Python example

### ISSUE THREAD

**Issue by suzaku** [facebookresearch/faiss#51]
I'm trying `faiss` on Ubuntu.

Both `make` and `make py` ran successfully.
The demo `tests/demo_sift1M` also ran correctly, I guessed this meant the *C++ core* is successfully installed.
Then I went on to check the Python wrapper, with the one liner documented [here](https://github.com/facebookresearch/faiss/blob/master/INSTALL):

```bash
root@428311598e54:/tmp/faiss-master# LD_LIBRARY_PATH=/opt/intel/compilers_and_librarie
s_2016.3.210/linux/mkl/lib/intel64 python -c "import faiss, numpy
faiss.Kmeans(10, 20).train(numpy.random.rand(1000, 10).astype('float32'))"
Failed to load GPU Faiss: No module named swigfaiss_gpu
Faiss falling back to CPU-only.
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
```

`LD_LIBRARY_PATH` is correctly set, and both modules are available in that path, but it failed with an `Intel MKL FATAL ERROR`.

```
root@428311598e54:/tmp/faiss-master# ls /opt/intel/compilers_and_libraries_2016.3.210/linux/mkl/lib/intel64/{libmkl_core.so,libmkl_avx2.so}
/opt/intel/compilers_and_libraries_2016.3.210/linux/mkl/lib/intel64/libmkl_avx2.so
/opt/intel/compilers_and_libraries_2016.3.210/linux/mkl/lib/intel64/libmkl_core.so
```

**Comment by mdouze** [comment]
Hi 

Setting MKL flags is a frustrating process of trial and errors, and indeed the flags to generate .a and .so files are different. Please post here if you manage to fix this compile error, we will incorporate it in the documentation.

**Comment by suzaku** [comment]
@mdouze Thanks. I'm trying `faiss` with `OpenBLAS` now.
