### ISSUE TITLE
Fail to reconstruct from IMI index

### ISSUE THREAD

**Issue by LuShengDong** [facebookresearch/faiss#519]
# Summary

Hello,

When I was trying to reconstruct from a IMI index, following the instructions in https://github.com/facebookresearch/faiss/issues/374, I got the following exception:

RuntimeError: Error in void faiss::IndexIVF::make_direct_map(bool) at IndexIVF.cpp:272: Error: '0 <= idlist [ofs] && idlist[ofs] < ntotal' failed: direct map supported only for seuquential ids

I constructed the index with my specific ids. Does it mean that I cannot reconstruct vectors in this situation. 

BTW, surprisingly, I can reconstruct some vectors from index after make_direct_map with a try-except surrounding. However, python interpreter crushed directly when I query some ids with the following output:
Assertion failed: (list_no < nlist), function list_size, file IndexIVF.cpp, line 181.

Thank you.

Best,

Shengdong

# Platform

OS: macOS

Faiss version: 0.1 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
Hi 
Yes, it is not supported via make_direct_map. The reason is simply because the direct map is a std::vector that can be addressed only with sequential ids not arbitrary ids like a hash table. 
You could wrap the index in an `IndexIDMap2` or handle the mapping yourself.

**Comment by LuShengDong** [comment]
Problem solved.
Thank you!

**Comment by yuyifan1991** [comment]
@LuShengDong I have the same problem, I have the hash ids, what should I do to reconstruct vectors

**Comment by Sarakio** [comment]
I use IVFFlat, following codes work

index = faiss.index_factory(10, "IVF" + str(10) + ", Flat")
index.make_direct_map()
index = faiss.IndexIDMap2(index)

index.train(np.array([[i]*10 for i in range(20)]).astype('float32'))
index.add_with_ids(np.array([[0]*10]).astype('float32'), np.array([1234]).astype('int'))

index.reconstruct(1234)
