### ISSUE TITLE
openblas error

### ISSUE THREAD

**Issue by danny1984** [facebookresearch/faiss#521]
# Summary

root@1daa58be02ec:~/faiss# ./misc/test_blas
BLAS test
errors=
 0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000
 0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000
 0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000
 0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000
 0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000
 0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000
 0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000
 0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000
 0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000
 0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000
Intentional Lapack error (appears only for 64-bit INTEGER):
info=0000064b00000000
Lapack uses 32-bit integers

Running on:
- [√ ] CPU
- [ ] GPU

Interface: 
- [ √] C++
- [ ] Python

# Reproduction instructions

**Comment by beauby** [comment]
What seems to be the issue here?

**Comment by danny1984** [comment]
**Intentional Lapack error (appears only for 64-bit INTEGER):**
info=0000064b00000000
Lapack uses 32-bit integers

I don't know if this will impact the later building. I failed building  as well, as seen in 
https://github.com/facebookresearch/faiss/issues/520

**Comment by beauby** [comment]
@danny1984 So this program is here to help you determine whether the LAPACK implementation you linked has a 32 or 64-bit interface. What you are observing is not an error, and would not impact the build.
