### ISSUE TITLE
A few questions about faiss

### ISSUE THREAD

**Issue by ghostboyzone** [facebookresearch/faiss#524]
- How to change nlist value while index is still running ?
- How to train index while index is not empty?
- How to get data from index by id?

**Comment by mdouze** [comment]
Hi, 
Answers: 
- not possible
- not possible 
- see https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes#reconstructing-vectors-from-an-index

**Comment by ghostboyzone** [comment]
if my index has custom ids , call `reconstruct` and `reconstruct_n` may have  problems below

```
  File "/opt/faiss/python/faiss/__init__.py", line 153, in replacement_reconstruct
    self.reconstruct_c(key, swig_ptr(x))
  File "/opt/faiss/python/faiss/swigfaiss.py", line 2880, in reconstruct
    return _swigfaiss.IndexIVF_reconstruct(self, key, recons)
RuntimeError: Error in virtual void faiss::IndexIVF::reconstruct(faiss::Index::idx_t, float*) const at IndexIVF.cpp:302: Error: 'direct_map.size() == ntotal' failed: direct map is not initialized
```

**Comment by ghostboyzone** [comment]
if my index ids start from `10` to `19`,  `index.ntotal` will be `10`, but i cannot gain data using id larger than `10`

**Comment by beauby** [comment]
@ghostboyzone Would you mind opening a separate issue?

**Comment by ghostboyzone** [comment]
transfer to #533
