### ISSUE TITLE
can faiss build index with someting like category id?

### ISSUE THREAD

**Issue by universewill** [facebookresearch/faiss#525]
I have got about 1000 categories, i want to build an index using faiss.
However, i only want the same category points to be returned when search a target category point.
Can faiss do this? Or how can i achieve this?

Must i build 1000 indexes for each category to achieve this goal?

**Comment by beauby** [comment]
Yes, you need to build 1000 indexes.

**Comment by mdouze** [comment]
See also https://github.com/facebookresearch/faiss/issues/40#issuecomment-286569115
