### ISSUE TITLE
While Auto tuning : TypeError: in method 'OperatingPointVector_at', argument 2 of type 'size_t'

### ISSUE THREAD

**Issue by yuyifan1991** [facebookresearch/faiss#527]
when i run the code in demo_auto_tune.py file, some trouble appeared: 
While Auto tuning : TypeError: in method 'OperatingPointVector_at', argument 2 of type 'size_t'

Who know how to solve it?

**Comment by mdouze** [comment]
Looks like an install problem.

**Comment by yuyifan1991** [comment]
@mdouze thank you so much. I have another question that  In faiss, we must input fixed dimension vector. But now, the different dimensions vectors I have got, what should I do to make the different dimensions vector also indexed in faiss successfully.

**Comment by mdouze** [comment]
Sorry, this question does not make sense. 
Closing.
