### ISSUE TITLE
Running in non-Intel machine

### ISSUE THREAD

**Issue by msharmavikram** [facebookresearch/faiss#529]
# Summary
I am trying to run FAISS in IBM Power 8 system with P100 GPUs. I see that most of code is hardcoded to use Intel platform with SSE4 enabled. Are there any ways I could get this working without the help of SSE4? I see IndexHNSW files have SSE4 optimizations. Any means I can avoid file and get running? 

# Platform
IBM Power 8 with Nvidia P100 machines with Cuda 8.0

OS:  Ubuntu 16.04LTS

Faiss version:  2dc30e14cfa76985ff8c2821c051f1725fe66afa 

Faiss compilation options:  Not using MKL, SSE4 or Intel specific options

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
Run it on IBM Machine.

**Comment by mdouze** [comment]
This is a good question. Sadly, by lack of a non-x64 dev platform we were dragged into writing non portable code.

However, all code that depends on SSE/popcount has a "slow" version that is written in generic c++. That code must be enabled, often manually in the current version.

In IndexHNSW, the only part that depends on SSE is the one handling PQ compressed HNSW which is a corner case use of HNSW. It can be safely commented out.

The function `fvec_L2sqr` is the most useful function for HNSW without compression, it is implemented in utils.cpp and the generic version is `fvec_L2sqr_ref`.

**Comment by msharmavikram** [comment]
Thanks for the information. I am going to try out these modifications that you suggested and if I find more issues, I will continue this thread.

**Comment by msharmavikram** [comment]
Are there any alternatives to these two structures?  
Distance2xXPQ4 and Distance2xXPQ4

**Comment by mdouze** [comment]
Compilation for non-intel machines is supported in 1.4.0
