### ISSUE TITLE
About  different dimensions vector input

### ISSUE THREAD

**Issue by yuyifan1991** [facebookresearch/faiss#530]
In faiss, we must input  fixed dimension vector. But now, the different dimensions vectors I have got, what should I do to make the different dimensions vector also  indexed in faiss successfully.

Who can help me?  Thanks a lot

**Comment by mdouze** [comment]
What would you like to do with vectors x and y of dimensions 10 and 20 for example?

**Comment by yuyifan1991** [comment]
For example, I have extracted the Image feature,they are vectors. But these feature vectors are  in different dimensions, one for 126-d, anther one for 174-d. So how to build index? Thank you so much

**Comment by mdouze** [comment]
how would you mathematically define the distance between a 126D and a 174D vector?

**Comment by yuyifan1991** [comment]
I mean, whether the vector must be fixed? The d must be fixed, or the d can be  variable ?

**Comment by beauby** [comment]
@yuyifan1991 If you want to work with multiple embeddings, you'll have to make one index per embedding.

**Comment by beauby** [comment]
Closing as the question was addressed. Feel free to keep commenting if you have further questions.

**Comment by nikolaydubina** [comment]
similar question. to illustrate example:

- dataset: vectors of length from 144D up to 1024D (smaller vectors are substrings of larger ones)
- query: vectors from 144D up to 1024D (smaller vectors are substrings of larger ones)

If we are to build index per each number dimensions that would be ~1000 indexes. This would take lots of RAM and nodes to host it, and network and code complexity overhead.

Many of these indexes would "overlap", meaning containing similar information.

Some ideas:

1. only few indexes: one at 144D, one at 256D, one at 512, ..., so ~10 indexes. And allow queries only to those sizes.
2. break down into smaller ones (eg, 370D = 128D + 128D + 64D + 32D) and have index for chunks then have some heuristic to of aggregate
3. have one max size index of 1024D and fill smaller search queries with 0

But would be good to have better solution and hear from experts in the area! (or some pointers what this problem looks like and some writings on it!). Thank you!
