### ISSUE TITLE
About k-means centroids initialization

### ISSUE THREAD

**Issue by Hugh0120** [facebookresearch/faiss#531]
Does faiss support to specify k centroids when I start training kmeans?

**Comment by mdouze** [comment]
see https://github.com/facebookresearch/faiss/wiki/Faiss-building-blocks:-clustering,-PCA,-quantization#clustering

**Comment by mdouze** [comment]
Sorry, I did not read the title. 
If on input of the training, the centroids table is a k*d vector, then it will be used as the initialization:
https://github.com/facebookresearch/faiss/blob/master/Clustering.h#L62

**Comment by Hugh0120** [comment]
Thanks!

**Comment by sthalles** [comment]
Hi, can someone point me to an example where we set the initial centroids?
Thanks.

**Comment by mdouze** [comment]
duplicate of #1294
