### ISSUE TITLE
What If numWarps > 32 ?

### ISSUE THREAD

**Issue by kevin-14** [facebookresearch/faiss#532]
# Summary
![image](https://user-images.githubusercontent.com/9441180/42937084-932cd3e4-8b80-11e8-8f62-660b777e14f9.png)

the above code from gpu/impl/L2Norm.cu, 
if numWarps > 32, given laneId in [0, 32), there would be some warps not added to result.

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

**Comment by wickedfoo** [comment]
All current GPU compute capabilities support at most 32 warps per CTA.
