### ISSUE TITLE
Interpreting search scores for high dimensional vectors.

### ISSUE THREAD

**Issue by ask4ralph** [facebookresearch/faiss#534]
# Summary
Hello, there isn't much documentation about how scores are derived.. What is the range of all possible scores. I'm using faiss for face image search using 8631 dimension vectors. 

Code:
...
dimension = 8631
sub_index = faiss.IndexFlat(dimension)
index = faiss.IndexIDMap2(sub_index)
...
index.add_with_ids(vectors,ids)

Result of search:
ids =>[[1,2,3]] 
scores => [[0.00, 12780.82421875, 43538.83984375]]

Questions:
ID 1 is an exact match. ID 1 and 2 are feature vectors of the same individual. 
1. Aren't both 1 and 2 supposed to have a score of 0.00 or close? 
2. Aren't the scores supposed to be between 0 and 10? 

Running on:
- [x] CPU
- [ ] GPU
#will move to GPU 

Interface: 
- [ ] C++
- [x] Python

**Comment by mdouze** [comment]
"Scores" are squared L2 distances.

**Comment by beauby** [comment]
1. If the feature vectors are close, they will have a small distance.
2. As @mdouze mentioned, "scores" are squared L2 distances between the vectors, so they are not bounded.

Closing as the questions have been addressed. Feel free to keep commenting if you have further questions.

**Comment by ask4ralph** [comment]
Thanks for the clarification.

**Comment by ask4ralph** [comment]
Hello, what is the best approach to normalize the scores to a bounded range say between 0-100? Thanks.

**Comment by haggenmatt** [comment]
@ask4ralph I wonder if you have managed to make this working and mind if you can share some code on how to glue all of this (DLib 128 face vector plus Faiss insertion/lookup).

**Comment by ask4ralph** [comment]
Hello,
I think you should take a look at the examples under [tutorials](https://github.com/facebookresearch/faiss/tree/master/tutorial) . I used python.

- Inserting:
`normalized_vectors = preprocessing.normalize(vectors)#you can normalize before indexing using sklearn
 index.add_with_ids(normalized_vectors, your_ids)
`
- Searching:
`distances, neighbors = index.search(vectors, k)  
`
- To get the bounded score for each distance:
`score = 25 * (4 - distance)`

**Comment by summarizepaper** [comment]
It only works if distance<4, which apparently is not true because it is not bounded...

**Comment by marzooq-unbxd** [comment]
I will try normalizing by the max distance in the list of scores you get, 
and then subtracting from 1

**Comment by elepherai** [comment]
> Hello, I think you should take a look at the examples under [tutorials](https://github.com/facebookresearch/faiss/tree/master/tutorial) . I used python.
> 
> * Inserting normalized vectors:
>   `normalized_vectors = preprocessing.normalize(vectors)#sklearn  index.add_with_ids(normalized_vectors, your_ids) `
> * Searching:
>   `distances, neighbors = index.search(vectors, k)   `
> * To get the bounded score for each distance:
>   `score = 25 * (4 - distance)`

@ask4ralph what does `score = 25 * (4 - distance)` mean? I can't find any information.
