### ISSUE TITLE
Enabling stats

### ISSUE THREAD

**Issue by msharmavikram** [facebookresearch/faiss#535]
# Summary
As I go deeper into the codebase, I see there are some perform stats structures available in the FAISS system. Could you please let me know how to enable all the stats? Is there something like verbose mode in which I can run faiss? 

# Platform

OS:  NA

Faiss version:  NA
 
Faiss compilation options:  NA

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [x] C++
- [x] Python

# Reproduction instructions

NA

  NA

**Comment by mdouze** [comment]
At some points in search, statistics are collected and written to global variables (eg. `indexIVFPQ_stats`). The variable should be `reset()` before calling the search function and can be read afterwards (with eg. `faiss.cvar.indexIVFPQ_stats.assign_cycles`.

Note however that this is undocumented and inconsistent, the stats were used during the development of Faiss.
