### ISSUE TITLE
How to print installed faiss version with python?

### ISSUE THREAD

**Issue by universewill** [facebookresearch/faiss#539]
I installed faiss-cpu using conda.
I want to see the version of my installed faiss. But faiss module doesn't have __version__ or version() interface.

**Comment by mdouze** [comment]
Maybe we should add a version number inside of Faiss. 
@beauby, any idea on how to do that?

**Comment by beauby** [comment]
The next version will expose `faiss.__version__`.

**Comment by beauby** [comment]
Closing as this is now in the latest release.
