### ISSUE TITLE
Implementing merge_from for indexes with pre-transform

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [facebookresearch/faiss#545]
I currently have an index with factory `PCAR128,IVF4096,SQ8`, 
however when I try to merge indexes using merge_from, it throws error saying indexPreTransform cannot be merged. My assumption was that having a pre index transform step should not matter when merging since its essentially just combining the Inverted vertex files. The code works correctly for `IVF4096,Flat` and I am verifying if it works for `IVF4096,SQ8`.

I am currently on this commit 
https://github.com/facebookresearch/faiss/commit/7f996bd9df4cd01537f632916a6df625edfcb83f

```
  File "/root/DVA/server/dvalib/retriever.py", line 134, in add_vectors
    self.faiss_index.merge_from(index, self.faiss_index.ntotal)
  File "/root/thirdparty/faiss/python/swigfaiss.py", line 1784, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, IndexPreTransform, name)
  File "/root/thirdparty/faiss/python/swigfaiss.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'IndexPreTransform' object has no attribute 'merge_from'
```

**Comment by mdouze** [comment]
The merge function for `IndexPreTransform`'s will be added to faiss shortly.

**Comment by AKSHAYUBHAT** [comment]
I verified that "IVF4096,SQ8" surely works. And in all of the type "IVF4096,..." most likely work. 
So its just pre-transform, that is missing the support. 

Thanks,

**Comment by mdouze** [comment]
Addressed in 1.4.0, see https://github.com/facebookresearch/faiss/blob/master/IVFlib.h#L44

**Comment by AKSHAYUBHAT** [comment]
It appears that "ivflib" is a separate library, with merge_into for merging two indexes. 
However it does not seems to be accessible in Python. 

```
>>> from faiss import ivflib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name ivflib
```

**Comment by beauby** [comment]
@AKSHAYUBHAT It is currently not exported to python. The way to do this is to modify `python/swigfaiss.swig` with something like:
```
diff --git a/python/swigfaiss.swig b/python/swigfaiss.swig
index b181059..ddf92c0 100644
--- a/python/swigfaiss.swig
+++ b/python/swigfaiss.swig
@@ -91,6 +91,7 @@ extern "C" {

 #include "index_io.h"

+#include "ivflib.h"
 #include "utils.h"
 #include "Heap.h"
 #include "AuxIndexStructures.h"
@@ -262,6 +263,7 @@ int get_num_gpus()
 %include "IndexPQ.h"
 %include "InvertedLists.h"
 %include "IndexIVF.h"
+%include "IVFlib.h"
 %include "IndexScalarQuantizer.h"
 %include "IndexHNSW.h"
 %include "IndexIVFFlat.h"
--
```

**Comment by AKSHAYUBHAT** [comment]
Thanks I will try !

**Comment by AKSHAYUBHAT** [comment]
So it seem with this patch the function "merge_into" gets imported into "faiss" namespace. 
i.e. its under faiss.merge_into rather than faiss.ivflib.merge_into since swig does treats nested namespaces as nested modules instead it simply puts them in same namespace. 

http://www.swig.org/Doc1.3/Python.html#Python_nn25

I also got this warning which seems concerning. 


```
swig -python -c++ -Doverride= -I../ -o swigfaiss_wrap.cpp swigfaiss.swig
../IVFlib.h:37: Warning 509: Overloaded method faiss::ivflib::extract_index_ivf(faiss::Index *) effectively ignored,
../IVFlib.h:36: Warning 509: as it is shadowed by faiss::ivflib::extract_index_ivf(faiss::Index const *).
```
I will test it with an example and see if it works.

**Comment by mdouze** [comment]
1: yes that is expected
2: nvm. SWIG just ignores const.

**Comment by hamhochoi** [comment]
Is there a simple python solution for merge_from with pre-transform?
