### ISSUE TITLE
Search for vectors by id?

### ISSUE THREAD

**Issue by LuShengDong** [facebookresearch/faiss#546]
# Summary

Is it possible to search vectors by its id? 

I have a IMI faiss model which contains 5 million vectors with customized id. Can I search for vectors 
by the vector that is already in the index using it's id? 

Thanks,

Best regards,
Shengdong

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by beauby** [comment]
Yes, you can use the `reconstruct()` method to retrieve a stored vector by id.
