### ISSUE TITLE
Is it neccessary to set 'index.dont_dealloc_me' when read index from file?

### ISSUE THREAD

**Issue by universewill** [facebookresearch/faiss#550]
I notice that we should set 'index.dont_dealloc_me' para to prevent crush in python code.

However, i have to read index from a saved index file.
How to set that para after read the index from file?

**Comment by mdouze** [comment]
No, it is not needed after reading the index from file.
https://github.com/facebookresearch/faiss/wiki/Index-IO,-index-factory,-cloning-and-hyper-parameter-tuning#io-and-deep-copying-indexes

**Comment by universewill** [comment]
Does the 'deep copy' in the doc mean that the dont_dealloc_me para would also be saved in the index file? So there is no need to set the para after read index from file?
@mdouze

**Comment by mdouze** [comment]
See 
https://github.com/facebookresearch/faiss/wiki/Faiss-code-structure#object-ownership
for a low-level explanation of object ownership.

**Comment by universewill** [comment]
Thank for your reply!
