### ISSUE TITLE
Testing the GPU implementation error

### ISSUE THREAD

**Issue by albalab** [facebookresearch/faiss#553]
I follow the install instruction and compile the GPU implementation. But testing give me error:

>> cd gpu; make test/demo_ivfpq_indexing_gpu
g++ -std=c++11 -fPIC -fopenmp -m64 -Wno-sign-compare -g -O3 -Wall -Wextra -DFINTEGER=int  -fopenmp   test/demo_ivfpq_indexing_gpu.cpp   -o test/demo_ivfpq_indexing_gpu
In file included from test/../GpuResources.h:12:0,
                 from test/../StandardGpuResources.h:12,
                 from test/demo_ivfpq_indexing_gpu.cpp:19:
test/../utils/DeviceMemory.h:12:26: fatal error: cuda_runtime.h: No such file or directory
 #include <cuda_runtime.h>
                          ^
compilation terminated.
make: *** [test/demo_ivfpq_indexing_gpu] Error 1

Ubuntu 14.04, Titan X, Cuda-8.0

Can anyone help?

**Comment by beauby** [comment]
@albalab Could you post your `makefile.inc`? Looks like you don't have cuda installed in a standard path.

**Comment by albalab** [comment]
This is my makefile.inc

```
CXX          = g++ -std=c++11
CXXCPP       = g++ -std=c++11 -E

CPPFLAGS     = -DFINTEGER=int 
CXXFLAGS     = -fPIC -fopenmp -m64 -Wno-sign-compare -g -O3 -Wall -Wextra
CPUFLAGS     = -msse4 -mpopcnt
LDFLAGS      = -fopenmp 
LIBS         = -lopenblas -llapack 
PYTHONCFLAGS = -I/home/alexander/anaconda2/include/python2.7 -I/home/alexander/anaconda2/include/python2.7 -I/home/alexander/.local/lib/python2.7/site-packages/numpy/core/include

NVCC         = /usr/local/cuda/bin/nvcc
NVCCLDFLAGS  = -L/usr/local/cuda/lib64 
NVCCLIBS     = -lcudart -lcublas -lcuda 
CUDAROOT     = /usr/local/cuda
CUDACFLAGS   = -I/usr/local/cuda/include 
NVCCFLAGS    = -I $(CUDAROOT)/targets/x86_64-linux/include/ \
-Xcompiler -fPIC \
-Xcudafe --diag_suppress=unrecognized_attribute \
-gencode arch=compute_35,code="compute_35" \
-gencode arch=compute_52,code="compute_52" \
-gencode arch=compute_60,code="compute_60" \
-gencode arch=compute_61,code="compute_61" \
-lineinfo \
-ccbin $(CXX) -DFAISS_USE_FLOAT16

OS = $(shell uname -s)

SHAREDEXT   = so
SHAREDFLAGS = -shared

ifeq ($(OS),Darwin)
	SHAREDEXT   = dylib
	SHAREDFLAGS = -dynamiclib -undefined dynamic_lookup
endif

MKDIR_P      = /bin/mkdir -p
PYTHON       = python
SWIG         = 

prefix      ?= /usr/local
exec_prefix ?= ${prefix}
libdir       = ${exec_prefix}/lib
includedir   = ${prefix}/include

```

**Comment by mdouze** [comment]
Please try to adapt the include flags.
