### ISSUE TITLE
[docs] Wrong docstring of eigen_power in PCAMatrix

### ISSUE THREAD

**Issue by asanakoy** [facebookresearch/faiss#559]
I found a confusing comment.   
It made me dig into the sources to understand that the [comment](https://github.com/facebookresearch/faiss/blob/master/VectorTransform.h#L137)  about the meaning of `eigen_power` in `PCAMatrix`  was just worng.
It says that to apply whitening you need to set `eigen_power=-2`. But it should be **-0.5**!

The correct description:
If eigen_power == 0: then no whitening will be applied,
elif  eigen_power == **-0.5**: then do **PCA whitening**.

 https://github.com/facebookresearch/faiss/blob/master/VectorTransform.h#L137

**Comment by mdouze** [comment]
Absolutely! Thanks for flagging.

**Comment by mdouze** [comment]
Will be fixed in next version. Closing.
