### ISSUE TITLE
Pick features from index [python]

### ISSUE THREAD

**Issue by HengDing890** [facebookresearch/faiss#56]
Hi everyone, is there a way to pick features from index file? 

Assuming that I have a large dataset xb, and I have save the index to a file PATH.
It seems that faiss has stored xb to the index?

```
index = faiss.IndexFlatL2(d)
index.add(xb)
faiss.write_index(index, PATH)
```

Then I load the index, and want to obtain xb[0] from the index.
```
index = faiss.read_index(PATH)
xb[0] = ?
```

**Comment by mdouze** [comment]
Hi 

You can use

```python
vector_no = 0
vec = np.empty(index.d, dtype='float32')
index.reconstruct(vector_no, faiss.swig_ptr(vec))
```

this uses the low-level vector access, since the `reconstruct` function does not have a high-level Python wrapper.

**Comment by shekkizh** [comment]
This hack doesn't seem to work now. 
`TypeError: replacement_reconstruct() takes exactly 2 arguments (3 given)`
Is this still the best way to access xb saved in index?
