### ISSUE TITLE
Segmentation fault and other errors

### ISSUE THREAD

**Issue by ghostboyzone** [facebookresearch/faiss#562]
# Summary

### Problem One:

continuous add data into index  (use `add_with_ids`),  index definition is below,  may have a probability to produce a segmentation fault, and no other error message can get

```
dimensions = 4096
nlist = 50 
quantizer = faiss.IndexFlatL2(dimensions)
myIndex = faiss.IndexIVFFlat(quantizer, dimensions, nlist, faiss.METRIC_L2)
```

```
Segmentation fault
```

### Problem Two:

Error occurs while delete data from index (use `remove_ids`), instable reappearance

```
python3: IndexIVF.cpp:130: virtual const uint8_t* faiss::InvertedLists::get_single_code(size_t, size_t) const: Assertion `offset < list_size (list_no)' failed.
```

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by beauby** [comment]
@ghostboyzone Could you provide the actual code that is crashing? Otherwise we can't help you. Also, are you adding/removing concurrently?

**Comment by ghostboyzone** [comment]
core code is below 

```
# 1. first train base index

dimensions = 4096
nlist = 50 
quantizer = faiss.IndexFlatL2(dimensions)
myIndex = faiss.IndexIVFFlat(quantizer, dimensions, nlist, faiss.METRIC_L2)
myIndex.train(arrData)
if myIndex.is_trained:
    faiss.write_index(myIndex, "4096_50.baseidx")

# 2. use trained index, provide a http restful service, add data with http request 

baseIndex = faiss.read_index("4096_50.baseidx")
myIndex = faiss.clone_index(baseIndex)

if id in gMap:
    myIndex.remove_ids(np.array([id]))

myIndex.add_with_ids(np.array([data]), np.array([id]))
```



[data.zip](https://github.com/facebookresearch/faiss/files/2278220/data.zip)

**Comment by ghostboyzone** [comment]
Concurrency request  may cause  add or delete at the same time , is this the reason ?

**Comment by beauby** [comment]
As stated on the [wiki](https://github.com/facebookresearch/faiss/wiki/FAQ#questions-on-the-api):
> Concurrent searches are supported for the CPU code, but not the GPU code. Concurrent search/add or add/add are not supported. There is no locking mechanism in place to protect against this, so the calling code should maintain a lock.

**Comment by ghostboyzone** [comment]
got it , thank you very much
