### ISSUE TITLE
provide CUDA9.2 conda build?

### ISSUE THREAD

**Issue by mingwugmail** [facebookresearch/faiss#564]
https://developer.nvidia.com/cuda-toolkit-archive

 CUDA Toolkit 9.2 (March 2018) has been release for some time now, can we provide CUDA9.2 conda build?

Also for Ubuntu 18.04.

Thanks.

**Comment by mdouze** [comment]
We provide pre-compiled Faiss only for a limited number of platforms. 
If Cuda 9.2 is very important for you, please compile Faiss yourself.
CC: @ailzhang

**Comment by ailzhang** [comment]
Yea we don't support cuda9.2 in the current release. We might consider adding it in a month or so if there are enough requests.  Also cc: @beauby since he is taking over the conda package builds. 

(@mdouze the ETA is for our driver upgrade).

**Comment by mdouze** [comment]
Closing.
