### ISSUE TITLE
Question: Sharding on GPU with flat indexes?

### ISSUE THREAD

**Issue by chrisjmccormick** [facebookresearch/faiss#569]
I am performing benchmarks on the flat (brute force) GPU indexes in FAISS and looking at larger dataset sizes in particular (10Ms - 100Ms vectors). I've noticed that FAISS supports multiple GPUs, but _when using flat indexes_ it only supports _cloning_ of the dataset to multiple GPUs and not sharding. This puts a significant limit on the maximum dataset size supported--the dataset must fit within the memory of a single GPU and cannot be spread across multiple GPUs.

I wanted to see if there was perhaps a workaround to this--here are a couple ideas I had:

1. IVF indexes _do support_ sharding on the GPU; is there perhaps a way to configure an IVF index so that it's effectively a flat index (brute force search)? 
2. Could I launch multiple threads, each running an IndexFlatL2 instance on a different GPU? I could then shard the dataset myself and combine the results from all the GPUs myself.

Thanks for your help!

**Comment by mdouze** [comment]
Yes this is just a limitation of the `cpu_to_gpu` family of functions. I will update it to support that use case. About your questions: 

1. an IVFFlat with a single centroid is equivalent to a flat index, just slower

2. yes you can but it would be inefficient

**Comment by chrisjmccormick** [comment]
Thanks, Matthijs, really appreciate it!
Do you have a rough idea when the feature would be ready?
Thanks again,
Chris

**Comment by mdouze** [comment]
This week. Here is the relevant patch, in case you're really in a hurry: 
https://gist.github.com/mdouze/7dcfd1b2fc199358ff7878be2a975354

**Comment by chrisjmccormick** [comment]
Fantastic, thank you!!

**Comment by mdouze** [comment]
Merged in 1.4.0

**Comment by chrisjmccormick** [comment]
Hi Matthijs,
Will version 1.4.0 be [pushed to anaconda](https://anaconda.org/pytorch/faiss-gpu) soon? 
Thanks,
Chris
