### ISSUE TITLE
How to read out the stored vectors from faiss index in python?

### ISSUE THREAD

**Issue by HorsonLiu** [facebookresearch/faiss#571]
There seems to be no method to read out the stored vectors from faiss index  in python, such as index[0] to get the first vector.

**Comment by HorsonLiu** [comment]
My index type is IVF,Flat

**Comment by mdouze** [comment]
See https://github.com/facebookresearch/faiss/wiki/Special-operations-on-indexes#reconstructing-vectors-from-an-index

**Comment by HorsonLiu** [comment]
Thanks!
