### ISSUE TITLE
How to distribute multiple index into different gpus?

### ISSUE THREAD

**Issue by universewill** [facebookresearch/faiss#572]
I have got thousands of faiss indexes, and they are as large as 30GB in total.
I want to distribute them in to four gpus, how can i do that?

For example, i have four index: a, b, c, d.
And i want a index in gpu 0, b index in gpu 1, and c in gpu 2, d in gpu3.

**Comment by mdouze** [comment]
When you create the GPU index or transfer it with `index_cpu_to_gpu` you indicate the gpu id (0..3).
