### ISSUE TITLE
How can I save centroid of ProductQuantizer in Python ?

### ISSUE THREAD

**Issue by ianzhang1988** [facebookresearch/faiss#575]
# My Problem
I want to save the model of ProductQuantizer for further use, As I understand that means saving centroids of the ProductQuantizer. But can't find a way to do it in Python.

> print pq.centroids  
print type(pq.centroids)  

got these
><faiss.swigfaiss.FloatVector; proxy of <Swig Object of type 'std::vector< float > *' at 0x7fbab9f600f0> >  
<class 'faiss.swigfaiss.FloatVector'>  

pq.centroids[0] raise exception
> TypeError: 'FloatVector' object does not support indexing

# My Question
How can I get these data out of faiss.swigfaiss.FloatVector, And how can I read these data and set it back?  

Any help would be appreciated

**Comment by mdouze** [comment]
You can get the centroids via 
```
centroids = faiss.vector_to_array(pq.centroids).reshape(pq.M, pq.ksub, pq.dsub)
```

**Comment by beauby** [comment]
Closing as the issue seems to be resolved.

**Comment by mdouze** [comment]
In C++ you can access `pq.centroids` directly. See https://github.com/facebookresearch/faiss/blob/master/impl/ProductQuantizer.h#L54

**Comment by beiyouwangzi** [comment]
How can I have the centroid of Ivf in c++?
