### ISSUE TITLE
Can FAISS be used On AMD GPU?

### ISSUE THREAD

**Issue by piyushmanglani08** [facebookresearch/faiss#576]
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
Yes. What makes you think it can't?

**Comment by mdouze** [comment]
sorry, AMD CPUs are supported but not GPUs. 
Faiss GPU is written in  Cuda and it would require a lot of work to translate it to another language + optimize it again.
@wickedfoo ?

**Comment by piyushmanglani08** [comment]
That is the reason I asked as I didn't found any thing on AMD gpu.

**Comment by piyushmanglani08** [comment]
CUDA has been developed specifically for NVIDIA GPUs. Hence, CUDA can not work on AMD GPUs. ... AMD GPUs won't be able to run the CUDA Binary (.cubin) files, as these files are specifically created for the NVIDIA GPU Architecture that you are using.So if I have AMD GPU I won't be able to test the GPU code so how to resolve this I guess a lot of people are using AMD GPU.

**Comment by wickedfoo** [comment]
Sorry just seeing this now. This would take some time. I don't have high hopes that the AMD cross-compiler could deal with some of the Faiss GPU code. Closing since this will probably not happen.

**Comment by vird** [comment]
Maybe AMD HIP can be used for port CUDA to AMD?

**Comment by mnorris11** [comment]
This is quite old, but just to close the loop (because this thread is the top Github result on Google): now with ROCm, Faiss can be run on AMD GPUs! Refer to https://github.com/facebookresearch/faiss/blob/928333c6ab54a1a97bcf23f14d305e61d82434f6/INSTALL.md?plain=1#L168 for instructions.
