### ISSUE TITLE
1.4.0 not available on conda pytorch channel 

### ISSUE THREAD

**Issue by lucapinello** [facebookresearch/faiss#579]
# Summary

When are you going to release 1.4.0 on the conda pytorch channel? Unfortunately, the version 1.3.0 doesn't work properly on OSX (this was already reported)

# Platform

OS: 

OSX

Faiss version: 

1.3.0 from conda pytorch channel

Faiss compilation options: 

Running on:
- [ X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X ] Python

# Reproduction instructions

Kernel restart

**Comment by mdouze** [comment]
The conda for 1.4.0 will be made available this week. 
What report do you refer to when you say 1.3.0 does not work properly?

**Comment by lucapinello** [comment]
Thanks for the quick reply, looking forward!

I was referring to what you have reported here: https://github.com/facebookresearch/faiss/wiki/Troubleshooting#crashes-in-pure-python-code

**Comment by beauby** [comment]
@lucapinello Note that the issue you are referring to is not OSX specific and that there are easy workarounds, though indeed this is fixed in 1.4.

**Comment by lucapinello** [comment]
Hi Lucas,

Thanks you are indeed right! I had a similar problem today on another
conda env under linux so it is not osx specific as you have mentioned.
