### ISSUE TITLE
 remove_ids  function's return  in index IVFPQ

### ISSUE THREAD

**Issue by fwz-fpga** [facebookresearch/faiss#582]
I use remove_ids function in index IVFPQ. 
 But the function returns 1 or 2 or -1. 
 I want to know what's the difference between 1 and 2.

**Comment by beauby** [comment]
It should return the number of vectors that were removed (c.f. https://github.com/facebookresearch/faiss/blob/master/IndexIVF.cpp#L272), so it should never be -1, right @mdouze?

**Comment by fwz-fpga** [comment]
I have tested the remove_ids function in IVFPQ. When the id doesn't exist, the function will return -1.

**Comment by mdouze** [comment]
@beauby right
@fwz-fpga could you post a short reproduction code?

**Comment by fwz-fpga** [comment]
Sorry, I find that the returned -1 is what I have defined before......And it's truly return the number of vectors that were removed.
But I find another interesting result when I use the remove_ids function before search. 
run the code below
------------------------------------
import faiss
import numpy as np

d=128
nlist=100
m=8
quantizer = faiss.IndexFlatL2(d) 
index = faiss.IndexIVFPQ(quantizer, d, nlist, m, 8)
np.random.seed(1234)
xb = np.random.random((10000, d)).astype('float32')
index.train(xb)

index.add(xb)
print("index.ntotal",index.ntotal)

test_1 = np.random.random((1, 128)).astype('float32')
test_2 = np.random.random((1, 128)).astype('float32')

index.add(test_1)
index.add(test_2)

D,I=index.search(test_1,3)
print("D",D)
print("Id",I)
D,I=index.search(test_2,3)
print("D",D)
print("Id",I)

print("remove test_1,then add")
index.remove_ids(np.array([10000]))
index.add(test_1)

D,I=index.search(test_1,3)
print("D",D)
print("Id",I)

D,I=index.search(test_2,3)
print("D",D)
print("Id",I)
---------------------------------

It shows that search the vectors test_1 and test_2 will  return the same id 10001 after remove_ids&add.

**Comment by fwz-fpga** [comment]
@mdouze 
Have you run the code, I don't know where goes wrong... Why search two vectors will return the same sequential id.

**Comment by beauby** [comment]
@fwz-fpga What seems to be the issue here?

**Comment by fwz-fpga** [comment]
@beauby  I know the problem.
I have read the code [https://github.com/facebookresearch/faiss/blob/master/IndexIVF.cpp](url). The remove_ids function was realized by copy the last vectors(both sequential id and code) to cover the memory where should be removed. But in this way, after a new vectors added there will be two same id in the vector<idx_t> ids.
In my project, the returned sequential id will be used as a index to search other list, so if the search result for two different vectors return the same id, the next search result will be wrong. 
Maybe I should use add_with_ids function ,which wouldn't create this issue.
