### ISSUE TITLE
remove ids not supported by gpu index?

### ISSUE THREAD

**Issue by universewill** [facebookresearch/faiss#584]
I test faiss gpu index, and it can execute add() function, but encounters error when execute remove_ids() function.

How can i remove ids directly with the gpu index?

**Comment by mdouze** [comment]
The remove functionality is not supported on GPU. 
I flag it as enhancement, but it is not on our priority list.

**Comment by Kaixhin** [comment]
Flagging this as a requested feature for me as well. Working with an [algorithm](https://arxiv.org/abs/1703.01988) with a large bottleneck from frequent single item lookups, and shifting from CPU to GPU is ~5x speedup. Adding `remove_ids` to GPU would make it much easier to deal with streaming data like this.

**Comment by mdouze** [comment]
Would this approach be suitable for your case? 
https://github.com/facebookresearch/faiss/wiki/Brute-force-search-without-an-index

**Comment by Kaixhin** [comment]
@mdouze thanks for the pointer! I could certainly use this to replace my current prototype code (using `IndexFlatL2`), but in general I suppose the aim would be to use more intelligent indices (for example the paper I linked uses kd-trees), perhaps rebuilding the index at points.

**Comment by mdouze** [comment]
KDTree is usually not very efficient to search in high dimensional spaces. 
But I understand the point. Let's reopen the issue.

**Comment by wickedfoo** [comment]
Which GPU index do you want remove on the most?

**Comment by senhuiguo** [comment]
@wickedfoo GpuIndexIVFPQ hands down

**Comment by Kaixhin** [comment]
I would use it for FlatL2 but as pointed out above it's not the real benefit of providing this feature on GPU. There's been a couple of issues on this which are best to refer to.

**Comment by wenqf11** [comment]
May I ask when will `remove_ids` becomes supported by gpu Index?

**Comment by safead** [comment]
Same question here...

**Comment by zsz00** [comment]
May I ask when will remove_ids becomes supported by gpu Index?

**Comment by asadoughi** [comment]
We expect the removal pattern to be satisfied by filtering followed by compaction in most ANN applications.
