### ISSUE TITLE
test_index_accuracy tests failing on master

### ISSUE THREAD

**Issue by orf** [facebookresearch/faiss#588]
Faiss version: e57270600a49fea2f7e86a7214755c4721be6602

Faiss compilation options: `make`

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

On master the `test_index_accuracy` tests appear to fail with a SWIG error on both MacOS and Linux. For example:

```
======================================================================
ERROR: test_IndexIVFPQ (test_index_accuracy.IndexAccuracy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/onfido/faiss_prebuilt/faiss/tests/test_index_accuracy.py", line 121, in test_IndexIVFPQ
    ivfpq = faiss.IndexIVFPQ(faiss.IndexFlatL2(d), d, ncentroids, M, 8)
  File "/home/travis/build/onfido/faiss_prebuilt/faiss/python/build/lib/faiss/__init__.py", line 320, in replacement_init
    original_init(self, *args)
  File "/home/travis/build/onfido/faiss_prebuilt/faiss/python/build/lib/faiss/swigfaiss.py", line 3877, in __init__
    this = _swigfaiss.new_IndexIVFPQ(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_IndexIVFPQ'.
  Possible C/C++ prototypes are:
    faiss::IndexIVFPQ::IndexIVFPQ(faiss::Index *,size_t,size_t,size_t,size_t)
    faiss::IndexIVFPQ::IndexIVFPQ()
```

A very similar argument error occurs in:

- `test_IndexPQ_ip`
- `test_IndexPQ`
- `test_IndexPQ_refined`
- `test_polysemous`

**Comment by mdouze** [comment]
https://github.com/facebookresearch/faiss/blob/master/tests/test_index_accuracy.py#L62

should be `int(d/8)` to support braindead Python 3 division.

**Comment by orf** [comment]
Or `d//8`. What's braindead about it, out of interest?

**Comment by mdouze** [comment]
Not `n//8` which actually means *float* division in Python 2 (reason 1 for braindead)
reason 2 is that only inferior languages like Matlab and Lua produce floats from integer operations
reason 3 is that division is used more often as a complement of modulo than of multiplication.

**Comment by beauby** [comment]
Closing as #589 was merged.
