### ISSUE TITLE
Segmentation fault on TITAN X (Pascal)

### ISSUE THREAD

**Issue by fighting-liu** [facebookresearch/faiss#59]
python benchs/bench_gpu_sift1m.py

load data
load GT
============ Exact search
add vectors to index
warmup
benchmark
k=1 0.804 s, R@1 0.9914
k=2 0.786 s, R@1 0.9935
k=4 0.907 s, R@1 0.9935
k=8 0.676 s, R@1 0.9935
k=16 0.912 s, R@1 0.9935
k=32 0.731 s, R@1 0.9935
k=64 0.900 s, R@1 0.9935
k=128 0.752 s, R@1 0.9935
k=256 0.986 s, R@1 0.9935
k=512 2.125 s, R@1 0.9935
k=1024 2.169 s, R@1 0.9935
============ Approximate search
train
WARNING clustering 100000 points to 4096 centroids: please provide at least 159744 training points
add vectors to index
Segmentation fault (core dumped)

**Comment by mdouze** [comment]
Hi 

I can't repro this.

**Comment by mdouze** [comment]
https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls

**Comment by jegou** [comment]
No further comment on this cant-repro issue.
Closing.
