### ISSUE TITLE
If I trained an index twice with two different datasets, what kind of query vectors should I use?

### ISSUE THREAD

**Issue by liqima** [facebookresearch/faiss#597]
If I have two datasets, and they have different distribution, of course they have the same dimension.
data1 has distribution type 1, and data2 has distribution type 2.
If I do this:

```
d = 1000 
quantizer = faiss.IndexFlatL2(d)
index = faiss.IndexIVFFlat(quantizer, d, nlist)
index.train(data1)
index.add(data1)
index.train(data2)
index.add(data2)   # can I do this?
```

after that, I use query vector to search. 
so, here is my question: **what type of distribution should query vector have**? type 1? or type 2?

another question,  I saw this "The train method of the IndexIVF adds the centroids to the flat index", if I retrain the index, will centroids be replaced?
if I do this:
```
d = 1000
quantizer = faiss.IndexFlatL2(d)
index = faiss.IndexIVFFlat(quantizer, d, nlist)
index.train(data2)
```
and this:
```
d = 1000
quantizer = faiss.IndexFlatL2(d)
index = faiss.IndexIVFFlat(quantizer, d, nlist)
index.train(data1)
index.train(data2)
```

does this two methods create the same index file?
Very thanks for your reply.

**Comment by beauby** [comment]
1. You should not train a given index twice. You probably want to have two separate indexes.
2. No, you can only train it once (c.f. https://github.com/facebookresearch/faiss/blob/master/IndexIVF.cpp#L60).

**Comment by liqima** [comment]
Thanks for your reply.
I learned from this file [test_index_composite.py
](https://github.com/facebookresearch/faiss/blob/master/tests/test_index_composite.py#L35) and merged several .index files.
If I have two dataset data1 and data2, they may have different distributions.
```
quantizer = faiss.IndexFlatL2(d)
index1 = faiss.IndexIVFFlat(quantizer, d, nlist)
index1.train(data1)
index1.add(data1)

index2 = faiss.IndexIVFFlat(quantizer, d, nlist)
index2.train(data2)  # maybe it's not necessary
index2.add(data2)

off_set = index1.ntotal
index1.merge_from(index2, off_set)  # now index1 have all the data1 and data2
```
after this, I get a merged index which include dataset data1 and data2.
here is my question: because data1 and data2 may have different distributions, if I wish the merged index hold the total dataset(data1 + data2)' distribution, need I to re-train this merged index using (data1 + data2) before search?

**Comment by beauby** [comment]
Merging IVF indexes is intended to be used for merging same-distribution indexes, with exactly the same clustering centroids. So unless that is your case, you will have to re-train an index on (a subset of) `data1 + data2`.
