### ISSUE TITLE
How can I obtain vectors from an index file?

### ISSUE THREAD

**Issue by liqima** [facebookresearch/faiss#598]
If I have a dataset like this
xb = [ [1, 2, ..., 3, 4], [2, 3, ..., 4, 5], ... [3, 4, ..., 5, 6] ] , and I add xb to create an index.
```
quantizer = faiss.IndexFlatL2(d)
index = faiss.IndexIVFFlat(quantizer, d, nlist)
index.train(xb)
index.add(xb)
faiss.write_index(index, "current_index.index")  # now I have an index file
```
after somedays I lost the dataset xb, but luckily I have the current_index.index file. So can I obtain xb data from this .index file? How？
Thanks for your reply.

**Comment by beauby** [comment]
You can reconstruct the vectors from the index using the [`reconstruct()`](https://github.com/facebookresearch/faiss/blob/master/Index.h#L154) method (or it's batch analog `reconstruct_n()`). In the case of an `IndexIVFFlat`, this will give you the exact vectors.

**Comment by yuyifan1991** [comment]
> You can reconstruct the vectors from the index using the [`reconstruct()`](https://github.com/facebookresearch/faiss/blob/master/Index.h#L154) method (or it's batch analog `reconstruct_n()`). In the case of an `IndexIVFFlat`, this will give you the exact vectors.

If I have the hash ids for index, can I reconstruct the vectors? I use the _IndexIVFFlat_ and _index.add_with_ids(xb,ids_xb)_
