### ISSUE TITLE
some install questions about faiss

### ISSUE THREAD

**Issue by ahappycutedog** [facebookresearch/faiss#605]
Summary

I am not very clear about the order of installation. If  I use conda to install（openblas or MKL way）,Is it necessary to compile c++?  

Platform
ubuntu 16.04

Faiss compilation options: MKL

Running on:
 CPU

Interface: 
 Python

Reproduction instructions

1.I used Anaconda (mkl) to install  and then got an error when I run:  ./misc/test_blas:
 "./misc/test_blas: error while loading shared libraries: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory"
What is the reason for this? I looked at the following directory, is it not compiled?
"test_blas  test_blas.cpp"

2.Then go to build faiss, it seems no problem
But in Testing Faiss, run the "demos/demo_ivfpq_indexing" and "make test‘’.
The errors are：
"-bash: demos/demo_ivfpq_indexing: No such file or directory"
"make -C python build
make[1]: Entering directory '/faiss/python'
python setup.py build
running build
running build_py
copying faiss/swigfaiss.py -> build/lib.linux-x86_64-2.7/faiss
copying faiss/__init__.py -> build/lib.linux-x86_64-2.7/faiss
copying faiss/_swigfaiss.so -> build/lib.linux-x86_64-2.7/faiss
make[1]: Leaving directory '/faiss/python'
make -C tests run
make[1]: Entering directory '/faiss/tests'
./tests
./tests: error while loading shared libraries: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory
Makefile:15: recipe for target 'run' failed
make[1]: *** [run] Error 127
make[1]: Leaving directory '/faiss/tests'
Makefile:66: recipe for target 'test' failed
make: *** [test] Error 2"

Of course, not working in the example test.

I have installed it many times, and have not solved this problem.Or what is the right way to install it?
Thanks!

**Comment by beauby** [comment]
If you use conda to install Faiss, you don't need to worry about compiling anything.
If you want to run the test suit, or the C++ demos, you'll need to compile Faiss (using `./configure && make`).

**Comment by ahappycutedog** [comment]
> If you use conda to install Faiss, you don't need to worry about compiling anything.
> If you want to run the test suit, or the C++ demos, you'll need to compile Faiss (using `./configure && make`).

 Thank you! But I have a question, if I just install it and don't compile it, will it not affect the normal use of faiss?

**Comment by beauby** [comment]
Closing, as the issue seems to be resolved. Feel free to keep commenting/reopen if needed.
