### ISSUE TITLE
Error in void faiss::write_index(const faiss::Index*, faiss::IOWriter*) at index_io.cpp:343

### ISSUE THREAD

**Issue by hanama** [facebookresearch/faiss#607]
Hi,

I'm using:
index = faiss.IndexFlatL2(d)
index2 = faiss.IndexIDMap(index)

And seems that it works well, including:
index2.add_with_ids(x, ids)

But when I'm trying to do:
faiss.write_index(index2, "file.index")

I got this error message:
faiss.write_index(index2, "file.index")
RuntimeError: Error in void faiss::write_index(const faiss::Index*, faiss::IOWriter*) at index_io.cpp:343: Error: 'ret == (size)' failed: write error

Can you assist please?

**Comment by mdouze** [comment]
This is probably due to a disk full or unreliable file system. 
But it is true that we could display a more informative error message.

**Comment by mdouze** [comment]
Specific error messages will be provided in the next version of Faiss. 
Closing.
