### ISSUE TITLE
problems on two GPUs

### ISSUE THREAD

**Issue by zjuchenwei** [facebookresearch/faiss#608]
when I test on my first GPU Faiss is ok
but when i test  on the second GPU on the same machine, it has trouble. I just set dev_no=0 or 1 and
do not change anything else 

![p1](https://user-images.githubusercontent.com/4024185/46462701-b0fb3180-c7f4-11e8-9a87-ee96f558f19f.jpg)

**Comment by zjuchenwei** [comment]
problem is solved. please close the issue.

**Comment by beauby** [comment]
@zjuchenwei Glad that it is solved. Would you mind explaining how you fixed it in case someone else ends up in the same situation?

**Comment by zjuchenwei** [comment]
Add DeviceScope scope(device_); in the Function, and the problem is solved
