### ISSUE TITLE
how to search with cosine similarity

### ISSUE THREAD

**Issue by YaaoTu** [facebookresearch/faiss#61]
hi, I only see two choices for searching:  METRIC_INNER_PRODUCT, METRIC_L2. how can I search with cosine similarity?

**Comment by mdouze** [comment]
Hi 

Please L2-normalize the vectors before adding and searching, then search with METRIC_INNER_PRODUCT.

**Comment by yhpku** [comment]
@mdouze ，I have the same question. But how to search with METRIC_INNER_PRODUCT? can you give example and code? thanks.

**Comment by billkle1n** [comment]
@yhpku something like that:

```python
from faiss import normalize_L2

# ...

index.train(normalize_L2(training_vectors))
index.index(normalize_L2(index_vectors))
index.search(normalize_L2(search_vectors), 5)
```

**Comment by mdouze** [comment]
The metric inner product flag is set when the index is built.

**Comment by 13293824182** [comment]
I have a question, when i try normalize_L2(dest_array_one) , i get the error:
 File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/faiss/lib/python2.7/site-packages/faiss/__init__.py", line 523, in normalize_L2
    fvec_renorm_L2(x.shape[1], x.shape[0], swig_ptr(x))
TypeError: in method 'fvec_renorm_L2', argument 3 of type 'float *'

**Comment by moscowart** [comment]
@13293824182 make sure your array is of type float32

**Comment by pranavnijampurkar33** [comment]
Just adding example if noob like me came here to find how to calculate the Cosine similarity from scratch

import faiss
dataSetI = [.1, .2, .3]
dataSetII = [.4, .5, .6]
#dataSetII = [.1, .2, .3]

x = np.array([dataSetI]).astype(np.float32)
q = np.array([dataSetII]).astype(np.float32)
index = faiss.index_factory(3, "Flat", faiss.METRIC_INNER_PRODUCT)
index.ntotal
faiss.normalize_L2(x)
index.add(x)
faiss.normalize_L2(q)
distance, index = index.search(q, 5)
print('Distance by FAISS:{}'.format(distance))

#To Tally the results check the cosine similarity of the following example

from scipy import spatial


result = 1 - spatial.distance.cosine(dataSetI, dataSetII)
print('Distance by FAISS:{}'.format(result))

**Comment by pzdkn** [comment]
do I need to use this function `faiss.normalize_L2` or can I use a numpy function for normalization ?
what's the advantage of using it over writing it yourself?
