### ISSUE TITLE
Training of IMI2x14 while keeping memory usage low

### ISSUE THREAD

**Issue by mingruimingrui** [facebookresearch/faiss#616]
Hi I've got a question about memory efficient training of an inverted multi index!

Given the following,
- a dataset of [1e9~10, 4096] fp32
- an IMI with 14 bit encoding (and m=2)  (which results in (2**14)**2 = 2.68e8 generated centroids)

I read from the guides that you typically would like to have about 100 * num_centroids for training but it would be expensive to keep all that in memory all at once.

What would be the advisable way to train an IMI for such a dataset?

**Comment by mdouze** [comment]
You will need around 1M vectors to train, see 

https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index#if-100m---1b-imi2x14

**Comment by mingruimingrui** [comment]
Thanks! It's really helpful!
