### ISSUE TITLE
can it be used on Windows

### ISSUE THREAD

**Issue by Sandy4321** [facebookresearch/faiss#617]
can it be used on Windows 
I use only Python

# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
It is project to port it on windows. 
https://github.com/facebookresearch/faiss/projects
PRs welcome!

**Comment by mdouze** [comment]
was asked before #415
