### ISSUE TITLE
 cpu consumption is very large

### ISSUE THREAD

**Issue by djy4713** [facebookresearch/faiss#62]
when i call the "search" function many times , cpu consumption continues to increase！

**Comment by mdouze** [comment]
Hi 

Could you give more details?

**Comment by djy4713** [comment]
import numpy as np
d = 64                           # dimension
nb = 1000000                      # database size
nq = 100                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

import faiss                   # make faiss available
index = faiss.IndexFlatL2(d)   # build the index
index.add(xb)                  # add vectors to the index

k = 4                          # we want to see 4 nearest neighbors
for i in range(100):
    D, I = index.search(xq, k)     # actual search

you can try

**Comment by djy4713** [comment]
**I run the following code , and found that CPU consumption continued to increase**

import numpy as ## np
d = 64                           # dimension
nb = 1000000                      # database size
nq = 100                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.
import faiss                   # make faiss available
index = faiss.IndexFlatL2(d)   # build the index
index.add(xb)                  # add vectors to the index
k = 4                          # we want to see 4 nearest neighbors
for i in range(100):
    D, I = index.search(xq, k)     # actual search

**Comment by mdouze** [comment]
What do you mean with "CPU consumption" ? 
What do you measure and what did you expect?
I ran your code and saw no memory leak. Please check 
https://github.com/facebookresearch/faiss/wiki/Troubleshooting#slow-brute-force-search-with-openblas
as well

**Comment by djy4713** [comment]
Sorry I may not express it clearly.   there are no memory leak, just cpu usage.
![439f39c1-7f86-4a3a-a602-f605d4d7aaa6](https://cloud.githubusercontent.com/assets/8231349/24702245/868f794c-1a30-11e7-80b6-60b1e429c3bf.png)
I found that the cpu usage of the process  increased to 3000% (my machine has 32 logic cpu cores)

**Comment by mdouze** [comment]
So you expect it to be at 3200% all the time? 
The number of queries is probably not large enough for that. Try increasing it to >= 4096

**Comment by djy4713** [comment]
I mean that 3000% is too large...is this normal?

**Comment by mdouze** [comment]
Faiss uses all cores if possible. If you want to run it single-threaded, call `faiss.omp_set_num_threads(1)` 
See also https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls

**Comment by djy4713** [comment]
thank you very much!
