### ISSUE TITLE
The  SIFT1B(BIGANN) dataset

### ISSUE THREAD

**Issue by ahappycutedog** [facebookresearch/faiss#627]
# Summary

We  trained your script file (python bench_gpu_1bn.py) on the BIGANN, and the search performed well.  However, I have a question about data sets. In addition to the necessary Base set and Query set, what are the main functions of the training set(learning set)? Is it possible to train directly with Base set? 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] Python

**Comment by beauby** [comment]
@ahappycutedog The training set for clustering has to have the same distribution as your database, otherwise you will get unbalanced clusters.

**Comment by beauby** [comment]
Note that you can use your database or a fraction of it to train the clustering.

**Comment by ahappycutedog** [comment]
> Note that you can use your database or a fraction of it to train the clustering.

Thanks
