### ISSUE TITLE
Error making demo_sift1M (Ubunt

### ISSUE THREAD

**Issue by shivajid** [facebookresearch/faiss#63]
faiss$  make tests/demo_sift1M
g++ -o tests/demo_sift1M -fPIC -m64 -Wall -g -O3  -msse4 -mpopcnt -fopenmp -Wno-sign-compare -Dnullptr=NULL -Doverride= -fopenmp tests/demo_sift1M.cpp libfaiss.a -g -fPIC  -fopenmp /usr/lib/libopenblas.so.0
tests/demo_sift1M.cpp: In function ‘float* fvecs_read(const char*, size_t*, size_t*)’:
tests/demo_sift1M.cpp:51:33: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fread(&d, 1, sizeof(int), f);
                                 ^
s
Sift files are listed below
/media/hdd1/faiss$ ls -l sift
total 563292
-rw-r--r-- 1 xx xx 516000000 Dec 15  2009 sift_base.fvecs
-rw-r--r-- 1 xx xx   4040000 Dec 15  2009 sift_groundtruth.ivecs
-rw-r--r-- 1 xx xx  51600000 Dec 15  2009 sift_learn.fvecs
-rw-r--r-- 1 xxx xx   5160000 Dec 15  2009 sift_query.fvecs

**Comment by mdouze** [comment]
Hi 

Please remove the -Wall flag from the compilation command line.

**Comment by mdouze** [comment]
This seems to fix the problem. Re-open if it is still there.
