### ISSUE TITLE
Faiss API

### ISSUE THREAD

**Issue by oguitart** [facebookresearch/faiss#633]
Hi All,

Is there a Faiss API? When I try to use some of the faiss methods I usually have questions about their parameters but I don't know where to find that information. If there are examples in the wiki, it is fine but there are many methods that are not explained in the wiki.
Thanks,

oriol

**Comment by mdouze** [comment]
The main source of documentation is in the Doxygen annotations of the C++ source. It can be browsed at
https://rawgit.com/facebookresearch/faiss/master/docs/html/namespacefaiss.html
Unfortunately, this is not exported automatically to Python, this is an open issue  #393

**Comment by oguitart** [comment]
Ok, thanks, Hopefully, the same kind of thing will be available in python.
