### ISSUE TITLE
How to limit the cpu utilization?

### ISSUE THREAD

**Issue by XiaXuehai** [facebookresearch/faiss#634]
The CPU utilization is 390% on my 4 cores cpu when searching frequently. How to limit the cpu utilization?
I tried the GPU, there is no improvement.

**Comment by XiaXuehai** [comment]
It's weird. I set `export OMP_NUM_THREADS=1`  in the` ~/.bashrc` file, it occupied 100%. But if  set OMP_NUM_THREADS>1, it occupied all cpu.

**Comment by quoniammm** [comment]
The CPU utilization is 450% on my 8 cores cpu when index building frequently, whether i can use the same way? @beauby
