### ISSUE TITLE
Does faiss::IndexHNSW support inner_product metric?

### ISSUE THREAD

**Issue by superlong** [facebookresearch/faiss#637]
# Summary
Currently, I use IndexHNSWFlat and it uses IndexFlatL2 which is hard coded, how does IndexHNSW support inner_product metric? Thanks in advance!

The code i saw doesn't supply MetricType parameter.

# Platform

OS: 

Faiss version: 
a91a24e77a3e16f0336eb8b70770bdf5daa1154e

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

**Comment by beauby** [comment]
`IndexHNSW` does not support the inner product metric.

**Comment by superlong** [comment]
Hi @beauby , thank you for your prompt reply.
