### ISSUE TITLE
Kmeans faiss distance

### ISSUE THREAD

**Issue by oguitart** [facebookresearch/faiss#639]
Hi,

We are wondering which metric you are using to calculate the distances in kmeans algorithm. We have realized that the calculated distances are not normalized since depending on the input data the distances varies a lot. We would like to normalize the obtained distances so that the 1 value means the furthest distance. Is that possible? We could normalize it by knowing the maximum possible distance value but this seems very data dependent and it is difficult to guess it without knowing the used metric.
Thanks,

oriol

**Comment by mdouze** [comment]
In the kmeans algorithm, the distance used to assign a vector to a centroid is the L2 distance (squared). 

How to normalize distances is application-dependent.
