### ISSUE TITLE
Using centroids initialization in Clustering

### ISSUE THREAD

**Issue by sharthZ** [facebookresearch/faiss#64]
How can i set centroids for Clustering instead of random initialization?
I tried to set it manually:
```python
clus = faiss.Clustering(d, k)
...
clus.centroids = sanitize(cents) # cents is ndarray
```
but i got:

> Traceback (most recent call last):
>   File "benchs/bench_gpu_1bn.py", line 813, in <module>
>     index = get_populated_index(preproc)
>   File "benchs/bench_gpu_1bn.py", line 686, in get_populated_index
>     gpu_index, indexall = compute_populated_index_2(preproc)
>   File "benchs/bench_gpu_1bn.py", line 626, in compute_populated_index_2
>     indexall = prepare_trained_index(preproc)
>   File "benchs/bench_gpu_1bn.py", line 542, in prepare_trained_index
>     coarse_quantizer = prepare_coarse_quantizer(preproc)
>   File "benchs/bench_gpu_1bn.py", line 516, in prepare_coarse_quantizer
>     centroids = train_coarse_quantizer(xt, ncent, preproc, centroids)
>   File "benchs/bench_gpu_1bn.py", line 498, in train_coarse_quantizer
>     clus.centroids = sanitize(cents)
>   File "/home/ivan/projects/faiss/swigfaiss_gpu.py", line 888, in <lambda>
>     __setattr__ = lambda self, name, value: _swig_setattr(self, Clustering, name, value)
>   File "/home/ivan/projects/faiss/swigfaiss_gpu.py", line 51, in _swig_setattr
>     return _swig_setattr_nondynamic(self,class_type,name,value,0)
>   File "/home/ivan/projects/faiss/swigfaiss_gpu.py", line 44, in _swig_setattr_nondynamic
>     if method: return method(self,value)
> TypeError: in method 'Clustering_centroids_set', argument 2 of type 'std::vector< float > *'

**Comment by mdouze** [comment]
Hi 

clus.centroids is a C++ vector not a Python array, you need to copy the data explicitly like:

```python
clus.centroids.resize(cents.size)
faiss.memcpy(clus.centroids.data(), faiss.swig_ptr(cents), cents.size * 4)
```
