### ISSUE TITLE
Will you please help me install Faiss on windows ?

### ISSUE THREAD

**Issue by chengerr** [facebookresearch/faiss#650]
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
https://github.com/facebookresearch/faiss/projects/2
We can help you if you want to undertake this.

**Comment by beauby** [comment]
Closing, as this is a duplicate of https://github.com/facebookresearch/faiss/issues/43.
