### ISSUE TITLE
Get index -1  when doing search on GPU

### ISSUE THREAD

**Issue by fabulousfeng** [facebookresearch/faiss#651]
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] GPU

Interface: 
- [ ] Python

# Reproduction instructions

 
Below is my code, I got -1 in Index I, which is strange, someone tells me what does -1 in index mean? Thank you.
```
import numpy as np

d = 100                           # dimension
nb = 6000000                      # database size
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
ns = len(xb)
k = 21
import faiss                     # make faiss available

res = faiss.StandardGpuResources()  # use a single GPU

faiss.normalize_L2(xb)


nlist = 2**12
quantizer = faiss.IndexFlatIP(d)
index_ivf = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_INNER_PRODUCT)

# make it an IVF GPU index
gpu_index_ivf = faiss.index_cpu_to_gpu(res, 0, index_ivf)

assert not gpu_index_ivf.is_trained
gpu_index_ivf.train(xb)        # add vectors to the index
assert gpu_index_ivf.is_trained

gpu_index_ivf.add(xb)          # add vectors to the index
print(gpu_index_ivf.ntotal)
gpu_index_ivf.nprobe = int(nlist/10)
_, I = gpu_index_ivf.search(xb[:ns], k)  # actual search
index = faiss.index_gpu_to_cpu(gpu_index_ivf)
faiss.write_index(index, "file.gpu.index")
for i in I:
    print(i)

```

**Comment by fabulousfeng** [comment]
Below is an example for one line
[4652 6844 5553 6670 5073 5849   -1   -1   -1   -1   -1   -1   -1   -1  -1   -1   -1   -1   -1   -1   -1]

**Comment by fabulousfeng** [comment]
@mdouze

**Comment by mdouze** [comment]
see 
https://github.com/facebookresearch/faiss/wiki/FAQ#what-does-it-mean-when-a-search-returns--1-ids
And yes add_with_ids is supported for GPU.

**Comment by fabulousfeng** [comment]
> see
> https://github.com/facebookresearch/faiss/wiki/FAQ#what-does-it-mean-when-a-search-returns--1-ids
> And yes add_with_ids is supported for GPU.

I see, it seems that I need to increase the nprobe and `gpu_index_ivf.nprobe = int(nlist/10) `may not work. However, when I use `ParameterSpace().set_index_parameter(index, 'nprobe', 100)`, it 
comes `NameError: name 'ParmeterSpace' is not defined`

**Comment by mdouze** [comment]
Prefix with `faiss.`

**Comment by mdouze** [comment]
Check syntax: 'ParmeterSpace' instead of 'ParameterSpace'

**Comment by fabulousfeng** [comment]
> ParmeterSpace

Problem solved, ParmeterSpace should be ParameterSpace. Should fix the [If you use GPU indices, replace ParameterSpace with GpuParmeterSpace.](https://github.com/facebookresearch/faiss/wiki/FAQ#how-can-i-set-nprobe-on-an-opaque-index)
