### ISSUE TITLE
Better contiguous array checking based on actual array type

### ISSUE THREAD

**Issue by cjnolet** [facebookresearch/faiss#653]
There are several places where the following is used in order to check that the input array is c-contiguous:

```python
assert x.flags.contiguous
n, d = x.shape
assert d == self.d
```

The problem is that other objects that follow Numpy's conventions, but do not necessarily implement all of the properties on Numpy's `flagsobj` are not able to be used.

If we, instead, used a helper function like the following, we could support `numpy.ndarray`, `cupy.ndarray` and `numba.cuda.cudadrv.devicearray.DeviceNDArray`:

```python
def verify_c_contiguous(x):
  if isinstance(x, numba.cuda.cudadrv.devicearray.DeviceNDArray):
    return x.is_c_contiguous()
  else
    return x.flags.c_contiguous
```

I understand this introduces more dependencies. Another option could be to document the requirement for the input array to be c-contiguous and put it on the users to follow through. I have filed a bug with Numba to support the `contiguous` property in their `numba.cuda.cudadrv.devicearray.DeviceNDArray` object (as their `numba.ndarray` already appears to support this).

It would be helpful if there was a way this could be implemented in FAISS so that other frameworks could be supported without making any assumptions about the flags they've chosen to support. 

Faiss version: next

Running on:
- [ ] CPU
- [ X] GPU

Interface: 
- [ ] C++
- [ X] Python

**Comment by mdouze** [comment]
In fact this check is not necessary because it is checked again in the `swig_ptr` function 

https://github.com/facebookresearch/faiss/blob/master/python/swigfaiss.swig#L582

Could you confirm that it works if we just remove the check? Then we can just do that.

**Comment by cjnolet** [comment]
@mdouze Much better idea. I was diving through the swig_ptr code on Friday night and, if I understand correctly, it should make use of the underlying C pointer to the GPU array.

Assuming the original pointer came from managed memory, doing a device to device transfer without hitting the host should be possible, right?

I've been having some trouble with the FAISS build. It almost seems as if the INSTALL.md instructions might be out of date.

**Comment by mdouze** [comment]
I don't know what the PyObject layout is for cupy and numba but as long as it is compatible with the ndarray it should be fine. The GPU code detects automatically if the pointer is a host or device pointer. Of course the CPU code will crash over non-CPU pointers.

The only device-to-device copies that happen transparently are when adding or searching data from another GPU. @wickedfoo can you confirm?

The `INSTALL.md` looks correct to me. What did you find is incorrect?

**Comment by cjnolet** [comment]
@mdouze, I was getting strange behavior that seemed to stem from my use of a Conda environment. Some modifications to the generated `makefile.inc` fixed the problem. Edited my last reply according.

**Comment by cjnolet** [comment]
It appears that neither the `numba` nor `cupy` PyObject's validate the `PyArray_Check` on the C++ side. I removed the `PyArray_Check` as well as the contiguous check on `swigfaiss.swig` and got a segmentation fault when attempting to run the following code (with a numba array):

```python
res = faiss.StandardGpuResources()
gpu_index = faiss.GpuIndexFlatL2(res, 2)

gpu_index.add(rm)
```

I suppose this means Numba does not support Numpy's `__array_interface__`? It looks like they've created their own `__cuda_array_interface__`. Not sure what the adoption of this looks like this thus far.

**Comment by mdouze** [comment]
`pytorch` has this convenient feature that you can access the data pointer of a tensor as a Python integer. Any chance this is possible with Numba?

**Comment by cjnolet** [comment]
@mdouze, just to establish a mutual understanding of the following statement from yesterday:

>  The GPU code detects automatically if the pointer is a host or device pointer. Of course the CPU code will crash over non-CPU pointers.

Is this dependent upon the UVM model or do you guys use another technique to determine that the pointer memory is host vs device vs unified?

> `pytorch` has this convenient feature that you can access the data pointer of a tensor as a Python integer. Any chance this is possible with Numba?

`numba arrays` do have a way to get a hold of the pointer to the underlying device memory. It also provides a way for us to introspect the type of memory backing it (unified, host, or device), which is necessary in my case (for RAPIDS cuML) since the memory manager backing cuDF is not UVM. They support (and established) the new __cuda_array_inferface__ which, ideally, FAISS would adopt once they define a C specification.

**Comment by cjnolet** [comment]
The following code causes a segmentation fault. I am using the GPU bindings. 

```python
import numpy as np
import faiss

a = np.array([[1, 5]], dtype = np.int32)
nb_arr = numba.cuda.to_device(a)

class NbWrap(object):
  def __init__(self, nb_arr):
    self.__array_interface__ = nb_arr.__cuda_array_interface__
    self.__array_interface__["version"] = 3
	self.shape = nb_arr.shape
	self.dtype = nb_arr.dtype
    
    a = np.array(nb_arr, dtype = nb_arr.dtype)
    
    self.flags = a.flags

res = faiss.StandardGpuResources()
idx = faiss.GpuIndexFlatL2(res, nb_arr.shape[1])

idx.add(NbWrap(nb_arr))
```

**Comment by mdouze** [comment]
It is probably more reasonable to support the numba array in `swig_ptr`.

**Comment by wickedfoo** [comment]
> Is this dependent upon the UVM model or do you guys use another technique to determine that the pointer memory is host vs device vs unified?

This is done via `cudaPointerGetAttributes`:

https://github.com/facebookresearch/faiss/blob/master/gpu/utils/DeviceUtils.cpp#L89

**Comment by cjnolet** [comment]
I'm closing this issue and opening up a new issue on Numba / __cuda_array_interface__ support.
