### ISSUE TITLE
Array type not recognize while using add_with_ids from Python wrapper

### ISSUE THREAD

**Issue by carlosost** [facebookresearch/faiss#655]
# Summary

# Platform

OS: Ubuntu 14.04

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

My code:

```
import numpy as np
import faiss

for vector in feat_vectors:
    <some_code>
    vectors.append(vector_norm)
    ids.append(custom_id)

vectors = np.array(vectors)[:,0]
ids = np.array(ids)

index = faiss.IndexFlatIP(320)
indexIDMap = faiss.IndexIDMap(index)
indexIDMap.add_with_ids(vectors, ids)
```

vectors.dtype is float32 and vectors.shape is (3, 320)
ids.dtype is int64 and ids.shape is (3,)

I am getting this error:
**ValueError: 'did not recognize array type'**

**Comment by mdouze** [comment]
Are you certain about the `dtype`s ? Please double-check. 

Then post a small piece of code that reproduces the error (as a gist).

**Comment by carlosost** [comment]
In order to create a gist, I decided to save the ``vectors`` and the ``ids``  np.array as files, to make sure you'd use the same data. 

While I was creating the code and files, I decide to test the dtype again and when I did ``vectors.dtype`` over the original code, the result is ``dtype('float32')``, but when I do the same instruction over the same variable, but after load it from the saved file, the result is just ``float32``.

For sure this is the problem, but I have no ideia what causes it. Anyway, I don't think it is a problem with faiss lib anymore.

**Comment by carlosost** [comment]
I will close this issue, because I don't think it is a problem with faiss, but the use of numpy and arrays. 
Thank you.

**Comment by Srinath-Raja** [comment]
faiss_index.add_with_ids(np.array([np.float32(feature_vectors)]),np.array([int(id)]))
the id is uuid
did not recognize array type
Facing the same issue,can you please help.

**Comment by mdouze** [comment]
See https://github.com/facebookresearch/faiss/wiki/FAQ#why-does-python-faiss-not-accept-float64float32float16-vectors-or-uint64-ids-or-non-contiguous-arrays
