### ISSUE TITLE
MKL error on AWS Ubuntu with Python 3.6

### ISSUE THREAD

**Issue by batrlatom** [facebookresearch/faiss#657]
# Summary
I am unable to run faiss installed via conda ( I need python 3.6 ) with 
conda install faiss-cpu -c pytorch 

Faiss can be imported, but when building index, I get an error : 
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
# Platform
Ubuntu 18.04 on AWS small instance 

OS:  Ubuntu 18
( basic AWS template )

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

conda set to python 3.6
proceed with normal conda faiss-cpu installation

**Comment by beauby** [comment]
Could you try installing `faiss-cpu` in a fresh conda environment?

**Comment by batrlatom** [comment]
Hi, I made a fresh install with
conda create -n recall-env python=3.6 anaconda

activated with:
conda activate recall-env

install faiss 
conda install faiss-cpu -c pytorch
conda install -c anaconda setuptools
conda install -c conda-forge python-socketio

tried to locate libs:
> locate libmkl_def.so 
/home/ubuntu/.conda/pkgs/mkl-2018.0.3-1/lib/libmkl_def.so
/home/ubuntu/miniconda3/lib/libmkl_def.so

> locate libmkl_avx2.so
/home/ubuntu/.conda/pkgs/mkl-2018.0.3-1/lib/libmkl_avx2.so
/home/ubuntu/miniconda3/lib/libmkl_avx2.so

**Comment by batrlatom** [comment]
I create a new instance ( with Amazon Linux ) and it works now. So maybe it was broken during my plays with python in nonconda env. 


Thanks

**Comment by beauby** [comment]
Glad to know you got it working. I'm closing this but feel free to keep commenting if you encounter other issues.
