### ISSUE TITLE
Compile python 3.6 bindings

### ISSUE THREAD

**Issue by batrlatom** [facebookresearch/faiss#662]
# Summary
I really struggle with a compilation of python 3.6 bindings. 
Since python3 is standard package in Ubuntu 18.04, it would be very helpful
to make it work ( I am able to do it in Conda, but this have other consequences which I
cannot overcome now )

What are the flags in configure script?
 I am using 

I have virtualenv activated in location /home/ubuntu/myproject/myprojectenv/

trying commands from your install tutorial ...
python3 -c "import distutils.sysconfig; print(distutils.sysconfig.get_python_inc())"
====> /usr/include/python3.6m

python3 -c "import numpy ; print(numpy.get_include())"
====> /home/ubuntu/myproject/myprojectenv/lib/python3.6/site-packages/numpy/core/include

Now trying to configure 
./configure PYTHONCFLAGS=/home/ubuntu/myproject/myprojectenv/lib/python3.6/site-packages/numpy/core/include PYTHON=python3.6m

output of configure relevant to python is 
checking for python... python3.6
checking for python-config... no
configure: WARNING: You won't be able to build the python interface.
checking for numpy headers path... /home/ubuntu/myproject/myprojectenv/lib/python3.6/site-packages/numpy/core/include

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

**Comment by beauby** [comment]
Could you try `./configure --with-python-config=python3.6m-config`?

**Comment by jinfagang** [comment]
@beauby  Then what do with python3.5?

**Comment by beauby** [comment]
@jinfagang `./configure --with-python=python3.5` should work.

**Comment by jinfagang** [comment]
@beauby  In INSTALL.MD it says /path/to/python , which is ambiguous, but indeed python3.5 works. Then directly tell users using python3.5 rather than path, it consist of include path and lib path, no of them are clear enough for people to install.
