### ISSUE TITLE
reduction vector

### ISSUE THREAD

**Issue by zpmmehrdad** [facebookresearch/faiss#664]
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] **CPU**
- [ ] GPU

Interface: 
- [ ] C++
- [ ] **Python**

# Reproduction instructions

 

Hi everyone,
I've extracted the features of 100M images that each vector is an array of 4096D. I want to reduce vectors then build an index but I only have 32Gb RAM and when I want to load all vectors but I got out of memory error.

this is my code:

import numpy as np
import faiss   

mt = [] #my all vetctors(4096x100M)
mat = faiss.PCAMatrix (4096, 128) #128D Or 256D
mat.train(mt)
assert mat.is_trained
tr = mat.apply_py(mt)
        
index = faiss.IndexFlatL2(128)  
index.add(tr)
faiss.write_index(index, '100M.inx')
D, I = index.search(xb[:5], 5)

Is it right?

**Comment by mdouze** [comment]
The right approach in this case is to process the data by blocks, see here: 
https://github.com/facebookresearch/faiss/blob/master/benchs/bench_polysemous_1bn.py#L185
To train the PCA matrix, using 50k vectors should be enough.

Your `mt` matrix is probably memory-mapped, as it is 1.6TB (4096 * 100M * 4).

**Comment by zpmmehrdad** [comment]
Thanks for your reply,
Can I use PCA apply for each 1M vectors and save them and then make an index.
Is there a way to merge 100 indexes to an index?
What is the best?

**Comment by mdouze** [comment]
You may be interested in 
https://github.com/facebookresearch/faiss/wiki/FAQ#how-can-i-distribute-index-building-on-several-machines
