### ISSUE TITLE
Packaging details for building against FAISS C++ API

### ISSUE THREAD

**Issue by cjnolet** [facebookresearch/faiss#669]
The documentation describes that FAISS builds shared & static libraries but these do not appear to end up in the installed Python packaging. Rather, the Python conda packaging only installs the swig-converted artifacts. 

If a codebase, dependent on FAISS, is being built against the libfaiss.so and/or libfaiss_gpu.so artifacts, this leaves developers with the option of forcing contributors to build FAISS themselves, or including the libs in the codebase. 

Further clarification on the ideal way of packaging against FAISS C++ API's would be ideal.

**Comment by cjnolet** [comment]
Assuming the users build your source before building libraries that depend on it, Would it make sense to have FAISS install the so files into a common directory already on the LD path (e.g. `/user/lib64/faiss`)?

We would also need to install the include files in `/usr/include` as well. This would allow other projects to depend on FAISS and just point their users to the FAISS source.

**Comment by mdouze** [comment]
Absolutely. IMO the proper paths would be 
```
/usr/lib64/faiss.so
/usr/include/faiss/Index.h
/usr/include/faiss/IndexFlat.h
...
```
I will talk to @beauby on where we can standardize this an if we can distribute a binary package.

**Comment by cjnolet** [comment]
Sounds good. I certainly don't mind providing a PR.

**Comment by cjnolet** [comment]
@mdouze @beauby, I'm preparing to get some changes merged in a project that depend on FAISS. Do you have any objections to changing the default libname / includedir in the build to be /usr/lib64 & /usr/include?

**Comment by beauby** [comment]
@cjnolet The current default values for `libdir`/`includedir` come from autoconf (see [here](https://github.com/facebookresearch/faiss/blob/master/makefile.inc.in#L49). I do not feel strongly about it though, but in the meantime you can do `./configure --libdir=/usr/lib64 --includedir=/usr/include`.
