### ISSUE TITLE
Numba /  cuda_array_interface support

### ISSUE THREAD

**Issue by cjnolet** [facebookresearch/faiss#670]
FAISS supports support for Numpy objects through Numpy's PyArrayObject interface, however, Numba support is not easily possible through this interface. 

Unfortunately, C bindings for cuda_array_interface support are not yet defined in the spec. 

It would be very useful, however, if the `swig_ptr` function would accept Numba objects directly, as it does with Numpy. Numba provides a function to retrieve the ctypes pointer [1] to the underlying device data. This could, perhaps, be passed down directly to swig. 

[1] http://numba.pydata.org/numba-doc/0.14/modules/numba.cuda.cudadrv.html#numba.cuda.cudadrv.devicearray.DeviceNDArrayBase.device_ctypes_pointer

**Comment by mdouze** [comment]
`swig_ptr` is a C++ function. I understand `device_ctypes_pointer` is pure Python. 

To convert to a swig compatible pointer: 
```
ptr = ctypes.cast(xxx.device_ctypes_pointer, ctypes.c_void_p).value)
faiss.cast_integer_to_float_ptr(ptr)
```
or `cast_integer_to_int_ptr` etc. 

This would have to be replaced in faiss.py.

**Comment by beauby** [comment]
Closing, as we understand that Rapids is not using the python interface of Faiss.
