### ISSUE TITLE
How to output the results of faiss::Clustering kMeans

### ISSUE THREAD

**Issue by kakadadudu** [facebookresearch/faiss#678]
For example, I have 1000 documents. After extracting a 256-dimensional feature from none of them, I use K function to cluster them into 10 automatically. 

CPU,C++

`faiss::ClusteringParameters cp;
cp.niter = numberOfEMIterations;
cp.verbose = true;
faiss::Clustering kMeans(dim, numberOfClusters, cp);
kMeans.train(numVecsToCluster, fDataset, index); `

How to output the clustered results according to different categories?

**Comment by vipda** [comment]
The results is storaged in Clustering.centroids

**Comment by kakadadudu** [comment]
> 
> 
> The results are storaged in Clustering.centroids

How to use the Clustering.centroids to output the all Clustering?

**Comment by vipda** [comment]
I know, faiss::Clustering can only calculate the cluster center. If you want to output the clustered results, you can define an IndexIVF, then use train, add. The following is a simple demo.
`int d = 256;`
`int ncentroids = 10;`
`IndexFlatL2 *coarse_quantizer = new IndexFlatL2(d);`
`IndexIVF *ivf = new IndexIVF(coarse_quantizer, d, ncentroids);`
`ivf ->train("your data");`
`ivf->add("your data");`
`InvertedLists *invlists = ivf->invlists;`
`for (int i = 0; i < ncentroids; i++) {`
`        int size = invlists->list_size(i);`
`        const long *ids = invlists->get_ids (i);`
`        const uint8_t *codes = invlists->get_codes (i);`
`        for (int j = 0; j < size; j++) {`
`            long id = ids[j]; // this is your data id`
`        }`
`    }`

**Comment by kakadadudu** [comment]
> 
> 
> I know, faiss::Clustering can only calculate the cluster center. If you want to output the clustered results, you can define an IndexIVF, then use train, add. The following is a simple demo.
> `int d = 256;`
> `int ncentroids = 10;`
> `IndexFlatL2 *coarse_quantizer = new IndexFlatL2(d);`
> `IndexIVF *ivf = new IndexIVF(coarse_quantizer, d, ncentroids);`
> `ivf ->train("your data");`
> `ivf->add("your data");`
> `InvertedLists *invlists = ivf->invlists;`
> `for (int i = 0; i < ncentroids; i++) {`
> ` int size = invlists->list_size(i);`
> ` const long *ids = invlists->get_ids (i);`
> ` const uint8_t *codes = invlists->get_codes (i);`
> ` for (int j = 0; j < size; j++) {`
> ` long id = ids[j]; // this is your data id`
> ` }`
> ` }`

Thank you very much.I get the result ids success.
可以加个微信方便以后继续请教吗？
WeChat: kakadadudu
