### ISSUE TITLE
Please share an example to run faiss on python

### ISSUE THREAD

**Issue by ashutoshsingh25** [facebookresearch/faiss#679]
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by Enet4** [comment]
There is already an example in the [Getting Started](https://github.com/facebookresearch/faiss/wiki/Getting-started#in-python) wiki page.

**Comment by alvisanovari** [comment]
I think what he means is a proper/practical example that takes, say, a batch of images, extracts features/embeddings and does a similarity search on them. My guess is most people are interested in that application and right now there is no real guidance on how to use faiss for that.
