### ISSUE TITLE
GpuIndexIVFFlat searching is failed when size(xb) = 100000 Faiss assertion err == CUBLAS_STATUS_SUCCESS 

### ISSUE THREAD

**Issue by YaaoTu** [facebookresearch/faiss#68]
hi，

I run code as follows:

gt_index = faiss.GpuIndexFlatL2(res, d, flat_config)
gt_index.metric_type = faiss.METRIC_INNER_PRODUCT
index = faiss.GpuIndexIVFFlat(res, dev_no, gt_index, False, d, nlist, faiss.INDICES_CPU, faiss.METRIC_INNER_PRODUCT )
index.train(xb)
index.add(xb)

D, I = index.search(xq, k)

the code is failed when size(xb) = 100000 but successed when size(xb) = 10000 :
Faiss assertion err == CUBLAS_STATUS_SUCCESS failed in void faiss::gpu::runMatrixMult(faiss::gpu::Tensor<T, 2, true>&, bool, faiss::gpu::Tensor<T, 2, true>&, bool, faiss::gpu::Tensor<T, 2, true>&, bool, float, float, cublasHandle_t, cudaStream_t) [with T = float; cublasHandle_t = cublasContext*; cudaStream_t = CUstream_st*] at utils/MatrixMult.cu:141Aborted (core dumped)

who could I solve this problem?

thanks~

**Comment by mdouze** [comment]
Hi 

This looks like it could be a memory issue. On what type of GPU are you running this? Please provide the output of nvidia-smi.

**Comment by mdouze** [comment]
Could you try with the current version? It has better low-mem GPU support.

**Comment by dyzhou2015** [comment]
@mdouze  sorry, new to Faiss , I want to use GpuIndexIVFFlat to accelerate the retrieval, But I cannot find any example on how to configure the parameters of GpuIndexIVFFlat. is there any good examples ???

**Comment by mdouze** [comment]
Hi 

Please uncomment https://github.com/facebookresearch/faiss/blob/master/benchs/bench_gpu_sift1m.py#L91

This will make a GpuIndexIVFFlat

**Comment by mdouze** [comment]
Re-opening (the last question has nothing to do with the thread's topic)

**Comment by mdouze** [comment]
Closing because there is no clear issue here. 
Please submit a new issue if needed.
