### ISSUE TITLE
Did something change between v1.5.0 and v1.4.0 to speed up single vector searches?

### ISSUE THREAD

**Issue by gamma0577215** [facebookresearch/faiss#680]
# Summary

I'm using "Flat" index, always doing comprehensive search, single vector at a time, CPU based search, vector dimension varies (256 or 512 or 1024), metric type varies (inner product or euclidean distance), total records about 600,000 per server (and a few hundred of those), plenty of memory and CPU.  This is pretty much the worse case for FAISS performance.

FAISS version v1.4.0 

Did something change between v1.4.0 and v1.5.0 that would speed up single vector searches?  I've been tasked with figuring out anything we can do to speed up FAISS searches, so if going to v1.5.0 would help that would be good to know.  It's non-trivial for me to go to 1.5.0 but if it's faster I'll make it happen.

Thank you very much

# Platform

Linux

Running on:
- [ x ] CPU
- [ ] GPU

Interface: 
- [ x ] C++
- [ ] Python

**Comment by mdouze** [comment]
No I am afraid it is still the same code. 
There is not much room for improvement if batching is not used because the limiting factor is memory bandwidth.

**Comment by beauby** [comment]
Note that Faiss parallelizes over queries, but you could shard your index so that each shard is searched in parallel, and later merge the results.

**Comment by gamma0577215** [comment]
Yes, we do shard across cores and machines.

For inner product only I wonder if this idea would help speed things up:

Suppose I have a 1024-D based database with N vectors and query for all entries with a 1024-D vector.  Is that equivalent to splitting the database into two 512-D based databases (DX, DY) each with N "half vectors" and querying them with two 512-D based vectors (VX, VY).  VX would query against DX and VY would query against DY, then the resulting inner products can be added together.  Isn't that a form of sharding ?  I guess I could try it out and see what happens.

**Comment by mdouze** [comment]
No it is not equivalent, because the result of a search is a short-list of k nearest vectors and it is unlikely that the k nearest vectors of the first half are the same as the k nearest vectors of the second half. So there would be nothing to add.
Noting that you have very large vectors and running into performance issues, I would recommend that you consider approximate search. Ask yourself: would a 10x increase in speed make a 1% drop in accuracy acceptable?

**Comment by gamma0577215** [comment]
Exhaustive search, as mentioned, shouldn't have that issue, correct?  If, for some reason, an answer ID/score, didn't appear for both the first half and second half then it could be skipped with a warning.  We could also just have N/2 full size (1024-D) records in two databases and it should work about as well.

We are indeed investigating which approximate search would work best for us, as well as other performance optimizations.

We don't have a way currently to train with the same data set across servers.  For now our training set will be a large random sample per server, it's not ideal but that's what we're doing for now.

Thanks for your time.

**Comment by mdouze** [comment]
> Exhaustive search, as mentioned, shouldn't have that issue, correct? If, for some reason, an answer ID/score, didn't appear for both the first half and second half then it could be skipped with a warning. 

"Exhaustive search, as mentioned, shouldn't have that issue, correct?" -> Exhaustive search does not return the whole dataset ranked (or it could, but it would be outrageously inefficient). If you have 600k vectors per server and ask for 1000 nearest neighbors, then the expectation of intersection size between the first and the second list of results is 1000 * (1000 / 600k) = 1.6 results, ie. you would have 998 warnings and 1-2 results per query! 

If the intersection is much larger than that, it means that the first 512D and the second 512D of the vectors are strongly correlated, so you would be better off using dimensionality reduction in the first place. 

> We could also just have N/2 full size (1024-D) records in two databases and it should work about as well.

Yes, that is what @beauby suggested. You can wrap the two datasets in an `IndexProxy`, that will merge the results for you. Note that `IndexProxy` will be renamed as `IndexReplicas` and moved to the non-gpu part of Faiss in the next version. CC: @wickedfoo

**Comment by gamma0577215** [comment]
For now we score every database vector against the single query vector.  Right now we're not concerned about that being inefficient, we're more concerned about completeness.  Thanks again.
