### ISSUE TITLE
Why calculate L2 Distance result without sqrt？

### ISSUE THREAD

**Issue by hxfxjun** [facebookresearch/faiss#681]
# Summary

/* same without SSE */
float fvec_L2sqr_ref (const float * x,
                     const float * y,
                     size_t d)
{
    size_t i;
    float res = 0;
    for (i = 0; i < d; i++) {
        const float tmp = x[i] - y[i];
       res += tmp * tmp;
    }
    return res;
}

Why calculate L2 Distance result without sqrt？

float fvec_L2sqr_ref (const float * x,
                     const float * y,
                     size_t d)
{
    size_t i;
    float res = 0;
    for (i = 0; i < d; i++) {
        const float tmp = x[i] - y[i];
       res += tmp * tmp;
    }
    return sqrt(res);   // add sqrt
}

**Comment by Enet4** [comment]
A squared distance is generally sufficient for most use cases, since it preserves the ordering of results compared to the actual L2-norm distance. Computing square roots is expensive, making it definitely worth avoiding. See also #192.

**Comment by hxfxjun** [comment]
thank you
