### ISSUE TITLE
Would you like to add NSG to faiss?

### ISSUE THREAD

**Issue by welfred** [facebookresearch/faiss#685]
NSG is a graph-based approximate nearest neighbor search (ANNS) algorithm. It provides a flexible and efficient solution for the metric-free large-scale ANNS on dense real vectors. 

NSG paper: [https://arxiv.org/pdf/1707.00143.pdf](url)
Code: [https://github.com/ZJULearning/nsg](url)

Looking forward to integrating NSG and PQ（more accurate and faster but less memory） into Faiss.

**Comment by mdouze** [comment]
Yes this is something we are considering. 
So far it has not been very high on our priority list because HNSW is a good alternative to NSG, using only slightly more memory.

**Comment by KinglittleQ** [comment]
@mdouze Hi, I plan to add an NSG index to faiss. Could I create a pull request for it in the future?

**Comment by mdouze** [comment]
That sounds good. Do you have an idea of how to lay out the code? 
NSG is built upon a pre-existing KNN graph, so probably the graph construction part should be configurable (eg. build with GPU).

**Comment by KinglittleQ** [comment]
@mdouze We first need to add an NN-Descent index which would be used for building an NSG index and also be available for users to construct a KNN graph using CPU. GPU support could be added later without much effort thanks to the power of GpuIndexFlat. 

So in my plan, We can do it step by step as follow:
1. Add an IndexNNDescent.
2. Add an IndexNSG with CPU support only.
3. Provide an option for users to switch between IndexNNDescent or GpuIndexFlat to build a KNN graph.

Every step should be carefully designed and well tested before the next step.

**Comment by mdouze** [comment]
This is implemented, closing issue
