### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by justinaustin** [facebookresearch/faiss#689]
I'm just wondering if you guys are planning on updating faiss to support python 3.7. I would like to use faiss in an ongoing project, but I would like to avoid downgrading that project to 3.6.

Thanks!

**Comment by beauby** [comment]
This is on our roadmap.

**Comment by beauby** [comment]
In the meantime you can manually compile fais against python37 and it should work

**Comment by justinaustin** [comment]
Awesome. Thanks!
