### ISSUE TITLE
Search NNs more then 1024?

### ISSUE THREAD

**Issue by sharthZ** [facebookresearch/faiss#69]
Is it possible to use nprobe and nnn more then 1024? 
Now it is causing errors at `gpu\impl\IVFPQ.cu`:524
```c++
FAISS_ASSERT(nprobe <= 1024);
FAISS_ASSERT(k <= 1024);
```

**Comment by wickedfoo** [comment]
Not on GPU.

**Comment by wickedfoo** [comment]
At least, we've only implemented it for k <= 1024 using fast k-selection. Other GPU k-selection techniques can allow for larger k / nprobe, but those are much slower, and we haven't implemented those.
