### ISSUE TITLE
search didn't get the correct result (resolved)

### ISSUE THREAD

**Issue by hazoth** [facebookresearch/faiss#693]
# Summary
sorry to bother, i know the reason now, it's the problem of endian. 
 
# Platform
OS: macOS 10.13.6
Faiss version: (installed by conda) faiss-cpu 1.4.0 py36_cuda0.0_1

Faiss compilation options: 

Running on:
- [ ] CPU

Interface: 
- [ ] Python

# Reproduction instructions

m = b'\xbdf\x8bj\xbe:\xcdY\xbd\xa3\xb2\xb6\xbc\xfd\x04\xc3\xbe\x1b\'\x82=\xf4\x89>\xbd~\xb1z=\xb8\x95\xb0\xbd\xe5Ps\xbd\xb9\xf0\xce\xbe\x13U\xb2>S\xf9\xa1\xbc\x1b]\x0f\xbc\xd1\x92~<m\xe2\'=F\xb5\x0c\xba\x93\xa7h=D\xe0\xb8\xbb\xc6\x8c\xfc\xbb?\x85f;\xa9\xacR="\xe6\n<\xe1\xf3\xfe\xbe\x01\x97\x0f\xbd\xb9\x8b\xcb<[\xbd\x93\xbd]T\x81\xbc\x86\xdd\xe1\xbd\x80Z\xe4=Yt\x0f=\x0b*\xdf\xbd\x96j\xb1<\n*6>\x1b\x9e)>\x03t\x08=\x19\xc6\xda=\x83\xd0\x01>\\1\xc4=:\x97\xc6\xbd>\xbc\x1b'
m = np.fromstring(m, '>f4')

k = b'\xbd\xc8\xb6\xb0==E\xcb\xbeH\x90\xf3\xbeZ\xe9\xa8<\xef\xcf\xfb\xbc\xd1x\x03>upk=\x1a\xd3P>S\n0>\x0fE\x95\xbe\xa6\x8f\xba=\xc9\x8f\xec\xbe\t\xd9\x0c>4\xd2\xc4>\x0fPN<\xe4\xe72=)^V\xbd\xbe\xf7\xcb\xbe\x1czz>\x01\r\xa7=\xfbl\xc5=u"\xe1<\x03L\xae>\x06?9=\xcf/\xf7\xbd}\n\x1a\xbd\xd1cF=\xdc\xb4=\xbd\xc3_\x08\xbdq\x18\xb1\xbd\t\xdf\xb5\xbdM\x04\xd7\xbd_\x13p>\x00+\x00\xbd \x19\xc7;5\x0e\xa9>o\xe4\xe6\xbe3\xa7J=\x0er\x1b>\n\xa0k'
k = np.fromstring(k, '>f4')

f = faiss.IndexFlatIP(40)
f.add(m.reshape(1, 40))

print(f.search(k.reshape(1, 40), 1))
print(k.dot(m))

**Comment by mdouze** [comment]
Ok, closing.
