### ISSUE TITLE
Index IVFPQ retrieving less results.

### ISSUE THREAD

**Issue by tmdavid** [facebookresearch/faiss#696]
# Summary

# Platform

OS: 

Faiss version: 1.3 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

Hi, first of all, thanks for releasing FAISS, it's awesome to have access to this project.
We are using the index IVFPQ but we have realized that it when retrieving, say 100 results, sometimes we get back less than those 100 results. Is there a way to understand why we are getting this behavior? Is it something from the index itself? Or any documentation I can get my hands on? Haven't seen anything from it.

Cheers

**Comment by mdouze** [comment]
I assume you are getting -1s in the result lists. Then you should increase the `nprobe`, see 
https://github.com/facebookresearch/faiss/wiki/FAQ#what-does-it-mean-when-a-search-returns--1-ids

**Comment by tmdavid** [comment]
Right, I see. Thank you very much!
