### ISSUE TITLE
Clarification of the license relaxation promise

### ISSUE THREAD

**Issue by vmarkovtsev** [facebookresearch/faiss#7]
Hi,

Is there any specific date when you plan to relax CC-BY-NC to BSD?

**Comment by mdouze** [comment]
Short answer: no 

Long: the current release is primarily for researches to evaluate the implementation and to integrate Faiss in research projects. For this CC-BY-NC is enough.

**Comment by mdouze** [comment]
The license changed to BSD+Patents.
