### ISSUE TITLE
Can faiss search in the specific indexes?

### ISSUE THREAD

**Issue by JustinhoCHN** [facebookresearch/faiss#700]
For example, I have to query in an 10000 x 128 numpy array, but I filtered some of the vectors (like 100 vectors) from the big array in some ways, can I just query from the 100 x 128 arrays rather than the big array without training index again?

**Comment by beauby** [comment]
See [wiki](https://github.com/facebookresearch/faiss/wiki/FAQ#is-it-possible-to-dynamically-exclude-vectors-based-on-some-criterion) for excluding vectors in your search.

**Comment by JustinhoCHN** [comment]
@beauby Thank you for your reply, seems there's no other way but to set a bigger k.
