### ISSUE TITLE
why don't gpu-IVFFlatScan l2norm distance use L2Norm.cu:runL2Norm？

### ISSUE THREAD

**Issue by lyeetao** [facebookresearch/faiss#704]
why don't gpu-IVFFlatScan l2norm distance use L2Norm.cu:runL2Norm？

gpu IVFFlatScan use  (a-b) * (a-b)
gpu Flat use   L2Norm.cu:runL2Norm  |c||^2 - 2qc + ||q||^2

**Comment by wickedfoo** [comment]
GPU flat uses cuBLAS GEMM for efficiency to do -2q . c, and then adds in separately ||c||^2 then performs k-selection.

IVFFlatScan doesn't use GEMM, so it computes the whole thing independently.

As vectors, (a - b) . (a - b) = a.a - 2a.b = b.b = ||a||^2 - 2a . b + ||b||^2, so they compute the same thing.

**Comment by lyeetao** [comment]
Thank you very much ! 
My question is which of the two methods is high performance, if flat's way performance is higher, why ivfflat is not used

**Comment by lyeetao** [comment]
> GPU flat uses cuBLAS GEMM for efficiency to do -2q . c, and then adds in separately ||c||^2 then performs k-selection.
> 
> IVFFlatScan doesn't use GEMM, so it computes the whole thing independently.
> 
> As vectors, (a - b) . (a - b) = a.a - 2a.b = b.b = ||a||^2 - 2a . b + ||b||^2, so they compute the same thing.

Thank you very much !
My question is which of the two methods is high performance, if flat's way performance is higher, why ivfflat is not used
