### ISSUE TITLE
'GPU flat' vs 'IVFFlatScan'

### ISSUE THREAD

**Issue by lyeetao** [facebookresearch/faiss#706]
【GPU flat uses cuBLAS GEMM for efficiency to do -2q . c, and then adds in separately ||c||^2 then performs k-selection.

IVFFlatScan doesn't use GEMM, so it computes the whole thing independently.

As vectors, (a - b) . (a - b) = a.a - 2a.b = b.b = ||a||^2 - 2a . b + ||b||^2, so they compute the same thing. 】

@wickedfoo  Thank you very much !

My question is which of the two methods is high performance, if flat's way performance is higher, why ivfflat is not used？What scenarios do the two methods apply to?

**Comment by mdouze** [comment]
We use BLAS only for matrix-matrix operations, not matrix-vector or vector-vector, which is the case for the scanning code.
