### ISSUE TITLE
Optional stop condition for k-means clustering

### ISSUE THREAD

**Issue by sharthZ** [facebookresearch/faiss#71]
1. Can faiss stop k-means clustering by some condition (for example, when  imbalance_factor < 1.05 or asssings_prev_step < n * 0.01)?
This log explains, why i need this:
> Clustering 80000000 points in 64D to 200000 clusters, redo 1 times, 100 iterations
>   Preprocessing in 9.31 s
> Iteration 56 (61926.14 s, search 61765.47 s): objective=1.67322e+07 imbalance=1.104 nsplit=0
> Iteration 57 (63012.82 s, search 62849.39 s): objective=1.67306e+07 imbalance=1.104 nsplit=0
> Iteration 59 (65185.64 s, search 65016.56 s): objective=1.67268e+07 imbalance=1.104 nsplit=0
> Iteration 61 (67359.24 s, search 67184.60 s): objective=1.67236e+07 imbalance=1.104 nsplit=0
> Iteration 62 (68446.49 s, search 68269.12 s): objective=1.67221e+07 imbalance=1.104 nsplit=0
> Iteration 65 (71708.19 s, search 71522.30 s): objective=1.67177e+07 imbalance=1.104 nsplit=0
> Iteration 67 (73882.47 s, search 73690.96 s): objective=1.6715e+07  imbalance=1.104 nsplit=0
> Iteration 68 (74968.98 s, search 74774.74 s): objective=1.67137e+07 imbalance=1.104 nsplit=0
> Iteration 69 (76056.25 s, search 75859.09 s): objective=1.67125e+07 imbalance=1.104 nsplit=0
> Iteration 70 (77142.76 s, search 76942.91 s): objective=1.67112e+07 imbalance=1.104 nsplit=0
> Iteration 71 (78229.37 s, search 78026.64 s): objective=1.67095e+07 imbalance=1.104 nsplit=0
> Iteration 72 (79316.50 s, search 79110.78 s): objective=1.67083e+07 imbalance=1.104 nsplit=0

It turns out that the main goal of the algorithm has already passed, but I have to wait for it to end, since it doesn't save any midterm data at `clus.train(x, index)`.

2. Can faiss k-means clustering output number of changed assignments at previous step?

**Comment by mdouze** [comment]
Hi 
I think this feature is very specific, and easy to implement, so I would suggest you implement it yourself.
