### ISSUE TITLE
Error when training index

### ISSUE THREAD

**Issue by BelindaDandanLIN** [facebookresearch/faiss#712]
Hi, 

I used the following code to train an index:

> quantizer = faiss.IndexFlatL2(num_dim)
	

> index = faiss.IndexIVFFlat(quantizer, num_dim, num_cells, faiss.METRIC_L2)

	

> assert not index.is_trained
	

> index.train(data_features)

	

> assert index.is_trained

However, the error occurred:

> Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.

An optional solution I tried is:

> conda install nomkl numpy scipy scikit-learn numexpr

> conda remove mkl mkl-service

However, the same error still happen.

What can I do for this?

Thank you very much

**Comment by beauby** [comment]
Hi @BelindaDandanLIN – could you try running `$ conda install -c pytorch faiss-cpu` in a fresh conda env, and post the output here?

**Comment by BelindaDandanLIN** [comment]
Hi,

Yes, I run it, and the output is as follows:

> ==> WARNING: A newer version of conda exists. <==
 

> current version: 4.5.12
  

> latest version: 4.6.1

> Please update conda by running

    

> $conda update -n base -c defaults conda

> # All requested packages already installed.

**Comment by beauby** [comment]
@BelindaDandanLIN Please run this command *in a fresh conda env* (see [here](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands) for how to do it).

**Comment by BelindaDandanLIN** [comment]
Hi, 

it has been fixed. May I know the reason about this? Thank you so much for your help.

**Comment by mdouze** [comment]
You don't want to know the intricacies of MKL linking...

**Comment by hhexiy** [comment]
Hi,

Reinstalling in fresh env works for me with Python3.6, but not with Python2.7... Is there a solution for py27? Thanks!

**Comment by luochenxi** [comment]
@hhexiy 
Hi，
I also encountered the same problem. Have you solved it?
