### ISSUE TITLE
IndexIdMap is blocked when multiple GPUs are used

### ISSUE THREAD

**Issue by shockjiang** [facebookresearch/faiss#717]
# Summary
I try to "train" an IndexIDMap (python, GPU). It works when I run on my physical machine. However, when I build a docker image and run it. 
1/ when one GPU is used, the program works well.
2/ when multiple GPUs are used, the program will be blocked by the train function.
the code sample is like this:

`

            co = faiss.GpuClonerOptions()
            co.useFloat16 = True
            co.usePrecomputed = False
            self._proxy = faiss.IndexProxy()
            for i in range(num_gpu):
                res = faiss.StandardGpuResources()
                # res.setTempMemory(3 * 1024 * 1024 * 1024)
                print("GPU res object(index:{}) allocated".format(i))
                self._res_list.append(res)
                sub_index = faiss.index_cpu_to_gpu(res, i, cpu_index, co)
                self._sub_index_list.append(sub_index)
                self._proxy.addIndex(sub_index)
            self.index = faiss.IndexIDMap(self._proxy)
            self.index.verbose = verbose
            # get nlist to decide how many samples used for training
            nlist = int([item for item in index_factory_string.split(",") if 'IVF' in item][0].replace("IVF",""))

            # training
            if not self.index.is_trained:
                indexes_sample_for_train = np.random.randint(0, len(target), nlist * 256)
                print("training...", end="", flush=True)
                self.index.train(target[indexes_sample_for_train])
                print("done")

The program prints "trainning...", but does not print "done".

any clues?

# Platform
Linux

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by mdouze** [comment]
To narrow down the problem, could you try:
- remove the IndexIDMap?
- monitor CPU and GPU usage during the training.

As a side note: it is inefficient to run the training on several GPUs, because it actually runs the same computation on each (and eg. the IVFPQ training is actually performed partially on CPU). So it is probably better to run the training on 1 GPU before duplicating the index with `index_cpu_to_all_gpus`.

**Comment by shockjiang** [comment]
thanks so much,  mdouze. We fixed it.
