### ISSUE TITLE
add_with_ids - AssertionError

### ISSUE THREAD

**Issue by hanama** [facebookresearch/faiss#720]
Hi,
This is my index:
index = faiss.IndexFlatL2(d)
index2 = faiss.IndexIDMap(index)

When I am using:
**index2.add_with_ids(descriptors, ids)**

Where:
1. "descriptors" is a (200,256) numpy.ndarray.
2. "ids" is a (200, ) numpy.ndarray. 
(I am trying to add 200 descriptors, each is a 256 bits vector).

I got this error:
File "...../anaconda3/lib/python3.6/site-packages/faiss/__init__.py", line 104, in replacement_add_with_ids
assert d == self.d
**AssertionError**"

Can you help please?

Running on:
- [+] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [+] Python

**Comment by mdouze** [comment]
As discussed on the Faiss users group, you need to set d to 256. 
https://www.facebook.com/groups/faissusers/permalink/590165248074432/
