### ISSUE TITLE
problem with rpc

### ISSUE THREAD

**Issue by mingrenbuke** [facebookresearch/faiss#724]
I wrote a python function to test faiss. As shown in the figure, It worked well.
![image](https://user-images.githubusercontent.com/29194085/52546377-93208780-2df9-11e9-8a01-ebc7909bf3c4.png)
figure 1 the test code
![image](https://user-images.githubusercontent.com/29194085/52546383-9ca9ef80-2df9-11e9-92f9-61b962eb0eab.png)
figure 2 the correct result
but when I wrote a rpc service to call this function，it does not work and suspend at the train step. The same problem occurs when call search function with IndexFlatL2 Index. Can you give me some help? Thank you!
![image](https://user-images.githubusercontent.com/29194085/52546386-a6cbee00-2df9-11e9-82d1-d157c817d97c.png)
figure 3 the error result

Running on:
- [x] CPU

Interface: 
- [x] Python

**Comment by mdouze** [comment]
Please do not post snapshots. 
What is RPC?

**Comment by Enet4** [comment]
I suspect it's remote procedure call, although I cannot identify from the screenshots which technologies are involved. One would need a minimal working example to reproduce the problem. And considering that it works locally, it might just be an issue with the RPC server or client.

**Comment by beauby** [comment]
Closing, as this is not a Faiss issue.
