### ISSUE TITLE
GPU allocMemorySpace support raise exception instead of crash

### ISSUE THREAD

**Issue by twds** [facebookresearch/faiss#726]
# Summary

We're using faiss as a 7*24 running ONLINE service, which support retrieve and realtime add new vectors.
However the cudaMalloc fail will crash the program and make the whole service unavailable.

```
Faiss assertion 'cudaMalloc(p, size) == cudaSuccess' failed in void faiss::gpu::allocMemorySpace(faiss::gpu::MemorySpace, void**, size_t) at utils/MemorySpace.cpp:19; details: Failed to cudaMalloc xxxx bytes
```

In this commit, most FAISS_ASSERT calls moved to C++ exceptions, except cudaMalloc.
https://github.com/facebookresearch/faiss/commit/aa1585cb215637606e66999bc638a8dd8333971d
https://github.com/facebookresearch/faiss/blob/master/gpu/utils/MemorySpace.cpp#L18

Can we also make cudaMalloc throw exception only instead of crash, or provide a use-specified option on crash-vs-exception decision?

# Platform

OS: CentOS 7.4

Faiss version: 1.5.0-py36_cuda9.0_1

Faiss compilation options: conda install

Running on:
GPU

Interface: 
Python

# Reproduction instructions

```
import faiss
import numpy as np
d = 128
n = 16 * 10**9 // (4 * d)

x = faiss.rand(d * n).reshape(n, d) # 16G memory
shape = x.shape[-1]

res = faiss.StandardGpuResources()
flat_config = faiss.GpuIndexFlatConfig()
flat_config.useFloat16 = False
flat_config.device = 0
index = faiss.GpuIndexFlatIP(res, shape, flat_config)

index.add(x)
```

Running on ~10GB memory gpu card, it will output the following message and crash.

```
Faiss assertion 'cudaMalloc(p, size) == cudaSuccess' failed in void faiss::gpu::allocMemorySpace(faiss::gpu::MemorySpace, void**, size_t) at utils/MemorySpace.cpp:19; details: Failed to cudaMalloc 16000000000 bytes
```

**Comment by mcgrady-forever** [comment]
Possibly it caused by the gpu memory is not enough

**Comment by twds** [comment]
Of course the assertion fail is caused by GPU memory is not enough.

Here we want to raise exception so that we can choose some fallback solutions (make some models offline, or use cpu, etc).
While right now the whole service will hung and crash when faiss assertion fail.

**Comment by mdouze** [comment]
The Facebook internal version has been modified to support throwing exceptions on GPU OOM.
The next release will include it.

**Comment by mcgrady-forever** [comment]
> Of course the assertion fail is caused by GPU memory is not enough.
> 
> Here we want to raise exception so that we can choose some fallback solutions (make some models offline, or use cpu, etc).
> While right now the whole service will hung and crash when faiss assertion fail.

How do you use faiss on online environment with high availibility like other distributed system, such as es. Do u have one index on each node?

**Comment by twds** [comment]
> The Facebook internal version has been modified to support throwing exceptions on GPU OOM.
> The next release will include it.

Cool~ Looking forward to the next release!

**Comment by twds** [comment]
> > Of course the assertion fail is caused by GPU memory is not enough.
> > Here we want to raise exception so that we can choose some fallback solutions (make some models offline, or use cpu, etc).
> > While right now the whole service will hung and crash when faiss assertion fail.
> 
> How do you use faiss on online environment with high availibility like other distributed system, such as es. Do u have one index on each node?

Well, here we use faiss instances for application-level service, NOT distributed system.

We've multiple Docker instances running faiss service for availability. The realtime update to faiss may only succeed in several instances, with eventually consistency assurance by other monitor tasks.

**Comment by mcgrady-forever** [comment]
> > > Of course the assertion fail is caused by GPU memory is not enough.
> > > Here we want to raise exception so that we can choose some fallback solutions (make some models offline, or use cpu, etc).
> > > While right now the whole service will hung and crash when faiss assertion fail.
> > 
> > 
> > How do you use faiss on online environment with high availibility like other distributed system, such as es. Do u have one index on each node?
> 
> Well, here we use faiss instances for application-level service, NOT distributed system.
> 
> We've multiple Docker instances running faiss service for availability. The realtime update to faiss may only succeed in several instances, with eventually consistency assurance by other monitor tasks.

When update the faiss index，the service is not available during this time?

**Comment by twds** [comment]
> When update the faiss index，the service is not available during this time?

1. The update cost very short time
2. We have multiple faiss indexes
3. Retrieve / Update ratio is 100x~1000x

In our practice, the availability of the whole service can reach  99.99%+

**Comment by mcgrady-forever** [comment]
> > When update the faiss index，the service is not available during this time?
> 
> 1. The update cost very short time
> 2. We have multiple faiss indexes
> 3. Retrieve / Update ratio is 100x~1000x
> 
> In our practice, the availability of the whole service can reach 99.99%+

Thanks for your reply, do you have one faiss index on each docker instance, or multiple faiss indexes on each docker instance

**Comment by twds** [comment]
> > > When update the faiss index，the service is not available during this time?
> > 
> > 
> > 
> > 1. The update cost very short time
> > 2. We have multiple faiss indexes
> > 3. Retrieve / Update ratio is 100x~1000x
> > 
> > In our practice, the availability of the whole service can reach 99.99%+
> 
> Thanks for your reply, do you have one faiss index on each docker instance, or multiple faiss indexes on each docker instance

We've multiple faiss indexes on each docker instance. You may deploy only one index on on instance of the cluster, depends on the GPU resource.

Each faiss can only response one request at the same time, concurrent retrieve and retrieve&update is not supported, so we use cluster to assure capacity and availability.
If availability does not match the target, there're some workarounds such as use more Docker instances, or dispatch retrieve requests to instances that not currently updating.

**Comment by mcgrady-forever** [comment]
> > > > When update the faiss index，the service is not available during this time?
> > > 
> > > 
> > > 
> > > 1. The update cost very short time
> > > 2. We have multiple faiss indexes
> > > 3. Retrieve / Update ratio is 100x~1000x
> > > 
> > > In our practice, the availability of the whole service can reach 99.99%+
> > 
> > 
> > Thanks for your reply, do you have one faiss index on each docker instance, or multiple faiss indexes on each docker instance
> 
> We've multiple faiss indexes on each docker instance. You may deploy only one index on on instance of the cluster, depends on the GPU resource.
> 
> Each faiss can only response one request at the same time, concurrent retrieve and retrieve&update is not supported, so we use cluster to assure capacity and availability.
> If availability does not match the target, there're some workarounds such as use more Docker instances, or dispatch retrieve requests to instances that not currently updating.

1. What is the data size in one index?
2. As you mentioned above 'We've multiple faiss indexes on each docker instance', these indexes are replicate or each one of them is part of the total index?

**Comment by twds** [comment]
> 1. What is the data size in one index?
> 2. As you mentioned above 'We've multiple faiss indexes on each docker instance', these indexes are replicate or each one of them is part of the total index?

1. each record is 256~1024dimensions float16, one index contains at most millions of records
2. replicate

**Comment by mcgrady-forever** [comment]
> > 1. What is the data size in one index?
> > 2. As you mentioned above 'We've multiple faiss indexes on each docker instance', these indexes are replicate or each one of them is part of the total index?
> 
> 1. each record is 256~1024dimensions float16, one index contains at most millions of records
> 2. replicate

You use multiple faiss indexes on each docker instance for the purpose of making search faster or high availability? Since you have already use cluster and I do not understand whether it is necessary here.

**Comment by twds** [comment]
> You use multiple faiss indexes on each docker instance for the purpose of making search faster or high availability? Since you have already use cluster and I do not understand whether it is necessary here.

As talked above, it's ok to have one or multiple indexes on one instance.
In our project, there're some tradeoff on the high-availability vs complexity. The multiple faiss indexes solution is a easier way to implement, due to project-specific requirements and related technologies the team is currently using.

**Comment by mcgrady-forever** [comment]
> > You use multiple faiss indexes on each docker instance for the purpose of making search faster or high availability? Since you have already use cluster and I do not understand whether it is necessary here.
> 
> As talked above, it's ok to have one or multiple indexes on one instance.
> In our project, there're some tradeoff on the high-availability vs complexity. The multiple faiss indexes solution is a easier way to implement, due to project-specific requirements and related technologies the team is currently using.

Now I understand what you said. And how to recover the index when the instance is dead，do you have to save it on disk?

**Comment by twds** [comment]
> Now I understand what you said. And how to recover the index when the instance is dead，do you have to save it on disk?

Yes, we've some background monitor tasks, which responsible to dump full dataset on disk, as well as detect&fill missing data generated after the last dump.
