### ISSUE TITLE
faiss doesn't work well after conda install faiss-gpu

### ISSUE THREAD

**Issue by 1049451037** [facebookresearch/faiss#727]
# Summary

cpu works well but gpu doesn't work.

# Platform

OS: Ubuntu 16.04

Faiss version: latest

Faiss compilation options: conda install faiss-gpu cuda90 -c pytorch

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

When running the code of [Getting-started](https://github.com/facebookresearch/faiss/wiki/Getting-started), I met this error:

```
Intel MKL FATAL ERROR: Cannot load libmkl_avx512.so or libmkl_def.so.
```

just after running this line:

```python
D, I = index.search(xq, k)     # actual search
```

It's really weird that this line works well but the above one doesn't:

```python
D, I = index.search(xb[:5], k) # sanity check
```

**Comment by 1049451037** [comment]
Ah, it's really strange that after removing faiss-gpu, installing faiss-cpu and reinstalling faiss-gpu. It worked now...

**Comment by jiankang1991** [comment]
I also have the same problem. After I install mkl with `conda install mkl`, it seems to work.

**Comment by 1049451037** [comment]
but I heard someone says mkl will make faiss slower...

**Comment by beauby** [comment]
You should not have both faiss-cpu and faiss-gpu installed. faiss-cpu is just a subset of faiss-gpu.

> but I heard someone says mkl will make faiss slower...

This should not be the case, on the contrary.
