### ISSUE TITLE
Makefile Error in v1.5.0

### ISSUE THREAD

**Issue by pakjce** [facebookresearch/faiss#731]
# Summary

Could you please re-deploy or add patched version tag (e.g. v1.5.1) as resolve this error?

Missing `\` in gpu/Makefile line 48 in v1.5.0
https://github.com/facebookresearch/faiss/blob/v1.5.0/gpu/Makefile#L48

Error Message:
> Makefile:49: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.

# Platform

OS: ubuntu16.04 (from `nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04` docker image)

Faiss version: v1.5.0 (version tag)

Faiss compilation options: MKL (with conda), CUDA9.0, Python3.6 (with conda)

conda install command:
```
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -u -p /usr/local && \
    rm ~/miniconda.sh
RUN conda install python=3.6 && conda clean -a -y

RUN conda install numpy mkl mkl-include setuptools cmake \ 
      pytorch=1.0.1 torchvision cudatoolkit=9.0 -c pytorch
```

my `./makefile.inc`
```
CXX      = g++ -std=c++11
CXXFLAGS = -fPIC -m64 -Wall -g -O3 -fopenmp -Wno-sign-compare
CPUFLAGS = -mavx -msse4 -mpopcnt
LDFLAGS  = -fPIC -fopenmp

# common linux flags
SHAREDEXT   = so
SHAREDFLAGS = -shared
MKDIR_P = mkdir -p

prefix      ?= /usr/local
exec_prefix ?= ${prefix}
libdir       = ${exec_prefix}/lib
includedir   = ${prefix}/include

MKLROOT = /usr/local/
LDFLAGS  += -Wl,--no-as-needed -L$(MKLROOT)/lib
LIBS     += -lmkl_intel_ilp64 -lmkl_core -lmkl_gnu_thread -ldl -lpthread
CPPFLAGS += -DFINTEGER=long

PYTHONCFLAGS = -I/usr/local/include -I/usr/local/include/python3.6m -I/usr/local/lib/python3.6/site-packages/numpy/core/include
PYTHONLIB    = -lpython
PYTHON = /usr/local/bin/python

CUDAROOT     = /usr/local/cuda-9.0
NVCC         = $(CUDAROOT)/bin/nvcc
NVCCLDFLAGS  = -L$(CUDAROOT)/lib64
NVCCLIBS     = -lcudart -lcublas -lcuda
CUDACFLAGS   = -I$(CUDAROOT)/include
NVCCFLAGS    = -I $(CUDAROOT)/targets/x86_64-linux/include/ \
-Xcompiler -fPIC \
-Xcudafe --diag_suppress=unrecognized_attribute \
-gencode arch=compute_35,code="compute_35" \
-gencode arch=compute_52,code="compute_52" \
-gencode arch=compute_60,code="compute_60" \
-lineinfo \
-ccbin $(CXX) -DFAISS_USE_FLOAT16
```

Running on:
- [v] CPU
- [v] GPU

Interface: 
- [v] C++
- [v] Python

# Reproduction instructions

In my dockerfile
`FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04`
......
1. `RUN wget -q https://github.com/facebookresearch/faiss/archive/v1.5.0.tar.gz -O /tmp/faiss.tar.gz`
2. `RUN cd /opt \
  && tar -xf /tmp/faiss.tar.gz && cd faiss-1.5.0 \
  && mv /tmp/faiss-makefile.inc ./makefile.inc \
  && ./configure \
  && exportCPLUS_INCLUDE_PATH=/usr/local/include:/usr/local/include/python3.6m:/usr/local/lib/python3.6/site-packages/numpy/core/include \
  && make -j $(nproc) && make install`
3. `RUN cd /opt/faiss-1.5.0/gpu \
  &&  CPLUS_INCLUDE_PATH=/usr/local/include:/usr/local/include/python3.6m:/usr/local/lib/python3.6/site-packages/numpy/core/include make -j$(nproc) all && make install`

Error occurred!
> Makefile:49: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.

**Comment by beauby** [comment]
This is fixed in the latest release (v1.5.1).
