### ISSUE TITLE
support Ctrl-C to stop a computation in python 

### ISSUE THREAD

**Issue by mdouze** [facebookresearch/faiss#733]
# Summary

A computation cannot be interrupted by ctrl-C in python on the CLI or in a notebook.

# Platform

Running on:
- [x ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x ] Python

This would require to accept a computation callback in the C++ code at some strategic points (search  and add functions). The callback should run at regular intervals. It should be in an openmp critical section, acquire the GIL and check `PyErr_CheckSignals`. If the function returns -1, it should raise a Faiss exception and the return to interpreter would be automatic.

https://docs.python.org/3/c-api/exceptions.html#c.PyErr_CheckSignals

**Comment by mylyu** [comment]
this would be a great new feature!

**Comment by beauby** [comment]
Closing as this is part of v1.5.1.
