### ISSUE TITLE
link to doxygen doc broken

### ISSUE THREAD

**Issue by mylyu** [facebookresearch/faiss#734]
The link to doxygen documentation (https://rawgit.com/facebookresearch/faiss/master/docs/html/annotated.html) in README.md, seems broken?

**Comment by beauby** [comment]
What seems broken on your end? It seems to work fine on mine.

**Comment by mylyu** [comment]
> What seems broken on your end? It seems to work fine on mine.

oh, it turns out an issue of my company's network. The link is ok with my mobile phone.
