### ISSUE TITLE
Range search for limited queries

### ISSUE THREAD

**Issue by tejaskhot** [facebookresearch/faiss#737]
I am trying to use the range search operation (only CPU support) for a scenario wherein the dataset contains ~200K high dimensional (16-32 D) points but there are only a small number of search queries to be made (<500). The bottleneck for this operation is creation of the index structure which takes time. Is it possible to bypass creation of the distances index for all points and do it selectively for this purpose?

**Comment by mdouze** [comment]
Yes it is possible to directly call the low-level function that does the range search on a given matrix. 
See here: 
https://github.com/facebookresearch/faiss/blob/master/utils.h#L255
LMK if you need to call it from Python (a bit more complex than C++)

**Comment by tejaskhot** [comment]
I am indeed interested in the python implementation of this. My current range search code is along the lines of that in the provided examples. It'll be great if you could share about I could incorporate into that.

**Comment by tejaskhot** [comment]
If I understand correctly, the following should produce correct results:
```
index_range = faiss.IndexFlatL2(data.shape[-1]) # data is (N x F)
index_range.add(data)
lims1, dist1, index1 = index_range.range_search(data, 1.5) # v1
lims2, dist2, index2 = index_range.range_search(data[200:300], 1.5) # v2
```
The two variants `v1` and `v2` should always produce the same results. Please confirm if my understand is correct (and the issue can be closed in that case).

**Comment by mdouze** [comment]
No that is incorrect. In v1  run you are querying all rows of the data matrix. 
In v2, you are searching only rows 200 to 299.
To come back to your initial question, here is an example that runs without creating an index (avoids a copy of the database matrix): 
https://gist.github.com/mdouze/5e561023d98187b7ee69a76da0fa36e2

**Comment by tejaskhot** [comment]
Thanks!
