### ISSUE TITLE
GPU Installation instructions missing or confusing

### ISSUE THREAD

**Issue by dexception** [facebookresearch/faiss#747]
Can someone put some steps on the home of this group for everyone so that people can compile the repo on gpu in c++ and python. Simple 10 commands one by one. 

Thank you.

**Comment by jamessmith90** [comment]
+1 
I am also facing issues

Followed the commands given in https://github.com/facebookresearch/faiss/blob/master/INSTALL.md

Issue no 1
cd gpu; make tests/demo_ivfpq_indexing_gpu

does not work because the folder name is "test" and not "tests"

Issue no 2
make test/demo_ivfpq_indexing_gpu

Getting the following output:
```
g++ -std=c++11 -fPIC -fopenmp -m64 -Wno-sign-compare -g -O3 -Wall -Wextra -DFINTEGER=int  -fopenmp   test/demo_ivfpq_indexing_gpu.cpp   -o test/demo_ivfpq_indexing_gpu
In file included from test/../GpuResources.h:12:0,
                 from test/../StandardGpuResources.h:12,
                 from test/demo_ivfpq_indexing_gpu.cpp:19:
test/../utils/DeviceMemory.h:12:26: fatal error: cuda_runtime.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'test/demo_ivfpq_indexing_gpu' failed
make: *** [test/demo_ivfpq_indexing_gpu] Error 1
```

**But the file exists**
**locate cuda_runtime.h**
**/usr/local/cuda-9.0/include/cuda_runtime.h**

**After editing the /etc/bash.bashrc
and adding the following export CPLUS_INCLUDE_PATH=/usr/local/cuda-9.0/include${CPLUS_INCLUDE_PATH:+:${CPLUS_INCLUDE_PATH}}

I am getting the following error** 
```
root@james-GL553VE:/opt/github4/faiss/gpu# make test/demo_ivfpq_indexing_gpu
g++ -std=c++11 -fPIC -fopenmp -m64 -Wno-sign-compare -g -O3 -Wall -Wextra -DFINTEGER=int  -fopenmp   test/demo_ivfpq_indexing_gpu.cpp   -o test/demo_ivfpq_indexing_gpu
/tmp/cc7rWBTS.o: In function `main':
/opt/github4/faiss/gpu/test/demo_ivfpq_indexing_gpu.cpp:56: undefined reference to `faiss::gpu::StandardGpuResources::StandardGpuResources()'
/opt/github4/faiss/gpu/test/demo_ivfpq_indexing_gpu.cpp:66: undefined reference to `faiss::gpu::GpuIndexIVFPQ::GpuIndexIVFPQ(faiss::gpu::GpuResources*, int, int, int, int, faiss::MetricType, faiss::gpu::GpuIndexIVFPQConfig)'
/opt/github4/faiss/gpu/test/demo_ivfpq_indexing_gpu.cpp:81: undefined reference to `faiss::gpu::GpuIndexIVFPQ::train(long, float const*)'
/opt/github4/faiss/gpu/test/demo_ivfpq_indexing_gpu.cpp:89: undefined reference to `faiss::gpu::index_gpu_to_cpu(faiss::Index const*)'
/opt/github4/faiss/gpu/test/demo_ivfpq_indexing_gpu.cpp:91: undefined reference to `faiss::write_index(faiss::Index const*, char const*)'
/opt/github4/faiss/gpu/test/demo_ivfpq_indexing_gpu.cpp:111: undefined reference to `faiss::gpu::GpuIndexIVF::add(long, float const*)'
/opt/github4/faiss/gpu/test/demo_ivfpq_indexing_gpu.cpp:138: undefined reference to `faiss::gpu::GpuIndex::search(long, float const*, long, float*, long*) const'
/opt/github4/faiss/gpu/test/demo_ivfpq_indexing_gpu.cpp:66: undefined reference to `faiss::gpu::GpuIndexIVFPQ::~GpuIndexIVFPQ()'
/opt/github4/faiss/gpu/test/demo_ivfpq_indexing_gpu.cpp:56: undefined reference to `faiss::gpu::StandardGpuResources::~StandardGpuResources()'
/opt/github4/faiss/gpu/test/demo_ivfpq_indexing_gpu.cpp:66: undefined reference to `faiss::gpu::GpuIndexIVFPQ::~GpuIndexIVFPQ()'
/opt/github4/faiss/gpu/test/demo_ivfpq_indexing_gpu.cpp:56: undefined reference to `faiss::gpu::StandardGpuResources::~StandardGpuResources()'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'test/demo_ivfpq_indexing_gpu' failed

```

Issue no 3

python gpu is also not working

```
root@james-GL553VE:/opt/github4/faiss/python# make _swigfaiss_gpu.so
make: *** No rule to make target '../libfaiss.a', needed by '_swigfaiss_gpu.so'.  Stop.
```

**Comment by beauby** [comment]
@jamessmith90 You are expected to run `./configure && make` at the root of your faiss checkout before building the gpu part.

**Comment by beauby** [comment]
@dexception I'm making a new docker file, which will contain what you requested. It will be available later this week.

**Comment by jamessmith90** [comment]
@beauby 
This is after i have executed the 
./configure in the root folder
make in the gpu folder


PS:  Why not 4 separate make files in the root folder ?
cpp_cpu_makefile
cpp_gpu_makefile
python_cpu_makefile
python_gpu_makefile

This will make everyone's life easy.

**Comment by tiangolo** [comment]
> @beauby  I'm making a new docker file, which will contain what you requested. It will be available later this week.

That's great to hear. I've been trying several modifications locally to compile it in Docker, I was thinking of sending a PR later, but I think I'll better wait for your new `Dockerfile`.

I was trying to debug why I'm not being able to run on GPU from Python (installing with `conda install faiss-gpu cuda90 -c pytorch`).

But now I think I'll just stop and wait for your new `Dockerfile` to continue debugging with it. Let me know if there's anything I can help with.

**Comment by mdv3101** [comment]
+1
GPU Compilation steps are not working. Waiting for fix.

**Comment by NightFury10497** [comment]
+1
Unable to Compile repo on GPU in python... getting compilation errors.

**Comment by beauby** [comment]
This should be fixed in master/v1.5.1 (and INSTALL.md was updated with up-to-date instructions). 
@tiangolo A new Dockerfile is also available.

**Comment by tiangolo** [comment]
That's great, thank you @beauby !

**Comment by tiangolo** [comment]
I confirm that the new conda version is using the GPU :tada:
(I had this comment in my backlog)

**Comment by dexception** [comment]
Thanks @beauby for the fixes..

Instructions are simple and easy to understand.
Any chance of adding a string with the vector ?

Instead of using multiple databases one would just simple return the json with it.
