### ISSUE TITLE
'\' separator missing in /gpu/Makefile line:48 (faiss-1.5.0)

### ISSUE THREAD

**Issue by shuguang101** [facebookresearch/faiss#749]
faiss-1.5.0/gpu/Makefile
48             GpuIndexBinaryFlat.o   -------->  48             GpuIndexBinaryFlat.o \

**Comment by Enet4** [comment]
This has already been fixed upstream in #672: https://github.com/facebookresearch/faiss/blob/master/gpu/Makefile#L48
