### ISSUE TITLE
metric_type option

### ISSUE THREAD

**Issue by sankovalev** [facebookresearch/faiss#757]
What does **metric_type** option mean when initializing an index? As I understand 0='IP', 1='L2', but it doesn't change when I create index with parameter _METRIC_INNER_PRODUCT_ or  _METRIC_L2_ in index_factory()

**Comment by beauby** [comment]
Could you post the specific string you use with `index_factory()`?

**Comment by sankovalev** [comment]
This code
```
index_l2 = faiss.index_factory(d, "IDMap,HNSW64", faiss.METRIC_L2)
index_ip = faiss.index_factory(d, "IDMap,HNSW64", faiss.METRIC_INNER_PRODUCT)

print(index_l2.metric_type, index_ip.metric_type)
```
outputs **1,1**

<hr>
There may be a problem in HNSW?

**Comment by beauby** [comment]
HNSW does not support any other metric than L2, hence your issue.

**Comment by sankovalev** [comment]
I know that original HNSW only works with L2, so the question came up.
Suppose it should display an error when initializing, as in the case of other indexes.
