### ISSUE TITLE
the HNSW::fill_with_random_links method has a bug

### ISSUE THREAD

**Issue by devjiang** [facebookresearch/faiss#764]
# Summary
in HNSW::fill_with_random_links function, in for-loop, it should be "level--", NOT "level++". 

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by beauby** [comment]
Thanks for reporting this @devjiang. This method is not used by indexes, but I'll fix it.
