### ISSUE TITLE
Failed on "cd gpu; make test/demo_ivfpq_indexing_gpu"

### ISSUE THREAD

**Issue by fengqingleiyue** [facebookresearch/faiss#766]
# Summary
Failed on "cd gpu; make test/demo_ivfpq_indexing_gpu"

g++ -std=c++11 -fopenmp  -L/usr/local/cuda/lib64  -o demo_ivfpq_indexing_gpu demo_ivfpq_indexing_gpu.o ../libgpufaiss.a ../../libfaiss.a -lopenblas   -lcudart -lcublas -lcuda
../libgpufaiss.a(GpuAutoTune.o)：inside function ‘faiss::gpu::GpuParameterSpace::initialize(faiss::Index const*)’：
/opt/faiss/gpu/GpuAutoTune.cpp:383：对‘faiss::gpu::getMaxKSelection()’ undefined reference ./libgpufaiss.a(GpuIndex.o)：in function ‘faiss::gpu::GpuIndex::search(long, float const*, long, float*, long*) const’中：
/opt/faiss/gpu/GpuIndex.cu:190：‘faiss::gpu::getMaxKSelection()’  undefined reference 
/opt/faiss/gpu/GpuIndex.cu:190：‘faiss::gpu::getMaxKSelection()’  undefined reference 
/opt/faiss/gpu/GpuIndex.cu:190：‘faiss::gpu::getMaxKSelection()’   undefined reference 
../libgpufaiss.a(GpuIndexIVF.o)：faiss::gpu::GpuIndexIVF::copyFrom(faiss::IndexIVF const*)’中：
/opt/faiss/gpu/GpuIndexIVF.cu:93：对‘faiss::gpu::getMaxKSelection()’  undefined reference 
../libgpufaiss.a(GpuIndexIVF.o):/opt/faiss/gpu/GpuIndexIVF.cu:93: floowing by more undefined reference faiss::gpu::getMaxKSelection()
collect2: error: ld returned 1 exit status
Makefile:13: recipe for target 'demo_ivfpq_indexing_gpu' failed
make: *** [demo_ivfpq_indexing_gpu] Error 1

# Platform
OS: Ubuntu 16.04 , with GPU Driver NVIDIA-Linux-x86_64-410.78 
CUDA cuda_9.0.176_384.81_linux and CUDNN cudnn-9.0-linux-x64-v7.3.1.20 

Faiss version:  git commit, 6c1cb3cd5c467fb6b0c1553a0bae83a784c29105
Faiss compilation options: 

Running on:
- [√ ] CPU
- [ √] GPU

Interface: 
- [ ] C++
- [ √] Python

# Reproduction instructions
cd gpu ; make -j 4 ; make test/demo_ivfpq_indexing_gpu

Here is my makefile.inc :
====================================
CXX          = g++ -std=c++11
CXXCPP       = g++ -std=c++11 -E
CPPFLAGS     = -DFINTEGER=int
CXXFLAGS     = -fPIC -fopenmp -m64 -Wno-sign-compare -g -O3 -Wall -Wextra
CPUFLAGS     = -msse4 -mpopcnt
LDFLAGS      = -fopenmp
LIBS         = -lopenblas
PYTHONCFLAGS = -I/usr/include/python3.5 -I/usr/include/x86_64-linux-gnu/python3.5m -I/usr/local/lib/python3.5/dist-packages/numpy/core/include

NVCC         = /usr/local/cuda/bin/nvcc
NVCCLDFLAGS  = -L/usr/local/cuda/lib64
NVCCLIBS     = -lcudart -lcublas -lcuda
CUDAROOT     = /usr/local/cuda
CUDACFLAGS   = -I/usr/local/cuda/include
NVCCFLAGS    = -I $(CUDAROOT)/targets/x86_64-linux/include/ \
-Xcompiler -fPIC \
-Xcudafe --diag_suppress=unrecognized_attribute \
-gencode arch=compute_35,code="compute_35" \
-gencode arch=compute_52,code="compute_52" \
-gencode arch=compute_60,code="compute_60" \
-gencode arch=compute_61,code="compute_61" \
-lineinfo \
-ccbin $(CXX) -DFAISS_USE_FLOAT16

OS = $(shell uname -s)

SHAREDEXT   = so
SHAREDFLAGS = -shared

ifeq ($(OS),Darwin)
	SHAREDEXT   = dylib
	SHAREDFLAGS = -dynamiclib -undefined dynamic_lookup
endif

MKDIR_P      = /bin/mkdir -p
PYTHON       = python3
SWIG         = swig
prefix      ?= /usr/local
exec_prefix ?= ${prefix}
libdir       = ${exec_prefix}/lib
includedir   = ${prefix}/include

==================================

One more strange thing is ,  after i finish build the py interface using "make py && cd python && sudo make install" , i was able to execute  'python3 -c "import faiss"'  under the faiss/python path , but if i switch to any other path it will report the following error message ,

===================================

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/faiss-0.1-py3.5.egg/faiss/__init__.py", line 21, in <module>
    from swigfaiss_gpu import *
ImportError: No module named 'swigfaiss_gpu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/faiss-0.1-py3.5.egg/faiss/__init__.py", line 28, in <module>
    from swigfaiss import *
ImportError: No module named 'swigfaiss'

======================================

any idea why it happens?

**Comment by beauby** [comment]
The Makefile for the GPU tests is currently broken. It will be fixed tomorrow.

**Comment by fengqingleiyue** [comment]
Cool , what about the problem 
"One more strange thing is , after i finish build the py interface using "make py && cd python && sudo make install" , i was able to execute 'python3 -c "import faiss"' under the faiss/python path , but if i switch to any other path it will report the following error message ,"  ...
