### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by sivanWu0222** [facebookresearch/faiss#776]
#Summary 
Excuse me, there was a problem! I have installed anaconda in my virtual Linux machine! When i obey the wiki to install FAISS! Some problems occured!

# Platform
OS: Ubuntu 18.04
Tools: Anaconda 1.4.4

# Problems
When i executed this command line:
> yirufeng@ubuntu:~$ conda install faiss-cpu

problem:
> conda: error: failed to fetch repodata from 'http://repo.continuum.io/pkgs/pro/linux-64/'

Ask for help! Thanks

**Comment by beauby** [comment]
The Faiss conda packages are on the pytorch conda channel, so you need to specify that:
```
$ conda install --channel pytorch faiss
```
