### ISSUE TITLE
Ask for More information about IndexLSH

### ISSUE THREAD

**Issue by yyincc** [facebookresearch/faiss#785]
I am using Minhash method to build signatures for my datasets. However, when it comes to search step, I just wonder if faiss supports to build index for these signatures and help me find the nearest queries.

**Comment by mdouze** [comment]
There is no minhash implementation in Faiss. 
If you want to use Faiss indexes, you should probably start from the signatures before hashing.

**Comment by yyincc** [comment]
By the way, how the IndexLSH in faiss works ? There is no details in the paper.

**Comment by mdouze** [comment]
If you just Hamming distance search, then you should use an `IndexBinary`. 
Hmmm I realize they are not documented. We will fix that.

**Comment by beauby** [comment]
Docs for binary indexes is now available in the [wiki](https://github.com/facebookresearch/faiss/wiki/Binary-indexes).
