### ISSUE TITLE
question about faiss.kmeans

### ISSUE THREAD

**Issue by maozezhong** [facebookresearch/faiss#789]
Hello, guys. When I run the sample code kmeans.train() in wiki (some parameter change): https://github.com/facebookresearch/faiss/wiki/Faiss-building-blocks:-clustering,-PCA,-quantization, I get the following output : 

> Sampling a subset of 2560 / 2000000 for training
> Clustering 2560 points in 64D to 10 clusters, redo 1 times, 60 iterations
>   Preprocessing in 0.36 s
>   Iteration 59 (0.12 s, search 0.09 s): objective=12807.8 imbalance=1.005 nsplit=0

From the output, It seems no matter how large you vector row is, It just extract 2560 sample for train? Like in my case, my input vector shape is (2000000, 64), It seems just get a subset (2560, 64) for train, Do I miss anything? Hope for your help.

my codes is as follows:

> import numpy as np
> import faiss
> import time
> ncentroids = 10
> niter = 60
> verbose = True
> n = 2000000
> d = 64
> x = np.random.rand(n, d).astype('float32')
> d = x.shape[1]
> kmeans = faiss.Kmeans(d, ncentroids, niter=niter, verbose=verbose)
> t1 = time.time()
> kmeans.train(x)
> t2 = time.time()
> print(t2-t1)

**Comment by maozezhong** [comment]
@beauby

**Comment by beauby** [comment]
See [wiki#how-many-training-points-do-i-need-for-k-means](https://github.com/facebookresearch/faiss/wiki/FAQ#how-z).

**Comment by FoilHao** [comment]
Is it possible to use all the features instead of automatic sampling?
