### ISSUE TITLE
Error in  tests/demo_ivfpq_indexing 

### ISSUE THREAD

**Issue by zoe-cheung** [facebookresearch/faiss#79]
I am installing FAISS onto SUSE Linux Enterprise Server 11 (x86-64) with two nodes (one master and one slave node).  I installed Intel MKL and ran make and tests/demo_ivfpq_indexing and got the following error: 

tests/demo_ivfpq_indexing: error while loading shared libraries: libmkl_intel_ilp64.so: cannot open shared object file: No such file or directory

I search my directory and found libmkl_intel_ilp64.so in /opt/intel/compilers_and_libraries/linux/mkl/lib/intel64 . 

How do I solve this error?

**Comment by mdouze** [comment]
Hi 

Have you tried setting the LD_LIBRARY_PATH environment variable?

**Comment by zoe-cheung** [comment]
I already added the library variable in the makefile.inc and I check the directory. Do I set the variable somewhere else?


[makefileinc_zoe.txt](https://github.com/facebookresearch/faiss/files/921726/makefileinc_zoe.txt)

**Comment by zoe-cheung** [comment]
SOLVED: need to add "export $LD_LIBRARY_PATH" 

adding to makefile.inc didn't work
In the command line: export the set library path
