### ISSUE TITLE
Is faiss only a library and I have to implement other server function by myself?

### ISSUE THREAD

**Issue by Traeyee** [facebookresearch/faiss#790]
I just built the faiss on my server and test its performance. I love its fast speed! But when I tried to find out more information about serving such as dumping backup, distributed calculation, nothing was revealed. Does it mean that faiss is only a 'library' just like eigen. And I have to implement its 'serving' by myself, for instance, integrating with ps-lite?

**Comment by beauby** [comment]
Faiss is a library, so if you want to build a kNN service, you will have to handle the service part yourself.
