### ISSUE TITLE
Add additional attributes

### ISSUE THREAD

**Issue by Aayushktyagi** [facebookresearch/faiss#794]
Hi ,
As far as I get faiss provide index based similarity search which will return me index and distance (I,D) .I also want to store/add UID(a simple unique number for each vector) corresponding to each vector so that I can map it back to original image .
Is there any way it can be done?

Thanks 
Aayush

**Comment by beauby** [comment]
Faiss adds vectors sequentially in the order you provide them, starting with id 0, so you can maintain a mapping between your images and Faiss internal ids.
