### ISSUE TITLE
Write IndexFlatL2 in append mode

### ISSUE THREAD

**Issue by srijiths** [facebookresearch/faiss#797]
# Summary
Is it possible to write a FAISS index in append mode ? Assume i need to add new vectors on the fly to the existing index.

# Platform

OS: 

Faiss version: 
1.5.1

Faiss compilation options: 

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [x] Python

# Reproduction instructions

**Comment by beauby** [comment]
Yes, you can call `index.add(...)` multiple times.

**Comment by srijiths** [comment]
What i meant is like a file append mode to .index file on disk.

**Comment by beauby** [comment]
In that case no, as it stands you will have to re-write the whole index.

**Comment by namhong1412** [comment]
can you tell me how to append the index file to disk?
