### ISSUE TITLE
How to export the result of search?

### ISSUE THREAD

**Issue by Kimi-n** [facebookresearch/faiss#798]
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [X] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

 

Hi, We are facing the problem of exporting the searching result. We try to build the knn graph of 300M records, k = 100. Due to the memory limit of GPU and CPU, IndexShards was used for 8 GPUs.  We transformed the searching result D and I to adjacent table and exported the table to csv file for the following spark jobs. But the speed of exporting is very poor, for a sample dataset of 5M users and 100 neighbors for each user, it took 40mins for exporting the 500M rows to the disk. Is there any efficient way to do this?

**Comment by mdouze** [comment]
Using csv or any form of text to store vectors or matrices is slow.
