### ISSUE TITLE
How can I search a tsv file instead of an h5 file? Is converting the only way?

### ISSUE THREAD

**Issue by JasonLLu** [facebookresearch/faiss#799]
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by beauby** [comment]
I’m not sure I understand your question, but it does not seem to be about Faiss. Could you be more specific?

**Comment by JasonLLu** [comment]
Sorry, I guess my question is not directly related to Faiss. If I am trying to read a tsv file into and instance of IndexFlatL2() (as opposed to an h5 file), how would I approach that?

**Comment by beauby** [comment]
Whatever the format of your data, you should make it into a numpy array with shape `(n, d)` (`n` number of vectors, `d` dimension of vectors), and then feed it to Faiss.

**Comment by Jorgegs102** [comment]
Good evening!
did you manage to convert a h5 model to TSV? how did you do it?

Thanks!
