### ISSUE TITLE
Error in example "bench_gpu_sift1m"

### ISSUE THREAD

**Issue by dyzhou2015** [facebookresearch/faiss#80]
I am installing FAISS (gpu version) onto ubuntu 14.04 without errors. 
when I test the benchmark code, I encounter some errors maybe something with gpu ??
gpu info: Tesla K40c
zhoudy@mclab:~/faiss$ python bench_gpu_sift1m.py
load data
load GT
============ Exact search
Faiss assertion numDev != -1 failed in int faiss::gpu::getNumDevices() at utils/DeviceUtils.cpp:34Aborted (core dumped)
How do I solve this error ? any advices would be appreciated.

**Comment by wickedfoo** [comment]
There don't appear to be any GPU devices available to CUDA. Have you installed the GPU driver and CUDA properly? What does nvidia-smi say?

**Comment by dyzhou2015** [comment]
Thanks@wickedfoo . 
when I type the command : nvcc -V
it says: 
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
the I type the command :nvidia-smi
it says:
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:02:00.0     Off |                  N/A |
| 22%   45C    P8    14W / 250W |   2638MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:03:00.0     Off |                  N/A |
| 57%   83C    P2   112W / 250W |  12129MiB / 12287MiB |     67%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 0000:04:00.0     Off |                  N/A |
| 52%   83C    P2   145W / 250W |  12136MiB / 12287MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 0000:05:00.0     Off |                  N/A |
| 32%   71C    P2   104W / 250W |   7897MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
I use the first one in my program.
any advices?

**Comment by dyzhou2015** [comment]
solved!  when I update the gpu driver to 367. erros gones.
