### ISSUE TITLE
How to understand the nlist parameter？

### ISSUE THREAD

**Issue by yuxingfirst** [facebookresearch/faiss#804]
# Summary
the sample code of cpp tutorial， like this, how to understand the nlist ?

```
int nlist = 100;
int k = 4;
int m = 8;                             // bytes per vector
faiss::IndexFlatL2 quantizer(d);       // the other index
faiss::IndexIVFPQ index(&quantizer, d, nlist, m, 8);
// here we specify METRIC_L2, by default it performs inner-product search
index.train(nb, xb);
index.add(nb, xb);
```

Running on:
- [ ] CPU

Interface: 
- [ ] C++

**Comment by beauby** [comment]
All IVF index work by splitting the vectors into `nlist` clusters, according to the quantizer. During search time, only `nprobe` clusters are searched.

**Comment by yuxingfirst** [comment]
> All IVF index work by splitting the vectors into `nlist` clusters, according to the quantizer. During search time, only `nprobe` clusters are searched.

Thanks your reply， i got that.
