### ISSUE TITLE
About inner product and "IVFxFlat"

### ISSUE THREAD

**Issue by scriptboy1990** [facebookresearch/faiss#805]
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

 

Hi,I want to get inner products by using "IVFxFlat",the L2 quantizer is right? 

    quantizer = faiss.IndexFlatL2(d)
    index = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_INNER_PRODUCT)

**Comment by beauby** [comment]
You should use an `IndexFlatIP` instead of an `IndexFlatL2` as quantizer.
