### ISSUE TITLE
Why did not use openblas when the query vector number < 20?

### ISSUE THREAD

**Issue by XiaXuehai** [facebookresearch/faiss#806]

**Comment by mdouze** [comment]
I don't understand the question. Maybe look at 
https://github.com/facebookresearch/faiss/wiki/Implementation-notes#matrix-multiplication-to-do-many-l2-distance-computations

**Comment by XiaXuehai** [comment]
In this function:
```
void knn_inner_product (const float * x,
        const float * y,
        size_t d, size_t nx, size_t ny,
        float_minheap_array_t * res)
{
    if (d % 4 == 0 && nx < distance_compute_blas_threshold) {
        knn_inner_product_sse (x, y, d, nx, ny, res);
    } else {
        knn_inner_product_blas (x, y, d, nx, ny, res);
    }
}
```
Did you mean `knn_inner_product_sse` is faster than `knn_inner_product_blas` when nx < distance_compute_blas_threshold?

**Comment by beauby** [comment]
@XiaXuehai The aforementioned link states:
> We use implementation 1 when nq < 20 and d is a multiple of 4, and implementation 2 otherwise. The threshold 20 can be adjusted via global variable faiss::distance_compute_bias_threshold (accessible in Python via faiss.cvar.distance_compute_bias_threshold).
>
> Note that solution 2 may be less stable numerically than 1 for vectors of very different magnitudes, see discussion in issue #297.

So it really depends on your data, and you should try different values of `distance_compute_blas_threshold`, but the default should be sane in most cases.

**Comment by XiaXuehai** [comment]
Thanks
