### ISSUE TITLE
Daily updated search service

### ISSUE THREAD

**Issue by s-a-nersisyan** [facebookresearch/faiss#807]
Hi!

I'm developing a web app where I need some nearest neighbor search over ~ 100m vectors and I found faiss. As I understand, the most effective way to work with it is to store whole index in RAM. But here comes the problem -- my data should be daily updated and I don't understand how can I implement such functionality: in simple terms I have website's backend python code with variable "index" which stores whole index in RAM and I need some way to update it everyday (e.g. with cron). Perhaps you can give me some tip / advice about developing described feature? Thanks a lot!

**Comment by beauby** [comment]
It really depends on your use case, and what your constraints are: do you have several servers? can you afford downtime? It is more of a generic systems design question than a Faiss-related question.
