### ISSUE TITLE
Having trouble trouble interpreting the 2nd output from `IndexFlatIP`

### ISSUE THREAD

**Issue by Santosh-Gupta** [facebookresearch/faiss#812]
# Summary

I'm having trouble trouble interpreting the 2nd output from `IndexFlatIP`

Example 

question_index = faiss.IndexFlatIP(question_bert.shape[-1])

D2, I2 = question_index.search(question_bert[0:1].astype('float32'), k)

print(D2)

The output is
 [[405.85333 405.82928 405.46613 405.45767 405.16296 404.1385  403.4854   403.4804  403.43344 403.32248 403.2827  403.2272  403.19385 403.02863   402.93143 402.93143 402.82086 402.76416 402.6483  402.63184 402.62112   402.62112 402.57986 402.5463  402.49426 402.3978  402.31146 402.2641   402.26385 402.22153]] 

Not sure how to interpret this. This should be the value of the dot product, but a dot product gives values from -1 to 1  , where as all these values are around ~400

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ x] Python

# Reproduction instructions

**Comment by beauby** [comment]
You're probably confusing inner product and cosine similarity.

**Comment by Santosh-Gupta** [comment]
I think you're right. So if the vectors were normalized, the output would be within -1 to 1?

**Comment by beauby** [comment]
Yes, in that case the output would be between -1 and 1, cf. [Cauchy-Schwarz inequality](https://en.wikipedia.org/wiki/Cauchy%E2%80%93Schwarz_inequality).

**Comment by Santosh-Gupta** [comment]
it looks like I can normalize the vectors using faiss.normalize_L2(x)
