### ISSUE TITLE
GpuKMeans failed

### ISSUE THREAD

**Issue by NacyLiu** [facebookresearch/faiss#82]
i created a project and run GpuKMeans [,](https://github.com/facebookresearch/faiss/wiki/GPU-k-means-example) and i got an error like this:
```
[ 50%] Building CXX object ~/GpuKMeans.cpp.o
~/GpuKMeans.cpp: In function ‘int main(int, char**)’:
~/GpuKMeans.cpp:32:5: error: ‘GpuIndexFlatConfig’ is not a member of ‘faiss::gpu’
     faiss::gpu::GpuIndexFlatConfig config;
     ^
~/GpuKMeans.cpp:33:5: error: ‘config’ was not declared in this scope
     config.device = 0;            // this is the default
     ^
~build.make:62: recipe for target '~/GpuKMeans.cpp.o' failed
make[3]: *** [~/GpuKMeans.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target '~/all' failed
make[2]: *** [~/all] Error 2
CMakeFiles/Makefile2:79: recipe for target '~/rule' failed
make[1]: *** [~/rule] Error 2
Makefile:118: recipe for target 'proj' failed
make: *** [proj] Error 2
```
it seems that GpuIndexFlatConfig cannot be resolved, where am i wrong?

**Comment by mdouze** [comment]
Hi 

The `GpuIndexFlatConfig` object was introduced in the last version of Faiss. Could you upgrade and check if it works?

**Comment by NacyLiu** [comment]
I have update my faiss project and rebuilt it, but `GpuIndexFlatConfig` still cannot be resolved. I have still tested another way, in which the `GpuIndexFlatConfig` was removed , `faiss::gpu::GpuIndexFlatL2 index(&res, dim, config);` was replaced by `faiss::gpu::GpuIndexFlatL2 index(&res, 0, dim,  false);` as it was decaled in `gpu/GpuIndexFlat.h`, then I got an error like this:
```
~/GpuKMeans.cpp:32: undefined reference to `faiss::gpu::GpuIndexFlatL2::GpuIndexFlatL2(faiss::gpu::GpuResources*, int, int, bool)'
CMakeFiles/retrieval_basic_proj.dir/GpuKMeans.cpp.o:(.rodata._ZTVN5faiss3gpu14GpuIndexFlatL2E[_ZTVN5faiss3gpu14GpuIndexFlatL2E]+0x28): undefined reference to `faiss::gpu::GpuIndexFlat::add(long, float const*)'
```

I created the proj outside the `faiss/` dir, but I included `faiss/` and `faiss/gpu/` in my CMakeLists.txt, I also linked `${faiss_lib}/libgpufaiss.a ${OpenMP_CXX_FLAGS} ${OpenBLAS_LIB} `, did i miss something?

**Comment by mdouze** [comment]
I believe this issue is related to cmake. We currently support only compiling with the makefiles.
