### ISSUE TITLE
the wiki error about the use of PQ

### ISSUE THREAD

**Issue by quoniammm** [facebookresearch/faiss#823]
[Lower memory footprint](https://github.com/facebookresearch/faiss/wiki/Lower-memory-footprint)

here the wiki document seems to have an error.

![image](https://user-images.githubusercontent.com/12003094/57517925-79380780-734a-11e9-8733-a806ea5a0ee5.png)

m should be M, number of sub quantizers

**Comment by beauby** [comment]
Fixed, thanks!
