### ISSUE TITLE
CUDA error 35 

### ISSUE THREAD

**Issue by enjoy4** [facebookresearch/faiss#825]
# Summary

# Platform

OS:  ubuntu 16.04 

Faiss version: 1.5

Faiss compilation options: 

Running on:
-  GPU

Interface: 
- Python

# Reproduction instructions

Faiss assertion 'err__ == cudaSuccess' failed in int faiss::gpu::getNumDevices() at gpu/utils/DeviceUtils.cu:32; details: CUDA error 35 CUDA driver version is insufficient for CUDA runtime version
Aborted (core dumped)

>>> torch.version.cuda
'8.0.61'
>>> torch.cuda.is_available()
True
>>> torch.__version__
'0.4.0'

Mon May 13 17:31:31 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:17:00.0 Off |                  N/A |
|  0%   34C    P8    10W / 280W |      2MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:65:00.0  On |                  N/A |
|  0%   45C    P8    13W / 280W |    563MiB / 11169MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by beauby** [comment]
The error message
> `CUDA error 35 CUDA driver version is insufficient for CUDA runtime version`

states that your CUDA driver version is insufficient for CUDA 8.0 runtime. You should update your CUDA driver.

**Comment by enjoy4** [comment]
The original CUDA driver is suitable for cuda 8.0 according to nvidia file.  and When I update  the cuda driver to 390.87, the problem still exists.

**Comment by enjoy4** [comment]
Should I update the driver to the newest one?

**Comment by beauby** [comment]
Yes, please update your driver.
