### ISSUE TITLE
how to install faiss in windows?thanks

### ISSUE THREAD

**Issue by LiangWUSDU** [facebookresearch/faiss#829]
i want to use faiss in windows.but i failed.

**Comment by beauby** [comment]
Faiss is currently not available on Windows.

On Sun 19 May 2019 at 16:14, LiangWUSDU <notifications@github.com> wrote:

> i want to use faiss in windows.but i failed.
>
-- 
Lucas Hosseini
lucas.hosseini@gmail.com
