### ISSUE TITLE
Return unsorted results from search function

### ISSUE THREAD

**Issue by LiberiFatali** [facebookresearch/faiss#837]
Is there any way to get unsorted distances for **all** (not nearest neighbors) with the index search function? If this is not possible now, which part of the code should we modify to get this task done?

Thanks!

**Comment by mdouze** [comment]
It is not clear what you want to achieve here. 

If you want to compute the distance to all vectors in a dataset without encoding or compressing, you don't need Faiss for that. 

```
import numpy as np
xq = np.random.rand(3, 10)
xb = np.random.rand(4, 10)

dis = (xq ** 2).sum(1).reshape(-1, 1) + (xb ** 2).sum(1) - 2 * np.dot(xq, xb.T)

err = ((xq[1] - xb[2]) ** 2).sum() - dis[1, 2]
```
err should be 0 (up to machine precision)

**Comment by LiberiFatali** [comment]
Thanks for answering. Yes, this is one way to do it. Another way I have also tried PyTorch pairwise distance.
The thing is I'd like to utilize faiss (with the advantage in searching speed and low memory footprint).

I already have codes that using faiss to search for top_k neighbors of IndexFlat. This is one corner case, and if I use extra plain numpy arrays, I will need to maintain many copies of the same index.

**Comment by mdouze** [comment]
If you only need a flat index and you want to avoid memory copies, you can do the reverse (not using an index at all), see: 

https://github.com/facebookresearch/faiss/wiki/Brute-force-search-without-an-index

**Comment by LiberiFatali** [comment]
Thanks. I will try it
