### ISSUE TITLE
read_index just return Index*?

### ISSUE THREAD

**Issue by Markliang1994** [facebookresearch/faiss#84]
`Index *read_index (FILE * f, bool try_mmap = false);`
First I write IndexIVFPQ to a database such as redis. Then
I need read the index from db to IndexIVFPQ. but read_index only return Index*.  That mean I must do a downcast?

**Comment by wickedfoo** [comment]
See your other issue re: Redis.

You'll have to dynamic_cast the index instance returned to get the appropriate type.
