### ISSUE TITLE
redefine the type of idx_t 

### ISSUE THREAD

**Issue by yuxingfirst** [facebookresearch/faiss#841]
# Summary

In my business scenario， i will use the add_with_ids function to add vector to index， the xids is userid. but the type of xids is long and i need unsigned long.
Is it possible to redefine idx_t to unsigned long and recompile the faiss?

**Comment by beauby** [comment]
This is not currently possible, but you can use `IndexIDMap` or maintain your own mapping.

**Comment by yuxingfirst** [comment]
> This is not currently possible, but you can use `IndexIDMap` or maintain your own mapping.

ok, I will consider other solutions
