### ISSUE TITLE
HNSW support range_search?

### ISSUE THREAD

**Issue by UpCoder** [facebookresearch/faiss#850]
Hi,

I am curious if HNSW supports range_search. I just know the IndexIVFFlat support range_search function.

I am looking forward to your reply!
Thank you.

**Comment by mdouze** [comment]
No range_search is not supported because the exploration strategy of nearest neighbors is tuned for knn-search. So it is not easy to add either.

**Comment by UpCoder** [comment]
OK, Thanks
