### ISSUE TITLE
Faiss assertion 'p + size == head_' failed in void faiss::gpu::StackDeviceMemory::Stack::returnAlloc(char*, size_t, cudaStream_t) at gpu/utils/StackDeviceMemory.cpp:147

### ISSUE THREAD

**Issue by AmierCheng** [facebookresearch/faiss#852]
# Summary

# Platform

OS: Ubuntu 16.04 

Faiss version: 1.5.0

Faiss compilation options: 

Running on:
- [ ] GPU

Interface: 
- [ ] Python

# Reproduction instructions

 

error：
Faiss assertion 'p + size == head_' failed in void faiss::gpu::StackDeviceMemory::Stack::returnAlloc(char*, size_t, cudaStream_t) at gpu/utils/StackDeviceMemory.cpp:147

How to solve this problem？

Thanks！

**Comment by beauby** [comment]
Please post some code exhibiting your issue.

**Comment by AmierCheng** [comment]
![image](https://user-images.githubusercontent.com/20810178/58878192-3f69df00-8705-11e9-99b1-e61e1d1fc10c.png)
@beauby

**Comment by beauby** [comment]
@AmierCheng Please paste the code rather than screenshots, as I cannot execute a screenshot.

**Comment by beauby** [comment]
Also, please post a full example.

**Comment by AmierCheng** [comment]
# coding:utf-8

from flask import Flask, render_template, request, redirect, url_for, jsonify
from werkzeug.utils import secure_filename
from flask_cors import CORS
import os
from os import *
import redis
import uuid
import time
import sqlite3
import tensorflow as tf
import numpy as np
import faiss
import requests
import io
import shutil
import json
import base64
from PIL import Image
from io import BytesIO
import json
import gc

app = Flask(__name__)


@app.route('/uploadbase64', methods=['POST'])
def uploadbase64():
    try:
        if request.method == "POST":
            basepath = os.path.dirname(__file__)
            base64Str = request.values.get('base64')
            getpath = os.path.join(basepath, 'static/upload')
            guidname = str('w' + str(uuid.uuid1()))
            upload_path = os.path.join(basepath, getpath, secure_filename(guidname + ".jpg"))
            imgdata = base64.b64decode(base64Str)
            print(upload_path)
            files = io.open(upload_path, 'wb')
            files.write(imgdata)
            files.close()
            return jsonify({'result': 1, 'filename': "static/upload/" + guidname + ".jpg"})
    except:
        files.close()
        return jsonify({'result': 0})


@app.route('/upload', methods=['POST'])
def upload():
    try:
        if request.method == "POST":
            f = request.files['file']
            basepath = os.path.dirname(__file__)
            getpath = os.path.join(basepath, 'static/upload')
            guidname = str('w' + str(uuid.uuid1()))
            upload_path = os.path.join(basepath, getpath, secure_filename(guidname + ".jpg.tmp"))
        f.save(upload_path)
        os.rename(upload_path, os.path.join(basepath, getpath, secure_filename(guidname + ".jpg")))
        image_path = "/web/" + os.path.join(basepath, getpath, secure_filename(guidname + ".jpg"))
        return jsonify({'result': 1, 'filename': "static/upload/" + guidname + ".jpg"})
    except:
        return jsonify({'result': 0})


# 查找llid api
@app.route('/getlid', methods=['GET'])
def getlid():
    try:
        if request.method == "GET":
            getids = request.args.get('id')
            if (redisinit.exists(getids)):
                llid = redisinit.get(getids)
                return jsonify({'result': 1, 'datas': llid})
            else:
                return jsonify({'result': 0, 'datas': 0})
    except:
        return jsonify({'result': 0, 'datas': 0})


# 删除索引api
@app.route('/update', methods=['GET'])
def update():
    try:
        if request.method == "GET":
            imgid = request.args.get('imgid')
            llid = request.args.get('llid')
            deletekey = request.args.get('appkey')
            if (deletekey != "uuac72a2646fe9fca8c8659cbf7525uu"):
                return jsonify({'result': 4})
            # 删除指定目录下特征文件
            upFilePath = "/lineindex/featuretxt/" + imgid + "_" + llid + "w.jpg.txt"
            endFilePath = "/lineindex/featuretxt/" + imgid + "_" + llid + ".jpg.txt"
            if ((os.path.exists(upFilePath))):
                os.rename(upFilePath, endFilePath)
            # 更新指定缓存
            redisinit.delete(int(imgid) + 1)
            # 添加缓存
            redisinit.set(int(imgid) + 1, llid)
            return jsonify({'result': 1})
    except:
        return jsonify({'result': 0})


# 删除索引api
@app.route('/remove', methods=['GET'])
def remove():
    try:
        if request.method == "GET":
            imgid = request.args.get('imgid')
            llid = request.args.get('llid')
            deletekey = request.args.get('appkey')
            if (deletekey != "ddac56a3489fe9fca7c3221cbf7525ee"):
                return jsonify({'result': 4})
            # 删除指定目录下特征文件
            delFilePath = "/lineindex/featuretxt/" + imgid + "_" + llid + ".jpg.txt"
            if ((os.path.exists(delFilePath))):
                os.remove(delFilePath)
            # 删除指定索引
            index2.remove_ids(faiss.IDSelectorRange(int(imgid), int(imgid) + 2))
            # 删除指定缓存
            redisinit.delete(imgid)
            return jsonify({'result': 1})
    except:
        return jsonify({'result': 0})

# return jsonify({'t':[imgid]})
# endregion
# 添加索引api
@app.route('/add', methods=['POST'])
def add():
    if request.method == "POST":
        basepath = os.path.dirname(__file__)
        imgid = request.values.get('imgid')
        llid = request.values.get('llid')
        txtpath = txt_dir + str(imgid) + '_' + str(llid) + '.jpg.txt'
        getpath = os.path.join(basepath, 'static/add/' + str(int(imgid) + 1) + '.jpg')
        print(llid)
        appkey = request.values.get('appkey')
        print(appkey)
        if (appkey != "mmac89a3489fe9fca7c6548cef7324nn"):
            return jsonify({'result': 4})
        if (os.path.exists(getpath)):
            return jsonify({'result': 3})
            print(imgid)
        if (os.path.exists(txtpath)):
            return jsonify({'result': 3})
        base64Str = request.values.get('base64')
        getpath = os.path.join(basepath, 'static/uploads')
        guidname = str('w' + str(uuid.uuid1()))
        upload_path = os.path.join(basepath, getpath, secure_filename(guidname + ".jpg.tmp"))
        imgdata = base64.b64decode(base64Str)
        print(upload_path)
        files = io.open(upload_path, 'wb')
        files.write(imgdata)
        files.close()
    os.rename(upload_path, os.path.join(basepath, getpath, secure_filename(str(int(imgid) + 1) + ".jpg")))
    image_path = "/web/" + os.path.join(basepath, getpath, secure_filename(str(int(imgid) + 1) + ".jpg"))
    # copy图片到add目录
    img_newpath = "/web/static/images/" + str(int(imgid) + 1) + ".jpg"
    shutil.copyfile(image_path, img_newpath)
    issucess = getimgfeatures(img_newpath, imgid, llid)
    if (issucess):
        return jsonify({'result': 1})
    else:
        return jsonify({'result': 0})


# url查询api
@app.route('/search', methods=['GET'])
def search():
    if request.method == "GET":
        result = 0
        lists = []
        imgsrc = request.args.get('src')
        # 判断图片大小
        imglen = requests.head(imgsrc).headers.get('content-length')
        if (len(imglen) > 2 * 1024 * 1024):
            result = 2
            results = dict(result=result, datas=lists)
            return jsonify(results)
        basepath = os.path.dirname(__file__)
        getpath = os.path.join(basepath, 'static/uploads')
        guidname = str('w' + str(uuid.uuid1()))
        upload_path = os.path.join(basepath, getpath, secure_filename(guidname + ".jpg"))
        response = requests.get(imgsrc)
        image = Image.open(BytesIO(response.content))
        rgb_im = image.convert('RGB')
        rgb_im.save(upload_path)
        # os.rename(upload_path,os.path.join(basepath, getpath,secure_filename(guidname+".jpg")))
        image_path = "/web/" + os.path.join(basepath, getpath, secure_filename(guidname + ".jpg"))
        print(image_path)
        if (os.path.exists(image_path)):
            image_data = tf.gfile.FastGFile(image_path, 'rb').read()
            pool_reshape = sess.graph.get_tensor_by_name('pool_3/_reshape:0')
            tzfe_datas = sess.run(pool_reshape, {'DecodeJpeg/contents:0': image_data})
            tzfe_datqa_np = np.squeeze(tzfe_datas)
            tzfe_datas_splits = np.fromstring(tzfe_datqa_np, dtype='float32')
            bottleneck_string = ','.join(str(x) for x in tzfe_datas_splits)
            ottleneck_values = [float(x) for x in bottleneck_string.strip().split(',')]
            # sess.close()
            xq = np.array([ottleneck_values]).astype('float32')
            sdatas = []
            m = 0
            D, I = gpu_index.search(xq, 50)
            for imgid in np.nditer(I):
                llid = redisinit.get(int(imgid))
                info = setdatas({'id': int(imgid), 'imgid': int(imgid) - 1, 'score': D[0, m], 'llid': llid})
                sdatas.append(info)
                m = m + 1
            # lists.append(int(imgid))
            result = 1
            results = dict(result=result, filename="static/uploads/" + guidname + ".jpg", datas=sdatas)
            cc = str(results)
            jsoninfos = json.loads(cc.replace("'", '"'))
            jsoninfo = json.dumps(jsoninfos)
            return jsoninfo


# 上传文件查询api
@app.route('/similar', methods=['POST'])
def similar():
    if request.method == "POST":
        f = request.files['file']
        basepath = os.path.dirname(__file__)
        getpath = os.path.join(basepath, 'static/uploads')
        guidname = str(uuid.uuid1())
        upload_path = os.path.join(basepath, getpath, secure_filename(guidname + ".jpg.tmp"))
    f.save(upload_path)
    os.rename(upload_path, os.path.join(basepath, getpath, secure_filename(guidname + ".jpg")))
    image_path = "/web/" + os.path.join(basepath, getpath, secure_filename(guidname + ".jpg"))
    print(image_path)
    result = 0
    lists = []
    if (os.path.exists(image_path)):
        image_data = tf.gfile.FastGFile(image_path, 'rb').read()
        pool_reshape = sess.graph.get_tensor_by_name('pool_3/_reshape:0')
        tzfe_datas = sess.run(pool_reshape, {'DecodeJpeg/contents:0': image_data})
        tzfe_datqa_np = np.squeeze(tzfe_datas)
        tzfe_datas_splits = np.fromstring(tzfe_datqa_np, dtype='float32')
        bottleneck_string = ','.join(str(x) for x in tzfe_datas_splits)
        ottleneck_values = [float(x) for x in bottleneck_string.strip().split(',')]
        # sess.close()
        xq = np.array([ottleneck_values]).astype('float32')
        sdatas = []
        m = 0
        D, I = gpu_index.search(xq, 50)
        for imgid in np.nditer(I):
            llid = redisinit.get(int(imgid))
            if (llid.__contains__('w') == False):
                info = setdatas({'id': int(imgid), 'imgid': int(imgid) - 1, 'score': D[0, m], 'llid': llid})
            sdatas.append(info)
            m = m + 1
        # lists.append(int(imgid))
        result = 1
        print D
        results = dict(result=result, filename="static/uploads/" + guidname + ".jpg", datas=sdatas)
        cc = str(results)
        jsoninfos = json.loads(cc.replace("'", '"'))
        jsoninfo = json.dumps(jsoninfos)
        return jsoninfo


@app.route('/pcsimilar', methods=['POST'])
def pcsimilar():
    if request.method == "POST":
        basepath = os.path.dirname(__file__)
        base64Str = request.values.get('base64')
        sizes = request.values.get('sizes')
        istrue = False
        try:
            int(sizes)
            istrue = True
        except:
            istrue = False
        if (istrue == False):
            return jsonify({'result': 5})
        if (int(sizes) > 50):
            return jsonify({'result': 6})
        getpath = os.path.join(basepath, 'static/uploads')
        guidname = str('w' + str(uuid.uuid1()))
        upload_path = os.path.join(basepath, getpath, secure_filename(guidname + ".jpg"))
        imgdata = base64.b64decode(base64Str)
        print(upload_path)
        files = io.open(upload_path, 'wb')
        files.write(imgdata)
        files.close()
        image_path = "/web/" + os.path.join(basepath, getpath, secure_filename(guidname + ".jpg"))
        print(image_path)
        if (os.path.exists(image_path)):
            image_data = tf.gfile.FastGFile(image_path, 'rb').read()
            # with tf.Session() as sess:
            pool_reshape = sess.graph.get_tensor_by_name('pool_3/_reshape:0')
            tzfe_datas = sess.run(pool_reshape, {'DecodeJpeg/contents:0': image_data})
            tzfe_datqa_np = np.squeeze(tzfe_datas)
            tzfe_datas_splits = np.fromstring(tzfe_datqa_np, dtype='float32')
            bottleneck_string = ','.join(str(x) for x in tzfe_datas_splits)
            ottleneck_values = [float(x) for x in bottleneck_string.strip().split(',')]
            # sess.close()
            xq = np.array([ottleneck_values]).astype('float32')
            sdatas = []
            m = 0
            D, I = gpu_index.search(xq, int(sizes))
            for imgid in np.nditer(I):
                llid = redisinit.get(int(imgid))
                info = setdatas({'id': int(imgid), 'imgid': int(imgid) - 1, 'score': D[0, m], 'llid': llid})
                sdatas.append(info)
                m = m + 1
            # lists.append(int(imgid))
            result = 1
            results = dict(result=result, datas=sdatas)
            cc = str(results)
            jsoninfos = json.loads(cc.replace("'", '"'))
            jsoninfo = json.dumps(jsoninfos)
            return jsoninfo


def getimgfeatures(imgpath, imgid, llid):
    # 判断文件是否存在
    # basepath = os.path.dirname(__file__)
    # getpath='/web/static/uploads/add/'
    # impath=getpath+imgpath
    issave = False
    try:
        # if(os.path.exists(imgpath)):
        #		create_graph()
        # sesss=tf.Session()
        image_data = tf.gfile.FastGFile(imgpath, 'rb').read()
        pool_reshape = sess.graph.get_tensor_by_name('pool_3/_reshape:0')
        tzfe_datas = sess.run(pool_reshape, {'DecodeJpeg/contents:0': image_data})
        tzfe_datqa_np = np.squeeze(tzfe_datas)
        tzfe_datas_splits = np.fromstring(tzfe_datqa_np, dtype='float32')
        bottleneck_string = ','.join(str(x) for x in tzfe_datas_splits)
        ottleneck_values = [float(x) for x in bottleneck_string.strip().split(',')]
        txt_feauture = str(ottleneck_values).replace('[', '').replace(']', '').replace(', ', ' ')
        txtpath = txt_dir + str(imgid) + '_' + str(llid) + 'w.jpg.txt'
        save(txtpath, txt_feauture)
        print (txtpath)
        ids = np.array([imgid], dtype=np.int)
        index2.add_with_ids(readtxt(txtpath), ids + 1)
        redisinit.set(str(int(imgid) + 1), llid)
        issave = True
    except:
        issave = False
    return issave


def create_graph():
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(tf.gfile.FastGFile(os.path.join(model_dir, 'output_graph.pb'), 'rb').read())
        tf.import_graph_def(graph_def, name='')


# 保存图片特征值txt文件
def save(filename, contents):
    fh = io.open(filename, 'wb')
    fh.write(contents)
    fh.close()


# 读取图片特征值txt文件
def readtxt(filename):
    addindex = np.loadtxt(str(filename), dtype=np.float32)
    xq = np.array([addindex])
    return xq


class setdatas(object):
    __slots__ = ('id', 'imgid', 'score', 'llid')

    def __init__(self, d):
        for i in self.__slots__:
            setattr(self, i, d[i] if i in d else None)

    def to_dict(self):
        return {i: getattr(self, i) for i in self.__slots__}

    def __str__(self):
        return str(self.to_dict())

    def __repr__(self):
        return str(self.to_dict())


if __name__ == '__main__':
    faiss.OMP_NUM_THREADS = 48
    # 模型路径初始化
    model_dir = '/helloworld/'
    # 初始化缓存
    redisinit = redis.Redis(host='127.0.0.1', port=6379, db=0)
    # redisinit.set('hello','world')
    config = tf.ConfigProto()

    config.gpu_options.allow_growth = True
    config.gpu_options.per_process_gpu_memory_fraction = 0.5
    sess = tf.Session(config=config)
    #sess = tf.Session(config=tf.ConfigProto(
    #    device_count={"CPU": 12},
    #    inter_op_parallelism_threads=10,
    #    intra_op_parallelism_threads=10
    #))
    create_graph()

    # 一个一个加入索引
    # txt_dir='/lineindex/featuretxt/'
    txt_dir = '/pythonpath/20190531tietu/'
    # txt_dir='/pythonpath/20190421/'
    dirs = os.listdir(txt_dir)
    d = 2048
    index = faiss.IndexFlatL2(d)
    index2 = faiss.IndexIDMap(index)
    file = ''
    indexids = 100
    try:
        for file in dirs:
            ids_llid = file.replace('.jpg.txt', '').split('_')
            ids = np.array([ids_llid[0]], dtype=np.int)
            index2.add_with_ids(readtxt(txt_dir + file), ids + 1)
            print(int(ids_llid[0]) + 1)
            print(ids_llid[1])
            if (redisinit.exists(int(ids_llid[0]) + 1) == 0):
                redisinit.set(int(ids_llid[0]) + 1, str(ids_llid[1]))
    except:
        print (file)
    # print("load datas fail!")
    gpu_index = faiss.index_cpu_to_all_gpus(index2)
    # app.debug = True
    app.config['MAX_CONTENT_LENGTH'] = 2 * 1024 * 1024
    ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif'])
    CORS(app, supports_credentials=True)
    app.run('192.168.1.213', 8089)
@beauby

**Comment by beauby** [comment]
Closing, as the issue has been addressed in #321.
