### ISSUE TITLE
Perform merge_tables on device

### ISSUE THREAD

**Issue by cjnolet** [facebookresearch/faiss#853]
On cuML, we are currently working to provide multi-Node multi-GPU support for the brute-force kNN. For the single node multi-GPU implementation, we have been using your `bruteForcekNN` function and the `merge_tables` function from `IndexShards.h`, however `merge_tables` appears to only work on host memory.

I don't believe a simple truncated merge would be too hard to do on device here and I can contribute code for this.

**Comment by wickedfoo** [comment]
If the results from each GPU can be copied to a single GPU, `runBlockSelectPair` can be run on the concatenated results to produce the final selected results.

https://github.com/facebookresearch/faiss/blob/master/gpu/utils/BlockSelectFloat.cu#L94

However the data from each GPU's partial results would need to be concatenated column-wise not row-wise (the above function takes row-major input, with the rows being the problem id, the columns being the data within that problem).

**Comment by cjnolet** [comment]
Thank you for pointing me to this! It makes sense why they would need to be concatenated this way.
