### ISSUE TITLE
Python2 installation fail: fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by WIll-Xu35** [facebookresearch/faiss#854]
@beauby 
Hi.

I'm installing faiss for python2 (I've successfully installed faiss for python3). The same error occurs as I previously installing for python3, `fatal error: Python.h: No such file or directory`. When installing for python3, I update swig version and solved this problem. This time the directory that python -c "import sysconfig; print(sysconfig.get_path('include'))" returns does not exist. It returns /usr/local/include/python2.7, but it is empty and the correct directory seems to be /usr/include/python2.7, according to my python3 installation experience.

Would you please show me how to solve this problem? Thanks.

**Comment by dingwoai** [comment]
here is my solution:
1. open ur makefile.inc file
2. "PYTHONCFLAGS =  -I/usr/include/python2.7 -I/usr/include/python2.7" instead of "PYTHONCFLAGS =  -I/usr/local/include/python2.7 -I/usr/local/include/python2.7"
3. make and then make py
works for me

**Comment by beauby** [comment]
@dingwoai's answer is right. There seems to be an inconsistency in the paths returned by python27 on Ubuntu.

**Comment by JanisSharma** [comment]
On Ubuntu, I was running Python 3 and I had to install

sudo apt-get install python3-dev
If you want to use a version of Python that is not linked to python3, install the associated python3.x-dev package. For example:

sudo apt-get install python3.5-dev

Find All solutions [Here](https://icetutor.com/question/fatal-error-python-h-no-such-file-or-directory)
