### ISSUE TITLE
Can Faiss GPU index be shared between processes?

### ISSUE THREAD

**Issue by AmitRozner** [facebookresearch/faiss#857]
# Summary
Can Faiss GPU index be shared between processes? i.e. is it possible to call search on an index which is in the GPU from multiple processes?

OS: Ubuntu 18.04 LTS

Running on:
- [ ] CPU
- [x ] GPU

Interface: 
- [ ] C++
- [x ] Python

# Reproduction instructions
Currently, I call Faiss from each process using:
```
        index = faiss.read_index(index.index))
        co = faiss.GpuClonerOptions()
        res = faiss.StandardGpuResources()
        index = faiss.index_cpu_to_gpu(res, 0, index , co)
```
This result in a waste of GPU memory. Is it possible to search the index from other python processes as well instead of reloading it? 
I just search the index so it can be on the GPU the whole time.

**Comment by wickedfoo** [comment]
This is not possible and will not be implemented, as this requires CUDA IPC handles etc.

Why are you trying to do this? Why can't the index just be owned by a single process and you route requests to that process?

**Comment by AmitRozner** [comment]
I can do that, was just wondering whether it is already implemented by any of Faiss methods.
