### ISSUE TITLE
how to guaranteed uniqueness of id in index with add_with_ids

### ISSUE THREAD

**Issue by handsomefun** [facebookresearch/faiss#859]
# Summary

# Platform

OS: Centos 7.5

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

Hi,
I  try try to add vector with a special id into index by add_with_ids api, also I do not want to add duplicate vector(identified by id) into index. 
But i find this index allow duplicate id exist, so i have to maintain an id set to decision whether exist or not. 
So, my questions :
1. Is there some api of index can be used to decision whether some id exist or not. 
2. Is there some api guaranteed uniqueness of id

<pre><code>
import faiss
import numpy as np

v = np.random.rand(1,128).astype('float32')
index = faiss.IndexFlatL2(128)
index = faiss.IndexIDMap(index)

index.add_with_ids(v, np.array([1001]))
print(index.ntotal) # 1
index.add_with_ids(v, np.array([1001]))
print(index.ntotal) # 2</code></pre>

**Comment by wickedfoo** [comment]
You would have to keep track of it yourself and enforce it. There is no requirement that the IDs are unique, in fact some use cases may desire that multiple vector have the same identifier.

**Comment by handsomefun** [comment]
> You would have to keep track of it yourself and enforce it. There is no requirement that the IDs are unique, in fact some use cases may desire that multiple vectors have the same identifier.

Ok, thanks
