### ISSUE TITLE
RuntimeError: Error in faiss::Index *faiss::read_index(faiss::IOReader *, int)

### ISSUE THREAD

**Issue by abmygate** [facebookresearch/faiss#861]
# Summary

RuntimeError while trying to read index. I'm trying to use faiss with gunicorn/uwsgi. I'm currently using 3 workers and have simultaneous add and search operations. Sometimes I encounter a RuntimeError with the following trace

`RuntimeError: Error in faiss::Index *faiss::read_index(faiss::IOReader *, int) at index_io.cpp:1056: Error: 'size >= 0 && size < (1L << 40)' failed`

And sometimes the error message is: 
`RuntimeError: Error in faiss::Index *faiss::read_index(faiss::IOReader *, int) at index_io.cpp:892: Error: 'ret == (size)' failed: read error in index_dump: 677867 != 1312512 (Invalid argument)`

# Platform

OS: macOS 10.14.5

Faiss version: 1.5.1

Faiss compilation options: conda install faiss

Running on:
- [X] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

I'm not sure how to reproduce this consistently.

#
I would like to understand why this behaviour is observed. Are there any steps that I can follow to avoid them?

**Comment by beauby** [comment]
Concurrent add is not supported, which might explain corrupted indexes.

**Comment by abmygate** [comment]
Thanks, I understand concurrent add is not supported.

Each worker in gunicorn/uwsgi maintains a separate index so corruption of these indexes is not possible (as far as I understand), does it mean that I'm somehow writing to the save file (sometimes) simultaneously from two separate workers and it is corrupted?

**Comment by mdouze** [comment]
These errors mean there is a data corruption in the file.
Needless to say, writing to the same file from several threads is not supported either...

**Comment by husterlantern1** [comment]
RuntimeError while trying to read index.
Error in faiss::Index* faiss::read_index(faiss::IOReader*, int) at impl/index_read.cpp:445: Error: 'ret == (size)' failed: read error in /index_file/index_1.idx: 10954941 != 295036288 (Success).
Can anyone help ? Thanks a lot!

**Comment by getoar-g** [comment]
Does anyone has the solution for this problem yet?

**Comment by rahulbhoyar1995** [comment]
I am also getting this error.

RuntimeError: Error in faiss::Index* faiss::read_index(faiss::IOReader*, int) at /project/faiss/faiss/impl/index_read.cpp:1053: Index type 0x19ef32bc ("\xbc2\xef\x19") not recognized


This is my code :

```
from langchain.vectorstores import FAISS
from langchain_openai import OpenAIEmbeddings
embeddings = OpenAIEmbeddings()
vectordb = FAISS.load_local(VECTOR_DATABASE_PATH, embeddings)

```
Does anyone knows how to resolve this ?

**Comment by SYKKKKKKKKKKK** [comment]
> RuntimeError。在 impl/index_read.cpp：445 处 faiss：：Index* faiss：：read_index（faiss：：IOReader*， int） 中出现错误：错误：“ret == （size）”失败：/index_file/index_1.idx 中的读取错误：10954941 ！= 295036288（成功）。谁能帮忙？多谢！

请问解决了吗
