### ISSUE TITLE
there is a way that parse the index file to db(such as redis)?

### ISSUE THREAD

**Issue by Markliang1994** [facebookresearch/faiss#87]
first I use write_index produce a index file(such as faiss.index) 
then I want parse the index file and write the index to redis

**Comment by wickedfoo** [comment]
Putting the index in a k/v type store such as Redis makes no sense. The entire purpose of the Faiss index is to provide for efficient nearest neighbor search. Maybe only if you wanted to put each inverted list in a separate entry, but then you'd still have to gather those entries together for a search.

What problem are you trying to solve here?

**Comment by Markliang1994** [comment]
I have one big common Index named CommonIndex, Then every developer can define their own resource and generate a Index named CustomIndex. One developer can define many custom research. when a query come, I will search in CommonIndex and CustomIndex, then merge these search results and get the best one.

**Comment by wickedfoo** [comment]
Unless the index is actually unpacked in memory in the form that the appropriate index (e.g., IndexIVFPQ) wants, you'd have to suffer the cost of deserialization of the index in the form that it exists in Redis. This seems very expensive.

Faiss is designed to be the index, not to be packed in some other indexing structure.

Unless the indices are small, this seems like it would be very slow.

**Comment by Markliang1994** [comment]
first thank your advice. we want to make the service be distributed so as if we have to face redis.
I will write a tool which serialize these to redis. have a try ( I feel I am in a wrong way =-=)

**Comment by mdouze** [comment]
Please re-open if you have more questions on this topic.
