### ISSUE TITLE
Support for double precision vectors ?

### ISSUE THREAD

**Issue by unmeshvrije** [facebookresearch/faiss#870]
Hello,

I could not use the library because I have double precision vectors and all train() methods use float in their signature.
I think I need to write overrides for all methods that contain floats.

Is this work worth to be added in a PR ?

**Comment by wickedfoo** [comment]
Just convert/round your data to single precision floating point before passing it to us.

We almost certainly won't change any of the compute to allow native double precision in the math kernels, so it's just a question of whether you do the conversion or we do, and letting you do the conversion makes the most sense to me.

**Comment by unmeshvrije** [comment]
@wickedfoo , Thank you for the suggestion. Is there any technical reason why "native double precision in the math kernels" is not allowed ?

**Comment by mdouze** [comment]
@unmeshvrije, Faiss focuses on high-performance search and most indexes are approximate. In this context, we benefit from the more compact and faster operations on float32 numbers. The added precision of float64 is of no use to Faiss.

**Comment by unmeshvrije** [comment]
Thank you @mdouze !
