### ISSUE TITLE
Question: how can I specify which gpu to run index on?

### ISSUE THREAD

**Issue by yangliu2** [facebookresearch/faiss#878]
For example, I can put indexing on gpu 1 with 
`gpu_index = faiss.index_cpu_to_gpu(res, 1, index)`
but if I want to put on gpu 1,2,3 because I'm using gpu 0, how can I use index_cpu_to_gpu_multiple or index_cpu_to_gpu_multiple_py? I was not able to find documentation on this.

**Comment by mdouze** [comment]
see https://github.com/facebookresearch/faiss/blob/master/python/faiss.py#L419

`index_cpu_to_gpu_multiple_py` is a slighltly higher level function than the C++ version. 

To do this you need to adapt the wrapper a little bit: 

```python

def my_index_cpu_to_gpu_multiple(resources, index, co=None, gpu_nos=None):
    vres = faiss.GpuResourcesVector()
    vdev = faiss.IntVector()
    if gpu_nos is None: 
        gpu_nos = range(len(resources))
    for i, res in zip(gpu_nos, resources):
        vdev.push_back(i)
        vres.push_back(res)
    index = faiss.index_cpu_to_gpu_multiple(vres, vdev, index, co)
    index.referenced_objects = resources
    return index
```

**Comment by yangliu2** [comment]
Greatly appreciated! Maybe my data is small, but running on 3 gpu is actually slower than 1 gpu (6 seconds instead of 5s) for me. It only used 1630 MB of GPU memory. My guess is the overhead of moving across gpus resulted in the additional time. I have 20000x512 for the matrix to index, and I'm searching all 20,000 against all 20,000 to find similar ones.

**Comment by mdouze** [comment]
Hmmm... This is not normal. At 5s, the overheads (data copy and distribution) should be negligible wrt. actual computations. And of course it does not calculate 3 times. 
I tested this on a 8-gpu machine, and I observed that for 20000 vectors, the 1-GPU option is indeed better, but a lot faster than what you report. For 100k vectors, 3 GPUs  is better. 
See here: 
https://gist.github.com/mdouze/bfa06e7dc0869f0c0495928aab25800f

**Comment by yangliu2** [comment]
Thank you again for the awesome code! It's always nice to compare code and see if I'm doing it as intended. I agree, for the new one I'm using 1,000,000 x 512, it's faster with improvement from 83 s to 43 s after using 3 instead of 1 GPU. And it's about 1/3 of the memory usage on each GPU. Cool beans!
