### ISSUE TITLE
How to search k nearest neighbors of index

### ISSUE THREAD

**Issue by BigHeartC** [facebookresearch/faiss#880]
# Summary
My index is big (about 10 million), and I train it by 'OPQ32_64,IVF16384,PQ32'. 
Now I want to search k nearest neighbors of one of my indexes, what should I do？

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by beauby** [comment]
See the [wiki](https://github.com/facebookresearch/faiss/wiki/Getting-started#searching): `index.search(queries, k)` to get the `k` nearest neighbors of your query vectors.

**Comment by BigHeartC** [comment]
@beauby hi, beauby, I think you may misunderstand what I said.

My query is in my index and I can't get the original vector. For example, I want to search for the k nearest neighbors of the 5th index, but I can't get the original vector of the 5th index through the Faiss APIs. So I can't use 'index.search'. Is there any function that can do this?

**Comment by beauby** [comment]
The `reconstruct` method returns the stored approximation of a vector from your index. If you want the exact vector, you need to store it outside the index.

**Comment by ajanaliz** [comment]
is there a way to find the k-nn of each item in the IndexIVFFlat? for the whole index? I think searching every single vector all over again seems redundant since the index is already trained? am I wrong?
