### ISSUE TITLE
The version installed with conda is inconsistent with the version in the code

### ISSUE THREAD

**Issue by luochenxi** [facebookresearch/faiss#882]
# Summary
Hi,@beauby @mdouze 
This releases version[#712](https://github.com/facebookresearch/faiss/releases/tag/v1.5.3) is what I like, I want to upgrade it. 
But found during the upgrade process，the version installed with conda is inconsistent with the version in the code.
# Platform
OS: macOS 10.14.1 

Installed info:
```text
## Package Plan ##

  environment location: /anaconda2

  added / updated specs:
    - faiss-cpu


The following NEW packages will be INSTALLED:

  blas               pkgs/main/osx-64::blas-1.0-mkl
  faiss-cpu          pytorch/osx-64::faiss-cpu-1.5.3-py27h04f5b5a_0
  libgfortran        pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2
  mkl_fft            pkgs/main/osx-64::mkl_fft-1.0.12-py27h5e564d8_0
  mkl_random         pkgs/main/osx-64::mkl_random-1.0.2-py27h27c97d8_0
  numpy              pkgs/main/osx-64::numpy-1.16.4-py27hacdab7b_0
  numpy-base         pkgs/main/osx-64::numpy-base-1.16.4-py27h6575580_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

Code version:
```shell
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 16:24:02)
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import faiss

In [2]: faiss.__version__
Out[2]: '1.5.2'
```

# Instructions
I want to show v1.5.3 in the code and use the features:
- [ ] add basic support for 6 new metrics in CPU IndexFlat and IndexHNSW (#848);
- [x] add support for IndexIDMap/IndexIDMap2 with binary indexes (#780).

of that version.  

What do I need to do for this? 
Thank you very much！

**Comment by beauby** [comment]
The version reported is wrong, the conda package is indeed a build of v1.5.3, with all the new features. I will upload new packages with corrected version number.

**Comment by juve** [comment]
@beauby I think some of the conda packages still have inconsistent versions:

```
$ conda create -n faiss python=3.6 pytorch::faiss-cpu=1.5.3
...
$ conda run -n faiss python -c "import faiss; print(faiss.__version__)"
1.5.2
```

**Comment by beauby** [comment]
Thanks for the reminder @juve – will fix it this week.
