### ISSUE TITLE
remove_ids Usage

### ISSUE THREAD

**Issue by engmubarak48** [facebookresearch/faiss#883]
I have a question of how to use remove_ids. 
I am trying to read a saved index and then to remove vectors by specifying their IDs. 

Here what I am trying to do. 

    d = 512
    nq = 1  # nb of queries to delete
    str_emb = # string that consists of vecors (embedding) to be stored. 
    xb = np.zeros((nq, d)).astype('float32')  # query
    # ids = np.arange(xb.shape[0])
    index = faiss.read_index("../doc/512_new")
    print(index.ntotal)
    ids = index.ntotal
    # print(str_emb)
    str_emb = str_emb.strip("()")
    str_emb = str_emb.replace(',', '')
    str_emb = np.array([v for v in str_emb.split(' ') if v]).astype(np.float)
    xb[0] = str_emb
    # print(xb)
    k = 4  # we want to see 4 nearest neighbors
    D, I = index.search(xb, k)  # actual search
    print(I)
    k1, k2, k3, k4 = I[0][0], I[0][1], I[0][2], I[0][3]
    # print(k1)
    idsel = faiss.IDSelector(k1, faiss.swig_ptr(np.array(ids)))
    index.remove_ids(idsel)
    # index.remove_ids(k1)
    print(index.ntotal)
    print('removed')
    # print(I[-1:])
    print("Distance:")
    print(D)
As you can see I want to remove the K1, which is the id of one of the vectors I want to remove.
in my case k1= 624, so I want to remove this from the index. I don't know what I am missing. 

one of the errors I am receiving 

    File "/home/mubarak/miniconda3/envs/face-recognition/lib/python3.6/site- 
    packages/faiss/swigfaiss.py", 
    line 5242, in __init__
    raise AttributeError("No constructor defined - class is abstract")

    AttributeError: No constructor defined - class is abstract

NB: when creating my index I created with indexIDMap. 
in this format:
   index = faiss.IndexFlatL2(d)  # build the index size of vector
   index2 = faiss.IndexIDMap(index)

**Comment by mdouze** [comment]
The code is not self-contained, so it is unclear what the issue is.

**Comment by engmubarak48** [comment]
> The code is not self-contained, so it is unclear what the issue is.

Thanks for your reply,  but fixed my issue.

**Comment by chiragsanghvi10** [comment]
Hi @engmubarak48,
I am working on something similar, may I know how did you delete the ID and corresponding vector?

**Comment by engmubarak48** [comment]
@chiragsanghvi10 sorry for the late reply, I i haven't looked at FAISS for sometime. Here is the delete function of my code [https://github.com/engmubarak48/Face-Recognition-System/blob/3b1b0993b126cbff788b5ab9acb3a5251cabfc61/app#L187](url).

You can also view, how it is used in the webservice here [https://github.com/engmubarak48/Face-Recognition-System/blob/3b1b0993b126cbff788b5ab9acb3a5251cabfc61/appservice#L36](url)

Hope this helps,
