### ISSUE TITLE
AttributeError: 'IndexPreTransform' object has no attribute 'invlists'

### ISSUE THREAD

**Issue by winself** [facebookresearch/faiss#884]
# Summary

# Platform centOS

Faiss version:  1.5.2

Running on: CPU

Interface:   Python

 I changed the "IVF4096,Flat" to  'OPQ20_80,IMI2x12,PQ20'  and run demo_ondisk_ivf.py failed.

error information : 
AttributeError: 'IndexPreTransform' object has no attribute 'invlists'

If I use 'OPQ20_80,IMI2x12,PQ20'  how to merge the index file.

Thanks

**Comment by beauby** [comment]
You're adding an index pre-transform, so you'll need to call `index.index.invlists`.

**Comment by winself** [comment]
but I meet "AttributeError: 'Index' object has no attribute 'invlists'"

**Comment by winself** [comment]
> You're adding an index pre-transform, so you'll need to call `index.index.invlists`.

but I meet "AttributeError: 'Index' object has no attribute 'invlists'"

**Comment by winself** [comment]
@beauby 
when i call index.index.invlists
 I meet "AttributeError: 'Index' object has no attribute 'invlists'"
thanks

**Comment by beauby** [comment]
`faiss.downcast_Index(index.index).invlists`

**Comment by winself** [comment]
@beauby 
sorry, 
when i call faiss.downcast_Index(index.index).invlists
I meet 
AttributeError: module 'faiss' has no attribute 'downcast_Index'

:(

**Comment by winself** [comment]
@beauby 
sorry,
when i call faiss.downcast_Index(index.index).invlists
I meet
AttributeError: module 'faiss' has no attribute 'downcast_Index'
Thanks very much 
:(

**Comment by winself** [comment]
@beauby 
as you say , I use the faiss.downcast_Index(index.index).invlists . it works 
but i meet another problem .
**RuntimeError: Error in size_t faiss::OnDiskInvertedLists::merge_from(const faiss::InvertedLists**, int, bool) at OnDiskInvertedLists.cpp:602: Error: 'il->nlist == nlist && il->code_size == code_size' failed**

i try print nlist  of  the train.index and block_x.index .they are same. 

can you give some sugestion ? 

 my code  ( just changed the "IVF4096,Flat" to 'OPQ20_80,IMI2x12,PQ20') 

`ivfs = []
for bno in range(2):
    # the IO_FLAG_MMAP is to avoid actually loading the data thus
    # the total size of the inverted lists can exceed the
    # available RAM
    print("read " + indexdir + "block_%d.index" % bno)
    index = faiss.read_index(indexdir + "block_%d.index" % bno,
                             faiss.IO_FLAG_MMAP)
    ivfs.append(faiss.downcast_index(index.index).invlists)

    # avoid that the invlists get deallocated with the index
    index.own_invlists = False

# construct the output index
index = faiss.read_index("./data/trained.index")

# prepare the output inverted lists. They will be written
# to merged_index.ivfdata


invlists = faiss.OnDiskInvertedLists(
    faiss.downcast_index(index.index).nlist, faiss.downcast_index(index.index).code_size,
    indexdir + "merged_index.ivfdata")

# merge all the inverted lists
ivf_vector = faiss.InvertedListsPtrVector()

for ivf in ivfs:
    ivf_vector.push_back(ivf)


print("merge %d inverted lists " % ivf_vector.size())
ntotal = invlists.merge_from(ivf_vector.data(), ivf_vector.size())

index.ntotal = ntotal
faiss.downcast_index(index.index).replace_invlists(invlists)

print("write " + indexdir + "all.index")
faiss.write_index(index, indexdir + "all.index")`
