### ISSUE TITLE
low search speed for IVFPQ with polysemous training

### ISSUE THREAD

**Issue by yingjianling** [facebookresearch/faiss#887]
# Summary
I compare the query speed of ivfpq with and without polysemous training on 5000 query samples and 105000 base samples. The results show that the ivfpq with polysemous training costs almost 2 times query time compared with the one withoutpolysemous training (29.94s vs 14.75s).
```
nlist = 2592;
m = 64;
faiss::IndexFlatL2 quantizer = new faiss::IndexFlatL2(d);
faiss::Index* index = new faiss::IndexIVFPQ(quantizers, d, nlist, m, 8);
((faiss::IndexIVFPQ*)(index))->nprobe = 2048;
((faiss::IndexIVFPQ*)(index))->do_polysemous_training = true; 
...
index->train(n, xb);
index->add(n,xb); 
...
((faiss::IndexIVFPQ*)index)->polysemous_ht = 220; 
index->search(n, xq, k, Di, Ii);
```
I add and search samples with batch size of 512.
# Platform

OS: Ubuntu 14.04.6 LTS

Faiss version: 656368b

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [x] C++
- [ ] Python

# Reproduction instructions

**Comment by wickedfoo** [comment]
Why are you using nprobe = 2048 which is a significant fraction of the total number of lists (2592)? A brute-force index would be faster in this case.

The typical use case of the approximate index is where nprobe << nlist.

**Comment by yingjianling** [comment]
setting nprobe = 512  256 128 gives similar results. 
nprobe                       512     256     128     
with polysemous       8.61s   5.89s   2.64s
without                      3.82s   2.05s   1.20s

here is the result of using 1million base samples and 5000 query samples.
nlist = 8020
nprobe                      512      256      128
with polysemous      9.01s    5.25s    3.22s
without                     5.01s    2.91s    1.72s

**Comment by yingjianling** [comment]
I think I have solved the problem. thank your reply

**Comment by beviah** [comment]
@yingjianling how did you solve the problem?
