### ISSUE TITLE
while executing i got the error        AttributeError: module 'faiss' has no attribute 'StandardGpuResources         can anyone helpme me 

### ISSUE THREAD

**Issue by sree5472** [facebookresearch/faiss#888]
# Summary

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [ ] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [ ] Python

# Reproduction instructions

**Comment by mdouze** [comment]
It means you are using the cpu-only Faiss.

**Comment by sree5472** [comment]
how install gpu based Faiss using pip

**Comment by Silent-Zebra** [comment]
I'm not sure about pip, but according to the install instructions [here](https://github.com/facebookresearch/faiss/blob/master/INSTALL.md) the recommended method is to install using Anaconda. I had some issues earlier, but setting up a new Anaconda virtual environment, running conda install faiss-cpu -c pytorch, then running conda install faiss-gpu cudatoolkit=10.0 -c pytorch worked for me

**Comment by beauby** [comment]
@sree5472 As @Silent-Zebra mentioned, the supported way of installing Faiss is through conda, and we do not support pip at the moment.

**Comment by zapaishchykova** [comment]
I also encountered this problem while was trying to use the faiss with virtual env through conda. The problem was that virtual enviroment was using python 3.5, while faiss was installed from a console for python 2.7, re-creating the evn with python 2.7 helped to solve the issue.
