### ISSUE TITLE
installation issues 

### ISSUE THREAD

**Issue by Ravikiran2611** [facebookresearch/faiss#889]
i have installed faiss using 
conda install faiss-cpu -c pytorch
 
but if i import faiss in any of my python file like
q =faiss.IndexFlatL2(dimension)
i get an error saying
AttributeError: module 'faiss' has no attribute 'IndexFlatL2'

i complied using command 
python filename.py

can anyone pls help me 
is there anything else need to be installed apart from the  command in the second line
bit urgent
thanks in advance !!!!!!!

**Comment by beauby** [comment]
Please paste your code.

**Comment by Ravikiran2611** [comment]
@beauby  thanks for your reply
got my error corrected 
thank you so much

**Comment by captify-dieter** [comment]
Can you please share how this was solved?

**Comment by dterg** [comment]
Can you please share this was solved?

**Comment by coderqiuqiu** [comment]
Can you please share how this was solved? Thanks!!

**Comment by yydai** [comment]
@Ravikiran2611 I get the same error message. Can you tell me how to solve the problem?
