### ISSUE TITLE
Building with Anaconda

### ISSUE THREAD

**Issue by zzzrpagliari** [facebookresearch/faiss#89]
I keep getting

`..pmypath/anaconda2/bin/../lib/libgomp.so.1: version GOMP_4.0 not found (required by ./_swigfaiss.so)`

I can see `libgomp1` under both anaconda and my `/lib` folder. Any idea about how to fix it?

**Comment by mdouze** [comment]
Hi 

Please make sure you are using the exact same compiler and libs that were used to compile anaconda.

**Comment by Horacehxw** [comment]
Hi, I have encountered the same issure, Can you clarify how to fix that?
