### ISSUE TITLE
display a vector at an index

### ISSUE THREAD

**Issue by Ravikiran2611** [facebookresearch/faiss#892]
i have index of type Index faiss.IndexIVFFlat
i need to retrieve or display a vector at a particular index
i am working on cpu
can anyone help me in this issue
thanks in advance

**Comment by beauby** [comment]
You can call `index.reconstruct(id)`.

**Comment by Ravikiran2611** [comment]
thanks you so much @beauby

**Comment by yuyifan1991** [comment]
> You can call `index.reconstruct(id)`.

Hi, when I use the _index.reconstruct(id)_ , error is: _RuntimeError: Error in virtual void faiss::IndexIVF::reconstruct(faiss::Index::idx_t, float*) const at IndexIVF.cpp:191: Error: 'direct_map.size() == ntotal' failed: direct map is not initialized_  
When I use the _index.make_direct_map()_ , error is : _RuntimeError: Error in void faiss::IndexIVF::make_direct_map(bool) at IndexIVF.cpp:159: Error: '0 <= idlist [ofs] && idlist[ofs] < ntotal' failed: direct map supported only for seuquential ids_
I have the hash ids for the index.
