### ISSUE TITLE
when will GpuIndexIVFPQ support METRIC_INNER_PRODUCT? It's been two years...

### ISSUE THREAD

**Issue by naah69** [facebookresearch/faiss#895]
# Summary

i have 1.7+  million datas on faiss. 
and i make the faiss be a distributed micro service. 
so the 1.7+ million datas will be shard to 9 indexs that stores 200 thousand datas.
each slice just is 40M ever when i use `GpuIndexIVFPQ` .but each slice will be 400M if i use `GpuIndexIVFFlat`

please make `GpuIndexIVFPQ` support `METRIC_INNER_PRODUCT` as soon as.
i watch the code page [faiss/gpu/GpuIndexIVFPQ.cu](https://github.com/facebookresearch/faiss/blob/master/gpu/GpuIndexIVFPQ.cu),the developmental requirement was created before 2 years ago.

i also watch the issue #132 . but my datas are not  normalized. 
**please make GpuIndexIVFPQ support METRIC_INNER_PRODUCT as soon as.**

# Platform

OS: CentOS7-CUDA

Faiss version: 1.5.1

Faiss compilation options: 

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [x] C++
- [x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
inner prod is supported on the CPU side. For GPU there is a fixme about this
https://github.com/facebookresearch/faiss/blob/master/gpu/GpuIndexIVFPQ.cu#L66
I'll mark it as enhancement. We have to discuss if this is high-priority.

**Comment by justinchiu** [comment]
Would this be difficult to implement, and is the GPU implementation coupled tightly to L2?

**Comment by wickedfoo** [comment]
This is now implemented in the Facebook version, will be available in GitHub the next time we push a version.

**Comment by wickedfoo** [comment]
Fixed in latest github version.
