### ISSUE TITLE
Failure in the Python wrapper: ImportError

### ISSUE THREAD

**Issue by zoe-cheung** [facebookresearch/faiss#90]
I ran "make py" and got error in both python -c "import faiss" and python -c "import faiss, numpy
faiss.Kmeans(10, 20).train(numpy.random.rand(1000, 20).astype('float32'))"

There seem to be undefined in file libstdc__.so.6 for ./_swigfaiss.so

Here is the error: 
queen:/data/faiss-master # python -c "import faiss, numpy
> faiss.Kmeans(10, 20).train(numpy.random.rand(1000, 10).astype('float32'))"
Failed to load GPU Faiss: No module named swigfaiss_gpu
Faiss falling back to CPU-only.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "faiss.py", line 28, in <module>
    from swigfaiss import *
  File "swigfaiss.py", line 17, in <module>
    _swigfaiss = swig_import_helper()
  File "swigfaiss.py", line 16, in swig_import_helper
    return importlib.import_module('_swigfaiss')
  File "/home/beehive/toolchain/x86_64-unknown-linux-gnu/python-2.7.3/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: ./_swigfaiss.so: symbol _ZNSo9_M_insertImEERSoT_, version GLIBCXX_3.4.9 not defined in file libstdc++.so.6 with link time reference

In my SLES environment, I found several version of libstdc++.so.6
queen:/ # find ./ | grep libstdc++.so.6
./home/beehive/toolchain/x86_64-unknown-linux-gnu/gcc-4.1.2/lib64/libstdc++.so.6.0.8
./home/beehive/toolchain/x86_64-unknown-linux-gnu/gcc-4.1.2/lib64/libstdc++.so.6
./home/beehive/toolchain/x86_64-unknown-linux-gnu/6.20/lib/libstdc++.so.6.0.8
./home/beehive/toolchain/x86_64-unknown-linux-gnu/6.20/lib/libstdc++.so.6
./home/beehive/toolchain/x86_64-unknown-linux-gnu/3.0/lib/libstdc++.so.6.0.8
./home/beehive/toolchain/x86_64-unknown-linux-gnu/3.0/lib/libstdc++.so.6
./usr/lib64/libstdc++.so.6.0.16
./usr/lib64/libstdc++.so.6
./usr/lib/libstdc++.so.6.0.16
./usr/lib/vmware-tools/lib64/libstdc++.so.6
./usr/lib/vmware-tools/lib64/libstdc++.so.6/libstdc++.so.6
./usr/lib/vmware-tools/lib32/libstdc++.so.6
./usr/lib/vmware-tools/lib32/libstdc++.so.6/libstdc++.so.6
./usr/lib/libstdc++.so.6

I also ran  ldd -r _swigfaiss.so
queen:/data/faiss-master # ldd -r _swigfaiss.so
        linux-vdso.so.1 =>  (0x00007fff5abff000)
        libmkl_intel_ilp64.so => /opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_intel_ilp64.so (0x00007f71f5489000)
        libmkl_core.so => /opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_core.so (0x00007f71f3995000)
        libmkl_gnu_thread.so => /opt/intel/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_gnu_thread.so (0x00007f71f2774000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f71f2543000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f71f2325000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f71f201b000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f71f1da2000)
        libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x00007f71f1b93000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f71f197d000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f71f1609000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f71f6178000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f71f13ff000)
\undefined symbol: PyObject_GenericGetAttr      (./_swigfaiss.so)
undefined symbol: PyExc_ValueError      (./_swigfaiss.so)
undefined symbol: PyExc_NotImplementedError     (./_swigfaiss.so)
undefined symbol: PyExc_OverflowError   (./_swigfaiss.so)
undefined symbol: PyClass_Type  (./_swigfaiss.so)
undefined symbol: PyExc_RuntimeError    (./_swigfaiss.so)
undefined symbol: PyExc_MemoryError     (./_swigfaiss.so)
undefined symbol: PyExc_IOError (./_swigfaiss.so)
undefined symbol: _PyWeakref_CallableProxyType  (./_swigfaiss.so)
undefined symbol: PyInstance_Type       (./_swigfaiss.so)
undefined symbol: _Py_NoneStruct        (./_swigfaiss.so)
undefined symbol: _Py_NotImplementedStruct      (./_swigfaiss.so)
undefined symbol: PyExc_TypeError       (./_swigfaiss.so)

Currently, my path is pointing to set /opt/intel/compilers_and_libraries/linux/mkl/lib/intel64:/usr/lib64
I tried to add different directory in the path, however I continue to get ImportError: ./_swigfaiss.so: symbol _ZNSo9_M_insertImEERSoT_, version GLIBCXX_3.4.9 not defined in file libstdc++.so.6 with link time reference.

How do I fix this error?

**Comment by mdouze** [comment]
Hi 

This does not look like a Faiss-specific error. Please make sure you are using the same libstdc++ as the one the c++ compiler is using (eg. via LD_LIBRARY_PATH). Also, if python uses several C++ librairies, it is probably a good idea to compile them with the same compiler.

**Comment by jegou** [comment]
No further comment on this cant-repro issue. 
Closing.

**Comment by hande6688** [comment]
@mdouze 
my operation command is as follows:
conda create -n retrieval python=3.6
conda install -c pytorch faiss-gpu cudatoolkit=10.1
pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
pip install -r requirements.txt

The installation faiss reported the following error, what's the matter：
ImportError: /home/vi/miniconda3/envs/retrieval/lib/python3.6/site-packages/faiss/../../.././libmkl_gnu_thread.so: undefined symbol: mkl_graph_mxm_gus_phase2_plus_second_fp32_def_i64_i32_fp32


Very anxious！
