### ISSUE TITLE
如何将自己的服务器上的图片(大约8亿张)训练成一个faiss可进行内部搜索的数据集？

### ISSUE THREAD

**Issue by codeLiFan** [facebookresearch/faiss#901]
尊敬的faiss开发者：
         我的服务器上大约有8亿张图片，使用keras的inceptionv3模型提取图片特征（最后一层向量），生成了自己的数据集，如：xx.h5，如和在faiss中使用？xx.h5作为基础数据进行搜索呢？

**Comment by mdouze** [comment]
Please write the issue in English.
