### ISSUE TITLE
Will IndexIVFFlat's reconstruct return the same vector as being indexed?

### ISSUE THREAD

**Issue by XinliYu** [facebookresearch/faiss#903]
I indexed two sets of embeddings separately using IndexIVFFlat, and the use the `reconstruct` method to retrieve the embeddings. 

To my surprise, one of them returns the same embeddings as those indexed, but the other returns different embeddings with quite large distance to the original embeddings (15000 vectors, sum of Euclidean distance 900+). Is this normal?

**Comment by XinliYu** [comment]
Confirmed it should return the same embeddings as those being indexed; any difference is wrong and we should check for bugs.

**Comment by yuyifan1991** [comment]
> I indexed two sets of embeddings separately using IndexIVFFlat, and the use the `reconstruct` method to retrieve the embeddings.
> 
> To my surprise, one of them returns the same embeddings as those indexed, but the other returns different embeddings with quite large distance to the original embeddings (15000 vectors, sum of Euclidean distance 900+). Is this normal?

Do you have the seuquential ids? I cannot reconstruct vectors and I using IndexIVFFlat to create the index? Could you tell me how to reconstruct? If I use _index.make_direct_map()_, error is: _RuntimeError: Error in void faiss::IndexIVF::make_direct_map(bool) at IndexIVF.cpp:159: Error: '0 <= idlist [ofs] && idlist[ofs] < ntotal' failed: direct map supported only for seuquential ids_
