### ISSUE TITLE
torch.cuda() hangs after import faiss

### ISSUE THREAD

**Issue by yanxi0830** [facebookresearch/faiss#908]
# Summary
Pushing tensors to the gpu hangs after `import faiss` is called

# Platform

OS: Ubuntu 16.04.6

Faiss version: faiss-gpu-1.5.3-py37h1a5d453_0

Faiss compilation options: installed with conda

Running on:
- GPU

Interface: 
- Python

# Reproduction instructions

```
conda create -n cuda-stuck
conda activate cuda-stuck
conda install pytorch torchvision faiss-gpu cudatoolkit=10.0 -c pytorch
```
If I run the following, then cuda hangs indefinitely, however, this does not happen if `import faiss` is not used.
```
import torch
import torchvision
import faiss
a = torch.zeros(10)
a.cuda()
```
python -m trace shows that the code seems to be stuck at https://github.com/pytorch/pytorch/blob/master/torch/cuda/__init__.py#L187
```
__init__.py(360):         return torch._C._cuda_getDeviceCount()
__init__.py(319):     return _get_device_properties(device)
__init__.py(131):         if capability == (3, 0) or major < 3:
__init__.py(133):         elif CUDA_VERSION <= 9000 and major >= 7 and minor >= 5:
__init__.py(126):     for d in range(device_count()):
__init__.py(187):     for queued_call, orig_traceback in _queued_calls:
```

**Comment by physicsrob** [comment]
I'm encountering this same symptom.  If I `import faiss` then calling `cuda()` on a tensor hangs.  Do you happen to remember the resolution to your issue @yanxi0830 ?
