### ISSUE TITLE
Cannot install 1.5.3

### ISSUE THREAD

**Issue by pandasMX** [facebookresearch/faiss#912]
# Summary

# Platform

OS:  ubuntu 16.04

Faiss version: 

Faiss compilation options:  use conda install

Running on:
-  CPU

Interface: 
-  Python

# Reproduction instructions

I installed 1.5.3 but the python import faiss shows 1.5.2

`conda install faiss-cpu==1.5.3 -c pytorch`
`python`
`import faiss`
`faiss.__version__`
`#1.5.2`

**Comment by mdouze** [comment]
This should be fixed now.
