### ISSUE TITLE
Question: Writing Index to File - Python 

### ISSUE THREAD

**Issue by angel-pan** [facebookresearch/faiss#914]
# Summary
Hi, I was just wondering if it there was a way to write index to file using other methods other than by filename. I noticed that there are 3 overloaded methods for `faiss::write_index` in C++. Is there something similar with python? Using `open(filename, 'w+b')` doesn't seem to substitute for FILE and I can't seem to use `faiss.IOWriter` in any useful way.

# Platform

OS: macOS 10.14.6 

Faiss version: 1.5.2 

Running on:
- [x] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

**Comment by mdouze** [comment]
Do you want to write an index to a python file object? 
If yes, it would require to change the SWIG interface a bit. 
As a workaround, if the index is not too big, you can write it to a string and store the string in the file, see [index_to_array.py](https://gist.github.com/mdouze/e30e8f57a98ed841c082cc68baa14b4a).

**Comment by angel-pan** [comment]
Ideally, I do want to write the index as a file object. I will look into the string option but as indices may contain over a million vectors, it may be too large. The reason is that I am trying to save the index to a file object is because I am trying to save the index through a flask app and flask seems to have some strange behavior when writing by filename.

**Comment by angel-pan** [comment]
I solved my problem. There was an unrelated bug in my code that was causing some unexpected results. I am going to close this issue, even though I still haven't figured out how to write index to python file object.

**Comment by gustavz** [comment]
@angel-pan how did you manage to save the index to a file object?
@mdouze was there any work to support it since this isue?
Using pickle seems to work:

```python
import faiss
import pickle
import numpy as np
from io import BytesIO

embeddings = [[1],[2],[3]]
vector = np.array(embeddings, dtype=np.float32)
d = vector.shape[1]
index = faiss.IndexFlatL2(d)
index.add(vector)

with BytesIO() as buffer:
    pickle.dump(index, buffer)
    buffer.seek(0)
    index2 = pickle.load(buffer)

vector = np.array([[4]], dtype=np.float32)
r1 = index.search(vector, k=1)
r2 = index2.search(vector, k=1)
r1 == r2
```
