### ISSUE TITLE
Very high matrice dimentionality makes crash the machine when indexing

### ISSUE THREAD

**Issue by jplu** [facebookresearch/faiss#916]
# Platform

OS: Linux Ubuntu 19.04
Config machine:
- 8 GPU V100
- CPU 96 cores
- 614 Go RAM

Faiss version: 1.5.3 (commit 656368b5eda4d376177a3355673d217fa95000b6)
Faiss compilation options: `./configure --with-cuda=/usr/local/cuda-10.0 --prefix=/opt/faiss --with-python=/usr/lib/python3.7/` with MKL version 2019.2.187-1

Running on:
- [ ] CPU
- [x] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

Here the minimal piece of code to reproduce the issue:

```
import numpy as np
import faiss
import time
k = 10
d = 1536
nb = 30000000
nq = 1
np.random.seed(1234) 
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

index = faiss.IndexFlatL2(d)
co = faiss.GpuMultipleClonerOptions()
co.shard = True
co.useFloat16 = True
index = faiss.index_cpu_to_all_gpus(index, co, ngpu=4)
index.add(xb) ##### WHERE IT CRASHS
start_time = time.process_time()
D, I = index.search(xq, k)
print(time.process_time() - start_time, " seconds")
print(I)
```

When running this piece of code the line ```index.add()``` makes crash the machine without any error message, the machine just hangs and then restarts.

**Comment by mdouze** [comment]
Right, it is a bit harsh that it does not report a usable error message. However, you are trying to add 11G of data at once. Could you try to add the data by slices of 1M elements?

**Comment by jplu** [comment]
Cool! Thanks a lot!!! Adding by slice of 1M works perfectly.
