### ISSUE TITLE
On disk searching seems to use more memory than it should

### ISSUE THREAD

**Issue by triclops200** [facebookresearch/faiss#926]
# Summary

The on-disk demo does not seem to actually be on disk. When I run stage 6, it's taking up about 550M of memory, which is roughly the same as just storing the vectors directly in memory.

# Platform

OS: Linux
Faiss version: 656368b5eda4d376177a3355673d217fa95000b6
Faiss compilation options: no-cuda
Running on CPU

Interface: Python

# Reproduction instructions
Run the ondisk demo stage 6

**Comment by mdouze** [comment]
Is this RSS memory or VSZ memory (see the top command)?

**Comment by mdouze** [comment]
The data is on disk. What you are seeing is probably just overhead, multiplying the dataset size by 10 or 100 should clarify that.

**Comment by triclops200** [comment]
Well, I did some more testing with another program, and, if the index is being opened with a mmap with MAP_SHARED enabled, I'm willing to close this ticket as the RES being reported is kind-of wrong due to how linux reports mem-mapped files.

**Comment by mdouze** [comment]
Usually the reported amount of resident mem is reasonable on Linux. 
I guess the real check is to mmap an index that does not fit in RAM.

**Comment by triclops200** [comment]
First off, results:
  larger than memory did search correctly, so it's not a bug and I can close the issue.

Secondly, explaination:
  Linux reports mmapped in memory pages as RES for the program, but it does not count as allocated memory at the system level. So, instead of OOMing, it will start depaging some of the file and keep the RES constant. The system reports a large cache size, though, but this isn't a problem for most usages. What this does mean is that you'll start hitting a performance cliff when the index can't fit in memory, but that's to be expected.
