### ISSUE TITLE
An error occured while starting kernel - Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by siva2k16** [facebookresearch/faiss#928]
# Summary - Installed CPU version. After installtion there is issue. Used Conda command - conda install -c pytorch faiss-cpu

# Platform
After CPU install, Import faiss leads to Error while starting kernel
Used Conda command - conda install -c pytorch faiss-cpu

OS: Ubuntu 18.04.2 LTS

Faiss version: faiss-cpu-1.5.3-py37h6bb024c_0 

Faiss compilation options: 

Running on:
- [ ] CPU

Interface: 
- [ ] Python - 3.7.1

ubuntu 18.04.2 LTS

# Reproduction instructions
import sys
sys.path.append(r'~/anaconda3/pkgs/faiss-cpu-1.5.3-py37h6bb024c_0/lib/python3.7/site-packages/faiss/')
import faiss
import numpy as np
index = faiss.IndexFlatL2(64)
print(index.is_trained)

An error ocurred while starting the kernel b''

#Tried to add sys.path.append to include package path for faiss. Didn't help.

In Anaconda command prompt - python -c "import faiss"
Returns - Illegal instruction (core dumped)

**Comment by mdouze** [comment]
seems to be a dup of #885
