### ISSUE TITLE
Question about "average query expansion"

### ISSUE THREAD

**Issue by batrlatom** [facebookresearch/faiss#929]
Hi, I have a question about technique used in search engines - query expansion. I have found a code in pure python and then naive faiss implementation. But the implementation is rather slow ( 50k 128d vectors takes about 1 second to process with gtx1080ti, 10 seconds on cpu ) for real time search. Do you have some prebuilt functions doing the same postprocessing? Or do you see how can I speed up the process?

The usecase is very similar to your wiki page : https://github.com/facebookresearch/faiss/wiki/Indexing-1M-vectors but with added postprocessing in the form of query expansion

Pure PYTHON:
```
def average_query_expansion(query_vecs, reference_vecs, top_k=5):
    """
    Average Query Expansion (AQE)
    Ondrej Chum, et al. "Total Recall: Automatic Query Expansion with a Generative Feature Model for Object Retrieval,"
    International Conference of Computer Vision. 2007.
    https://www.robots.ox.ac.uk/~vgg/publications/papers/chum07b.pdf
    """
    # Query augmentation
    sim_mat = calculate_sim_matrix(query_vecs, reference_vecs)
    indices = np.argsort(-sim_mat, axis=1)

    top_k_ref_mean = np.mean(reference_vecs[indices[:, :top_k], :], axis=1)
    query_vecs = np.concatenate([query_vecs, top_k_ref_mean], axis=1)

    # Reference augmentation
    sim_mat = calculate_sim_matrix(reference_vecs, reference_vecs)
    indices = np.argsort(-sim_mat, axis=1)

    top_k_ref_mean = np.mean(reference_vecs[indices[:, 1:top_k+1], :], axis=1)
    reference_vecs = np.concatenate([reference_vecs, top_k_ref_mean], axis=1)

    return query_vecs, reference_vecs
```

PYTHON FAISS code
```
def average_query_expansion(query_vecs, reference_vecs, resources, top_k=5):
    """
    Average Query Expansion (AQE)
    Ondrej Chum, et al. "Total Recall: Automatic Query Expansion with a Generative Feature Model for Object Retrieval,"
    International Conference of Computer Vision. 2007.
    https://www.robots.ox.ac.uk/~vgg/publications/papers/chum07b.pdf
    https://github.com/leeesangwon/PyTorch-Image-Retrieval/blob/public/inference.py
    """

    query_vecs = query_vecs.astype(np.float32)
    reference_vecs = reference_vecs.astype(np.float32)

    # Query augmentation
    query_aug = faiss.IndexFlatIP(reference_vecs.shape[1])
    query_aug = faiss.index_cpu_to_all_gpus(query_aug)
    query_aug.add(reference_vecs)
    distances, indexes = query_aug.search(x=query_vecs, k=top_k)
    query_aug.reset()

    top_k_ref_mean = np.mean(reference_vecs[indexes], axis=1, dtype=np.float32)
    query_vecs = np.concatenate([query_vecs, top_k_ref_mean], axis=1)

    # Reference augmentation
    ref_aug = faiss.IndexFlatIP(reference_vecs.shape[1])
    ref_aug = faiss.index_cpu_to_all_gpus(ref_aug)
    ref_aug.add(reference_vecs)
    distances, indexes = ref_aug.search(x=reference_vecs, k=top_k + 1)
    ref_aug.reset()

    top_k_ref_mean = np.mean(reference_vecs[indexes], axis=1, dtype=np.float32)
    reference_vecs = np.concatenate([reference_vecs, top_k_ref_mean], axis=1)

    return query_vecs, reference_vecs
```

**Comment by mdouze** [comment]
IIUC, the `query_vecs` contains a single query. Then it is unlikely that the overhead of building the index and moving it to GPU can be amortized compared to the pure search time.

**Comment by batrlatom** [comment]
I see, thanks for the remarks.  I appreciate it

**Comment by mylyu** [comment]
> Hi, I have a question about technique used in search engines - query expansion. I have found a code in pure python and then naive faiss implementation. But the implementation is rather slow ( 50k 128d vectors takes about 1 second to process with gtx1080ti, 10 seconds on cpu ) for real time search. Do you have some prebuilt functions doing the same postprocessing? Or do you see how can I speed up the process?
> 
> The usecase is very similar to your wiki page : https://github.com/facebookresearch/faiss/wiki/Indexing-1M-vectors but with added postprocessing in the form of query expansion
> 
> Pure PYTHON:
> 
> ```
> def average_query_expansion(query_vecs, reference_vecs, top_k=5):
>     """
>     Average Query Expansion (AQE)
>     Ondrej Chum, et al. "Total Recall: Automatic Query Expansion with a Generative Feature Model for Object Retrieval,"
>     International Conference of Computer Vision. 2007.
>     https://www.robots.ox.ac.uk/~vgg/publications/papers/chum07b.pdf
>     """
>     # Query augmentation
>     sim_mat = calculate_sim_matrix(query_vecs, reference_vecs)
>     indices = np.argsort(-sim_mat, axis=1)
> 
>     top_k_ref_mean = np.mean(reference_vecs[indices[:, :top_k], :], axis=1)
>     query_vecs = np.concatenate([query_vecs, top_k_ref_mean], axis=1)
> 
>     # Reference augmentation
>     sim_mat = calculate_sim_matrix(reference_vecs, reference_vecs)
>     indices = np.argsort(-sim_mat, axis=1)
> 
>     top_k_ref_mean = np.mean(reference_vecs[indices[:, 1:top_k+1], :], axis=1)
>     reference_vecs = np.concatenate([reference_vecs, top_k_ref_mean], axis=1)
> 
>     return query_vecs, reference_vecs
> ```
> 
> PYTHON FAISS code
> 
> ```
> def average_query_expansion(query_vecs, reference_vecs, resources, top_k=5):
>     """
>     Average Query Expansion (AQE)
>     Ondrej Chum, et al. "Total Recall: Automatic Query Expansion with a Generative Feature Model for Object Retrieval,"
>     International Conference of Computer Vision. 2007.
>     https://www.robots.ox.ac.uk/~vgg/publications/papers/chum07b.pdf
>     https://github.com/leeesangwon/PyTorch-Image-Retrieval/blob/public/inference.py
>     """
> 
>     query_vecs = query_vecs.astype(np.float32)
>     reference_vecs = reference_vecs.astype(np.float32)
> 
>     # Query augmentation
>     query_aug = faiss.IndexFlatIP(reference_vecs.shape[1])
>     query_aug = faiss.index_cpu_to_all_gpus(query_aug)
>     query_aug.add(reference_vecs)
>     distances, indexes = query_aug.search(x=query_vecs, k=top_k)
>     query_aug.reset()
> 
>     top_k_ref_mean = np.mean(reference_vecs[indexes], axis=1, dtype=np.float32)
>     query_vecs = np.concatenate([query_vecs, top_k_ref_mean], axis=1)
> 
>     # Reference augmentation
>     ref_aug = faiss.IndexFlatIP(reference_vecs.shape[1])
>     ref_aug = faiss.index_cpu_to_all_gpus(ref_aug)
>     ref_aug.add(reference_vecs)
>     distances, indexes = ref_aug.search(x=reference_vecs, k=top_k + 1)
>     ref_aug.reset()
> 
>     top_k_ref_mean = np.mean(reference_vecs[indexes], axis=1, dtype=np.float32)
>     reference_vecs = np.concatenate([reference_vecs, top_k_ref_mean], axis=1)
> 
>     return query_vecs, reference_vecs
> ```

is this query expansion or actually database augmentation?
