### ISSUE TITLE
problem: index.reset() 

### ISSUE THREAD

**Issue by thbqlf** [facebookresearch/faiss#93]
execute index.reset()   why ids not remove？

code：

- import faiss                   # make faiss available
- index = faiss.IndexFlatL2(d)   # build the index
- id_map = faiss.IndexIDMap(index)
- print id_map.is_trained
- id_map.reset()
- id_map.add_with_ids(xb[:1],ids[:1])
- id_map.reset()
- id_map.remove_ids(ids)
- ids[:1]=9999999
- print ids[:1]
- id_map.add_with_ids(xb[:1],ids[:1])

when  execute id_map.remove_ids(ids) has Anomalies：

Failed to load GPU Faiss: No module named swigfaiss_gpu
Faiss falling back to CPU-only.
Traceback (most recent call last):
File "/data/pycharm-2016.3.2/helpers/pydev/pydevd.py", line 1596, in <module>
globals = debugger.run(setup['file'], None, None, is_module)
File "/data/pycharm-2016.3.2/helpers/pydev/pydevd.py", line 974, in run
pydev_imports.execfile(file, globals, locals)  # execute the script
File "/home/allen/PycharmProjects/faissTest/faissTest.py", line 28, in <module>
id_map.remove_ids(ids)
File "/opt/faiss/faiss/swigfaiss.py", line 763, in remove_ids
def remove_ids(self, *args): return _swigfaiss.Index_remove_ids(self, *args)
TypeError: in method 'Index_remove_ids', argument 2 of type 'faiss::IDSelector const &'

**Comment by tboggs** [comment]
I have the same issue when attempting to remove id's from an `IndexIVFFlat`:
```
>>> index.remove_ids([2]) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "swigfaiss_gpu.py", line 1764, in remove_ids
    def remove_ids(self, *args): return _swigfaiss_gpu.IndexIVFFlat_remove_ids(self, *args)
TypeError: in method 'IndexIVFFlat_remove_ids', argument 2 of type 'faiss::IDSelector const &'
```
Are we supposed to explicitly create an instance of an `IDSelector` subclass to pass to the `remove_ids` method?

**Comment by mdouze** [comment]
Hi

`remove_ids` is not implemented for `IndexFlat` or `IndexIDMap`. 

For `IndexIVFFlat`, you have to pass it an `IDSelector`. The following should work:

```python
idsel = IDSelectorBatch(ids.size, faiss.swig_ptr(ids))
index.remove_ids(idsel)
```

I will make this smoother in the next iteration of Faiss.

**Comment by thbqlf** [comment]
code:
import numpy as np
d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

ids=(np.random.random(nb)*1000000000000).astype(int)
# ids=[]
for i in range(0,100000):
      ids[i]=1000000

ids=np.array(ids,dtype=np.int64)



import faiss                   # make faiss available
from faiss import IDSelectorBatch
index = faiss.IndexFlatL2(d)   # build the index
id_map = faiss.IndexIDMap(index)
print id_map.is_trained
#id_map.reset()
id_map.add_with_ids(xb[:1],ids[:1])
#id_map.reset()
print ids[:1]
bb=IDSelectorBatch(ids[:1].size,faiss.swig_ptr(ids[:1]))
id_map.remove_ids(bb)
ids[:1]=9999999
print ids[:1]
id_map.add_with_ids(xb[:1],ids[:1])

#id_map.reset()
# id_map.add_with_ids(xb,ids)
# id_map.reset()

print id_map.ntotal

k = 2                          # we want to see 4 nearest neighbors
print  xb[:1]
D, I = id_map.search(xb[:1], k) # sanity check
print I
print D

print "========================================="

print xq
D, I = id_map.search(xq[:1], k)     # actual search
print I[:5]                    # neighbors of the 5 first queries
print I[-5:]                   # neighbors of the 5 last queriess
print I[:1][0][0]
error:
Faiss assertion !"remove_ids not implemented for this type of index" failed in virtual long int faiss::Index::remove_ids(const faiss::IDSelector&) at Index.cpp:40True
Do you have the full demo？

**Comment by mdouze** [comment]
See comment above: remove_ids is not implemented for IndexFlat or IndexIDMap.

**Comment by mdouze** [comment]
It is implemented now, so closing issue.
