### ISSUE TITLE
When I use GPU IVF Flat, nprobe can't exceed 1024

### ISSUE THREAD

**Issue by JinHai-CN** [facebookresearch/faiss#932]
Error issued:

void faiss::gpu::GpuIndexIVF::setNumProbes(int) at gpu/GpuIndexIVF.cu:198: Error: 'nprobe > 0 && nprobe <= getMaxKSelection()' failed: GPU index only supports nprobe <= 1024; passed 2048

Does it mean GPU index IVF can't support nprobe > 1024? Does CPU index IVF has the same limitation?

**Comment by mdouze** [comment]
GPU indexes are limited to some size (I thought it was 2048).
CPU Faiss does not have this limitation. However, keep in mind that performance for very large result lists degrades.

**Comment by wickedfoo** [comment]
It should support <= 2048 if you are compiling with CUDA 9.0 or later. You seem to be using an old version of the code, as the error is thrown at line 206 now.

https://github.com/facebookresearch/faiss/blob/master/gpu/GpuIndexIVF.cu#L206
