### ISSUE TITLE
Little Typo in wiki

### ISSUE THREAD

**Issue by seungwubaek** [facebookresearch/faiss#934]
Hello, I'm a frequent visitor in wiki.
I found typo like below.

First line at the link,
https://github.com/facebookresearch/faiss/wiki/Index-IO,-index-factory,-cloning-and-hyper-parameter-tuning#examples

From origin,
an index for 128D vectors that resduces them to 80D by PCA
maybe To,
an index for 128D vectors that __reduces__ them to 80D by PCA

Thank you!

**Comment by beauby** [comment]
Fixed, thanks!
