### ISSUE TITLE
problem: How to process large data.

### ISSUE THREAD

**Issue by hxtsch** [facebookresearch/faiss#94]
Load data code will be:
print "load data"
xt = fvecs_read("sift1M/sift_learn.fvecs")         (Question: if the size of sift1M/sift_learn.fvecs is 70G, how to deal with it?)
xb = fvecs_read("sift1M/sift_base.fvecs")
xq = fvecs_read("sift1M/sift_query.fvecs")

It is to say that all of the data must be read into RAM at first. But if the data is large ,such as: the train data is 70G. Usually, our RAM is not so  big. So, how to use faiss to solve the problem.
Is there any one  have encountered such a problem?

**Comment by wickedfoo** [comment]
Depending upon the index parameters, you probably only need a subset of the training, as there is usually only so much variation that the quantization can capture (and only so much variation in the dataset as well).

If you are using an index with a coarse quantizer, the clustering during training will only use up to 256 vectors per centroid by default, for instance. This is a configurable parameter.

For example, for a dataset of 1 billion 256-d vectors (size = 1 TB), you might choose 4 * sqrt(n) ~ 2^17 centroids, which means that for 256 centroids per input vector, you only need to provide 2^17 * 256 = 33.5 million vectors, or 34.3 GB of data, sampled randomly from the input dataset. You can choose and experiment similarly for your data.

**Comment by hxtsch** [comment]
Thank you for replying me so fast. But could you give me an example code for the large data (size >70G).
Thank you!
