### ISSUE TITLE
parameter of merge_into() function

### ISSUE THREAD

**Issue by hamhochoi** [facebookresearch/faiss#940]
I have read the issue about merge_from with pretransform and it leads to merge_into() solution. But there are 3 parameters which I don't know what to fill into.  

Can anybody have me to figure out what are there parameters?

_Originally posted by @hamhochoi in https://github.com/facebookresearch/faiss/issues/545#issuecomment-529140962_

**Comment by mdouze** [comment]
merge_into takes 2 indexes, merges the second one into the first, deallocates the second one. The boolean argument indicates whether the ids should be kept as is or if they are sequentially numbered.

https://github.com/facebookresearch/faiss/blob/master/IVFlib.h#L43

**Comment by hamhochoi** [comment]
I have build feature vectors and save to files. Then I loaded some of them to train with "PCA64,IVF262144_HNSW32,Flat". After that, I loaded the dataset and write_index(), but when I do merge indexes step, the program complain about merge_from():
 ```
    ntotal = invlists.merge_from(ivf_vector.data(), ivf_vector.size())
  File "/data/thanhdc/miniconda2/lib/python2.7/site-packages/faiss/swigfaiss.py", line 4415, in merge_from
    return _swigfaiss.OnDiskInvertedLists_merge_from(self, ils, n_il, verbose)
RuntimeError: Error in size_t faiss::OnDiskInvertedLists::merge_from(const faiss::InvertedLists**, int, bool) at OnDiskInvertedLists.cpp:602: Error: 'il->nlist == nlist && il->
code_size == code_size' faile
```
I came up with the link above, and try to use merge_into() function. But I still don't know how it works. 
Can you provide full script to merge all inverted list for "PCA64,IVF262144_HNSW32,Flat"?

**Comment by hamhochoi** [comment]
I have found another way to do what I want so I will close this issue here. Thank you so much @mdouze
