### ISSUE TITLE
How can we build index/search based on cosine similarity

### ISSUE THREAD

**Issue by cherryPotter** [facebookresearch/faiss#95]
> index = faiss.IndexFlatL2(d)
and
> index.add(xb)
> index = faiss.IndexIVFPQ(coarse_quantizer, d, nlist, m, faiss.METRIC_L2)

The above are all based on Euclid distance. How can I build index/search based on cosine similarity using faiss python package?

**Comment by bheinzerling** [comment]
`index = faiss.IndexFlatIP(d)`

IP stands for "inner product". If you have normalized vectors, the inner product becomes cosine similarity.

Here is an overview of the available indices:

https://github.com/facebookresearch/faiss/wiki/Faiss-indexes

**Comment by Berndinio** [comment]
This is searching for the cosine similarity! Not the cosine distance! Cosine distance is 1-<cosine similarity>.

**Comment by pranavnijampurkar33** [comment]
Just adding example if noob like me came here to find how to calculate the Cosine similarity from scratch

import faiss
dataSetI = [.1, .2, .3]
dataSetII = [.4, .5, .6]
#dataSetII = [.1, .2, .3]

x = np.array([dataSetI]).astype(np.float32)
q = np.array([dataSetII]).astype(np.float32)
index = faiss.index_factory(3, "Flat", faiss.METRIC_INNER_PRODUCT)
index.ntotal
faiss.normalize_L2(x)
index.add(x)
faiss.normalize_L2(q)
distance, index = index.search(q, 5)
print('Distance by FAISS:{}'.format(distance))

#To Tally the results check the cosine similarity of the following example

from scipy import spatial


result = 1 - spatial.distance.cosine(dataSetI, dataSetII)
print('Distance by FAISS:{}'.format(result))

**Comment by samuela** [comment]
Do any of the other indices support inner product based search? `IndexFlatIP` [appears to be the only one](https://github.com/facebookresearch/faiss/wiki/Faiss-indexes) and is just a brute-force implementation AFAIU.

**Comment by Sandy4321** [comment]
any solution pls

**Comment by jermwatt** [comment]
Are you looking for an index with an inner product metric and non-exhaustive search?

If yes - it looks like you can use the `index_factory` to create this sort of index.  The [index factory guide](https://github.com/facebookresearch/faiss/wiki/The-index-factory) gives the starter example below under the non-exhaustive section.


String | Quantizer class | Number of centroids | Comments
-- | -- | -- | --
IVF4096 | IndexFlatL2 or IndexFlatIP | 4096 | Constructs one of the IndexIVF variants, with a flat quantizer.

**Comment by ucas010** [comment]
have the same problem for 1B datasets 
and the vectors have been L2 norm 
could you pls help me ?
