### ISSUE TITLE
[Question]What's the difference between GpuIndex* and index_cpu_to_gpu?

### ISSUE THREAD

**Issue by JustinhoCHN** [facebookresearch/faiss#952]
I saw the ```index_cpu_to_gpu``` is usually used in running faiss on gpu in tutorial. Are these two both can make faiss running on gpu? Which one is preferable?

**Comment by mdouze** [comment]
`GpuIndex` is an abstract class, it cannot be instantiated. 

To construct concrete GPU indexes, for example `GpuIndexIVFPQ` there are two possibilities: 
- directly call the `GpuIndexIVFPQ` constructor [here](https://github.com/facebookresearch/faiss/blob/master/gpu/GpuIndexIVFPQ.h#L47)
- construct an `IndexIVFPQ`, for example with `index_factory` and call `index_cpu_to_gpu` on the result. 

Both are acceptable. Maybe the second may be easier if you want to switch to/from CPU indexes easily.

**Comment by JustinhoCHN** [comment]
@mdouze crystal clear, thanks! closed.
