### ISSUE TITLE
Actual GPU memory consumption doesn't equal to theroretical consumption.

### ISSUE THREAD

**Issue by JustinhoCHN** [facebookresearch/faiss#953]
I've done the following test, to see the GPU memory consumption.

- xb.shape: (10000000, 128)
index: ```IVF8096,SQfp16```
theroretical gpu mem: 2 * 128 * 10000000 / 1024 / 1024 / 1024 ≈ 2.3 GB
actual gpu mem: < 1.743 GB

- xb.shape: (10000000, 128)
index: ```IVF8096,Flat```
theroretical gpu mem: 4 * 128 * 10000000 / 1024 / 1024 / 1024 ≈ 4.6 GB
actual gpu mem: ≈ 5.6 GB

Besides, when I increase the xb shape to 100M (using ```IVF8096,SQfp16```), the gpu memory still remain lower than 1.7GB, I don't understand why.

Another question is, when I run ```'demos/demo_auto_tune.py'``` with my own dataset, which xb.shape = (10000000, 128), index = ```IVF8096,SQfp16``` and xq.shape = (10000, 128), auto_tune outputed the following result:
perf: 0.743, time: 2.432 (running on gpu)

2.432s to finish query, but if I build the index myself, the query time with same conditions is 0.65 seconds, why there's such gap?

Thanks everyone.

**Comment by mdouze** [comment]
I think this is because the index is not transferred to gpu at all for the scalar quantizer variant. In this specific case, please use a Flat index and request it to be converted to fp16 when transferring to GPU.

**Comment by JustinhoCHN** [comment]
yeah, you replied me at facebook faiss group, only the new GpuSQ index can be transfered to gpu.
@mdouze
