### ISSUE TITLE
Dockerfile request for benchmarking faiss-cpu

### ISSUE THREAD

**Issue by flrngel** [facebookresearch/faiss#955]
# Summary

My team is investigating unexpected performance issue with `FLATIP`, lower dimension searching is significantly slower than higher dimension (d=1792 vs d=2025). Before we issue this with reproducible code, we want to ensure if it's not a platform or compile-related problem. (We also found that there's performance difference between different source distributions with same release version)

As faiss provides `Dockerfile` which targets gpu machines (base image is `nvidia/cuda-8.0`), can we get a official Dockerfile for benchmarking faiss-cpu?

Thanks!

# Platform

OS: 
Running on:
- CPU

Interface: 
- Python

**Comment by wickedfoo** [comment]
What is the exact size of your problem (number of vectors in the IndexFlatIP index, and number of query vectors)?

Could it be the case that the N x 2025 case no longer fits into last level cache, and performance falls off a cliff? Have you tried interpolating between 1792 and 2025 to see if there is a performance cliff?

**Comment by flrngel** [comment]
HI @wickedfoo , here's our benchmark table. We didn't interpolate between 1792-2025 yet.

| DB Size | Search count | Faiss Version | Instance Type | Used memory | d=1792 | d=2025 | 
|---------|--------------|---------------|---------------|-------------|---------------------------|--------------------------| 
| 1M      | 1000         | v1.5.2        | r5.xlarge     | 14.6GB      | 0.647824494               | 0.342724457              | 
| 3M      | 1000         | v1.5.2        | r5.4xlarge    | 43.5GB      | 1.716049964               | 0.542412717              | 
| 5M      | 1000         | v1.5.2        | x1e.2xlarge   | 72.3GB      | 5.043245749               | 1.576336837              | 
| 7M      | 1000         | v1.5.2        | x1e.2xlarge   | 101.GB      | 7.026452808               | 2.448474893              |

**Comment by flrngel** [comment]
This is same to #918 and since benchmarks are not related to Dockerfile, I'm closing this issue and will open new issue about benchmarking.

**Comment by flrngel** [comment]
@wickedfoo After projection, I found that there's two way of searching, BLAS/SSE(when dimension is multiple of 4). I'm not sure when difference of SSE and BLAS, but I've got the entry point where should I look into. Thanks!
