### ISSUE TITLE
Problem when searching

### ISSUE THREAD

**Issue by Itaru7** [facebookresearch/faiss#962]
# Summary
Trying to create a program to find similar images. I was able to store features in index, but when searching from index, it gives me an error.

# Platform

OS: 

Faiss version: 

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions
There are 23 images to train.    

    dimension = 512
    quantizer = faiss.IndexFlatL2(dimension)  # this remains the same
    index = faiss.IndexIVFPQ(quantizer, dimension, 23, 32, 4) # 8 specifies that each sub-vector is encoded as 8 bits

The error is generated on this code:

    D, I = index.search(query_features, 5)

And the error message is this:

    libc++abi.dylib: libc++abi.dylib: libc++abi.dylib: terminating with uncaught exception of type 
    faiss::FaissException: Error in faiss::(anonymous namespace)::IVFPQScannerT<long long, 
    faiss::METRIC_L2>::IVFPQScannerT(const faiss::IndexIVFPQ &, const 
    faiss::IVFSearchParameters *) [IDType = long long, METRIC_TYPE = faiss::METRIC_L2] at 
    IndexIVFPQ.cpp:823: Error: 'pq.nbits == 8' failedlibc++abi.dylib: terminating with uncaught 
    exception of type faiss::FaissException: Error in faiss::(anonymous 
    namespace)::IVFPQScannerT<long long, faiss::METRIC_L2>::IVFPQScannerT(const 
    faiss::IndexIVFPQ &, const faiss::IVFSearchParameters *) [IDType = long long, METRIC_TYPE 
    = faiss::METRIC_L2] at IndexIVFPQ.cpp:823: Error: 'pq.nbits == 8' failed

    terminating with uncaught exception of type faiss::FaissException: Error in faiss::(anonymous 
    namespace)::IVFPQScannerT<long long, faiss::METRIC_L2>::IVFPQScannerT(const 
    faiss::IndexIVFPQ &, const faiss::IVFSearchParameters *) [IDType = long long, METRIC_TYPE 
    = faiss::METRIC_L2] at IndexIVFPQ.cpp:823: Error: 'pq.nbits == 8' failed

**Comment by mdouze** [comment]
Right we should do this check much earlier. 
nbits != 8 is not supported (yet) for `IndexIVFPQ`.
The fact that it is not properly reported in Python is because the exception is thrown inside an OpenMP parallel section.

**Comment by Itaru7** [comment]
I see, thank you for your replay.
I am also not sure what to put in the parameter of IndexIVFPQ. What I understand as follows:

    faiss. IndexIVFPQ(quantizer, dimension, ncentroids, code_size, n_bits)
    ncentroids <= number of data
    code_size: choose the number that can multiply dimension with no reminder && the length of 
    code_size must be 2^n
    n_bits: number of data >= n_bits where 2^n
Could you verify if it's right? If not, it would be very helpful to tell me what to put.

**Comment by mdouze** [comment]
Will be fixed in the next version of Faiss.
