### ISSUE TITLE
faiss roadmap

### ISSUE THREAD

**Issue by JinHai-CN** [facebookresearch/faiss#963]
Hello,

Faiss is a great work in ANNS. We have learned a lot from this open source library.
We are inspired to develop an open source vector database/search engine (Milvus). 
We plan to provide user the capability such as data management, cloud native deployment, intelligent processor (CPU/GPU) selection and etc.

We actually integrate the IVF index implemenation from Faiss into our system as one of the indexes. 
When we first started the work, Faiss 1.5.0 did not support IVF SQ8 index on GPU, so we have developed our own IVF SQ8 on GPU.
We just noticed Faiss will support SQ8 on GPU in 1.6.0. We are glad to see it as it means we might have similar opion in this area. 

Can you share some more info about the future plan of Faiss? Something like a roadmap.

Thanks a lot.

**Comment by mdouze** [comment]
Thanks for your interest in Faiss and for sharing details on how you use it!

In terms of roadmap, we are considering the issues annotated as "enhancement" . 
We are considering being more open about future developments.

**Comment by gujun720** [comment]
Hi Matthijs,

So far Faiss is using FP32 when calculating the distance. Do you have plan to support INT8? I am just curious if Facebook is using INT8 in the production system.

Thanks.

**Comment by mdouze** [comment]
@JinHai-CN, we don't have a clear roadmap to share, but we plan to support other distance types than inner product and L2 on GPU.

**Comment by mdouze** [comment]
Please refer to https://github.com/facebookresearch/faiss/projects/5
