### ISSUE TITLE
1R@1's result of PCA32,Flat is really excellent!!!

### ISSUE THREAD

**Issue by bazige** [facebookresearch/faiss#965]
# Summary

When I tested the recall rate of PCA32 with Deep1b dataset, I found the result to be exceptionally good, up to 0.995. The PCA8 can also achieve a result of 0.993. I feel very unbelievable, and definitely there is something wrong.

# Platform

OS: 
    Ubuntu 16.04.5 LTS
Faiss version: 
    faiss-gpu                 1.5.3

Faiss compilation options: 
    I use anaconda to install it，and conda version is
    conda version : 4.7.11
    and the command is 
    conda install faiss-gpu cudatoolkit=10.0 -c pytorch 

Running on:
- [ ] CPU
- GPU

Interface: 
- [ ] C++
- Python

# Reproduction instructions
When I tested the 1R@1 of PCA32 with Deep1b dataset, I found the result to be exceptionally good, and it up to 0.995. The PCA8 can also achieve a result of 0.993. This result is very unbelievable, and definitely there is something wrong. Since the data set of deep1b is too large and limitations of my computer's RAM, my database size is 1000000, while the training stage I use 10000000 data of learn.fevcs. Groundtruth is the index randomly generated in [0,1000000], and query data xq is taken in xb according to the groundtruth index data.

```python
database_size = 1000*1000
xt_len = 10*1000*1000
database_path = './'
xb = mmap_fvecs(database_path+'Deep1B/base.fvecs')
xt = mmap_fvecs(database_path+'Deep1B/learn.fvecs')
# xq is selected 10000 data from 1 billion database, while gt is index of xq. 
# For 1million database, these two data should be reselect.
#xq = mmap_fvecs(database_path+'Deep1B/deep1B_queries.fvecs')
#gt = ivecs_read(database_path+'Deep1B/deep1B_groundtruth.ivecs')
gt = np.random.randint(0, database_size,(10000, 1), dtype='int32')
xq = xb[gt[0][0]:gt[0][0]+1]
for i in range(1, 10000):
    s = gt[i][0]
    xq = np.concatenate((xq, xb[s:s+1]), axis=0)
xb = xb[:database_size]
xt = xt[:xt_len]
gt = gt.astype('int64')
d = xt.shape[1]
k = gt.shape[1]
```
```python
mode=='use-gpu'
keys_to_test = [
    #"Flat" # only for reference
    "PCA8,Flat"
    ]
res = faiss.StandardGpuResources()
    # step2: create index object and add data
if mode=='use-gpu':
    # if this fails, it means that the GPU version was not comp
    assert faiss.StandardGpuResources, \
        "FAISS was not compiled with GPU support, or loading _swigfaiss_gpu.so failed"
    res = faiss.StandardGpuResources()  # use a single GPU
    

for index_key in keys_to_test:
    print("============ key[{0}] @database[{1}] processing...".format(index_key, xb.shape[0]))

    # make the index described by the key
    index = faiss.index_factory(d, index_key)
    
    if mode == 'use-gpu':
        index = faiss.index_cpu_to_gpu(res, device_id, index)
    
    if index_key!='Flat':
        index.train(np.ascontiguousarray(xt))

    index.add(np.ascontiguousarray(xb))

    # new added 
    print('\t' + 'R@1     R@10    R@100      time    %pass')
    ts = time.time()
    D, I = index.search(np.ascontiguousarray(xq), 100)
    te = time.time()
    pdb.set_trace()
    for rank in 1, 10, 100:
        n_ok = (I[:, :rank] == gt[:, :1]).sum()
        print"\t%.4f" % (n_ok / float(xq.shape[0])),
    print"%8.3f  " % ((te - ts) * 1000.0 / xq.shape[0])
```

**Comment by bazige** [comment]
while PCA8, Flat 1R@1 results of Flat also reached 0.992

**Comment by mdouze** [comment]
There is a bug. Please check your code again.

**Comment by bazige** [comment]
I checked the code again and found no bugs. May i have your help to tell me where the problem is?

**Comment by bazige** [comment]
> There is a bug. Please check your code again.



> while PCA8, Flat 1R@1 results of Flat also reached 0.992



> I checked the code again and found no bugs. May i have your help to tell me where the problem is?

**Comment by bazige** [comment]
> There is a bug. Please check your code again.

I checked the code again and found no bugs. May i have your help to tell me where the problem is?
