### ISSUE TITLE
FAISS for camera surveillance

### ISSUE THREAD

**Issue by jimd6776** [facebookresearch/faiss#968]
Hi,

I would like to ask if faiss can implement a camera surveillance application whether it is a human detection or image recognition. What are the common applications in this field using faiss algorithm? How one can apply specifically IVFFlat to implement this and is there a dataset that I can test?

Thanks in advance.

**Comment by mdouze** [comment]
This question is about a whole system, with a CV component etc. It is out of scope for the pure Faiss library.
