### ISSUE TITLE
Residual memory grows significantly faster during frequent inserts than it should

### ISSUE THREAD

**Issue by sgjurano** [facebookresearch/faiss#969]
# Summary

Hi!

My system uses multiple small inserts, typical batch size is between 10 and 1000 vectors.
150k vectors were added over 10 hours, about 20 inserts per minute, but memory consumption grew by as much as 2.8Gb, which is a lot more than I expected.

Restarting the application helps to restore memory consumption to the expected value, but it doesn't last.

I am trying to find a memory leak in my code, but I haven't been successful so far.
Is it normal for the index to behave like that?

My index is IVF52428_HNSW32,PQ64. it's about ~130kk vectors 128d.

This is the method I'm using:
`index.add_with_ids(vectors, ids)`

# Platform

OS: 

Faiss version: 
1.5.3

Faiss compilation options: 

Running on:
- [x] CPU
- [ ] GPU

Interface: 
- [ ] C++
- [x] Python

# Reproduction instructions

**Comment by mdouze** [comment]
So you start from 130k vectors and grow to 130k+150k vectors by batches of say 100, correct?
Did you observe the same memory blow up when making a simple loop that adds random vectors without your application-level code?

**Comment by mdouze** [comment]
I tried it
https://gist.github.com/mdouze/3e599afe88f4b49feadde4ae50a539f1
it adds ~118 bytes per vector, which is more than the theoretical 64+8 bytes but much less than what you observe.

**Comment by sgjurano** [comment]
I couldn't use your code example, what versions of python, faiss and numpy do you use?
I have `Python 3.7.2
faiss==1.5.3
numpy==1.17.2`

I did the tests on 40_000_000 vectors and it shows:
In-app test:
`n_elems=40000000, mem_MiB=3656.43, bytes_per_vector=96`

Loop test:
`index size 40000000, mem usage 3077.77 MiB, 80 bytes per vector`

As I see, the faiss.get_mem_usage_kb() method just reading /proc/$pid/status file, so memory leak exists, and nothing more.

When I comment only the line `index.add_with_ids(vectors, ids)`, then memory growth stopping.
May be it's a version-specific artifact? Somebody forgot to decref something :)

**Comment by sgjurano** [comment]
I've finally found memory leak on my side, thank you for your advice about bytes per vector measurements!

**Comment by gtmtg** [comment]
@sgjurano I think I'm facing the same issue - do you remember where your memory leak was? (and specifically why it wasn't in FAISS but went away when you commented the `add_with_ids` line?)
