### ISSUE TITLE
how to Scope search? Like sql between.eg: ids between 100 to 1000.

### ISSUE THREAD

**Issue by AmierCheng** [facebookresearch/faiss#977]
how to Scope search? Like sql between.eg: ids between 100 to 1000. If faiss so, how to use it? If no，Will it be supported later?

We hope that our questions will be answered by the relevant developers in time, so as to make it stronger.

**Comment by mdouze** [comment]
See this FAQ entry: 
https://github.com/facebookresearch/faiss/wiki/FAQ#is-it-possible-to-dynamically-exclude-vectors-based-on-some-criterion
