### ISSUE TITLE
How to search similar image in the index of 10 millions of CNN features 

### ISSUE THREAD

**Issue by mengk007** [facebookresearch/faiss#98]
I generated 10 million of CNN features for lots of images (512 dimensions)，and created indexes in the Faiss, but when I load indexes and search one similar image,  it is out of memory by Python.

Is there any one have encountered such a problem? Could you give me some sample codes?

**Comment by mdouze** [comment]
Hi

Please be more specific. Is it with a GPU index? What type of index did you use?

**Comment by mengk007** [comment]
CPU only, we are going to apply GPU env. IVFFlat index.
Thank you for your reply!

**Comment by mdouze** [comment]
Closing this issue. Re-open if you have more questions.
