### ISSUE TITLE
make test_gpu: TestShardedFlat fails for 1 GPU

### ISSUE THREAD

**Issue by drydenb** [facebookresearch/faiss#982]
# Summary

`make test_gpu` fails if I have 1 GPU due to the TestShardedFlat test case where it asserts that the number of GPUs should be greater than 1. 

Does Faiss require more than 1 GPU to function as expected?

OS: Ubuntu 16.04

Faiss version: 31393764cccb3ae94e8a604e1fd891b331c46221

Faiss compilation options: 

Running on:
- [ ] CPU
- [X] GPU

Interface: 
- [ ] C++
- [X] Python

# Reproduction instructions

`make test_gpu` where you have 1 GPU. Line 224, `assert faiss.get_num_gpus() > 1` in `test_gpu_index.py` of course fails.

**Comment by mdouze** [comment]
No Faiss works fine with 1 GPU. This test should just be disabled when run with a single GPU (or 1 cuda visible device).

**Comment by mdouze** [comment]
TODO: disable this test when only 1 GPU is available.
