### ISSUE TITLE
cuda8 gpu compile error

### ISSUE THREAD

**Issue by 5ace** [facebookresearch/faiss#986]
# Summary

# Platform

OS: CentOS Linux release 7.3.1611 (Core)

Faiss version:  31393764cccb3ae94e8a604e1fd891b331c46221

Faiss compilation options: /usr/local/cuda-8.0/bin/nvcc -I /usr/local/cuda-8.0/targets/x86_64-linux/include/ -Xcompiler -fPIC -Xcudafe --diag_suppress=unrecognized_attribute -gencode=arch=compute_35,code=compute_35 -gencode=arch=compute_52,code=compute_52 -gencode=arch=compute_60,code=compute_60 -gencode=arch=compute_61,code=compute_61  -lineinfo -ccbin g++ -std=c++11 -DFAISS_USE_FLOAT16 -I. -g -O3 -c gpu/GpuIndexIVFScalarQuantizer.cu -o gpu/GpuIndexIVFScalarQuantizer.o

Running on:
- [ ] CPU
- [* ] GPU

Interface: 
- [ *] C++
- [ ] Python

# error info:
./faiss/gpu/impl/GpuScalarQuantizer.cuh(162): error: function "faiss::gpu::Convert<half, float>::operator()" cannot be called with the given argument list
            argument types are: (unsigned int)
            object type is: faiss::gpu::Convert<half, float>

./faiss/gpu/impl/GpuScalarQuantizer.cuh(163): error: class "__half2" has no member "y"

./faiss/gpu/impl/GpuScalarQuantizer.cuh(180): error: no suitable conversion function from "half" to "unsigned int" exists

./faiss/gpu/impl/GpuScalarQuantizer.cuh(181): error: class "__half2" has no member "y"

4 errors detected in the compilation of "/tmp/tmpxft_0000457c_00000000-13_GpuIndexIVFScalarQuantizer.compute_61.cpp1.ii".
make: *** [gpu/GpuIndexIVFScalarQuantizer.o]

**Comment by beauby** [comment]
@5ace Could you try https://github.com/facebookresearch/faiss/pull/987 ?

**Comment by 5ace** [comment]
> @5ace Could you try #987 ?

It solved, thx

**Comment by daisyhaohao** [comment]
> > @5ace Could you try #987 ?
> 
> It solved, thx
I have the same problem. How did you solve it ?
