### ISSUE TITLE
Unofficial faiss bindings

### ISSUE THREAD

**Issue by xolott** [facebookresearch/faiss#996]
Is there a possibility that you can include a page with unofficial binding projects in other languages?

Like @Enet4 project in [Rust](https://github.com/Enet4/faiss-rs).
Or my own on [.NET Core 3.0](https://gitlab.com/josetruyol/faisssharp)

**Comment by mdouze** [comment]
Good idea. 
I added a page: https://github.com/facebookresearch/faiss/wiki/Related-projects

**Comment by xolott** [comment]
Thanks!
Closing issue!
